### ISSUE TITLE
Final example missing getter

### ISSUE THREAD

**Issue by gerbercj** [dart-lang/site-www#1012]
The final example on the page has all of the code, except for this line:
`int get speed => _speed;`

Reference: https://codelabs.developers.google.com/codelabs/from-java-to-dart/#1

**Comment by chalin** [comment]
Which page?

**Comment by kwalrath** [comment]
Thanks very much for the report, @gerbercj.

**Comment by kwalrath** [comment]
Fixed in https://codelabs.developers.google.com/codelabs/from-java-to-dart/#1 and the DartPad it links to, https://dartpad.dartlang.org/a81cf6bde4d52bb8b774d87aff842b56.
