### ISSUE TITLE
Finding the SDK zip file on the website involves so many pages

### ISSUE THREAD

**Issue by DanTup** [dart-lang/site-www#102]
I've reported this before (many years ago) and it was improved, but on the current site it seems worse than before. I always use the SDK zip file and just unzip it to a folder on my machine that's in PATH.

To get to the SDK Zip file from the homepage, here's the steps:

1. Go to dartlang.org
1. Click "Tools"
1. Optional: Click the "SDK" link which just jumps down the page
1. Click "Install Dart" (if you click "Dart SDK" as I did, you actually end up with an extra step!)
1. Click "Installing Dart on Windows"
1. Click "installing Dart manually"

Compare this to node (which is far from perfect, but doesn't feel like a maze):

1. Go to nodejs.org
1. Click "Other Downloads"

There's not a hude difference between Node and Dart in terms of platforms so it seems like this could be significantly simplified. I feel like I'm being trolled when I try to download Dart and wonder if I'm going in circles! Why the homepage can't have a link to a downloads page that just has all downloads on it?

**Comment by Sfshaza** [comment]
@DanTup, it's now two clicks to get to the zip files. "Install Dart" on the front page, and then "Download zip files" from that page. I'm closing this but please re-open if you have further feedback.

**Comment by DanTup** [comment]
@Sfshaza Much better!

Slightly off-topic but I think the "Get Started" and "Install Dart" buttons would be much better if they stood out a little more - seems like they're main attractions for this page but the whole page is kinda grey!

![Current](https://cloud.githubusercontent.com/assets/1078012/18390721/534e16be-76a3-11e6-8554-941e1973e30d.png)

![Tweaked](https://cloud.githubusercontent.com/assets/1078012/18390734/5693e236-76a3-11e6-8f14-4365db7249ee.png)

**Comment by Sfshaza** [comment]
@filiph

**Comment by filiph** [comment]
One of the earlier feedback was that they were too bright, so I dimmed them. :)

But I have a slight redesign of the homepage in my TODO list, so I'm adding this. We'll iterate until we're somewhat acceptable for most users.

**Comment by DanTup** [comment]
Heh; can't please everyone! :D

**Comment by Sfshaza** [comment]
Thanks for weighing in, Filip! I'm considering this issue well and truly closed.  ;)
