### ISSUE TITLE
Document Flutter SDK constraints

### ISSUE THREAD

**Issue by nex3** [dart-lang/site-www#103]
In Dart 1.19, pub is adding support for Flutter SDK constraints (see dart-lang/pub#1432). These constraints go under the `environment` key in pubspecs like so:

```yaml
environment:
  sdk: ">=1.19.0 <2.0.0"
  flutter: "^0.1.2"
```

A Flutter SDK constraint will only be satisfied if Pub is running in the context of the `flutter` executable, and the Flutter SDK's `version` file matches the given version constraint. Otherwise, the package will not be selected.

In order to publish a package with a Flutter SDK constraint, it must also have a Dart SDK constraint whose minimum version is at least `1.19.0` (technically pre-release versions will also work, but that won't be relevant after 1.19 releases). This ensures that older versions of pub won't accidentally install packages that need Flutter.

**Comment by kwalrath** [comment]
This affects https://www.dartlang.org/tools/pub/pubspec, where **environment** and perhaps **sdk** are mentioned.

cc @Sfshaza
