### ISSUE TITLE
'Effective Dart: Design' question about "PREFER annotating with dynamic instead of letting inference fail."

### ISSUE THREAD

**Issue by patlillis** [dart-lang/site-www#1032]
From URL: https://www.dartlang.org/guides/language/effective-dart/design

Effective Dart says "PREFER annotating with dynamic instead of letting inference fail.". However, it is extremely common for Dart users to use a single untyped underscore for function parameters they don't care about:

```dart
someStream.listen((_) => print('Something happened.'));
```

Following this Effective Dart guideline, this should be written as: 

```dart
someStream.listen((dynamic _) => print('Something happened.'));
```

which makes the "single underscore" convention much less terse and therefore less attractive.

Not sure if it's worth calling this case out in Effective Dart, or if this is just one more reason why this guideline is only "PREFER". Just wanted to bring it to someone's attention.

**Comment by munificent** [comment]
> However, it is extremely common for Dart users to use a single untyped underscore for function parameters they don't care about:

That's true, but those unused parameters are typically correctly inferred too, so they don't usually run afoul of this guideline.
