### ISSUE TITLE
Codelabs DartPad example uses wrong PI constant

### ISSUE THREAD

**Issue by roancoetzee** [dart-lang/site-www#1036]
In this example [Create a factory](https://codelabs.developers.google.com/codelabs/from-java-to-dart/index.html?index=..%2F..%2Findex#3) the following [DartPad](https://dartpad.dartlang.org/56381ac0a35594844919150039dcf214) example uses the `PI` constant from Dart 1.x when it should be using `pi` from Dart 2

Snippet from the tutorial itself
`In Dart 1.x, core library constants were uppercase (PI); in Dart 2, they're lowercase (pi).`

**Comment by chalin** [comment]
Thanks for pointing that out!

**Comment by kwalrath** [comment]
Fixed. It looks like when I updated the codelab, I missed one of the links in the page. Thanks for the report, @roancoetzee!
