### ISSUE TITLE
Library tour:"The following examples use the prefix math to make clear which top-level functions and constants are from the Math library:"

### ISSUE THREAD

**Issue by amisare** [dart-lang/site-www#1039]
The description says that there is a ‘math’ prefix at function.
but new version examples does not have prefix.
it makes  confused.

**Comment by chalin** [comment]
Thanks for the issue! The `as math` was dropped following this comment https://github.com/dart-lang/site-www/pull/480/commits/6697439b50023a3ca5c34223a8589e3098d67a77#r157355550. I'll drop the corresponding phrase in the prose.
