### ISSUE TITLE
Document SDK dependencies

### ISSUE THREAD

**Issue by nex3** [dart-lang/site-www#104]
Dart 1.19 is adding support for a new source, called `sdk` (see dart-lang/pub#1431). The general idea is that this source can be used for any SDKs that are shipped along with packages, which may themselves have dependencies. However, Flutter is the only SDK that's supported right now.

The syntax looks like this:

```yaml
dependencies:
  flutter_driver:
    sdk: flutter
    version: ^0.0.1
```

The identifier after `sdk` indicates which SDK the package comes from. If it's `flutter`, the dependency is satisfiable as long as:

* pub is running in the context of the `flutter` executable,
* the Flutter SDK contains a package with the given name,
* and that package's version matches the version constraint.

If it's an unknown identifier, the dependency is always considered unsatisfied.

In order to publish a package with an `sdk` dependency, it must have a Dart SDK constraint whose minimum version is at least `1.19.0` (technically pre-release versions will also work, but that won't be relevant after 1.19 releases). This ensures that older versions of pub won't accidentally install packages that need SDK dependencies.

**Comment by kwalrath** [comment]
Affects https://www.dartlang.org/tools/pub/dependencies.

cc @Sfshaza
