### ISSUE TITLE
Travis build is failing due to linkchecking

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1051]
For example see this Travis log: https://travis-ci.org/dart-lang/site-www/jobs/411906465. The good news is that the build still gets deployed. At first glance, it isn't obvious what is causing the link checking to fail.

The source of the problem is actually `superstatic` (and `firebase-tools`): see https://github.com/firebase/superstatic/issues/260 and https://github.com/firebase/firebase-tools/issues/876.

**Comment by chalin** [comment]
(This is also affecting site-webdev.)

**Comment by amisare** [comment]
Here may some useful information.

I fork the project, and followed the readme as follows:

- source ./scripts/env-set.sh
- ./scripts/before-install.sh
- ./scripts/install.sh
- ./scripts/serve.sh

Visit site: http://localhost:4000

![image](https://user-images.githubusercontent.com/6335968/43903973-33304b78-9c20-11e8-8c90-e80d68a7fe29.png)

**Comment by chalin** [comment]
The source of the problem is actually `superstatic` (and `firebase-tools`): see https://github.com/firebase/superstatic/issues/260 and https://github.com/firebase/firebase-tools/issues/876.
