### ISSUE TITLE
Update pub docs: --checked -> --enable-asserts

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1059]
See https://github.com/dart-lang/pub/pull/1964

**Comment by kwalrath** [comment]
Affected files:

src/_articles/dart-vm/benchmarking.md
src/tools/pub/cmd/pub-run.md

**Comment by chalin** [comment]
Related: https://github.com/flutter/website/pull/1191, in particular this comment: https://github.com/flutter/website/pull/1191#pullrequestreview-149994598.

**Comment by kwalrath** [comment]
But first, make sure that `--enable-asserts` is in a dev/stable release (and, if possible, add some info about when it changed.)

**Comment by kwalrath** [comment]
Currently, https://www.dartlang.org/tools/pub/cmd/pub-run says `$ pub run [--mode=<mode>] [--checked] <executable> [args...]

I'll remove `--mode` and `--checked`, and add `--enable-asserts`.

**Comment by chalin** [comment]
```console
$ pub run -h
Run an executable from a package.

Usage: pub run <executable> [args...]
-h, --help                   Print this usage information.
    --[no-]enable-asserts    Enable assert statements.
```

Given that `--no-enable-asserts` is supported, it can make one wonder what the flag's default is. It would be good to document the default.

**Comment by chalin** [comment]
In #1255, you've written:

```console
$ pub run [--enable-asserts] <executable> [args...]
```

which, at least to me, makes it clear that the default is that asserts are _not_ enabled. (Maybe the command flag's help needs to be tweaked to specify a default?)
