### ISSUE TITLE
Give more details about using const

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1061]
In https://github.com/dart-lang/site-www/issues/972#issuecomment-401157777 @munificent wrote:

> const is an important performance *improvement* on Flutter, but can be a perf *hit* on the web

There should be some mention of the hidden costs of using `const` for each of the three platforms. Maybe this is another candidate topic for the "advanced language features" guide.

**Comment by kwalrath** [comment]
Also see dart-lang/sdk#34669, which points to some confusion people have about const constructors and const in general.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/4350 to consolidate issues related to `const` in the language tour. Thanks!
