### ISSUE TITLE
Async articles are out of date / wrong

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1070]
_From @MichaelRFairhurst on August 10, 2018 17:15_

This gives a lot of no longer accurate advice:

https://www.dartlang.org/tutorials/language/futures

See a confused user here: https://www.reddit.com/r/dartlang/comments/965b8u/async_in_dart/?utm_content=full_comments&utm_medium=message&utm_source=reddit&utm_name=frontpage

Not sure who to ping: @kwalrath @chalin @munificent or if ithis is the right repo for this issue

_Copied from original issue: dart-lang/sdk#34123_

**Comment by chalin** [comment]
_From @kwalrath on August 10, 2018 17:20_

Actually, I mistakenly thought this was in dart-lang/site-www... which would be the right repo. You can report an issue on any page by clicking the BUG icon at the upper right of the page.

**Comment by kwalrath** [comment]
@MichaelRFairhurst would you be willing to review/edit this page? Would it be possible for you to create gists for what the code should be? (Or if not you, who'd be good?)

**Comment by MichaelRFairhurst** [comment]
I think Bob or Florian would be best able?

I can try to make an edit to get the process started, though....

**Comment by MichaelRFairhurst** [comment]
@munificent?

**Comment by munificent** [comment]
Oof, I don't think I have bandwidth for it any time soon. :(
