### ISSUE TITLE
Bad URL: https://www.dartlang.org/dart2js-reflection

### ISSUE THREAD

**Issue by whesse** [dart-lang/site-www#108]
URL: https://www.dartlang.org/dart2js-reflection
Expected page: 
  A page explaining how to do reflection in dart2js, especially about not using dart:mirrors.

There is a warning message emitted by the compiler (in this case, when building observatory when building the dart runtime), that reads:

****************************************************************
* WARNING: dart:mirrors support in dart2js is experimental,
*          and not recommended.
*          This implementation of mirrors is incomplete,
*          and often greatly increases the size of the generated
*          JavaScript code.
*
* Your app imports dart:mirrors via:
*   index.bootstrap.dart => package:observatory => dart:mirrors
*   main.dart => package:observatory => dart:mirrors
*   index.web_components.bootstrap.dart => package:observatory => dart:mirrors
*   index.html.polymer.bootstrap.dart => package:observatory => dart:mirrors
*
* You can disable this message by using the --enable-experimental-mirrors
* command-line flag.
*
* To learn what to do next, please visit:
*    http://dartlang.org/dart2js-reflection
****************************************************************

So the URL given in this warning should be a valid page.

**Comment by kwalrath** [comment]
Thanks for the report, Bill!

Looking at the old redirector.py file, /dart2js-reflection redirected to https://code.google.com/p/dart/issues/detail?id=21654, which itself redirects to https://github.com/dart-lang/sdk/issues/21654. I'll make sure this redirect is reinstated on the new site.

**Comment by filiph** [comment]
Fixed with https://github.com/dart-lang/site-www/commit/b710c9a46dfc2ab8af30ef7748319ea5de640f74
