### ISSUE TITLE
Issue for SuperMixins: Documentations

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/site-www#1086]
**What:** Issue for implementation for Analyzer

**FYI on Code ETA :** 10/15 in Dart Repo. 

**For:** [SuperMixins Implementation]( https://github.com/dart-lang/language/blob/master/accepted/super-mixins.md) and [strawman documentation](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) 

**Meta Issue:** This is subsumed under the [Super Mixins Meta Issue in the Language Repo](https://github.com/dart-lang/language/issues/12)

**Comment by kwalrath** [comment]
Currently, the only thing we could do (not urgent, maybe not even desirable) is update the spec links in the following docs:

https://www.dartlang.org/guides/language/language-tour#adding-features-to-a-class-mixins
https://www.dartlang.org/articles/language/mixins

They currently link to https://github.com/dart-lang/sdk/blob/master/docs/language/informal/mixin-declaration.md, which says that the canonical version of the document is now at https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md.

**Comment by kwalrath** [comment]
The two links listed in the previous comment have been updated.
