### ISSUE TITLE
Small "Dart by example" issues

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/site-www#109]
On https://www.dartlang.org/dart-vm/dart-by-example we see the following example
>
```
main() async {
  var url = 'http://www.google.com/';
  var client = new http.Client();
  try {
    var response = await client.get('${url}/search');
    printResponseBody(response);
    response = await client.get('${url}/doodles');
    printResponseBody(response);
  } finally {
    client.close();
  }
}
```

whereas on https://www.dartlang.org/guides/language/effective-dart/usage we have the "rule"
>
AVOID using curly braces in interpolation when not needed.
If you’re interpolating a simple identifier not immediately followed by more alphanumeric text, the {} should be omitted.
```
'Hi, $name!'
"Wear your wildest $decade's outfit."
'Wear your wildest ${decade}s outfit.'
'Hi, ${name}!'
"Wear your wildest ${decade}'s outfit."
```

It should probably be either "${url}search" (resulting in google.com/search) or "$url/search" (resulting in google.com//search (as the current example, but at least adhering to the style guide). (Equivalent for the doodles example).

Next we have
> Handling errors when making a request
An HTTP request may return a response, or it may generate an error.
```
import 'package:http/http.dart' as http;
handleSuccess(http.Response response) {
  print('something went wrong');
  print(response.body);
}
handleFailure(error) {
  print('Something went wrong.');
  print(error.message);
}
main() async {
  try {
    var response = await http.get("http://some_bogus_website.org");
    handleSuccess(response);
  } catch (e) {
    handleFailure(e);
  }
}
```

where the
```
handleSuccess(http.Response response) {
  print('something went wrong'); // <=== !!!
```
hardly seems right.

Finally,

>Identifying the operating system
Use Platform.operatingSystem to get the operating system as a String. Or, use the isMacOS, isAndroid, isLinux, and isWindows static getters defined in Platform.

mentions everything but "isIOS" which could probably be added to the list...

**Comment by kwalrath** [comment]
Good points. Thanks for the feedback!

**Comment by Sfshaza** [comment]
Fixed.

**Comment by kwalrath** [comment]
Just for the record, it looks like another PR has the same fix: https://github.com/dart-lang/dart-samples/commit/b12098ffc51b8cf989f7eeae277aa7dbcc9507c4
