### ISSUE TITLE
Unpin firebase-tools and superstatic

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1091]
- Original failure: Travis build is failing due to linkchecking #1051
- Pinning PR used to reinstate link checking #1089
- Issues:
  - https://github.com/firebase/superstatic/issues/260
  - https://github.com/firebase/firebase-tools/issues/876.

**Comment by chalin** [comment]
I've been able to unpin firebase-tools, but not superstatic yet.

**Comment by chalin** [comment]
To be clear, we can unpin firebase-tools if used for deploying only, not for serving.

**Comment by kwalrath** [comment]
@chalin & @filiph, does this still need to happen?

**Comment by chalin** [comment]
The versions of these two tools are no longer pinned, ever since stopped using the `before-install.sh` script to fetch and globally install the tools (we now install local copies via npm install).
