### ISSUE TITLE
Update VS Code logo

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1096]

**Comment by richa031** [comment]
what has to be done here?

**Comment by kwalrath** [comment]
The logo in https://www.dartlang.org/tools#ides-and-editors is apparently old:

![image](https://user-images.githubusercontent.com/2164483/51780149-0cfa0680-20c1-11e9-9c91-83a87e15dc1d.png)

Looking at the page source, it uses the image path `{% asset tools/vscode.png @path %}`, which resolves to https://github.com/dart-lang/site-www/blob/master/src/_assets/image/tools/vscode.png.

I think the task is to find an up-to-date version of the Visual Studio Code logo that is the right size, and replace the existing logo with it. I think SVG should be fine.

**Comment by richa031** [comment]
can i work on this issue?

**Comment by kwalrath** [comment]
Sorry, I missed your comment. Yes, please, @richa031!

**Comment by richa031** [comment]
Richa@DESKTOP-D0TNMAR MINGW64 ~/Desktop/site-www-master (master)
$ git push -u origin branch1
error: src refspec branch1 does not match any.
error: failed to push some refs to 'origin'

Richa@DESKTOP-D0TNMAR MINGW64 ~/Desktop/site-www-master (master)
$ git push -u origin master
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Richa@DESKTOP-D0TNMAR MINGW64 ~/Desktop/site-www-master (master)
$ git push origin master
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
![screenshot 104](https://user-images.githubusercontent.com/32764563/52293399-bf24ae80-299c-11e9-8db2-3aec0ba6cff6.png)

**Comment by kwalrath** [comment]
Can you push to your repo, not ours? You should still be able to make a PR.

**Comment by richa031** [comment]
ohhk i'll try
