### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by adaojunior** [dart-lang/site-www#110]
URL: https://www.dartlang.org/docs/spec/deferred-loading
Expected page: I could not find the page

The broken link is here: http://news.dartlang.org/2014/08/dart-16-adds-support-for-deferred.html

**Comment by kwalrath** [comment]
The URL should now be https://www.dartlang.org/guides/language/language-tour#deferred-loading.

**Comment by kwalrath** [comment]
Fix in progress...

**Comment by kwalrath** [comment]
Confirmed that https://www.dartlang.org/docs/spec/deferred-loading.html now redirects correctly.
