### ISSUE TITLE
Image assets: add back default image dimension attributes

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1103]
Jekyll-assets used to, by default, add image dimension and `alt` attributes, e.g.:

```diff
- <p><img src="/assets/guides/avoid-empty-statements.png" width="251" height="108" alt="guides/avoid-empty-statements.png"></p>
+ <p><img src="/assets/guides/avoid-empty-statements.png"></p>
```

Consider adding these back.

**Comment by kwalrath** [comment]
I don't know about image dimensions, but a pass to add real, handwritten `alt` attributes would probably be much more useful to people who can't see the images.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/bcbff3ea28c25a6d2fb44b2e5e3b761c704a4a7f
