### ISSUE TITLE
Make it easier to copy-paste commands

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1105]
Feedback from a user of https://webdev.dartlang.org/guides/get-started:

> It was hard to copy-paste from the console instructions. I think some of our other pages have some fix so that the selection doesn’t include the `>` character.

/cc @mit-mit

**Comment by chalin** [comment]
Yes, the plan is to make use of all of tri-site tricks once the shared infrastructure lands. Thanks for opening this issue to track that particular improvement made to the Flutter site but not yet used here (or on webdev).

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/3846 where I plan to tackle this alongside some of the other work.
