### ISSUE TITLE
Linkcheck intermittently failing when accessing main.css

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1107]
E.g., see https://travis-ci.org/dart-lang/site-www/jobs/421216035:

```nocode
http://localhost:4000/
- (31:2) <link> => http://localhost:4000/assets/main-293ea365996dfb8532618fa8e602517fdbf7144b2fec92634f87542c04e7deb3.css (connection failed)
- (31:2) <link> => http://localhost:4000/assets/main-293ea365996dfb8532618fa8e602517fdbf7144b2fec92634f87542c04e7deb3.css (connection failed)
http://localhost:4000/articles
- (31:2) <link> => http://localhost:4000/assets/main-293ea365996dfb8532618fa8e602517fdbf7144b2fec92634f87542c04e7deb3.css (connection failed)
- (31:2) <link> => http://localhost:4000/assets/main-293ea365996dfb8532618fa8e602517fdbf7144b2fec92634f87542c04e7deb3.css (connection failed)
http://localhost:4000/articles/dart-vm
- (31:2) <link> => http://localhost:4000/assets/main-293ea365996dfb8532618fa8e602517fdbf7144b2fec92634f87542c04e7deb3.css (connection failed)
- (31:2) <link> => http://localhost:4000/assets/main-293ea365996dfb8532618fa8e602517fdbf7144b2fec92634f87542c04e7deb3.css (connection failed)
...
```

**Comment by chalin** [comment]
@filiph - now that we're using linkcheck for flutter/website, I've started seeing this issue there too; e.g. https://travis-ci.org/flutter/website/jobs/427283321. /cc @Sfshaza 

Note that it _could_ be a **firebase issue**. Any idea what might be causing the **connection failures**, or do you have suggestions for how to debug it?

Maybe linkcheck needs a "retry" option?

**Comment by chalin** [comment]
Btw, I can't reproduce this intermittent failure locally. No, I haven't tried running with `--verbose` on Travis, I'm worried that it might generate too much output. WDYT?

> Was there a change in the asset pipeline?

Yes, but the issue does not arise locally.

> Is that file generated?

Yes.

> Can you access that URL from the browser?

Yes.

**Comment by filiph** [comment]
Ok, I have a speaking engagement later today so not sure I get to this, but I'm going to [run travis in Docker locally](https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e) and see if I can inspect this better.

@chalin, can you point me to the recent change in the asset pipeline?

**Comment by chalin** [comment]
>  I'm going to run travis in Docker locally and see if I can inspect this better.

Good idea.

> point me to the recent change in the asset pipeline?

The change in the asset pipeline for www was to upgrade the jekyll-assets v3 (#1098). On flutter.io, we introduced use of jekyll-assets v3.

Just a reminder that there have be significant changes on the firebase side of things -- e.g., locally, we are [pinned to old versions](https://github.com/dart-lang/site-www/blob/2e22820f46d3c6a21c97dc2137d0e6274f74e32e/package.json#L11-L12) of `firebase-tools` and `superstatic` because the most recent versions cause problems. So maybe (part) of the cause is with firebase/superstatic?

Also, I'm just wondering if linkcheck might benefit from a retry feature, to retry a get after a communication failure?

**Comment by kwalrath** [comment]
Is this still an issue?

**Comment by chalin** [comment]
The short answer is yes.

I added a skip rule to `tool/config/linkcheck-skip-list.txt` so that main CSS files are ignored. If I comment out that rule I now get the following error:

```console
$ pub run linkcheck --skip-file ./tool/config/linkcheck-skip-list.txt :4002 (logging to /Users/chalin/tmp/linkcheck-log.txt)
Crawling...
Unhandled exception:
NoSuchMethodError: Class 'int' has no instance getter 'name'.
Receiver: 0
Tried calling: name
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _Parser.processSelectorExpression (package:csslib/parser.dart:1736:51)
#2      _Parser.processPseudoSelector (package:csslib/parser.dart:1649:20)
#3      _Parser.simpleSelectorTail (package:csslib/parser.dart:1590:16)
#4      _Parser.simpleSelector (package:csslib/parser.dart:1533:14)
#5      _Parser.simpleSelectorSequence (package:csslib/parser.dart:1445:11)
#6      _Parser.processSelector (package:csslib/parser.dart:1363:26)
#7      _Parser.processSelectorGroup (package:csslib/parser.dart:1343:27)
#8      _Parser._nestedSelector (package:csslib/parser.dart:1177:30)
#9      _Parser.processDeclarations (package:csslib/parser.dart:1205:27)
#10     _Parser.processRule (package:csslib/parser.dart:1129:26)
#11     _Parser.parse (package:csslib/parser.dart:214:20)
#12     parse (package:csslib/parser.dart:103:36)
#13     parseCss (package:linkcheck/src/parsers/css.dart:29:17)
#14     checkPage (package:linkcheck/src/worker/worker.dart:162:12)
<asynchronous suspension>
#15     worker.<anonymous closure> (package:linkcheck/src/worker/worker.dart:192:29)
<asynchronous suspension>
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#26     _StreamController._add (dart:async/stream_controller.dart:639:7)
#27     _StreamController.add (dart:async/stream_controller.dart:585:5)
#28     _StreamSinkWrapper.add (dart:async/stream_controller.dart:858:13)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#30     CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#35     _StreamController._add (dart:async/stream_controller.dart:639:7)
#36     _StreamController.add (dart:async/stream_controller.dart:585:5)
#37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
...
```

cc @filiph

**Comment by parlough** [comment]
At least the issue resulting in that stack trace doesn't seem to occur anymore, appearing to be fixed in https://github.com/filiph/linkcheck/commit/011ce655653c0f94bb6f522ef92f486fc835a513

The connection failed issue is still occurring though, even with the switch to GitHub actions.

**Comment by atsansone** [comment]
Issue appears resolved. No further investigation warranted. Closing issue.
