### ISSUE TITLE
Site pages: subheaders no longer show link on hover, and TOC has no subheadings

### ISSUE THREAD

**Issue by patlillis** [dart-lang/site-www#1109]
From URL: https://www.dartlang.org/guides/language/effective-dart/style (and all other Effective Dart pages).

Steps to reproduce:

1) Go to https://www.dartlang.org/guides/language/effective-dart/style
2) Scroll to "DO name types using UpperCamelCase." rule.
3) Hover over "DO name types using UpperCamelCase." header

EXPECTED:
A link button should be shown that, when clicked, either updates the URL to point to that specific rule, or copies that rule's URL into the clipboard.

ACTUAL:
No link button is shown.

**Comment by chalin** [comment]
Sorry about that temporary inconvenience. It is a side effect of a workaround for something else.

**Comment by patlillis** [comment]
Cool, thanks. Only a minor inconvenience :)
