### ISSUE TITLE
Article generation breaks when `date:` is in the future

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1111]
[This change](https://github.com/dart-lang/site-www/pull/1110/commits/80b8cb5b7fefbc01c022cc3d220b5014636209b0) seems to make `/articles/libraries/dart-io` valid. When I had a date in the future, the page wasn't generated. See #1110 for more context.

**Comment by filiph** [comment]
FWIW, I think this is indeed WAI. The date feature is there for scheduling posts. I think there's a way to disable the behavior in Jekyll.

**Comment by kwalrath** [comment]
Makes sense, but yeah, I'd like to disable this behavior. Or at the very least have an easily spottable notification. (I made a bunch of changes at the same time, so it took me a while to figure out that this is the one that stopped the page from being generated.)

**Comment by kwalrath** [comment]
Yes, please, `future: true` would be helpful. Thanks!
