### ISSUE TITLE
Update `void` guidance

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1117]
https://medium.com/dartlang/dart-2-legacy-of-the-void-e7afb5f44df0 has good recommendations that we should reflect/mention in the language tour. We might want to link to that article, as well.

**Comment by micpap25** [comment]
Hi, looks like we do already link to the article here: 

![image](https://user-images.githubusercontent.com/34077605/107840246-31e07580-6d7f-11eb-8643-64fd21632b32.png)

I'm fairly certain that following the document's recommendations for built-in times would require a more extensive rework; for one, we would have to replace all of our recommended cases for using the `dynamic` type.

**Comment by kwalrath** [comment]
The article is a bit obsolete with null safety, so maybe we shouldn't link to it any more. I need to check on our `void` guidance and (as filed in #2485) add something about `Never`.

**Comment by kwalrath** [comment]
I think we're good. Please file another bug if we're still missing something.
