### ISSUE TITLE
Replace DartPad button images by icon

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1118]
From https://github.com/dart-lang/site-www/pull/1112#discussion_r214305909

---

... we want to show a button (which we can color red if that is deemed necessary):

    Click the run button <i class="material-icons">play_circle_filled</i>.

As you can see from this DartPad screenshot:

> <img width="351" alt="screen shot 2018-08-31 at 05 57 41" src="https://user-images.githubusercontent.com/4140793/44906418-d7ecb200-ace2-11e8-8403-41cff639ec30.png">

The DartPad run button is essentially a standard Material play button, so it seems appropriate IMHO:

> <img width="304" alt="screen shot 2018-08-31 at 06 00 04" src="https://user-images.githubusercontent.com/4140793/44906537-3023b400-ace3-11e8-9ac8-59753efdbaf5.png">

---

**Comment by kwalrath** [comment]
The new DartPad has no icon.
