### ISSUE TITLE
Exception section links to itself

### ISSUE THREAD

**Issue by mnordine** [dart-lang/site-www#1120]
https://www.dartlang.org/guides/libraries/library-tour#exceptions  

The sentence, "For more information, see Exceptions and the Exception API docs".  

Exceptions is a link to https://www.dartlang.org/guides/libraries/library-tour#exceptions  

Not sure if there really is a more informative section on Exceptions. If so, the link should be updated. If not, the link should be removed.

**Comment by kwalrath** [comment]
Oops, thanks for pointing that out.
