### ISSUE TITLE
Mention "brew update" in install/mac.md

### ISSUE THREAD

**Issue by martinsik** [dart-lang/site-www#113]
Maybe the documentation should mention that before running `brew install dart` you should also run `brew update`.  
Otherwise, you might have old formulae in cache that installs some ancient version of Dart.

**Comment by martinsik** [comment]
This seems to be fix already: https://www.dartlang.org/install/mac

**Comment by Sfshaza** [comment]
@martinsik noted that this is already there (not sure why his followup comment is not showing here). And it is there:  https://www.dartlang.org/install/mac#updating

Closing.
