### ISSUE TITLE
from-java-to-dart codelab: Clarify the scope of privacy

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1135]
https://codelabs.developers.google.com/codelabs/from-java-to-dart/#1 shows how to create a private variable, but doesn't mention the scope of privacy (library/file). One user was surprised that the variable was accessible (via print) outside of the class.

**Comment by kwalrath** [comment]
Should take very little time if you're already working on the codelab source (i.e. the internal-only Google Doc).

**Comment by FineTillYouCameAlong** [comment]
Completely pointless and time-wasting example if they didn't at least explain that none of it applies if everything is in the same file. I can't tell if they're trolling, or trying to weed out undesirable types of developers, or just another example of the breathtaking incompetence behind the shiny veneer of Google.

**Comment by kwalrath** [comment]
Just fixed this now.
