### ISSUE TITLE
Add gitter link to community page?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#114]
Right?

**Comment by kwalrath** [comment]
I was hesitating until we figured out what (if anything) our official channel would be. I figure we should point to either Slack or Gitter, not both. @filiph should I just throw the switch and make Gitter "it"?

**Comment by lrhn** [comment]
Just out of curiosity: What does it mean that a channel is "official"? And why can there be only one?

**Comment by kwalrath** [comment]
"Official" just means "what *.dartlang.org points to". I figure it's unwise to split the community between two chat systems, since people will feel like they have to check both every time they want an answer.

**Comment by kwalrath** [comment]
https://www.dartlang.org/community acquired a gitter link a while ago, so I'm closing this.
