### ISSUE TITLE
'Write HTTP Clients...`  still uses `pub serve` instead of `webdev serve`

### ISSUE THREAD

**Issue by pet-ro** [dart-lang/site-www#1150]
Page URL: https://www.dartlang.org/tutorials/dart-vm/httpserver
Page source: https://github.com/dart-lang/site-www/tree/master/src/_tutorials/dart-vm/httpserver.md

Still mentions `pub serve`  to launch the webserver from the top directory of the app,
instead of `webdev serve`.

pubspec.yaml needs a change to 

````pubspec.yaml
name: httpserver
description: Sample HTTP clients and servers

homepage: https://www.dartlang.org/docs/tutorials/httpserver/

dependencies:
  http_server: ^0.9.6

dev_dependencies:
  build_runner:  '>=0.8.10 <0.11.0'
  build_web_compilers: '>=0.3.6 <0.5.0'
  test: ^1.3.0
````

**Comment by kwalrath** [comment]
I'll check for this in all pages.

**Comment by kwalrath** [comment]
I've updated the linked-to code: dart-lang/dart-tutorials-samples#46
