### ISSUE TITLE
Fix typos in Chinese codelab translation

### ISSUE THREAD

**Issue by Purotis** [dart-lang/site-www#1159]
https://codelabs.flutter-io.cn/codelabs/from-java-to-dart-cn/index.html#3

_4. 创建工厂模式 -> 选项 1：创建一个顶层的方法 -> 注意 -> 第四小点_

**字符串是使用双引号进行生命** 应改为 **字符串是使用双引号进行声明**

**Comment by kwalrath** [comment]
Thanks for the report @CasLur. @mjohnsullivan, what's the best way to get typos or mistranslations fixed in the Chinese version of Flutter codelabs? Here's what the bug says, according to Google Translate:

> 4. Create Factory Mode -> Option 1: Create a top-level method -> Note -> Fourth Small
> 
> Strings are stored in double quotes. should be changed. Strings are declared in double quotes.

This is a translation of the following text from [the English original](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#3):

> To use a single quote inside a string, either escape the embedded quote using slash (`'Can\'t create $type.'`) or specify the string with double quotes (`"Can't create $type."`).

**Comment by kwalrath** [comment]
We have another issue that might be from the Chinese version of the codelab: #1169. The Chinese codelab pages link to our issue repo (see lower left of screenshot below). They should instead link to a place monitored by the Chinese translator.

![image](https://user-images.githubusercontent.com/2164483/45909655-e8f78300-bdb7-11e8-8d45-5dd4e9b1feba.png)

**Comment by CasLur** [comment]
OK. The Chinese version of the codelab isn't yours. It is translator's fault. Sorry to bother you.

**Comment by CasLur** [comment]
OK. The Chinese version of the codelab isn't yours. It is translator's fault. Sorry to bother you.

**Comment by kwalrath** [comment]
No worries! The codelab tells you to report issues here. We need to get them to fix that. I'm going to reopen this until we have a solution or the issue reported in a more appropriate place.

**Comment by kwalrath** [comment]
Another one: #1176

**Comment by parlough** [comment]
This translation has now been fixed and the website also links to their own bug tracker. Thanks again for reporting this!
