### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by tnip** [dart-lang/site-www#116]
URL: https://www.dartlang.org/docs/library-tour#maps-aka-dictionaries-or-hashes
Expected page: https://www.dartlang.org/guides/libraries/library-tour#maps

Linked to from https://api.dartlang.org/stable/1.18.1/dart-html/Storage-class.html.

**Comment by kwalrath** [comment]
Thanks very much for letting us know, @tnip!

@vsmenon: what's the best way to report/fix this API doc URL problem?

**Comment by vsmenon** [comment]
Can you fix the text here:

https://github.com/dart-lang/sdk/blob/864b64fd5e7f55a154d67b73e03da8afbe1bfe5d/tools/dom/templates/html/impl/impl_Storage.darttemplate#L28

?  @terrylucas or @alan-knight can regenerate the DOM from there.

**Comment by kwalrath** [comment]
@tnip, you up for making that edit?

**Comment by tnip** [comment]
SGTM, replicated issue over at https://github.com/dart-lang/sdk/issues/27150 for tracking.
