### ISSUE TITLE
中文错别字

### ISSUE THREAD

**Issue by SephirothLT** [dart-lang/site-www#1169]
![image](https://user-images.githubusercontent.com/20485889/45859561-8e4d2f80-bd95-11e8-9c82-3c9233f58a66.png)
应该为  ：即时

**Comment by kwalrath** [comment]
Which URL has this problem? (It's not our site, but we need to figure out how to handle issues like these.)

**Comment by SephirothLT** [comment]
https://codelabs.flutter-io.cn/codelabs/from-java-to-dart-cn/index.html#1

**Comment by parlough** [comment]
This typo has been fixed and the codelab bug report link now points to the proper destination. Thanks again for opening an issue!
