### ISSUE TITLE
中文错别字

### ISSUE THREAD

**Issue by InoueKonoha** [dart-lang/site-www#1176]
![](https://user-images.githubusercontent.com/4694199/45989821-d3cc6e00-c0af-11e8-9e66-5587d6cbe2bc.png)

应该是：**当**作为
原文地址：https://codelabs.flutter-io.cn/codelabs/from-java-to-dart-cn/index.html#5

**Comment by parlough** [comment]
This typo has been fixed and the codelab bug report link now points to the proper destination. Thanks again for opening an issue!
