### ISSUE TITLE
Clarify which examples are encouraged and discouraged for naming boolean values

### ISSUE THREAD

**Issue by bholtz** [dart-lang/site-www#118]
In the section linked [here](https://www.dartlang.org/guides/language/effective-dart/design#prefer-a-non-imperative-verb-phrase-for-a-boolean-property-or-variable), it would be nice if the language were made a little stronger. I referred to this section when trying to explain why a variable name like editable was not as strong as isEditable, but the recipient of my comment interpreted the closeable example as justification for keeping editable. Maybe the wording could be changed to 

closable // adjective, not preferred
canClose // verb, preferred

The same type of language changes could be made anywhere else where examples are presented without the red and green backgrounds.

**Comment by munificent** [comment]
I'm not sure how we can be much clearer here. `closeable` is literally in the list of bad examples of what not to do.
