### ISSUE TITLE
'Create Library Packages' page - document that library directives should be unique

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#1181]
Page URL: https://www.dartlang.org/guides/libraries/create-library-packages
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/libraries/create-library-packages.md

Until we get https://github.com/dart-lang/dartdoc/issues/1082 resolved there is still a need for many libraries to have a library directive.

In Dart you can't import two libraries with the same name - so we should call out that if you're using a library directive in a package you distribute the library directive should always be unique - like `package_name.something` rather than `something`.

**Comment by parlough** [comment]
I know this is four years late...But do you think we need to mention this now that no-name library declarations will be allowed in 2.19? Would it be sufficient to just expand on our documentation on how to use a no-name library declaration and add documentation to that (tracked in https://github.com/dart-lang/site-www/issues/4314)?

**Comment by parlough** [comment]
I'm going to close this as the library name clash rule was removed from the spec in https://github.com/dart-lang/language/pull/1083 and the analyzer removed the warning in https://github.com/dart-lang/sdk/commit/ef147c0a95bc345fbfca99946434745bf484ca08.
