### ISSUE TITLE
'Pub Versioning Philosophy' page issue

### ISSUE THREAD

**Issue by pet-ro** [dart-lang/site-www#1182]
Page URL: https://www.dartlang.org/tools/pub/versioning
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/versioning.md

The page contains the section
<a href="https://www.dartlang.org/tools/pub/versioning#shared-dependencies-and-unshared-libraries"
       >Shared dependencies and unshared libraries</a>

Issue: The term _unshared libraries_ is never used in the section.

I recommend to repalce the snippet
<blockquote>
  Because of this (and because of the headaches of trying to 
  debug an app that has multiple versions of things 
  with the same name), we’ve decided `npm`’s model
  isn’t a good fit.
</blockquote>

by this one

<blockquote>
 Because of this (and because of the headaches of trying to 
  debug an app that has multiple versions of things 
  with the same name), we’ve decided `npm`’s model
   isn’t a good fit. 
   `npm`’s model is that _shared dependency are resolved 
   by unshared libraries
</blockquote>

By the way here I suggestion to rephrase the section titles:

 - _A name and a number_
   turns to
   _library versioning: a name and a number_

- _shared dependencies and unshared libraries_
   turn to
   _Resolving a shared dependency_

   Add  a subsection
     _Resolving by unshared libraries_  (The 'npm' approach)

 -  Turn _Version lock_ into a subsection  of   _Resolving a shared dependency_
    named
   _Resolving  by a  fix version lock_ (The dead end approach)

- Turn _Version constraints_ into a subsection of   _Resolving a shared dependency_
   named 
   _ Resolved by version constraints_ (The Dart approach)

**Comment by kwalrath** [comment]
SGTM (with a few minor edits such as "(T" -> "(t", and clearer text around packages vs. libraries). 

@munificent or @nex3, have any opinions?

**Comment by munificent** [comment]
+1.

**Comment by pet-ro** [comment]
The URI scheme name "package" could have a provisional entry at
[Uniform Resource Identifier (URI) Schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)

**Comment by kwalrath** [comment]
Fixed by #1640.
