### ISSUE TITLE
Front page should mention Dart is an open-source project

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#1186]
The front of dartlang.org should make it clear that Dart is an open-source project, and should contain a link to our GitHub org.

**Comment by kwalrath** [comment]
We do have the link, but it's way down in the footer and easy to miss.

**Comment by mit-mit** [comment]
All I can see in the footer is this minute icon:

<img src="https://user-images.githubusercontent.com/13644170/47016173-2fd65f80-d14f-11e8-9ea1-50153d8af6f7.png" width="200">

And that is a link to the GitHub repo of the website.

I'd like to see an explicit piece of text with something like 'Dart is an open-source project, developed on GItHub' with a link to our GitHub org.

**Comment by chalin** [comment]
As you might know, for the [new flutter site](https://flutter-io-staging-1.firebaseapp.com) we've opted for a (larger) Octokitty icon that will _always_ be visible in the top nav (under mobile and desktop):

> <img width="400" alt="screen shot 2018-10-16 at 09 36 53" src="https://user-images.githubusercontent.com/4140793/47020315-19b4a900-d127-11e8-82cb-175624e54881.png">

Ideally we'd like something uniform across sites. Would this work for you?

**Comment by mit-mit** [comment]
Yes, that would be great.

In addition I'd like some sentence that says '...is free and open source.', again just like the Flutter site.
