### ISSUE TITLE
dart的冒號用法和function的簡單寫法讓代碼變得好難懂啊

### ISSUE THREAD

**Issue by see7di** [dart-lang/site-www#1188]
dart的冒號用法和function的簡單寫法讓代碼變得好難懂啊
例如:
class Box{
  int width,height;
  Box.fromJSON(Map json):width=json['width'],height=json['height']{
    this.width=width;
    this.height=height;
  }
}
頓時讓自己感覺自己就是一個傻逼

**Comment by kwalrath** [comment]
This seems to be a language comment, not a doc comment. It might be better discussed in the group: https://groups.google.com/a/dartlang.org/forum/#!forum/misc.

If you think we can fix this issue in the documentation (to some extent), please re-open this issue with specific suggestions and the URLs that you'd like us to change. Thanks!
