### ISSUE TITLE
'What Not to Commit' page issue

### ISSUE THREAD

**Issue by haarts** [dart-lang/site-www#1189]
Page URL: https://www.dartlang.org/guides/libraries/private-files
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/libraries/private-files.md

Under the section 'The Rules' the list of files might be mistaken for a complete `.gitignore` file. It isn't though, the comment on the last line is treated as part of the regex.

Small thing, I know.

**Comment by kwalrath** [comment]
Good point. Thanks for filing the issue!

**Comment by Purukitto** [comment]
This looks like it's fixed.
Looking at the current page, I don't see any reason to believe that the block of code is the whole `.gitignore`
