### ISSUE TITLE
dart:isolates to become a server-side only tech for now

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#119]
_From @kwalrath on July 21, 2016 22:41_

_From @nicolasgarnier on August 26, 2014 15:12_

_From [sethladd@google.com](https://code.google.com/u/sethladd@google.com/) on September 23, 2013 20:07:33_

Until Dartium supports isolates + html, let's double check we don't hint you can use isolates in HTML.

_Original issue: http://code.google.com/p/dart/issues/detail?id=13515_

_Copied from original issue: dart-lang/www.dartlang.org#744_

_Copied from original issue: dart-lang/site-webdev#24_

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 15:13_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on June 04, 2014 16:48:33_

**Labels:** -Area-Documentation Area-Site

**Comment by kwalrath** [comment]
There's one mention in the webdev site (in the dart2js page). I'll move this to webdev for now. Once that occurrence is fixed, we can check the www site.

**Comment by kwalrath** [comment]
Looking at all pages on www.dartlang.org that mention "isolate", I find no implications that anything but the VM supports isolates. Closing.

**Comment by lrhn** [comment]
I'm surprised by this decision, which I understand as removing isolates as a core Dart library and making it a server-only library (like dart:io). That leaves non-server without any concurrency mechanisms, and it makes any library that uses isolates incompatible with web-development.

I believe the current restriction on isolates is against using `Isolate.spawn`, but using `Isolate.spawnUri` does work in Dartium (or at least it used to). 

There is code in dart2js to support isolates, so there might be generic libraries using isolates for concurrency. These will stop working in the browser if isolates are removed.

**Comment by kwalrath** [comment]
This is an old bug (2013), not a new decision. I went ahead and completed the "fix" because I hadn't heard anything new encouraging isolates in web apps.
