### ISSUE TITLE
Main nav buttons don't highlight on tab

### ISSUE THREAD

**Issue by alecglassford** [dart-lang/site-www#1195]
The navigation buttons on the main nav (bar at top of screen that reads: "Getting Started, Language, Libraries, Tools, Dart 2") don't get highlighted as you tab through them - adding this functionality would improve accessibility by making it easier to navigate the website without a mouse.

I believe changing `&:hover` to `&:hover, &:focus` at https://github.com/dart-lang/site-www/blob/3d976f3310d0ade0bbc94bd58b1f8d5fd84bd08a/src/_assets/css/main.scss#L296 would fix this.

(The same improvement might be applicable on other parts of the site as well!)

**Comment by kwalrath** [comment]
flutter.io has this functionality, so presumably we'll get it when we use the flutter infrastructure (#1331).
