### ISSUE TITLE
Style: Prefer overload-style methods to dynamic calls or arguments

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/site-www#1205]
Based on work/analysis with @srawlins fixing issues across google3. This might be better suited for _multiple_ style rules instead of a single one, but I wanted to file a single issue for posterity and start there.

**BAD**: Using dynamic calls to perform intersection-type-like calls.

This causes poor code to be emitted on both DDC and Dart2JS (probably Dart AOT too), as well as drops all useful type information (users can pass `bool` to `checkLength`, for example, and get no static checking).

```dart
void checkLength(dynamic /*String | List*/ element) {
  if (element.length > 5) {
    print('Too big!');
  }
}
```

**GOOD**: Use overload-like methods.

Sure, it is strictly speaking more typing, but gives you (a) monomorphic functions and (b) static type checking. In a Dart 2.0 (AOT) world, both of these make infinitely more sense than the above option.

```dart
void checkList(List<void> elements) {
  if (element.length > 5) {
    print('Too big!');
  }
}

void checkString(String text) {
  if (text.length > 5) {
    print('Too big!');
  }
}
```

-----

**BAD**: Using `dynamic` to mean "unknown" type.

Using the `dynamic` keyword encourages accidental dynamic calls, which are slower on some runtimes, as well as omit any type checking, automated refactoring, and so on. 

```dart
void checkAny(dynamic /* String | bool */ stringOrBool) {
  // ...
}
```

**GOOD**: It is preferred to _Use overload-like methods_ where possible (see above), but if not possible, use `Object` and the `is` operator in order to emit only statically checked calls:

```dart
void checkAny(Object /* String | bool */ stringOrBool) {
  if (stringOrBool is String) {
    // ...
  } else if (stringOrBool is bool) {
    // ...
  } else {
    throw new ArgumentError('stringOrBool');
  }
}
```

**Comment by munificent** [comment]
I don't know if we need this specific guideline. There is a general trend away from using `dynamic` at all and I think this falls out naturally from that.

**Comment by matanlurey** [comment]
Is the general trend away reflected in the style guide? @munificent

**Comment by munificent** [comment]
Yes, [the new section on types](https://www.dartlang.org/guides/language/effective-dart/design#types) generally pushes in a direction of having things not dynamically typed unless that's specifically what you want.

**Comment by matanlurey** [comment]
I feel like [this](https://www.dartlang.org/guides/language/effective-dart/design#prefer-annotating-with-dynamic-instead-of-letting-inference-fail) slightly conflicts with that, but mostly agreed. @srawlins and @alorenzen points out we have https://www.dartlang.org/guides/language/effective-dart/design#do-annotate-with-object-instead-of-dynamic-to-indicate-any-object-is-allowed:

> Using dynamic sends a more complex signal. It may mean that Dart’s type system isn’t sophisticated enough to represent the set of types that are allowed, or that the values are coming from interop or otherwise outside of the purview of the static type system, or that you explicitly want runtime dynamism at that point in the program.

Is that true still in Dart 2?

**Comment by munificent** [comment]
The "PREFER annotating with dynamic instead of letting inference fail." rule doesn't cause you to have more dynamically typed variables. Instead, it means that when you *do* have them, you should write `dynamic` down explicitly to make that obvious.

> Is that true still in Dart 2?

Yeah, I think so. We could push back on that, but I believe that rule accurately describes how most people write Dart today. (Keep in mind that the style guide is both prescriptive and descriptive.)

**Comment by matanlurey** [comment]
If we had an `unknown` type, I'd agree with you. Using `dynamic`, which happens to also disable all static analysis, and require type-flow analysis in both Dart2JS and Dart AOT for optimized code, doesn't seem like something that should be a best practice, if anything it should be the opposite.

**Comment by kwalrath** [comment]
Is this issue fixed by https://dart.dev/guides/language/effective-dart/design#avoid-using-dynamic-unless-you-want-to-disable-static-checking?

Note: We might want to refer to that guidance (or update the text of) https://dart.dev/guides/language/effective-dart/design#prefer-annotating-with-dynamic-instead-of-letting-inference-fail.

**Comment by munificent** [comment]
> Is this issue fixed by https://dart.dev/guides/language/effective-dart/design#avoid-using-dynamic-unless-you-want-to-disable-static-checking?

Only partially. That says to use `Object` instead of `dynamic` for overload-ish cases, but doesn't say to avoid those cases.

> Note: We might want to refer to that guidance (or update the text of) https://dart.dev/guides/language/effective-dart/design#prefer-annotating-with-dynamic-instead-of-letting-inference-fail.

That rule is about a somewhat different thing, but definitely could stand to be written better.

**Comment by munificent** [comment]
I'm giving "Effective Dart" some love right now and I'd like to figure out what we want to do here. What do you think of a guideline something like:

> ### AVOID using `Object` or `dynamic` parameters to fake overloading.
>
> It's common for an API to support the same or similar operations on parameters of different types. If callers generally know which type they have and which specific operation they want, it's better to define multiple methods with different names to let them select it directly. This gives better static type checking and faster performance since it avoids any runtime type tests. However, if users may have an object of some unknown type and *want* the API to do a runtime type check to pick the right operation, then a single method with a parameter of type `Object` might be appropriate.

Thoughts?

**Comment by munificent** [comment]
PR out: https://github.com/dart-lang/site-www/pull/3021
