### ISSUE TITLE
Style: Avoid using the "is" operator to implement the visitor pattern

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/site-www#1206]
Semi-related to https://github.com/dart-lang/site-www/issues/1205.

**BAD**: Using the `is` operator to implement the visitor pattern, where possible. While it produces strictly speaking less code, it also requires potentially expensive runtime checks instead of relying on polymorphism directly.

```dart
void checkArgument(Object any) {
  if (any is User) {
    _checkUser(any);
  } else if (any is Company) {
    _checkCompany(any);
  }
}
```

**GOOD**: Using a boxed object and a visitor instead, especially if you own the objects. A simple `Visitor` pattern can make a `checkArgument` call a one-liner, and as a plus you can re-use the pattern in other places:

```dart
void checkArgument(DataModel m) {
  m.accept(_checkArgumentVisitor);
}

abstract class DataVisitor {
  void visitUser(User u);
  void visitCompany(Company c);
}

abstract class DataModel {
  void accept(DataVisitor v);
}

class User implements DataModel {
  @override
  void accept(DataVisitor v) => v.visitUser(u);
}

class Company implements DataModel {
  @override
  void accept(DataVisitor v) => v.visitCompany(u);
}
```

**Comment by munificent** [comment]
I think this is both too specific (it's not something I see misused often in code) and too far-reaching (does it disallow *all* uses of `is`) to be a good general guideline. The visitor pattern is really heavyweight, obscure, and unintuitive until you've had enough time to get familiar with it.

Why are `is` checks so slow?

**Comment by rakudrama** [comment]
The dispatch mechanisms on V8 ae overwhelmed when there are more than a handful of classes. At that point it becomes 'megamorphic' and is essentially a global hash-table lookup at each call to visitXXX and accept. It is not clear this is better or worse than a sequence of type checks, or that a benchmark written today would support the performance profile at some future state of the implementation.

The biggest problem with the visitor pattern is that requires you to plan ahead. The data items need to anticipate the need for the visitor and the visitor to know of all data item types. This could not easily be made to work for some more open-ended data-model with different classes provided by different libraries, like protocol buffer classes.

I think there needs to be a strongly compelling advantage to replace 7 lines of code with 20 lines of code. It is unlikely to result in a smaller compiled program.

**Comment by yjbanov** [comment]
Isn't `m.accept(_checkArgumentVisitor);` polymorphic?

**Comment by munificent** [comment]
Yes, that's what @rakudrama is saying. The visitor pattern can actually be pretty slow in JS VMs because the `accept()` calls end up polymorphic, often megamorphic.

**Comment by yjbanov** [comment]
In that case I'm not sure if this guideline will be effective at reaching its own goal. People will just not use `is` checks and use another form of polymorphism. If the program is necessarily polymorphic it will be polymorphic irrespective of what mechanism developers choose. It will be polymorphic even in C++.

So I guess :man_shrugging:

**Comment by jmesserly** [comment]
@matanlurey do you recall which compiler you were seeing the slow `is` check issue?

We optimized `is` for many types in `dartdevc` but there are still types that go down the slow path.

**Comment by matanlurey** [comment]
Going to close for now due to less-than-ethusiastic reception :)

**Comment by jmesserly** [comment]
Yeah SGTM to close this. It does make me wonder if we should open a bug on the compiler(s) though?

In general, a few `is` checks should be faster than the visitor pattern (which requires double dispatch). Visitor pattern is good when you have a lot of types. If there aren't many, I'd rather encourage `is` and fix the compilers if needed.

Thinking about this more, I realized DDC is not well optimized for `is`. It does better at casts, because it has fast paths for common *successful* casts. But that doesn't help `is`, which needs to be equally fast when the result is `false`. We can do better on those.
