### ISSUE TITLE
'Effective Dart: Design' page issue

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/site-www#1208]
Page URL: https://www.dartlang.org/guides/language/effective-dart/design
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/design.md

The example for `DO annotate with Object instead of dynamic to indicate any object is allowed.` is incorrect. It uses `dynamic` instead of `Object` for the parameter type in `convertToBool`.

**Comment by kwalrath** [comment]
I think the type in `convertToBool` is intentional. The argument can't be just any object — it must be a String or bool. The type in `log` is (correctly) `Object` because any type of object is allowed.

/cc @matanlurey @munificent

**Comment by matanlurey** [comment]
That seems needlessly complex, `dynamic` and `Object` aren't meaningfully different to express that, and `dynamic` allows (accidental) dynamic calls, effectively shutting off static analysis, and making it much easier to make mistakes or slow down code.

**Comment by lrhn** [comment]
Nevertheless, using `dynamic` to mean "there is a type restriction, but the type system cannot express it" and `Object` to mean "any object goes" is the traditional and idiomatic way to distinguish those cases.

It's slightly dangerous to use `dynamic` as argument type because `dynamic` does not allow type promotion of the parameter variable. If you are not careful, you can end up with dynamic invocations even after an `is` check (at least for static checking, compilers can be smarter).

**Comment by matanlurey** [comment]
> is the traditional and idiomatic way to distinguish those cases.

Then we should change the culture here and what is idiomatic and what is not :)

**Comment by munificent** [comment]
Changing the culture is fine, but "Effective Dart" mostly tries to follow and not lead. We should be very careful of using it as a blunt instrument to enforce our preferred culture changes. I'd much rather change the culture by actually persuading humans, and *then* have "Effective Dart" follow that.

**Comment by matanlurey** [comment]
> "Effective Dart" mostly tries to follow and not lead

I haven't found exhaustive evidence that `dynamic` is actually used for the intention effective Dart outlines. When I talk to users, they are surprised that `Object` effectively means the same thing.

**Comment by munificent** [comment]
I think this is covered by #2487, which I have a fix out for.
