### ISSUE TITLE
Add more tools to the Tools page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1211]
It seems like /tools should at least have dartdoc. What other tools are generally useful and in the Dart & Flutter SDKs? We can also point to non-SDK tools.

**Comment by parlough** [comment]
It seems like the [tools page](https://dart.dev/tools) was expanded including dartdoc and others during the site redesign and later on as well. Is there anything in particular you would like to see now? Maybe we could link to the [flutter-cli page](https://docs.flutter.dev/reference/flutter-cli)? Not sure if that's what you may have in mind.

**Comment by kwalrath** [comment]
I think the page is fine now
