### ISSUE TITLE
Add a function to search for language keywords

### ISSUE THREAD

**Issue by sanderAtMaxdoro** [dart-lang/site-www#1214]
For instance, 'is' is a keyword in dart. So if I want to know how to use it , I search for 'is' in the search bar on the dart site. 

But because 'is' is also a regular English word, there is no obvious entry in the results where I can quickly find how to use it. 

Some ideas: add a section on the right that shows all language keywords, use 'keyword' 'is' in the search bar or whatever.

**Comment by kwalrath** [comment]
There's a table in the language tour that lists all the keywords: https://www.dartlang.org/guides/language/language-tour#keywords

If you search the site for "keyword", then the language tour is the top result, although you then have to do another search inside the page (or click the TOC on the right) to find the keyword table. However, the table doesn't link to the discussions of each keyword; it should.

Would adding links to the items in the keyword table solve your problem? We could also add a link to the keywords table to the top of the language tour page, which would make the list more findable.

**Comment by kwalrath** [comment]
I'm going to close this because we don't plan to add this feature. I'm hoping that the links in the keyword table provide a good-enough solution.
