### ISSUE TITLE
Effective Dart and underscores in directory names

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/site-www#1215]
https://www.dartlang.org/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores

The style guide asks for lowercase_with_underscores in _file_ and _library_ names.

Should this be extended to include _package_ and _directory_ names?

That seems to be mostly what people are currently doing. There are cases where people are using lowercasewithoutunderscores instead in directory names, though.

**Comment by munificent** [comment]
Yes, I think that was always the intent that directory names should be lowercase_with_underscores.

Packages aren't part of the Dart language and pub [does document how they should be named](https://www.dartlang.org/tools/pub/pubspec#name), but I suppose it wouldn't hurt to state that here too.

**Comment by davidmorgan** [comment]
Sounds good, thanks.

**Comment by lrhn** [comment]
(Packages are part of the language as far as the format for `package:` URIs. From the language's perspective, a package name must just be a valid URI path segment. That's what the `.packages` file supports and what the `package:package_config` package does. All other restrictions on package names comes from Pub.)
