### ISSUE TITLE
'A Tour of the Dart Language' should explain type variables for generics

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/site-www#1216]
Page URL: https://www.dartlang.org/guides/language/language-tour#generics
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

The "Generics" section of the Dart language tour page states:

> By convention, type variables have single-letter names, such as E, T, S, K, and V.

without explaining their meaning or usage.  Are these arbitrary names?  When writing a generic, should the names be picked randomly? (We perhaps can expect readers to deduce that E is used for an element, K and V for key and value, T for type, but S is mysterious.)

Meanwhile https://www.dartlang.org/guides/language/effective-dart/design#do-follow-existing-mnemonic-conventions-when-naming-type-parameters does explain (and additionally lists R and U).

I recommend that the language tour page link to that guideline.

**Comment by Botanium** [comment]
This section in the documentation confused me a lot. I had to read other documentation from other programming languages to understand this point.
