### ISSUE TITLE
Futures tutorial text is confusing: "dart is single-threaded"

### ISSUE THREAD

**Issue by xxgreg** [dart-lang/site-www#1218]
https://github.com/dart-lang/site-www/blob/master/src/_tutorials/language/futures.md

The article states:
"Dart is single-threaded."
And "Dart is a single-threaded programming language."

This statement has confused at least one person - see this discussion:
https://www.reddit.com/r/dartlang/comments/9rs5d3/my_experiences_so_far/

Dart doesn't have shared-state multi-threading or locks, which I assume is the point which this article is trying to make. But isolates are a form of multi-threading.

Perhaps this would be better expressed as something like: "Futures are used to express concurrency within a single thread. (See isolates for running code on multiple cores)". 

I'm sure someone on the team can come up with something better than this - but I hope you get the gist ;)

**Comment by kwalrath** [comment]
@kevmoo we should talk about how to say this.

**Comment by kevmoo** [comment]
@munificent @leafpetersen @mraleph may have the right words here.

We have "safe(r)" concurrency via isolates + message passing – instead of notions of locks/semaphores, etc like other systems that support the traditional notion of threads

**Comment by kwalrath** [comment]
fyi, we're actively discussing this on an email thread. Words are hard!

**Comment by kwalrath** [comment]
We have a proposal. @xxgreg what do you think?

**Comment by xxgreg** [comment]
Good work.

I agree, words are hard. It's a difficult concept to describe briefly without going into more detail about the event loop.

Personally, given the target audience of developers, I'd replace "straight through" with "sequentially". But I don't have a strong opinion about that.

Also consider adding a link to the Isolate class in the blurb about isolates.
