### ISSUE TITLE
'Effective Dart: Design' page issue

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/site-www#1221]
Rule: [AVOID defining a one-member abstract `class` when a simple function will do][1]

[1]: https://www.dartlang.org/guides/language/effective-dart/design#avoid-defining-a-one-member-abstract-class-when-a-simple-function-will-do

As of Dart 2.x, we've found this advice is a little problematic. Previously in Dart 1.x, users would create a `typedef`, and rely on the nominal nature of that `typedef` in order to _key_ it to something. For example, one might write:

```dart
typedef PersonNameFormatter = String Function(Person);

void registerFormatters(Map<Type, String Function(Person)> formatters) {
  formatters[PersonNameFormatter] = (person) => '${person.first} ${person.last}',
}
```

In Dart 2.x, however, the following is true:

```dart
typedef PersonNameFormatter = String Function(Person);
typedef PersonTitleFormatter = String Function(Person);

void registerFormatters(Map<Type, String Function(Person)> formatters) {
  formatters[PersonNameFormatter] = (person) => '${person.first} ${person.last}',

  // Oops: Overwrote `PersonNameFormatter`!
  formatters[PersonTitleFormatter] = (person) => '${person.title}';
}
```

I like this rule, and we should keep it - but I'd like to suggest a small amendment to clarify Dart 2.x:

> there is a good chance you just want a function.

to:

> there is a good chance you just want a function.
>
> **NOTE**: As of Dart 2.x, a `typedef` or any function type is _structural_ not _nominal_.
> It is _not_ safe and _not recommended to use a function type as a key in a `Map`, `Set`, or
> related data structure:
>
> _Insert GOOD/BAD examples here_

/cc @srawlins @munificent @natebosch

**Comment by munificent** [comment]
> Previously in Dart 1.x, users would create a typedef, and rely on the nominal nature of that typedef in order to key it to something.

Typedefs have *never* been nominal in Dart.

Does this really come up often enough in Dart code to be worth adding a note for? I can see it happening in the world of Angular DI stuff, but I don't think I've *ever* seen a map where keys are function types.

**Comment by natebosch** [comment]
> Typedefs have _never_ been nominal in Dart.

Perhaps not in the spec, but they were in the tools. That is `SomeTypeDef == SomeOtherTypeDef` and `identical(SomeTypeDef, SomeOtherTypeDef)` were false in Dart 1 and are now true.

**Comment by matanlurey** [comment]
@munificent 

> Typedefs have _never_ been nominal in Dart.

Ah. Nominal is not the right name. That is, they were not canonicalized in Dart2JS/DDC, so:

```dart
typedef PersonNameFormatter = String Function(Person);
typedef PersonTitleFormatter = String Function(Person);

void main() {
  print(identical(PersonNameFormatter, PersonTitleFormatter)); // Used to be false, now true.
}
```

That was recently fixed: https://github.com/dart-lang/sdk/issues/32785.

> Does this really come up often enough in Dart code to be worth adding a note for?

You mean, do people put a `Type` in a `Map` or `Set` or `switch` statement? They definitely do.

**Comment by munificent** [comment]
> That is, they were not canonicalized in Dart2JS/DDC

Yeah, that's always been a bug and the wrong behavior.

> You mean, do people put a Type in a Map or Set or switch statement? They definitely do.

Types, yes. It's not uncommon for people to use class types as keys. I'm asking if they do that for *function* types. I haven't seen that and it seems pretty dubious because function types are structural and have complex subtype relationships. It would be a weird, risky thing to do.

**Comment by matanlurey** [comment]
They definitely do for `typedef`, hence this discussion to make of note of that in this rule.

**Comment by munificent** [comment]
Well, I understand at least one person has. :) My question is whether this comes up enough to justify putting in the style guide. My intuition is no based on the code I see, but I don't know if that's a skewed perspective.

Based on readability reviews, I already get the impression we've reached the point where "Effective Dart" is too long for people to hold all in their head.

**Comment by natebosch** [comment]
Another option to consider is expanding the doc comment on `Type` and including information about their behavior around canonicalization and equality. As we make decisions on things like https://github.com/dart-lang/sdk/issues/35098 that would also be a good place to document it.

I think I agree that using `Type` instances this way is probably too niche to warrant space in effective dart.

**Comment by matanlurey** [comment]
Thanks for this discussion! Opened up https://github.com/dart-lang/sdk/issues/35144 instead.
