### ISSUE TITLE
'Dart Language Asynchrony Support: Phase 2' page issue

### ISSUE THREAD

**Issue by denis-beurive** [dart-lang/site-www#1239]
Page URL: https://www.dartlang.org/articles/language/beyond-async
Page source: https://github.com/dart-lang/site-www/tree/master/src/_articles/language/beyond-async.md

The page is out of date (as specified) :

The members `moveNext()` and `current`  don't exist anymore.

Best regards

the members moveNext() and current

**Comment by lrhn** [comment]
Not sure which part of the page you are referring to, but `moveNext` and `current` are still members of the `Iterator` interface.
