### ISSUE TITLE
Bad URL - Eclipse-Plugin

### ISSUE THREAD

**Issue by toennito** [dart-lang/site-www#124]
URL: https://www.dartlang.org/tools/eclipse-plugin
Expected page: Page for the Eclipse-Plugin as descripted in http://news.dartlang.org/2015/04/the-present-and-future-of-editors-and.html and never officially revoked.
Why is the repository offline? Is there an alternative?

**Comment by kwalrath** [comment]
Thanks for the report. We should make that URL redirect to www.dartlang.org/tools/.

The Eclipse plugin is no longer supported. The recommended alternative is a JetBrains IDE such as WebStorm or IntelliJ IDEA. (I personally use WebStorm; internally, most Googlers use IntelliJ. They both use the same plugin.)

**Comment by kwalrath** [comment]
URL fix is in progress...

cc @filiph because we should probably clarify the status of the plugin. (Perhaps we could add a note to the news page?)

**Comment by kwalrath** [comment]
For some reason, this fix hasn't made it in. https://www.dartlang.org/tools/eclipse-plugin.html (and the .html-less version) still results in a 404.

**Comment by filiph** [comment]
Hmm, sorry for that, we have a redirect entry for /tools/eclipse-plugin/ but not /tools/eclipse-plugin.html. That's an error.

**Comment by filiph** [comment]
I had a look now and https://www.dartlang.org/tools/eclipse-plugin/ (the link in that article) doesn't result in 404. 

The url mentioned by @kwalrath (https://www.dartlang.org/tools/eclipse-plugin.html & the suffix-less version) does, but I'm not sure if anyone actually links to that URL. If so, please let me know, I'll add it to the redirects list.

I think the larger issue is that we don't mention Eclipse on that page and that people (therefore?) find [this page](https://marketplace.eclipse.org/content/dart-plugin-eclipse) when searching for [eclipse plugin for dart]? If that's the case, I'll reach out to the plugin author (Paul Verest?) and I'll ask you, @kwalrath, to add a note saying something like "Note that the Eclipse Plug-in for Dart is no longer maintained" to /tools.
