### ISSUE TITLE
"If android else" should be "If and else"

### ISSUE THREAD

**Issue by glud123** [dart-lang/site-www#1241]
Page URL: http://dart.goodev.org/guides/language/language-tour#control-flow-statements流程控制语句

![image](https://user-images.githubusercontent.com/22994043/48965423-b8baa380-eff7-11e8-8038-b9256dc2fd5e.png)

"If android else" should be "If and else"

**Comment by kwalrath** [comment]
dart.goodev.org is old. We link to a new site, http://www.dartdoc.cn.
