### ISSUE TITLE
Default parameter values example don't need null check

### ISSUE THREAD

**Issue by feinstein** [dart-lang/site-www#1242]
On this example `device` has a default parameter value, so there's no need to null check it:

```
String say(String from, String msg,
    [String device = 'carrier pigeon', String mood]) {
  var result = '$from says $msg';
  if (device != null) {
    result = '$result with a $device';
  }
  if (mood != null) {
    result = '$result (in a $mood mood)';
  }
  return result;
}

assert(say('Bob', 'Howdy') ==
    'Bob says Howdy with a carrier pigeon');
```

**Comment by lrhn** [comment]
The example is from https://sites.google.com/site/dartlangexamples/learn/functions

Sadly, there is a reason (even if it's not being handled correctly here).
It's possible to call the function as `whatnot.say("from", "message", null)` in which case the `device` parameter will be `null`. You probably won't do that explicitly, but just call it with some variable `device` which happens to accidentally contain `null`.

It's still bad design. Please don't ever accept `null` and have it mean anything different from the default value. I would start the function with:
```dart
if (device == null) throw ArgumentError.notNull("device");
```
to handle the problem.

**Comment by feinstein** [comment]
I thought about this at first... But couldn't we also call `say(null, null, null)`? The example doesn't have a null check for `from` and `msg`, so why bother with `device`?

**Comment by lrhn** [comment]
That is a good point. The code is not written to be defensive, so it is suspicious that it is for `device`. It does look like it intends you to be allowed to pass `null` (which I hope is not true).

**Comment by feinstein** [comment]
Precisely, I think the example should be concise and clear, otherwise examples become too big and complicated. 

Defensive coding IMHO should be only introduced in the `try-catch` section to make the reading more pleasing, and in that section the whole concept can have a paragraph of itself. 

Checking some variables are not the others leads to confusion for beginners.

**Comment by kwalrath** [comment]
Agreed, we should simplify that example. Thanks for reporting this, @feinstein, and for the discussion, @lrhn.

**Comment by feinstein** [comment]
@kwalrath my pleasure to help :)

**Comment by micpap25** [comment]
Looks like this was simplified by removing "mood" and the default parameter on `device`. I think it's concise enough now. 
```
String say(String from, String msg, [String device]) {
  var result = '$from says $msg';
  if (device != null) {
    result = '$result with a $device';
  }
  return result;
}
```

This can be closed IMO.

**Comment by kwalrath** [comment]
@micpap25 I still see `mood` in https://dart.dev/guides/language/language-tour#default-parameter-values. (I think you're looking at https://dart.dev/guides/language/language-tour#optional-positional-parameters?)

**Comment by micpap25** [comment]
Ah, I misunderstood where the issue was. I can submit a PR for this.
