### ISSUE TITLE
Typo in "The main() function"

### ISSUE THREAD

**Issue by feinstein** [dart-lang/site-www#1243]
it says **entrypoint**, I believe it was meant **entry point**?

**Comment by kwalrath** [comment]
It's a bit questionable, but apparently we use one word fairly consistently (https://www.dartlang.org/tools/pub/glossary#entrypoint).

(Thanks for reporting this! It's good to know someone's paying close attention.)

**Comment by feinstein** [comment]
I confess I was wondering if I wasn't being obnoxious 😅

**Comment by kwalrath** [comment]
Not at all!
