### ISSUE TITLE
From JSON Constructor Example uses a Map

### ISSUE THREAD

**Issue by feinstein** [dart-lang/site-www#1245]
The [Using Constructors](https://dart.dev/language/classes#using-constructors) topic shows this example:
```
var p1 = Point(2, 2);
var p2 = Point.fromJson({'x': 1, 'y': 2});
```

AFAIK `{'x': 1, 'y': 2}` is a Dart `Map<String, int>`, in JSON notation, but JSON is in fact a textual representation of data, the specs make it clear for me, so I think the correct would be:

```
var p1 = Point(2, 2);
var p2 = Point.fromJson('{"x": 1, "y": 2}');
```

or

```
var p1 = Point(2, 2);
var p2 = Point.fromMap({'x': 1, 'y': 2});
```

**Comment by chalin** [comment]
We follow the [json_serializable](https://pub.dartlang.org/packages/json_serializable) conventions where the argument type of the `.fromJson()` constructor is of type `Map<String, ...>`. cc @kwalrath

@kevmoo any comments about this?

**Comment by feinstein** [comment]
Oh, interesting, maybe this could be a side note on the example? This way beginners won't get confused and also learn a little thing on the side.

PS: IMHO the correct would be calling it `fromJsonMap`, but I understand the short name to keep it simpler.

**Comment by atsansone** [comment]
This would be covered in the language specification. Closing as Won't Do. Please reopen if you believe this change necessary. Thanks!
