### ISSUE TITLE
dartdocs-gen-api.zip for case-insensitive filesystem

### ISSUE THREAD

**Issue by sgon00** [dart-lang/site-www#1248]
Hi, when I unzip `dartdocs-gen-api.zip` downloaded from https://www.dartlang.org/tools/sdk/archive, it generates many replacement errors due to duplicated files, such as `SIGTSTP-constant.html` vs `sigtstp-constant.html`.

I understand that case-sensitive file system is better and I used to case-sensitive file system in Linux, but because I am developing iOS apps based on flutter, I am working on MacOS right now and the MacOS suggests using case-insensitive filesystem and many apps may cause errors if I use case-sensitive fs. Even MacOS experts suggest using case-insensitive fs.

**Comment by kwalrath** [comment]
Good point. I'm not sure where this bug should go, though.

@whesse or @jcollins-g, what do you think?

**Comment by jcollins-g** [comment]
this is https://github.com/dart-lang/dartdoc/issues/1196

**Comment by kwalrath** [comment]
Closing in favor of dart-lang/dartdoc#1196. Please follow that issue.
