### ISSUE TITLE
The library keyword is mentioned but not explained

### ISSUE THREAD

**Issue by feinstein** [dart-lang/site-www#1249]
The `library` keyword is mentioned on the Library section, almost at the end, but it isn't explained, nor there's a reference to read more about it.

**Comment by kwalrath** [comment]
I think this issue is in the language tour? I should probably add "when to use the `library` directive" to the list at the end of the section, in https://www.dartlang.org/guides/libraries/create-library-packages.

**Comment by feinstein** [comment]
Yes, it is in the language tour, I forgot this issues are related to the whole website.

That addition will be very helpful.

**Comment by kwalrath** [comment]
Thanks for reporting these issues, @feinstein. They really do help us improve the docs!

**Comment by feinstein** [comment]
I truly believe Flutter will bring Dart to a whole new level of adoption. It's a rare thing to be able to help something as this on its infancy, so I feel good to be a part of it.

Specially if this helps jump-start Dart as a first-class citizen in Android, as Google did for Kotlin (that's my hannukah wish for next year).

So count on me as much as you guys need :)
