### ISSUE TITLE
中文错别字

### ISSUE THREAD

**Issue by Hatsune39** [dart-lang/site-www#1253]
![image](https://user-images.githubusercontent.com/20898148/49497742-1ecee280-f8a4-11e8-8ba6-c4462ae6862d.png)

 URL：https://codelabs.flutter-io.cn/codelabs/from-java-to-dart-cn/index.html#3

**Comment by Hatsune39** [comment]
应该是 “转义符” 和 “声明的”

**Comment by daoyuly** [comment]
<img width="406" alt="d0429a6b-a1f1-40ca-9143-c9dee21775fa" src="https://user-images.githubusercontent.com/994481/49850944-6ca29800-fe1a-11e8-90e1-bce7da94dcde.png">
![df65568d-fc3d-4698-96dd-4b7472519996](https://user-images.githubusercontent.com/994481/49850952-76c49680-fe1a-11e8-8e16-572d24e69026.png)
prose： written or spoken language in its ordinary form, without metrical structure. 翻译成 使用简洁直白的方式 似乎更好理解。

**Comment by amisare** [comment]
@daoyuly 中文版，可关注 www.dartdoc.cn
