### ISSUE TITLE
Cover set literals in the language tour

### ISSUE THREAD

**Issue by gggustafson** [dart-lang/site-www#1257]
On the page https://www.dartlang.org/guides/language/language-tour#built-in-types is not Set a built-in type?

**Comment by kwalrath** [comment]
Not yet, but soon I think (see https://github.com/dart-lang/language/issues/36). I'll keep this open to remind us to add them once set literals are implemented.

**Comment by kwalrath** [comment]
The language tour mentions only those classes that have specific language support. APIs for dart:core classes (such as Set and even built-in classes) are covered in the library tour (e.g. https://www.dartlang.org/guides/libraries/library-tour#sets).

**Comment by kwalrath** [comment]
Set literals are coming soon! When we update the language tour to cover them, we should also update the ["Do use collection literals when possible"](https://www.dartlang.org/guides/language/effective-dart/usage#do-use-collection-literals-when-possible) guideline to mention sets.
