### ISSUE TITLE
Add guidance for when to use factory constructors

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1258]
@munificent is this something that belongs in Effective Dart?

See https://github.com/flutter/website/pull/1958 for the discussion.

**Comment by munificent** [comment]
It's not a bad idea, but I'm not sure what the guidance should be. I don't recall this coming up very often, so it may be that users naturally figure out what to do and we don't need to give guidance.

**Comment by kwalrath** [comment]
I'm going to close this. If anyone comes up with guidance that'll be helpful, please open a new bug.
