### ISSUE TITLE
Archive dart-tutorials-samples repo to consolidate examples to this repo

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1270]
More info: dart-lang/dart-tutorials-samples#47

**Comment by kwalrath** [comment]
We should either have a process to keep these in sync, or we should stop pointing to dart-tutorials-samples.

**Comment by kwalrath** [comment]
dart-tutorials-samples repo was just updated in github.com/dart-lang/dart-tutorials-samples/pull/49.

**Comment by kwalrath** [comment]
And again: https://github.com/dart-lang/dart-tutorials-samples/pull/51

**Comment by parlough** [comment]
I've modified this issue to track archiving the other repository to avoid potential confusion as most, if not all, examples there are out dated and likely not functional with null safety.

Once https://github.com/dart-lang/site-www/issues/3415 is completed, everything still used from there should be tracked on site-www

**Comment by parlough** [comment]
This work was completed by https://github.com/dart-archive/dart-tutorials-samples/issues/60
