### ISSUE TITLE
'What Not to Commit' page issue

### ISSUE THREAD

**Issue by patarapolw** [dart-lang/site-www#1275]
Page URL: https://www.dartlang.org/guides/libraries/private-files
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/libraries/private-files.md

Description: 

I think `.pub/` is generated by `pub get` and should also not to be committed to GitHub. Otherwise, there will be thousands of files committed.

Can you please confirm this?

**Comment by kwalrath** [comment]
There's a note on that page:

> Note: The .dart_tool directory, which is new in Dart 2, is used by pub and other tools. It replaces the .pub directory as of the 2.0.0-dev.32.0 SDK release. The .packages file replaces the packages directories that early Dart 1.x versions produced."

So I think `.pub` is intentionally omitted. I confirmed that, as of pub 2.1.0, no `.pub` directory is generated by `pub get`.

**Comment by patarapolw** [comment]
It won't be fair for someone who use `dart@1` though.

Not every package is moved to Dart 2.

**Comment by kwalrath** [comment]
We have an archived version of the site for people who are still on Dart 1.
