### ISSUE TITLE
Update article or mark older as pointed bugs are fixed

### ISSUE THREAD

**Issue by shubhamhackz** [dart-lang/site-www#1280]
```
import 'dart:async';
void main() {
  print('main #1 of 2');
  scheduleMicrotask(() => print('microtask #1 of 3'));

  new Future.delayed(new Duration(seconds:1),
      () => print('future #1 (delayed)'));

  new Future(() => print('future #2 of 4'))
      .then((_) => print('future #2a'))
      .then((_) {
        print('future #2b');
        scheduleMicrotask(() => print('microtask #0 (from future #2b)'));
      })
      .then((_) => print('future #2c'));

  scheduleMicrotask(() => print('microtask #2 of 3'));

  new Future(() => print('future #3 of 4'))
      .then((_) => new Future(
                   () => print('future #3a (a new future)')))
      .then((_) => print('future #3b'));

  new Future(() => print('future #4 of 4'));
  scheduleMicrotask(() => print('microtask #3 of 3'));
  print('main #2 of 2');
}
```
According to the[ article](https://webdev.dartlang.org/articles/performance/event-loop#question-2) because of bugs [9001](https://github.com/dart-lang/sdk/issues/9001) and [9002](https://github.com/dart-lang/sdk/issues/9002) , output of the above program will be :
```
main #1 of 2
main #2 of 2
microtask #1 of 3
microtask #2 of 3
microtask #3 of 3
future #2 of 4
future #2a
future #2b
future #2c
future #3 of 4
future #4 of 4
microtask #0 (from future #2b)
future #3a (a new future)
future #3b
future #1 (delayed)
```
Since both [9001](https://github.com/dart-lang/sdk/issues/9001) and [9002](https://github.com/dart-lang/sdk/issues/9002) bugs are fixed, the article should be updated or marked older.
Output of the above program now changed because of the bugs fixed:

```
main #1 of 2
main #2 of 2
microtask #1 of 3
microtask #2 of 3
microtask #3 of 3
future #2 of 4
future #2a
future #2b
future #2c
microtask #0 (from future #2b)
future #3 of 4
future #4 of 4
future #3a (a new future)
future #3b
future #1 (delayed)

```

**Comment by kwalrath** [comment]
This bug is about https://www.dartlang.org/articles/libraries/zones, which is marked as older (at the very top).

**Comment by parlough** [comment]
Since the discussed article [no longer exists](https://web.archive.org/web/20181211221156/https://webdev.dartlang.org/articles/performance/event-loop), I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/2142 which aims to introduce a replacement. Thanks again for opening the issue!
