### ISSUE TITLE
'A Tour of the Dart Language' page issue

### ISSUE THREAD

**Issue by kyungkoo** [dart-lang/site-www#1282]
Page URL: https://www.dartlang.org/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Description:
SampleCode at [Strings](https://www.dartlang.org/guides/language/language-tour#strings),  `const aConstList = [1, 2, 3];` is unnessary. As I think, it is better to remove it.

**Comment by kwalrath** [comment]
I think the point was to show that although some consts for built-in types can work in string literals, not all do.
