### ISSUE TITLE
Consider redirecting tutorials/dart-vm to tutorials/server

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#1285]
Did we used to have the pages in a different place? Some users are finding links to `tutorials/dart-vm` which don't exist, while the same path under `tutorials/server` does exist.

 https://gitter.im/dart-lang/TALK-general?at=5c254ee837975e7ca93380c2

**Comment by kwalrath** [comment]
Thanks for the report. We changed dart-vm to server in #1274. Unfortunately, fixing the 404s isn't trivial, but I'll keep an eye on 404s and see if there are any other obvious fixes to make.
