### ISSUE TITLE
Flutter migration guide not valid

### ISSUE THREAD

**Issue by ghost** [dart-lang/site-www#1290]
https://www.dartlang.org/dart-2#migration

Flutter migration guide

This link not valid 

target page not exists

**Comment by kwalrath** [comment]
Yikes! @sfshaza2 where should this link go to? (Where has the info from https://github.com/flutter/flutter/wiki/Dart-2-Migration gone?)

**Comment by chalin** [comment]
cc @Hixie @filiph - where is the Flutter Dart-2-Migration page and if it is gone, what should we use as a replacement?

**Comment by Hixie** [comment]
no idea, cc @kevmoo

**Comment by sfshaza2** [comment]
I don't remember seeing this page on the wiki. At any rate, it's gone. This info belonged on the regular site, not the wiki, which is likely why it was removed.

If anyone has a version of the page handy, I'm happy to put it on flutter.io.  (Though I think the migration changes were limited to new/const, pretty much.)

**Comment by sfshaza2** [comment]
Yes, please do that. Thanks!
