### ISSUE TITLE
'Native Extensions for the Standalone Dart VM' page issue

### ISSUE THREAD

**Issue by mikemaksymowych** [dart-lang/site-www#1293]
Page URL: https://www.dartlang.org/articles/server/native-extensions
Page source: https://github.com/dart-lang/site-www/tree/master/src/_articles/server/native-extensions.md

Description:
The links to dart_api.h should actually point to dart_native_api.h

**Comment by kwalrath** [comment]
It looks like the first bit of code (e.g. `typedef void (*Dart_NativeFunction)(Dart_NativeArguments arguments)`) comes from dart_api.h, but at least some later ones (e.g. Dart_CObject) come from dart_native_api.h. It would take a bit of research to figure out what each references should be to.

@mikemaksymowych, would you be willing to create a PR? You could just click the page source link above and edit it in github's UI. (If not, no worries! It's just likely to get fixed sooner if you do it.)

/cc @whesse
