### ISSUE TITLE
Can't permalink to a style rule for Effective Dart

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/site-www#13]
Previously you could link to a particular style rule:
https://web.archive.org/web/20160702200714/https://www.dartlang.org/effective-dart/usage/#do-use-adjacent-strings-to-concatenate-string-literals

The permalink is easily accessible on the right of each rule. We use this all the time for Dart Readability reviews in Google, to point folks at a specific item.

In the new site it doesn't seem possible:
https://www.dartlang.org/guides/language/effective-dart/usage

The ids are still there on each item, if you open up web inspector. So it's possible to make a permalink, but not easy.

**Comment by jmesserly** [comment]
Source code for Effective Dart seems to be: https://github.com/dart-lang/site-www/blob/master/src/_guides/language/effective-dart/

**Comment by Sfshaza** [comment]
OK, it sounds like we need to add this back. (The links are still there in the source, but you have to view source to find it.)

How would you prefer this feature to work?
1. A generated TOC at the beginning of the file?
2. Hovering over the header to see a hash on the right that you click?

**Comment by Sfshaza** [comment]
Also filed here:  https://github.com/dart-lang/site-www/issues/9  (closed as a duplicate)

**Comment by jmesserly** [comment]
Oh nice! Yeah either way works. Slight preference for option 2, but whatever is easier :)

**Comment by har79** [comment]
Could we have both? I would really appreciate a TOC for finding rules. I often want to reference a rule I know exists but can't even remember which page of effective-dart it's in, let alone where on the page, and end up with four tabs and Ctrl-F to find it. A TOC would make this a lot quicker and make it easier to remember the list of rules in each page.

**Comment by jmesserly** [comment]
yeah, good point the groupings into different sections has never made a lot of sense. Most style guides put everyone on one page for that reason (easy to search)

**Comment by kwalrath** [comment]
In the short term, we plan to produce a TOC at https://www.dartlang.org/guides/language/effective-dart that lists and links to _all_ of the rules.

Let's see how that goes, and then we'll add anchors if need be.

**Comment by jmesserly** [comment]
sounds great! thank you :)

**Comment by har79** [comment]
That would be great, thanks!

**Comment by gmesch** [comment]
So if I want to link to the section I'm looking at, I have to go to the TOC, find the headline of the same section again, and copy the link from there? I admit this doesn't sound so convincing.

**Comment by filiph** [comment]
Here's the quick fix @kwalrath mentioned above:
https://www.dartlang.org/guides/language/effective-dart#summary-of-all-rules

It's not ideal because unless you know the rules by heart, you will have trouble finding them without the context (for example, I sometimes find it faster to look at the good/bad code examples than to read the name of the rule).

I'll figure out how Github does this (on rendered markdown files, for example) and will try to implement something like that. It might take time so I landed this fix. (https://github.com/dart-lang/site-www/commit/ce2059381fc217ee97420161c783d7dbf0e29b88)

I'm not closing this issue. Please let me know if the fix is at least somewhat helpful or if you have any other quick fix ideas.

**Comment by har79** [comment]
That summary's helpful thanks. Also being able to link from an item would be great, but with the TOC this is already quicker for me than it was with the old site.

There does appear to be an issue with encoding though; the item
"CONSIDER using => for short members whose body is a single return statement."
is linked in the TOC as
"#consider-using-gt-for-short-members-whose-body-is-a-single-return-statement"
but this doesn't work as it actually has an id of
"#consider-using--for-short-members-whose-body-is-a-single-return-statement"

**Comment by filiph** [comment]
Thanks for the report! I fixed the generator with https://github.com/dart-lang/site-www/commit/9749340f50e22cfcecad2c49f5cffcb69e331588. Once this gets [deployed](https://travis-ci.org/dart-lang/site-www/builds/146488502), the broken anchor should not be an issue anymore.

**Comment by rkj** [comment]
Any update?

**Comment by kwalrath** [comment]
Check out the pages now, with big old TOCs at the top:

https://www.dartlang.org/guides/language/effective-dart/style

Still no # in the headers, though.
