### ISSUE TITLE
anonymous functions unexplained in language tour

### ISSUE THREAD

**Issue by ben4ever** [dart-lang/site-www#130]
Anonymous functions are talked about in [this article](https://www.dartlang.org/resources/dart-tips/dart-tips-ep-7) but they aren't explained in the [language tour](https://www.dartlang.org/guides/language/language-tour).

**Comment by Sfshaza** [comment]
You can see the new section here:
https://www.dartlang.org/guides/language/language-tour#anonymous-functions
