### ISSUE TITLE
Wrong characters in Chinese

### ISSUE THREAD

**Issue by alienyan** [dart-lang/site-www#1304]
![tim 20190108144307](https://user-images.githubusercontent.com/13297495/50814230-eb282200-1353-11e9-9d40-60e965b7bd00.png)

Please correct “比赛服” to “标识符”

http://dart.goodev.org/guides/language/language-tour#strings字符串

**Comment by kwalrath** [comment]
dart.goodev.org is old. We link to a new site, http://www.dartdoc.cn.
