### ISSUE TITLE
'Pubspec Format' page: document ideal 'description' length

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#1305]
Page URL: https://www.dartlang.org/tools/pub/pubspec#description
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/pubspec.md

Should be `>= 60 && <= 180`

https://github.com/dart-lang/pana/blob/820ce672ccaf5b950e028737219f55aa57e185ef/lib/src/maintenance.dart#L376-L400

**Comment by isoos** [comment]
We have already talked in a related topic with @jonasfj: `pana` right has three major parts:
- running `pub upgrade`, `dartfmt` and `dartanalyzer`, and interpreting, summarizing their output
- scanning the source code itself for platform classification and conflict detection (slow)
- "surface scan" of the package (fast)

The later includes the suggested length of the description field, and a few more similar checks. We thought that these should be probably done in a separate package, maybe also included in `pub` client's suggestions before upload.

What do you think, should we create a canonical place for such "surface scans"?

**Comment by kwalrath** [comment]
Fixed by #1640.
