### ISSUE TITLE
Please add to "Effective Dart" a recommendation to omit "void" in setters

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/site-www#131]
bad:

``` dart
void set foo(Foo value) {...}
```

good:

``` dart
set foo(Foo value) {...}
```

The `void` is pointless noise.  Please formalize this in [Effective Dart](https://www.dartlang.org/guides/language/effective-dart) so that we have something official to point to in code review.  I got a soft promise from rnystrom@google.com that he would do this sometime in 10/2016.

**Comment by trinarytree** [comment]
Ping.  This issue still comes up in our codebase.

**Comment by kwalrath** [comment]
@munificent, OK for me to add this?

**Comment by munificent** [comment]
That would be awesome! I've been pulled in so many directions I haven't been able to give any love to the style guide.

**Comment by munificent** [comment]
Thank you for doing this!
