### ISSUE TITLE
Nit in description of callable classes - the _instances_ are callable

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#1316]
https://www.dartlang.org/guides/language/language-tour#callable-classes

"To allow your Dart class to be called like a function, implement the call() method."

Pedantically this should be 

"To allow an instance of your Dart class to be called like a function, implement the call() method."

**Comment by natebosch** [comment]
Reported here: https://gitter.im/dart-lang/sdk?at=5c3def028ce4bb25b8b66f09

**Comment by kwalrath** [comment]
Thanks for the report, @natebosch.

**Comment by micpap25** [comment]
Looks like this was fixed, can be closed. 
![image](https://user-images.githubusercontent.com/34077605/96788157-ff220400-13c0-11eb-8303-ad71afb988a0.png)

**Comment by natebosch** [comment]
Looks like this was fixed by https://github.com/dart-lang/site-www/pull/1620

**Comment by kwalrath** [comment]
Thanks, @micpap25 & @natebosch
