### ISSUE TITLE
Pubspec page should warn about generic custom top-level fields

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#1317]
Currently the [pubspec page](https://github.com/dart-lang/site-www/blob/1f27503b89a57d3bc50c96cd625d4e742f5c1435/src/tools/pub/pubspec.md#supported-fields) says that additional top-level fields are ignored.

We should document that:
 * custom top-level fields should have unique names (maybe suggest using a registered package name).
 * generically named top-level fields should be avoided as `pub` may choose to define a format for such fields in the future, which would break your package.
 * We could go further to suggest that custom top-level fields be prefixed with `_` or `$`, such that there is a clear convention to follow.

Examples of generic field names includes:
 * `bugs`
 * `license`
 * `scripts`
 * `resources`
 * `links`
 * `config`
 * `build_steps`

/cc @munificent

**Comment by kwalrath** [comment]
@jonasfj what would be an example of a registered package name? `my_pkg_resources`?

I'm trying to think of how to phrase this. Maybe something like this:

> ## Supported fields
> ...
> 
> Pub ignores all other fields.
> 
> If you add custom fields to the pubspec, avoid generic field names, which might clash with future additions to the supported fields. We recommend a prefix of `$`, `_`, or your package name. For example, instead of `resources`, you might add `$resources`, `_resources`, or `my_pkg_resources`.

/cc @kevmoo

**Comment by jonasfj** [comment]
It might be fine to just discourage generically named properties.

Most people probably don't want to read a lot of about custom top-level properties anyways :)

(note, I doubt is high priority, it's mostly just a nit)

**Comment by kwalrath** [comment]
Fixed by #1640.
