### ISSUE TITLE
Improve linter integration with docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1319]
- [x] Maybe use a different example lint in the overview (since the help for `prefer_collection_literals` lacks types). Or maybe just fix the help.
- [x] Maybe move the linter text down the page to https://www.dartlang.org/guides/language/effective-dart#how-to-read-the-guides.
- [ ] Automate and test the association between linter rules and guideline text/URLs. (See http://github.com/dart-lang/site-www/issues/921#issuecomment-454890452.)
- [ ] Update descriptions in linter rule docs. (Should file a linter bug for this work.)

**Comment by parlough** [comment]
I'm not sure we need to automate this association, especially since it's maintained on the same site now, and rarely new lints will be added for current guidelines. If anyone feels strongly about this, feel free to open a new issue. Thanks!
