### ISSUE TITLE
Add README.md info to package layout page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1321]
See dart-lang/pub-dartlang-dart#1973 for details.

**Comment by kwalrath** [comment]
@isoos or @jonasfj, can you point me to a good example of a package that has an example/README.md file? I looked in the sdk repo but didn't find one there.

**Comment by isoos** [comment]
@kwalrath: Not sure what qualifies as good, but this package has many things in the example directory, and uses a readme.md:  https://github.com/flutter/plugins/tree/master/packages/in_app_purchase

**Comment by isoos** [comment]
A few others:
- https://github.com/jacobaraujo7/bloc-pattern
- https://github.com/DanTup/tiler
- https://github.com/RafaelBarbosatec/achievement_view_flutter
- https://github.com/ganeshsp1/wallpaperplugin

**Comment by kwalrath** [comment]
Fixed by #1640.
