### ISSUE TITLE
Use flutter.io infrastructure

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1331]
We want to use flutter.io's navigation and styles, with tweaks as necessary. We share a lot of infrastructure, but not as much as we should.

**Comment by chalin** [comment]
I've given this some more thought, and you might be able to copy over what you want piecewise. You'll first need to have a good understanding of the [shared site infrastructure](https://github.com/dart-lang/site-shared/blob/master/doc/infrastructure.md).

Note that while the flutter/website SCSS and JS files have been organized with site sharing in mind, the setup isn't complete. In particular:

- flutter/website SCSS and JS files that you intend to share will need to be moved into site-shared.
- For CSS, try to confine site-specific changes to `src/_assets/css/_site_overrides.scss`.

**Comment by kwalrath** [comment]
#1381 is a start.

**Comment by kwalrath** [comment]
dart.dev uses flutter's nav & styles, with tweaks to make it easily distinguishable.
