### ISSUE TITLE
'Effective Dart: Usage' page issue

### ISSUE THREAD

**Issue by patlillis** [dart-lang/site-www#1332]
Page URL: https://www.dartlang.org/guides/language/effective-dart/usage
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/usage.md

Description: "DON’T use `this.` when not needed to avoid shadowing." needs an exception for redirecting to a named constructor.

That guideline states "The only time you need to use `this.` is when a local variable with the same name shadows the member you want to access.". This is not true, you also need it when redirecting to a named constructor.

E.g. following does not compile:
```dart
class Thingy {
  Thingy._black();

  Thingy.blue() : _black();
}
```

Instead it needs to be:
```dart
class Thingy {
  Thingy._black();

  Thingy.blue() : this._black();
}
```

**Comment by munificent** [comment]
Fixed by #1334.
