### ISSUE TITLE
Language Tour on Mixins refers to the master CHANGELOG for more info

### ISSUE THREAD

**Issue by srawlins** [dart-lang/site-www#1333]
[The language tour](https://www.dartlang.org/guides/language/language-tour#adding-features-to-a-class-mixins) should at least refer to the 2.1.0 CHANGELOG, more of a permalink.

Even better, the canonical source of mixin documentation (outside of the impenetrable spec) should not be the CHANGELOG entry.

But we can start by fixing the CHANGELOG link, pointing it instead to: https://github.com/dart-lang/sdk/blob/2.1.0/CHANGELOG.md#language

**Comment by athomas** [comment]
I couldn't find that link in the Tour. Closing, please re-open if I misunderstood.
