### ISSUE TITLE
Delete examples_archive

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1336]
Original sources for the Language Tour & Lib Tour. We've since adapted the relevant parts of the code and integrated it all into the source found under `examples`.

**Comment by MrBirb** [comment]
@kwalrath Looks like it was deleted?

**Comment by kwalrath** [comment]
> @kwalrath Looks like it was deleted?

Yes, it was. Thanks for letting us know, @MrBirb!
