### ISSUE TITLE
Remove links to old Chinese Dart site

### ISSUE THREAD

**Issue by tianchengman** [dart-lang/site-www#1337]
![image](https://user-images.githubusercontent.com/44338340/52119734-033e4900-2655-11e9-8512-a4f7d18b4919.png)
![image](https://user-images.githubusercontent.com/44338340/52119757-1cdf9080-2655-11e9-955e-cee513f254fe.png)

**Comment by kwalrath** [comment]
An old site that we might have linked to (dartlang.cc) no longer has Dart content.

Although neither dartlang.org nor www.dartdoc.cn (the site we link to) has a link to this old site, _another_ copy of dartlang.org (dart.goodev.org) _does_ link to it.

Unfortunately, I don't think there's anything we can do about this.
