### ISSUE TITLE
Creation of a Videos page

### ISSUE THREAD

**Issue by packtpartner** [dart-lang/site-www#134]
Since videos is the new tool that is catching up in the learning of developers, I would suggest if you could create a Videos page just like the Books page (https://www.dartlang.org/resources/books)

Packt has published a new video on "[Learning Dart](https://www.packtpub.com/web-development/learning-dart-video)" this year. We would appreciate if you could feature this as it intends to help with the learning of the Dart community.

Would love to hear your thoughts on this.

**Comment by packtpartner** [comment]
@leafpetersen could you help me out on this please?

**Comment by Sfshaza** [comment]
Perhaps, in the short term, we could extend the Books page to "Books and Videos".

**Comment by packtpartner** [comment]
@Sfshaza thanks for updating the page and adding the video. Highly appreciated
