### ISSUE TITLE
'Get Started' page issue

### ISSUE THREAD

**Issue by SilvesterSchneider** [dart-lang/site-www#1343]
Page URL: https://www.dartlang.org/guides/get-started
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/get-started.md

Description:

Error compiling to JavaScript:
XMLHttpRequest error.

when click on "RUN"

**Comment by kwalrath** [comment]
I don't have that issue. Can you tell me where you're located and what browser you're using? Thanks!

**Comment by SilvesterSchneider** [comment]
Germany and Google Chrome

Am Do., 7. Feb. 2019, 01:42 hat Kathy Walrath <notifications@github.com>
geschrieben:

**Comment by kwalrath** [comment]
Thanks, @SilvesterSchneider. Do you still see the issue?

/cc @jcollins-g @devoncarew

**Comment by SilvesterSchneider** [comment]
https://dartpad.dartlang.org/fae22cffa7b184b4d27cd96dd633a5af
 
on this link i see this Problem:

Error compiling to JavaScript:
XMLHttpRequest error.

in the console:

POST https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json 403 (Forbidden)

Access to XMLHttpRequest at 'https://dart-services.appspot.com/api/dartservices/v1/compile?alt=json' from origin 'https://dartpad.dartlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by kwalrath** [comment]
Thanks for that info. I'm not seeing the same issue as you are. I wonder if it has to do with your location or your browser configuration.

I _do_ see something weird when I go to https://dartpad.dartlang.org/fae22cffa7b184b4d27cd96dd633a5af (which, for my own notes, is not embedded in any page, but is linked to by the sample in the dartlang.org homepage). At first DartPad looks normal and I can see the pi generation output, but then the page scrolls down, and I can't scroll back up. Nothing appears in the console. I plan to open a separate DartPad issue for this.

Back to the Get Started page... I need to find out who else is having issues with it. I'll ask some people in other places to try it out.

**Comment by kwalrath** [comment]
@SilvesterSchneider could you take screenshots of the issue you're seeing? Thanks!

**Comment by jcollins-g** [comment]
@SilvesterSchneider Also, any information about browser and version would be very helpful.

**Comment by SilvesterSchneider** [comment]
Now it works?!
I think the problem is fixed :)
Thanks a lot


Am Fr., 8. Feb. 2019 um 23:36 Uhr schrieb Janice Collins <
notifications@github.com>:

**Comment by kwalrath** [comment]
I'm glad it's working! Still curious about why it wasn't, but since we can't reproduce it...
