### ISSUE TITLE
'Pub Versioning Philosophy' page issue

### ISSUE THREAD

**Issue by shrike69** [dart-lang/site-www#1344]
Page URL: https://www.dartlang.org/tools/pub/versioning
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/versioning.md

Description: In the paragraph that reads

When you add a dependency to your package, you’ll sometimes want to specify a range of versions to allow. How do you know what range to pick? You need to forward compatible, so ideally the range encompasses future versions that haven’t been released yet. But how do you know your package is going to work with some new version that doesn’t even exist yet?

the third sentence should read

You need to be forward compatible...

**Comment by kwalrath** [comment]
I'll happily fix this typo, but in the future, it might be quicker for you to just edit the page.

**Comment by shrike69** [comment]
Sorry, I thought I was following the correct procedure. I'm happy to fix typos myself. Can you private message me with the info on how to do that?

**Comment by kwalrath** [comment]
You did nothing wrong! We're always happy to accept either issues or PRs for little things like typos. For bigger issues, we prefer some advance notice so we can coordinate. I should update the [CONTRIBUTING](https://github.com/dart-lang/site-www/blob/master/CONTRIBUTING.md) file to be clearer about this.

**Comment by kwalrath** [comment]
Fixed by #1640.
