### ISSUE TITLE
'Search Dart Sites' page issue

### ISSUE THREAD

**Issue by vijayanmmm** [dart-lang/site-www#1347]
Page URL: https://www.dartlang.org/search.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/search.html

Description: Suddenly search is not working, whatever  i search there is no result,

**Comment by kwalrath** [comment]
Strange! Could you attach a screenshot? Can you tell me your location and browser version?

**Comment by kwalrath** [comment]
Closing due to lack of information, but please open a new issue if you're able to provide the info.

**Comment by vijayanmmm** [comment]
Thanks, could be browser issue, i have tried to reproduce the error but could not get the same.
