### ISSUE TITLE
Add documentation style guidance for inline code

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1351]
_From @camsteffen on February 14, 2019 16:49_

The Effective Dart: Documentation page has a [section for code blocks](https://www.dartlang.org/guides/language/effective-dart/documentation#prefer-backtick-fences-for-code-blocks) but there is no guideline for inline code. Issue https://github.com/dart-lang/dartdoc/issues/303 seems to suggest that the `[:code:]` style is the old way.

Should we add a section like the following?

> Note: You may see some docs with inline code written as `[:code:]`. This is the old way of formatting inline code. This style is still supported, but you should prefer using standard markdown style with backticks like `` `code` ``.

_Copied from original issue: dart-lang/dartdoc#1936_

**Comment by kwalrath** [comment]
_From @jcollins-g on February 14, 2019 17:14_

@kwalrath Where should issues like this go?

**Comment by kwalrath** [comment]
In the dart-lang/site-www repo. The ideal way is probably to go to the page and click the bug icon at the top right, but it's also fine to just transfer this bug there.

**Comment by munificent** [comment]
We do have a section saying to use Markdown, which includes some examples of inline backticks. I think that's probably sufficient. The `[: ... :]` is ancient, was invented by a couple of people on the Dart team, and was never known by any significant number of humans on Earth.
