### ISSUE TITLE
A new resource to learn Dart 2 based on latest Dart documentation

### ISSUE THREAD

**Issue by smartherd** [dart-lang/site-www#1353]
This [playlist on youtube](https://www.youtube.com/watch?v=5rtujDjt50I&list=PLlxmoA0rQ-LyHW9voBdNo4gEEIh0SjG-q) provides Dart 2 learning resource for beginners. The course quality is premium.

Kindly update the [publications page](https://www.dartlang.org/resources/books).

**Comment by kwalrath** [comment]
Thanks for the link, @smartherd.

@domesticmouse, @mjohnsullivan, @RedBrogdon: let's talk about how to cover video resources like this one.

**Comment by kwalrath** [comment]
We've decided that the publications page should really be called the books page, and we should (in the not-too-distant future) have a separate Videos page, a la https://flutter.io/docs/resources/videos.

Until we get a Videos page, I'll put a link to this series in https://www.dartlang.org/community#additional-community-resources.

**Comment by smartherd** [comment]
Hi, I also have Flutter course on youtube
https://www.youtube.com/watch?v=fmPmrJGbb6w&list=PLlxmoA0rQ-Lw6tAs2fGFuXGP13-dWdKsB
.
You can run a QA review and technical review. If you like it, put it on
Flutter video resources page.

Thanks,
Sriyank Siddhartha
Pluralsight Author

**Comment by kwalrath** [comment]
> Hi, I also have Flutter course on youtube https://www.youtube.com/watch?v=fmPmrJGbb6w&list=PLlxmoA0rQ-Lw6tAs2fGFuXGP13-dWdKsB . You can run a QA review and technical review. If you like it, put it on Flutter video resources page. Thanks, Sriyank Siddhartha Pluralsight Author

Could you please open a bug for this at https://github.com/flutter/website/issues?

**Comment by kwalrath** [comment]
I'm moving this to the new videos page (#1808).
