### ISSUE TITLE
'Get Started' page issue

### ISSUE THREAD

**Issue by xuongrau** [dart-lang/site-www#1358]
Page URL: https://www.dartlang.org/guides/get-started
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/get-started.md

Reporting a TYPO? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by kwalrath** [comment]
Closing for lack of description.

**Comment by xuongrau** [comment]
thật tuyệt.

Vào Th 5, 21 thg 2, 2019 vào lúc 00:04 Kathy Walrath <
notifications@github.com> đã viết:
