### ISSUE TITLE
Dead links - 404 errors

### ISSUE THREAD

**Issue by LeslieJohnson** [dart-lang/site-www#136]
https://github.com/dart-lang/site-www/blob/master/guides/language/language-tour

Returns 404.

**Comment by Sfshaza** [comment]
@LeslieJohnson, the src for that file is here:
https://github.com/dart-lang/site-www/blob/master/src/_guides/language/language-tour.md

and the URL is here:
https://www.dartlang.org/guides/language/language-tour

Can you tell me where that link came from?

**Comment by LeslieJohnson** [comment]
Not certain, but here's another that gives 404 errors for links. Probably related: https://github.com/dart-lang/site-www/blob/master/src/_guides/language/language-tour.md

**Comment by LeslieJohnson** [comment]
Ok, I'm trying links from the source rather than generated pages. My bad, but it is kinda confusing.

**Comment by Sfshaza** [comment]
Yes, you really should be viewing the site from dartlang.org and not GitHub.

**Comment by LeslieJohnson** [comment]
Found the links. The page: https://github.com/dart-lang/dart-up-and-running-book says it's outdated, and to follow https://github.com/dart-lang/site-www/blob/master/src/_guides/language/language-tour.md and https://github.com/dart-lang/site-www/blob/master/src/_guides/libraries/library-tour.md which in turn point to dead links. I'll take your suggestions about dartlang.org.

**Comment by Sfshaza** [comment]
Thanks, @LeslieJohnson, I'll update that errant README!
