### ISSUE TITLE
Clarify that const isn't necessary for literals in constant context

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1364]
See https://github.com/dart-lang/site-www/pull/1361#pullrequestreview-207830869, where @lrhn points this out. I bet we have similar text in other places: list, map, ....

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/4350 to consolidate issues related to `const` in the language tour. Thanks!
