### ISSUE TITLE
Add set literals to docs where appropriate

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1365]
Library tour, Effective Dart (#1410).

Related: #1257.

**Comment by kwalrath** [comment]
Also search for other examples that could use set literals.

**Comment by ejain** [comment]
Looks like this issue was closed accidentally?

**Comment by kwalrath** [comment]
You're right, it doesn't look like this should be closed.

**Comment by kwalrath** [comment]
This bug will be fixed once we start using pedantic 1.9.0, which added prefer_collection_literals. ([Changelog](https://pub.dev/packages/pedantic#-changelog-tab-))

Closing in favor of #2160.
