### ISSUE TITLE
'Operator table' omits `>>>` and should be described as non-normative

### ISSUE THREAD

**Issue by eernstg** [dart-lang/site-www#1372]
The language tour [operator table](https://www.dartlang.org/guides/language/language-tour#operators) matches the appendix of the language specification with one exception: The operator `>>>` has been added (it is in the language specification, but is not yet implemented), and it does not occur in the table. Similarly, the corresponding compound assignment operator `>>>=` is missing.

We just had an issue (https://github.com/dart-lang/sdk/issues/36055) where the language tour operator table was use as a source of truth for a question about parsing.

So I think it would be useful to mention in the section that contains the operator table (as it is in the language specification appendix) that this table is not normative, and parsing questions should be resolved by consulting the grammar rules. I guess it's enough to say the latter, if the word 'normative' does not fit in with the preferred style in the language tour. I've added labels 'bug' for the missing operator and 'enhancement' for the 'not normative' part. Hope that works. ;-)

**Comment by kwalrath** [comment]
Thanks for the report. I'll add the caveat and (once it's implemented, if not before) the operator.

Related issue: #1371
