### ISSUE TITLE
http://www.dartlang.cc跳到了赌博网站呀

### ISSUE THREAD

**Issue by lifetin** [dart-lang/site-www#1377]
http://www.dartlang.cc跳到了赌博网站呀
![11](https://user-images.githubusercontent.com/10474968/53812296-23d02a80-3f96-11e9-8274-670d7d307b96.png)

**Comment by kwalrath** [comment]
Thanks for the report! We no longer link to dartlang.cc, so I don't think there's anything we can do in this repo.

/cc @mit-mit in case there's anything else we can/should do about this domain.
