### ISSUE TITLE
'Futures and Error Handling' page issue

### ISSUE THREAD

**Issue by feinstein** [dart-lang/site-www#1378]
Page URL: https://www.dartlang.org/guides/libraries/futures-error-handling
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/libraries/futures-error-handling.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

this page seems to be an important topic, still there's a note that "Some of the content of this page might be out of date.", it would be nice if someone could make a review and update the page.

**Comment by kwalrath** [comment]
Agreed. I'm working on a codelab that'll cover this, but we also need to update this doc.

**Comment by kwalrath** [comment]
Related issue: #512

**Comment by kwalrath** [comment]
The dart.dev version of this page is no longer marked obsolete.
