### ISSUE TITLE
Dart calculating problem

### ISSUE THREAD

**Issue by BillChan96** [dart-lang/site-www#1379]
When i try to calculating by a formula: double * (integer | double) = ???
Ex:
Case 1: 0.179 * 100 = 17.9 (right)
Case 2: 0.169 * 100 = 16.900000000000002 (??? i think result equal is 16.9)

How do fix this issue?

**Comment by kwalrath** [comment]
Interesting question, but this issue tracker isn't the right place to get an answer. I'd suggest one of the resources from the community page, such as Gitter or StackOverflow: http://dartlang.org/community#join-the-conversation
