### ISSUE TITLE
'Getting Started with Pub' page issue

### ISSUE THREAD

**Issue by sndrjyplm** [dart-lang/site-www#1380]
Page URL: https://www.dartlang.org/tools/pub/get-started
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/get-started.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by kwalrath** [comment]
Closing for lack of description.
