### ISSUE TITLE
Clarify ambiguity about explicit types for parameters with initialization expressions

### ISSUE THREAD

**Issue by tetkin-g** [dart-lang/site-www#1387]
Given the following method (or constructor):

`void foo({color = SomeColorEnum.orange})`

The `color` parameter should have an explicit type, but Effective Dart doesn't explicitly cover that scenario.

Readers may expect it to follow the rule about using [implicit typing for variables / fields that have initializers](https://www.dartlang.org/guides/language/effective-dart/design#avoid-type-annotating-initialized-local-variables), but the compiler doesn't actually apply that same kind of inference for parameters.

In the case of constructors, they may think that the rule about [not type-annotating initializing formals](https://www.dartlang.org/guides/language/effective-dart/usage#dont-type-annotate-initializing-formals) applies, but when it's a regular parameter that doesn't apply either. This can be easy to mistake when changing code like:

`Thing({this.foo = 123})`

to something like:

`Thing({foo = 123}) : _foo = foo;`

**Comment by kwalrath** [comment]
@munificent what's your take on this?

**Comment by munificent** [comment]
Yes, I suggested @tetkin-g file this. :) It's a complete oversight in "Effective Dart". It says to annotate when inference "fails", but parameters are a case where there's no attempt at inference at all. The language simply lets you omit the annotation and puts in dynamic instead. We should call that case out explicitly.
