### ISSUE TITLE
Header is not rendered properly in IE11

### ISSUE THREAD

**Issue by gonzalopezzi** [dart-lang/site-www#14]
The logo and the menu options in the header, are outside of the header in IE11: 
![dartlangorg_header_ie11](https://cloud.githubusercontent.com/assets/3994908/16868477/171e965c-4a78-11e6-9291-77ff151b261f.JPG)

**Comment by gonzalopezzi** [comment]
More information about my system: 

- OS: Windows 7
- IE11 version: 11.0.9600.18314

**Comment by filiph** [comment]
Thanks for the report. Will look at this.

**Comment by kwalrath** [comment]
I'm going to close this, since less than 1% of our visitors are using IE.
