### ISSUE TITLE
Link to download Dartium gives 404 error

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-www#140]
_From @alexmugford on September 8, 2016 19:40_

My Dartium seems to have expired, and gives me a link to download a new one 

`https://www.dartlang.org/tools/dartium`

This page however gives back a 404: Page Not Found.

Also, going to `https://webdev.dartlang.org/tools/dartium` and choosing "Dartium for Windows" gives an error, so I can't download it.
![dartiumdownload](https://cloud.githubusercontent.com/assets/9115310/18364143/42e73ee0-75db-11e6-86bd-1172a0eb8a09.PNG)

_Copied from original issue: dart-lang/sdk#27281_

**Comment by anders-sandholm** [comment]
I can repro the 404 error. Will move this issue to the dartlang.org repo.

"Dartium for Windows" works fine for me. @alexmugford , would you try again? If it still does not work, would be great to know what browser you're using.

**Comment by alexmugford** [comment]
The download seems to be working fine for me now...thanks!

**Comment by Sfshaza** [comment]
We need to add this link to our redirects for dartlang.

**Comment by filiph** [comment]
Please do so in the spreadsheet, I'll fix asap.

**Comment by filiph** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/5edff05518d74264e07fb9384b3c3af5422bce6b. Thanks @alexmugford for reporting!

**Comment by Sfshaza** [comment]
I've added it to the spreadsheet.

**Comment by alexmugford** [comment]
Thanks for fixing it so quickly! :)
