### ISSUE TITLE
add info about trailing commas

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1404]
Trailing commas are allowed in places like list literals, set literals, map literals, enum declarations, argument lists, and parameter lists. I think that the example at the bottom of https://www.dartlang.org/guides/language/language-tour#sets is the first usage of a trailing comma in the language tour, but maybe we should introduce them in the list literal section.

We should mention that it doesn't matter whether the trailing comma is there or not, but it can help prevent errors when copy-pasting code.

More info: https://github.com/dart-lang/sdk/issues/26644

**Comment by kwalrath** [comment]
Thanks for the PR, #2716! Do you think we should add something about nonliterals — enums, arg lists, param lists?

**Comment by micpap25** [comment]
I agree that we should mention that you can you trailing commas for those other types. I'll add to my PR, let me know what you think.
