### ISSUE TITLE
Mention set literals in effective dart

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/site-www#1410]
Page URL: https://www.dartlang.org/guides/language/effective-dart/usage
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/usage.md

https://www.dartlang.org/guides/language/effective-dart/usage#do-use-collection-literals-when-possible
This mentions List and Map literals, but not the new Set literal.

**Comment by kwalrath** [comment]
Thanks for the report. I'm going to close this in favor of #1365.
