### ISSUE TITLE
Contributing with translations

### ISSUE THREAD

**Issue by yohanhyunsungyi** [dart-lang/site-www#1424]
Hello!

I am currently working as an iOS Developer in the U.S but also using Dart language to create an app. I want to contribute to translating this documents of Plutter into Korean which is my mother language. I saw the issue #645 , and there I saw that it is okay to register my domain and put some translated documents about some small subset. 
Therefore. If you agree, I would like to register the dartlang.co.kr domain and post a Korean translation. Please advise.

Also if it is eligible,  could my website be the official translation site for Dart?

**Comment by kwalrath** [comment]
We'd be very happy to have you translate the site and to point to it if it's the best resource for Korean Dart developers. I don't know what the policy is on domain names, though. @filiph maybe you know?

**Comment by YohanHyunsungYi** [comment]
Thank you @kwalrath ! 
Anyways, I have already started translate the site for my personal studying use. Once I finalize it I can share it with you guys :)
let me know if there is a policy on domain name. :)
I am so happy to be able to contribute to the Dart language environment.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/1424 where we track site/infrastructure support for surfacing multiple languages. Thanks!
