### ISSUE TITLE
Remove the word "Lame" from docs

### ISSUE THREAD

**Issue by cphoenix-google** [dart-lang/site-www#1427]
"We've got to type x four times here define a field. Lame. We can do better:"

https://github.com/dart-lang/site-www/blob/master/src/_guides/language/effective-dart/usage.md

**Comment by kevmoo** [comment]
CC @munificent 

Are we worried that this won't be understandable by non-native speakers?

I kind of like the casual tone – FWIW.

**Comment by kevmoo** [comment]
CC @kwalrath

**Comment by cphoenix-google** [comment]
It's offensive / hurtful to some people. Just seems better not to use it
this way. https://en.wikipedia.org/wiki/Ableism#The_Pitied_Character

**Comment by kwalrath** [comment]
I think we can just remove the entire sentence ("Lame."). @cphoenix-google you're welcome to make this change yourself by clicking the doc icon at the top of the page, or we can do it the next time we get a chance.

**Comment by cphoenix-google** [comment]
I did https://github.com/dart-lang/site-www/pull/1428 but got an error on the pull request, and I can't remember whether Googlers are or aren't supposed to sign the CLA.

**Comment by kwalrath** [comment]
@cphoenix-google I think you just need to register your GitHub account at go/github.

**Comment by kwalrath** [comment]
@cphoenix-google did you try registering your GitHub account at go/github?

**Comment by munificent** [comment]
Looks like this is fixed now. :)
