### ISSUE TITLE
dart-popover dialogs have issues

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#143]
Two issues:
1. The dialog is cropped if it's too near the edge of the frame. For example, on https://www.dartlang.org/tutorials/dart-vm/cmdline I had to move "import dart:async;" to the third line. It really should be on the first line, but the top of the dialog was chopped off. (Once this bug is fixed, move this import back to the top.)
   
   Also, make your window narrow and hover the cursor over "async" on the "Future dcat" line. The right of the dialog is cropped.
2. The pop-over text highlighting causes the text to be mis-aligned. Look at the 3 import statements. The highlighted statement "import dart:async" doesn't line up with the first two.

Pull requests welcome!

@kwalrath

**Comment by parlough** [comment]
The tool seems to put the popover below now if it doesn't have space. Either way, we likely will remove/replace this functionality (https://github.com/dart-lang/site-www/issues/2316).
