### ISSUE TITLE
Is _speed really private?

### ISSUE THREAD

**Issue by CevG33ko** [dart-lang/site-www#1438]
https://codelabs.developers.google.com/codelabs/from-java-to-dart/index.html?index=..%2F..index#1

Hi just doing the dart intro and I got irritated py the "private" _speed variable.
if "_speed" from the bicycle class is private, shouldnt I be unable to change its value manually in the main method?

> class Bicycle {
>   @override
>   String toString() => 'Bicycle: $_speed mph';
>   int cadence;
>   int _speed=0;
>   int gear;
>   Bicycle(this.cadence, this.gear);
>   int get speed => _speed;
> }
> 
> void main() {
>   var bike = Bicycle(2,0);
>   print(bike);
>   bike._speed=1;
>   print(bike);
> }

The console reads:
```
Bicycle: 0 mph
Bicycle: 1 mph
```

**Comment by CevG33ko** [comment]
I am using dartpad for this outcome.

**Comment by kwalrath** [comment]
Hi, @CevG33ko. The variable is library-private, and main() is in the same library. I should fix this when I update the codelab (before I/O). Thanks for the report!

Closing in favor of #1135.

**Comment by CevG33ko** [comment]
Got it! Thanks!
