### ISSUE TITLE
Add context on pre-releasing of packages to 'Publishing a Package' page

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#1442]
Page URL: https://dart.dev/tools/pub/publishing
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/publishing.md

If you publish a package version `1.0.0` on `pub.dartlang.org`, and then later publish `2.0.0-dev|alpha|beta...` then it'll show up as a pre-release. That is `1.0.0` will remain the primary version advertised on the package page `pub.dartlang.org/packages/<package>`, documentation and package score will still be computed based on `1.0.0`.

However, a link to the page for `2.0.0-dev...` (the pre-released package) will be displayed on the package page `pub.dartlang.org/packages/<package>`. And documentation and package scores will still be generated for the pre-released package version, but low package scores here won't affect search results or show up on the primary package package (thus, affecting reputation).

Whenever your developing a package, it makes sense to always publish it as a pre-release first, to see how the documentation is generated, what the package score is, and fix potential nits that show up in markdown or other places. It's particularly useful when publishing a package that depends on a -dev version of the dart-sdk.

**Comment by atsansone** [comment]
@jonasfj : I believe this might have been fixed in https://github.com/dart-lang/site-www/pull/5706. If not, could you clarify the change you want to see made and reopen? Thanks.
