### ISSUE TITLE
'Fixing Common Type Problems' page issue

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [dart-lang/site-www#1450]
Page URL: https://www.dartlang.org/guides/language/sound-problems
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/sound-problems.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'Iterable<String>'

**Comment by kwalrath** [comment]
@dharanidharandharmasivam can you explain a bit more where you saw this? A code example (perhaps a gist) would be very helpful.

**Comment by kwalrath** [comment]
Closing due to lack of info. If you get the repro info, please add it to a comment and I'll reopen this bug.
