### ISSUE TITLE
Fix or remove html_proof.rb

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1461]
As of April 16, 2019, `./deploy/html_proof.rb` fails. It hasn't changed, so I suspect a ruby change. Here's the output (with `./` substituted for my directory path details):

```
$ ./deploy/html_proof.rb 
./deploy/urls/get_all.rb:3:in `require_relative': cannot load such file -- 
./deploy/urls/old_site_urls (LoadError)
	from ./deploy/urls/get_all.rb:3:in `<top (required)>'
	from ./deploy/html_proof.rb:7:in `require_relative'
	from ./deploy/html_proof.rb:7:in `<main>'
```

**Comment by parlough** [comment]
This was removed in https://github.com/dart-lang/site-www/commit/99fd6c7e61d2dc70809bed4b3dd6efe8fd5b2470
