### ISSUE TITLE
'A Tour of the Dart Language' page issue

### ISSUE THREAD

**Issue by zhengger** [dart-lang/site-www#1466]
Page URL: https://www.dartlang.org/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
When I increased the page size to 120%, the left side table disappeared. Can you cancel such settings so that I can check the content anytime? 
Or could you add buttons to hide/show two sides which will be much more convenient for reading?
Thanks.

**Comment by kwalrath** [comment]
Thanks for the feedback, @zhengger. The left-side navigation is still available via the "hamburger" menu at the top left. Does that work for you?

**Comment by zhengger** [comment]
> Thanks for the feedback, @zhengger. The left-side navigation is still available via the "hamburger" menu at the top left. Does that work for you?

Thank you for your prompt reply, kwalrath!
I cannot find the "hamburger" menu. My browser is Firefox. I read flutter page at 120% size as well which works well for me. Here are two screenshots you can check out.  
![Pasted Graphic](https://user-images.githubusercontent.com/2143234/56578728-eafd1b00-6600-11e9-8eae-b9ad1c6321ce.png)
![Pasted Graphic 1](https://user-images.githubusercontent.com/2143234/56578920-59da7400-6601-11e9-862c-8561fef7962e.png)

Thanks again.

**Comment by kwalrath** [comment]
I'm going to close this because we've completely redone the site implementation. If it's still an issue, could you please comment?
