### ISSUE TITLE
Dart tools page doesn't link to documentation about the "dart" command

### ISSUE THREAD

**Issue by skybrian** [dart-lang/site-www#147]
On this page:
https://www.dartlang.org/tools

I expected to see a link to this page:
https://www.dartlang.org/dart-vm/tools/dart-vm

More generally, it would be nice if we had a list of the "man pages" for each command included in the Dart SDK.

**Comment by srawlins** [comment]
This link now exists. https://www.dartlang.org/tools/ now contains a link text "Dart VM tools" linking to https://www.dartlang.org/dart-vm/tools.
