### ISSUE TITLE
Create new article/page about benchmarking

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1475]
We're retiring the [benchmarking article](https://github.com/dart-lang/site-www/blob/27bd825939507669a1df2431f22def6f6ff93a70/src/_articles/server/benchmarking.md), which was at articles/server/benchmarking, because it's untested and out of date. We should replace it.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/site-www/issues/4351
