### ISSUE TITLE
Recommend "?? false" and "?? true"

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#1476]
There are a few places in the language where "Boolean conversion" happens — where you use a value to determine whether or not to execute some code: if conditions, while conditions, operands to `&&` and `||`, etc. That conversion throws an exception if the value is null. Unlike other scripting languages, we don't treat null as "falsey".

That means when users do have an expression that could evaluate to null, they need to wrap it in something that turns it into true or false, depending on what they want it to represent. There are a couple of common idioms:

```dart
if (nullableCondition ?? false) // null is falsey.
if (nullableCondition ?? true) // null is truthy.

if (nullableCondition == true) // null is falsey.
if (nullableCondition == false) // null is truthy.

if (nullableCondition != false) // null is falsey.
if (nullableCondition != true) // null is truthy.
```

All are somewhat common. I think "Effective Dart" should encourage the first two. My arguments are:

* The `??` operator makes it clear that there is something to do with *null* going on. The others could be comparing objects of other arbitrary types.

* It's actually pretty confusing to mentally work through the Boolean logic to figure out what the other examples even mean. The fact that `== true` mentions "true" but means "treat null as *false*" is particularly opaque. But the fact that `!= true` means that you have to do the negation in your head too is also confusing.

**Comment by lrhn** [comment]
Also:
* Expressions like `if (something == true) ...` or `if (something != false) ...` are semi-commonly seen as mistakes (unnecessary code) for people who are not used to working with boolean values, a superfluous check on a non-nullable boolean expression. 

It's easier to fix those mistakes when the code is never to be used at all. I mistook it for a mistake in code reviews the first few times I saw the pattern.

We should definitely recommend the `??` versions and discourage comparison to boolean values everywhere.
