### ISSUE TITLE
Update dart2js references to (possibly) refer to dartdevc

### ISSUE THREAD

**Issue by skybrian** [dart-lang/site-www#148]
DDC is included in the latest  release (1.19.1) as bin/dartdevc, but seems to be undocumented? Doing a Google Search doesn't find a corresponding "man page" describing its flags.

**Comment by kwalrath** [comment]
cc @vsmenon 

These docs probably belong on [webdev.dartlang.org](webdev.dartlang.org). The most current docs I could find are in the dart-lang/sdk repo, but they haven't been updated since DDC moved into the SDK:

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/USAGE.md

For the record, Vijay gave a talk about DDC at Dart Dev Summit 2016. Here's the [video](https://youtu.be/oH6czEQwHdE?list=PLOU2XLYxmsILKY-A1kq4eHMcku3GMAyp2).

**Comment by Sfshaza** [comment]
We've added:

* https://webdev.dartlang.org/tools/dartdevc

More info will be forthcoming on how to configure the Dart plugin for JetBrains but, as a short summary:

* The pubspec files for the stagehand templates have a compiler tag that you should uncomment.
* Go into Edit Configurations in WebStorm and change your browser to Chrome.

**Comment by kwalrath** [comment]
The following files mention dart2js:

_articles/dart-vm/snapshots.md
_articles/language/emulating-functions.md
_articles/libraries/reflection-with-mirrors.md
_articles/libraries/serialization.md
_guides/language/language-tour.md
_guides/language/sound-dart.md
_guides/language/sound-faq.md
_guides/libraries/library-tour.md
_guides/libraries/private-files.md
resources/synonyms/assets/synonyms.dart.js
resources/synonyms/assets/synonyms.dart.js.map
resources/synonyms/assets/synonyms.dart.precompiled.js
tools/jetbrains-plugin.md
tools/pub/assets-and-transformers.md
tools/pub/pubspec.md
tools/pub/transformers/index.md
tools/sdk.md

**Comment by Sfshaza** [comment]
Thanks for compiling this list, @kwalrath. I've added this info to the [spreadsheet](https://docs.google.com/a/google.com/spreadsheets/d/1oIzCK7OU7gxgcL6rUcHHZeVVQTKCLPoB49KidPJgZs8/edit?usp=sharing).

**Comment by Sfshaza** [comment]
Status of these updates:

<s>_articles/dart-vm/snapshots.md</s>&mdash;Article deleted and now redirects to the wiki page.
_articles/language/emulating-functions.md
_articles/libraries/reflection-with-mirrors.md
_articles/libraries/serialization.md
_guides/language/language-tour.md
_guides/language/sound-dart.md
_guides/language/sound-faq.md
_guides/libraries/library-tour.md
_guides/libraries/private-files.md
resources/synonyms/assets/synonyms.dart.js
resources/synonyms/assets/synonyms.dart.js.map
resources/synonyms/assets/synonyms.dart.precompiled.js
tools/jetbrains-plugin.md
tools/pub/assets-and-transformers.md
tools/pub/pubspec.md
tools/pub/transformers/index.md
tools/sdk.md

**Comment by anders-sandholm** [comment]
Should this be moved to site-webdev?

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#1384

**Comment by chalin** [comment]
@anders-sandholm: this issue seems to have grown to cover two topics. I've created dart-lang/site-webdev#1384 to track those aspects that are specific to the dartdevc page on site-webdev.

I'll leave this issue open to track the cleanup of the site-www files mentioned above.

**Comment by chalin** [comment]
@anders-sandholm: this issue seems to have grown to cover two topics. I've created dart-lang/site-webdev#1384 to track those aspects that are specific to the dartdevc page on site-webdev.

I'll leave this issue open to track the cleanup of the site-www files mentioned above.

**Comment by kwalrath** [comment]
I just did a survey of site-www pages that mention dart2js or dartdevc, and all remaining references look legit to me. My notes follow.

I'll open an issue to follow up on www.dartlang.org/tools/pub/package-layout and www.dartlang.org/guides/libraries/create-library-packages.

Pages that mention dart2js:
- src/tools/sdk/index.md
  - https://www.dartlang.org/tools/sdk 
  - LGTM
- src/_articles/language/emulating-functions.md
  - https://www.dartlang.org/articles/language/emulating-functions
  - LGTM (doesn’t mention dartdevc, but that seems OK)
- src/_articles/language/mixins.md (as Dart2js)
  - https://www.dartlang.org/articles/language/mixins
  - LGTM
- src/_articles/libraries/serialization.md
  - https://www.dartlang.org/articles/libraries/serialization
  - LGTM (doesn’t mention dartdevc, but that seems OK)
- src/_guides/language/language-tour.md
  - https://www.dartlang.org/guides/language/language-tour
  - LGTM
- src/_guides/libraries/private-files.md
  - https://www.dartlang.org/guides/libraries/private-files
  - LGTM (doesn’t mention dartdevc, but that seems OK)
- src/_shared/tools/sdk/index.md
  - https://www.dartlang.org/tools/sdk
  - LGTM

Pages that mention dartdevc:
- src/tools/sdk/index.md
- src/tools/pub/package-layout.md
  - https://www.dartlang.org/tools/pub/package-layout
  - LGTM, although I should check whether the note still applies to web (and whether it applies beyond web).
- src/tools/analyzer.md
  - https://www.dartlang.org/tools/analyzer 
  - LGTM
- src/_articles/language/mixins.md
- src/_guides/language/analysis-options.md
  - https://www.dartlang.org/guides/language/analysis-options
  - LGTM
- src/_guides/language/language-tour.md
- src/_guides/language/sound-dart.md
  - https://www.dartlang.org/guides/language/sound-dart
  - LGTM
- src/_guides/libraries/create-library-packages.md
  - https://www.dartlang.org/guides/libraries/create-library-packages
  - LGTM, but see note above for src/tools/pub/package-layout.md
- src/_shared/tools/sdk/index.md
- src/dart-2.md
  - https://www.dartlang.org/dart-2
  - LGTM
