### ISSUE TITLE
print styles need work

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#149]
When you print out a page, you see all kinds of stuff that you shouldn't—headers, footers, and more.

**Comment by kwalrath** [comment]
Partially fixed by #150. I should apply these fixes to webdev.dartlang.org, as well.

Some other print format issues I noticed:

* Notes should have a box around them, but don't. They just look indented for no reason (especially in notes where there's no bold title to lead off... we really should make a point of doing that). For an example, see https://www.dartlang.org/tools/pub/cmd.

* In Canary, at least, the printout often has blank pages at the end. For example, https://www.dartlang.org/tools/pub/cmd has 3 pages of content followed by 4 blank pages.

**Comment by Sfshaza** [comment]
Another issue. Highlighted text in code blocks doesn't display.

**Comment by kwalrath** [comment]
Another issue: local URLs print (in parens) after their link, but external URLs don't. If we were to differentiate, the opposite should be true. I'm inclined to just underline the link text and NOT provide the URL in the printed version. The external link icon could probably be dropped, too.

**Comment by kwalrath** [comment]
I'm working on some fixes... should have a PR soon.

**Comment by kwalrath** [comment]
The issues might be fixed... but I'm not sure. I'd love for someone else to take a look and see what we could do to improve.

**Comment by Sfshaza** [comment]
I've looked at several pages on www.dartlang. I brought up the print panel, and viewed the preview there - I didn't actually print.

* There are still no boxes around notes. (same as reported)
* Local URLs still display, but you only see the link icon for external links. (same as reported)

Overall, I think the output looks pretty good!

**Comment by Sfshaza** [comment]
Oh, the table in the Get Started page doesn't look that great, but I doubt this is a page that will be printed much.

**Comment by kwalrath** [comment]
There might still be a few ways we can improve print styles (maybe code highlighting?), but we can file individual bugs for those.
