### ISSUE TITLE
Searching in omnibox loses the search terms

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#15]
1. Go to the Chrome omnibox.
2. Type "dartlang.org", and then tab.
3. Type a search term (e.g. Effective Dart) and then return/enter.

You'd expect to be taken to search results as if you did the search using the www.dartlang.org search field.

Instead, you're taken to a blank search page, and you have to re-enter the search.

**Comment by kwalrath** [comment]
This probably something to do with it replacing the existing site and/or search engine. Per https://productforums.google.com/forum/#!topic/chrome/sXuF-bwkvyk, I tried deleting all Dart search engines from Chrome search engines. The webdev search engine wasn't in there, though, so I suspect there's either a big delay or something off about the new search engines. Perhaps they don't support OSD by default? Perhaps they use POST and need to use query strings instead?

**Comment by Sfshaza** [comment]
I just tried the steps in the original bug, and it worked great.  Closing.
