### ISSUE TITLE
remove bad link

### ISSUE THREAD

**Issue by fanyuedong** [dart-lang/site-www#1519]
The link(旧的 Dart 中文网，包含更多中文[http://old.dartlang.cc/]) at the bottom of the site is wrong

**Comment by kwalrath** [comment]
@fanyuedong can you give me the URL for a page that this link appears on?

**Comment by fanyuedong** [comment]
Sorry, I got it wrong. the bad link is in http://dart.goodev.org. chinese website, i found the issues link in it's bottom.i will close this issue. sorry

**Comment by kwalrath** [comment]
OK, thanks for following up so quickly!
