### ISSUE TITLE
Update links to language proposals

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1553]
#1550 has links to two language proposals that will presumably be moved once 2.3 is on stable channel. I'm creating this reminder because I don't think our link checker will notice that change.

**Comment by kwalrath** [comment]
All 3 references to dart-lang/language that I find in the tutorial are still valid. I'm going to leave this open as a reminder to periodically check these links by hand and maybe update them someday. It's not ideal, but it's better than nothing. The relevant links:

* https://github.com/dart-lang/language/blob/master/accepted/2.3/spread-collections/feature-specification.md
* https://github.com/dart-lang/language/blob/master/accepted/2.3/control-flow-collections/feature-specification.md
* https://github.com/dart-lang/language/blob/master/accepted/2.1/super-mixins/feature-specification.md#dart-2-mixin-declarations

Found with the following search:

```
$ fgrep "dart-lang/language" src/_guides/language/language-tour.md 
```

Generalizing that search (`fgrep -Rl "dart-lang/language" src`) finds uses in the FAQ and spec page, as well, but those appear to be legitimate links to directories, rather than to individual feature discussions.

**Comment by kwalrath** [comment]
Just confirmed that those 3 links are still valid. The super-mixins spec link is no longer in the language tour.

I also did a wider search to find all possible references in the site:

```
fgrep -R "dart-lang/language/blob" src
```

Here are the results, all of which are still valid links:
src/tools/diagnostic-messages.md:[definiteAssignmentSpec]: https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md
src/null-safety/unsound-null-safety.md:   [package configuration file]: https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md
src/null-safety/understanding-null-safety/index.md:[flow analysis]: https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md
src/null-safety/migration-guide.md:   [package configuration file]: https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md
src/faq.md:[language process]: https://github.com/dart-lang/language/blob/master/doc/life_of_a_language_feature.md
src/_guides/language/extension-methods.md:[specification]: https://github.com/dart-lang/language/blob/master/accepted/2.7/static-extension-methods/feature-specification.md#dart-static-extension-methods-design
src/_guides/language/effective-dart/style.md:[extensions design document.]: https://github.com/dart-lang/language/blob/master/accepted/2.7/static-extension-methods/feature-specification.md#dart-static-extension-methods-design
src/_guides/language/spec.md:[LaTeX file]: https://github.com/dart-lang/language/blob/master/specification/dartLangSpec.tex
src/_guides/language/language-tour.md:[collections proposal]: https://github.com/dart-lang/language/blob/master/accepted/2.3/control-flow-collections/feature-specification.md
src/_guides/language/language-tour.md:[spread proposal]: https://github.com/dart-lang/language/blob/master/accepted/2.3/spread-collections/feature-specification.md
src/_guides/language/evolution.md:[language versioning feature]: https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/feature-specification.md#dart-language-versioning

**Comment by atsansone** [comment]
@munificent : Are these still going concerns?

**Comment by parlough** [comment]
This was used as a tracking issue to occasionally update the links as they moved to accepted or a specific release.

It is still a going issue, however we currently have no outdated feature specification links as we've kept them updated. I'd be fine closing this and having this simply as part of our release process.

**Comment by munificent** [comment]
Yes, the other side of this is that we on the language team should have some explicit task during the release process to move language proposals from `future-releases/` into the corresponding version directory once they get released. There are a bunch of stale ones in there that should be moved already.

**Comment by atsansone** [comment]
@parlough : I'd rather update this to part of the release process. Could you make a note of this and close this issue?

**Comment by parlough** [comment]
Yeah it's part of my release process, but I just added a note to include it as a check/step in https://github.com/dart-lang/site-www/wiki/(WIP)-Release-documentation-process-for-technical-writers.
