### ISSUE TITLE
Conditional imports is not covered in the language tour

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#1569]
Page URL: https://www.dartlang.org/guides/language/language-tour
Page source: [src/_guides/language/language-tour.md](https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md).

Conditional imports is not covered by the language tour. Conditional imports are usually done like:

```dart
import 'src/impl_stub.dart'  // stub implementation
    if (dart.library.io) 'src/impl_io.dart' // implementation using dart:io
    if (dart.library.html) 'src/impl_web.dart'; // implementation using dart:html|js
```

It would be nice to cover this in the language tour as the specification is hard to read. A few good examples of what you can make conditions on would also be useful, as this is not obvious.

@lrn, please correct me if this is not a stable language feature?

**Comment by mit-mit** [comment]
@kwalrath what the needs-info part?

**Comment by kwalrath** [comment]
I think I was waiting to hear if this was a stable feature.

**Comment by jonasfj** [comment]
Hmm, I might have pinged the wrong LRN, sorry..

@lrhn, is this something that is stable, and can we encourage developers to adopt it?

**Comment by mit-mit** [comment]
Related issue (where I just commited to getting more info from lang. team): https://github.com/dart-lang/site-www/issues/1750

**Comment by AppleEducate** [comment]
here is an example project that i use this with for desktop, mobile and web: https://github.com/AppleEducate/moor_shared

**Comment by rydmike** [comment]
Great example @AppleEducate, it solved my issue in https://github.com/flutter/flutter/issues/40488

**Comment by AppleEducate** [comment]
Thanks 😎💪🏻

**Comment by leafpetersen** [comment]
This is a shipped and specified feature, and there are no current plans to deprecate it.

**Comment by SwissCheese5** [comment]
This still requires documentation. I'm finding problems with conditional imports.

This is my firebase_access.dart class
```
export 'unsupported_firebase.dart' if (dart.library.io) 'firebase_mobile.dart' if (dart.library.html) 'firebase_web.dart';
```

This class works for firebase_mobile.dart but does NOT work for firebase_web.dart.
I don't know why, I tried printing an line for each, it prints for firebase_mobile on mobile, does NOT print for firebase_web.

This is firebase_web.dart (using the firebase_web plugin) :
![image](https://user-images.githubusercontent.com/7407478/68547948-7b117f00-03f0-11ea-9bb7-d609dd763a61.png)
In the following code, we have
```dart
    print("firebase web init");
```
while in firebase_mobile.dart (using the official firebase plugin):
![image](https://user-images.githubusercontent.com/7407478/68547977-bca22a00-03f0-11ea-8e22-bea970b782fc.png)
we have 
```dart
    print("firebase mobile init");
```

Now in my main class, I'm doing the following:
![image](https://user-images.githubusercontent.com/7407478/68547980-cfb4fa00-03f0-11ea-9d60-a0c11d8d6bb0.png)

Note the import firebase_access.dart

In both mobile and web, it prints `beginning init`
However on mobile, it prints `firebase mobile init` after while on web, it does NOT print `firebsae web init`

I'm unsure why. The lack of documentation is problem.

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
I see no problem with the conditional export. My guess is that the problem lies elsewhere.
If the program *compiles*, then it has exported *some* version of the library.
Does the `unsupported_firebase.dart` file contain any prints, so you can see if it picks that incorrectly?

**Comment by SwissCheese5** [comment]
@lrhn Yes it does:

![image](https://user-images.githubusercontent.com/7407478/68593012-1f50ff80-049d-11ea-89c8-34acea8d8139.png)
It's never printed.

**Comment by SwissCheese5** [comment]
Should I open a new issue for this?

**Comment by mit-mit** [comment]
Yes, please open a new issue (the present bug tracked documentation), with the smallest set of repro steps you have. Please open it in the SDK repo: https://github.com/dart-lang/sdk/issues
