### ISSUE TITLE
'Effective Dart: Style' page need to be updated for Unified Collections

### ISSUE THREAD

**Issue by alanhzhao** [dart-lang/site-www#1575]
Page URL: https://www.dartlang.org/guides/language/effective-dart/style
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/style.md

Description of issue:

[Unified Collections](https://github.com/dart-lang/language/blob/master/accepted/future-releases/unified-collections/feature-specification.md) adds Control Flow Collections to the language. The rule "DO use curly braces for all flow control structures" needs to be updated to mention this syntax, since it also does not use curly braces.

**Comment by kwalrath** [comment]
What do you say, @munificent? I know that new guidelines usually lag the language, but this does seem like it could be confusing.
