### ISSUE TITLE
Need breadcrumbs for some doc sets.

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#159]
This is also true for webdev.

Some of our doc sets could use breadcrumbs so we can easily pop to the top. Currently, the only ways to do this are to either edit the URL or click the "prev page" link repeatedly until we reach the top.

This is particularly true for:
- pub docs
- ~ng2 code lab~
- Effective Dart

**Comment by Sfshaza** [comment]
Also: https://github.com/dart-lang/site-www/issues/396

**Comment by kevmoo** [comment]
Please!

**Comment by Sfshaza** [comment]
@kwalrath, can we prioritize this? Kevmoo, I'm working on Flutter these days.

I'm wondering if Patrice can help out?

**Comment by chalin** [comment]
Yes, Kathy agreed (offline). I'll be working on this soon.

**Comment by Sfshaza** [comment]
Thanks!

**Comment by chalin** [comment]
[Firebase](https://firebase.google.com/docs/storage/web/start) site example of breadcrumbs:
<img src="https://user-images.githubusercontent.com/4140793/31575127-885358fc-b0ad-11e7-80df-2069af5d517e.png" width="300">

[Another example](https://developers.google.com/web/tools/lighthouse/):
<img width="453" alt="screen shot 2017-10-14 at 07 16 45" src="https://user-images.githubusercontent.com/4140793/31575234-d26b981c-b0af-11e7-9624-cb2ca41c9f36.png">

Note that the breadcrumb line simply gets truncated for narrow displays.

**Comment by Sfshaza** [comment]
I think our deepest level is tools > pub > cmd > pub-uploader, so it doesn't go too deep and where it does, we tend to have short directory names.

We don't need breadcrumbs on EVERY page, I don't think.  On www, pub is definitely one area. I can't think of others right now.

@kwalrath  @kevmoo

**Comment by chalin** [comment]
Ok, thanks.

> We don't need breadcrumbs on EVERY page ... pub is definitely one area.

Right. I'll set it up for pub only, to start with.
