### ISSUE TITLE
Recommend mixin keyword after 2.1?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/site-www#1597]
https://dart.dev/guides/language/effective-dart/design#do-document-if-your-class-supports-being-used-as-a-mixin

Should recommend mixin keyword after 2.1?

**Comment by kwalrath** [comment]
@munificent what do you think?

**Comment by kwalrath** [comment]
Btw, thank you @mnordine for all your feedback! It's great to know that someone's reading the docs carefully.

**Comment by mnordine** [comment]
No prob at all!

**Comment by munificent** [comment]
Yes, the new mixin syntax is rad!
