### ISSUE TITLE
Asynchronous example has uncaught error

### ISSUE THREAD

**Issue by andrewkrieger** [dart-lang/site-www#16]
The examples on https://www.dartlang.org/tutorials/language/futures all encounter an error when making an HTTP request. For example, in the first example, the code prints three lines (as expected), then prints "Uncaught" instead of the result of the request.

The requested page <https://www.dartlang.org/f/dailyNewsDigest.txt> is still live. The error object is an Event (from dart:html). I'm not familiar enough with the HTTPRequest API to debug further than that.

Issue occurs in Chrome 51.0.2704.106, both on Ubuntu and ChromeOS.

**Comment by Sfshaza** [comment]
Thanks for bringing this to our attention! I'll set HTTP access control to read-only for the new website. (It defaults to no-access.)

**Comment by Sfshaza** [comment]
Filip has fixed this. Thanks!
