### ISSUE TITLE
The article about event loop had been removed

### ISSUE THREAD

**Issue by jinyulei0710** [dart-lang/site-www#1617]
I was just start learn about flutter, there was a article about event loop, but now had been removed.

**Comment by kwalrath** [comment]
@jinyulei0710 can you tell me which article (which URL) you were looking for and where you found the link to it? Thank you!

**Comment by kwalrath** [comment]
To clarify, we knowingly removed some obsolete articles, but we'd like to know what people were hoping to learn from them.

**Comment by jinyulei0710** [comment]
@kwalrath it's a article about event loop. path: https://webdev.dartlang.org/articles/performance/event-loop#annotated-sample-and-output

**Comment by kwalrath** [comment]
We've gotten another report of this article being missing, so it seems I need to add it back.

**Comment by tijoforyou** [comment]
[FYI] This article is actually also linked from DocComments: https://api.dartlang.org/stable/2.3.0/dart-async/scheduleMicrotask.html
