### ISSUE TITLE
'The pubspec file' page issue

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#1627]
Page URL: https://www.dartlang.org/tools/pub/pubspec.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/pubspec.md

Description of issue:

`pana` used for score of packages on `pub.dev` deducts points if the description is not between 60 and 180 characters. I believe this is based on SEO guidelines..

In https://github.com/dart-lang/linter/pull/1569#issuecomment-493546136 @pq suggests this is inconsistent with advice given on the website.

> This is optional for your own personal packages, but if you intend to publish your package you must provide a description. This should be relatively short—a few sentences, maybe a whole paragraph—and tells a casual reader what they might want to know about your package.

I think we should update the documentation to indicate that should be a short description, like a sentence or two. I'm not sure how to phrase it.

**Comment by pq** [comment]
cc @kwalrath

**Comment by kwalrath** [comment]
Yep, this is a known issue. I can fix this now that the I/O crunch is over. Closing in favor of #1305.
