### ISSUE TITLE
Broken link to Cascade notation in The main() function

### ISSUE THREAD

**Issue by nsgonultas** [dart-lang/site-www#163]
In the section [The main() function](https://www.dartlang.org/guides/language/language-tour#the-main-function), there is a broken link to _Cascade notation_ which points `#cascade`. It should point to `#cascade-notation-`. I can work on this if you need help :octocat:

**Comment by kwalrath** [comment]
Sure, we welcome pull requests!

**Comment by kwalrath** [comment]
Fixed by #164.
