### ISSUE TITLE
URL links to subheadings in effective dart are broken

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/site-www#1641]
This broke some time in the last 48 hours.  I use this feature every single day to link to effective dart in code reviews.  Please fix as soon as possible.

**Comment by kwalrath** [comment]
Tracked in #1638.

**Comment by leiboldm** [comment]
I just realized there's a workaround here: you can copy the links from the table of contents.

Also, in case it wasn't clear from the original report, I'm referring to the little paper clip icons that appear next to each section header and allow you to copy a link to that section.  They have stopped appearing.

**Comment by kwalrath** [comment]
Yep, I know exactly what you're talking about. Thanks for making sure we knew about this!
