### ISSUE TITLE
'Effective Dart: Design' page issue - harder to get links to particular items

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/site-www#1642]
Page URL: https://www.dartlang.org/guides/language/effective-dart/design
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/design.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: There aren't any obvious anchors next to the items. There used to be a little link icon that you could use to get a link to refer to any particular guideline. I do that a LOT for readability.

**Comment by kwalrath** [comment]
Tracking in #1638.
