### ISSUE TITLE
dart.dev favicon colors look slightly off

### ISSUE THREAD

**Issue by nshahan** [dart-lang/site-www#1673]
Compared to the icon on the page and the favicon on pub.dev the colors look slightly lighter.

<img width="144" alt="Screen Shot 2019-06-10 at 9 33 55 AM" src="https://user-images.githubusercontent.com/2498387/59211215-32fde000-8b64-11e9-87ae-72b656a77fc2.png">

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/pull/2946

**Comment by chalin** [comment]
Was this a dup of #2472?

**Comment by kwalrath** [comment]
> Was this a dup of #2472?

Yes, I think so.
