### ISSUE TITLE
Publish diagnostics.md

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1674]
Related: #1654 

Before publishing, we should add a comment to the file that warns them away from editing it directly and (ideally) gives tips on providing feedback on the content and format of the page. Something like this:

```
{%- comment %}
WARNING: Do NOT EDIT this file directly. It is autogenerated by...
{% endcomment -%}
```

I'm thinking the location should be something like /guides/language/diagnostics.

Let's NOT put this in the sidenav yet.

/cc @legalcodes @domesticmouse @johnpryan @bwilkerson

**Comment by bwilkerson** [comment]
The notification is being generated as of https://dart-review.googlesource.com/c/sdk/+/105600.

**Comment by kwalrath** [comment]
As of 7/31, it's being published at https://dart.dev/tools/diagnostic-messages.

**Comment by chalin** [comment]
> Let's NOT put this in the sidenav yet.

Is there an issue open to track its addition?

**Comment by kwalrath** [comment]
> > Let's NOT put this in the sidenav yet.
> 
> Is there an issue open to track its addition?

Nope, not yet. I'm not sure we'll ever want it in the sidenav. It's mostly there for the tools to point to.
