### ISSUE TITLE
Add "Safe" (nullable) cast operator `as?`

### ISSUE THREAD

**Issue by sosite** [dart-lang/site-www#1678]
It'll be a little enhancement but so much pleasant one :)

Kotlin and Swift has something like _Safe casting_ with `as?` operator. It gives an opportunity to casting with `null` fallback if cast can't be performed:

```dart
void someFunction(dynamic arg) {
  // we could has something like
  final classVariable = (arg as? SomeClass)?.someValue;
  
  // in place of
  final classVariable = arg is SomeClass ? arg.someValue : null;
}
```

**Comment by johnpryan** [comment]
Thanks for filing an issue - just a head up, this issue tracker is for issues with the website. Language feature requests can be filed at https://github.com/dart-lang/language

**Comment by sosite** [comment]
Ahh, you're right, sorry ;)
