### ISSUE TITLE
Confused by the docs for caret constraints

### ISSUE THREAD

**Issue by nex3** [dart-lang/site-www#168]
_From @adamlofts on November 9, 2016 10:13_

On this page: https://www.dartlang.org/tools/pub/dependencies#version-constraints

The first example of a caret constraint (right at the top of the page) is given as:

```
dependencies:
  transmogrify: ^=1.0.0
```
In the caret syntax section the syntax is given as ^version and the example is:
```
dependencies:
  path: ^1.3.0
```

Is ^= a valid syntax for a constraint? Or perhaps the version of transmogrify is "=1.0.0". 

_Copied from original issue: dart-lang/pub#1469_

**Comment by nex3** [comment]
_From @zoechi on November 9, 2016 13:28_

I think https://github.com/dart-lang/site-www would be the right repo for reporting this issue

**Comment by kwalrath** [comment]
Good question, @adamlofts.

@nex3 What's the answer? (We can chat if it isn't very simple.)

**Comment by nex3** [comment]
The `^=` form is just wrong. It should be `^1.0.0`.
