### ISSUE TITLE
How to Solve Interface Naming Conflict

### ISSUE THREAD

**Issue by 84819760** [dart-lang/site-www#1680]
//C# code
    interface IInterface1 { string GetValue(); }
    interface IInterface2 { int GetValue(); }
    class Test : IInterface1, IInterface2
    {
        //C# Multi-interface Code=
        string IInterface1.GetValue() => "result";
        int IInterface2.GetValue() => 9527;       
    }
    void Main(string[] args)
    {
            //C# Use interface
            var test = new Test();
            string resultString = (test as IInterface1).GetValue();
            int resultInt = (test as IInterface2).GetValue();
    }

//Dart code 
abstract class Interface1 {  **String** getValue(); }
abstract class Interface2 {  **int** getValue(); }
class Test implements Interface1, Interface2 {
    //dart Multi-interface Code=?
   //how to explicit override?
}

**Comment by johnpryan** [comment]
Dart [doesn't support](https://github.com/dart-lang/sdk/issues/49#issuecomment-108301493) type based overloading but you can implement a more specific return type (a covariant return type) as long it is a subtype:

```
abstract class Interface1 { num getValue(); }
abstract class Interface2 { int getValue(); }
class Test implements Interface1, Interface2 {
  int getValue() => 0;
}
```

You might have better results posting questions on [stackoverflow](https://stackoverflow.com/questions/tagged/dart). This issue tracker is for issues specifically for the website. You can also file issues at [dart-lang/sdk](https://github.com/dart-lang/sdk).
