### ISSUE TITLE
Article on serialization returns 404...

### ISSUE THREAD

**Issue by kf6gpe** [dart-lang/site-www#1684]
Searching on Google for "Dart serialization" turns up https://dart.dev/articles/serialization as the first hit, but it's no longer available.

**Comment by sfshaza2** [comment]
Correct. That article was out of date 

This link should be forwarded to our JSON page:  https://dart.dev/guides/json
And you may notice that our current most comprehensive info is on the Flutter website (linked to from the JSON page).
