### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by vinicentus** [dart-lang/site-www#1695]
URL: [https://dart.dev/articles/dart-vm/native-extensions](https://dart.dev/articles/dart-vm/native-extensions)
Expected page: info page about native extensions
Redirected from [https://www.dartlang.org/articles/dart-vm/native-extensions](https://www.dartlang.org/articles/dart-vm/native-extensions)

What happened to this page?

**Comment by johnpryan** [comment]
Good catch - this page moved to https://dart.dev/server/c-interop-native-extensions so we need to add a redirect.
