### ISSUE TITLE
'Dart documentation' page issue

### ISSUE THREAD

**Issue by Y24** [dart-lang/site-www#1697]
![Screenshot from 2019-06-23 14-49-32](https://user-images.githubusercontent.com/37091129/59972687-38c4de00-95c6-11e9-8458-9f869a79e9c4.png)
Page URL: https://www.dartlang.org/guides/index
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/index.md

Description of issue: It's hard to describe the bug, When using firefox brower, everything is ok, however, once turns to google chrome, some ugly unexcepted words appear in the same web page, just look at the photo for more details, What's more, the docs website of flutter has the exact same bug.
          hope the test group
![Screenshot from 2019-06-23 14-49-32](https://user-images.githubusercontent.com/37091129/59972739-2303e880-95c7-11e9-93d4-fd5fa8ebb6d7.png)
 do more jobs!

**Comment by johnpryan** [comment]
Are you running any Chrome extensions or ad blockers?

**Comment by sfshaza2** [comment]
@Y24, this is not reproducible for me. @johnpryan asks a good question. Are you running any Chrome extensions? That may be causing your problem.

**Comment by Y24** [comment]
@johnpryan no, The Chrome brower is a totally new brower I installed because I can use flutter's devtools. by the way, When I open the website in Chrome on Andorid's device, they show me the same bugs:joy:

**Comment by sfshaza2** [comment]
Is it still happening for you, @Y24?

**Comment by Y24** [comment]
@sfshaza2 oh，wonderful，I checked it right now, It seems to be fine, thank you.

**Comment by sfshaza2** [comment]
Good to hear! Thanks!
