### ISSUE TITLE
Create redirect for Broadcast Streams article

### ISSUE THREAD

**Issue by vinicentus** [dart-lang/site-www#1698]
URL: https://dart.dev/articles/broadcast-streams
redirected from https://www.dartlang.org/articles/broadcast-streams/

Can't find the page... Google only seems to index the old dartlang url.

**Comment by johnpryan** [comment]
I can't find where this article went but there are still some [tests](https://github.com/dart-lang/site-www/tree/master/examples_archive/site_tests/articles/broadcast-streams) @sfshaza2 was article was taken out? We may want to redirect to https://dart.dev/tutorials/language/streams#broadcast-streams if that's the case

**Comment by sfshaza2** [comment]
Yes, I remember that article, and it’s definitely gone from the repo. That surprises me as I wasn’t aware of any aspect of broadcast streams going out of date. I would suggest the following (though Kathy might have different ideas):

- Add a redirect from the former article to the link that @johnpryan suggested. It’s the only remaining place on the site that talks about broadcast streams. However, it’s a bit thin, in terms of explanation. So…
- To that section of the streams tutorial, add links to community articles. These two look pretty good (but should be vetted):
  https://medium.com/@ayushpguptaapg/using-streams-in-flutter-62fed41662e4
  https://www.burkharts.net/apps/blog/fundamentals-of-dart-streams/   (His comment “Steams: Let it flow” cracked me up.)

**Comment by kwalrath** [comment]
I think we just didn't have any tests for the code. This page is archived at https://web.archive.org/web/20190402211111/https://www.dartlang.org/articles/libraries/broadcast-streams/. I could add it back and file a bug to create tests for all the code...

**Comment by kwalrath** [comment]
Sorry this took so long... We should at least do the redirect.

**Comment by MrBirb** [comment]
Looks like all the links here are 404s

**Comment by kwalrath** [comment]
Still our 2nd highest 404. Although that's not a great experience for users, it _is_ a handy way for us to figure out which missing things are actually... missed. I looked at the last 2 years' data:

* In 89% of cases this was the landing page.
* 45% of referrals were from google searches; 20% were direct; 7% appeared to come from a non-longer-existent page on a Korean site (which is still somehow sending us viewers).
* 6% of referrals were from https://pub.dev/documentation/rxdart/latest/rx/Rx-class.html (API doc for the popular [rxdart package](https://pub.dev/packages/rxdart)).
* We didn't have enough occurrences to get search terms/queries.

**Comment by vinicentus** [comment]
The article was removed in 32193158565f756508d8c573246577f445ca35e9. We should probably:
A) check how obsolete it actually is, and consider adding it back with possible modifications, or
B) have it redirect to https://dart.dev/tutorials/language/streams#two-kinds-of-streams (The rationale for not redirecting directly to the broadcast streams sections is that the old article covered both types of streams)

Also, note that there is another article about streams [here](https://dart.dev/articles/libraries/creating-streams)
