### ISSUE TITLE
Effective Dart   

### ISSUE THREAD

**Issue by Jungle68** [dart-lang/site-www#1699]

**Comment by johnpryan** [comment]
What is issue you are seeing? The Effective Dart article is here: https://dart.dev/guides/language/effective-dart

**Comment by sfshaza2** [comment]
Hi @Jungle68! I saw the other bug you opened where you had an issue with the translated version of our site. Please direct your questions to them. If you have an issue with our site, dart.dev, maybe you can find someone who can translate to English? Closing this for now. Thanks!
