### ISSUE TITLE
Bad URL: Language tour

### ISSUE THREAD

**Issue by challe** [dart-lang/site-www#17]
URL: https://www.dartlang.org/language-tour/
Expected page: https://www.dartlang.org/guides/language/language-tour

**Comment by kwalrath** [comment]
Thanks for the report, @challe. Can you tell me where you got the first URL from?

**Comment by challe** [comment]
Oh, just via a google search. So I don't know if there are broken links on the actual page itself, but adding a redirect if the URL changed would be nice :)

**Comment by filiph** [comment]
Thanks for the report, this is fixed now with https://github.com/dart-lang/site-www/commit/d3bacdaee2c39e2827f1d3066a5e627cf32b79a1.
