### ISSUE TITLE
Effective Dart   描述文字错误

### ISSUE THREAD

**Issue by Jungle68** [dart-lang/site-www#1700]
![image](https://user-images.githubusercontent.com/7939686/60010354-32a82d80-96aa-11e9-8a63-ee6b00351d2b.png)

**Comment by lrhn** [comment]
I do not believe the goodev.org site is owned by the Dart team. If there are issues with the translation, the owner of the site is the one who needs to be contacted. I do not see any contact information on the dart.goodev.org page, though.

**Comment by sfshaza2** [comment]
@lrhn is correct. I’m closing this issue. Please re-open if you have an issue with dart.dev. Thanks!
