### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by johnstuarthunter** [dart-lang/site-www#1702]
URL: https://dart.dev/articles/await-async
Expected page: 
A page about Dart async and await.
This has been over a week now.. and is the top result when you search:
"dart when an async method returns what is returned" in GOOGLE

**Comment by johnpryan** [comment]
It looks like this article was removed intentionally (32193158565f756508d8c573246577f445ca35e9) so this page should probably redirect to https://dart.dev/tutorials/language/futures

**Comment by sfshaza2** [comment]
That’s correct. Also, we have a new async/await codelab coming very soon.
