### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by Beast1488** [dart-lang/site-www#171]
URL: https://www.dartlang.org//community/who-uses-dart
This page not found (error code 404)

**Comment by Sfshaza** [comment]
That is a bad URL with the double slash. This works:
https://www.dartlang.org/community/who-uses-dart

**Comment by Beast1488** [comment]
Yes, I see. Just wrote to correct the mistake on dartlang.org - this bad url is in the footer

**Comment by Sfshaza** [comment]
Thanks! I will fix.

**Comment by Sfshaza** [comment]
Hi @Beast1488! I cannot confirm this broken link. Manually checks were fine, and I ran a link checker. Also fine.
