### ISSUE TITLE
https://dart.dev/ bloccked in Browser: Invalid cert

### ISSUE THREAD

**Issue by stritti** [dart-lang/site-www#1711]
Error: `NET::ERR_CERT_AUTHORITY_INVALID`

![image](https://user-images.githubusercontent.com/184547/60329021-c40bee00-998f-11e9-9d30-fe5e91be4220.png)

**Comment by sfshaza2** [comment]
Hmm.  I’m asking various folks around the globe to see if they can reproduce this.

**Comment by stritti** [comment]
I got it at Germany. But it looks like the cert is outdated.
