### ISSUE TITLE
Improve isolate coverage in language tour

### ISSUE THREAD

**Issue by joriki** [dart-lang/site-www#1712]
Page URL: https://www.dartlang.org/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Description of issue:

The term "isolate" (which I hadn't encountered before) is first used without explanation and without a link in [the section on exceptions](https://dart.dev/guides/language/language-tour#exceptions) -- it should link to [the section on isolates](https://dart.dev/guides/language/language-tour#isolates) and perhaps also be briefly explained or contextualized.

**Comment by sfshaza2** [comment]
Excellent point, @joriki!

The page should also embed this video:  https://www.youtube.com/watch?v=vl_AaCgudcY

You might also find these community articles useful:
https://blog.usejournal.com/flutter-async-beginner-friendly-guide-for-heavy-lifting-operations-cf8ec81833d7
https://www.didierboelens.com/2019/01/futures---isolates---event-loop/

**Comment by kwalrath** [comment]
We should consider pointing to the docs for spawn, compute, and TransferableTypedData.
