### ISSUE TITLE
'Dart cheatsheet codelab' page issue

### ISSUE THREAD

**Issue by Henriquedn** [dart-lang/site-www#1713]
Page URL: https://www.dartlang.org/codelabs/dart-cheatsheet/
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/dart-cheatsheet/index.md

Description of issue: The Solution for the Exceptions part is missing catch(e) on line 18 hence the solution itself cannot pass the test

```
try{
    untrustworthy();
  } on ExceptionWithMessage catch(e){
    logger.logException(e.runtimeType, e.message);
  } on Exception catch(x) {
    logger.logException(x.runtimeType);
  } finally{
    logger.doneLogging();
  }
```

**Comment by kwalrath** [comment]
I think this is https://gist.github.com/RedBrogdon/e221e3fd667825e62aac79079b8b5c59.

**Comment by kwalrath** [comment]
@RedBrogdon I can fix this if you’d like. Since it’s your gist, I thought I’d give you first crack. :)

**Comment by kwalrath** [comment]
It looks like it's passing the test now, and the gist was updated 11/2019.
