### ISSUE TITLE
#mainnav ends up under #page-header in IE11

### ISSUE THREAD

**Issue by challe** [dart-lang/site-www#172]
My IE version is 11.0.9600.18524 and on dartlang.org, the nav tag ends up under the header tag. See image.

![image](https://cloud.githubusercontent.com/assets/1176022/20667067/c51c6d38-b567-11e6-8859-b06b5068cae7.png)

**Comment by t-miller** [comment]
I'm on version 11.15.16299.0 and am not getting the same issue.
![image](https://user-images.githubusercontent.com/19845698/31740305-f119e7ec-b41e-11e7-996d-65adcdc49f5c.png)

**Comment by kwalrath** [comment]
Thanks for the update, @t-miller. I'm going to close this. (I wonder if it was related to the blue box, which is no longer present but might reappear someday.)
