### ISSUE TITLE
Fix dart.dev search engines and search page text

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1724]
Two things are weird about search right now:

1. The Search dart.dev page is returning results from api.flutter.dev & flutter.dev as well, for some reason. E.g. go to https://dart.dev/search and search for “language” (dart.dev is first, but flutter.dev results appear on the first page) or “mixin” (api.flutter.dev is first).

2. The search-all page and engine should search api.dart.dev, and mention that it might get results from api.dartlang.org.
    E.g.: check out https://dart.dev/search-all#gsc.tab=0&gsc.q=object&gsc.sort=

**Comment by kwalrath** [comment]
Just noticed this again today. It's really annoying to get the flutter.dev results!

**Comment by parlough** [comment]
As far as I can tell, I'm only getting results from dart.dev on the primary search page. Perhaps this was fixed on the Google CSE end? 

As for the search-all page, what is the problem in the behavior currently? Or do you just want the text to be more clear in the websites the search pulls from?

**Comment by kwalrath** [comment]
I think I fixed this on the CSE side
