### ISSUE TITLE
'Effective Dart: Usage' page issue

### ISSUE THREAD

**Issue by dballesteros7** [dart-lang/site-www#1725]
Page URL: https://www.dartlang.org/guides/language/effective-dart/usage
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/usage.md

Description of issue:

This part of the "DO use initializing formals when possible" style rule:

"You can't always take advantage of it. In particular, using it means
the parameter is not visible in the initialization list. But, when you can, you
should." 

is not valid since [Dec 2016].(https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#1210---2016-12-07) when this changed was applied:

"Support access to initializing formals, e.g., the use of x to initialize y in class C { var x, y; C(this.x): y = x; }."

Perhaps it should be removed?

**Comment by kwalrath** [comment]
@munificent, what do you think we should do?

**Comment by munificent** [comment]
This bug is correct. The text is out of date.

The main case now where you wouldn't use an initializing formal is if the parameter is named, but you don't want the name to be the same as the initializing field as in:

```dart
class Foo {
  int _privateThing;
  Foo({int thing}) : _privateThing = thing;
}
```

**Comment by kwalrath** [comment]
@munificent is it OK to just remove the rule, or do you want to change it?
