### ISSUE TITLE
Missing documentation around packages with non-stable SDK deps.

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#1733]
We are missing documentation on how to handle publishing of packages that depend on non-stable SDKs. Specifically:

- https://dart.dev/tools/pub/pubspec#version makes it sound like pre-release versions must use `-alpha.x`. Can you not use the more traditional `-dev.x`?
- https://dart.dev/tools/pub/versioning doesn't mention pre-release versioning at all
- https://dart.dev/tools/pub/publishing should mention the usecase of how to publish a package that is pre-release with some guidance:
   * Packages published using release versions (0.y.z or x.y.z) should ALWAYS depend on Dart & Flutter SDKs in stable versions (not dev versions)
   * Packages depending on dev SDKs should be published using pre-release version numbers
 - https://dart.dev/tools/pub/publishing is missing a section on how the Pub.dev site will actually score packages after publishing. This can link to https://pub.dev/help#scoring

**Comment by mit-mit** [comment]
cc @kwalrath I think this is a pretty big gap. @jonasfj has offered to write some raw content for it!

**Comment by jonasfj** [comment]
Filed https://github.com/dart-lang/site-www/pull/1785

**Comment by jonasfj** [comment]
> https://dart.dev/tools/pub/versioning doesn't mention pre-release versioning at all

I'm not sure how we would bring that up here.. We could start by documenting that we don't actually use semver, but instead have [`pub_semver`](https://github.com/dart-lang/pub_semver) which is based on `semver 2.0.0-rc.1`. I just filed https://github.com/dart-lang/pub_semver/pull/38 to document that we're using `semver 2.0.0-rc.1`.

I'm not sure dart.dev/tools/pub/versioning is reference documentation, I think it's more an explanation of how semantic versioning works.

**Comment by mit-mit** [comment]
I think this has been resolved?

**Comment by jonasfj** [comment]
Yes, this is resolved.
