### ISSUE TITLE
是utf8而不是UTF8

### ISSUE THREAD

**Issue by JayTam** [dart-lang/site-www#1734]
https://github.com/dart-lang/site-www/blob/fe8fcfd5fac83102d5580109a3b8c9df16d7d1f4/examples_archive/library_tour/client-server/bin/main.dart#L12

**Comment by kwalrath** [comment]
The issue appears to be that `UTF8` should be `utf8`. However, I don’t think this code is used anywhere. In fact, we intend to remove the examples_archive directory (#1336). I’m going to close this issue in favor of #1336.
