### ISSUE TITLE
'Get the Dart SDK' page issue

### ISSUE THREAD

**Issue by Yairimedinac4621** [dart-lang/site-www#1736]
Page URL: https://www.dartlang.org/get-dart.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/get-dart.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by kwalrath** [comment]
Closing for lack of a description.
