### ISSUE TITLE
DDC claims to support every modern browser on one page, and only Chrome on another

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/site-www#1738]
Page URL: https://www.dartlang.org/tools/dartdevc/
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/dartdevc/index.md

Description of issue:

The very first sentence claims DDC lets you _debug your Dart web app in any modern web browser_.

In contrast, the [FAQ](https://dart.dev/tools/dartdevc/faq#the-basics) mentions that Chrome is the only supported browser, and that others _might_ work.

**Comment by kwalrath** [comment]
@vsmenon the first sentence should say “the Chrome browser”, right? (We avoid making forward-looking statements in the docs.)

**Comment by vsmenon** [comment]
Agreed, we should say "the Chrome browser".

**Comment by yourpalal** [comment]
I support updating the docs to reflect this but I want to register my discontent about the fact that DDC is only supported in Chrome.

Unfortunately, this not only means developing in Firefox is unsupported (and even broken, for angulardart), it means that supporting firefox with your dart code takes notably more effort. If there's a bug under firefox, you cannot use the normal dev flow to fix it which is unfortunate when `webdev` is so well tailored to that sort of task. This also means that probably most dart code will not be tested under firefox, and will therefore be more likely to break under firefox.

**Comment by kwalrath** [comment]
@yourpalal I believe we do intend to make dartdevc support all recent browsers, but unfortunately I can’t find a tracking bug for you to follow. The relevant issues should be filed under https://github.com/dart-lang/sdk/labels/area-dev-compiler.

**Comment by bergwerf** [comment]
A bug with the DDC now prevents me from developing on Firefox, and since having to move to Chrome for development is not ideal for me (partly because of convenience, partly for dogmatic reasons), I made an issue to ask/track progress of official Firefox support for the DDC here: https://github.com/dart-lang/sdk/issues/37767
