### ISSUE TITLE
Bad URL for dartanalyzer

### ISSUE THREAD

**Issue by Anrock** [dart-lang/site-www#174]
URL: http://www.dartlang.org/tools/analyzer
Expected page: homepage of analyzer

Excerpt from ```dartanalyzer --help```:
```
For more information, see http://www.dartlang.org/tools/analyzer.
```

Checked on 1.19.1 and 1.20.1, maybe other versions too.

**Comment by Sfshaza** [comment]
Fixed.

https://github.com/dart-lang/site-www/commit/211feecfd0a5d87ab221f5518dc512a3b8cd0d35
