### ISSUE TITLE
dartpad.dartlang.org -> dartpad.dev

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1741]
@domesticmouse or @RedBrogdon, is there any reason we shouldn’t make this change now?

**Comment by domesticmouse** [comment]
Uhm, I'm curious what the specific change is that you are asking about. [dartpad.dev](https://dartpad.dev/) works as is, but I don't want to hard re-direct from `dartpad.dartlang.org` to `dartpad.dev` as we will break a bunch of web pages. We are reliant on the information after the # in the URL, which is never sent to the server.

**Comment by johnpryan** [comment]
FWIW I think the fragment identifier stays in the URL after the redirect. I don't see how this would break any functionality but I could be missing something.

**Comment by kwalrath** [comment]
What I mean to do is to change all the DartPad links/inclusions on dart.dev from dartpad.dartlang.org to dartpad.dev. This should be a simple matter of changing a variable in a config file.

I just want to know if there’s any reason NOT to link to dartpad.dev (instead of dartpad.dartlang.org).

**Comment by johnpryan** [comment]
That sounds reasonable to me, but would like @domesticmouse to weigh in since he's more aware of the details

**Comment by domesticmouse** [comment]
That should be safe, we have already started making that change in various places. From an implementation perspective the two urls are completely equivalent
