### ISSUE TITLE
Support code highlighting in markdown code blocks

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1744]
I’d love to be able to use only triple-tick dart, never `{% prettify …%}`. But at least one use case (highlighting: `[!…!]`) doesn’t work with triple-tick dart. Having to remember to use prettify causes unnecessary complexity for site contributors. Also, I think prettify styles are different from ```dart styles.

Second, it’d be good to improve the formatting of code within strings: #1108.

**Comment by chalin** [comment]
It is possible to use triple-tick markdown and get highlighting to work -- that what we did in `site-webdev`. AFAIR, most of the necessary infrastructure has already been moved into `site-shared`.

**Comment by chalin** [comment]
(Maybe the title of this issue should be updated to something like: _Support code highlighting in markdown code blocks_.)

**Comment by parlough** [comment]
I want to standardize on the markdown code blocks, so I'll look into this soon.

**Comment by parlough** [comment]
I'm going to close this in favor of tracking the work in https://github.com/dart-lang/site-www/issues/3846.
