### ISSUE TITLE
Chore: Fail build if "./tool/build-and-check-links.sh" fails

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1748]
I don’t want to have to go to travis to find out that the link check failed. I’ll fix this unless someone gets to it first…

**Comment by parlough** [comment]
I believe GitHub actions fails if there is an error with the linkchecker. Do you want it to fail if there are warnings as well?

**Comment by kwalrath** [comment]
Nope, warnings are fine. Thanks for asking!
