### ISSUE TITLE
Gemfile references deprecated Sass library

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/site-www#1758]
The site's Gemfile:

https://github.com/dart-lang/site-www/blob/master/Gemfile

Includes a reference to [Ruby Sass](https://rubygems.org/gems/sass/versions/3.7.4), which has been deprecated in favor of Dart Sass:

https://sass-lang.com/ruby-sass

**Comment by chalin** [comment]
Yep, we also have a corresponding issue on the flutter/website side: https://github.com/flutter/website/issues/1175.

**Comment by chalin** [comment]
Here's the post-install message from sass:

> Ruby Sass has reached end-of-life and should no longer be used.
> 
> * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install
> 
> * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme
> 
> * For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841
