### ISSUE TITLE
Doc request for "So I want to move to strong mode"

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#177]
_From @sethladd on November 30, 2016 17:20_

You've convinced me I want to move to strong mode. :)  How do I do it?

I saw http://news.dartlang.org/2016/11/dart-strong-mode-and-ahead-of-time_30.html and I'm sold. Is there a "follow this guide" or "do these things" doc?

Thanks!

_Copied from original issue: dart-lang/sdk#27944_

**Comment by kwalrath** [comment]
Shams is working on this. I'll move this bug to site-www.

**Comment by kwalrath** [comment]
_From @sethladd on December 1, 2016 16:53_

Great to hear!

**Comment by Sfshaza** [comment]
New docs:

[Sound Dart](https://www.dartlang.org/guides/language/sound-dart)
[Sound Dart FAQ](https://www.dartlang.org/guides/language/sound-faq)
[Sound Dart: Common Problems](https://www.dartlang.org/guides/language/common-prob)
