### ISSUE TITLE
Layout basics codelab has incorrect solution

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#1773]
The gist used for https://flutter.dev/docs/codelabs/layout-basics in section"Try using SizedBox to make space" uses `50` for the SizedBox's width, but the test code expects `100`. Corrected gist is here:

https://gist.github.com/johnpryan/326b8c5774079b7a80922e11a3730f99

I don't see a way to make a pull request to the original gist (https://gist.github.com/RedBrogdon/0c3e1ce8177a2f0cc8e2275d5260b348)

**Comment by kwalrath** [comment]
I think this issue belongs in github.com/flutter/website, but I can't move/transfer it for some reason.

What I usually do is fork the original gist and change the .md file to point to the new gist.

**Comment by johnpryan** [comment]
oops, wrong repo. Fix is here: https://github.com/flutter/website/pull/2845
