### ISSUE TITLE
'Effective Dart: Style' page issue

### ISSUE THREAD

**Issue by Stef-GMS** [dart-lang/site-www#1774]
Page URL: https://dart.dev/guides/language/effective-dart/style
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/style.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: The page states that using prefixes is "bad", but yet there are constants in the Dart Packages which have the 'k' prefix (i.e. kBottomNavigationBarHeight, kAlwaysCompleteAnimation, kElevationToShadow, etc.) This is confusing to the reader and inconsistent.

**Comment by kwalrath** [comment]
Good point.

@eseidelGoogle or @hixie, can you comment on why many of [Flutter material's constants](https://api.flutter.dev/flutter/material/material-library.html#constants) use the `k` prefix?

@munificent, do you think we should soften https://dart.dev/guides/language/effective-dart/style#dont-use-prefix-letters?

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#begin-global-constant-names-with-prefix-k

**Comment by munificent** [comment]
> @munificent, do you think we should soften https://dart.dev/guides/language/effective-dart/style#dont-use-prefix-letters?

No, I don't. The only places I've ever seen this done are the Flutter framework and every now and then years ago when one of the Dart VM team members used to writing C++ would write a little Dart code without knowing the idioms.

I think the documented style is fine.
