### ISSUE TITLE
Make sure image files are used

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1789]
More info: https://github.com/dart-lang/site-www/pull/1780#issuecomment-514753731

We might have other image files that are unused... it wouldn't be bad to do a pass to find those.

**Comment by kwalrath** [comment]
#2889 might fix this.

**Comment by atsansone** [comment]
Created an [Audit File](https://docs.google.com/spreadsheets/d/1R9L0Pzk16-hHEQS5aVoGX5nF-KE4UK7vtjvRuXypSiY)

**Comment by atsansone** [comment]
We delete unused image files automatically?

**Comment by atsansone** [comment]
Used this command to find images in all `*.scss`, `*.js`, `*.md` files:

```terminal
$ grep -R -e '\.(jpg|png|gif|svg)' ./
```
