### ISSUE TITLE
Change optional param separator from : to = in language tour (and elsewhere)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#180]
_From @sethladd on December 2, 2016 20:47_

The 1.21 Dart language support "Allow = as well as : as separator for named parameter default values."

We could mention that in https://www.dartlang.org/guides/language/language-tour

_Copied from original issue: dart-lang/sdk#27976_

**Comment by lrhn** [comment]
If you change anything, I would just change them all to `=`. It's more "future-safe" since we are likely to deprecate `:` in v1.50+ and remove it in v2.0.

**Comment by sethladd** [comment]
Thanks for the advice!

**Comment by kwalrath** [comment]
We'll need a note about : for people who are using older releases/code.

**Comment by kwalrath** [comment]
I'm going to close this, since I can't think of other uses of `:` (nor an easy way to search for them).
