### ISSUE TITLE
'dart2aot' page issue

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/site-www#1801]
Page URL: https://dart.dev/tools/dart2aot.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/dart2aot.md

Description of issue: We should probably mention that `dart:mirrors` isn't supported, and talk about how to include package dependencies into a binary.

**Comment by kwalrath** [comment]
@domesticmouse are you getting this information, or do you need some help from me in finding the details?

**Comment by domesticmouse** [comment]
I don’t currently have time to chase this one down 😎
