### ISSUE TITLE
Request to add generic methods to the Language Tour

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#181]
_From @sethladd on December 2, 2016 20:46_

https://www.dartlang.org/guides/language/language-tour doesn't seem to have generic methods.

The 1.21 changelog mentions it support generic methods. https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md

Here is the "informal specification" : https://gist.github.com/eernstg/4353d7b4f669745bed3a5423e04a453c

Thanks!

_Copied from original issue: dart-lang/sdk#27975_

**Comment by Sfshaza** [comment]
Here is some info:
https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/doc/GENERIC_METHODS.md

**Comment by kwalrath** [comment]
This should probably go in the [Generics section](https://www.dartlang.org/guides/language/language-tour#generics) of the language tour, but doing it well might require some thought. Also, some other parts of the language tour might be affected.

A quick fix would be to add a note to the Generics section that refers to [Using Generic Methods](https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/doc/GENERIC_METHODS.md) (which should probably itself refer to the informal spec).

**Comment by kwalrath** [comment]
I'm going to close this, but feel free to reopen this (or create a new issue) if you think of a better way/place to handle this.
