### ISSUE TITLE
futures codelab needs tests for examples

### ISSUE THREAD

**Issue by legalcodes** [dart-lang/site-www#1810]
(1) We should write tests for the test code that runs in DartPad exercises
(2) We should extract / test the code in example snippets. 

Ed 10/23: We should update the codelab's test code to use Andrew's test package. (The test code was written before the package was finished.)

**Comment by legalcodes** [comment]
See :

https://github.com/dart-lang/site-www/tree/master/examples
https://raw.githubusercontent.com/dart-lang/site-www/master/src/samples/index.md

**Comment by galeyang** [comment]
Details from previous offline discussion

> We need tests for test code: 1. ensure solution code works 2. feed failing code and check out test result and custom error messages 

cc: @RedBrogdon I'm not sure which repo should we track this.

**Comment by legalcodes** [comment]
@galeyang Sorry, I should have clarified in the initial description:

(1) should probably be tracked in dart-lang/dart-pad @RedBrogdon please correct if I'm mistaken about this
(2) can be tracked in dart-lang/site-www since we currently have a mechanism for doing this in that repo

**Comment by kwalrath** [comment]
If we could get the DartPads' code from arbitrary repo files, not just gists, then (2) could possibly take care of (1) for this site.

**Comment by kwalrath** [comment]
@legalcodes could you update the status of this?

**Comment by legalcodes** [comment]
AFAIK we can't move forward on this before https://github.com/flutter/website/issues/3262 is resolved, though to be 100% certain we'd need to verify that the issue exists for dart-lang/site-www.

**Comment by kwalrath** [comment]
Looks like flutter/website#3262 has been resolved.

**Comment by legalcodes** [comment]
This  codelab uses gists, so IIRC in order to add testing we're also waiting for an update on https://github.com/dart-lang/dart-pad/issues/1120.

@RedBrogdon can you please advise?

**Comment by kwalrath** [comment]
#2454 changed the codelab to use embedded code, rather than gists. So now the code is analyzed, but the tests still aren't being automatically run.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/1803 now that the page is using code excerpts, we just need to actually run the tests.
