### ISSUE TITLE
'Articles' page issue: should Zones be in the list?

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1812]
Page URL: https://dart.dev/articles/index
Page source: https://github.com/dart-lang/site-www/tree/master/src/_articles/index.md

Description of issue: the page lists articles with a "library" tag in the front matter. The current list has 3 entries:
> <img width="427" alt="Screen Shot 2019-08-03 at 12 36 17" src="https://user-images.githubusercontent.com/4140793/62414586-6c464f80-b5eb-11e9-80fd-1b7cd4b5323d.png">

The *Zones* article is under _articles/archive/zones.md. I'm assuming that if it is archived, then it shouldn't show up on the main "Articles" page. If it is ok to show the article, maybe it should be moved out of the "archive" folder?

**Comment by kwalrath** [comment]
Good point, I'll remove that tag from the Zones article.

**Comment by chalin** [comment]
Closed by #1814
