### ISSUE TITLE
'Articles' page doesn't appear in left- or top-nav

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1816]
Page URL: https://dart.dev/articles/index
Page source: https://github.com/dart-lang/site-www/tree/master/src/_articles/index.md

- Left nav: it could appear under **Resources**
- Top nav: it should appear under **Doc**

**Comment by kwalrath** [comment]
This is WAI. We have the page there only for URL walkers. (That said, we aren't wedded to this organization. We just didn't want to commit to the idea of articles.)
