### ISSUE TITLE
Make refresh-code-excerpts more robust

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1821]
We had a build breakage (#1818) due to code_excerpter trying to parse a .swp file. I don't know if the fault lies with code_excerpter or refresh-code-excerpts.sh, but either way, a .swp file shouldn't be able to break your build!

**Comment by chalin** [comment]
This PR excludes dot files from being processed by the code_excerpter builder: https://github.com/chalin/code_excerpter/pull/15.

@johnpryan @legalcodes @kwalrath : would one of you like to review/approve that PR?
