### ISSUE TITLE
'Troubleshooting pub' explain workaround for "localhost not working in browser"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#1822]
Page URL: https://dart.dev/tools/pub/troubleshoot
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/troubleshoot.md

Description of issue:

If working on Chromebook, working over SSH, or in a container, it can be the case that the `localhost` where `pub` is running is different from the `lcoalhost` in the browser the user is using.
This makes it impossible to login. The user will be able open the sign-in link and sign-in, but they will then be redirected to `http://localhost:<port>?code=...` which won't work. The browser will say something like:
> "This site can’t be reached localhost refused to connect."

In this case, the user can copy the URL and do `curl http://localhost:<port>?code=...` in a terminal next to the pending `pub publish` command.

I've seen this issue twice now: https://github.com/dart-lang/pub/issues/2187

So maybe we should add an entry to the troubleshooting section. Something along the lines of:

------

## Localhost unreachable after sign-in
If running `pub publish` in container or over an SSH session it might be that the `localhost` which `pub` is listening to is different from the `localhost` accessible in your browser. If this is the case, it is possible to sign-in, after which the browser will complain that `http://localhost:<port>?code=...` is not reachable.

A possible workaround for this is to copy the URL from the browser into a terminal session next to the `pub publish` awaiting for sign-in and run `curl http://localhost:<port>?code=...`.

------

Does this make any sense, I doubt this is super frequent, if it turns out to be super common, then perhaps we should revise the sign-in flow and avoid listening on localhost. Or offer an alternative sign-in flow.

**Comment by aardappel** [comment]
Yup, just ran into this when working over ssh. `curl` workaround worked.

**Comment by kwalrath** [comment]
Seems important to document now that so many people are working from home.
