### ISSUE TITLE
the old page has been redirect to a dangerous site; you can remove the prompt 

### ISSUE THREAD

**Issue by yao8384** [dart-lang/site-www#1831]

**Comment by yao8384** [comment]
[http://www.dartlang.cc](url)

**Comment by kwalrath** [comment]
To my knowledge, we don't control or link to dartlang.cc. I'll see if there's something else we can do about this site.

**Comment by kwalrath** [comment]
Closing because I've confirmed that dart.dev doesn't link to dartlang.cc.

/cc @messi01
