### ISSUE TITLE
Update js-interop page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1835]
We're revamping the JS interop docs to make it very clear that people should use package:js instead of dart:js. Some of the work will be in the sdk repo (links from dart:js to package:js, improvements to the package:js README), but this page needs some work, too:

* Remove TS from the page name.
* Remove js_facade_gen.
* Instead of pointing to pub.dev js dependencies, point to individual packages, probably firebase_web & sass. Maybe others.
* Perhaps don't point directly to matanlurey/dart_js_interop (package:js might point there instead, and we should consider having some of the content on dart.dev).

/cc @vsmenon @natebosch

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/1835, as these points are outdated and we should document the new mechanism of interop instead.
