### ISSUE TITLE
'Asynchronous programming: futures, async, await' page issue

### ISSUE THREAD

**Issue by rootext** [dart-lang/site-www#1837]
Page URL: https://dart.dev/codelabs/async-await/
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/async-await/index.md

Description of issue:
All code examples are empty in Chrome

**Comment by domesticmouse** [comment]
It would be useful to see the contents of the console log in the browser. The code examples are being loaded into a DartPad embed, which is possibly failing out somehow.

/cc @johnpryan

**Comment by rootext** [comment]
@domesticmouse 
```
GET https://fonts.googleapis.com/css?family=:300,400,400i,500,600,700,700i net::ERR_ABORTED 400
logo.png:1 GET https://google.qualtrics.com/jfe/themes/skins/google/google3gg-new/version-1563530585806-0dd10e/files/logo.png 403
new_embed_dart.dart.js:449 Uncaught Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at hX.ew (new_embed_dart.dart.js:9803)
    at ez.e2 (new_embed_dart.dart.js:8683)
    at Object.eval (eval at pw (new_embed_dart.dart.js:590), <anonymous>:3:36)
    at iM.$0 (new_embed_dart.dart.js:4987)
    at iL.$1 (new_embed_dart.dart.js:4995)
    at mL.d2 (new_embed_dart.dart.js:5814)
    at mO.$1 (new_embed_dart.dart.js:5851)
    at Object.rR (new_embed_dart.dart.js:1362)
    at Object.rS (new_embed_dart.dart.js:1353)
    at ez.fc (new_embed_dart.dart.js:8681)
```

**Comment by johnpryan** [comment]
```
Uncaught Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

This could be related to #1838

**Comment by johnpryan** [comment]
Can you check if you need to [unblock third-party cookies](https://github.com/apollographql/apollo-client-devtools/issues/106#issuecomment-368752638)?

**Comment by rootext** [comment]
@johnpryan, Unblocking third-party cookies resolves the issue.

**Comment by johnpryan** [comment]
@rootext thanks. It looks like Chrome disallows access to localStorage if 3rd party cookies are blocked. (DartPad uses the localStorage API to store snippets.) It might be possible to remove the dependency on localStorage for the embedded version though.

**Comment by kwalrath** [comment]
Should we have a troubleshooting page for users of DartPad that links to solutions like this one?

**Comment by johnpryan** [comment]
I think so. The two issues that are happening are 1. using an ad-blocker and 2. disabling 3rd party cookies

**Comment by johnpryan** [comment]
Thanks for your help @rootext, we now have a troubleshooting page https://dart.dev/tools/dartpad/troubleshoot

**Comment by kwalrath** [comment]
Related: https://github.com/dart-lang/dart-pad/issues/1237
