### ISSUE TITLE
Font for "Try dart" editor on dart.dev

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/site-www#1839]
- go to dart.dev
- click the "Try dart" button at the top
- lock at the editor

On my machine (Linux) the font used is too small and not monospace --- basically making the thing unreadable and unusable.

**Comment by jensjoha** [comment]
![Screenshot](https://user-images.githubusercontent.com/20773519/63249095-07385e00-c269-11e9-9a03-6c65b1ec55e7.png)

**Comment by johnpryan** [comment]
DartPad issue here: https://github.com/dart-lang/dart-pad/issues/1203

**Comment by chalin** [comment]
With the closing of https://github.com/dart-lang/dart-pad/issues/1203, this issue should be resolved as well, right @kwalrath?

**Comment by johnpryan** [comment]
Good catch, I think we can close this one.
