### ISSUE TITLE
'Asynchronous programming: futures, async, await' page issue

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/site-www#1841]
Page URL: https://dart.dev/codelabs/async-await/
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/async-await/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

The dark mode tutorials are really hard to read. The curly braces look like semicolons or something and in general the font seems really small.

Note that I am in general a fan of dark mode, so I don't know exactly why I found these so much harder to read than the others... I think the small font size has something to do with it. 

![Screenshot from 2019-08-19 12-30-38](https://user-images.githubusercontent.com/984921/63293687-7cae2980-c27d-11e9-9783-0661a059c5b1.png)

Note that this picture is exactly as it appeared to me it isn't compressed or altered.

**Comment by johnpryan** [comment]
related to https://github.com/dart-lang/dart-pad/issues/1192

**Comment by jakemac53** [comment]
For some reason my screenshot looks much worse than that one, fwiw

**Comment by johnpryan** [comment]
the font issue (dart-lang/dart-pad#1203) has been fixed here: https://github.com/dart-lang/dart-pad/pull/1215.

We've gone through a few revisions of the colors, here's the original design:

![Screen Shot 2019-08-19 at 2 11 58 PM](https://user-images.githubusercontent.com/1145719/63301248-eedb3a00-c28e-11e9-93c9-552e12008b28.png)

here's the current version:
![Screen Shot 2019-08-19 at 2 37 33 PM](https://user-images.githubusercontent.com/1145719/63301255-f1d62a80-c28e-11e9-9015-4e5db0ea08bd.png)

here's a version with 13px font size and brighter colors:
![Screen Shot 2019-08-19 at 2 37 41 PM](https://user-images.githubusercontent.com/1145719/63301259-f4d11b00-c28e-11e9-9ccd-7f1695dce494.png)

Does that help?

**Comment by jakemac53** [comment]
I think it was just the font - these both look fine to me.
