### ISSUE TITLE
Security alert: Nokogiri

### ISSUE THREAD

**Issue by legalcodes** [dart-lang/site-www#1845]
GitHub is issuing a security alert for nokogiri, and recommends upgrading to version 1.10.4

See https://github.com/dart-lang/site-www/network/alert/Gemfile.lock/nokogiri/open

And our gemfile: https://github.com/dart-lang/site-www/blob/master/Gemfile#L9

**Comment by kwalrath** [comment]
I clicked the button to auto-fix the security issue. Let's see what happens...
