### ISSUE TITLE
Clarify how `const` should be applied to const constructors 

### ISSUE THREAD

**Issue by ninachen** [dart-lang/site-www#1859]
Problem:
I find that people tend to be confused* about whether you need to explicitly specify `const` when calling a const constructor.

Expected result:
Perhaps add a specific example for calling just a const constructor on https://dart.dev/guides/language/effective-dart/usage#dont-use-const-redundantly

*Here's an explanation I gave recently:

```dart
class Foo {
  const Foo();
}

var a = const Foo(); // is const
const b = Foo(); // is const
var c = Foo(); // is not const

const d = const Foo(); // is const, but disallowed by style guide[0]
var e = new Foo(); // is not const, but also disallowed by style guide[1]
```

[0]https://dart.dev/guides/language/effective-dart/usage#dont-use-const-redundantly
[1]https://dart.dev/guides/language/effective-dart/usage#dont-use-new

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/4350 to consolidate issues related to `const` in the language tour. Thanks!
