### ISSUE TITLE
Allow users to adjust the height of embed Dartpad

### ISSUE THREAD

**Issue by galeyang** [dart-lang/site-www#1860]
Moved https://github.com/dart-lang/dart-pad/issues/1209 to this repo so that we can continue tracking it.

> From a recent UX study, users complained that sometimes the height of an embedded is too small. Since users use various screen size, it's hard to have one exact value that fits for all users. We would like an option that enable users to resize the editor by dragging.

>The size of the iframe is controlled by the page that contains it, so this would need to be a change in flutter.dev/dart.dev rather than one in DartPad. It's a good idea, though.

cc: @kwalrath @RedBrogdon @legalcodes

**Comment by kwalrath** [comment]
> Is this built in browser functionality sufficient?

I think so. I'm closing this issue.
