### ISSUE TITLE
Use ```terminal across site for terminal command examples

### ISSUE THREAD

**Issue by legalcodes** [dart-lang/site-www#1868]
See, e.g. 
https://raw.githubusercontent.com/dart-lang/site-www/master/src/tools/dart2aot.md
which renders as:
https://dart.dev/tools/dart2aot

**Comment by kwalrath** [comment]
Examples of things to replace:
* `{% prettyprint sh %}`
* <code>```sh</code>
* Some occurrences of `prettyprint` or <code>```</code> with `none`

**Comment by kwalrath** [comment]
We should probably be consistent about whether we use `console` or `terminal`. I like `terminal` better. More info:

https://github.com/dart-lang/site-shared/blob/master/doc/infrastructure.md#jekyll

**Comment by chalin** [comment]
We should also probably agree on a prompt symbol: I'd vote for `$`, as it is probably what we've been using most often.

**Comment by atsansone** [comment]
This will depend upon what platform we highlight.

- If it's macOS or Linux, it should be `terminal` with a `$` prompt _unless_ it requires root access, then it should be `#`.
- If it's Windows, it should be `powershell` with a `>` prompt. 

I'll review.
