### ISSUE TITLE
Track the visibility of an element (e.g. survey, embedded DartPad)

### ISSUE THREAD

**Issue by galeyang** [dart-lang/site-www#1869]
UXR would love to have a way to track number of visitors saw or were exposed to an element, such as survey, embedded DartPad placed at the end of the page.

It'd be great to get this count from GA.

This issue is also cross posted on https://github.com/flutter/website/issues/2960.

cc: @RedBrogdon

**Comment by kwalrath** [comment]
Bumping the priority so we won't forget to discuss this.

**Comment by kwalrath** [comment]
Maybe we need to use an element visibility trigger? https://support.google.com/tagmanager/answer/7679410?hl=en&ref_topic=7679108

**Comment by galeyang** [comment]
I was looking at that, Google Tag Manager, last Friday (before we published the Flutter codelab survey). I reached Flutter UXR, Flutter/Dart marketing team and another product's UXR team but I couldn't find people have experience with setting GTM up and can provide immediate guidance. Do you know who may know this?

**Comment by kwalrath** [comment]
> I couldn't find people have experience with setting GTM up and can provide immediate guidance. Do you know who may know this?

No, I don't.

The other solution that occurred to me was attaching an analytics event to the code that detects when a TOC entry is active. E.g. if you go to https://dart.dev/guides/language/language-tour in a wide browser window and scroll down a bit, then inspect the blue link on the right, you'll see something like this:

![image](https://user-images.githubusercontent.com/2164483/64391538-e6f4f700-cffd-11e9-9787-2f5737195e21.png)

It might be able to generate an analytics event when a special item is visible. I don't know how feasible this is, though.

**Comment by galeyang** [comment]
The team helped me to get the Flutter GTM 🎉 .  I will start with trying it on the Flutter site. If it works well, then we can implement it on Dart site.

**Comment by kwalrath** [comment]
A bit late now that our survey is no longer up, but GTM is up on the Dart site (#1950), and @galeyang has admin privileges.
