### ISSUE TITLE
Add fallback image for front page's video tag

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1889]
From #1838:

> we could display an image of the final state of the animation... [by putting] HTML content inside the HTML5 video tag, which will be rendered in the case that the video isn't rendered.

**Comment by kwalrath** [comment]
I think we display an image instead of animation on mobile devices... If this image is high enough quality, we could re-use it inside the video tag.

**Comment by hugekoala** [comment]
Would love to work on that. Is it ok?

**Comment by kwalrath** [comment]
> Would love to work on that. Is it ok?

Yes, consider this issue yours, @hugekoala!

**Comment by ctsstc** [comment]
Should this issue be closed out, looks like the PR has been merged in.

**Comment by kwalrath** [comment]
Yes, thank you @ctsstc!
