### ISSUE TITLE
Update diagnostic messages page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1892]
https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/tool/diagnostics/diagnostics.md has just been updated. We should update https://dart.dev/tools/diagnostic-messages accordingly.

**Comment by kwalrath** [comment]
It's been updated again. https://dart-review.googlesource.com/c/sdk/+/118820

**Comment by chalin** [comment]
Maybe having a script/task to fetch and update the page would be welcome?

**Comment by kwalrath** [comment]
> Maybe having a script/task to fetch and update the page would be welcome?

Yes, it would be. :)

**Comment by chalin** [comment]
If you are updating this issue to include automating the task, then it will take more than e0-minutes. (Maybe we should create another issue for the automation of the page update?)

**Comment by bwilkerson** [comment]
There are new docs ready to be published whenever you can do so.
