### ISSUE TITLE
Setup analyzer-results files based on Dart channel rather than Dart version

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1894]
Just before Dart 2 was released, the site build was adapted so that it could run under Dart 1 and Dart 2. In particular, this implied supporting the analysis and testing of the site examples under both versions of Dart. Part of the challenge was to support:

- Analyzer options that differed across versions
- Analyzer output that differed across versions

This issue concerns the adaptation of the build scripts to support analyzer-results variants that differ across Dart channels (or some similar criteria), rather than Dart major version.

This will allow us to make the dev channel example tests to pass once again.

Remember to drop the allow-failure of dev channel examples tests after this issue is fixed.

**Comment by kwalrath** [comment]
I'd love to have this working!
