### ISSUE TITLE
Help people debug and improve performance of command-line apps

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1899]
We have dart.dev/tools/dart-devtools, but we need to add some resources (videos, docs, ...) to help people debug their apps and improve their apps' performance.

See #2055 for more discussion.

**Comment by kwalrath** [comment]
Let me explain the weird effort labels...It'll take minutes to do the basic getting started instructions, but doing more (providing a walkthrough, documenting how to use DevTools, etc.) is likely to take hours or days.

**Comment by devoncarew** [comment]
The pages which will work for CLI apps are the debugger, memory usage, the profiler page, and logging.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/site-www/issues/4352 which discusses documenting various DevTools views.
