### ISSUE TITLE
Use dartfmt on all samples in the language/library tour

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#190]
I think we disagreed with some of dartfmt's output, but we should probably just knuckle under.

**Comment by filiph** [comment]
+1!

**Comment by Sfshaza** [comment]
Knuckling under since 1999. 

I'm on it!

**Comment by kwalrath** [comment]
Be careful, however, to specify the right line length. I'm pretty sure that we need something < 80 chars (60? 65?) to display without breaks in the most common screen widths.

**Comment by Sfshaza** [comment]
I've used 70.

**Comment by kwalrath** [comment]
70 might be fine for the majority of the sites' pages (we should have some representative pages that we can test, to make sure). I think we need 60 for anything under webdev/angular. The code labs with 2-column formats probably need even smaller line lengths.

**Comment by Sfshaza** [comment]
That's fine, but I'm formatting code used by the library and language tour.
70 seems ok for that, yes?

**Comment by kwalrath** [comment]
We've confirmed that 68 works on www. When dartfmt is working right, that is.

**Comment by Sfshaza** [comment]
I found a bug in dartfmt that is blocking the fix of this bug: https://github.com/dart-lang/dart_style/issues/630

Btw, K and I looked and the ideal width for code is 68 chars.

**Comment by chalin** [comment]
This is now done and checked by Travis. We vary the line limit length depending on the source file. See https://github.com/dart-lang/site-www/blob/master/scripts/dartfmt.sh for details.
