### ISSUE TITLE
Please help to unpublish a package

### ISSUE THREAD

**Issue by yegor-pelykh** [dart-lang/site-www#1907]
Hi! I want to unpublish/remove the package I published. It is very new and there is no other packages or projects dependent on it. It is just empty.
Please, may you help me to unpublish it?
Thank you!

**Comment by kwalrath** [comment]
Hi, I believe you need to file an issue at https://github.com/dart-lang/pub-dev/issues/new. An example to follow might be https://github.com/dart-lang/pub-dev/issues/1193.
