### ISSUE TITLE
Don't commit compiled dartpad_picker JS

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1915]
Followup to #1887 and #1914.

We current commit the _compiled_ JS version of dartpad_picker. We should instead generate it when the site is built and let Jekyll place it under the assets folder.

**Comment by kwalrath** [comment]
Although I understand the desire to avoid committing generated files, I'm a little leery of introducing yet another way the build can break.

/cc @filiph @johnpryan

**Comment by chalin** [comment]
(Just thought that I'd mention in passing that merging in commits where there are local remote and local changes to generated files is no fun. Admittedly, that shouldn't happen too often.)

**Comment by parlough** [comment]
I'm going to close this, as this rarely needs to be updated. Committing it reduces chances for the build to break and reduces build times. If we switch to [Dart based tooling](https://github.com/dart-lang/site-www/issues/4163) in the future, we can reconsider this then.
