### ISSUE TITLE
Support loading DartPad sources from site vs Gist

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1919]
The [dartpad_picker](https://github.com/dart-lang/site-www/tree/master/tool/dartpad_picker) illustrates how Dartpad sources can be loaded from somewhere other than a Gist. The tool is currently used to build a dropdown list that is shown on the homepage, but the functionality to load Dartpad sources could be factored out and reused elsewhere on the site.

Such an approach would address this issue that we opened over dartpad: https://github.com/dart-lang/dart-pad/issues/788 Load content from any GitHub repo path.

Related: https://github.com/dart-lang/dart-pad/issues/1096 Load exercises from a repo in addition to gists. In particular this comment: https://github.com/dart-lang/dart-pad/issues/1096#issuecomment-517842744.

**Comment by RedBrogdon** [comment]
I've been working on this for a bit, and should have a PR to allow for loading from a repo ready for review in the next few days.

**Comment by chalin** [comment]
As I mentioned out-of-band, the [GitHub rate limit](https://developer.github.com/v3/#rate-limiting) (as was mentioned in [this comment](https://github.com/dart-lang/site-www/issues/1972#issuecomment-542870466)), might be another reason to explore the solution proposed here.
