### ISSUE TITLE
'Asynchronous programming: streams' page issue

### ISSUE THREAD

**Issue by iChicago** [dart-lang/site-www#1922]
Page URL: https://dart.dev/tutorials/language/streams
Page source: https://github.com/dart-lang/site-www/tree/master/src/_tutorials/language/streams.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

In the section *"Methods that modify a stream"* you added the method 
```dart Stream<R> retype<R>();```
I think this method was removed Stream<T> Class.
https://api.dart.dev/stable/2.5.0/dart-async/Stream-class.html

**Comment by kwalrath** [comment]
Fixed by #1923. Thank you, @iChicago!
