### ISSUE TITLE
Change default <code> color from RED to something else

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1929]
In general, the color of `<code>` elements under the new site design is the default `pretty-print` red. Red should be used parsimoniously.

> <img width="501" alt="Screen Shot 2019-09-20 at 09 12 52" src="https://user-images.githubusercontent.com/4140793/65329797-30f5e500-db87-11e9-93f6-74477e3be00d.png">

How about matching the flutter.dev color (##008f83, which happens to be the same color used on angulardart.dev and, I believe, was the same color that we used to have as part of the previous site design), or one that is just a bit darker in order to have [sufficient contrast](https://webaim.org/resources/contrastchecker) (#006555):

> ![image](https://user-images.githubusercontent.com/4140793/65330706-2ccac700-db89-11e9-8da3-a67fecc05b4f.png)

**Comment by chalin** [comment]
@kwalrath WDYT?

**Comment by kwalrath** [comment]
@mit-mit looking at the designs, the code font was supposed to be teal. I don't remember when/how it turned red, do you?

**Comment by chalin** [comment]
Under `flutter/website` the code color is defined on this line: https://github.com/flutter/website/blob/master/src/_assets/css/_bootstrap_adjust.scss#L102

```scss
code {
  color: #008f83;
}
```

It seems that that definition wasn't migrated over to site-www's `_bootstrap_adjust.scss` when the site redesign happened.

As a consequence, the code color defaults to what is defined at https://github.com/dart-lang/site-www/blob/master/src/_assets/css/_variables.scss#L141, which is the old color setting from over 3 years ago:

```scss
//== Code

$code-color:                  #c7254e;
$code-bg:                     #f9f9f9;
```

If we're going to use the same code color for site-www and flutter/website, then we might as well set it in https://github.com/dart-lang/site-shared/blob/master/src/_assets/css/_code_pre.scss.

**Comment by chalin** [comment]
Related issue: #1942

**Comment by dhanushuUzumaki** [comment]
Can I take this up?

**Comment by kwalrath** [comment]
No, I think the sites will each have their own colors.

**Comment by dhanushuUzumaki** [comment]
@kwalrath So, the new color for code would be #006555?
