### ISSUE TITLE
Delete examples_archive

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1931]
Examples contained in `examples_archive` are from the Dart 1 era. They've been kept around for long enough (in case we needed some old sources from there). It's probably a good time to delete this directory of mostly obsolete example code.

(Also remove the directory name from the top-level `analysis_options.yaml` file.)

**Comment by dhanushuUzumaki** [comment]
Hello, Can I take this up?

**Comment by kwalrath** [comment]
Yes please, @dhanushuUzumaki!

**Comment by dhanushuUzumaki** [comment]
@kwalrath PR Created https://github.com/dart-lang/site-www/pull/1975

**Comment by chalin** [comment]
Thanks! Closed by #1975
