### ISSUE TITLE
GitHub Actions: run tests under Windows too

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1932]
Given that most clients are under Windows, maybe we should consider (also) running site tests under Windows.

More info: [Windows support for Dart on Travis CI](https://medium.com/dartlang/announcing-windows-support-for-dart-on-travis-ci-8160f53662f)

**Comment by kwalrath** [comment]
@johnpryan, @domesticmouse, @filiph what do you think? Has it been an issue that the Dart source code in dart.dev isn't tested on Windows?

I'm loathe to complicate our build unless we've actually experienced a problem.

**Comment by johnpryan** [comment]
I don't think we need to run all of the tests on windows. The samples used in our command line apps articles could benefit, but yes this would increase the complexity of the build.

**Comment by parlough** [comment]
Currently this won't work for our Docker based infrastructure. We can revisit if we move to a Dart based infrastructure or someone feels strongly about this or is impacted by it.
