### ISSUE TITLE
Inline or move src/_includes/dart-html-tour.md

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1934]
The [src/_includes/dart-html-tour.md](https://github.com/dart-lang/site-www/blob/master/src/_includes/dart-html-tour.md) file is included from only one other file, namely `src/_guides/libraries/library-tour.md`. It would be better to either inline the include, or at least move it to the same folder as the including file, namely `src/_guides/libraries`.

Note that [src/_includes/dart-html-tour.md](https://github.com/dart-lang/site-www/blob/master/src/_includes/dart-html-tour.md) uses Jekyll comments rather than code-excerpt instructions (#1803).

**Comment by dhanushuUzumaki** [comment]
Hello, Can I take this up?

**Comment by kwalrath** [comment]
> Hello, Can I take this up?

Absolutely! Thank you!

**Comment by dhanushuUzumaki** [comment]
@kwalrath Should I inline the content or move the file to libraries?

**Comment by chalin** [comment]
I'd suggest that we start by relocating the file (you'll need to use an `include_relative` tag once that is done) until we've fix the code-excerpt-as-comments issue in that file.

**Comment by dhanushuUzumaki** [comment]
Hello, Raised a PR - https://github.com/dart-lang/site-www/pull/1961
