### ISSUE TITLE
'Creating streams in Dart' showing "Pending" comment

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#1947]
Page URL: https://dart.dev/articles/libraries/creating-streams
Page source: https://github.com/dart-lang/site-www/tree/master/src/_articles/libraries/creating-streams.md

https://github.com/dart-lang/site-www/blame/00af2b563253cfa6553707dfe251bde098c7c282/src/_articles/libraries/creating-streams.md#L261

> **[PENDING: Did we show this before?]**

I suspect it was intended to be wrapped in `{% comment %}`?

**Comment by kwalrath** [comment]
Oh goodness. I'm tempted to fix that right now, but I'll leave it to a new contributor. :)

**Comment by dhanushuUzumaki** [comment]
Hello, Can I take this up?

**Comment by kwalrath** [comment]
> Hello, Can I take this up?

Absolute, it's yours!
