### ISSUE TITLE
dart2aot -> dart2native

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1948]
The `dart2aot` command will be replaced by [`dart2native`](https://github.com/dart-lang/sdk/tree/master/pkg/dart2native).

We'll need to do the following:

* Write a new page for dart2native.
* Remove https://dart.dev/tools/dart2aot and redirect it to dart2native.
* Be sure to cover the aot & exe formats, and when you'd want each one.

/cc @mit-mit @cskau-g

**Comment by mit-mit** [comment]
Wrt. aot vs exe, I would say something like this:

The standard output format is executable. This produces a stand-alone executable that contains Dart source code ahead-of-time (AOT) compiled to native machine code, and a small Dart run-time system that handles type checking and garbage collection.

The option `-o aot` can be used to compile the source code to a native AOT machine code snapshot that doesn't include the Dart runtime. This produces a smaller output file, but it's not stand-alone. To execute these AOT snapshots, use the `dartaotruntime`. This option can be desirable when you need several programs, and want the smallest total size, as the runtime is not replicated across all the programs.
