### ISSUE TITLE
Clarify C/C++/... interop

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1955]
The Dart & Flutter FFI pages should be clearer about what languages you can interface to. E.g., currently the [Dart page](https://dart.dev/guides/libraries/c-interop) says "C interop", but the [Flutter page](https://flutter.dev/docs/development/platform-integration/c-interop) says "C/C++ interop".

According to @sjindel-google (from [this comment](https://github.com/flutter/website/issues/2941#issuecomment-535693884)):

> FFI can bind to a C _interface_, regardless of whether that interface is implemented by C, C++, Swift, Objective-C, Rust or even Go.

/cc @mjohnsullivan, @sfshaza2, @mit-mit

**Comment by mit-mit** [comment]
I suggest we just use 'C interop' everywhere

**Comment by dhanushuUzumaki** [comment]
Hello @kwalrath can I take this one? Should I update C/C++ interop to C interop in flutter docs?
https://github.com/flutter/website/blob/1fbbdc481550b9d8bc3b5ef29ca695575a839f4b/src/_data/sidenav.yml#L128

**Comment by kwalrath** [comment]
@dhanushuUzumaki I'm in the midst of figuring this one out, but you updating C/C++ interop to C interop in the Flutter docs SGTM (sounds good to me) if it's OK by @sfshaza2.

But first, let's wait until my PR (incoming) for this page is approved. That'll give you a model to follow.

**Comment by dhanushuUzumaki** [comment]
@kwalrath Sure.

**Comment by kwalrath** [comment]
Moving to flutter/website, since I believe that https://flutter.dev/docs/development/platform-integration/c-interop should use "C interop", to match what you see at https://dart.dev/guides/libraries/c-interop
