### ISSUE TITLE
Go through web tutorials, fix or report any issues

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1958]
We need someone(s) to go through each of the 4 tutorials at https://dart.dev/tutorials/web, reporting/fixing any issues. We especially want to know what's confusing to new Dart devs.

* [x] Fetch Data Dynamically (reviewer: @dhanushuUzumaki)
* [x] Connect Dart & HTML (reviewer: @wang-ories)
* [x] Add elements to the DOM (reviewer: @grieff)
* [x] Remove DOM elements (reviewer: @shreyansh-goyal)

Here are some issues we already know about:

* #1959 (link to mini, mini_with_style)
* ~#1807 (todo app missing)~ FIXED!
* ~#1800 (portmanteau example not working)~ FIXED!
* #1270 (dart-tutorials-samples is often out of sync)

**Comment by dhanushuUzumaki** [comment]
Hello, I would like to take this up.

**Comment by kwalrath** [comment]
> Hello, I would like to take this up.

That'd be great! How about you do one (just comment here to say which one you choose) and report back, and we'll decide how to proceed from there. Sound good?

**Comment by dhanushuUzumaki** [comment]
@kwalrath That's great. I will start with "Fetch Data Dynamically".

**Comment by wang-ories** [comment]
Hi @kwalrath, 
I would like to contribute and I can start with  this topic 
**Connect Dart & HTML**

**Comment by shreyansh-goyal** [comment]
HI @kwalrath 
I would like to take up with "Remove DOM Elements"

**Comment by grieff** [comment]
Hi @kwalrath 
I'll like to contribute ane check the remaining one, «Add elements to the DOM»

**Comment by kwalrath** [comment]
Thank you, all!

**Comment by MaxRupees** [comment]
@kwalrath Do you require anyone else to run through any of the tutorials a second time to receive and further feedback? If so I'd like to contribute.

**Comment by kwalrath** [comment]
@MaxRupees we have other tutorials, and it's always to get eyes on them. Would you be interested in running through any of the other tutorials at https://dart.dev/tutorials?

**Comment by dhanushuUzumaki** [comment]
Hello @kwalrath 
I went through the tutorial and found two issues with loading data.

https://dart.dev/tutorials/web/fetch-data#using-getString-function
https://dart.dev/tutorials/web/fetch-data#making-a-get-request

In both cases, the request fails and the data is not loaded. In network monitoring, I see both of those requests as canceled. Should I open an issue?

Regards,
Dhanushu A P

**Comment by kwalrath** [comment]
> Hello @kwalrath
> I went through the tutorial and found two issues with loading data.
> 
> https://dart.dev/tutorials/web/fetch-data#using-getString-function
> https://dart.dev/tutorials/web/fetch-data#making-a-get-request
> 
> In both cases, the request fails and the data is not loaded. In network monitoring, I see both of those requests as canceled. Should I open an issue?

Yes, please. Open an issue with all the details you can easily supply. Thanks!

**Comment by shreyansh-goyal** [comment]
"Remove DOM Elements" is working fine

**Comment by dhanushuUzumaki** [comment]
> > Hello @kwalrath
> > I went through the tutorial and found two issues with loading data.
> > https://dart.dev/tutorials/web/fetch-data#using-getString-function
> > https://dart.dev/tutorials/web/fetch-data#making-a-get-request
> > In both cases, the request fails and the data is not loaded. In network monitoring, I see both of those requests as canceled. Should I open an issue?
> 
> Yes, please. Open an issue with all the details you can easily supply. Thanks!

Created a new issue #1970

Regards,
Dhanushu A P

**Comment by kwalrath** [comment]
@wang-ories and @grieff, could you please update this issue with the results of your assigned web tutorial reviews? Thanks!

**Comment by wang-ories** [comment]
I worked on  Connect Dart & HTML tutorial and  I opened issue here : #1966
Thanks,

**Comment by grieff** [comment]
I've checked the "Add elements to the DOM" tutorial, and everything is working fine. Also, I doesn't seem to have anything that'll be confusing to new Dart users.

**Comment by kwalrath** [comment]
Thanks, everyone! I'm closing this issue.
