### ISSUE TITLE
Link/include mini, mini_with_style?

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1959]
The [source code](https://github.com/dart-lang/site-www/blob/24852a92f5eb1845d252ec1aa8018121a54b1b46/src/_tutorials/web/low-level-html/connect-dart-html.md) for https://dart.dev/tutorials/web/low-level-html/connect-dart-html captures sample_links for mini & mini_with_style, but the new site doesn't use sample_links.

This page should instead link to that source code directly — or maybe we should just move it to site-www, where we can test and include it.

Related: #1803

**Comment by parlough** [comment]
These are no longer referenced with https://github.com/dart-lang/site-www/commit/53fb128420f99bc34f84329869b4e6c402e29e56.
