### ISSUE TITLE
Pub links redirect to the main pub page

### ISSUE THREAD

**Issue by nex3** [dart-lang/site-www#196]
Many of the links on [the pub page](https://www.dartlang.org/tools/pub) are currently broken—they redirect to the page they're on rather than going to useful information. Try clicking the "Pub Dependencies" link, for example.

**Comment by filiph** [comment]
Fixed. Thanks for reporting!

cc @kwalrath @Sfshaza: Let's make sure we don't use all-encompassing wildcard redirects (like `/pub/**` when there are sub-redirects (like `/pub/whatever`) present. Firebase doesn't follow the specific-first rule. Basically, we can't have 'everything else' redirects.
