### ISSUE TITLE
Add info about bundling a library using dart compile

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1960]
/cc @mit-mit 

Context: #1954

**Comment by MrBirb** [comment]
Same thing here. The dart compile command replaced the dart2native and dart2aot commands.

**Comment by atsansone** [comment]
Updated in https://github.com/dart-lang/site-www/pull/1954/. Closing.

**Comment by parlough** [comment]
@atsansone This one is still not complete. We don't yet document how to bundle native libraries with `dart compile` executables.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/5388, since that will be a consolidated, first-party story for this question. I don't think we'll have time to document this before that's ready anyway.
