### ISSUE TITLE
DartPad appears on mobile Safari

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#1965]
I'm not sure if we want to show DartPad on mobile devices. It still works, but isn't quite as usable.

![Image-1](https://user-images.githubusercontent.com/1145719/65986668-2bc35080-e439-11e9-8693-712292a993e5.jpg)

**Comment by parlough** [comment]
The new DartPad UI has a more usable, adaptive experience on mobile devices, so I'm going to close this for now in favor of more specific [issue on the DartPad repository](https://github.com/dart-lang/dart-pad/issues) around the mobile experience.

I also would like to see much of the uses of DartPad on dart.dev replaced with a more lightweight experience as well. Tracking that possibility in https://github.com/dart-lang/dart-pad/issues/2702.
