### ISSUE TITLE
homepage looks bad when window is very wide

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1969]
URL: https://dart.dev

@mit-mit noticed that when you have a large monitor and maximize the window, you end up with the homepage flowing to the full width, and the "proof points" looking very enlarged.

The designer says that we should limit the max-height to 644px, and allow for empty space on each side rather than scaling the images to the width of the container. Here's a mockup:

![image](https://user-images.githubusercontent.com/2164483/66153745-ef2a5d00-e5d0-11e9-9f8e-10e989ce294f.png)

@johnpryan would this be easy to fix?

**Comment by johnpryan** [comment]
I think so - I'll take a look.
