### ISSUE TITLE
Tutorial Fetch Data Dynamically - Unable to load data in sandbox. Request is cancelled.

### ISSUE THREAD

**Issue by dhanushuUzumaki** [dart-lang/site-www#1970]
I went through the tutorial and found two issues with loading data.

https://dart.dev/tutorials/web/fetch-data#using-getString-function
https://dart.dev/tutorials/web/fetch-data#making-a-get-request

In both cases, the request fails and the data is not loaded. In network monitoring, I see both of those requests as canceled.

![image](https://user-images.githubusercontent.com/14927280/66160496-e39a5e80-e5ef-11e9-9d78-97302ce0e558.png)

**Comment by kwalrath** [comment]
It looks like we just need to update the gists to change www.dartlang.org to dart.dev. Here's a similar change:

https://github.com/dart-lang/site-www/issues/1800#issuecomment-536180384

**Comment by wang-ories** [comment]
Hello @kwalrath 
Can I fixed this one?

**Comment by kwalrath** [comment]
Yes, please, @wang-ories!

**Comment by dhanushuUzumaki** [comment]
@kwalrath Updated the gist in my fork https://gist.github.com/dhanushuUzumaki/7f53d30c278259db277373944057e0f8

**Comment by kwalrath** [comment]
Your changes look good, and I've forked them here:

https://gist.github.com/kwalrath/f8aa7310e96d359c5f68343c9ccba8ed

Now you just need to create a PR that embeds f8aa7310e96d359c5f68343c9ccba8ed instead of the current gist.

**Comment by kwalrath** [comment]
(Of course, there are two samples that need to be updated.)

**Comment by dhanushuUzumaki** [comment]
PR created - https://github.com/dart-lang/site-www/pull/1971

Regards,
Dhanushu

**Comment by kwalrath** [comment]
Oops, @wang-ories, I didn't remember that @dhanushuUzumaki had already started on this.

Could you please pick another bug?

**Comment by dhanushuUzumaki** [comment]
Sorry, @wang-ories I didn't saw the earlier comment.

**Comment by wang-ories** [comment]
@kwalrath It is Ok, I will pick another bug .
