### ISSUE TITLE
more DartPad troubleshooting...

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1972]
From #1967:

* Add an include for the DartPad troubleshooting page high up in https://dart.dev/tutorials/web/low-level-html/add-elements (probably deleting the include that's lower in that page).
* Add info to the DartPad troubleshooting page about what happens if you load too many DartPads and run into GitHub rate-limiting. (Rare unless you're repeatedly reloading a page full of DartPads.)

**Comment by dhanushuUzumaki** [comment]
@kwalrath Can I take this up?

**Comment by dhanushuUzumaki** [comment]
@kwalrath for the second part, what should be the content?

**Comment by kwalrath** [comment]
For the second part, I think we need to add a bullet to the https://dart.dev/tools/dartpad/troubleshoot#embedded-dartpads-dont-appear section, saying something like this:

* If you repeatedly reload a page that contains embedded DartPads, then you might run into [GitHub rate limiting.](https://developer.github.com/v3/#rate-limiting) Within 60 minutes, you should be able to reload the page and see code in the embedded DartPads.

**Comment by kwalrath** [comment]
Looks like this was fixed by #2001.
