### ISSUE TITLE
Go through package tutorial, report/fix issues

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1977]
https://dart.dev/tutorials/libraries/shared-pkgs

See #1958 for a similar pass through tutorials.

**Comment by wang-ories** [comment]
Hello @kwalrath ,
I would like to pass through this tutorial and report issues.

**Comment by kwalrath** [comment]
It's yours. Thank you!

**Comment by wang-ories** [comment]
OK

**Comment by wang-ories** [comment]
@kwalrath  I found  just  one typo : a reference to pub.dev site at this line 
**You can follow these same steps to install any package hosted at the [Pub site](https://pub.dev;.** 
The close parenthesis is missing and the link is not working.

**Comment by kwalrath** [comment]
Thank you! Would you like to file an issue or just fix it?

**Comment by wang-ories** [comment]
Just fix it.

**Comment by kwalrath** [comment]
> Just fix it.

Cool, I'll look for a PR from you.

**Comment by wang-ories** [comment]
Ok, great!
