### ISSUE TITLE
dartpad links on https://www.dartlang.org/tutorials/language/futures are broken

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#198]
_From @aam on December 13, 2016 0:41_

Dartpad code examples show no code.

_Copied from original issue: dart-lang/sdk#28082_

**Comment by mit-mit** [comment]
@aam, I cannot repro this. Does this still repro for you? If so, can you add a few more details (OS, browser).

**Comment by aam** [comment]
That is on mac os 10.12.1 in chrome 54.0.2840.98. It still doesn't work on this machine. Looking at the console log in chrome I see the following:
===
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
https://api.github.com/gists/38feef09be9b1e7b5136 Failed to load resource: the server responded with a status of 403 (Forbidden)
embed.dart.js:8590 Error loading gist 38feef09be9b1e7b5136.
Instance of 'ta'
https://api.github.com/gists/15d5ef986238c97dbc14 Failed to load resource: the server responded with a status of 403 (Forbidden)
embed.dart.js:8590 Error loading gist 15d5ef986238c97dbc14.
Instance of 'ta'
https://api.github.com/gists/da80b1e7eed75db53ef3 Failed to load resource: the server responded with a status of 403 (Forbidden)
embed.dart.js:8590 Error loading gist da80b1e7eed75db53ef3.
Instance of 'ta'
===

I am able to login into github without problems.

**Comment by filiph** [comment]
FWIW, I also cannot reproduce (I have Mac OS 10.11.6 and Chrome 54.0.2840.98, I also tried on a Windows and a Linux machine). You don't need to be logged into github for this to work (I just tried in an incognito window and the code still loads).

@aam, what do you see when you access https://api.github.com/gists/15d5ef986238c97dbc14 directly? Can you paste the response headers here, please?

**Comment by aam** [comment]
@filiph , https://api.github.com/gists/15d5ef986238c97dbc14 returned reasonable results:
```
{
  "url": "https://api.github.com/gists/15d5ef986238c97dbc14",
  "forks_url": "https://api.github.com/gists/15d5ef986238c97dbc14/forks",
  "commits_url": "https://api.github.com/gists/15d5ef986238c97dbc14/commits",
  "id": "15d5ef986238c97dbc14",
  "git_pull_url": "https://gist.github.com/15d5ef986238c97dbc14.git",
  "git_push_url": "https://gist.github.com/15d5ef986238c97dbc14.git",
  "html_url": "https://gist.github.com/15d5ef986238c97dbc14",
  "files": {
    "main.dart": {
      "filename": "main.dart",
      "type": "text/plain",
      "language": "Dart",
      "raw_url": "https://gist.githubusercontent.com/Sfshaza/15d5ef986238c97dbc14/raw/4a0b87ed307abb1edd9d17373439222740b0d9b7/main.dart",
      "size": 582,
      "truncated": false,
      "content": "// Copyright (c) 2015, the Dart project authors.\n// Please see the AUTHORS file for details.\n// All rights reserved. Use of this source code is governed\n// by a BSD-style license that can be found in the LICENSE file.\n\nimport 'dart:async';\n\nFuture<int> sumStream(Stream<int> stream) async {\n  var sum = 0;\n  await for (var value in stream) {\n    sum += value;\n  }\n  return sum;\n}\n\nStream<int> countStream(int to) async* {\n  for (int i = 1; i <= to; i++) {\n    yield i;\n  }\n}\n\nmain() async {\n  var stream = countStream(10);\n  var sum = await sumStream(stream);\n  print(sum); // 55\n}\n"
    }
...
```

And after that I tried https://www.dartlang.org/tutorials/language/futures again, and the content of dartpad snippets is populated. (30 minutes ago it came back empty).

**Comment by filiph** [comment]
Thanks @aam! This is weird but looks like an issue with the gist API itself. We'll keep an eye on it.

If this every happens again, please let us know (context would be super helpful, like what happened since this last worked for you).

Thanks again.
