### ISSUE TITLE
"Effective Dart: Style" page issue regarding do-use-curly-braces-for-all-flow-control-structures

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/site-www#1994]
Link: https://dart.dev/guides/language/effective-dart/style#do-use-curly-braces-for-all-flow-control-structures  
Source: https://github.com/dart-lang/site-www/blob/master/src/_guides/language/effective-dart/style.md  

The "DO use curly braces for all flow control statements." section (see link) states that the **dangling else** problem should be avoided, however, it also states that curly braces should be used for "**all** flow control statements" including `for`-loops, which cannot possibly create a situation that has the dangling else problem.

It should sensibly say that curly braces should be used for flow control statements that could lead to a dangling else problem, i.e. only statements with multiple `if`s and at least one `else`.  
For consistency one could argue that `if` `else` should always use curly braces, but `for`-loops and single `if`-statements, even if they reach the next line, have nothing to do with the problem and curly braces are unhelpful in that case because they add noise to the code when they can just be ommited without any negative effects regarding readability.

Related issue: https://github.com/dart-lang/linter/issues/1763

**Comment by kwalrath** [comment]
@munificent what do you say?

**Comment by munificent** [comment]
Good point. Dangling else is only one reason we prefer curlies on all multi-line control flow statements. Another key one is that it is less error-prone when a user adds another line of code to the body of a statement. [This](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/) is a famous example of problems that can cause.

**Comment by suztomo** [comment]
(Not sure this issue is for voting) As a Flutter user, I prefer to have braces for all `for` statements regardless of the length of the body.

@creativecreatorormaybenot You may want to rename the issue title. E.g., "Effective Dart: Style" exclude for-statement from curly_braces_in_flow_control_structures

**Comment by munificent** [comment]
> (Not sure this issue is for voting) As a Flutter user, I prefer to have braces for all `for` statements regardless of the length of the body.

Yes, that is the current rule, and I don't think we plan to change it.

**Comment by suztomo** [comment]
Thank you for clarification.
