### ISSUE TITLE
中文翻译错别字

### ISSUE THREAD

**Issue by duanxianze** [dart-lang/site-www#1996]
使用静态类型(例如前面示例中的 num ) 可以更清晰的表明你的意图，并且可以让静态分析工具来分析你的代码， 但这并不是牵制性的。（在调试代码的时候你可能注意到 没有指定类型的变量的类型为 dynamic。）

牵制 应该为 强制

**Comment by kwalrath** [comment]
Can you please tell me the URL where you found this issue?

**Comment by duanxianze** [comment]
The URL is [dart](http://dart.goodev.org/guides/language/language-tour)。It is a Chinese documentation of Dart.I can't confirm if this is an official document。but there is a link to here.

**Comment by kwalrath** [comment]
Thanks, @duanxianze. I don't control that site, but I'm gathering issues under the "localization" label.

**Comment by parlough** [comment]
Thanks again for the report! As far as I can tell this content is not on the original page anymore, so I will close this issue.

I believe the content at dart.cn is relatively up to date and its language tour does not appear to have this issue, so I recommend you check there: https://dart.cn/guides/language/language-tour

If you have any more issues or suggestions, feel free to open a new issue. Thanks!
