### ISSUE TITLE
Update /web/deployment

### ISSUE THREAD

**Issue by mnordine** [dart-lang/site-www#1997]
https://dart.dev/web/deployment#use-dart2js-flags-to-produce-better-javascript

Mentions `fast-startup` flag. For more info, it links to https://dart.dev/tools/dart2js, which does not mention this flag.

And then from the CHANGELOG: https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#dart2js-2

> The old "full emitter" back-end is removed and dart2js always uses the "fast startup" back-end. The generated fast startup code is optimized to load faster, even though it can be slightly larger. The --fast-startup and --no-fast-startup are allowed but ignored. They will be removed in a future version.

**Comment by kwalrath** [comment]
Thanks for the report, @mnordine. If you'd like to fix this, we'd welcome your PR.

**Comment by mnordine** [comment]
I'm not sure I'm in a position to? I can't find any information on what `fast-startup` does exactly, and if it is indeed removed? It mentions "in a future version". If it is indeed removed, I could remove mention of it, of course.

**Comment by kwalrath** [comment]
It looks like the whole page (https://dart.dev/web/deployment) could use an update. Some of that information looks pretty old.

@jacob314 or @vsmenon, who'd be a good person to take a fresh look at this page?

**Comment by vsmenon** [comment]
@sigmundch - I think `--fast-startup` is obsolete (now the default).

Generally, this page is somewhat redundant with https://dart.dev/tools/webdev too.

**Comment by kwalrath** [comment]
I think /web/deployment should more about deployment tips and processes, and /tools/webdev (theoretically, at least) should be more of an overview of Dart web tools, with links to tool reference pages and to pages that cover tool usage.

**Comment by sigmundch** [comment]
> @sigmundch - I think --fast-startup is obsolete (now the default).
correct, `fast-startup` is now the only emitter we have
