### ISSUE TITLE
Optional Parameters vs Optional Named Parameters

### ISSUE THREAD

**Issue by Dstri26** [dart-lang/site-www#2002]
Case : Optional Parameters 
int func1(int a, int b, [int c])
{ 
        ......;
}
Calling Function for this is : 
func1(2,3,5);

Case : Optional Named Parameters 
int func1(int a, {int b, int c})
{
       .......;
}
calling function has to be 
func1(2, b : 3 , c : 5) ;
//This won't accept just func1(1,2,3)

Issue is why have two different Function types when we can just make them one.

Just Example : 
void func1(int a , int b , int c)
{
            .........  ;
}
and both calling function 
func1(2,3,4);
or
func1(a:2, b:3 ,4);
will work for same declaration
No need to have 2 different function type.

**Comment by kwalrath** [comment]
This sounds like a language design issue, not a documentation issue. There might be some discussion in one of our [communities](https://dart.dev/community#join-the-conversation).

If you're sure you want to propose a language change, https://github.com/dart-lang/language is the place to go.
