### ISSUE TITLE
Improve Lang-tour const constructors explanation

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/site-www#2010]
There was a doubt in this repo's Gitter about const constructors.
@zoechi answered very well here:

> a const constructor has constraints, like it can't have a body.
> A class can have const constructors and non-const constructors. Only const constructors can be used to create constant values.
> You still can have runtime-created instances of the same class, for example if parameter values can't be provided as constants.

It would be nice to have that answer included in 
https://www.dartlang.org/guides/language/language-tour#using-constructors

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/4350 to consolidate issues related to `const` in the language tour. Thanks!
