### ISSUE TITLE
Possible minor error in Windows instructions for Native Extensions

### ISSUE THREAD

**Issue by DanTup** [dart-lang/site-www#2012]
On this page:

https://www.dartlang.org/articles/dart-vm/native-extensions#wrapping-the-c-function

Under the Windows section, it says:

2. Configuration properties / C/C++ / General / Additional Include Directories: Add the path to the directory containing dart_api.h, which is dart-sdk/include in the downloaded Dart SDK.

However I think this is slightly incorrect. The sample code contains these includes:

```cpp
#include "include/dart_api.h"
#include "include/dart_native_api.h"
```

These paths are relative to the SDK root, not the include folder. To avoid compile errors, I had to add the SDK root folder to *Additional Include Directories*, not the include directory.

I didn't send a PR to fix this, because I haven't made the whole thing work yet, so I'm not totally positive the above is sound (C/C++ are not my forté!).

**Comment by kwalrath** [comment]
Obsolete? (see https://github.com/dart-lang/site-www/issues/2015#issuecomment-544740455)

**Comment by DanTup** [comment]
If those docs are going away in favour of new FFI ones, then I think so. I don't know if that's certain (I'm not at all familiar with this side of things and the linked comment looks like an open question). Feel free to close if/when you think that's the case 👍

**Comment by kwalrath** [comment]
Closing because these docs are going away.
