### ISSUE TITLE
Stale documentation about the event loop

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/site-www#2014]
On the page https://webdev.dartlang.org/articles/performance/event-loop, in the section titled "Microtask queue: scheduleMicrotask()", there is a reference to two issues to explain the "current" behavior. Both of these issues are now closed, so it seems likely that this section should be updated.

**Comment by kwalrath** [comment]
We've removed that article and redirected it to https://medium.com/dartlang/dart-asynchronous-programming-isolates-and-event-loops-bffc3e296a6a.
