### ISSUE TITLE
Location for native-extension if provided for Linux and Raspberry / Anatomy of native extension

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/site-www#2015]
Here https://www.dartlang.org/articles/dart-vm/native-extensions#anatomy-of-a-native-extension
your say 
> For example, extensions becomes libextension.so on Linux

What if I want to provide precompiled libs for Linux x64 **and** Raspberry Pi - both names are identical...

**Comment by kwalrath** [comment]
@a-siva we're removing https://dart.dev/server/c-interop-native-extensions in favor of https://dart.dev/guides/libraries/c-interop, right? (E.g. see dart-lang/site-www#1389) If so, this issue should be closed.

**Comment by a-siva** [comment]
Yes that is correct https://dart.dev/guides/libraries/c-interop will still be a beta version and we will have a transition period before  https://dart.dev/server/c-interop-native-extensions is completely deprecated.

**Comment by kwalrath** [comment]
Closing because we don't plan to update the native extensions page.
