### ISSUE TITLE
'Asynchronous programming: futures, async, await' page issue

### ISSUE THREAD

**Issue by TunSawThant** [dart-lang/site-www#2019]
Page URL: https://dart.dev/codelabs/async-await/
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/async-await/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by chalin** [comment]
Hi. Thanks for opening an issue, but you haven't provided a description so I'm going to close it for now. You can still add a description after it's closed; if you do that, we'll reopen the issue.
