### ISSUE TITLE
Deprecating the `authors` field in `pubspec.yaml`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#2029]
Maybe wait until https://github.com/dart-lang/pub/issues/2234 is done, as the `authors` field is currently required when publishing a package.

In the future the `authors` field will not be displayed on `pub.dev`. The `pub publish` command will warn that it has been deprecated, but beyond that there is no harm in including the field.

However, once https://github.com/dart-lang/pub/issues/2234 has landed in `pub` and released in a stable Dart/Flutter release, we should be sure to update the documentation site.

**Comment by jonasfj** [comment]
/CC @sigurdm, who is working to make this land in Dart 2.7.

**Comment by kwalrath** [comment]
This is apparently visible in at least some releases, per #2084, so I should update the docs.

**Comment by sigurdm** [comment]
Yes - I think that would be fine.

**Comment by pouloghost** [comment]
We have deployed a pub server inside our company, and author field is crucial for looking for the developer of the package/plugin.
All packages are published using one CI machine, hence we can't use uploader.
And I think this is more or less the standard routine in big companies, so
What is the purpose of deprecating author? What's the alternative?

**Comment by sigurdm** [comment]
> What is the purpose of deprecating author? What's the alternative?

The problem with the authors field is that there is no validation of it.
You could claim you are A else misusing the end-users trust in A.

Therefore we have stopped displaying it on pub.dev.
We find it misleading to support a tag that we are never going to use.

Though it is deprecated you can still use it internally on your own server - I don't think we can or will ever forbid you from doing that.

Alternatively you can invent your own alternative field for this information. The [pubspec docs](https://dart.dev/tools/pub/pubspec) explains that you can add custom fields. For example: `<company_name>_authors` or some such.

I don't know how you are using the author information, but for CI error reporting you should probably look up the person making the commit that triggered the CI run instead. For Travis you can maybe use
https://stackoverflow.com/questions/39681509/travis-ci-how-to-get-committer-email-author-name-within-after-script-command

**Comment by kwalrath** [comment]
Fixed in #2085.
