### ISSUE TITLE
Upgrade to Jekyll 4 and the latest jekyll-assets

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#2043]
AFAICT, Jekyll 3.x development has stopped: the jekyll repo 3.x branches are all closed. Only `jekyll` 4 uses `jekyll-sass-converter` 2, which uses `sassc` instead of `sass` that has reached end-of-life.

For the Jekyll 4 change log, see https://github.com/jekyll/jekyll/releases/tag/v4.0.0.

Blocked by `jekyll-assets`, awaiting support for Jekyll 4: https://github.com/envygeeks/jekyll-assets/issues/613. Another option would be to use jekyll-assets at head (for fork and pin the current HEAD), since it is working with Jekyll 4; but given the thread of discussion in https://github.com/envygeeks/jekyll-assets/issues/613 it is probably advisable to wait.

**Comment by chalin** [comment]
(Given that #1758 was a p2, this is at least a p2 as well.)

**Comment by chalin** [comment]
A bit more motivation: AFAICT, Jekyll 3.x development has stopped: the jekyll repo 3.x branches are all closed. Only jekyll 4 uses jekyll-sass-converter 2, which uses sassc instead of the deprecated sass gem.

**Comment by chalin** [comment]
Another option would be to use jekyll-assets at head (for fork and pin the current HEAD), since it is working with Jekyll 4.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/pull/3765
