### ISSUE TITLE
SDK Archive sorting is weird

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/site-www#2046]
When I go to the [Dart SDK Archive page](https://dart.dev/tools/sdk/archive) to download a .zip file, for Linux I see:

![image](https://user-images.githubusercontent.com/17391434/57399893-12b6bc00-7187-11e9-9fb1-cec438f2f243.png)

1. The "32-bit" and "64-bit" entries don't specify what CPU architecture they're for.  They should be labeled "ia32" and "x64" instead (or "x86" and "x64", but "ia32" matches the filename).

2. The "Bits" column is misnamed. (It probably made more sense before ARM versions were added.) "Architecture"/"Arch." would be better.

3. The sort order seems odd.  I expect that most people want the ia32/x64 versions instead of the ARM ones, yet the ARM ones are listed first.  64-bit versions probably should be favored over 32-bit ones too.

(This also would be consistent with the "Download URLs" section, which refers to "`<architecture>`" in the URL format.)

**Comment by mit-mit** [comment]
Closing as this seems to have been resolved:

<img width="528" alt="Screenshot 2020-04-29 at 15 21 09" src="https://user-images.githubusercontent.com/13644170/80600703-17761f00-8a2d-11ea-9a7b-bb858217c560.png">

**Comment by jamesderlin** [comment]
It's certainly better now than it used to be, but the ordering still seems kind of weird.  Presumably ia32 and ia64 appear above ARMv7 and ARMv8 because most people downloading the SDK are downloading for an x86-based desktop, but by the same reasoning, x64 should be first.
