### ISSUE TITLE
Link to native_app

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2063]
The soon-to-be-released dart2native page might have this:

![image](https://user-images.githubusercontent.com/2164483/68162170-498a4680-ff0c-11e9-9ee3-062523fd3081.png)

We might also want to link to the example from other pages.

/cc @johnpryan

**Comment by MrBirb** [comment]
Looks like the dart compile command replaced the dart2native command.

**Comment by kwalrath** [comment]
> Looks like the dart compile command replaced the dart2native command.

Yep, we should add this link to https://dart.dev/tools/dart-compile.

Also related: #3221
