### ISSUE TITLE
Change Windows installer link to be https

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#2072]
The [community supported Windows installer](http://www.gekorm.com/dart-windows) referenced in:

https://github.com/dart-lang/site-www/blob/a4b74d94bf0e94fafbaeb4af8e55f69ff4abf39b/src/tools/sdk/_windows.md#L50-L55

Only has an HTTP-only website (ie. without HTTPS support).

https://github.com/dart-lang/site-www/blob/a4b74d94bf0e94fafbaeb4af8e55f69ff4abf39b/src/tools/sdk/_windows.md#L61

@GeKorm, is this still maintained? If so could we consider upgrading the website to HTTPS, or moving it to some static web host with HTTPS support.

Or maybe we should consider not advertising this installation method.

**Comment by jonasfj** [comment]
I just saw the github repository [github.com/GeKorm/dart-windows](https://github.com/GeKorm/dart-windows), which has been updated fairly recent, so I assume this is still maintained.

@GeKorm, maybe it would be safer to host the website for the installer on github pages which has HTTPS?

**Comment by GeKorm** [comment]
Hi, it is indeed hosted on github pages. I'll look into enabling HTTPS, thanks

**Comment by jonasfj** [comment]
If it's on GitHub pages it should just be an option to enforce HTTPS:
https://github.blog/2018-05-01-github-pages-custom-domains-https/

Thanks for looking into this :)

**Comment by GeKorm** [comment]
Yep those are the changes. Github used a different set of IPs for A records before that blog post

**Comment by GeKorm** [comment]
Should be good now, with http -> https redirection

**Comment by kwalrath** [comment]
Thanks, @GeKorm!
