### ISSUE TITLE
"Get the Dart SDK" page has list bullet points on top of the text

### ISSUE THREAD

**Issue by refi64** [dart-lang/site-www#2075]
![Screenshot from 2019-11-07 12-26-19](https://user-images.githubusercontent.com/1690697/68416624-7895f780-015a-11ea-88ca-f96fe663fdf9.png)

The bullet points for the channel list somehow got stuck on top of the above text.

**Comment by kwalrath** [comment]
Known problem. :( Closing as a duplicate of #2054.

(@refi64, if you have any additional information, #2054 would be a great place to put it.)

**Comment by refi64** [comment]
Worth noting I had this appear on Chrome though...

**Comment by kwalrath** [comment]
That is definitely worth noting! Which version of Chrome? Can you reproduce it?
