### ISSUE TITLE
Add legend to "Core libraries" page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2077]
In https://dart.dev/guides/libraries, it's unclear what JIT and AOT mean. You shouldn't have to go to the platform page to see those definitions.

Related: #2070

**Comment by micpap25** [comment]
I feel like the existence of this issue contradicts #2091 and might be confusing for people looking through the issues. I think this can be closed and the importance of #2091 be stressed.

**Comment by kwalrath** [comment]
Even with a glossary, it's still a good idea to define acronyms before using them. I'm going to leave this issue open, since even if we have a glossary, we'll still need to define the acronyms (or at least link to the glossary).

**Comment by parlough** [comment]
Marking this as fixed by https://github.com/dart-lang/site-www/issues/2077 which links to more resources and clarifies the words with modifiers.
