### ISSUE TITLE
Either support zsh or clarify that only bash is supported

### ISSUE THREAD

**Issue by miquelbeltran** [dart-lang/site-www#2080]
I am trying to run the site and I am facing an issue with the installation scripts.

At the step "3. Run installation scripts" I can't get past the step:

> `./tool/before-install.sh`   # install core set of required tools

The error I get is:

```
dart-lang/site-www [master] » ./tool/before-install.sh
Dart SDK appears to be installed: dart is /usr/local/bin/dart
Dart VM version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "macos_x64"
tool/shared/before-install.sh: line 26: travis_fold: command not found
```

I installed `travis-fold` using `npm install -g travis-fold` but I still see the error.

I use a MacOs 10.15.1, iTerm2 and zsh.

Thankfully I was able to continue the setup manually by running `npm install` and `bundle install`, then I've been able to run the site by using `jekyll serve --livereload` for example.

**Comment by chalin** [comment]
Hi Miguel. We only currently support the use of `bash` to build the site, not `zsh` (though I did try to adapt the scripts to zsh a little while back, but couldn't get it to work and, I needed to move on to other things). So if you'd like to use the build scripts "as is", then you'll need to launch an interactive `bash` session first.

I do realize that `zsh` is the default shell under macOS 10.15, so maybe that'll bump up the priority in looking into `zsh` support. cc @kwalrath @legalcodes

**Comment by miquelbeltran** [comment]
Thanks! indeed, when I run the install scripts from within `bash` they work as expect.

**Comment by chalin** [comment]
Changed the title to just "support zsh". @kwalrath @legalcodes I'll let you decide if you think that this is worthwhile, and assign a priority.

**Comment by kwalrath** [comment]
We can't justify supporting zsh at this time, but we should clarify that the scripts expect bash.

**Comment by chalin** [comment]
I thought that we already has such a comment in this site's README, but we don't yet. Ah, it seems that I had only added the bash prerequisite to the flutter.dev README: https://github.com/flutter/website/blob/master/README.md#1-get-the-prerequisites.
