### ISSUE TITLE
'The pubspec file' page issue with author field

### ISSUE THREAD

**Issue by larryaasen** [dart-lang/site-www#2084]
Page URL: https://dart.dev/tools/pub/pubspec.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/pubspec.md

Description of issue:
I just used pub publish -n and it reported this error:
`Your pubspec.yaml includes an "author" section which is no longer used and may be removed.`

However, the documentation still includes `author` as a valid field.

```
$ dart --version
Dart VM version: 2.6.0-dev.8.2.flutter-bbe2ac28c9 (Wed Oct 30 22:13:25 2019 +0000) on "macos_x64"
```

**Comment by kwalrath** [comment]
Thanks for letting us know this is now visible! I'm closing this in favor of #2029, and I've removed the **blocked** label from that issue.
