### ISSUE TITLE
External link icons aren't shown in sidenav

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#2088]
Flutter.dev has external link icons showing in the sidenav (both under mobile and desktop), e.g.:

> <img width="400" alt="Screen Shot 2019-11-13 at 14 15 40" src="https://user-images.githubusercontent.com/4140793/68796215-7e8b4d00-0620-11ea-9a37-d201617b6b6d.png">

Why have external link icons explicitly been hidden for dart.dev? Shouldn't we be showing them too @kwalrath? /cc @legalcodes

**Comment by kwalrath** [comment]
I think it was a conscious choice — they were ugly, we didn't have many of them, and they were clustered together so it didn't seem necessary.

For some reason, I thought flutter.dev didn't have external link icons in the regular text, so I was surprised to see them in the menu.

**Comment by chalin** [comment]
Adding external link icons to flutter.dev is WIP. That is why the sidenav has them, and not the main text :).

**Comment by kwalrath** [comment]
Closing this because we don't plan to add icons to the dart.dev sidenav
