### ISSUE TITLE
'DartPad' page issue: packages are supported

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#2090]
Page URL: https://dart.dev/tools/dartpad/
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/dartpad/index.md

From the page:

> DartPad ... doesn’t support dart:io or libraries from packages.

But packages are supported, e.g., see the embedded DartPad from the [Flutter.dev layout codelab](https://flutter.dev/docs/codelabs/layout-basics#row-and-column-classes):

> <img src="https://user-images.githubusercontent.com/4140793/68803893-9b2e8180-062e-11ea-9b36-1e0ca1a23f81.png" width=400>

**Comment by chalin** [comment]
I see from the [DartPad wiki "Embedding Guide"](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide#embed-flutterhtml) that `flutter_web` packages are available. If those are the _only_ packages that are available, then maybe all we need is a note to that effect? /cc @kwalrath @johnpryan

**Comment by kwalrath** [comment]
Yes, I believe that only flutter_web packages are available, and only under certain circumstances.

@RedBrogdon is there a page with the details about dartpad package support?

**Comment by johnpryan** [comment]
Here's the issue for package support: https://github.com/dart-lang/dart-pad/issues/901

**Comment by RedBrogdon** [comment]
John's on the money. For dart you can import the `dart:xxx` libraries. For Flutter you gain additional access to `package:flutter/xxx.dart`, but that's the limit of our support for now.
