### ISSUE TITLE
Create top-level glossary

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#2091]
Might it make sense to move `src/tools/pub/glossary.md` to the top level and use it as the basis for a general Dart glossary? We'd then have a place to add glossary entries for terms like AOT and JIT (#2077).

**Comment by kwalrath** [comment]
Yes, it might make sense... Let's use this issue to talk about which terms we'd want in a top-level glossary.

**Comment by atsansone** [comment]
Page was created in https://github.com/dart-lang/site-www/pull/4630. Closing.

@MaryaBelanger : If you want to add these terms to the glossary, go ahead.
