### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by broislove** [dart-lang/site-www#21]
URL: https://www.dartlang.org/docs/cookbook/#strings
Expected page: https://www.dartlang.org/dart-vm/dart-by-example ???

Link from https://api.dartlang.org/stable/1.17.1/dart-core/String-class.html, chapter "Other resources"

**Comment by filiph** [comment]
Thanks for the report and sorry about the broken link. The fix (https://github.com/dart-lang/site-www/commit/10dddfb581899cf2301c5fda0e2f5d424b35fb42) is deploying now.
