### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by paultz54** [dart-lang/site-www#211]
URL: https://www.dartlang.org/guides/language/library-tour
Expected page: https://www.dartlang.org/guides/libraries/library-tour

**Comment by kwalrath** [comment]
@paultz54 where did you find the original URL?

**Comment by Sfshaza** [comment]
Yes, where did this link come from? And thanks!

I've fixed this as  part of the top 18 broken links for the last week. Closing.

https://github.com/dart-lang/site-www/commit/30edfd73aa2072a316292b638d0a1f2b02d7cdf7
