### ISSUE TITLE
examples/fetch_data: write tests or check web app build for problems

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#2113]
At least a smoke test. Alternatively, until tests are written, we could at least run `webdev build` to ensure that no errors are reported.

For the record, the code is at least being analyzed.

**Comment by parlough** [comment]
Going to close this in favor of https://github.com/dart-lang/site-www/issues/3852 where we're going to replace the article with a cross-platform one. I'm writing tests and code excerpts in that process.
