### ISSUE TITLE
cross-site cookie warnings in console

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#2117]
There are multiple warnings in the console on the dart.dev homepage:

![image](https://user-images.githubusercontent.com/1145719/69173361-744fcf80-0ab4-11ea-8122-ca3cfa9d4f4e.png)

This is related to #2115

**Comment by chalin** [comment]
FYI, I opened https://github.com/dart-lang/dart-pad/issues/1378 to cover this issue.
