### ISSUE TITLE
Create issues for TODO comments

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2119]
As of today, there are 39 occurrences of [TODO in site-www source code](https://github.com/dart-lang/site-www/search?utf8=%E2%9C%93&q=TODO). Some of them are valid (e.g. the Todo app), but many are actual TODOs and should be tracked by GitHub issues.

We should (1) add issues for the actual TODOs and (2) either remove the corresponding TODO from the source code or put the issue number by the TODO comment.

Similar: https://github.com/flutter/website/issues/3270

**Comment by lenniezelk** [comment]
i'd like to work on this @kwalrath

**Comment by kwalrath** [comment]
@lenniezelk it's yours. Thank you!

**Comment by lenniezelk** [comment]
@kwalrath i found 36 valid TODOs. Do i make 36 issues?

**Comment by kwalrath** [comment]
> @kwalrath i found 36 valid TODOs. Do i make the 36 issues?

Good question. First I'd make sure the TODOs don't already have an associated issue. (If they do, we should update the source code to refer to that issue... so you could either do that or add a note to the issue that the TODO needs to be updated.)

Second, it's fine to combine related TODOs in a single issue if (1) they're likely/easy to be fixed in a single PR or (2) they have a common theme that's likely to require other files (that don't have TODOs) to be affected.

So probably you'll file >1 issue but < 36. Make sense?

**Comment by lenniezelk** [comment]
I have tried grouping the ones that seem related. Any more that can be grouped or what do you think needs to change?
 https://gist.github.com/lenniezelk/ba4526665f321cde5aa8aa634ef61724
@kwalrath

**Comment by kwalrath** [comment]
I haven't had time to look in depth at your groupings, but I aim to give you feedback today or tomorrow. Thanks very much for your work on this!

**Comment by kwalrath** [comment]
Finally looked at https://gist.github.com/lenniezelk/ba4526665f321cde5aa8aa634ef61724. Thanks so much for your work on this! Your groupings look good. Some specific comments:

* 5 (TODO: refactor into an AbstractLlamaGreetingFactory?) is a joke comment intended to be shown in the docs, so no issue is necessary.
* We might be able to combine some TODOs under an issue related to infrastructure tools: 4, 6, 7, 8, ... (maybe that's all?).
* 12 might be the same as #1744 (although it should have a new comment pointing to the TODO).
* Agreed that 20 seems to be covered by #2010.

Again, thanks!!

**Comment by srLitem** [comment]
Hello @kwalrath!
I was curious if there is anything else that needs to be done regarding this issue.

**Comment by kwalrath** [comment]
@srLitem thanks for asking! I suspect we do still need to do something, especially since we now have 46 occurrences of TODO in code (up from 39). Are you willing to do a review similar to the one @lenniezelk did?

**Comment by woinbo** [comment]
@kwalrath, as @srLitem didn't reply, may I work on this TODO issue.

**Comment by kwalrath** [comment]
Go ahead, @woinbo. I suspect @srLitem needed a response sooner than I was able to give it. :(

**Comment by woinbo** [comment]
> Go ahead, @woinbo. I suspect @srLitem needed a response sooner than I was able to give it. :(

Thank you @kwalrath, for assigning it to me.

**Comment by woinbo** [comment]
I have grouped the remaining TODOs in this file https://gist.github.com/woinbo/f71447550872339e51683f50bfc2d464 .
Please check it out! Anything else for me.
@kwalrath

**Comment by woinbo** [comment]
> I have grouped the remaining TODOs in this file https://gist.github.com/woinbo/f71447550872339e51683f50bfc2d464 .
> Please check it out! Anything else for me.
> @kwalrath

@kwalrath can you check this one too..

**Comment by kwalrath** [comment]
Your groupings look great, @woinbo. Could you please file the issues and then create one or more PRs to add the relevant issue URL/number next to each TODO in the source code? Thank you!

**Comment by woinbo** [comment]
Hello @kwalrath, changes are to be done in the grouping (gist) file or in the main site-www source code. Thank you!

**Comment by kwalrath** [comment]
The gist is just a planning doc. We need issues on the site-www tracker, and references to those issues in the site-www source code.

**Comment by woinbo** [comment]
ok, sure I will do it. Thank you @kwalrath, could you also review my PR #2841

**Comment by woinbo** [comment]
Hey @kwalrath, I did create issue #2852 for all the TODO' and list the files. can you please check and if anything needs to be changed do inform me.

**Comment by woinbo** [comment]
> Your groupings look great, @woinbo. Could you please file the issues and then create one or more PRs to add the relevant issue URL/number next to each TODO in the source code? Thank you!

PR updating TODO's with issues number next to each TODO

#2866
#2865
#2867

**Comment by srLitem** [comment]
@kwalrath I was not able to reply during the last few weeks...Thanks, @woinbo for taking over 🔥  
Let me know if there's something I can do now, I'm looking forward to contributing 😄

**Comment by masteradit** [comment]
Hey! I would like to contribute if this issue is still open.

**Comment by vendz** [comment]
@kwalrath as this issue is still open, is there anything I can do to contribute?

**Comment by kwalrath** [comment]
Sorry I haven't responded! I'm not sure what the status is of this.

Maybe someone could volunteer to search for TODO comments, compare the list to woinbo's list, and see (1) what's still to be done on the list and (2) if anything's cropped up since the list was made?

**Comment by vendz** [comment]
@kwalrath can I try this one?

**Comment by vendz** [comment]
@kwalrath I found out out a few TODOs what should I do next?

**Comment by kwalrath** [comment]
@vendz could you put your results in the comments here?

**Comment by vendz** [comment]
Following are the `TODOs` i found that isn't present @woinbo 's list

- TODO(miquelbeltran) language-tour.md should be updated, List<String> cannot be used with null-safety
- TODO(miquelbeltran) Maybe ! would be better here
- TODO: refactor into an AbstractLlamaGreetingFactory?
- TODO(miquelbeltran) language-tour.md should explain that non-required params can be null
- TODO(chalin): I believe that handleError's test argument should be declared

**Comment by kwalrath** [comment]
I think the Llama TODO is intentional, but the others are legit. Thanks, @vendz!

**Comment by vendz** [comment]
@kwalrath is there anything else I can do?

**Comment by kwalrath** [comment]
Could you please add the language tour TODOs in a comment to #2950? If any of the new TODOs aren't in the language tour, could you make sure there's a bug for them?

(I wish #2950 used a format like #2863... if you're up for making that happen, it'd be great.)

**Comment by vendz** [comment]
@kwalrath I have commented on the issue please do check: https://github.com/dart-lang/site-www/issues/2950#issuecomment-854067041

**Comment by kwalrath** [comment]
There's a part I forgot (it's been a while since I filed this!): Update the .md file so that the TODO refers to the bug.

The goal would be that every TODO in a .md file (except for the intentional Llama TODO) has `TODO (<link to issue>)`. Like this one from src/_guides/libraries/c-interop.md:

```
[TODO (https://github.com/dart-lang/site-www/issues/2219): Fix build instructions.]
```

**Comment by vendz** [comment]
@kwalrath so do I create new issues for all 5 `todos` and create a PR?

**Comment by kwalrath** [comment]
There can be multiple related TODOs in a single issue... So just make sure each TODO is covered by an issue, and create a PR to add the issue # to the .md file(s) at the site of each TODO. Thank you, @vendz!

**Comment by vendz** [comment]
@kwalrath pardon me as I am a bit new to this but none of the TODOs I listed above are from a `.md` file, all of them are from a `.dart` file

**Comment by kwalrath** [comment]
> @kwalrath pardon me as I am a bit new to this but none of the TODOs I listed above are from a `.md` file, all of them are from a `.dart` file

Oh interesting! I think the same thing applies. We want an issue referring to the TODOs, so we don't forget they exist, and we want a reference from the .dart file back to the issue.

**Comment by parlough** [comment]
@vendz Thanks for your work so far! As a suggestion, I also recommend linking to the TODO line on Github so it's easier to identify where to look for someone wanting to work on the issue. For example for this issue(https://github.com/dart-lang/site-www/issues/3294) you could add to the description a link to the line where the TODO is: https://github.com/dart-lang/site-www/blob/master/null_safety_examples/misc/test/language_tour/generics_test.dart#L26

**Comment by vendz** [comment]
@kwalrath I have opened a PR (#3299) so please review it

**Comment by vendz** [comment]
@parlough thank you for the feedback I will edit the issues right away

**Comment by TalMoshel1** [comment]
Hey,
if you still need help, I want to work on it.

**Comment by austinhutchen** [comment]
I would enjoy working ont his, if help is still needed!

**Comment by parlough** [comment]
Hey @austinhutchen, taking a look, most of the relevant TODOs had issues created by woinbo. Thanks for offering though. I'll close this issue to avoid any confusion.

You may want to look at some of the "Help Wanted" issues to see if any them match your interests: https://github.com/dart-lang/site-www/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
