### ISSUE TITLE
Information on https://www.dartlang.org/guides/language/effective-dart/design is wrong

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/site-www#212]
https://www.dartlang.org/guides/language/effective-dart/design#avoid-defining-a-class-that-contains-only-static-members

This block of code is marked 'good' but is not valid:

```
class Color {
  const red = '#f00';
  const green = '#0f0';
  const blue = '#00f';
  const black = '#000';
  const white = '#fff';
}
```

Attempting to create a class like this will result in errors "Only static fields can be declared as const"

**Comment by kwalrath** [comment]
It was valid a few years ago... Good catch! I think we just need to change each `const` to `static const`.

@munificent, OK for us to make that change?

**Comment by munificent** [comment]
Yup, just looks like a mistake to me.

**Comment by Sfshaza** [comment]
Fixed.
