### ISSUE TITLE
Homepage Try-Dart example code issues

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#2126]
Consider making code changes shown in red to avoid the named analyzer issues:

 > <img src="https://user-images.githubusercontent.com/4140793/69352338-c9254e80-0c4a-11ea-8b66-df2dd838f701.png" width=400>

><img src="https://user-images.githubusercontent.com/4140793/69352749-71d3ae00-0c4b-11ea-8aff-28d6ab5ca404.png" width=400>

Also, quite a few of the example files have `ignore: type_annotate_public_apis` which we might want to address.

Followup to https://github.com/dart-lang/site-www/pull/2124#discussion_r349008367. cc @mit-mit

**Comment by kwalrath** [comment]
@johnpryan what do you say?

**Comment by johnpryan** [comment]
Do we need the `ignore:` statements or can we fix the samples?

**Comment by chalin** [comment]
We can certainly fix the examples, if you feel that the fixes proposed above are reasonable.

To give you a bit of context: All of the site's example code is analyzed under the [pedantic](https://pub.dev/packages/pedantic) analyzer options. Elsewhere, @legalcodes and @kwalrath gave a thumbs up agreeing that:

> ... pretty much **all example code** should be **free of analyzer issues** when configured with the **pedantic** options. -- From the short thread starting at https://github.com/dart-lang/site-www/issues/2128#issuecomment-557663290.

If you agree too, then we should update the code, including removing the `ignore: type_annotate_public_apis` directives and adding the necessary types.

(Btw, in case you are wondering, `ignore` directives in the example code don't show up in the published code because I've configured the code-excerpter to strip them out.)

**Comment by johnpryan** [comment]
That makes sense. I left some more specific comments here: https://github.com/dart-lang/site-www/pull/2124#pullrequestreview-322455574

**Comment by johnpryan** [comment]
I think these issues are fixed by https://github.com/dart-lang/site-www/pull/2124 now.
