### ISSUE TITLE
Improve Try-Dart section of Dart homepage to adjust better between mobile, desktop

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#2127]
@mit-mit, correct me if I'm wrong, but the improvements that you'd like to see relative to the Try-Dart section are the following:

- Add spacing (and/or some other visual element(s)), to more clearly separate the Try-Dart section from the rest of the busy Homepage.
- Consider keeping the Try-Dart section even on mobile, so that there will always be a valid target for https://dart.dev/#try-dart. On mobile that section will direct users to dartpad.dev.

cc @kwalrath @galeyang @legalcodes

**Comment by galeyang** [comment]
> Add spacing (and/or some other visual element(s)), to more clearly separate the Try-Dart section from the rest of the busy Homepage.

Overall, I like this idea! However, for this particular [demo](https://mit-staging.firebaseapp.com/#try-dart), the big space is a bit surprising to me. When I scrolled down from the top to the end, I thought the big space is the end, and then embedded DartPad shows up. We might want to try different visual options.
 
> Consider keeping the Try-Dart section even on mobile, so that there will always be a valid target for https://dart.dev/#try-dart. On mobile that section will direct users to dartpad.dev.

As mentioned in other channel, I just wanted to note that dartpad.dev is not very mobile friendly now. We can think about if we want to do 2nd point after we optimize the mobile UI.

**Comment by mit-mit** [comment]
In the demo, I picked a fairly arbitrary amount of spacing just to demonstrate the concept of using whitespace to separate out DartPad. Fully agree that we need to spend some time determining the correct amount of spacing.

**Comment by chalin** [comment]
IMHO the current overall design and layout of the homepage is fine. Adding a little space before the Try Dart section won't really address the current issue on large displays, since the problem isn't that "Try Dart" is embedded on the homepage, it's that on large (tall) displays, visiting "/#try-dart" doesn't put the "Try Dart" section title at the top of the view.

In an email @galeyang mentioned moving the "Try Dart" section higher up in the homepage. That could fix this issue by putting more page content _below_ the "Try Dart" section, which in turn could make the homepage tall enough so that the "/#try-dart" target could be displayed at the very top of the view.

---

Since this is a "discussion" issue, and for completeness's sake, below are my views on why I think that a separate playground page might make sense, but I understand that this isn't the favoured solution.

It is my understanding that we want to cater specifically to (at least) these **three use cases**:

1. On **desktop**, a user lands on the **homepage**, scrolls through it and reaches the Try Dart section so she/he and can start interacting with the DartPad examples -- w/o having to visit another page.
2. On **desktop**, a user is **already browsing the docs**, clicks "Try Dart" in the main nav.
3. On **mobile**, a user selects "Try Dart" from the nav.

IMHO:
- For (1) [desktop, "first-time" user"] it makes sense to have the Try-Dart DartPad on the homepage.
- For (2) [desktop, "seasoned user"], I believe that a user would get the best experience by being directed to a page dedicated to trying out a Dart feature -- i.e., a playground w/o the distraction of everything else that is going on on the homepage, or just being directed to dartpad.dev.
- For (3) [mobile users]:
  - Not embedding a DartPad on the homepage makes sense to reduce the page load / first-paint time.
  - It would be more consistent to keep a "Try Dart" section for mobile too, w/o an embedded DartPad, and to provide a link to a local "Try Dart"/playground page, or to dartpad.dev.
  - Mobile users wishing to try Dart could be directed to a dedicated try-Dart page (rather than the DartPad), where we can have a bit more control over the mobile-friendliness of the experience. (If I'm not mistaken, a page with an embedded DartPad can be made a bit more mobile friendly than dartpad.dev is currently -- my quick tests seem to confirm that.)

My 2 cents. Thoughts?

**Comment by parlough** [comment]
I'm going to close this as the current setup has been working well without more comments for a while now.

The "Try Dart" section adapts to a height appropriate to your display size, while mobile is directed to the DartPad site which now has a dedicated mobile/narrow layout.

Please feel free to reopen or let me know if you think more changes are still needed here. Thanks!
