### ISSUE TITLE
'Creating streams in Dart' page issue

### ISSUE THREAD

**Issue by andesappal** [dart-lang/site-www#2129]
Page URL: https://dart.dev/articles/libraries/creating-streams
Page source: https://github.com/dart-lang/site-www/tree/master/src/_articles/libraries/creating-streams.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: search for the word "promise", which should be a "future".

**Comment by kwalrath** [comment]
Good to know you're paying attention! The only case of _promise_ I found in this doc isn't actually referring to the Future class (or to JS promises):

> Stream listeners must never be called until the code that added the listener has fully returned, and using a synchronous controller at the wrong time can break this promise and cause good code to fail. 

So I'm going to close this bug, although I'll be happy to update the text if @lrhn has a better idea.
