### ISSUE TITLE
Make web debugging page refer to new Dart DevTools

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/site-www#2130]
Can we correct the `Note` on this page:

https://dart.dev/web/debugging

to point the new Dart DevTools work instead?

I.e.,
> Note: A Dart fork of Chrome DevTools exists but isn’t ready yet for general use. For the latest status, see the devtools-frontend README.

Alternatively, we could delete it for now.  We have no further plans for that fork.

@kwalrath @grouma

**Comment by kwalrath** [comment]
Oops, yes I can correct that.

**Comment by grouma** [comment]
We can direct users to `package:webdev` which exposes the `--debug` flag. There is some basic documentation in https://github.com/dart-lang/webdev but we definitely can do a lot better.

**Comment by kwalrath** [comment]
How much should you use Dart DevTools vs. Chrome DevTools?

**Comment by grouma** [comment]
Long term we hope most folks are using Dart DevTools for debugging Dart logic, in conjunction with Chrome DevTools for general HTML / CSS debugging. If they are developing a Flutter Web app, we hope they mostly only use Dart DevTools.

**Comment by kwalrath** [comment]
I've created a PR to delete the note. I want to point to the Dart DevTools, but I need to understand more about how they're used (for both dart:html & Flutter web apps) before I do that. I'll leave this issue open to track that.

**Comment by kwalrath** [comment]
It looks like we need to do this sooner rather than later: https://bugs.chromium.org/p/chromium/issues/detail?id=1016755#c3
