### ISSUE TITLE
Description Errors (https://dart.dev/guides/language/effective-dart/design)

### ISSUE THREAD

**Issue by nolon5** [dart-lang/site-www#2132]
"DO annotate when Dart infers the wrong type." The example is not clear, the same code in the correct and erroneous examples.

https://dart.dev/guides/language/effective-dart/design

Screenshot: https://i.stack.imgur.com/WlpFh.pn

**Comment by kwalrath** [comment]
I'm going to reopen this since it's really easy to miss the type annotation on `highest`.
