### ISSUE TITLE
Fix await void issue in async await codelab

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#2135]
https://gist.github.com/legalcodes/25ade03f0632878a9169209e3cd7bef2

The `void createOrderMessage ()` should be `Future<void> createOrderMessage()`.

**Comment by chalin** [comment]
Yes, that was a point raised in #2128.

**Comment by chalin** [comment]
Specifically in this comment: https://github.com/dart-lang/site-www/issues/2128#issuecomment-557660677

**Comment by natebosch** [comment]
:+1: Will comment on that thread and close this as a duplicate.
