### ISSUE TITLE
What is the effective way to document generic return types?

### ISSUE THREAD

**Issue by gewoonwoutje** [dart-lang/site-www#2140]
I was reading Page URL: https://dart.dev/guides/language/effective-dart/documentation
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/documentation.md

I was looking how to effectively document the expected generic return types. As an example of what I would like to document:
```dart
abstract class UserRepository {
  /// @returns A [Left]<[Failure]> if an error occured, a [Right]<[Some]<[Person]>> when the Me person
  /// was loaded successfully or a [Right]<[None]> when no person was saved as Me.
  Future<Either<Failure, Option<Person>>> getMe();
}
```
Where `[Either]`, `[Left]`, `[Right]`, `[Option]`, `[Some]` and `[None]` are FP style types from the dartz package, and `[Failure]` is a custom abstract error type.

There are a number of ways how to do this, for instance:
`[Left<Failure>]` or `[Left]<[Failure]>`.

What would be recommended? And could some recommended examples be added to the effective dart page?

**Comment by kwalrath** [comment]
@munificent can you point to some good examples and/or give us some guidance?

**Comment by munificent** [comment]
I think guidance at this level is a little too specific for "Effective Dart", which is already quite long and intimidating. I would just write a sentence that is as clear as you can make it and contains links to the declarations that you think a reader will find the most useful.

**Comment by gewoonwoutje** [comment]
Fair enough. 
It would be nice though if VS code showed the `[Block type]` as a hyperlink in the inline documentation viewer; it currently does not: 
![image](https://user-images.githubusercontent.com/9407072/69683957-f17fd380-10b6-11ea-8dae-2b779e6a1691.png)

I think I'll stick with `[Outer]<[Inner]>` format, because I think it has a better chance of working correctly when the above is implemented.
