### ISSUE TITLE
Book that you are missing

### ISSUE THREAD

**Issue by caviroski** [dart-lang/site-www#2143]
In this list: https://dart.dev/resources/books

you are missing this book:
http://shop.oreilly.com/product/9781941222256.do

**Comment by kwalrath** [comment]
Thanks very much for letting us know about this book. (I wonder how we missed it!) I don't plan to add this book, since it's 5 years old and covers Dart 1, but if and when they update to Dart 2, I'd be very happy to add the new edition.

**Comment by caviroski** [comment]
The book is from November 2014, more than half of the books on the list are older than this book. But it is your decision :)
