### ISSUE TITLE
Gist link is broken

### ISSUE THREAD

**Issue by robin-carry** [dart-lang/site-www#2154]
On the congratulation page for the 20-mins Java-to-Dart tutorial, there is a gist link is broken. 

https://dartpad.dartlang.org/fae22cffa7b184b4d27cd96dd633a5af  - doesn't load. 

![image](https://user-images.githubusercontent.com/4965919/70265807-0829c880-1750-11ea-8899-8f2731f41c50.png)

**Comment by joshvocal** [comment]
The DartPad you provided seems to work currently, @robin-carry.

I also checked out the [Intro to Dart for Java Developers](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#6) code lab and that link works too.

**Comment by kwalrath** [comment]
Thanks for checking, @joshvocal. The DartPad is working for me, too, so I'm going to close this issue.

**Comment by robin-carry** [comment]
Sorry for bothering you guys. at that point of time, the link didn't open. Appreciate looking into this.

**Comment by kwalrath** [comment]
No worries, we appreciate all reports! Gists are usually pretty reliable, but sometimes there are issues with rate limits, so we're considering other solutions.
