### ISSUE TITLE
Documents for Strong Mode contradict to each other

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/site-www#216]
[Sound Dart: FAQ](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/sound-faq.md#is-it-a-sound-type-system "site-www/sound-faq.md at master · dart-lang/site-www") and [Sound Dart | Dart](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/sound-dart.md#what-constitutes-strong-mode "site-www/sound-dart.md at master · dart-lang/site-www")  contradict to each other.
[Sound Dart: FAQ](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/sound-faq.md#is-it-a-sound-type-system "site-www/sound-faq.md at master · dart-lang/site-www") says that strong mode is part ... of a sound type system,
while [Sound Dart | Dart](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/sound-dart.md#what-constitutes-strong-mode "site-www/sound-dart.md at master · dart-lang/site-www") says that dart’s strong mode consists of three pieces: Sound type system, ... .
Also, [Sound Dart | Dart](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/sound-dart.md#what-constitutes-strong-mode "site-www/sound-dart.md at master · dart-lang/site-www") is a self contradiction.
[Sound Dart | Dart](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/sound-dart.md#what-constitutes-strong-mode "site-www/sound-dart.md at master · dart-lang/site-www") says that dart’s strong mode implementation, **which enables soundness**, consists of three pieces: **Sound type system**, ...

IMHO, the term of "strong mode" should be equivalent to "sound type system", because "strong mode" introduces runtime checks in DDC (is it correct?), which consists of **compile time** checks, runtime checks, ... .

**Comment by Sfshaza** [comment]
@munificent, how would you characterize strong mode vs sound Dart?

My understanding is that strong mode is part of making Dart a sound language, though I do say at the beginning of the FAQ that these terms are sometimes used interchangeably:

https://www.dartlang.org/guides/language/sound-faq#what-is-strong-mode

Thanks for clarification!

**Comment by munificent** [comment]
> how would you characterize strong mode vs sound Dart?

I would say that "strong mode" is a sound static type system that uses a combination of static and runtime checks to ensure your code is type safe—that you can never see a value whose runtime type does not match its static type.

With strong mode enabled (in an implementation that has both the static and runtime checks), Dart is a sound language. Currently, dev_compiler is the only full implementation of strong mode. VM and dart2js support are on their way.

**Comment by munificent** [comment]
@leafpetersen in case he wants to chime in.

**Comment by leafpetersen** [comment]
What @munificent said.
