### ISSUE TITLE
Update to pedantic 1.9.0, latest analyzer

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2160]
And undo the quick fixes we made to fix the build in #2159

**Comment by kwalrath** [comment]
No longer blocked due to analyzer brokenness (see https://github.com/dart-lang/site-www/pull/2159#pullrequestreview-329142485).

**Comment by kwalrath** [comment]
Important but not urgent, compared to other stuff happening this week...

**Comment by kwalrath** [comment]
Looking at the output, it all seems to boil down to the following lints:

  lint • Don't access members with `this` unless avoiding shadowing. • ... • unnecessary_this
  lint • Don't check for null in custom == operators. • ... • avoid_null_checks_in_equality_operators
  lint • Omit type annotations for local variables. • ... • omit_local_variable_types
  lint • Prefer generic function type aliases. • ... • prefer_generic_function_type_aliases
  lint • Prefer single quotes where they won't require escape sequences. • ... • prefer_single_quotes
  lint • Prefer using `??=` over testing for null. • ... • prefer_conditional_assignment
  lint • Prefer using if null operators. • ... • prefer_if_null_operators
  lint • Private field could be final. • ... • prefer_final_fields
  lint • The function xxx should have a return type but doesn't. • ... • always_declare_return_types
  lint • The method xxx should have a return type but doesn't. • ... • always_declare_return_types
  lint • Use adjacent strings to concatenate string literals. • ... • prefer_adjacent_string_concatenation
  lint • Use collection literals when possible. • ... • prefer_collection_literals
  lint • Use generic function type syntax for parameters. • ... • use_function_type_syntax_for_parameters

**Comment by kwalrath** [comment]
I think we should mostly follow the pedantic lints. If they're too onerous in certain cases, then I'll switch to effective_dart lints or add allow comments.

**Comment by kwalrath** [comment]
Downgrading to p2. Still need to do this, but it isn't urgent.

**Comment by parlough** [comment]
Since we have migrated to `lints:recommended.yaml` for all new examples instead of pedantic, I'll consider this fixed by https://github.com/dart-lang/site-www/pull/3263
