### ISSUE TITLE
Remove outdated version notes for changes before 2.12

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2174]
This came up in the course of reviewing PR #2166.

```
$ fgrep -Rl version-note src
src/_includes/async-await-2.0.md
src/codelabs/async-await.md
src/_guides/libraries/library-tour.md
src/_guides/language/sound-problems.md
src/_guides/language/effective-dart/style.md
src/_guides/language/language-tour.md
```

**Comment by kwalrath** [comment]
Also, remove as many "1.x" references as possible.

**Comment by parlough** [comment]
Do you think we're at a point now where we can consider removing at least some of the Dart 2 version notes?

**Comment by kwalrath** [comment]
> Do you think we're at a point now where we can consider removing some of the initial Dart 2 version notes?

I suspect so. I'll bring this up tomorrow when I talk to @mit-mit.

**Comment by kwalrath** [comment]
We decided that since most people are using 2.12 or later (according to our analytics) and the tools tell you what to do to use new features if you're using a 2.7+ SDK, we'll only talk about versions for features introduced in 2.12 or later.

So let's remove the version notes for anything before 2.12.
