### ISSUE TITLE
Add section about enabling Effective Dart rules using package

### ISSUE THREAD

**Issue by tenhobi** [dart-lang/site-www#2182]
Hello 👋,

before I create a PR I would like to kindly ask if I am allowed to add a section about enabling a set of rules corresponding to the Effective Dart guide using [`package:effective_dart`](https://github.com/tenhobi/effective_dart) to the Customizing static analysis page, similarly to the pedantic section -> https://dart.dev/guides/language/analysis-options#default-google-rules-pedantic.

The package is already mentioned in https://github.com/dart-lang/linter and used on its site http://dart-lang.github.io/linter/lints. Also, packages like the Bloc library uses this package and I am awaiting this addition before I share it more, so people can benefit from it. 💙

Thanks!

**Comment by kwalrath** [comment]
Sorry I didn't see this before! Most of us were out the previous 2 weeks, but I plan to look at your PRs today.
