### ISSUE TITLE
Incorrect string shown in hint/error for async-await Exercise: Putting it all together Part 3

### ISSUE THREAD

**Issue by itsconquest** [dart-lang/site-www#2194]
**Bug description:**
The hint/error for _async-await Exercise: putting it all together Part 3_ asks the user if they added:
```Thanks! See you next time!```
However the exercise asks for and checks for the string:
```Thanks, see you next time```

**Solution:**
Correct the hint/error to show the correct string `Thanks, see you next time` to avoid confusion

**Comment by kwalrath** [comment]
Thanks for the report, @itsconquest!

**Comment by legalcodes** [comment]
Nice catch, will look into this.
