### ISSUE TITLE
Set up 404 tracking

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#22]
_From @kwalrath on September 25, 2014 16:35_

We could find out about broken links and missing redirects by getting 404 reports and tossing out the random stuff. @jakemac53 knows lots about this.

_Copied from original issue: dart-lang/www.dartlang.org#1060_

**Comment by Sfshaza** [comment]
_From @jakemac53 on September 25, 2014 17:3_

The main thing with this is it can be extremely noisy, so it is a must to have the ability to collect a few things about each 404 and apply (saved) filters over the results, specifically:

  * Referrer: This tells you where the original broken link lies. If it is not available you can usually just throw it out as its not very useful.
  * User Agent: Useful for filtering out bots/etc.

**Comment by kwalrath** [comment]
We're tracking this using weekly analytics reports for the 404 page. (PAGE TITLE: 404 Error, Primary Dimension: Page)
