### ISSUE TITLE
Update browser support info in FAQ for IE11 sunset

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2205]
Page URL: https://dart.dev/faq.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/faq.md

Update https://webdev.dartlang.org/faq#q-what-browsers-do-you-support-as-javascript-compilation-targets to reflect the IE 11 sunset info announced in https://groups.google.com/a/dartlang.org/forum/#!topic/announce/x7eDinVT6fM.

**Comment by Salmankhancodes** [comment]
> Page URL: https://dart.dev/faq.html
> Page source: https://github.com/dart-lang/site-www/tree/master/src/faq.md
> 
> Update https://webdev.dartlang.org/faq#q-what-browsers-do-you-support-as-javascript-compilation-targets to reflect the IE 11 sunset info announced in https://groups.google.com/a/dartlang.org/forum/#!topic/announce/x7eDinVT6fM.

What changes exactly we need to make?

**Comment by kwalrath** [comment]
It currently says:

> The production compiler (dart2js) supports Internet Explorer 11 and the last two major releases of the following browsers:

I think we just need to remove "Internet Explorer 11 and".

Correct, @kevmoo?

**Comment by Salmankhancodes** [comment]
> It currently says:
> 
> > The production compiler (dart2js) supports Internet Explorer 11 and the last two major releases of the following browsers:
> 
> I think we just need to remove "Internet Explorer 11 and".
> 
> Correct, @kevmoo?

Will you assigned me this task?

**Comment by kwalrath** [comment]
> Will you assigned me this task?

Assigned. Thank you!

**Comment by Salmankhancodes** [comment]
> > Will you assigned me this task?
> 
> Assigned. Thank you!

Please Review the changes.Thank you.

**Comment by kwalrath** [comment]
Fixed in #2244
