### ISSUE TITLE
Update pub versioning recommendations

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2207]
A discussion with @munificent, @mit-mit, @nex3, and @jonasfj concluded that we want to recommend that **applications use caret notation** (or version ranges) in pubspec.yaml. This makes it easy to use `pub upgrade` to get semver-compatible upgrades.

We need to update two pages:

* https://dart.dev/tools/pub/dependencies, which currently suggests that users might want to use **any** (or nothing at all, which is the same as **any**).
* https://dart.dev/guides/packages, which has an example without constraints.

We confirmed that we want to continue recommending the following:
* For applications:
  * DO: check in pubspec.lock
* For packages:
  * DO: use caret notation (or version ranges) in pubspec.yaml
  * AVOID: versioning pinning in pubspec.yaml (if possible)

We might also want to make other pub doc improvements at the same time (a quick search shows #47, #292, #1806, and more).

**Comment by jonasfj** [comment]
We could also consider:


 * [avoid recommending adding dependencies without caret](https://user-images.githubusercontent.com/149732/72152421-3c298680-33ab-11ea-93af-5ce45ee8984b.png)
 * [avoid example without dependency constraints](https://user-images.githubusercontent.com/149732/72152423-3d5ab380-33ab-11ea-932a-b56375e62cfd.png)

On flutter.dev

Page URL: https://flutter.dev/docs/development/packages-and-plugins/using-packages.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/using-packages.md

**Comment by aboutmydreams** [comment]
when I pub get, the lock file is update now (flutter 2.10), the lock file can’t let everyone working on the app uses the exact same versions. I think the doc should be update.

And I think, one of the principles of whether it is recommended to add it to gitignore is whether it is an auto-generated vs. overridden file

please reconsider, thanks!

**Comment by mit-mit** [comment]
Sorry @aboutmydreams not sure I fully understand. If you are seeing a case where `pubspec.lock` is being touched even when not needed, can you please file a new issue including some repro steps?

**Comment by jonasfj** [comment]
When you've upgrade/downgrade Flutter SDK, it's likely that `pubspec.lock` will need to be changed. This is an unfortunate side-effect of pinned dependencies in Flutter sdk-packages. Is that what you're talking about?

**Comment by aboutmydreams** [comment]
The version of the Flutter SDK has not changed. This is sent when I switch my application to view the branch. The two branch .lock files are the same, but when I execute the switch command, the dart plugin of vscode automatically helps me execute it. flutter pub get, resulting in an update of the .lock file
