### ISSUE TITLE
Fix CSS for external links, so punctuation can be outside the link

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2211]
For more info, see #2210.

We should also make sure this is documented somewhere obvious, so contributors know what to do.

**Comment by nvjvn** [comment]
I'm a beginner with open source. I would like to take up this issue but wanted to confirm if this is still open.
Thanks!!

**Comment by kwalrath** [comment]
It's definitely still open, and I'd love for you to take on this issue!

**Comment by nvjvn** [comment]
Thanks @kwalrath

**Comment by joshuamwolfe** [comment]
Have a few weeks till class restarts I’ll take a crack.

**Comment by lukelima** [comment]
hey @joshuamwolfe are you still doing it ? If not, can I be assigned to this issue ?

**Comment by joshuamwolfe** [comment]
I was not expecting to be accepted to springboard boot camp I don't have the time that I thought I did. Yes it can be reassigned.

**Comment by lukelima** [comment]
Thanks for reporting it, @joshuamwolfe  !

Hey @kwalrath ! Could you assign it to me ?

**Comment by kwalrath** [comment]
> Hey @kwalrath ! Could you assign it to me ?

Done. Thank you for volunteering!

**Comment by nathan-king** [comment]
Hey @kwalrath, I can get this done if still open :)

**Comment by f3ve** [comment]
If this is still open I'd like to help! :)

**Comment by kwalrath** [comment]
I'm starting to think this isn't going to happen, but I'd be very happy for you to try, @f3ve! The baton is yours.

**Comment by f3ve** [comment]
Thanks! I'll take a swing at it.

**Comment by f3ve** [comment]
How do you want something like this? 
![image](https://user-images.githubusercontent.com/56381169/87215607-febb9c80-c2ec-11ea-9c35-ee7de05df87e.png)
Would you prefer the icon stay inside or be on the outside?

**Comment by kaaaartikkkk** [comment]
Hey, can I know if I can get this done?

**Comment by joshuamwolfe** [comment]
Just give it a try, at worst, you learned something new!

**Comment by thomasmelak** [comment]
I am new to open source and I'd like to fix this issue but I don't know which file I should fix can you guys help?

**Comment by kwalrath** [comment]
What would be great would be for someone to provide the CSS. I can stick it into the necessary file (probably https://github.com/dart-lang/site-www/blob/master/src/_assets/css/main.scss), but I don't know what CSS to use.

You could test your CSS changes against one of the places that (erroneously) doesn't have the punctuation inside the external link. E.g. look at the "AngularDart" link at https://dart.dev/faq#q-what-web-frameworks-can-i-use-with-dart. It looks like this, with an unfortunate gap between the word and the punctuation:

![image](https://user-images.githubusercontent.com/2164483/89439588-46242580-d6ff-11ea-8170-77463c15a24d.png)

Our current (awkward) solution of including the punctuation in the link makes these links look like this one in https://dart.dev/guides/libraries/library-tour#darthtml:

![image](https://user-images.githubusercontent.com/2164483/89439828-98fddd00-d6ff-11ea-8023-cfcd8523112f.png)

I'd love for the punctuation to be outside of the link, but with the external link marker very close. This solution would need to work well not only with commas and periods, but with taller punctuation such as colons (`:`) and possibly (lower priority because these are rare) exclamation points (`!`) and question marks (`?`).

**Comment by laurameck** [comment]
👋 Is this still available? I'd like to work on this.

**Comment by laurameck** [comment]
Had some thoughts after debugging this in the browser a bit. If you change the styling of the icon to be absolute, you can make the punctuation appear right after the text content when it's outside the link. However, this also makes it so that any following content won't know about the icon, and you'd need a way to determine where to add extra spacing. 

For example, in your previous example, the content after the link is `. During [...]`. We want the period to ignore the icon, but we want to make sure that `During` is far enough apart that the icon and content don't overlap. Because most of the markup content following a link doesn't have a unique class, it would be pretty tricky to determine how to account for the icon's spacing considering we don't want the punctuation pushed over, but we _do_ want other types of text content to shift.

I looked into how Wikipedia handles this, and it appears that they actually use an SVG background image of the "icon" and then the padding on the link itself accounts for this spacing. Here's a code snippet of Wikipedia: 
```
    background-image: url(external link svg is here);
    background-position: center right;
    background-repeat: no-repeat;
    padding-right: 13px;
```
If the icon being used could be made available as an SVG, I could implement it similarly to Wikipedia.

**Comment by kwalrath** [comment]
Thanks for taking a look, @laurameck! Can you point me to a representative page in Wikipedia?

**Comment by laurameck** [comment]
Sure thing, if you scroll to the bottom of [this article](https://en.wikipedia.org/wiki/Gladys_West), you can see the external links under the References section

**Comment by kwalrath** [comment]
That's interesting. They still have the punctuation afterward (so there's still a gap), but because the symbol is aligned on the baseline, the gap isn't noticeable/objectionable.

I'm not sure whether we must/should use an SVG icon (assuming the font could be on the baseline), but it looks like we could _get_ it from the material icons site: maybe [open_in_new](https://material.io/resources/icons/?search=open_in_new&icon=open_in_new&style=baseline) ([SVG](https://fonts.gstatic.com/s/i/materialicons/open_in_new/v7/24px.svg?download=true)).

**Comment by laurameck** [comment]
Good catch--here's what it looks like with the vertical-align set to baseline

Period outside of link:
<img width="148" alt="" src="https://user-images.githubusercontent.com/9971478/94977295-612fcd80-04d5-11eb-82c6-6175489df725.png">
Period inside of link:
<img width="79" alt="" src="https://user-images.githubusercontent.com/9971478/94977323-799fe800-04d5-11eb-87ef-d7f8521c8c22.png">

Does that look acceptable?

**Comment by kwalrath** [comment]
If we set vertical-align to baseline, LGTM, and we can (over time) stop including the punctuation in the link.

Would you be able to create a PR for the vertical-align change, @laurameck?

**Comment by laurameck** [comment]
Sure thing! I'll get a PR up shortly.
