### ISSUE TITLE
Link icons next to effective dart headers should copy the link to the clipboard

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/site-www#2213]
Currently, these icons cause the header to jump to the top of screen which seems pretty pointless because I could much more intuitively achieve the same effect by just scrolling.  What I really want when clicking that icon is to copy the link address so that I can paste it somewhere else.

Note that this is how these icons work on other google sites: https://sites.google.com/site/southcountycats/volunteer-opportunities

**Comment by kwalrath** [comment]
Thanks for the input. You aren't the first to ask for this (see #920). Unfortunately, it isn't easy with our current infrastructure. I'm going to close this as a duplicate of #920, which you might want to thumbs-up or comment on.
