### ISSUE TITLE
fix dev build

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2214]
The [dev build has broken](https://travis-ci.org/dart-lang/site-www/jobs/637095921#L1329) in a weird way. I'm going to allow that failure for now, in hopes that the next dev release will fix the problem. If it doesn't, I'll take a look. (Or someone else is welcome to take a look... just let me know.)

From the [raw build log](https://api.travis-ci.org/v3/job/637095921/log.txt):

```
Analyzing analysis_options.yaml, bin, lib, test...
  error â€¢ Undefined class 'extension'. â€¢ lib/effective_dart/style_good.dart:108:1 â€¢ undefined_class
  error â€¢ Functions must have an explicit list of parameters. â€¢ lib/effective_dart/style_good.dart:108:11 â€¢ missing_function_parameters
  error â€¢ Undefined class 'on'. â€¢ lib/effective_dart/style_good.dart:108:26 â€¢ undefined_class
  error â€¢ A function body must be provided. â€¢ lib/effective_dart/style_good.dart:108:26 â€¢ missing_function_body
  error â€¢ Functions must have an explicit list of parameters. â€¢ lib/effective_dart/style_good.dart:108:29 â€¢ missing_function_parameters
  error â€¢ Undefined class 'extension'. â€¢ lib/effective_dart/style_good.dart:110:1 â€¢ undefined_class
  error â€¢ Functions must have an explicit list of parameters. â€¢ lib/effective_dart/style_good.dart:110:11 â€¢ missing_function_parameters
  error â€¢ Undefined class 'on'. â€¢ lib/effective_dart/style_good.dart:110:28 â€¢ undefined_class
  error â€¢ A function body must be provided. â€¢ lib/effective_dart/style_good.dart:110:28 â€¢ missing_function_body
  error â€¢ Functions must have an explicit list of parameters. â€¢ lib/effective_dart/style_good.dart:110:31 â€¢ missing_function_parameters
  lint â€¢ Name non-constant identifiers using lowerCamelCase. â€¢ lib/effective_dart/style_good.dart:108:11 â€¢ non_constant_identifier_names
  lint â€¢ Name non-constant identifiers using lowerCamelCase. â€¢ lib/effective_dart/style_good.dart:108:29 â€¢ non_constant_identifier_names
  lint â€¢ Name non-constant identifiers using lowerCamelCase. â€¢ lib/effective_dart/style_good.dart:110:11 â€¢ non_constant_identifier_names
  lint â€¢ Name non-constant identifiers using lowerCamelCase. â€¢ lib/effective_dart/style_good.dart:110:31 â€¢ non_constant_identifier_names
10 errors and 4 lints found.
```

/cc @bwilkerson in case this is an analyzer output issue

**Comment by bwilkerson** [comment]
If you're talking about the "â€¢" sequences, they are likely caused by `dartanalyzer` attempting to produce a small black circle between pieces of the output.

If you're talking about the diagnostics themselves, my guess is that the code is using extensions and being analyzed by a version of analyzer in which extensions are not yet supported.

**Comment by kwalrath** [comment]
> If you're talking about the "â€¢" sequences, they are likely caused by `dartanalyzer` attempting to produce a small black circle between pieces of the output.

That did look weird, but I assumed it was the circle so I didn't worry about it.

> If you're talking about the diagnostics themselves, my guess is that the code is using extensions and being analyzed by a version of analyzer in which extensions are not yet supported.

The weird thing is that the same code passes in the stable build. But maybe the messages are different. I'll try updating the messages for the dev build.

**Comment by kwalrath** [comment]
I just tried generating the messages, but there's no message difference. It seems like extensions aren't on in the new dev release (2.8.0-dev.2.0). Can that really be true?!

**Comment by bwilkerson** [comment]
Extension methods were supposed to be enabled by default on [9/30/19](https://dart-review.googlesource.com/c/sdk/+/119327). If you're using a later SDK then there might be a bug.
