### ISSUE TITLE
/get-dart instructions on switching to dev didn't work

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2216]
If someone out there is a Homebrew expert, I'd love your take on this.

I had a confusing experience today when trying to update my version of the SDK. I don't know if this is just a bad message in brew, something wrong with the dart formulas, and/or something we should fix in our docs.

https://dart.dev/get-dart says that, to upgrade to a dev channel release when a stable release is currently active, you should run this command:

```
 brew upgrade --force dart -- --devel
```

But I got this message:

```
Error: No available formula with the name "--devel" 
```

As a workaround, I ran the following:

```
brew unlink dart
brew install dart -- --devel
```

More commands below. It looks like I'd been using 2.7.0, but also had 2.8.0-dev.0.0 and 2.8.0-dev-2.0 installed. Strangely, the `brew upgrade dart` command mentioned 2.8.0-dev.0.0, but not -dev.2.0 or 2.7.0.

```
$ brew upgrade dart
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 4973f6707b to 50354852f4.
Updated 2 taps (homebrew/core and dart-lang/dart).
==> New Formulae
...
Warning: dart-lang/dart/dart 2.8.0-dev.0.0 already installed

$ dart --version
Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "macos_x64"

$ which dart
.../homebrew/bin/dart

$ brew info dart
dart-lang/dart/dart: stable 2.7.0, devel 2.8.0-dev.2.0
...

$ brew upgrade --force dart -- --devel
Error: No available formula with the name "--devel" 

$ brew unlink dart
Unlinking .../homebrew/Cellar/dart/2.7.0... 9 symlinks removed

$ brew install dart -- --devel

$ dart --version
Dart VM version: 2.8.0-dev.2.0 (Tue Jan 14 21:11:02 2020 +0100) on "macos_x64" 
```

**Comment by kwalrath** [comment]
I just ran into this again, and it's frustrating, so I'm increasing the priority.

@kevmoo, any tips?

**Comment by kevmoo** [comment]
What's w/ the `-- --devel`?

I never use the stand-alone `--`.

I DO have to uninstall dart stable before I can get dev to work...and vice versa. I've never been able to do the in-place switch.

**Comment by kwalrath** [comment]
A while ago we started having to add `--` everywhere. The relevant PR, #1844, mentions @filiph discovering this, so maybe he can tell us more.

**Comment by kwalrath** [comment]
We've removed the dev instructions from this page (favoring the SDK archive instead), so I'm closing this.
