### ISSUE TITLE
Code sample and fails with error

### ISSUE THREAD

**Issue by scorpioa** [dart-lang/site-www#2217]
[Link](https://dartpad.dartlang.org/8e2ad295a1b7c8254414afb43fc7d280) does not open code sample and fails with error. Source link is [Implement an interface](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#4)

**Comment by kwalrath** [comment]
That link is working for me. Could you try it again? If it still doesn't work, could you comment with a screenshot and any text that's in the console? Thanks!
