### ISSUE TITLE
Links in FFI document are broken

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/site-www#2218]
If you try to download files like hello.c in https://dart.dev/guides/libraries/c-interop#examples the links are broken.

**Comment by johnpryan** [comment]
the `c/` folder moved to `hello_library` so the URLs should be changed to:

https://github.com/dart-lang/samples/blob/master/ffi/hello_world/hello_library/hello.c
https://github.com/dart-lang/samples/blob/master/ffi/hello_world/hello_library/hello.h

**Comment by johnpryan** [comment]
@kwalrath I think I forgot that we were linking to the source code from the docs

**Comment by johnpryan** [comment]
The other thing that changed is that we are using CMake for these samples now. The steps are:

1. install cmake (using apt or homebrew)
2. run `cmake .`
3. run `make`

The only documentation we have for the CMake stuff is in the unit test right now: https://github.com/dart-lang/samples/blob/master/ffi/hello_world/test/hello_world_test.dart

**Comment by kwalrath** [comment]
Oh, ha, just filed https://github.com/dart-lang/site-www/issues/2219 about the build instructions.
