### ISSUE TITLE
Give example of using constructor variable initialization with named parameters

### ISSUE THREAD

**Issue by rkj** [dart-lang/site-www#2221]
Language tour have many example of classes and their initialization, but none of them includes named arguments that also initialize. Would be nice have something like:

```dart
class Point {
  num x, y;
  Point({@required this.x, @required this.y});
}
```

As when you have multiple arguments with the same type it's usually better to make them named to avoid mistakes / make the callsite easier to read. There is also an edge case here when you want to assign to a private variable, which requires to do that:

```dart
class Point {
  num _x, _y;
  Point({@required num x, @required num y}) : _x = x, _y = y;
}
```

I know from code reviews that newcomers struggle to figure it out initially.

**Comment by kwalrath** [comment]
Thanks, @rkj, this kind of feedback based on code reviews is very helpful!

**Comment by parlough** [comment]
As a reference, there currently is an example of this in the cheatsheet codelab: https://dart.dev/codelabs/dart-cheatsheet#using-this-in-a-constructor

Perhaps we could present this as an alternative in the [constructor section](https://dart.dev/guides/language/language-tour#constructors) for the `Point` constructor.

**Comment by natebosch** [comment]
My suggestions for the https://dart.dev/language/constructors#super-parameters section are a little less concrete.

I think the most confusing part is this sentence:

> Super-initializer parameters cannot be positional if the super-constructor invocation already has positional arguments, but they can always be named:

I think this is easier to express with a bad example (do we use those in this type of doc?)

```dart
  // If the super constructor invocation (`super(0)` below) has any
  // positional arguments it is an error to use a super parameter.
  Vector3d.xAxisError(super.x): z = 0, super(0); // BAD
```

Then I might adjust the prose above the following example:

> When the super constructor has named arguments they may be split between named super parameters (`super.y` below) and named arguments to the super constructor invocation (`super.named(x: 0)` below).

And the following example can be kept as is.
