### ISSUE TITLE
some section tabs load Docs-like pages, but aren't included in Docs navigation

### ISSUE THREAD

**Issue by ryanmcginnis** [dart-lang/site-www#2225]
Page URL: https://dart.dev/platforms.html, https://dart.dev/community, https://dart.dev/get-dart
Page source: https://github.com/dart-lang/site-www/tree/master/src/platforms.md, et al

i've been spending some time reading the Docs section of the Dart website. when i navigate to one of the other sections on Dart's website (the top bar tabs Platform, Community, and Get Dart), a page loads that visually appears to be a part of the Docs section. but the page isn't highlighted in the left-hand table of contents like a documentation page would be, and the section i chose is highlighted in the section tabs (indicating it is the "active" tab, while Docs remains not highlighted).

for example, selecting "Platforms" loads a documentation page called "Platforms" that isn't included in the doc set. it's disorienting that i navigated away from Docs, but landed on a page that looks just like documentation. if it is a documentation page, it's confusing that i would load specific pages from the top bar.

"Try Dart" does something like i would expect (load some new section of the site, or in this case jump to an anchor), except that the tab doesn't get highlighted (probably because a new page isn't loaded).

big nitpick, maybe! but i think it might be worth exploring a different way of presenting the other sections, or at least including them in the TOC.

**Comment by kwalrath** [comment]
The lack of being in the TOC is intentional (and mimics what Flutter does, I believe), but your point about the page looking too much like docs is a good one.

**Comment by atsansone** [comment]
@ryanmcginnis : This might be revised at a later date. This will be taken under advisement, but not handled as a specific change. 

Closing.
