### ISSUE TITLE
Language Tour - @override issue

### ISSUE THREAD

**Issue by ahan** [dart-lang/site-www#2228]
Page URL: https://dart.dev/guides/language/language-tour#extending-a-class

Question:
There are two similar examples with `class SmartTelevision`, one is without @override annotation, one is with.
Are there any differences between these two examples?

```
class SmartTelevision extends Television {
  void turnOn() {
    super.turnOn();
    _bootNetworkInterface();
    ...
  }
  // ···
```

```
class SmartTelevision extends Television {
  @override
  void turnOn() {...}
  // ···
}
```

**Comment by kwalrath** [comment]
Good catch! There's no real difference, other than indicating that the method was intentionally overridden, but I believe pedantic wants `@override` everywhere now (i.e. it's considered good practice at Google), so we should probably add it.

**Comment by micpap25** [comment]
The current version of the Language Tour uses the former to introduce `extends` and the latter to introduce `@override`. I don't think this needs to be condensed or changed, and perhaps this can be closed.

**Comment by MrBirb** [comment]
I agree with micpap on this

**Comment by kwalrath** [comment]
Thanks for the feedback, @micpap25 & @MrBirb. Closing!
