### ISSUE TITLE
The 'as' operator is NOT a shorthand for the 'is' operator

### ISSUE THREAD

**Issue by AmirSimantov** [dart-lang/site-www#2233]
[Contributors, please label with "LanguageTour"]

Hi guys, as this is not just a typo, I have not directly edited the language-tour.md file but, rather, opening an issue in order to discuss it.

GIVEN
Citing from /src/_guides/language/language-tour.md:
"Use the as operator to cast an object to a particular type. In general, you should use it as a shorthand for an is test on an object followed by an expression using that object."

CLAIM
I would like to claim that the 'as' operator is NOT a shorthand for the 'is' operator plus operating on the variable.

BACKING
If we are not sure that the variable in question is of type T, we cannot use 'as'. This is later clearly noted after the second example: "The code isn’t equivalent. If emp is null or not a Person, the first example (with is) does nothing; the second (with as) throws an exception". As the two snippets of code are not equivalent, so the first one is NOT a shorthand of the second one. Hence, 'as' is not a shorthand of 'is' plus operating on the object.

SUGGESTION

1. Revise the first sentence to something like: "Use the `as` operator to cast an object to a particular type T if - and only if - you are sure that the obejct in question is of type T."
2. Delete the sentence: "In general, you should use it as a shorthand for an is test on an object followed by an expression using that object". 
3. Put the example for 'as'.
4. Replace the sentence "You can make the code shorter using the as operator:" with something like: "If you are not sure that the obejct is of that type, you should check it before, using 'is' only then operate on it".
5. Show the 'is' sample.
6. Show the special note.

Any thought on this?

Thanks,
Amir

**Comment by kwalrath** [comment]
SGTM, at first glance. Anyone else have an opinion? Maybe @munificent?

**Comment by munificent** [comment]
I agree with @AmirSimantov.

**Comment by kwalrath** [comment]
@AmirSimantov would you like to create a PR?

**Comment by AmirSimantov** [comment]
I would like to @kwalrath, but I am not a native English speaker and this is quite a change. In this case, is creating a PR is the best way? Because there may (probably) be grammar mistakes there... If yes, I will gladly do it. Otherwise, I can prepare the text here and only when approved by natively English speakers I will create the PR.

**Comment by kwalrath** [comment]
I thought your wording was better than what many native English speakers would write. Also, I can copy edit the file in the actual PR.

But tweaking the language here works, too. The only place where I found the wording unclear was the last sentence: 

> If you are not sure that the object is of that type, you should check it before, using 'is' only then operate on it.

I'd change it to something like this:

> If you aren't sure that the object is of type _T_, then use <code>is <em>T</em></code> to check the object's type before using it.

Note that we tend to use contractions where it makes sense — especially for "not", which can easily get separated from the word before. https://developers.google.com/style/contractions has details.

**Comment by kwalrath** [comment]
Closed by #2253.
