### ISSUE TITLE
link to isolate (and other packages that expand on core libraries)

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2234]
Page URL: https://dart.dev/guides/libraries/useful-libraries
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/libraries/useful-libraries.md

It seems like we should do a couple of things:

1. Link to the core+ packages from https://dart.dev/guides/libraries (and maybe even move all info about these packages from https://dart.dev/guides/libraries/useful-libraries, to avoid duplication). Otherwise, it's too hard to find that there's a supported package that builds on a core library.
2. Add https://pub.dev/packages/isolate to the list of core+ packages.

@lrhn are there any other packages we should link to that build on core libraries, besides that ones listed in https://dart.dev/guides/libraries/useful-libraries#packages-that-correspond-to-sdk-libraries?

Related: https://github.com/dart-lang/sdk/issues/40238#issuecomment-576425766

**Comment by lrhn** [comment]
We have `package:async`, `package:collection`, `package:convert`, `package:isolate`, `package:typed_data` that I am considering myself in charge of (whether other people agree with that is open for debate). I don't think we have a `package:math` and definitely no `package:core`.

So, do add `isolate` and `typed_data` to the list.

I know there is a `package:js` and `package:html`, but I don't know anything else about them. It seems `package:js` is abandoned (last udated June 2018). I had never heard of `package:io` before.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/d3586bf1490e75c799e2ce2e790a766bbec28978 and https://github.com/dart-lang/site-www/commit/f9f99849aa8db71e2ce180332e9ced88d02eb10d. `package:isolate` is not included as it was discontinued.
