### ISSUE TITLE
'Iterable collections' page issue

### ISSUE THREAD

**Issue by jaredbaszler** [dart-lang/site-www#2240]
Page URL: https://dart.dev/codelabs/iterables.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/iterables.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

The bottom exercise lists that a method isValidEmailAddress() is provided but it it is not:

```
bool isValidEmailAddress() {  
return RegExp(r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+").hasMatch(this.address);
}
```

**Comment by kwalrath** [comment]
Actually, that method _is_ provided for you — it's just not visible in the UI. But if you call it, it does run and (in a very simple way) work.

**Comment by kwalrath** [comment]
Implementation is in test.dart in https://gist.github.com/0be68487b124b4e55927c3e026094547
