### ISSUE TITLE
Update dart.dev/web

### ISSUE THREAD

**Issue by sfshaza2** [dart-lang/site-www#2246]
Some feedback I've received in email:

I noticed that [https://dart.dev/web](https://dart.dev/web) doesn't describe the current state of Dart on the Web any more. Specifically, there's no mention of Fluter for Web, and there's nothing about the [level of support](https://github.com/dart-lang/angular/issues/1866#issuecomment-571851626) users should expect from AngularDart. Anyone here maintains the website or cares, perhaps it is time for an update.

Perhaps it could help address questions such as [this](https://groups.google.com/a/dartlang.org/g/web/c/iKTx3cbLZ9o).

AND:

Agree that it would be good to include a link to Flutter for Web now that it's in beta.

**Comment by kwalrath** [comment]
@kevmoo & @mit-mit we should talk.

**Comment by kwalrath** [comment]
We need to iron out a couple of small details, and then I'll create a PR.
