### ISSUE TITLE
Improve extension method examples' pubspec file

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2251]
File: https://github.com/dart-lang/site-www/blob/master/examples/extension_methods/pubspec.yaml

* Drop dependency_overrides
* Fix name
* Delete version?

Basically, make it as much like the other example pubspecs as possible.

I think we had the dependency override for analyzer due to https://github.com/dart-lang/sdk/issues/39702, but we removed it from other pubspecs (#2159). This one might have been in flight when all that happened.

**Comment by MrBirb** [comment]
Looks like the file was deleted?

**Comment by kwalrath** [comment]
> Looks like the file was deleted?

Looks like. Thanks, @MrBirb!
