### ISSUE TITLE
'Mobile app development' page issue: other ways of creating mobile apps?

### ISSUE THREAD

**Issue by rudolfolah** [dart-lang/site-www#2252]
Page URL: https://dart.dev/mobile.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/mobile.md

Description of issue: If there are other ways of creating mobile apps without using Flutter SDK, it would be helpful if they were listed.

**Comment by kwalrath** [comment]
I don't know of any other Dart ways, offhand. Anyone?
