### ISSUE TITLE
'Troubleshooting pub' page issue

### ISSUE THREAD

**Issue by rahul-bavaliya** [dart-lang/site-www#2254]
Page URL: https://dart.dev/tools/pub/troubleshoot
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/troubleshoot.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Using below command I set proxy and provide credential for proxy. But unable to run flutter doctor from it.
**set https_proxy=username:password@hostname:port**

Here I provide the console log for further information.
Console log : 
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest :
Access Denied (authentication_failed)
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
At D:\RAHUL_1647164\flutter_dev\flutter_windows_v1.12.13+hotfix.7-stable\flutter\bin\internal\update_dart_sdk.ps1:68 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Error: Unable to update Dart SDK. Retrying...

**Comment by kwalrath** [comment]
@jonasfj can you figure out what's wrong here? I'm not sure whether this is a pub issue, a flutter issue, or a misunderstanding, but I'd like to update the troubleshooting page if that might help.

**Comment by jonasfj** [comment]
@rahul-bavaliya, I think this is a flutter issue, probably the `flutter doctor` command runs a powershell script that doesn't handle the proxy config.. Maybe configuring system proxy will help, I don't know windows well enough.. Or maybe you need to quote the environment variable when you set it..

I suggest filing a bug on https://github.com/flutter/flutter/issues/

quick note: for future reference please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) for pasting terminal output :)

**Comment by kwalrath** [comment]
@rahul-bavaliya could you refer to this issue when you open the Flutter issue? Thank you!

(Oh, and I've added the code fences. :) )
