### ISSUE TITLE
'DartPad' page issue

### ISSUE THREAD

**Issue by bertbeck** [dart-lang/site-www#2259]
Page URL: https://dart.dev/tools/dartpad/
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/dartpad/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Text is misleading.**

**What does this mean?**

"If you want to use dart:io, use the Dart SDK instead. If you want to use a package, get the SDK for a platform that the package supports."

It seems to mean: "DartPad does not work with dart:io or other packages that are not defined in the flutter web sdk." 

Saying "If you want to use a package, get the SDK for a platform that the package supports." is confusing. If I do this - will my package work in DartPad? I want to xml2json but I get this error:

Error compiling to JavaScript:
Unsupported input: package:xml2json/xml2json.dart

I assume there is no way to use this package. Am I correct?

**Is there any way to add user packages to DartPad?**

**Comment by kwalrath** [comment]
No, there's no way to add user packages to dartpad.dev. We should be clearer.

It is open source, so you _could_ create your own version of DartPad and serve it up... but that's not something we expect people to do.

**Comment by bertbeck** [comment]
What is it that prevents a user to add packages to darted.dev?

Is there any guide to creating. your own version of dartpad and including
user packages?

I assume that any Flutter Web compatible packages should be able to be
used. The xml2json packages seems like it should be compatible.

**Comment by kwalrath** [comment]
> What is it that prevents a user to add packages to darted.dev? Is there any guide to creating. your own version of dartpad and including user packages? I assume that any Flutter Web compatible packages should be able to be used. The xml2json packages seems like it should be compatible.

https://github.com/dart-lang/dart-pad/issues/901 is the issue for adding package support to dartpad.dev. It has some good info, with links to relevant issues.

I think that implementing your own DartPad server is possible but might not be easy or commonly done. Still, it is open source, so you're free to try: https://github.com/dart-lang/dart-services.
