### ISSUE TITLE
</tr> </tr> in paragraph before table

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/site-www#226]
https://www.dartlang.org/articles/language/emulating-functions#interactions-with-mirrors-and-nosuchmethod

An undesired line of text `</tr> </tr>` appears between a paragraph and table:

![screenshot from 2017-01-31 12 04 47](https://cloud.githubusercontent.com/assets/1916163/22482363/80ef26aa-e7ad-11e6-8158-6e1fdc86d2c3.png)

**Comment by kwalrath** [comment]
Whoopsie, I'll fix this.
