### ISSUE TITLE
'A tour of the Dart language' page issue

### ISSUE THREAD

**Issue by Afsar-Pasha** [dart-lang/site-www#2262]
Page URL: https://dart.dev/guides/language/language-tour#final-and-const
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Description of issue:

> As of Dart 2.5, you can define constants that use type checks and casts (is and as), collection if and collection for, and spread operators (... and ...?):

Looks like `collection for` can't be used in constants.

**Comment by kwalrath** [comment]
You're right. I just checked https://github.com/dart-lang/language/blob/master/accepted/2.3/control-flow-collections/feature-specification.md, which says:

> In order to fit within the restrictions on constants, the set of things you could conceivably do with for is so limited that we felt the best option was to omit it entirely.
