### ISSUE TITLE
Remove extra space at top of cmd-line example

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2268]
Followup to #2266; see https://github.com/dart-lang/site-www/pull/2266#pullrequestreview-355494669 for details.

**Comment by Nishikoh** [comment]
hi , @kwalrath .
If I will work on this issue, should I fix like next images?
  
**current space**
![image](https://user-images.githubusercontent.com/55723667/77228082-25cc5200-6bc8-11ea-9c80-bf1196629ccd.png)

**fix space**
![image](https://user-images.githubusercontent.com/55723667/77228293-a8094600-6bc9-11ea-8fa1-c7eced31d0cc.png)

**Comment by kwalrath** [comment]
Actually, no. This bug is about a single sample, visible at https://dart.dev/tutorials/server/cmdline#overview-of-the-dcat-app-code. It seems to have an extra blank line at the top (above `import 'dart:convert';`), and I don't know why.

**Comment by Nishikoh** [comment]
@kwalrath 
I understand.
I'll try to fix this issue.

**Comment by micpap25** [comment]
Looks like this issue was fixed with this merged, we can close this.

**Comment by kwalrath** [comment]
True. Thanks, @micpap25!
