### ISSUE TITLE
Language Tour doesn't mention covariant

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#227]
_From @sethladd on January 31, 2017 20:20_

`covariant` is a new language feature coming for Dart. I didn't find an open issue to add it to the Language Tour.

An example, with a useful explanation, is here: https://github.com/dart-lang/sdk/commit/c3f1212a9c5b1105a604b575c9999d7a29ab1d3d#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR53

_Copied from original issue: dart-lang/sdk#28583_

**Comment by kwalrath** [comment]
_From @sethladd on January 31, 2017 20:21_

cc @kwalrath

**Comment by kwalrath** [comment]
Also see https://github.com/dart-lang/sdk/issues/27486

**Comment by sethladd** [comment]
This was a very useful bit of info from @leafpetersen 

me: "Related: why can't we allow this?"

```
class Cat extends Predator {
  void chaseAndEat(covariant Mouse m) => ...
}
```

That is: put the marker at the place where I'm specializing.

Leaf: This is allowed.  Once you mark a parameter in a method as "covariant" then that parameter is treated as covariant in that class, and in all overrides.  You are free to put it in the superclass (which tends to fit the pattern that we saw in Flutter where there is a single superclass which is intended to be covariantly overridden in many places), in which case the subclasses will "inherit" the covariant modifier.  But you are also free to add it at any point in the subclass hierarchy, in the case that a superclass did not anticipate the need for a covariant override.  Note though that there are static restrictions on valid covariant overrides, e.g. you can't covariantly override from unrelated types like "int" to "String".

**Comment by sethladd** [comment]
For more description of this feature, see thread titled "why covariant?" in our internal dart users mailing list.

**Comment by kwalrath** [comment]
There's also the public post, which has many more details than I put in the docs: http://news.dartlang.org/2017/02/dart-122-faster-tools-assert-messages.html

The language tour has been. As you can see from the discussion in #234, I initially discussed `covariant` at much greater depth, but we realized that we don't really want to encourage it. It's available, but not an idiom we recommend.
