### ISSUE TITLE
'Effective Dart: Style' page issue

### ISSUE THREAD

**Issue by bagintz** [dart-lang/site-www#2271]
Page URL: https://dart.dev/guides/language/effective-dart/style
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/style.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

The wording seems to indicate that enums should be both UpperCamelCase and lowerCamelCase in the sections `DO name types using UpperCamelCase.` and `PREFER using lowerCamelCase for constant names.` respectively

**Comment by kwalrath** [comment]
I interpret it as enum _types_ should be UpperCamelCase, and enum _values_ should be lowerCamelCase. Do you think we need a note/example to clarify this, and if so, where?

**Comment by bagintz** [comment]
that makes sense, and the second one `PREFER using lowerCamelCase for constant names` does say `enum values`.  Maybe adding `types` to the first one to give the distinction????
