### ISSUE TITLE
Broken link (404 not found) in tutorial for linked Dartpad code

### ISSUE THREAD

**Issue by SkepticalBit** [dart-lang/site-www#2280]
[Found here](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#5), in the "Intro to Dart for Java Developers"

Last link from this paragraph at the top of the page:

> Dart supports all of these features. In Dart, even functions are objects and have a type, Function. This means that functions can be assigned to variables or passed as arguments to other functions. You can also call an instance of a Dart class as if it were a function, as in [this example](https://dartpad.dartlang.org/405379bacf30335f3aed).

The link returns a 404: Not found.

**Comment by kwalrath** [comment]
Strangely, the gist behind this DartPad exists: https://gist.github.com/Sfshaza/405379bacf30335f3aed. I'll look into this.

Thanks for the heads up, @SkepticalBit!

**Comment by kwalrath** [comment]
@johnpryan do you know why the links http://dartpad.dartlang.org/405379bacf30335f3aed & http://dartpad.dev/405379bacf30335f3aed don't work? The first one used to, and the link http://gist.github.com/405379bacf30335f3aed does work. Is it because DartPad has gotten pickier about requiring the file to be named main.dart?

**Comment by johnpryan** [comment]
I think this is an issue with the router DartPad uses. If you don't want to fork the gists, you can change the URL to [`https://dartpad.dev/?id=405379bacf30335f3aed`](https://dartpad.dev/?id=405379bacf30335f3aed).

**Comment by kwalrath** [comment]
I'd rather DartPad could handle the route, since I suspect this affects more than just one link. Is that a possibility?

**Comment by johnpryan** [comment]
I think this is something we can fix in DartPad. Created https://github.com/dart-lang/dart-pad/issues/1489 to track

**Comment by RedBrogdon** [comment]
This is an easy fix. It was broken when we migrated to python3.

https://github.com/dart-lang/dart-pad/pull/1490

**Comment by kwalrath** [comment]
Yay, thank you! Could you tell us when you expect the fix to go out?

**Comment by RedBrogdon** [comment]
https://github.com/dart-lang/dart-pad/pull/1492

**Comment by johnpryan** [comment]
@kwalrath this is deployed now
