### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by roelvandun** [dart-lang/site-www#2288]
On https://codelabs.developers.google.com/codelabs/from-java-to-dart/#5 the link at the end of the sentence "You can also call an instance of a Dart class as if it were a function, as in this example." is a link to DartPad which gives a 404: https://dartpad.dartlang.org/405379bacf30335f3aed

**Comment by kwalrath** [comment]
Closing in favor of #2280. But thank you very much for making sure we knew about this!
