### ISSUE TITLE
Add and auto-include cheatsheet code samples

### ISSUE THREAD

**Issue by jddeep** [dart-lang/site-www#2295]
We need to add the cheatsheet code samples in the repo so that we can link the code-excerpts in the source file.

Context: #1803 

cc: @kwalrath

**Comment by kwalrath** [comment]
#2296 fixes the issue of having tests for the code, but now we need to auto-include the code in the cheatsheet codelab.

**Comment by jddeep** [comment]
@kwalrath I will make a PR for including the code-excerpts in the cheatsheet src `.md` file. should we close this and direct that PR to #1803 ? Let me know while I make the PR :)

**Comment by kwalrath** [comment]
What you did (saying that your new PR fixes this issue) is the right thing. I'll take a look at your PR today. Thank you!

**Comment by kwalrath** [comment]
I think we still have some code that isn't analyzed, so I'm going to reopen this until we ascertain that there's no more left to do.
