### ISSUE TITLE
Add tutorial on i18n/l10n

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#23]
_From @nicolasgarnier on August 26, 2014 15:11_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on August 05, 2013 20:20:03_

We should help developers build apps that are easy to translate/localize. A good start would be documenting current i18n/l10n best practices.

I know of two libraries, intlx & intl. It looks like intlx depends on intl, adding new formatting capabilities.

Info about intlx:
- pub home: https://pub.dartlang.org/packages/intlx \* demo: http://seaneagan.me/intlx/ \* API docs: http://seaneagan.me/intlx/docs/intlx.html \* repo: https://github.com/seaneagan/intlx Info about intl:
- pub home: https://pub.dartlang.org/packages/intl \* API docs: http://api.dartlang.org/intl.html \* intl in the Dart repo: https://code.google.com/p/dart/source/browse/trunk/dart/pkg/intl/

_Original issue: http://code.google.com/p/dart/issues/detail?id=12243_

_Copied from original issue: dart-lang/www.dartlang.org#728_

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:11_

_From [seaneagan1](https://code.google.com/u/seaneagan1/) on August 06, 2013 13:38:55_

Glad to see this!

I've started the process of merging intlx into intl: https://chromiumcodereview.appspot.com/18793002/ but I expect this to take a good bit of time.

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:11_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on June 04, 2014 14:58:12_

**Labels:** -Area-Documentation Area-Site

**Comment by Sfshaza** [comment]
_From @sethladd on September 3, 2014 23:40_

This sounds like a great tutorial.

**Comment by Sfshaza** [comment]
_From @timfayz on March 28, 2015 7:8_

What's new here? It has been over 6 months. I try to find exhaustive resource using i18n/l10n features with Dart.

**Comment by Sfshaza** [comment]
_From @sethladd on March 30, 2015 23:55_

I don't think anyone is working on this tutorial. We suggest emailing misc@dartlang.org with any questions, as perhaps people on that general list have some experience with the intl package.

**Comment by kwalrath** [comment]
Still something we should consider covering, but you can find some good info here: https://flutter.io/docs/development/accessibility-and-localization/internationalization.

**Comment by atsansone** [comment]
This issue might have been related to issues with darthtml, which Flutter supercedes. Closing.

**Comment by parlough** [comment]
This is still relevant for us as non-Flutter apps may still want internationalization and localization functionality.

**Comment by atsansone** [comment]
@parlough : I talked this through with @RedBrogdon . Closing.
