### ISSUE TITLE
Dart SDK as Debian package in the .deb package format link is broken

### ISSUE THREAD

**Issue by Dmitry-Borodin** [dart-lang/site-www#2309]
https://dart.dev/get-dart#install-a-debian-package
Alternatively, download Dart SDK as Debian package in the .deb package format.

    Stable channel -> leads to top of the page, so there is no way I can download stable dart SDK as .deb file
For develop channel link works

**Comment by kwalrath** [comment]
@Dmitry-Borodin could you try again? When I click the **Stable channel** link, it starts downloading a file.

**Comment by Dmitry-Borodin** [comment]
@kwalrath Yes, now it point to storage.googleapis.com, not to parent page. Looks like it's fixed.
Thank you.
