### ISSUE TITLE
Initial null safety docs for tech preview

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#2312]
As of https://github.com/dart-lang/pub/pull/2465, pub will link to https://dart.dev/null-safety/migration-guide, so we need to provide a file or redirect for that URL.

**Comment by kwalrath** [comment]
https://github.com/dart-lang/pub/pull/2465/files#diff-7192e860ddb78fc60e6bb87a113e4535 proposes a link to a migration guide, perhaps at /null-safety/migration-guide.

**Comment by kwalrath** [comment]
Working on a PR now for a placeholder and redirect.

**Comment by franklinyow** [comment]
Can this be closed?

**Comment by kwalrath** [comment]
I think so. @mit-mit?

**Comment by mit-mit** [comment]
Yes, we are no longer blocked, closing
