### ISSUE TITLE
Make dart.dev's default font size larger.

### ISSUE THREAD

**Issue by legalcodes** [dart-lang/site-www#2319]
I think it'd be worth testing with a few larger font sizes to see what the majority of users prefer, but I'd also happily settle for moving from 14px to 16px so that we are at least consistent with flutter.dev.

**Comment by sfshaza2** [comment]
+100

**Comment by kwalrath** [comment]
We're looking into making dart.dev fonts similar to pub.dev fonts, which are a bit bigger and heavier.

**Comment by parlough** [comment]
I'm going to mark this as fixed by https://github.com/dart-lang/site-www/commit/63393923a1854289bb37e4919a37ec294d2ae887 which increased the font-size to 16px.
