### ISSUE TITLE
--disable-service-origin-check flag not documented

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/site-www#2321]
Hi, 

I was getting some forbidden errors with observatory and @simolus3 commented about this flag ```--disable-service-origin-check``` in Gitter and it helped me to get it to work.

I wonder why is it not documented here: https://dart.dev/tools/dart-vm and also not here: https://dart-lang.github.io/observatory/get-started.html ?

**Comment by kwalrath** [comment]
@a-siva should we be documenting the `--disable-service-origin-check` flag, either on the websites or in a troubleshooting page somewhere?

/cc @sfshaza2

**Comment by sfshaza2** [comment]
Yeah, keep me posted. Though, @jodinathan, we don't generally support the Observatory docs on the wiki.

**Comment by a-siva** [comment]
@kwalrath the option `--disable-service-origin-check ` is an internal option we use for testing purposes and is not intended for use otherwise, I would prefer we do not document it as it bypasses the origin check.
@jodinathan what kind of errors are you running into when you do not use the flag ?

**Comment by simolus3** [comment]
In Gitter, it came up when trying to run Dart in a container and connecting to the vm service protocol from the host. The VM will respond with a 403 error in that case.
I thought this use-case might be common enough to deserve documentation. Since it appears to be a security risk in general, maybe it's more appropriate to add this to the Docker readme?

**Comment by jodinathan** [comment]
@a-siva as @simolus3 commented, I was trying to view the Observatory from a dockered dart vm application and I was able to open the observatory page, but the requests in the chrome network panel were throwing a 403.
Once I added the mentioned flag, the requests were accepted

**Comment by kwalrath** [comment]
I'm going to close this, since it appears we shouldn't be documenting this flag on dart.dev.
