### ISSUE TITLE
'Publishing packages' page issue

### ISSUE THREAD

**Issue by codegrue** [dart-lang/site-www#2322]
Page URL: https://dart.dev/tools/pub/publishing.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/publishing.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

`pub publish --dry-run` doesn't seem to report issues that would lower a packages score: old dependencies, having warning, etc. Is there a way to perform that analysis before publishing?

**Comment by kwalrath** [comment]
@jonasfj any advice? 2.8's `pub outdated` should help find old dependencies, and maybe you could use https://pub.dev/packages/pana directly, but is there something more we can do (either in this page or in `pub publish`)?

**Comment by codegrue** [comment]
It would be nice in this publish instructions page to list all the automated analyses that are executed after upload, so that it can be performed prior to this. What I end up doing is publishing a version e.g. 1.8.0, seeing what issues it reports, then have to immediately publish a 1.8.1 version to address those. Would like to avoid that double publish.

**Comment by jonasfj** [comment]
You can run `pana` locally, but I don't think we should document it at this point.

The `pana` CLI is still very unpolished, it's not a user-friendly product at this point.

We are aware of this short coming, most of the missing analysis can be remedied by using `package:pedantic`.

We could update the docs to let users know that `pub.dev` runs additional analysis (to minimize the surprise). But the analysis we currently run is constantly changing -- and we have pending plans to refactor current analysis. IMO, this is not a documentation shortage, but instead a failure of ours to provide decent tooling for running the analysis performed on `pub.dev`.

**Comment by jonasfj** [comment]
Just to be clear, I fully acknowledge that the current situation is not ideal -- and that this is the underlying problem we should solve. Once we have a solution, we should document it.
