### ISSUE TITLE
Null safety intro code lab

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#2323]
Tracks an initial code lab for null safety tech preview to cover main topics (core feature, opt-ing in, inference, etc.). Doesn't need to cover migration, that can come later.

**Comment by mit-mit** [comment]
Note that https://github.com/dart-lang/site-www/issues/2324 tracks a more interactive learning experience. It may be work discussing if that is sufficient, and we don't need the present codelab if we have that.

**Comment by mit-mit** [comment]
Punting to beta 2

**Comment by parlough** [comment]
With the introduction of the [Null safety codelab](https://dart.dev/codelabs/null-safety) in https://github.com/dart-lang/site-www/pull/2983 which covers these main topics, I will close this issue as fixed. 

Further improvements to the codelab are being tracked in https://github.com/dart-lang/site-www/issues/3093.
