### ISSUE TITLE
Null safety code challenge for tech preview

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#2324]
Tracks a request for am online code challenge for null safety for tech preview. This is expected to be similar to https://dart.dev/codelabs/dart-cheatsheet, just with a bunch of coding challenges specific to null safety.

This is a complement to the general docs (https://github.com/dart-lang/site-www/issues/2312), and the more structured learning codelab (https://github.com/dart-lang/site-www/issues/2323).

**Comment by kwalrath** [comment]
Will the koans being developed by @RedBrogdon be sufficient to address this issue?

**Comment by mit-mit** [comment]
Yup, that's exactly what this was meant to track

**Comment by franklinyow** [comment]
Ready to close?

**Comment by kwalrath** [comment]
> Ready to close?

Yes, this is fixed by the **Learn with Snippets!** code samples in https://nullsafety.dartpad.dev.
