### ISSUE TITLE
Assert

### ISSUE THREAD

**Issue by sahniajay** [dart-lang/site-www#2325]
Page URL: https://dart.dev/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by kwalrath** [comment]
@sahniajay could you describe the issue? Thanks!

**Comment by kwalrath** [comment]
Closing due to lack of info.
