### ISSUE TITLE
Update docs & SDK archive page to reflect the beta channel

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2326]
Once Dart has a beta channel, we'll need to update places that talk about stable & dev to also talk about beta. We'll also need to update the code in https://dart.dev/tools/sdk/archive.

For details on the beta channel, see https://github.com/dart-lang/sdk/issues/40687.

/cc @johnpryan

**Comment by athomas** [comment]
Thanks for creating this issue!

Note that for chocolatey and homebrew, the beta channel will be distributed as separate packages.

Homebrew:
https://github.com/dart-lang/sdk/issues/40990#issuecomment-605957206
```
brew install dart-beta
```

Chocolatey:
https://github.com/dart-lang/sdk/issues/40995 (not implemented, yet)
```
choco install dart-sdk-beta
```

**Comment by kwalrath** [comment]
Fixed with #2362.
