### ISSUE TITLE
'Fixing common type problems' page issue

### ISSUE THREAD

**Issue by amarendrajoshi** [dart-lang/site-www#2331]
Page URL: https://dart.dev/guides/language/sound-problems
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/sound-problems.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
error: A function body must be provided.

**Comment by kwalrath** [comment]
@amarendrajoshi could you give us more context? Thanks!

**Comment by amarendrajoshi** [comment]
Hi Kathy,

The said error was a result of improper bracketing in the code, kindly go through the below screen shots to know more. Sorry if this error don’t qualifies for consideration.

import 'package:flutter/material.dart';

void main(
  runApp(TempApp())
)

class TempApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '',
      home: Scaffold(
        appBar: AppBar(title: Text('')),
        body: Center(
          child: Row(),
        ),
      ),
    );
  }
}


[A screenshot of a cell phone  Description automatically generated]

Regards

Amar

**Comment by kwalrath** [comment]
Since this isn't a type problem, I'm going to close this issue. But it does seem like something that IDEs/editors could be much more helpful with.
