### ISSUE TITLE
Codelab: Intro to Dart for Java Developers - dart:math, not dart.math

### ISSUE THREAD

**Issue by cspok82** [dart-lang/site-www#2333]
Codelab: Intro to Dart for Java Developers
Step 4: Create a factory
URL: https://google.dev/codelabs/from-java-to-dart?return=https%3A%2F%2Fgoogle.dev%2Fpathways%2Fbeta%2Fintro-to-flutter%3Fhl%3Den%23codelab-https%3A%2F%2Fgoogle.dev%2Fcodelabs%2Ffrom-java-to-dart&hl=en#3

Under the first Observations, third point:

- dart.math is one of Dart's core libraries. Other core libraries include dart:core, dart:async, dart:convert, and dart:collection.

Should be dart:math instead of dart.math, note the comma (,) vs the colon (:).

**Comment by domesticmouse** [comment]
Thanks for the report @cspok82! 

Would you like to author a PR to fix it? =)

**Comment by cspok82** [comment]
@domesticmouse I would love to. But I can't seem to find the file containing the issue. :(

**Comment by domesticmouse** [comment]
Ahh, yeah codelabs. I got this. Thanks for the report!

**Comment by domesticmouse** [comment]
Shams, I added some suggested edits to the source for this codelab. =)

**Comment by sfshaza2** [comment]
Thanks, @kwalrath! @domesticmouse, Kathy owns that one now.  :)

**Comment by kwalrath** [comment]
I've fixed it and republished. Thanks for the report, @cspok82!

It's kind of amazing how long that little typo existed, unnoticed (or at least unreported).
