### ISSUE TITLE
Analysis options page should document strict modes

### ISSUE THREAD

**Issue by srawlins** [dart-lang/site-www#2338]
There are three strict analysis modes, `strict-raw-types`, `strict-inference`, and `strict-casts`. These should be documented at https://dart.dev/guides/language/analysis-options.

Summary:
* `strict-raw-types`:
  * since: 2.9.0
  * spec: https://github.com/dart-lang/language/blob/master/resources/type-system/strict-raw-types.md
* `strict-inference`:
  * since: 2.9.0
  * spec: https://github.com/dart-lang/language/blob/master/resources/type-system/strict-inference.md
* `strict-casts`:
  * since: 2.17.0
  * spec: https://github.com/dart-lang/language/blob/master/resources/type-system/strict-casts.md

I'd love to collaborate with someone on how the page should be updated.

These three modes are probably recommended over `implicit-dynamic: false`, so we could deprecate that (or stop documenting it) at the same time. I'll confer with my team on this deprecation idea.

**Comment by bwilkerson** [comment]
I agree. I believe that we're now at a point where we can remove the documentation of the `strong-mode` option / section and replace it with the `language` options Sam mentioned.

@srawlins Just to confirm, are those the only two language options we plan to add at this point?

When we do this, we should be sure to update the characterization of the language options, which currently reads

> Another tag you might see is `language:`, which is used for experimental language features.

I don't think we want to characterize these two modes as experiments.

**Comment by srawlins** [comment]
> I agree. I believe that we're now at a point where we can remove the documentation of the strong-mode option / section and replace it with the language options Sam mentioned.

Unfortunately, I got strong pushback from prominent voices inside google that `implicit-casts: false` is still useful and should not be deprecated. We had a plan to replace this mode with `strict-casts`, which would be almost identical, except that casts from dynamic would be allowed, to match the Null Safety type system. Again, users were saying that `implicit-casts: false` is useful as is. Perhaps we could create `strict-casts` to replace it, and with the _exact same_ functionality.

But this work has not been done yet (I'd be in favor of prioritizing it). Maybe leave `strong-mode` alone for now?

@srawlins Just to confirm, are those the only two language options we plan to add at this point?

Correct. We have plans for `strict-casts` but it has not been prioritized.

> I don't think we want to characterize these two modes as experiments.

Agree. They've been vetted by internal google and by the sass packages.

**Comment by bwilkerson** [comment]
> We had a plan to replace this mode with `strict-casts`, which would be almost identical, except that casts from dynamic would be allowed, to match the Null Safety type system.

That would have been useful when it was proposed, but at this point, with Null Safety as close as I hope it is, I don't think doing this would add enough value.

> Again, users were saying that `implicit-casts: false` is useful as is. Perhaps we could create `strict-casts` to replace it, and with the exact same functionality.

That sounds good to me. I think it's reasonable to allow users to opt out of allowing implicit casts from dynamic.

In the meantime we can at least stop documenting the "strong-mode" options that have been replaced.

**Comment by srawlins** [comment]
There is now a third: `strict-casts: true`. I've updated the top description.

**Comment by kevmoo** [comment]
We should be clear about which SDK versions these appear in!

**Comment by srawlins** [comment]
Good point; I've updated the summary with "since" versions; strict-casts is not in until 2.17.0

**Comment by parlough** [comment]
@srawlins Just to confirm, `strict-casts` will only be available in 2.17? https://github.com/dart-lang/language/blob/master/resources/type-system/strict-casts.md lists 2.16 and it seems to work in the beta as well.

**Comment by kevmoo** [comment]
Seems like it's 2.16 – works fine here https://github.com/dart-lang/ffigen/pull/264

**Comment by srawlins** [comment]
Ah yeah, sorry. I had checked `2.16.0-dev.0`, but that is not the right thing to check 🤣 . 2.16.0 should be good.

**Comment by mit-mit** [comment]
> Unfortunately, I got strong pushback from prominent voices inside google that implicit-casts: false is still useful and should not be deprecated. 

We can still remove it here from the public docs if we don't feel it's something new, external developers should consider using. These docs should essentially be our recommendation for what things to consider using.

**Comment by parlough** [comment]
With `strict-casts` coming out in 2.16 that's no longer much of a worry. I am working on this now and outside of a mention of when `strict-casts` was introduced I don't plan to document `implicit-casts` much.
