### ISSUE TITLE
Misprint

### ISSUE THREAD

**Issue by Konoshenko** [dart-lang/site-www#2343]
<img width="693" alt="Screenshot 2020-04-12 at 22 26 47" src="https://user-images.githubusercontent.com/15077780/79077871-13e45780-7d0d-11ea-98fb-19240cf4fd58.png">
> take(3)gets the next 3 values—2, 3, and 5—in the values list literal.
need change to
take(3)gets the next 3 values—2, 3, and **4**—in the values list literal.

https://codelabs.developers.google.com/codelabs/from-java-to-dart/#5

**Comment by kwalrath** [comment]
The values are `[1, 2, 3, 5, 10, 50]`, so "2, 3, and 5" is correct. If we changed the values to something less contiguous — e.g. 2, 4, 8, 16, 32 — would that be less confusing?

**Comment by Konoshenko** [comment]
Sure

пн, 13 апр. 2020 г. в 19:13, Kathy Walrath <notifications@github.com>:
