### ISSUE TITLE
Google Form not loading

### ISSUE THREAD

**Issue by VarunChilukuri** [dart-lang/site-www#2349]
https://dart.dev/resources/dartpad-best-practices

at the bottom of the page, the google form doesn't load.

**Comment by kwalrath** [comment]
Hi, @VarunChilukuri. Can you give us some information about your browser? Is there anything in the console window?

**Comment by VarunChilukuri** [comment]
I am using chrome and I see the following:

![google form not loading](https://user-images.githubusercontent.com/48163435/79234125-d3352d00-7e37-11ea-8561-fcf96448a366.PNG)

The window loads for me but the actual form is not viewable

**Comment by kwalrath** [comment]
Oh wow, that's embarrassing. I'll talk to the survey creator.

**Comment by kwalrath** [comment]
I believe works now, so I'm closing this bug.

**Comment by kwalrath** [comment]
Thank you very much, @VarunChilukuri, for letting us know about this!
