### ISSUE TITLE
Dart homepage console error

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2353]
https://groups.google.com/a/dartlang.org/d/msg/misc/LjbcekI-Ja4/124WwIyFBwAJ reports the following bug:

> DOM error on Dart homepage, similar value in id element caused Javascript to fail.

@johnpryan might you be able to diagnose this?

**Comment by johnpryan** [comment]
Yeah, I think this was introduced in https://github.com/dart-lang/site-www/pull/2115

**Comment by johnpryan** [comment]
I'm not sure what's causing this, but it doesn't affect users. Search results for "YouTube iframe failed to execute postmessage on domwindow does not match the recipient window's origin" don't seem to agree on a solution.
