### ISSUE TITLE
Document AOT size reduction via DWARF stack traces

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#2360]
I believe this has now all landed, cc @sstrickl to confirm?  If so, can you @sstrickl work with @kwalrath to get some basic docs online for this?

Background: https://github.com/dart-lang/sdk/issues/35851, https://pub.dev/packages/native_stack_traces

**Comment by mit-mit** [comment]
Some ideas: Maybe we can add it on https://dart.dev/tools/dart2native, alternatively start a new AOT performance tuning page?

**Comment by sstrickl** [comment]
We can also start with some of the information in https://github.com/dart-lang/sdk/blob/master/runtime/docs/dwarf_stack_traces.md, though that predates pulling the translator out into the native_stack_traces package so would need updating to mention its use. It also includes technical details of the translator code in the latter half that should be dropped for this kind of documentation (it was originally written with Flutter in mind for integrating into their own toolset so they could default to non-symbolic stack traces in their ecosystem, I'm not sure what state that's in ATM).

/cc @mkustermann

**Comment by mkustermann** [comment]
I think for `dart2native` we might not want to advertise this too much:

  * any caught exception will have a stack trace that needs to be symbolized (on a server which writes exception stacks to a logging system, this might be really inconvenient)
  * size matters much less for desktop/server apps

On mobile (where the size really matters), flutter has their own commands which use this under the hood and they should also have their own documentation for `flutter symbolize` ...

@mit-mit if we want to advertise this, should it be part of the new `dartdev` tool? e.g. provide a similar `dartdev symbolize` (analogous to `flutter symbolize`)?

**Comment by mit-mit** [comment]
I see. Maybe this really belongs on flutter.dev then! cc @sfshaza2

**Comment by sfshaza2** [comment]
I just searched the flutter.dev docs. I recently moved the [obfuscate page to flutter.dev](https://flutter.dev/docs/deployment/obfuscate) (from the wiki) and updated it (as of 1.16). It is the only place I can find where `flutter symbolize` is mentioned on the website. On the page for reducing app size, I only added info on the `--split-debug-info tag`.

If I'm understanding this correctly, it sounds like we might want to mention this in the [performance docs](https://flutter.dev/docs/perf). Does it apply only to web? If so, I can also add it to the web docs, perhaps on the [web deployment](https://flutter.dev/docs/deployment/web) page. If it applies to all deployment scenarios, I can add a mention to all deployment pages.

But I need your guidance.  :)

**Comment by mit-mit** [comment]
No, this is primarily for mobile or any other platform where app size is important.

What this feature does is to use a much more compact format (DWARF) for encoding the code source mapping. This makes the app smaller, but also makes it much harder to read the stack traces. We then added flutter tooling to decode those stack traces.

From a use case point-of-view, this is unrelated to obfuscation.

**Comment by mit-mit** [comment]
@sfshaza2 is this still 'needs information'?

**Comment by sfshaza2** [comment]
I don't think so. It sounds like we can get what we need from engineering.

**Comment by kwalrath** [comment]
I'll close this and create a flutter/website issue.

**Comment by mit-mit** [comment]
Flutter docs: https://flutter.dev/docs/perf/app-size#reducing-app-size
