### ISSUE TITLE
Clarify classes of keywords

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2367]
From [@eernstg](https://github.com/dart-lang/site-www/pull/2359#issuecomment-615265188) :

> I have a couple of drive-by comments, cf. https://github.com/dart-lang/site-www/pull/2358#issuecomment-614973233.
> 
> The phrase 'contextual keyword' is not used in the language specification documents. I did use it in a comment in the [spec grammar](https://github.com/dart-lang/sdk/blob/ae0eca83188ce3bd99e3f012cf7eec4b0bdf2c4f/tools/spec_parser/Dart.g#L1539) , but only with await and yield. Those two words are special in that they are considered to be reserved words in the body of an async (they cannot be the name of any declaration, which is more strict than built-in identifiers that can't be the name of a type but can be the name of other things).
> 
> So it would make sense to single out just await and yield as being contextual keywords (they are currently presented as 'newer' because asynchrony was new some years back, but that's hardly helpful today). So they'd get superscript '1'.
> 
> All the words currently marked with superscript '1' would no more be marked with that superscript: extension will be a built-in identifier ('2'), and it's not obvious that we would need to mention async, hide, of, on, show, and sync as special at all: They can be used as the name of any declaration, and they can be used as identifiers in any expression. They do occur explicitly in the grammar, but it's not helpful to teach anybody to keep them in a mental list of special words (to avoid), because there are no special constraints on the use of these words as identifiers.
> 
> If we expect this to be a surprise to readers then we could mention async, hide, of, on, show, sync after the table, saying that there are no constraints on the use of those words as identifiers, even though they appear in the grammar.

**Comment by atsansone** [comment]
Fixed in https://github.com/dart-lang/site-www/pull/5681 and https://github.com/dart-lang/site-www/pull/5702.
