### ISSUE TITLE
Typo in https://dart.dev/codelabs/async-await (Section: Why asynchronous code matters)

### ISSUE THREAD

**Issue by farr64** [dart-lang/site-www#2370]
Typo in https://dart.dev/codelabs/async-await

Section: Why asynchronous code matters

The "the" (which I highlighted in bold) is either superfluous or out of sequence:

In the next sections you’ll learn **the** about futures. . .

**Comment by kwalrath** [comment]
Thanks for reporting this! If you'd like to fix it, you can click the doc icon at the upper right of the page.

**Comment by Samtfm** [comment]
Looks like this has been fixed. The typo is no longer present on the live site.

**Comment by farr64** [comment]
Yeah: I fixed it after Kathy's suggestion ;-)

Thanks. Closing this now.
