### ISSUE TITLE
Compilation error In Step 4 of the "Intro to Dart for Java Developers"

### ISSUE THREAD

**Issue by vipref** [dart-lang/site-www#2374]
The keyword 'extends' needs to be changed to 'implements' for all subclasses when the Shape class has a factory constructor else the code doesn't compile.

The error is below:

Error compiling to JavaScript:
main.dart:15:3:
Error: The superclass, 'Shape', has no unnamed constructor that takes no arguments.
  Circle(this.radius);
  ^^^^^^
Error: Compilation failed.

**Comment by kwalrath** [comment]
Thanks for the issue, @vipref. Could you tell me exactly where the affected code is? (URL + some nearby text) Thanks!

**Comment by vipref** [comment]
Will re-file with details
