### ISSUE TITLE
'dart2js: Dart-to-JavaScript compiler' – replace IE w/ Edge

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#2382]
Page URL: https://dart.dev/tools/dart2js.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/dart2js.md

Replace "Internet Explorer" with Edge

**Comment by Aayush-B** [comment]
Hi,
I would like to work on this.

**Comment by kwalrath** [comment]
Fixed in #2384 by @Aayush-B. Thank you!
