### ISSUE TITLE
Improve search pages & CSE

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2383]
From flutter/website#4000, here are some problems with the search pages on dart.dev & flutter.dev that we'd love some help with:

* ~~When the text field is empty on both /search & /search-all, it's too small. Fixed on dart.dev by #2741.~~
* It'd be nice to copy the search query from /search over to /search-all.
* We should probably tweak the ownership of the CSEs, so a role account is the owner instead of me. (This is the only part that probably requires a Googler.)

Page links:
* https://dart.dev/search
* https://dart.dev/search-all
* https://flutter.dev/search
* https://flutter.dev/search-all

CSE links:
* Flutter.dev: https://cse.google.com/cse?cx=011220921317074318178:qhv1ojyoytz
  ([admin link](https://cse.google.com/cse/setup/basic?cx=011220921317074318178:qhv1ojyoytz))
* Flutter.dev and more: https://cse.google.com/cse?cx=011220921317074318178%3Adeii8vtsimy
  ([admin link](https://cse.google.com/cse/setup/basic?cx=011220921317074318178%3Adeii8vtsimy))
* Dart.dev: https://cse.google.com/cse?cx=011220921317074318178%3Aufsd-ukx1ii
  ([admin link](https://cse.google.com/cse/setup/basic?cx=011220921317074318178%3Aufsd-ukx1ii))
* Dart.dev and more: https://cse.google.com/cse?cx=011220921317074318178%3A_yy-tmb5t_i
  ([admin link](https://cse.google.com/cse/setup/basic?cx=011220921317074318178%3A_yy-tmb5t_i))

**Comment by micpap25** [comment]
@kwalrath Should the Dart /search and /search-all files be simplified down to the way they are in Flutter?

**Comment by micpap25** [comment]
@johnpryan made some changes to the site that fix the first problem you listed, I'm bringing them over to the Flutter site right now.

**Comment by kwalrath** [comment]
> @kwalrath Should the Dart /search and /search-all files be simplified down to the way they are in Flutter?

Yes, I think so. When I updated the Flutter search, I just copy-pasted what was in the custom search console. Going back to the console, here's what it says for the dart.dev-only search:

```
<script async src="https://cse.google.com/cse.js?cx=011220921317074318178:ufsd-ukx1ii"></script>
<div class="gcse-search"></div>
```

And for the "more sites" search:

```
<script async src="https://cse.google.com/cse.js?cx=011220921317074318178:_yy-tmb5t_i"></script>
<div class="gcse-search"></div>
```

**Comment by parlough** [comment]
We're going to plan larger search improvements that likely go in a different direction, so I'm going to close this in favor of that work. Thanks everyone!
