### ISSUE TITLE
Add date to SDK archive page?

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2389]
Page URL: https://dart.dev/tools/sdk/archive/
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/sdk/archive/index.md

https://flutter.dev/docs/development/tools/sdk/releases?tab=macos has dates for each release, which is handy (e.g. when updating wikipedia, or when deciding whether you should download the SDK again). It'd be nice to have release dates on the Dart page. We might consider aligning the pages in other ways, too.

/cc @sfshaza2 @johnpryan @domesticmouse @mit-mit

**Comment by sfshaza2** [comment]
I love that idea!

**Comment by domesticmouse** [comment]
@mit-mit what is required to make this happen? I'm guessing the included html is generated during the release process somehow. =)

**Comment by mit-mit** [comment]
The Dart code we have actually contains support for getting the time stamps off of the SDK archive files. I tried extending the html so those are shown in the tables. But I don't think it's going to work well for us, as it looks like the time stamps are often off by a few days from what the [changelog](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md) has.

@athomas I suspect that's because we often build the archives 1-2 days before releasing them?

**Comment by athomas** [comment]
@mit-mit Depends on the channel, dev releases are typically released on the same day. Beta releases maybe, but stable releases usually have at least a 2 day gap from the release date. A better way would be to use the dates from the git tags, those are usually created just before the release is published. We could expand the promotion step to add another file to cloud storage that contains the publish date.

**Comment by parlough** [comment]
@athomas Was there ever any work done to make the publish date available from cloud storage?

**Comment by athomas** [comment]
Hmm, this is weird, I can't reproduce the timestamps being off on the `release` artifacts, they are off on the `raw` zips. This is for macOS, but I get the same result for Linux SDKs:

```
$ gsutil.py stat gs://dart-archive/channels/stable/release/2.18.1/sdk/dartsdk-macos-arm64-release.zip
gs://dart-archive/channels/stable/release/2.18.1/sdk/dartsdk-macos-arm64-release.zip:
    Creation time:          Wed, 14 Sep 2022 14:12:28 GMT
    Update time:            Wed, 14 Sep 2022 14:12:28 GMT
    Storage class:          MULTI_REGIONAL
    Content-Language:       en
    Content-Length:         173745542
    Content-Type:           application/zip
    Hash (crc32c):          g1t3fQ==
    Hash (md5):             UvbgyKi6oi6rCcFFMsT4lw==
    ETag:                   CMe5qMC7lPoCEAE=
    Generation:             1663164748537031
    Metageneration:         1

$ gsutil.py stat gs://dart-archive/channels/stable/raw/2.18.1/sdk/dartsdk-macos-arm64-release.zip
gs://dart-archive/channels/stable/raw/2.18.1/sdk/dartsdk-macos-arm64-release.zip:
    Creation time:          Tue, 13 Sep 2022 09:53:20 GMT
    Update time:            Tue, 13 Sep 2022 09:53:20 GMT
    Storage class:          MULTI_REGIONAL
    Content-Length:         173483692
    Content-Type:           application/zip
    Hash (crc32c):          o259wQ==
    Hash (md5):             7z/V+GeTEWzL+EtpnHLw6Q==
    ETag:                   CNCly9u/kfoCEAE=
    Generation:             1663062800257744
    Metageneration:         1

```
🤷
