### ISSUE TITLE
one example wrong in Language Style

### ISSUE THREAD

**Issue by amitbar05** [dart-lang/site-www#2392]
In section [DO capitalize acronyms and abbreviations longer than two letters like words](https://dart.dev/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words)
You got a conflict between:
Good examples:
DB, Id
Bad examples:
Db, ID

Just need to change in good example the "Id" to "ID".

**Comment by kwalrath** [comment]
Ah, but ID is an abbreviation, not an acronym. It's covered by the following sentence:

>  (Two-letter abbreviations like ID and Mr. are still capitalized like words.)
