### ISSUE TITLE
22ms for a "Hello world!" is not fast

### ISSUE THREAD

**Issue by piegamesde** [dart-lang/site-www#2396]
The language is advertised as being fast using this screenshot:

![image](https://user-images.githubusercontent.com/14054505/81331749-585fda80-90a2-11ea-82f3-6e3ec4bbfd19.png)

Game developer Jonathan Blow has made a [short thread](https://twitter.com/Jonathan_Blow/status/1258424476116508672) about this that explains why this isn't fast nor a good example.

I do understand the intention behind this image though – it is about startup time and not about performance, startup time in managed languages is a big issue and AOT compilation is a great feature to show off.

Possible improvements:

- Don't put "Fast on all platforms" next to that screen shot. The image refers to "AOT-compile apps to native machine code for instant startup", but the design doesn't make this link clear enough.
- Improve the image to empathize the startup time instead of general performance, e.g. by changing the "Completed in just 22 ms" seconds.

**Comment by kwalrath** [comment]
Thanks for making sure we're aware of this, @piegamesde.

/cc @johnpryan @mit-mit @kevmoo @messi01

**Comment by mit-mit** [comment]
Fixed earlier in https://github.com/dart-lang/site-www/pull/3413
