### ISSUE TITLE
Add note about old release names?

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2397]
flutter.dev will soon have a note about the name change: flutter/website#4064. Should we, as well?

The relevant pages:
* https://dart.dev/get-dart
* https://dart.dev/tools/sdk/archive#download-urls

Also relevant is the PR that updated the pages and code for beta: #2363

/cc @mit-mit

**Comment by mit-mit** [comment]
I *think* the changes on our end were pretty minor, and don't need a note?
