### ISSUE TITLE
documentation improvement: run-time libraries on client vs server?

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#24]
_From @nicolasgarnier on August 26, 2014 15:9_

_From [jim.trai...@gmail.com](https://code.google.com/u/102189678801052322170/) on July 09, 2013 18:46:23_

Developers are often confused about what libraries can be used where.  e.g. client side versus server side limitations.

A standard means to document this for packages would be helpful.

The same improvement could capture platform specific limitations, or caveats, that developers need to understand in order make informed decisions about using a particular feature, or package, in the Dart environment. e.g. caveats about javascript, or browser, support where it is limited.

Please see related forum thread: https://groups.google.com/a/dartlang.org/forum/#!topic/misc/82a9yi2vqrs

_Original issue: http://code.google.com/p/dart/issues/detail?id=11755_

_Copied from original issue: dart-lang/www.dartlang.org#717_

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:9_

_From [ras...@mindplay.dk](https://code.google.com/u/106562836841821712456/) on July 09, 2013 10:48:15_

duplicate of #11754

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:9_

_From [iposva@google.com](https://code.google.com/u/iposva@google.com/) on July 10, 2013 14:12:06_

**Status:** Triaged  
  **Labels:** Area-Documentation

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:9_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on July 23, 2013 14:15:30_

Issue 11754 has been merged into this issue.

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:9_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on July 23, 2013 14:15:57_

**Labels:** Docs-API

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:9_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on June 04, 2014 14:58:12_

**Labels:** -Area-Documentation Area-Site

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:9_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on June 04, 2014 16:49:36_

**Labels:** -Type-Defect Type-Documentation

**Comment by Sfshaza** [comment]
_From @srawlins on September 3, 2014 14:23_

This sounds like a docgen and/or dartdoc-viewer feature. Should this be moved from this issue tracker?

**Comment by Sfshaza** [comment]
_From @sethladd on September 3, 2014 15:24_

Yes, should be dartdoc-viewer. Could also surface on pub.dartlang.org.

**Comment by Sfshaza** [comment]
_From @kwalrath on September 3, 2014 22:52_

I'm not sure where this should go, but it seems like we could have a figure high up in the programmer's guide about this. We should also fix this on api.dartlang.org.

**Comment by kwalrath** [comment]
Covered by pub.dartlang.org, woohoo!
