### ISSUE TITLE
Blank embedded DartPads on codelab

### ISSUE THREAD

**Issue by misiurina** [dart-lang/site-www#2400]
https://dart.dev/codelabs/async-await has all the embedded DartPads blank. No code there, copy and reset don't work. Probably an issue with the source.

**Comment by kwalrath** [comment]
It works for me, so I think you need to take a look at https://dart.dev/tools/dartpad/troubleshoot.

(There's a link to that up high in the page, but it's easy to miss. I'm not sure how I can make it more obvious without distracting the majority of people who have no problem with the DartPads.)

**Comment by misiurina** [comment]
It didn't work for me on two different devices, so I thought, there's a problem with the site. Thanks for the link and sorry for bothering you.

**Comment by kwalrath** [comment]
No worries, we want to know about possible outages! Is it working for you yet?
