### ISSUE TITLE
Dart Codelabs and Dartlab broken - XMLHttpRequest error and minify error

### ISSUE THREAD

**Issue by bobjoyce** [dart-lang/site-www#2401]
In the Intro to Dart for Dart Developers, I click on Open the Scream example in DartPad. and I get the error Error loading gist 9bcb7dba6dca46e2a9dbfb300298461e.

In the Dart Cheatsheet lab, I got an error when I run some solutions (e.g. running the solution for getters and setters.  The error mentioned issues converting to javascript and minify.  I'd show the error but now I just get a blank screen and the Solutions menu item does not even appear. See image below.

I also now get an error running a simple program in Dartpad - Error compiling to JavaScript:
XMLHttpRequest error. See second image below.

I hit a similar problem yesterday but that issue was resolved and things worked this morning and early afternoon.  

![image](https://user-images.githubusercontent.com/804093/81759606-03450f80-947a-11ea-86e3-f37286ee24a4.png)

![image](https://user-images.githubusercontent.com/804093/81759733-5919b780-947a-11ea-9ebd-c223329cfa67.png)

**Comment by domesticmouse** [comment]
I think I may have finally figured out the right ritual to placate the server gods. Closing this for now, but feel free to re-open if it goes sideways again. Or ping me on Twitter (same username).
