### ISSUE TITLE
Remove "PREFER placing external 'package:' imports before other imports."

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#2402]
I personally like the guideline, but we've never had automated tooling support for it and don't have any plans. I think the benefits of being able to easily automatically sort imports outweigh the benefits of seeing a package's own "package:" imports separately.

I think we should just remove the rule and let the previous rule cover all "package:" imports.

**Comment by pq** [comment]
> I personally like the guideline, but we've never had automated tooling support for it

Unless I'm misunderstanding, I _think_ we do?

I believe that the sorting analysis server provides and you can call out to in IntelliJ via the Code Menu respects this ordering.

![image](https://user-images.githubusercontent.com/67586/81991446-1977da80-95f6-11ea-824e-fee5d3943ffb.png)

(fyi @scheglov)

Also as of really recently (https://github.com/dart-lang/sdk/commit/7fe16ba8125ccaa275dfb29bf029cf5d4566c105) I added a quickfix that I've been wanting forever for the corresponding `directives_ordering` lint so the tooling is slowly catching up... 🐌

**Comment by munificent** [comment]
We have support for sorting imports, but (as far as I know) it doesn't separate out a package's own "package:" imports from "package:" imports of other packages. At least tidy_dart does not support that, and I think that's the one that is most widely used inside Google.

**Comment by scheglov** [comment]
The sorting in Analysis Server also does not separate package's own `package:` imports from other  `package:` imports.

**Comment by pq** [comment]
Ah, ok, cool.  Thanks!  In that case, bombs away :)

**Comment by pq** [comment]
Is this  done?

**Comment by kwalrath** [comment]
Fixed by #2405.
