### ISSUE TITLE
Add "What's new" page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2412]
Maybe start with a "What's new on this site" section to dart.dev/docs, like flutter.dev/docs.

Then we can add a page like https://flutter.dev/docs/whats-new-archive.

This came up in the course of Effective Dart changes: #2404, #2405.

**Comment by nnhhiilliisstt** [comment]
can i work on this issue?

**Comment by kwalrath** [comment]
Thanks for volunteering, @nnhhiilliisstt! You're welcome to submit a PR, but be warned, it might be fiddly work because we'll want to set a good precedent for future changes.

**Comment by nnhhiilliisstt** [comment]
will try my best
