### ISSUE TITLE
Add dark mode for documentation page

### ISSUE THREAD

**Issue by nnhhiilliisstt** [dart-lang/site-www#2414]

**Comment by kwalrath** [comment]
Could you please elaborate?

**Comment by nnhhiilliisstt** [comment]
It's a feature request. I don't know anyone felt the need of it or, not but I think it would be nicer if @dart-lang team adds a 'Dark Mode' in the official documentation.

Thank you.

**Comment by kwalrath** [comment]
This would be a significant project, but an interesting one if anyone has the time to volunteer. If anyone's interested in mocking this up, let us know on this issue.

**Comment by NinaPacifier** [comment]
@kwalrath Dark mode seems an interesting feature for me. Can I take this issue??

**Comment by kwalrath** [comment]
> @kwalrath Dark mode seems an interesting feature for me. Can I take this issue??

Go for it!

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/2625 which covers the same issue. Thanks everyone for opening the issue and surrounding suggestions!
