### ISSUE TITLE
'Iterable collections' page issue

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/site-www#2418]
Page URL: https://dart.dev/codelabs/iterables.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/iterables.md

Description of issue:
Under Iterable [Example: Using first and last](https://dart.dev/codelabs/iterables#example-using-first-and-last)
Instead of `var iterable = ['Salad', 'Popcorn', 'Toast'];` it should be `Iterable iterable = <String>['Salad', 'Popcorn', 'Toast'];` .
`var iterable = ['Salad', 'Popcorn', 'Toast'];` allows using `[]` to access elements.

**Comment by domesticmouse** [comment]
Type casting a `List` to a `List<String>` (which is what your suggested patch does) doesn't stop the use of indexing. The following code works:

```dart
void main() {
  var iterable = <String>['Salad', 'Popcorn', 'Toast'];
  print('The first element is ${iterable[0]}');
  print('The last element is ${iterable[iterable.length -1]}');
}
```

The way to stop this, is to cast the `List` to a `Iterable`, like thus:

```
void main() {
  Iterable iterable = ['Salad', 'Popcorn', 'Toast'];
  print('The first element is ${iterable[0]}');
  print('The last element is ${iterable[iterable.length -1]}');
}
```

**Comment by dev-aentgs** [comment]
`Iterable iterable = <String>['Salad', 'Popcorn', 'Toast'];` 
i mentioned this.

**Comment by kwalrath** [comment]
@dev-aentgs want to do a PR for this?

**Comment by dev-aentgs** [comment]
@kwalrath changes will be needed in example code given in embedded dartpad, not sure how to change those.

**Comment by kwalrath** [comment]
Good point, @dev-aentgs. I'm converting the gists to be auto-included, but until then... I've forked the gist and pointed to the new code.

**Comment by dev-aentgs** [comment]
Thank you @kwalrath
