### ISSUE TITLE
'Iterable collections' page issue missing function in Exercise: Putting it all together

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/site-www#2420]
Page URL: https://dart.dev/codelabs/iterables.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/iterables.md

Description of issue:
In [Exercise: Putting it all together](https://dart.dev/codelabs/iterables#exercise-putting-it-all-together)  the `bool isValidEmailAddress(EmailAddress)` function is not provided.

**Comment by dev-aentgs** [comment]
`isValidEmailAddress(EmailAddress)` doesn't appear in (_ctrl + space_ ) autocomplete suggestions but it is provided internally.

**Comment by kochetkov-ma** [comment]
![image](https://user-images.githubusercontent.com/16944358/95780261-3f53f900-0cd4-11eb-9980-9f3c6c8a09eb.png)

**Comment by kwalrath** [comment]
I suspect the issue is that the **Run** button doesn't run the solution. You need to copy the code back into the **Dart** tab and _then_ click Run. That works for me.

This confusing UI has been reported: https://github.com/dart-lang/dart-pad/issues/1601
