### ISSUE TITLE
'Write command-line apps' page issue

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/site-www#2426]
Page URL: https://dart.dev/tutorials/server/cmdline
Page source: https://github.com/dart-lang/site-www/tree/master/src/_tutorials/server/cmdline.md

Description of issue:
In [Overview of the dcat app code](https://dart.dev/tutorials/server/cmdline#overview-of-the-dcat-app-code)  and [Parsing command-line arguments](https://dart.dev/tutorials/server/cmdline#parsing-command-line-arguments)
why is cascade notation used for `addFlag()` ?
> 
`final parser = ArgParser()
    ..addFlag(lineNumber, negatable: false, abbr: 'n');
`
>

**Comment by domesticmouse** [comment]
If you look at the documentation for [`addFlag()`](https://pub.dev/documentation/args/latest/args/ArgParser/addFlag.html) you will see that it's return type is void, so utilising cascade allows the construction of the parser and adding a flag in a one liner. 

The alternative would be to construct the parser on one line, and then set it on the following line, which I believe we have a lint check to prevent.

**Comment by kwalrath** [comment]
Thanks for the answer, @domesticmouse!
