### ISSUE TITLE
Need examples for a testing page.

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#243]
I will be writing a page on testing and I need at least two examples that are interesting enough when showing off the testing features in IntelliJ and the continuous testing with Travis. I'd like one that uses packages:test, and one that uses package:test and package:mockito.

This page will live on dartlang, not webdev, so they shouldn't use web packages.

**Comment by isoos** [comment]
An idea: testing integration with a third-party system, like database access CRUD code, or a REST API call. Although I'm not sure what what use case would provide the minimal amount of code and still be meaningful...

**Comment by Sfshaza** [comment]
An interesting idea!  @kevmoo, @filiph, you both know far more about testing than I do. Please weigh in!

**Comment by Sfshaza** [comment]
@isoos, I will share the doc plan with you.

**Comment by kevmoo** [comment]
@isoos we probably want to be careful with examples that require 3rd-party packages or other running services.

I think shelf is a good example. He has code that runs client & server. It uses the travis matrix to run multiple Dart versions + browsers, etc.

https://github.com/dart-lang/shelf

**Comment by Sfshaza** [comment]
@isoos, I met with Filip today (I'm starting to work on the testing page and am gathering info). I showed him the mockito example I'm using for now and he asked me to share it here.

```
import 'dart:math' show Random;

import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

// A service that feeds cats.
class CatCafe {
  static final Random _index = new Random();
  List<String> _menu = ['fish', 'chicken', 'beef', 'milk', 'kibble'];

  String serveMeal() {
    return _menu[_index.nextInt(_menu.length)];
  }
}

class Cat {
  final service;
  Cat(CatCafe this.service);

  String getFood() {
    return service.serveMeal();
  }
}

@proxy
class MockCatCafe extends Mock implements CatCafe {}

main() {
  var real_cafe = new CatCafe();
  var real_cat = new Cat(real_cafe);

  for (var i = 0; i < 5; i++) {
    print(real_cat.getFood());
  }

  test('cat cafe', () {
    var mock_cafe = new MockCatCafe();
    var mock_cat = new Cat(mock_cafe);

    when(mock_cafe.serveMeal()).thenReturn('kibble');
    mock_cat.getFood();
    expect(mock_cat.getFood(), 'kibble');
    verify(mock_cafe.serveMeal()).called(2);
  });
}
```

I'm still figuring out the exact scope of the doc, but I don't want to repeat Natalie's doc in the package_test README, as she did a good writeup. I do want to show/discuss a mockito example. I also want to show how devs might want to use tags in package:test.

**Comment by isoos** [comment]
I've updated your code a bit, and I've also added the ISS spotter @filiph mentioned to me earlier. It is a simple REST API that returns the current GPS position of the ISS, and I think 'mocking' that may provide more visible benefits:
https://github.com/isoos/testing_example/tree/master/lib
https://github.com/isoos/testing_example/tree/master/test

What do you think?

**Comment by filiph** [comment]
So cool! I love both the examples. I'll defer to Shams' judgement on which one to choose.

If we decide to use the ISS one, it might make sense to create the simplest possible "app" in https://github.com/isoos/testing_example/blob/master/web/ and `peanut` -> publish to github.io. That way we can actually show people something useful ("Is ISS visible from your city at this time?") first and then saying "so how would you test something like _that_?")

**Comment by Sfshaza** [comment]
I also love them both! Who says I can't use both?  Maybe I'm a bit of a
piggy pig.   ;)

Istvan you really improved the cat_cafe example, thx!

Thanks so much, @isoos!

**Comment by isoos** [comment]
The useful (and worth-to-mention) example app should contain Google Maps integration, and at that point, I think the testing focus is kind of misplaced. Anything less feel strange an sub-par compared to e.g. https://spotthestation.nasa.gov/sightings/ or http://iss.astroviewer.net/observation.php

A simpler approach could be to present it as a console application, which can be more simple: a few pre-defined location (major cities) and the ability to specify a coordinate by argument.

What do you think?

**Comment by Sfshaza** [comment]
@isoos, I love your idea of tying this to an example that uses Google Maps. (Bye bye, cats!)

Though this is an example for www.dartlang, which isn't supposed to cover web stuff, in this case it's not ABOUT the web implementation. I asked Filip and he feels that it should be a /web app, otherwise it just isn't that compelling, and I agree.

I'm going to let you decide on the implementation details for the /web app. It probably shouldn't be too complicated, but have fun with it.  :)

By the way, I don't quite follow how sphericalDistanceKm() works. Is it calculating, somehow, whether the ISS is visible from point1, point2, or anywhere in between? Is there some restriction on how far point1 can be from point2 for the math to work?

**Comment by isoos** [comment]
I may be overdoing this, but I think a web app will be a distraction. E.g. see the following branch:
https://github.com/isoos/testing_example/tree/web_app
Public demo is not working ATM, because github pages is over https, and the ISS position service is HTTP-only, and browsers are picky nowadays to prevent non-https request in such cases. Will update with a different host soon.

(If you can think of a narrower scope for a reasonable app, let me know, happy to delete the stuff I have.)

**Comment by isoos** [comment]
Demo link: http://isoos-dart-demo.s3-website.eu-central-1.amazonaws.com/testing_example/index.html

**Comment by Sfshaza** [comment]
@isoos, I am OK if we don't include a web app. The example is very useful without it.

Thanks so much!

**Comment by Sfshaza** [comment]
I'm closing this. Thanks, @isoos!
