### ISSUE TITLE
Update pub uploader output

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2431]
In a week or two, we expect the `pub uploader` output to change. The example text should be updated at that time.

Details:
https://github.com/dart-lang/site-www/pull/2395

/cc @jonasfj @isoos

**Comment by jonasfj** [comment]
This is scheduled for 28th, in either case, shipping the new messages a few days in advance is probably okay.
We're switching traffic gradually anyways, so there will be inconsistencies.
