### ISSUE TITLE
Question - Write HTTP clients & servers 

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/site-www#2435]
Page URL: https://dart.dev/tutorials/server/httpserver
Page source: https://github.com/dart-lang/site-www/tree/master/src/_tutorials/server/httpserver.md

Question :
Are there updated versions of links given in [What next?](https://dart.dev/tutorials/server/httpserver#what-next)  

Saw the warnings given on [github.io server codelab](https://dart-lang.github.io/server/codelab/) and the related [github issue](https://github.com/dart-lang/server/issues/12)

**Comment by kwalrath** [comment]
Good question, @dev-aentgs. As you can probably tell, this page was written a long time ago.

@kevmoo & @mit-mit, what do you think we should do? Is this page still useful? If so, where should we point next? (https://pub.dev/packages/shelf? https://github.com/dart-lang/pub-dev? https://github.com/dart-lang/dart-services?)

**Comment by domesticmouse** [comment]
Fwiw, I referred to this page while building out my Flutter for macOS sample, so yes it is a useful page. No preferences on where next, however. =)

**Comment by mit-mit** [comment]
I definitely this this page is useful. I would link to all those three links you have [there](https://github.com/dart-lang/site-www/issues/2435#issuecomment-634271674) Kathy in 'What next'

**Comment by parlough** [comment]
The tutorial was stripped in https://github.com/dart-lang/site-www/commit/a97d50201ee78fcd38d52d9d83dbc2aa875d4d91 resulting in this not being relevant and work for replacement material is planned in https://github.com/dart-lang/site-www/issues/3058. Closing in favor of that work. Thanks again for opening an issue!
