### ISSUE TITLE
'Add elements to the DOM' page issue

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/site-www#2437]
Page URL: https://dart.dev/tutorials/web/low-level-html/add-elements
Page source: https://github.com/dart-lang/site-www/tree/master/src/_tutorials/web/low-level-html/add-elements.md

Description of issue:
It is mentioned in [Other resources](https://dart.dev/tutorials/web/low-level-html/add-elements#other-resources) that more info about DOM and CSS can be found in [Language tour](https://dart.dev/guides/language/language-tour).
> Other resources
You can find more information about the DOM and CSS in the language tour, which also provides thorough coverage of the Dart language.
>

I think in Language tour there is no info about DOM and CSS.

**Comment by kwalrath** [comment]
Thanks, @dev-aentgs! I think we should probably just remove this section unless there are other resources we want to point to.
