### ISSUE TITLE
'Remove DOM elements' page issue 

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/site-www#2438]
Page URL: https://dart.dev/tutorials/web/low-level-html/remove-elements
Page source: https://github.com/dart-lang/site-www/tree/master/src/_tutorials/web/low-level-html/remove-elements.md

Description of issue:
CSS `font-size `property to make text larger is missing in dartpad code.

**The code in dartpad**
`#to-do-list li:hover {
  color: red;
  cursor: pointer;
}`
**The code in explanation**
`#to-do-list li:hover {
  color: red;
  font-size: 18px;
  cursor:pointer;
}`

**Comment by kwalrath** [comment]
Thanks, @dev-aentgs! We need to make a pass through the pages that contain DartPads, auto-including code instead of using gists. I'll create a project for these changes and add this.

**Comment by dev-aentgs** [comment]
Thank you @kwalrath
