### ISSUE TITLE
'Effective Dart: Design' page 

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/site-www#2440]
Page URL: https://dart.dev/guides/language/effective-dart/design
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/design.md

Description:
[AVOID extending a class that isn’t intended to be subclassed.](https://dart.dev/guides/language/effective-dart/design#avoid-extending-a-class-that-isnt-intended-to-be-subclassed) 
Dart doesn't allow `final` `class`.
Like in java, in this case allowing the class to be marked as `final` would prevent another class from inheriting it.
What would be the side effects if this was allowed?

**Comment by kwalrath** [comment]
Good question, but beyond the scope of the website. Maybe ask this on a Dart discussion group? https://dart.dev/community

**Comment by dev-aentgs** [comment]
Thank you @kwalrath , asked on [dart-lang #987](https://github.com/dart-lang/language/issues/987)
