### ISSUE TITLE
'Effective Dart: Design' page issue

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/site-www#2441]
Page URL: https://dart.dev/guides/language/effective-dart/design
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/design.md

Description of issue:
In [design.md](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/effective-dart/design.md), the text appears to be _strike through_  starting just before [Libraries section](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/effective-dart/design.md#libraries) and continues till the end of page.
![why_striked_out](https://user-images.githubusercontent.com/65178249/82780401-a59ac500-9e74-11ea-9dab-3a8a23844550.png)

**Comment by domesticmouse** [comment]
The [rendered version](https://dart.dev/guides/language/effective-dart/design) on dart.dev looks good to me. The markdown we are using isn't quite the same as GitHub markdown. Unfortunately markdown is underspecified.

**Comment by dev-aentgs** [comment]
Yes rendered version is good.
