### ISSUE TITLE
'Extension methods' page private/public information

### ISSUE THREAD

**Issue by RayDarar** [dart-lang/site-www#2442]
Page URL: https://dart.dev/guides/language/extension-methods
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/extension-methods.md

I think it is worth noticing that it's possible to create extension methods without naming it and that by doing so, it will make it "private". I can't come up with the application other than "local scoping" extension methods to the file.

```dart
// library.dart

extension on String {
  int toInt() => int.parse(this);
}
```

```dart
// main.dart

void main() {
  String str = "19";
  int number = str.toInt(); // won't work
}
```

P.S. I'm new to dart, so maybe there's a reason for not mentioning it in the docs that I don't know.

**Comment by kwalrath** [comment]
Thanks for making sure we knew about this, @RayDarar. We initially thought there wasn't a good use case for unnamed extensions, but it appears there might be. I'm going to close this in favor of #2337.
