### ISSUE TITLE
'Fixing common type problems' page issue

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#2444]
Page URL: https://dart.dev/guides/language/sound-problems
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/sound-problems.md

https://dart.dev/guides/language/sound-problems#the-function-expression-type--isnt-of-type-

## Incorrect description

> However, in Dart 2 passing something other than `dynamic`

This should be "in Dart 2 using a parameter type other than `dynamic`". The current phrasing implies a probably with passing the value to the function, not to the function type itself.

## Style

The example assigns a closure to a variable, violating https://dart.dev/guides/language/effective-dart/usage#do-use-a-function-declaration-to-bind-a-function-to-a-name

It also uses a (local?) variable type which shouldn't be necessary, and finally it seems to encourage `typedef`. I might write the examples as:

Static analysis warning:

```dart
void filterValues(bool Function(dynamic) filter) {}
filterValues((String x) => x.contains('Hello'));
```

Add type parameter:

```dart
void filterValues<T>(bool Function(T) filter) {}
filterValues<String>((x) => x.contains('Hello')); // x has type String
```

Cast:

```dart
void filterValues(bool Function(dynamic) filter) {}
filterValues((x) => (x as String).contains('Hello'));
```

cc @munificent for thoughts.

**Comment by simphotonics** [comment]
We are encouraged to **omit_local_variable_types**. In the example below, omitting the type declaration of the variable `alphaDecoder` leads to `constantReader` being identified as having type `dynamic`. In this case, I would have to specify the type of the function parameter. 

Question. Is is at all possible to use the typedef `Decoder<T>` on the RHS to **omit_local_variable_types** when assigning a value to `alphaDecoder`? 





```Dart
import 'package:source_gen/source_gen.dart';

typedef Decoder<T> = T Function(ConstantReader constantReader);

class Alpha{
  const Alpha(this.value);
  final int value;
}

void main(){
...
  final Decoder<Alpha> alphaDecoder = ((constantReader){                        
    return (cr == null) ? null: Alpha(constantReader.peek('value')?.intValue);
  } 
}
```

**Comment by natebosch** [comment]
> I'd like to ask: Is is at all possible to use the typedef `Decoder<T>` on the RHS to **omit_local_variable_types** when assigning a value to `alphaDecoder`?

No, and I believe the lint `omit_local_variable_types` _should_ allow this.

In any case, outside of any considerations about local variable type annotations, the way we would recommend you write this is:

```dart

void main(){
...
  Alpha alphaDecoder(ConstantReader constantReader) {                        
    return (constantReader == null) ? null: Alpha(constantReader.peek('value')?.intValue);
  } 
}
```

See https://dart.dev/guides/language/effective-dart/usage#do-use-a-function-declaration-to-bind-a-function-to-a-name

**Comment by simphotonics** [comment]
@natebosch Thank you for your reply, I'll take that on board.  Appreciate the link (I must have missed it in your comment above).

 Had a quick look and at least with my setup, I am including `package:pedantic/analysis_options.yaml` in my local `analysis_options.yaml` file,  the lint `omit_local_variable_types` does indeed flag the usage shown above. Won't be an issue though, I'll follow the recommended way of binding a function to a name. 

![screenshot](https://user-images.githubusercontent.com/5442704/88641303-e7cfc500-d0b6-11ea-869a-28f480973637.png)

**Comment by natebosch** [comment]
Ah, yeah I think https://github.com/dart-lang/linter/issues/2107 tracks that issue.
