### ISSUE TITLE
Change wording in grey boxes

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-www#245]
Suggestion from @kasperl : I'd suggest changing two of the prominently featured grey boxes. 

Change:

  Dart webdev
  Build browser apps.

to:

  Web
  Build browser apps.

and:

  Dart VM
  Build scripts, servers.

to:

  Command-line
  Build scripts, servers.

**Comment by Sfshaza** [comment]
@anders-sandholm @filiph @kwalrath 

This has been languishing because we didn't reach consensus. Should we schedule a meeting to discuss?

**Comment by filiph** [comment]
Happy to meet!

FWIW I agree with the changes (sorry for taking so long to reply).

**Comment by srawlins** [comment]
"Webdev" has changed to "Web", but "Dart VM" has not yet been changed to "Command-line"

**Comment by chalin** [comment]
Has a consensus been reached?

The _What next?_ section of the [Get Started](https://www.dartlang.org/guides/get-started) page currently refers to the platforms as **_Mobile_**, **_Web_**, and **_Server_**:

> <img width="420" alt="screen shot 2018-06-24 at 11 25 21" src="https://user-images.githubusercontent.com/4140793/41820544-57cdeea2-77a1-11e8-9cf6-d9b56fdd8436.png">

Given the "client-optimized" focus for Dart, it seems most reasonable (and complementary) to refer to the other platform as _Server_ rather than just command-line.

Thoughts?

cc @kevmoo

**Comment by anders-sandholm** [comment]
I'd like to propose - as I believe Patrice also suggests above - that we remain consistent (with the What next) and rename "Dart VM" to "Server" on the platform page as well (and keep the existing subtitle "Write a command-line app or server").

**Comment by chalin** [comment]
Sounds good. Whatever terminology we settle on, we should be consistent across pages:

- [ ] [Get Started page](https://www.dartlang.org/guides/get-started)
- [ ] [Platforms page](https://www.dartlang.org/guides/platforms)
- [ ] Sidenav - all pages (when viewed from wide displays) other than the front page.

Should we be changing the `/dart-vm` URLS to be `/server` (with appropriate redirects, of course)?

**Comment by anders-sandholm** [comment]
Happy for us to use 'Server' or 'server-side app' depending on context. 
Changing the URLs is not necessary (and higher risk, I guess), but probably a nice thing to do as well while we're at it.

**Comment by chalin** [comment]
Closing this issue since it has been addressed. Followup actions will be tracked via #965.
