### ISSUE TITLE
Comparing Generics doesn't work with Collections

### ISSUE THREAD

**Issue by nosmirck** [dart-lang/site-www#2461]
When trying to Compare Generics with types, it works as expected, example:

```dart
void foo<T>(){
  if(T == int) print('this is an int!');
  if(T == double) print('this is a double!');
  if(T == String) print('this is a String!');
  if(T == List) print('this is a List!');
}
```

But when comparing with other types like List<int> it breaks.

```dart
void foo<T>(){
   if(T == List<int>) print('this is a List<int>!');
}
```

With the following Errors:

```diff
-Error: A comparison expression can't be an operand of another comparison expression.
-  if (T == List<int>) return 'str' as T;
-                   ^
-main.dart:13:21:
-Error: Expected an identifier, but got ')'.
-  if (T == List<int>) return 'str' as T;
-                    ^
-main.dart:13:16:
-Error: The operator '<' isn't defined for the class 'Type'.
- - 'Type' is from 'dart:core'.
-  if (T == List<int>) return 'str' as T;
-               ^
```

**Comment by kwalrath** [comment]
@leafpetersen should this work?

**Comment by leafpetersen** [comment]
No.  This is a parsing restriction that goes back to Dart 1.  You can't use `List<T>` (or other generic class instantiations) as a type Object.  You can work around this parsing restriction by defining a function `Type typeObject<T>() => T` and comparing `T == typeObject<T>()`.

**Comment by nosmirck** [comment]
@leafpetersen thank you very much! That worked!

I managed to work around it in a naive way doing:
`if(<int>[] is T) print('foo got a List of int');`

But your solution is much better!!

Sadly, I can't use it as I originally intended using a switch statement like this (can't use mine neither):

```dart
void main() {
  foo<int>();
  foo<List<int>>();
  foo<String>();
}

void foo<T>() {
  switch (T) {
    case String:
      print('foo got string');
      break;
    case int:
      print('foo got integer');
      break;
    case typeOf<List<int>>(): //doesn't work here
      print('foo got a list of integers');
      break;
    default:
      throw 'oh oh, cannot process $T';
  }
}

Type typeOf<T>() => T;

```

Because switch statements must have cases that resolve to const (either directly or a returned invocation) and it's not possible to do that with the typeOf<T>()

But I can happily use my if/else if statements otherwise, good and close enough to what I need!

By the way, maybe the method `Type typeOf<T>()` could be added to the language? Maybe it's too basic, but I think it would be useful to have it, maybe something better that works like it does in C#? Like if T is List<String> and I do typeOf(T) it returns List<String>.

Anyways, thanks for the help, in closing this now!
