### ISSUE TITLE
Followup changes for new /tools/experiment-flags page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2468]
As a followup to #2467, we should add that page to the sidenav and any other relevant page indexes. We might also add a version note about when `pub run` started supporting `--enable-experiment`.

Also, we should probably add that flag to the command pages (e.g. pub, dart).

**Comment by parlough** [comment]
We now link to this on the sidenav, from the `dart run` documentation, and we don't need a version note with support being there for multiple years now. Closing this.
