### ISSUE TITLE
'Debugging Dart web apps' page issue

### ISSUE THREAD

**Issue by 01abhishekjain** [dart-lang/site-www#2474]
Page URL: https://dart.dev/web/debugging.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/web/debugging.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
This document should also mention how to automatically break at start of user script, similar to node's `--inspect-brk` flag

**Comment by kwalrath** [comment]
@grouma can you tell us how you'd automatically break? thanks!
