### ISSUE TITLE
How to convert string to raw string in dart

### ISSUE THREAD

**Issue by Mahmud-CSE16** [dart-lang/site-www#2476]
I want to convert an existing string to raw string.

like,
String s = "Hello \n World"

I want to convert this s variable to raw string(I want to print exact  "Hello \n Wrold")

Thanks

**Comment by kwalrath** [comment]
I don't know the answer, offhand. Have you tried https://stackoverflow.com/tags/dart?

**Comment by Mahmud-CSE16** [comment]
> I don't know the answer, offhand. Have you tried https://stackoverflow.com/tags/dart?

yes but i can not get any answer. I need backslash(\) in output. I am trying to fetch string value from rest api. it have bunch of mathjax(latex) formula containing backslash.

**Comment by domesticmouse** [comment]
@Mahmud-CSE16 can you link to your StackOverflow question?

**Comment by Mahmud-CSE16** [comment]
> @Mahmud-CSE16 can you link to your StackOverflow question?

there have similar question but answer is not clear.
I ask the question in my way.
**here is the link:**
[https://stackoverflow.com/questions/62270974/how-to-convert-string-to-raw-sting-in-dart](https://stackoverflow.com/questions/62270974/how-to-convert-string-to-raw-sting-in-dart)

**Comment by kwalrath** [comment]
I'm going to close this, since it looks like your question is being answered on StackOverflow.
