### ISSUE TITLE
Add IIFE description

### ISSUE THREAD

**Issue by AAAbramenko** [dart-lang/site-www#2478]
Page URL: https://dart.dev/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Add info/description about Dart IIFE (immediately invoked function expression) support.
Learned about it from [here](https://medium.com/dartlang/3-cool-dart-patterns-6d8d9d3d8fb8).

**Comment by parlough** [comment]
This is very useful, especially in terms of initializing `late final` variables. Bumping up the priority.

**Comment by parlough** [comment]
For reference, IIFE is also a construct used in JS. MDN has some extensive docs with some shared motivation: https://developer.mozilla.org/en-US/docs/Glossary/IIFE

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/4613 which provides some extra details.
