### ISSUE TITLE
Open redirect in website

### ISSUE THREAD

**Issue by neutrinoguy** [dart-lang/site-www#248]
The site contains an open redirect due to a bug in the express-js framework. Maybe it can be used to redirect user to evil site.

Here are the headers
[![dart_open.png](https://s8.postimg.org/focv3qm11/dart_open.png)](https://postimg.org/image/chibk41kx/)

The original express-js issue : [Redirect to external website](https://github.com/expressjs/serve-static/issues/26) 
Updating the express-js/serve-static will fix it.
Thanks

**Comment by kwalrath** [comment]
Thanks very much for the report, @neutrinoguy. @filiph, what do you say? This would apply to the webdev & events sites, as well.

**Comment by filiph** [comment]
Thanks @neutrinoguy!

I don't think this is expressjs-related (we don't serve through expressjs -- we use Firebase). There might be some redirect rule that does this, though. I'll take a look ASAP.

**Comment by filiph** [comment]
FYI I created a bug report for Firebase. I think this is a bug on their side, since webdev.dartlang.org has the same issue and its redirect setup is minimal.

**Comment by neutrinoguy** [comment]
Hey @filiph have you got any updates on this? I still believe the issue lies in ExpressJS as I have seen many sites suffering from the same issue. Well lets see what Firebase team says on this.

Thanks

**Comment by filiph** [comment]
Hi, I think I ended up filing this as a bug it with the Firebase team. I don't have any actionable updates from them yet.

**Comment by neutrinoguy** [comment]
Hey @filiph the issue seems to be fixed now. I suggest to close this now.

Thanks you !

**Comment by kwalrath** [comment]
Thanks for checking, @neutrinoguy!
