### ISSUE TITLE
Bad URL in server homepage

### ISSUE THREAD

**Issue by vgazioglu** [dart-lang/site-www#2484]
Page URL: https://dart.dev/server/
Page source: https://github.com/dart-lang/site-www/tree/master/src/server/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

gRPC Quicstart HTML link is wrong. Must be

https://grpc.io/docs/languages/dart/quickstart/
not
https://grpc.io/docs/languages/dart.html/quickstart/

**Comment by kwalrath** [comment]
Thank you, @vgazioglu! This should be easy to fix by editing the page source in the GitHub UI. Any takers?

**Comment by nyvasilev11** [comment]
I wanna give a try on this.

**Comment by Lilymage** [comment]
Hi, I tried my first PR on this!
#eff53ef

**Comment by kwalrath** [comment]
> Hi, I tried my first PR on this!

Cool! Just to make sure you know, you can edit this file in the page source without even creating a local version of the site-www repo.

(Not that there's anything wrong with having the whole repo... but it isn't necessary for this typo fix.)

**Comment by Lilymage** [comment]
Hmm, I tried editing the page by clicking on the little pencil, but I got this note : 
" You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork Lilymage/site-www, so you can send a pull request. "
Is there something I am not doing right ?

**Comment by kwalrath** [comment]
Nope, you're doing it exactly right. Keep going!!

**Comment by Mihir-Bhasin** [comment]
can I also help in this

**Comment by Lilymage** [comment]
I changed the link in my repo and made a PR #2489 :)

**Comment by kwalrath** [comment]
> can I also help in this

@Lilymage already fixed this one, but you're welcome to make other doc fixes, @Mihir-Bhasin!

**Comment by Mihir-Bhasin** [comment]
Ok my pleasure thank you
