### ISSUE TITLE
Effective Dart should more strongly point away from `dynamic` arguments

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#2487]
https://dart.dev/guides/language/effective-dart/design#do-annotate-with-object-instead-of-dynamic-to-indicate-any-object-is-allowed

Usage has shifted since this was written. It is now more common to take `Object` for the "try to act like a type union" case. `dynamic` is reserved for when you do want runtime dynamic behavior.

This guideline should say to prefer `Object` always, not exclusively for the case where you want to express "This can be any Object".

cc @munificent

**Comment by kwalrath** [comment]
@munificent what do you say?

**Comment by matanlurey** [comment]
+1000. This seems consistent with TypeScript's use and of the `unknown` type:
https://mariusschulz.com/blog/the-unknown-type-in-typescript

**Comment by munificent** [comment]
Yes, I think this is a good change. I believe the ecosystem has moved since we originally added that guideline and now dynamic really means "I want complete dynamism".

**Comment by munificent** [comment]
Done: https://github.com/dart-lang/site-www/pull/2535
