### ISSUE TITLE
Add information about lazy initialization of global and static variables

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/site-www#2493]
It would be nice to add some words to the language tour about the fact that global and static variables are initialized lazy,

**Comment by kwalrath** [comment]
@leafpetersen wdyt?

**Comment by jamesderlin** [comment]
The language tour does state:

> ## Final and const
>
> [...] A final top-level or class variable is initialized the first time it’s used.

But this isn't quite accurate and seems somewhat misleading since it doesn't really have anything to do with the variable being `final` or not.
