### ISSUE TITLE
Site monitoring

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#25]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [amouravski@google.com](https://code.google.com/u/amouravski@google.com/) on April 10, 2013 04:29:56_

We need to know when api.dartlang.org, dartlang.org and pub.dartlang.org are not accessible.

_Original issue: http://code.google.com/p/dart/issues/detail?id=9818_

_Copied from original issue: dart-lang/www.dartlang.org#637_

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [sandholm@google.com](https://code.google.com/u/sandholm@google.com/) on April 10, 2013 05:09:40_

**Status:** Triaged  
  **Labels:** -Type-Defect Type-Enhancement Area-Site

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [sethladd@google.com](https://code.google.com/u/sethladd@google.com/) on November 26, 2013 10:25:07_

**Labels:** -Type-Enhancement Type-Task

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [sethladd@google.com](https://code.google.com/u/sethladd@google.com/) on November 26, 2013 10:38:06_

**Labels:** Milestone-Later

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kasperl@google.com](https://code.google.com/u/kasperl@google.com/) on July 10, 2014 03:20:32_

**Labels:** -Milestone-Later Oldschool-Milestone-Later

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kasperl@google.com](https://code.google.com/u/kasperl@google.com/) on August 04, 2014 00:43:01_

**Labels:** -Oldschool-Milestone-Later

**Comment by Sfshaza** [comment]
_From @kwalrath on July 21, 2016 21:35_

@filiph is working on something for www & webdev (& presumably events), possibly using http://www.stackdriver.com/, which is what pub.dartlang.org uses. (I don't know what api.dartlang.org uses, if anything.)

**Comment by kwalrath** [comment]
@filiph did anything ever come of this?

**Comment by parlough** [comment]
@khanhnwin Was any related tracking or monitoring implemented internally for the Dart and Flutter websites? Do we need any work here with that or simply due to the nature of Firebase? Let me know if we can close this. Thanks!

**Comment by parlough** [comment]
Sounds like this isn't something needed with the current Firebase setup then. I'm going to close this, but if someone feels this is needed, feel free to open a new issue. Thanks all!
