### ISSUE TITLE
Should be easier to see highlights in code

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2502]
I don't know when this happened, but I no longer notice highlighted code because the yellow highlight is too close to the grey background. Here's an example from https://dart.dev/tools/diagnostic-messages#abstract_super_member_reference:

![image](https://user-images.githubusercontent.com/2164483/86067001-920cec00-ba28-11ea-9b69-124b9d36f98d.png)

In line 5, the second to last character is highlighted, but that's easy to miss.

**Comment by habeckmatt** [comment]
Hey, is this up for grabs?

**Comment by kwalrath** [comment]
> Hey, is this up for grabs?

Yes! Consider it yours!

**Comment by kwalrath** [comment]
Oh wait... looks like someone else has already grabbed it, @habeckmatt. :) Let me take a look at @doctorbracewell's work.

**Comment by DoctorBracewell** [comment]
Oh! Sorry @habeckmatt , I don't know how I missed your comment. Sorry :(.
It was actually in dart-lang/site-shard, check https://github.com/dart-lang/site-shared/pull/120

**Comment by kwalrath** [comment]
I happened to be looking through all the code samples I can find, and here are 2 places that exemplify highlighting:

* https://dart.dev/guides/language/language-tour#metadata (`@deprecated` in the first code block)
* https://dart.dev/guides/language/effective-dart/usage#prefer-asyncawait-over-using-raw-futures (`async` and `await` in the "good" code block)

The highlighting is much more visible on the greenish background than it is on the light gray background.

**Comment by NinaPacifier** [comment]
Hey, @kwalrath  May I work on this issue???

**Comment by kwalrath** [comment]
Looks like this was fixed by https://github.com/dart-lang/site-shared/pull/120.
