### ISSUE TITLE
'dart (Dart VM)' page issue

### ISSUE THREAD

**Issue by zeyadsharo** [dart-lang/site-www#2505]
$ flutter new app
Setting VM flags failed: Unrecognized flags: disable-dart-dev
![image](https://user-images.githubusercontent.com/33178745/86105318-dac7b200-bac7-11ea-99ab-a3f5d32584bc.png)

**Comment by zeyadsharo** [comment]
#

> ###

**Comment by domesticmouse** [comment]
Hey @zeyadsharo, I'm guessing you are attempting to run flutter under [MINGW64](http://mingw-w64.org/doku.php)?

**Comment by zeyadsharo** [comment]
> Hey @zeyadsharo, I'm guessing you are attempting to run flutter under [MINGW64](http://mingw-w64.org/doku.php)?

i don't know but i tried to use flutter web i gets this issue

**Comment by kwalrath** [comment]
I'm going to close this, since we don't cover Flutter on this site. I'd suggest getting help via the Flutter community: https://flutter.dev/community. (Maybe the Flutter Community Slack?) Good luck, @zeyadsharo!
