### ISSUE TITLE
'Sound null safety' page: how to try (or not) for Flutter

### ISSUE THREAD

**Issue by jonmountjoy** [dart-lang/site-www#2512]
Page URL: https://dart.dev/null-safety/
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/index.md

Description of issue:

Many people use Dart to develop Flutter apps.

This documentation page doesn't make it clear how to use the latest Dart and its sound null safety, in Flutter apps.  
Doing so may result in a lot more usage of the feature.

**Comment by kwalrath** [comment]
You can't yet use the feature with Flutter. We could be much clearer about this.

**Comment by zhesha** [comment]
There is "Important" section with text: "Because null safety is still in tech preview, don’t use null safety in production code.". I think flutter can be mentioned here as well. For example: "Also, as Flutter uses stable version of Dart, null safety not yet available in Flutter"

**Comment by jonmountjoy** [comment]
FWIW, I installed the beta channel of Flutter, thinking it would be there too, so perhaps don't say "as Flutter uses stable version...".

**Comment by kwalrath** [comment]
> FWIW, I installed the beta channel of Flutter, thinking it would be there too, so perhaps don't say "as Flutter uses stable version...".

I'm not sure I can guarantee what version of Dart Flutter uses... What really matters is that the Flutter libraries haven't been converted yet.
