### ISSUE TITLE
'dart2native' isn't exist with the dart sdk

### ISSUE THREAD

**Issue by A-freedom** [dart-lang/site-www#2514]
Hi I'm on Ubuntu 20.04 LTS and I have 'Dart Sdk'  installed on my computer and It is run just fine but dart2native isn't exist 

```
➜  ~ dart
dart          dartanalyzer  dartdoc                               
dart2js       dartdevc      dartfmt                               
```
```
➜  bin git:(stable) cd /home/max/Android/flutter/bin/cache/dart-sdk/bin/
➜  bin git:(stable) ls
dart  dart2js  dartanalyzer  dartdevc  dartdoc  dartfmt  model  pub  resources  snapshots
➜  bin git:(stable) 
```

for some reason or another, dart2native isn't existed, I had tried to reinstall it from different sources and still this same  result

**Comment by kwalrath** [comment]
I believe that dart2native isn't included in the Flutter SDK. You'll need to download the Dart SDK separately.
