### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by manosrenieris** [dart-lang/site-www#2518]
URL:  https://www.dartlang.org/docs/tutorials/fetchdata/
Linkedfrom: https://api.dart.dev/stable/2.8.4/dart-html/HttpRequest-class.html
Expected page:  Possibly https://dart.dev/tutorials/web/fetch-data

**Comment by zhesha** [comment]
The link is under the "Other resources" section(first link), link title is "Fetch Data Dynamically" and description is "a tutorial from A Game of Darts, shows two different ways to use HttpRequest to get a JSON file." and it fails with 404.
Interesting that next link says "Get Input from a Form, another tutorial from A Game of Darts, shows using HttpRequest with a custom server." and in links to https://angulardart.dev/guide/forms and not to "A Game of Darts" and there is nothing about HttpRequest, so I think it wrong as well.
I don't know what is "A Game of Darts" so I am not sure is it possible to fix them, maybe just remove?

**Comment by zhesha** [comment]
Also, the issue should be moved to "dart-lang/sdk", as an API page generated from comments in code. I can create PR to fix this, but I'm not sure is simply removing these two links is good enough. Also, we can add a link to https://dart.dev/tutorials/web/fetch-data, as it has some explanation about HttpRequest.

**Comment by kwalrath** [comment]
Thanks for the report, @manosrenieris, and for the analysis, @zhesha.

I think we should update the API doc comments (dart-lang/sdk) *and* add a redirect on site-www to fetch-data.

**Comment by zhesha** [comment]
@kwalrath I want help, but I am not sure how. I think we should remove two links to "tutorial from A Game of Darts" because there is no such tutorial. And add a new link to https://dart.dev/tutorials/web/fetch-data. If I'm right I will create PR tomorrow. If you need more time to investigate how to change these links, I'll wait.

**Comment by kwalrath** [comment]
I'm not actually sure how to modify the API docs at the moment, but it should be possible via a dart-lang/sdk PR (cc me!). As to creating a redirect, you'd do that by adding an entry to the long list in https://github.com/dart-lang/site-www/blob/master/firebase.json.

**Comment by kwalrath** [comment]
As for "A Game of Darts", it's just the old name for the Dart tutorials. The equivalent today would be https://dart.dev/tutorials.

**Comment by zhesha** [comment]
@kwalrath I have created PR to dart-lang/sdk, and it already merged.
Here is a change to file with redirects https://github.com/dart-lang/site-www/compare/master...zhesha:patch-1
Can you accept this change and can we update API docs from dart-lang/sdk comments, as they are updated?

**Comment by kwalrath** [comment]
Thank you, @zhesha! Your change looks good, except that the URL should be a host-agnostic path. Could you create a PR for the change? (I could, but then you wouldn't get credit.)

```
BEFORE:
      { "source": "/docs/tutorials/fetchdata", "destination": "https://dart.dev/tutorials/web/fetch-data", "type": 301 },
 
AFTER:
      { "source": "/docs/tutorials/fetchdata", "destination": "/tutorials/web/fetch-data", "type": 301 },
```

**Comment by zhesha** [comment]
I have created the right patch https://github.com/dart-lang/site-www/compare/master...zhesha:patch-2 . But I don't have a button to close the previous one. Also, as I can see there are some changes in API docs comments in dart-lang/sdk repo, so will you regenerate API doc section on site?

**Comment by kwalrath** [comment]
The API doc gets regenerated automatically, but it takes a while for changes to make their way to the stable channel. You can check out the latest generated docs by going to the `be` (bleeding edge) docs:

https://api.dart.dev/be/dart-html/HttpRequest-class.html
