### ISSUE TITLE
Update documentation for Windows pub cache location to from APPDATA  to LOCALAPPDATA

### ISSUE THREAD

**Issue by jmagman** [dart-lang/site-www#2526]
https://github.com/dart-lang/pub/pull/2297 changed the default pub cache path on Windows to `%LOCALAPPDATA%\Pub\Cache`
Update documentation still referring to `%APPDATA%`:
- https://dart.dev/tools/pub/environment-variables
- https://dart.dev/tools/pub/cmd/pub-get#the-system-package-cache

https://github.com/dart-lang/site-www/search?q=APPDATA&unscoped_q=APPDATA

**Comment by kwalrath** [comment]
Thanks, @jmagman! Do you want to fix this, or shall I open it up to the community?

**Comment by jmagman** [comment]
@kwalrath https://github.com/dart-lang/site-www/pull/2527
