### ISSUE TITLE
Update serialization article

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#253]
To fix https://github.com/dart-lang/site-www/issues/251, I added a note to the [serialization article](https://www.dartlang.org/articles/libraries/serialization). But it would be nice to actually update the article.

**Comment by parlough** [comment]
This article hasn't existed for a long time, so I'm going to close this. If someone wants to see a new serialization article, beyond expanded JSON documentation (tracked in https://github.com/dart-lang/site-www/issues/4286), feel free to open a new issue.
