### ISSUE TITLE
'The pub tool' page issue

### ISSUE THREAD

**Issue by Thwaltaraung** [dart-lang/site-www#2534]
Page URL: https://dart.dev/tools/pub/cmd/
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/cmd/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
No issue listed. Closing.
