### ISSUE TITLE
 Solution fails -- Codelab: Asynchronous programming: futures, async, await. 

### ISSUE THREAD

**Issue by xpat** [dart-lang/site-www#2539]
I got the following error messages when I ran the solution on the first exercise:

Part 1 Test failed! Did you forget to implement or return from reportUserRole?
Part 2 Test failed! Did you forget to implement or return from reportLogins?

They're the hints, right?  Why do they appear when I run the solution?

**Comment by sfshaza2** [comment]
@johnpryan, can you weigh in?

**Comment by johnpryan** [comment]
It sounds like you might be viewing the solution, but haven't copied the code into the "Dart" tab. 

We might consider changing the behavior of DartPad to run the solution when it's selected.

**Comment by xpat** [comment]
Sure enough, when I run the solution from the Dart tab I get the message:  All tests passed!

Thumbs up on this idea:
> We might consider changing the behavior of DartPad to run the solution when it's selected.

@johnpryan @sfshaza2 Thank you both for your follow-up.
