### ISSUE TITLE
Content on migrating existing code to null safety

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#2540]
Placeholder for now

Should cover the migration tool, how to think about dependencies, running tests, SDK constraint, etc etc

CC @sfshaza2 @kwalrath

**Comment by sfshaza2** [comment]
Thanks for setting this up, @kevmoo! I figure we can use this bug as a meta bug for the changes needed.

**Comment by mit-mit** [comment]
I think we should move this to the beta milestone, WDYT @kwalrath @kevmoo ?

**Comment by kevmoo** [comment]
SGTM – although let's talk about it tomorrow, @mit-mit

**Comment by pcsosinski** [comment]
what's blocking this currently?

**Comment by sfshaza2** [comment]
Creating a new page? Nothing. Kathy volunteered to do it yesterday afternoon.

**Comment by mit-mit** [comment]
I think @pcsosinski is asking since @kwalrath added the 'blocked' tag

**Comment by kwalrath** [comment]
Actual content is blocked on Flutter being ready for people to try null-safety migration.
