### ISSUE TITLE
Diagnostic messages documentation not rendering links correctly

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/site-www#2541]
The diagnostic messages documentation contains links, but those links are appearing as HTML tags.

For an example, look at https://dart.dev/tools/diagnostic-messages#unchecked_use_of_nullable_value and notice the explicit HTML text `<a href=` (and following) in the doc. The link is in the markdown version of the documentation and is not escaped. This should have been rendered as a link, so I'm guessing that we're escaping the characters later on.

We either need to not escape HTML that's in the markdown file or we need to update the generation of the markdown file to produce something that will be interpreted correctly.

**Comment by sfshaza2** [comment]
Yes that's an oopsie. I see 5 hrefs on that page.

**Comment by kwalrath** [comment]
We should use markdown link format, like we do for `[constant context]`. Actually, we can improve the constant context links, too... I'll create a PR.
