### ISSUE TITLE
Font size too small on print => long line lengths

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#2543]
When printing a beautiful but lengthy document like the null safety article from @munificent, the text is very small on letter and A4 paper, which results in long line lengths. There is a sizeable body of published research on line length and readability; while it comes to varying conclusions as to the optimum, our default here (150 characters) is over double the recommendations that I've encountered. 

The attached PDF demonstrates this.
[Understanding null safety BEFORE.pdf](https://github.com/dart-lang/site-www/files/4973947/Understanding.null.safety.BEFORE.pdf)

A simple fix would be to add a media query to increase the font size. Something like this should do the trick:
```css
@media print {
   body {
      font-size: 1rem
   }
   pre {
      font-size: 0.85rem
   }
}
```

Manually adjusting the document with these settings results in this, which is significantly better:
[Understanding null safety AFTER.pdf](https://github.com/dart-lang/site-www/files/4973950/Understanding.null.safety.AFTER.pdf)

Thoughts?

**Comment by munificent** [comment]
I actually find the font a little painfully small even on a desktop web browser.

**Comment by sfshaza2** [comment]
Me too!

**Comment by kwalrath** [comment]
Related: #2319

**Comment by kwalrath** [comment]
If someone would like to give us a PR for the print fonts, I'd happily test and accept it.

**Comment by parlough** [comment]
I'm going to close this as fixed by https://github.com/dart-lang/site-www/commit/63393923a1854289bb37e4919a37ec294d2ae887 which saw the font sizes and font weight increased across the site.
