### ISSUE TITLE
Add link to `Never` for methods that never return in summary of 'Understanding Null Safety'

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/site-www#2545]
In this section of the null safety doc (https://dart.dev/null-safety/understanding-null-safety#top-and-bottom), in the last bullet item, consider mentioning one use case for `Never`: using it as a return type on methods that never return. The analyzer now uses that as being equivalent to the `alwaysThrows` annotation from `package:meta`, and it would be nice to eventually remove the annotation and stop supporting it.

**Comment by bwilkerson** [comment]
@munificent

**Comment by bwilkerson** [comment]
Or add a forward pointer to "Never for unreachable code".

**Comment by atsansone** [comment]
@munificent : Is this still needed with Dart 3?

**Comment by munificent** [comment]
I don't know about *needed*, but, yes, it is still a valid use case for `Never` to use it as the return type for a function that never actually returns. For example, `dart:io`'s `exit()` function which abort the process, or any function that unconditionally throws. (This is why the `Never` type is called that: it's the type for functions and expressions that never yield a value.)
