### ISSUE TITLE
"Understanding null safety" should label each figure or snippet as with or w/o null safety

### ISSUE THREAD

**Issue by dkwingsmt** [dart-lang/site-www#2546]
There are a lot of figure or snippets in this article (great!), but it's unclear whether the figure or snippet is before or after the change without carefully reading the context, which might be misleading when a reader is skimming through the article. I suggest labeling each of them clearly, or at least those that are compared side-by-side.

**Comment by sfshaza2** [comment]
Good idea!

**Comment by kwalrath** [comment]
@munificent are you interested in taking this on?

**Comment by munificent** [comment]
Happy to!

**Comment by kwalrath** [comment]
Thanks, @munificent!
