### ISSUE TITLE
Discuss language versioning

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#2554]
Pages like https://dart.dev/guides/language/extension-methods talk about how the feature was added in `2.7` but doesn't discuss how to set up the pubspec.yaml for this feature

```yaml

environment:
  sdk: '>=2.7.0 <3.0.0'
```

We should document that. 

We should also (Perhaps) discuss how using experimental features also requires aligning with language versioning and link to https://dart.dev/tools/experiment-flags

See

https://github.com/dart-lang/sdk/blob/master/tools/experimental_features.yaml
and
https://github.com/dart-lang/sdk/blob/master/docs/process/language-versions-and-experiments.md

**Comment by kwalrath** [comment]
Do we really need a separate page/section for language versioning, or could we just point people to https://dart.dev/tools/pub/pubspec#sdk-constraints from everywhere that requires a minimum SDK version?

I guess I'm asking whether "language versioning" is an important thing to present to average Dart developers, or whether "minimum SDK" is all they really need to know.

**Comment by leafpetersen** [comment]
Seems to me that there should be some basic documentation that explains that:
  - New language features (breaking or non-breaking) are not available unless opted into
  - Opting in is done by setting the min sdk constraint
  - Possibly a table showing what language features are enabled by what version (this requires maintenance work)

**Comment by kwalrath** [comment]
We have a page (https://dart.dev/guides/language/evolution) that could be a natural home for all this info. I think the table could be very useful, I'm willing to maintain it, and updating this page is already on our release checklist.

/cc @mit-mit

**Comment by mit-mit** [comment]
Combining it with that SGTM.

When we document this, should also mention this analyzer message that developers will likely see:
<img width="675" alt="Screenshot 2020-08-17 at 09 32 32" src="https://user-images.githubusercontent.com/13644170/90369765-99399900-e06c-11ea-9172-a9df65cd5099.png">

**Comment by kwalrath** [comment]
@munificent wrote a bunch about language versioning in this PR: #2628

**Comment by kwalrath** [comment]
We've added the language versioning info to the evolution page (https://dart.dev/guides/language/evolution#language-versioning) in #2696. Leaving this bug open to make sure we cover everything we need to.

**Comment by kwalrath** [comment]
Done! We probably want to move the Per-library language version selection section out of the evolution page, but that's tracked by #2766.
