### ISSUE TITLE
Get started: command-line and server apps tutorial has incorrect (?) paths after stagehand console-full 

### ISSUE THREAD

**Issue by andy7809** [dart-lang/site-www#2558]
The command-line and server apps tutorials here recommend creating a directory `cli`. Then, running `stagehand console-full` in `cli` results in the following files being written (I think):

  ```
  cli/.gitignore
  cli/CHANGELOG.md
  cli/README.md
  cli/analysis_options.yaml
  cli/bin/cli.dart
  cli/lib/cli.dart
  cli/pubspec.yaml
  cli/test/cli_test.dart
```
In step 6, the tutorial recommends running `dart bin/main.dart` to run the starter app. Shouldn't this instead be `dart bin/cli.dart`?

Did I do the tutorial wrong?

**Comment by andy7809** [comment]
I have changed the `dart bin/main.dart` instances to `dart bin/cli.dart` locally, but I wanted to get some feedback before I opened a PR or anything. Am I doing this right?

Thanks for your viewing patience, I'm just an intern trying to learn some dart before the end of the summer :)

**Comment by kwalrath** [comment]
What you're doing sounds right. I suspect that the template started producing different names quite a while ago, and you're just the first person to report this issue.

**Comment by kwalrath** [comment]
We'd love it if you created a PR, so I've assigned this to you. Thank you!!
