### ISSUE TITLE
Proposal: Display "Subscribe"/"Follow us" prominently

### ISSUE THREAD

**Issue by filiph** [dart-lang/site-www#256]
I'd like to test this hypothesis of mine:

> We have a bunch of dartlang.org visitors that are intrigued by what they're seeing, but not intrigued _enough_ to install the SDK (maybe they read on mobile, maybe they don't have time, maybe they need more 'shopping around' first).

If that's true, adding a low-barrier action might help get some of these people to come back later. Most sites do this by asking people to join mailing lists and follow social media accounts. I'm open to other suggestions as well.

Destination URLs:

* [Subscribe to newsletter](https://feedburner.google.com/fb/a/mailverify?uri=dartlang/uusT&amp;loc=en_US) -- mails from news.dartlang.org articles
* [Follow us on Twitter](https://twitter.com/dart_lang)
* [Follow us on G+](https://plus.google.com/+dartlang)

Placement:

* After some pondering, I don't think it's a good idea to place the button on the homepage. It would be easier to find, but the relevance is kind of slow.
* On the other hand, it should be visible and accessible from most subsequent pages. Especially as a 'safety net' for Getting started.
* It can't be just tucked away somewhere in the footer where nobody will ever look unless they're _really_ searching for something.
* [A] It can be part of the top bar.
  * This would require it to be bitesized, probably just one icon + one word.
* [B] It can be part of the left nav bar.
  * A little more space.
  * But already cluttered a lot.
* [C] It can be at the end of every article, _above_ the footer.
  * Can be a full-scale button (or more). Doesn't clutter anything. Right in the path of the eye.
  * Not easy to find when you come subscribe.

Design implementation:

* This will depend on the placement, but it needs to stand out by color and be a button (can't be just a link).

I'd like to have your opinion, @kwalrath and @lukechurch.

**Comment by kwalrath** [comment]
I'd be inclined to put an icon with a tooltip in the top bar. (Although I suppose a tooltip isn't terribly mobile friendly, we could have an in-between page/dialog that explains things.)

**Comment by kwalrath** [comment]
I'm very willing to help, but I'd like input from @lukechurch first.

**Comment by kwalrath** [comment]
Maybe @inmatrix or @galeyang has an opinion?
