### ISSUE TITLE
How to forward on the diagnostic messages page

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/site-www#2569]
The diagnostic messages page (https://dart.dev/tools/diagnostic-messages) uses anchors whose names match the names of the diagnostics. We now have a case where we would like to rename one of the diagnostics that has documentation on that page.

The problem is that if we rename the diagnostic from `a` to `b`, the analysis server in newer versions of the SDK will produce a link containing `#b` while the analysis server in earlier versions of the SDK will continue to produce a link containing `#a`, and updating the page so that this anchor doesn't exist will cause broken links.

How can we best set up forwarding such that an attempt to access `https://dart.dev/tools/diagnostic-messages#a` will forward to `https://dart.dev/tools/diagnostic-messages#b`?

**Comment by kwalrath** [comment]
The most straightforward, lowest tech possibility is to just put a manual forward in the page. Something like this:

```
## a

This message has changed to [b](#b).
```

Another possibility is to add an anchor tag to b, but that risks confusing users.

**Comment by bwilkerson** [comment]
> ... but that risks confusing users.

I hadn't considered that aspect.

> ... put a manual forward in the page.

How about just
```
## a

See [b](#b).
```

Would it be ok (or even preferable) for all of those to be at the end of the page?

**Comment by kwalrath** [comment]
> Would it be ok (or even preferable) for all of those to be at the end of the page?

Yes, end of page makes sense to me.

**Comment by bwilkerson** [comment]
Ok, thanks! I've updated my CL to include the forwarding section in case you're interested (https://dart-review.googlesource.com/c/sdk/+/157921).
