### ISSUE TITLE
'Extension methods' page issue

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#2572]
Page URL: https://dart.dev/guides/language/extension-methods
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/extension-methods.md

![image](https://user-images.githubusercontent.com/40364434/89931575-a558cd00-dc0c-11ea-9108-94af80b6ffb5.png)

`Feature specification` link is broken.

**Comment by kwalrath** [comment]
Thanks for letting us know! If someone wants to grab this, it should be an easy fix.

Old URL: https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md#dart-static-extension-methods-design 
New URL: https://github.com/dart-lang/language/blob/master/accepted/2.7/static-extension-methods/feature-specification.md#dart-static-extension-methods-design

(Change 2.6 to 2.7)

**Comment by LifeofDan-EL** [comment]
I would like to work on it. Can I be assigned that?

**Comment by LifeofDan-EL** [comment]
Made a PR https://github.com/dart-lang/site-www/pull/2573
