### ISSUE TITLE
Test homepage DartPad code

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2578]
The upgrade to jekyll (#2570) caused a problem that is making us stop using code-excerpt in the homepage. This means that the code displayed in the embedded DartPad won't be auto-included/tested. Once #2570 and #2575 are in, we should reimplement #2124 in a way that works with the new jekyll.

/cc @johnpryan @theacodes

**Comment by atsansone** [comment]
@parlough : Is this still a concern?

**Comment by parlough** [comment]
Yes this is still a concern.
