### ISSUE TITLE
Change Effective Dart when "bad" code doesn't pass analysis

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2580]
#2575 fixed the build, partly by removing test code that no longer passes analysis. Two occurrences were in Effective Dart:

* https://dart.dev/guides/language/effective-dart/design#do-annotate-when-dart-infers-the-wrong-type ([diff](https://github.com/dart-lang/site-www/pull/2575/files/ef7995c200ec41622cc12ce6a7eb1e24117824be#diff-b95ea59d5bd24841b41baee2745469d7))
* https://dart.dev/guides/language/effective-dart/usage#do-initialize-fields-at-their-declaration-when-possible ([diff](https://github.com/dart-lang/site-www/pull/2575/files/ef7995c200ec41622cc12ce6a7eb1e24117824be#diff-e1df7aee84d572a5d2aeea1fd3eb38f8))

Can we produce valid "bad" code for both of these rules, or should we alter/delete the rule?

**Comment by johnpryan** [comment]
Just a drive-by comment, but in that first example, the good and bad snippets are exactly the same.

**Comment by kwalrath** [comment]
> Just a drive-by comment, but in that first example, the good and bad snippets are exactly the same.

Looks like it's been that way since #889. What the heck?

**Comment by munificent** [comment]
> Just a drive-by comment, but in that first example, the good and bad snippets are exactly the same.

Not *exactly* the same. In the good example, `highest` is declared using `num` and in the bad example, it's `var`.

For the second one, I think removing `final` from both the good and bad examples should fix it:

```dart
// Bad:
class Folder {
  final String name;
  List<Document> contents;

  Folder(this.name) : contents = [];
  Folder.temp() : name = 'temporary'; // Oops! Forgot contents.
}

// Good:
class Folder {
  final String name;
  List<Document> contents = [];

  Folder(this.name);
  Folder.temp() : name = 'temporary';
}
```
