### ISSUE TITLE
Fix `runTwice` function for Dart 2.9  in DartPad samples on homepage

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#2581]
Since https://github.com/dart-lang/site-www/pull/2574 was merged, we need to apply [this change](https://github.com/dart-lang/site-www/pull/2575/files#diff-1528efe58227b3be77486de58b4e8c6dR10) to the snippet in dartpad_picker_main.js:

**Comment by kwalrath** [comment]
I didn't notice you were assigned and tried to do this myself... ./compile[_dev].sh didn't work for me, though.

**Comment by johnpryan** [comment]
The bash scripts both worked for me with Dart 2.9.2, do you have any console output?

I created a PR to address this issue: https://github.com/dart-lang/site-www/pull/2683
