### ISSUE TITLE
'Nullability and Generics' example needs adjustment

### ISSUE THREAD

**Issue by eernstg** [dart-lang/site-www#2583]
Thanks to @dark-chocolate for noticing this, cf. https://github.com/dart-lang/sdk/issues/43069#issue-680165596. The section https://dart.dev/null-safety/understanding-null-safety#nullability-and-generics should be adjusted. It says that the following example is OK:

```dart
// Using null safety:
class Box<T> {
  final T? object;
  Box.empty();
  Box.full(this.object);
}
```

However, it is actually a compile-time error for a generative constructor like `Box.empty` to fail to initialize `object`. It could do it in an initializer list: `Box.empty(): object = null;`, but that doesn't fit the associated text ('it is fine to leave it uninitialized').

Maybe `object` shouldn't be final? In that case it is in fact OK to leave it uninitialized.

**Comment by dark-chocolate** [comment]
Sir, please correct me if I'm wrong.

The field `object` can have a value of `null` so it is fine to leave it uninitialised, and hence the above code should be OK. But just because it won't give us an idea whether the user actually forgot to initialise the field `object` or he wants `object` to have a value of `null`, Dart should give a compile time error. It's done to improve code maintainability or readability right?

**Comment by eernstg** [comment]
Exactly. The rule in the language specification that requires final instance variables to be initialized by each generative constructor (or by an initializing expression in the declaration itself) is [here](https://github.com/dart-lang/language/blob/b9017651a340cc5b26b1b814782374b1932d446b/specification/dartLangSpec.tex#L3247).

It would not be unsound to allow such a final instance variable with a nullable type to be implicitly initialized to null, but we never allowed that for final instance variables (it was also an error before null safety). The point is that a final instance variable should have a value which is meaningful (because you can't "correct" the value later on), and hence it would be too error prone to allow it to have the value null just because we forgot to initialize it in one of those constructors.

So, in the end, the code is not OK, it's a compile-time error. But that error is motivated by software engineering correctness/readability concerns, not by soundness.

**Comment by munificent** [comment]
Yes, this was a mistake on my part. We could either provide an initializer in Box.empty() or make the field non-final. I lean slightly towards the latter since it leaves the prose alone. So:

```dart
// Using null safety:
class Box<T> {
  T? object;
  Box.empty();
  Box.full(this.object);
}
```
