### ISSUE TITLE
'Understanding null safety' page issue

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/site-www#2586]
Page URL: https://dart.dev/null-safety/understanding-null-safety/
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/understanding-null-safety/index.md

Description of issue:

https://dart.dev/null-safety/understanding-null-safety#null-assertion-operator has an example:

```dart
// Using null safety, incorrectly:
class HttpResponse {
  final int code;
  final String? error;

  HttpResponse.ok() : code = 200;
  HttpResponse.notFound()
      : code = 404,
        error = "Not found";

  String toString() {
    if (code == 200) return "OK";
    return "ERROR $code ${error.toUpperCase()}";
  }
}
```

The `HttpResponse.ok` constructor neglects to initialize the `error` member, which currently must be initialized because it is `final`.  I assume that we do still want to require explicit initialization `final` members even if they're nullable.

**Comment by kwalrath** [comment]
While we're in there, we should change the double quotes to single quotes, to match the style of other Dart code in the website.

**Comment by jamesderlin** [comment]
It's been [pointed out to me](https://stackoverflow.com/questions/63440051/why-a-final-field-should-be-initialised-when-it-is-made-nullable/63440535?noredirect=1#comment112268890_63440535) that https://dart.dev/null-safety/understanding-null-safety#nullability-and-generics also has:

```dart
// Using null safety:
class Box<T> {
  final T? object;
  Box.empty();
  Box.full(this.object);
}
```
and says:

> Note the `?` on the declaration of `object`. Now the field has an explicitly nullable type, so it is fine to leave it uninitialized.

So it seems that the intended behavior is to no longer require `final` fields to be initialized if they're nullable?  The above code doesn't work in https://nullsafety.dartpad.dev/ though.

**Comment by munificent** [comment]
These are both mistakes on my part. Final fields do need to be initialized even if nullable. I would change them to:

```dart
// Using null safety, incorrectly:
class HttpResponse {
  final int code;
  final String? error;

  HttpResponse.ok()
      : code = 200,
        error = null;
  HttpResponse.notFound()
      : code = 404,
        error = "Not found";

  String toString() {
    if (code == 200) return "OK";
    return "ERROR $code ${error.toUpperCase()}";
  }
}
```

And:

```dart
// Using null safety:
class Box<T> {
  final T? object;
  Box.empty() : object = null;
  Box.full(this.object);
}
```

Sorry about that!

**Comment by kwalrath** [comment]
> I'm very new to Github and don't know much about how to pull things here and there. I'll pick a page from docs, will make my changes and push it then to see if that got merged by you.

Sounds good.
 
> To be very honest with you, I've found that people working on Dart team are so much awesome (never raised any issue or consult any Flutter developer yet, but Dart team is really really awesome. 

It's great to hear that!
