### ISSUE TITLE
Update wording and docs on /cloud

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-www#259]
Related to https://github.com/dart-lang/server/issues/8, we need to update wording and docs re AppEngine as Martin's updates for the new Flex-oriented version of appengine package gets ready.

**Comment by Sfshaza** [comment]
Just to be clear, these docs don't live on www.dartlang. They live on a GitHub wiki:
https://dart-lang.github.io/server/

**Comment by Sfshaza** [comment]
I've updated the docs: http://dart-lang.github.io/server/google-cloud-platform/app-engine-flex/

Commit: https://github.com/dart-lang/server/commit/077d6ed9dd1dc3198abc8ff621db8388e2cf7e09

I have gotten minor feedback from Martin, which I've incorporated.

Commit:  https://github.com/dart-lang/server/commit/a42698f1f2527b553f97bb6bdec19c974ff2ae38

I'll wait to see if there's more feedback from @mkustermann or @kevmoo before closing.

**Comment by Sfshaza** [comment]
No further feedback. Closing.
