### ISSUE TITLE
Outdated instruction on DartPad page

### ISSUE THREAD

**Issue by tatsuyafujisaki** [dart-lang/site-www#2593]
Page URL: https://dart.dev/tools/dartpad#step-2-server
Page source: https://github.com/dart-lang/site-www/blob/master/src/tools/dartpad/index.md
Description of issue: The following instruction ...
```
2. Clear the Show web content checkbox, at the bottom right of DartPad.
The HTML and CSS tabs disappear.
```

... may not line up with the current DartPad.
![](https://user-images.githubusercontent.com/1838962/90995019-94895d80-e5f5-11ea-833e-7e63c0d59660.png)

**Comment by kwalrath** [comment]
Thank you for letting us know about this! I won't get to this for a few days, but I think a community member could easily fix this, so I've marked it **help wanted**.

**Comment by parzuko** [comment]
Can I take this issue?
