### ISSUE TITLE
move code_excerpt_framer.rb into site_shared

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#2594]
Since https://github.com/dart-lang/site-www/pull/2591, the file in flutter/website and dart-lang/sdk have diverged. This file should be moved to site_shared, and use a symlink instead.

**Comment by johnpryan** [comment]
https://github.com/dart-lang/site-shared/pull/121 has been merged, this symlink can be added now

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/pull/2600
