### ISSUE TITLE
The dartdoc docs should explain more about how to describe valid values for parameters

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#26]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [timarmst...@google.com](https://code.google.com/u/107468075128892442478/) on April 20, 2013 00:42:59_

I'm trying to write some doc comments and be consistent with the Dart best practices for writing them. I want to write which values are valid for a particular parameter in a function. Other doccomment systems have @param which is useful, but Dart doesn't seem to have this. We should better explain what to do in this case.

_Original issue: http://code.google.com/p/dart/issues/detail?id=10066_

_Copied from original issue: dart-lang/www.dartlang.org#654_

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [timarmst...@google.com](https://code.google.com/u/107468075128892442478/) on April 19, 2013 15:51:59_

**Labels:** -Type-Defect Type-Documentation

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [sandholm@google.com](https://code.google.com/u/sandholm@google.com/) on May 21, 2013 03:53:15_

**Labels:** Area-DartDoc

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on July 24, 2013 14:54:10_

This should probably go in http://www.dartlang.org/articles/doc-comment-guidelines/ .

**Labels:** -Type-Documentation -Area-DartDoc Docs-Articles Area-Documentation

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [amouravski@google.com](https://code.google.com/u/amouravski@google.com/) on October 08, 2013 10:17:54_

**Owner:** ---

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on October 08, 2013 10:38:44_

**Cc:** kathyw@google.com floitsch@google.com

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [sethladd@google.com](https://code.google.com/u/sethladd@google.com/) on December 04, 2013 12:22:39_

**Owner:** kathyw@google.com  
  **Cc:** -kathyw@google.com  
  **Labels:** -Priority-Medium Priority-Low

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [lrn@google.com](https://code.google.com/u/lrn@google.com/) on January 29, 2014 07:41:14_

**Labels:** Type-Enhancement

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 15:0_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on June 04, 2014 14:58:11_

**Labels:** -Area-Documentation Area-Site

**Comment by munificent** [comment]
Effective Dart already has:

[DO use prose to explain parameters, return values, and exceptions.](https://www.dartlang.org/guides/language/effective-dart/documentation#do-use-prose-to-explain-parameters-return-values-and-exceptions)

Is there anything more you want to add?

**Comment by munificent** [comment]
I think we're OK here.
