### ISSUE TITLE
Error displayed near the footer on the dart.dev website homepage

### ISSUE THREAD

**Issue by thearyanvijay** [dart-lang/site-www#2604]
<?code-excerpt replace=”/ *\/\/\s+ignore_for_file:[^\n]+\n//g; /(^	\n) *\/\/\s+ignore:[^\n]+\n/$1/g; /(\n[^\n]+) *\/\/\s+ignore:[^\n]+\n/$1\n/g”?>

![Screenshot 2020-08-30 at 4 07 04 AM](https://user-images.githubusercontent.com/70454372/91647300-f07d3780-ea76-11ea-9a36-614ca3b1d152.png)

**Comment by domesticmouse** [comment]
Can you please tell us your operating system make and revision, and your browser make and version. Thanks!

**Comment by thearyanvijay** [comment]
Apple MacBook Air
macOS Catalina 10.15.6

Browser: Chrome, Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by thearyanvijay** [comment]
Apple MacBook Air
macOS Catalina 10.15.6

Browser: Safari, Version 13.1.1 (15609.2.9.1.2)

**Comment by thearyanvijay** [comment]
![WhatsApp Image 2020-08-31 at 4 20 16 PM](https://user-images.githubusercontent.com/70454372/91712792-1b19de00-eba6-11ea-827a-c0ae0f71ce19.jpeg)


![WhatsApp Image 2020-08-31 at 4 21 03 PM](https://user-images.githubusercontent.com/70454372/91712804-240aaf80-eba6-11ea-9d41-ed118f7fe6f0.jpeg)

**Comment by kwalrath** [comment]
Oops, I see it too (though I have to select the empty area). This looks like a leftover of us converting from auto-included code to in-file code.
