### ISSUE TITLE
Remove server option from pub publish page

### ISSUE THREAD

**Issue by santitigaga** [dart-lang/site-www#2612]
Page URL: https://dart.dev/tools/pub/cmd/pub-lish.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/cmd/pub-lish.md

We need to remove the server discussion from this page.

-----
Original description of issue:

The task pub publish can´t add the option --server 
<img src="https://i.imgur.com/TZZyWae.png"/>

**Comment by kwalrath** [comment]
@jonasfj can you (or someone you know :) clarify the situation with the `--server` option, and whether it should be mentioned in https://dart.dev/tools/pub/cmd/pub-lish and the help?

**Comment by jonasfj** [comment]
This is a problem in `flutter_tool` wrapping `pub`.

You can do it with `flutter pub pub publish --server ...`, but this option isn't very useful, unless you're publishing to a server behind VPN as we don't have any authentication in place for this.

Another option is to use the `publish_to: <server>` in `pubspec.yaml`. Again, then authentication story for these is not good.

-------------------

I would be okay with not documenting this option on `dart.dev`, given that we don't have a good story with authentication for 3rd-party pub servers, I think it's reasonable that we don't document it too much.

Also there is afaik 3 ways to do this:
 * `pub publish --server <url>`,
 * `publish_to: <url>` in `pubspec.yaml`, and
 * `export PUB_HOSTED_URL=<url> && pub publish`.

Neither of these supports authentication, so users that do this typically rely on network security by being behind a VPN.

The situation is not ideal, there are issue for this: https://github.com/dart-lang/pub/issues/1381
