### ISSUE TITLE
Add a redirect for mocking-with-dart?

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#262]
An old StackOverflow article points to the removed Mocking With Dart article ([archived version](http://web.archive.org/web/20150402011242/https://www.dartlang.org/articles/mocking-with-dart/)).

Perhaps we should instead redirect /articles/mocking-with-dart to the mockito package: https://pub.dartlang.org/packages/mockito

**Comment by Sfshaza** [comment]
Duplicate of https://github.com/dart-lang/site-www/issues/249
