### ISSUE TITLE
Suggestion change 'Using class members code example' 

### ISSUE THREAD

**Issue by jonasjuni** [dart-lang/site-www#2627]
Hi, sorry for disturbing you guys but the code exemple shown on [Using class members](https://dart.dev/guides/language/language-tour#using-class-members) is a bit confusing, using the [Point](https://api.dart.dev/stable/2.9.2/dart-math/Point-class.html) class as an exemple give me an error because we can't assign another value to a final

```
// Set the value of the instance variable y.
p.y = 3; // The final variable 'y' can only be set once.
```

I know it isn't a big deal, but it'd nice to have an easy working example.
Cheers!

**Comment by kwalrath** [comment]
Thanks for the feedback! We do test the code, but sometimes we use shortcuts, and this looks like one of those cases. :/
