### ISSUE TITLE
Clarify usage of late

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2632]
See https://github.com/dart-lang/language/issues/1020#issuecomment-642941016

**Comment by mit-mit** [comment]
I think we should make this a P1 (it's a new keyword with the potential to make the code less verbose and more efficient). I also suggest we tag it on a null safety beta milestone.

**Comment by kwalrath** [comment]
#3008 contributes to addressing this issue.

**Comment by kwalrath** [comment]
Here's the new coverage we've published, so far:

* https://dart.dev/guides/language/language-tour_migrated#late-variables
* https://dart.dev/guides/language/effective-dart/usage_migrated#dont-use-late-when-a-constructor-initializer-list-will-do
* https://dart.dev/guides/language/effective-dart/design_migrated#avoid-public-late-final-fields-without-initializers
