### ISSUE TITLE
Document when, if ever, is it better to use a bool to check late initialization

### ISSUE THREAD

**Issue by dnfield** [dart-lang/site-www#2633]
I'm writing code where I will lazily initialize a cache field on my class.

I could make the variable `Foo? _cachedFoo;` or `late Foo _cachedFoo;` with a bool to track whether I've set it at least once.

Reading https://dart.dev/null-safety#creating-variables, it's not entirely clear to me whether either of these is preferable, but it seems like one should be. It'd be helpful if that documentation explained this kind of case, and how to make a good decision about which pattern to prefer.

/cc @leafpetersen @munificent - sorry if this is the wrong repo

**Comment by munificent** [comment]
Thanks for filing this, @dnfield. I agree some guidance would be good. I moved the issue over to the repo for dart.dev where the null safety docs and "Effective Dart" live.
