### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by RobLewis** [dart-lang/site-www#2635]
URL: https://www.dartlang.org/articles/libraries/broadcast-streams (link <a href="https://www.dartlang.org/articles/libraries/broadcast-streams">Single-Subscription vs. Broadcast Streams</a> on page https://pub.dev/documentation/rxdart/latest/rx/Rx-class.html  
Expected page: a description of Single-Subscription vs. Broadcast Streams. 
Actual page: 404

**Comment by Aman9026** [comment]
@RobLewis This page is a part of [ReactiveX](https://github.com/ReactiveX)
I've created a [PR](https://github.com/ReactiveX/rxdart/pull/505) to fix this.
You can refer to https://www.dartcn.com/articles/libraries/broadcast-streams for a description of Single-Subscription vs. Broadcast Streams.

**Comment by kwalrath** [comment]
Thank you, @Aman9026! I'm going to close this issue.
