### ISSUE TITLE
'A tour of the Dart language' page issue

### ISSUE THREAD

**Issue by brammool** [dart-lang/site-www#2639]
Page URL: https://dart.dev/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
The example for "default values for positional parameters" has a default value for "device" and still checks
if "device" is null:
    if (device != null) {
That seems superfluous.  Can't this condition just be removed?

**Comment by kwalrath** [comment]
The issue, iirc, was that even though there's a default value, someone could pass `null` as the value. When null safety hits, we'll probably want to rewrite this example!
