### ISSUE TITLE
'Package versioning' page issue

### ISSUE THREAD

**Issue by ug2454** [dart-lang/site-www#2648]
Page URL: https://dart.dev/tools/pub/versioning.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/versioning.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Under Title 'A name and a Number' in a para, 3rd line, it is written "...and it won’t affect you one **whit** because the version you use is unchanged."

Instead of 'whit', it should be 'bit'.

**Comment by ug2454** [comment]
can i please be assigned to this issue?

**Comment by kwalrath** [comment]
I think this would be a good change, since "whit" is a very uncommon word. Want to do it, @ug2454?

**Comment by ug2454** [comment]
Yes absolutely. I closed it after looking up meaning of whit which is the same as bit. But you are right, its not very common. I will make changes.

**Comment by kwalrath** [comment]
Fixed by #2650 

Thanks, @ug2454!
