### ISSUE TITLE
'Troubleshooting DartPad' page issue

### ISSUE THREAD

**Issue by pnkjsajwan** [dart-lang/site-www#2651]
Page URL: https://dart.dev/tools/dartpad/troubleshoot.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/dartpad/troubleshoot.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by kwalrath** [comment]
Closing due to lack of description.
