### ISSUE TITLE
Update analyser-results.txt files for CI builds

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#2652]
The beta and dev channel builds are currently broken since the output has changed slightly in 2.10:

old:

```
error • A value of type 'Object' can't be assigned to a variable of type 'String'. • lib/assignment.dart:11:14 • invalid_assignment
```

new:

```
error - A value of type 'Object' can't be assigned to a variable of type 'String' at lib/assignment.dart:11:14 - (invalid_assignment)
```

Pull request https://github.com/dart-lang/site-www/pull/2624 runs `dart analyze` on the `dev` and `beta` channels. To fix CI for the `dart` and `beta` channel builds we have two options:

1. Run `dart bin/update_dart_analyzer_txt.dart` from the `tool/dart_tools` directory to re-create the analyzer-results.txt files when 2.10 becomes the stable channel.
2. Create empty `analyzer-results-CHANNEL.txt` files for each channel in each example, and run `dart bin/update_dart_analyzer_txt.dart` from the `tool/dart_tools` directory

After either step, we need to re-run `tool/refresh-code-excerpts.sh`

**Comment by parlough** [comment]
When I merged `null_safety_examples` into `examples`, I also updated analysis results for `beta` and `dev` and marked their CI tasks as no longer experimental. So I'll close this as fixed by https://github.com/dart-lang/site-www/commit/f8eb9b21a0b6933fcefba0a6d7f286db81802dfa
