### ISSUE TITLE
'Get started: command-line and server apps' page issue

### ISSUE THREAD

**Issue by BerlinLion** [dart-lang/site-www#2657]
Page URL: https://dart.dev/tutorials/server/get-started
Page source: https://github.com/dart-lang/site-www/tree/master/src/_tutorials/server/get-started.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

I always get the error message "command not found", although I've set all the paths in both mentioned files. Maybe you should also mention all other files, which need to be modified, either instead of writing ".etc"!!!!!1!11!!!!
Or if you want to invest some few minutes more in the installation file, maybe modify the installation file in a way, that it automatically changes all the files, that need to be modified in the right way, instead of giving out a warning about changing some files, without even naming all of them, which need to be modified.

However I've done all the installation instructions pretty well and tried out all available workarounds and instructions, but I still get that error message "command not found", when entering "stagehand"

**Comment by kwalrath** [comment]
Could you give us your OS info?

**Comment by BerlinLion** [comment]
I have an Ubuntu 20.04.1 LTS

Best Regards,
Hamid Aminirad

**Comment by kwalrath** [comment]
This seems like a mix of Dart info (`pub global`) and platform-specific (`PATH`) info. We will soon be changing the way a lot of commands work, due to the `dart` all-in-one command, so this is an area that's likely to change soon.

**Comment by BerlinLion** [comment]
Thanks a lot for Your answer. I have already solved the problem, but I
don't know anymore how I did it. Indeed it was a mixture of different
solution, that I had found here and there on different websites.
However I thank You though for Your answer.

Best regards,
Hamid Aminirad

**Comment by saumya66** [comment]
Does this page has a typo ? @BerlinLion

**Comment by NinaPacifier** [comment]
@BerlinLion May I work on this issue???

**Comment by kwalrath** [comment]
@NinaPacifier thank you for volunteering! I'm assigning this to you. This page has been updated recently, so this issue might not even be an issue any more.

**Comment by MrBirb** [comment]
@kwalrath Kathy page was updated and stagehand was removed. I don’t think there is anything to fix here.

**Comment by parlough** [comment]
Now that `pub` has moved to a `dart` sub-command and the contents raising this issue have been removed, I'll close it for now.

Let us know if you have any further issues or questions, thanks!
