### ISSUE TITLE
Difference between <T extends SomeBaseClass> to just <SomeBaseClass>

### ISSUE THREAD

**Issue by feinstein** [dart-lang/site-www#2659]
Since Dart generics are very limited compared to other languages, I wonder what's the difference between `<T extends SomeBaseClass>` to just `<SomeBaseClass>`. This is the kind of use case the [language tour shows][1], but I don't see the point of using it.

Am I missing something? I feel the docs should at least point out why `<T extends SomeBaseClass>` would be desirable over the simpler `<SomeBaseClass>`.

  [1]: https://dart.dev/guides/language/language-tour#restricting-the-parameterized-type

**Comment by kwalrath** [comment]
You're right, we should clarify this.

My guess would be that `<SomeBaseClass>` accepts types that mix in or implement `SomeBaseClass`, but `<T extends SomeBaseClass>` requires a `extends SomeBaseClass` somewhere in the type's superclass chain.

@leafpetersen is my guess right? Can you give us an example of why this might matter?

**Comment by leafpetersen** [comment]
> Since Dart generics are very limited compared to other languages, I wonder what's the difference between `<T extends SomeBaseClass>` to just `<SomeBaseClass>`. This is the kind of use case the [language tour shows](https://dart.dev/guides/language/language-tour#restricting-the-parameterized-type), but I don't see the point of using it.

I'm sorry, I need a little more context for where `<SomeBaseClass>` appears.  From the docs, I think you may be confusing parameters and arguments?  That is, just as with functions I can have:

```
// someVariable is a parameter to the test function, and it has type int which means
// that test can only be applied to variables having type int
void test(int someVariable) {

}

void main() {
  int someVariable = 3;
  // someVariable is an argument being passed to the test function
  test(someVariable);
}
```

With generic classes there is a corresponding notion of generic parameters and arguments:

```
// T is a parameter to SomeClass, and it requires that SomeClass only be passed arguments
// which extend SomeBaseClass
class SomeClass<T extends SomeBaseClass> {}

void main() {
  // SomeBaseClass is a type argument to the SomeClass constructor.
  new SomeClass<SomeBaseClass>();
}
```

If I've missed the point of your question, perhaps you can expand a bit?

**Comment by feinstein** [comment]
I am used with Java and C# which have more elaborated generics bounds, so I decided to play with some codes to try out Dart simpler bounds.

Code 1:

```dart
void main() async {
  
  Base1 b1 = Base1();
  
  Base3 v = b1.get(Base4()..b = 1..i = 2);
  print(v.b);
  print(v.i);
}

class Base1 {
  Base2 get(Base2 value) {
    return value;
  }
}

abstract class Base2 {
  int i;
}

class Base3 extends Base2 {
  int b;
}

class Base4 extends Base3 {
  int c;
}
```

Code 2:

```dart
void main() async {
  
  Base1 b1 = Base1<Base4>();
  
  Base3 v = b1.get(Base4()..b = 1..i = 2 ..c = 3);
  print(v.b);
  print(v.i);
}

class Base1<T extends Base2> {
  T get(T value) {
    return value;
  }
}

abstract class Base2 {
  int i;
}

class Base3 extends Base2 {
  int b;
}

class Base4 extends Base3 {
  int c;
}
```

Then I wondered why go to the trouble to specify `<T extends Base2>` on Code 2 and then use T, if I can use `Base2` instead, like in Code 1, not having to care about `T`. 

Since Dart generics bounds can only extend to one class, why not just type that class instead of `T`?

**Comment by kwalrath** [comment]
I'm rusty on generics, but I wonder if Flutter has some real-world examples of this. E.g. collections where the type must descend from `Widget`, but you want to know for sure what _kind_ of widget you'll get.

**Comment by leafpetersen** [comment]
@feinstein Your code in "Code 1" is less statically safe.  There's an implicit downcast on the result of the call to `b1.get` that can fail at runtime.  For example, this slight modification of your code still statically checks out, but fails at runtime:
```
void main() async {

  Base1 b1 = Base1();

  Base3 v = b1.get(Base4()..c = 1..i = 2);
  print(v.b);
  print(v.i);
}

class Base1 {
  Base2 get(Base2 value) {
    return value;
  }
}

abstract class Base2 {
  int i;
}

class Base3 extends Base2 {
  int b;
}

class Base4 extends Base2 {
  int c;
}
```

If you make the same changes to your "Code 2" (and add the missing generic argument on the type of `b1`) there error is caught at runtime:

```
void main() async {
  
  Base1<Base4> b1 = Base1<Base4>();
  
  Base3 v = b1.get(Base4()..c = 1..i = 2 ..c = 3);
  print(v.b);
  print(v.i);
}

class Base1<T extends Base2> {
  T get(T value) {
    return value;
  }
}

abstract class Base2 {
  int i;
}

class Base3 extends Base2 {
  int b;
}

class Base4 extends Base2 {
  int c;
}
```

It is true that there is overlap in what can be expressed using generics and using subtype polymorphism: the difference is that with subtype polymorphism you can express more precise static properties.  So here, your "Code 1" can only say "b1 takes something thats a subtype of Base2 and returns something that's a (possibly different) subtype of Base2", whereas your "Code 2" says "b1 takes something that has a specific type T (or a subtype), and returns something of that same specific type T".

**Comment by feinstein** [comment]
Oh, got it!

Maybe a simple explanation on this implicit downcast could be added so users would know the benefit of this.

**Comment by kwalrath** [comment]
IIRC, I recently saw someone (in a PR that converts code from non-null-safe to null-safe) change `<T>` to `<T extends Object>`, to ensure that the incoming type was non-nullable.

So that's another use case we might see a lot more of once null safety is the norm.

**Comment by kwalrath** [comment]
> @feinstein Your code in "Code 1" is less statically safe. There's an implicit downcast on the result of the call to `b1.get` that can fail at runtime. For example, this slight modification of your code still statically checks out, but fails at runtime:

It doesn't statically check out for me, even if I add `?`s. Also, I don't see what's different between this and the old code. Maybe the analyzer is too smart for us now?

I'm working on this issue right now, trying to come up better text (and maybe example code) for https://dart.dev/guides/language/language-tour#restricting-the-parameterized-type.

**Comment by kwalrath** [comment]
Is this something that the tools handle for us now, so we don't need to explicitly talk about it? I was thinking of a note like this, but maybe the point is moot:

-----------
  How does `Foo<T extends SomeBaseClass>` differ from `Foo<SomeBaseClass>`?
  If you use `<SomeBaseClass>`,
  then `Foo` can be provided objects of _any_ `SomeBaseClass` subtype.
  Adding `T extends` not only lets members of `Foo` use the type argument `T`,
  but lets you restrict the argument's type to subtypes of `T`.

-----------

**Comment by leafpetersen** [comment]
> How does `Foo<T extends SomeBaseClass>` differ from `Foo<SomeBaseClass>`?

Again, this is (or at least reads as) a category confusion.  If you really mean, how does `class Foo<T extends SomeBaseClass> ...` differ from `class Foo<SomeBaseClass> ...` the answer is that `SomeBaseClass` in the first declaration is a free variable which refers to a specific class, and `SomeBaseClass` in the second example is the parameter, and does not refer to a specific class (you could equally well write the second as `class Foo<T> ...`.  

I think what this issue is more about is the question of using subtype polymorphism vs generic polymorphism.  That is, it's more about the difference between the following two classes:

```
class Foo1<T extends SomeBaseClass> {
  final T x;
  Foo1(this.x);
}

class Foo2 {
  final SomeBaseClass x;
  Foo2(this.x);
}
```

`Foo1` uses generic polymorphism, `Foo2` uses subtype polymorphism.

**Comment by kwalrath** [comment]
@feinstein, with the changes to the type system, do you still think we need to clarify this?

**Comment by feinstein** [comment]
No, I think this can be closed... Thank you for taking the time to clarify the type system!
