### ISSUE TITLE
'dartanalyzer' installation instructions not found

### ISSUE THREAD

**Issue by maheshmnj** [dart-lang/site-www#2663]
Page URL: https://dart.dev/tools/dartanalyzer.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/dartanalyzer.md

I searched throughout the dart docs and could not find how to install dartanalyzer.

**Comment by kwalrath** [comment]
Good point. We should have a link from all the tools pages back to https://dart.dev/tools/sdk.

**Comment by parzuko** [comment]
Can i maybe try fixing this ?

**Comment by kwalrath** [comment]
I'd like to fix one page, to set up the precedent for other pages to follow... but I suppose you might have a better idea than I would. Sure, go ahead! Just fix one page, for now, so we can figure out a good scheme.

**Comment by parzuko** [comment]
Alright! Should I just start with adding the link back to https://dart.dev/tools/sdk ?

**Comment by kwalrath** [comment]
Yes, I think so. The question is what form that link should take. (It should be simple, clear, and easy to use across every non-`dart`-command page. The `dart` pages will be special because we'll probably want to mention the Flutter SDK too.) 

We can work out that form here, or you can create a PR with a proposal for `dartanalyzer`. Your choice!

**Comment by JHBitencourt** [comment]
Wouldn't it be cool to add a note on each one of theses SDK tools to prefer using the new `dart` unified tool, from Dart 2.10?

I mean, now it is preferable to use `dart analyze foo.dart` over `dartanalyzer foo.dart`

**Comment by kwalrath** [comment]
@JHBitencourt we probably should. (I hadn't because up until recently, I thought 2.10 would just be a tech preview for the unified `dart` tool.) Could you file an issue for that?

**Comment by JHBitencourt** [comment]
@kwalrath  Sure! #2678

**Comment by kwalrath** [comment]
Thank you!

**Comment by MrBirb** [comment]
@kwalrath Kathy looks like the page was removed

**Comment by kwalrath** [comment]
> @kwalrath Kathy looks like the page was removed

Yes, it was replaced by https://dart.dev/tools/dart-analyze, and it looks like that has a good link back to the `dart` tool page, which says that the tool is in the SDK. Thanks for helping us clean up our issue list, @MrBirb!
