### ISSUE TITLE
Broken "Imperative Component Loading" link

### ISSUE THREAD

**Issue by mnordine** [dart-lang/site-www#2666]
On https://dart.dev/web/deployment, link is `404`

**Comment by mnordine** [comment]
@kwalrath my bad, it's the following link that is a `404`: https://github.com/dart-lang/angular/blob/master/doc/faq/component-loading.md

**Comment by kwalrath** [comment]
Oh, good catch! It looks like everything inside https://github.com/dart-lang/angular/tree/master/doc is gone!

@kevmoo is there a replacement?
