### ISSUE TITLE
Mention computing finals as a use case for `factory`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#267]
https://github.com/dart-lang/site-www/blob/68367eb5a3d8cd821db46d432a8563f250e6972f/src/_guides/language/language-tour.md#factory-constructors

We often get confusion from devs who want to assign to a final in the constructor like they can in Java. Usually we point to factory constructors as an alternative. Our documentation introducing factory constructor should also call this out as a possible use case.

**Comment by kwalrath** [comment]
Might take more than a few minutes if we add an example.

**Comment by kwalrath** [comment]
Is the factory constructor still a good pattern, now that you can use `late final`?

**Comment by kwalrath** [comment]
Oh, and hey, it looks like we already cover this case! https://dart.dev/guides/language/language-tour#factory-constructors
