### ISSUE TITLE
Explain why Dart uses '_' for privacy rather than a keyword in the documentation.

### ISSUE THREAD

**Issue by kfish610** [dart-lang/site-www#2671]
Coming from C#, I was incredibly confused why Dart chose to use a prefix of `_` for private variables, rather than the typical `public`, `private`, and `protected` modifiers. After reading through https://github.com/dart-lang/sdk/issues/33383, however, I understand why Dart chose this method of visibility modification, and I don't mind it as much. However, it seems strange to me that no where in the docs does it even reference an explanation (unless I missed something, and if I did, please let me know). I think adding a section somewhere in the docs to explain the underscore notation (maybe a note in the tour?) would make people less likely to immediately discount Dart based off of this choice (I know I did, and looking at that issue, so did a lot of people).

Any opinions?

**Comment by kwalrath** [comment]
I don't think the language tour should justify or provide history, but it seems legit to link out to justifications (such as dart-lang/sdk#33383, in this case). Maybe a note like this:

> **Language note:** If you're used to `public` and `private` annotations, see [SDK issue 33383](https://github.com/dart-lang/sdk/issues/33383) for details on why Dart uses the `_` prefix instead.

What do you think, @kfish610?

**Comment by kfish610** [comment]
That sounds reasonable, though I think they're called access modifiers, not annotations. Other than that, seems well worded, definitely would have made me much less confused than I was when I read the tour originally.

**Comment by kwalrath** [comment]
Oops, yep, you're right about using _access modifiers_.

**Comment by kwalrath** [comment]
@kfish610 would you like to make this fix, or shall we open it up to the community?

**Comment by kfish610** [comment]
I can make it, is there anything I need to do other than make a pull request?

**Comment by kwalrath** [comment]
> I can make it, is there anything I need to do other than make a pull request?

Thanks! Just make a pull request. Search for "Deprecation note" to find some code to copy. (I don't see any other "Language note"s, but it makes sense to me to have a separate note type for this.)

**Comment by kfish610** [comment]
@kwalrath Out of curiosity, is there a reason you prefer saying "Language note" as opposed to just "Note"? All of the notes on the tour just say "Note", and most of them refer to the language.

**Comment by kwalrath** [comment]
You're not wrong. I was thinking that a "Language note" might imply a comparison to other languages, but perhaps that's too subtle a point.
