### ISSUE TITLE
Create notes on Dart SDK tools pages to inform about the new dart unified tool

### ISSUE THREAD

**Issue by JHBitencourt** [dart-lang/site-www#2678]
Page URL: https://dart.dev/tools/dartanalyzer.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/dartanalyzer.md

According to the new Dart 2.10, is preferable to use the new `dart` unified command line tool over the standalone ones, such as `dartanalyzer`, `dartfmt`, `dart2js`, `dart2native` and `pub`.

So it would be cool to create an informative note on each one of these pages, linking to the following page:
https://dart.dev/tools/dart-tool

**Comment by sumandipanshu** [comment]
can i work on this issue?

**Comment by kwalrath** [comment]
> can i work on this issue?

Sorry, we aren't quite ready for this yet.

**Comment by kwalrath** [comment]
Obsoleted in favor of #2719 (which I'm working on this very minute).
