### ISSUE TITLE
Make sure people can update dartpad_picker_main.js

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2684]
See #2581 for info. I was unable to use ./compile[_dev].sh, but @johnpryan had no problems. I should try again and put the console output here.

**Comment by parlough** [comment]
I have a feeling if you try again with the a stable SDK >= 2.12 on your path this may now work, but if not - can you provide the output so I can take a look? 

Depending on what you find I can also update the instructions in the README, providing some other extra context that may be useful in general.

**Comment by kwalrath** [comment]
@parlough you just updated [dartpad_picker_main.dart.js](https://github.com/dart-lang/site-www/blob/master/src/assets/dash/js/dartpad_picker_main.dart.js) in #3276.

Did you find any problems or documentation we should improve? If not, perhaps we can close this issue.

**Comment by parlough** [comment]
@kwalrath Everything has seemingly been working the past few times I've worked with it(now with SDK >= 2.13).

I'll close this for now, but if you(or someone else reading this) has any other issues in the future, feel free to open a new issue and I can identify the issue and flesh out more documentation as necessary.
