### ISSUE TITLE
'Understanding null safety' page issue

### ISSUE THREAD

**Issue by kellsaro** [dart-lang/site-www#2692]
Page URL: https://dart.dev/null-safety/understanding-null-safety#nullability-and-generics
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/understanding-null-safety/index.md

Description of issue:

At section 'Nullability and generics', there is an error at the code example:
```
// Using null safety:
class Box<T> {
  final T? object;
  Box.empty();
  Box.full(this.object);

  T unbox() => object as T;
}
```
As `object` has been declared `final` it must be initialized in `empty` constructor. Remove `final` keyword or `empty` constructor otherwise.
Solutions:
```
// Using null safety:
class Box<T> {
  final T? object;
  Box.empty(): this.object = null;
  Box.full(this.object);

  T unbox() => object as T;
}
```

```
// Using null safety:
class Box<T> {
  final T? object;
  Box.full(this.object);

  T unbox() => object as T;
}
```

```
// Using null safety:
class Box<T> {
  T? object;
  Box.empty();
  Box.full(this.object);

  T unbox() => object as T;
}
```

**Comment by johnpryan** [comment]
Looking at the previous snippet, it seems like solution 3 is what was intended. I don't think the `final` is necessary here, since it's focused on the cast in the `unbox()` method.
