### ISSUE TITLE
Document abstract fields

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2695]
Details: dart-lang/sdk#43712

**Comment by kwalrath** [comment]
@munificent I never got to this. Do you think you could add a bit about abstract fields to https://dart.dev/null-safety/understanding-null-safety, so I can point to that from other places? Or maybe you could feed me some words, and I'll figure out a reasonable place to plop them for now?

**Comment by leafpetersen** [comment]
Any progress on this?

**Comment by kwalrath** [comment]
> Any progress on this?

@leafpetersen could you ask @munificent the next time you're in the same (virtual) room?

**Comment by munificent** [comment]
This is documented in "Understanding Null Safety" now. Do you want this bug to also cover the "Language Tour" changes too?
