### ISSUE TITLE
Typo in "Understanding null safety"

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/site-www#2697]
In our translation of this doc we found some typos. Some of them has been fixed already, but this one is still remained:

https://github.com/dart-lang/site-www/blob/4ef930c2feaaf49d614d63aba91c6d420f7b0750/src/null-safety/understanding-null-safety/index.md#L713

Should `the now non-nullable` be `the new non-nullable` ?

**Comment by kwalrath** [comment]
Pretty sure @munificent meant "now". `List` used to be nullable, but "now" (i.e. under null safety) it's non-nullable.

**Comment by AlexV525** [comment]
Thanks for the explanation!
