### ISSUE TITLE
Doc comment guidelines for libraries

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#27]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [amouravski@google.com](https://code.google.com/u/amouravski@google.com/) on April 09, 2013 18:59:10_

It'd be nice to have documented exactly what library level documentation comments should be. We have many good examples of something very explanatory, so is that what we want? See unittest for example.

_Original issue: http://code.google.com/p/dart/issues/detail?id=9807_

_Copied from original issue: dart-lang/www.dartlang.org#636_

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on April 09, 2013 10:04:36_

True. This would be in the Content section of http://www.dartlang.org/articles/doc-comment-guidelines/ .

I can do this eventually, but anyone else should feel free to claim this bug and modify the article and add a library to the test.

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [amouravski@google.com](https://code.google.com/u/amouravski@google.com/) on April 09, 2013 12:43:00_

My suggestion is something like:

First sentence: similar to comment on other doc comments. Should stand alone, should be direct.
<blank line>
Explanation of how to use library. As detailed as possible for big libraries, or less for smaller utility libraries.
Code samples are almost necessary.
<blank line>
Warnings, reminders, and other gothchas.
<blank line>
How is this library used elsewhere?
<blank line>
See also:
<blank line>
Unordered list of links to more information, other docs, helpful guides, tutorials, etc.

Something like:

/// This library does <blah> with <foo>.
///
/// To get all <fooblahs> do:
///
///     code sample here
///
/// Remember to <plurdle> your <cruncheons> when you use this library.
///
/// This library is used in <somewhere>, but can be adapted to 
/// <the screen> by switching out your <hair care product>.
///
/// See also:
///
///   * [An informative source]( http://example.com/ ) from the Example Source.

(I prefer /** */, but I used /// here for ease of typing in a crappy box.

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on July 24, 2013 14:03:01_

**Labels:** -Type-Documentation -Area-Site Docs-Articles Area-Documentation

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on September 13, 2013 14:29:02_

**Labels:** Docs-StyleGuide

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on September 13, 2013 14:29:53_

**Labels:** -Docs-Articles

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [rnystrom@google.com](https://code.google.com/u/rnystrom@google.com/) on September 23, 2013 12:14:16_

I like calling out that the first paragraph should be a single sentence, which the doc comment guidelines do. For other stuff, I don't want to be prescriptive. Doc comments should be structured in a way that makes the most sense for its content. Being too rigidly patterned won't add value for many libraries.

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on September 30, 2013 08:21:15_

I tend to agree with you, Bob, that each library could have its own style, as long as the first paragraphs are consistently a one-sentence-fragment description (since the tools rely on that). We should also have a checklist of things good docs should have:

- A brief discussion of when you should or shouldn't use this library/class
- code snippets, where appropriate
- links to important members of this library/class
- links to other relevant libraries/classes
- links to documentation that discusses this library/class
- links to samples that show how to use this library/class

And we should point to some good docs, perhaps from multiple libraries, perhaps with a little explanation of why each one's approach makes sense. E.g.:

[CommonClass]: Because this class is one of the first that beginning Dart programmers encounter, it has lots of explanation and code snippets, without duplicating content covered elsewhere. It follows the good practice of linking to other relevant classes, documentation, and samples.

[ObscureClass]: Used only in special cases, this class has brief but helpful descriptions, with links to relevant classes and code.

Finally, I've added Florian because he had some ideas for when and how to use [parameter] in a way that tools such as Dart Editor could pick up.

**Cc:** floitsch@google.com rnystrom@google.com

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [sethladd@google.com](https://code.google.com/u/sethladd@google.com/) on December 04, 2013 12:22:11_

Looks like we can update https://www.dartlang.org/articles/doc-comment-guidelines/ with this.

**Status:** Triaged  
  **Owner:** kathyw@google.com

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [lrn@google.com](https://code.google.com/u/lrn@google.com/) on January 29, 2014 07:39:11_

**Labels:** Type-Enhancement

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on June 04, 2014 14:58:11_

**Labels:** -Area-Documentation Area-Site

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kasperl@google.com](https://code.google.com/u/kasperl@google.com/) on July 10, 2014 03:20:32_

**Labels:** -Milestone-Later Oldschool-Milestone-Later

**Comment by Sfshaza** [comment]
_From @nicolasgarnier on August 26, 2014 14:58_

_From [kasperl@google.com](https://code.google.com/u/kasperl@google.com/) on August 04, 2014 00:43:01_

**Labels:** -Oldschool-Milestone-Later

**Comment by kwalrath** [comment]
Also see https://github.com/dart-lang/dartdoc/issues/1082 regarding where to put library docs.

**Comment by kwalrath** [comment]
Here's the minimum I think that library docs need:

* One-line description.
* Example of importing the library.
* Link to help on using the library.

Here's an example from [angular.dart](https://github.com/dart-lang/angular/blob/master/angular/lib/angular.dart):

```
/// The primary library for the [AngularDart web framework][AngularDart].
///
/// Import this library as follows:
///
/// ```
/// import 'package:angular/angular.dart';
/// ```
///
/// For help using this library, see the AngularDart documentation:
///
/// * [AngularDart guide][]
/// * [AngularDart cheat sheet][cheatsheet]
///
/// [AngularDart]: https://webdev.dartlang.org/angular
/// [AngularDart guide]: https://webdev.dartlang.org/angular/guide
/// [cheatsheet]: https://webdev.dartlang.org/angular/cheatsheet

library angular;
```

@munificent Does that sound reasonable? For a library that doesn't have extensive docs & examples elsewhere, you'd want to put much more in the library description.
