### ISSUE TITLE
DartPad input/output features of dart:io library not working

### ISSUE THREAD

**Issue by shankar-pariyar** [dart-lang/site-www#2700]
In DartPad some features of dart:io library not working like "stdin.write()" and "stdout.readLineSync()" are not working.
Runtime error is occurring as below:
- For stdin.write()
Uncaught Error: Unsupported operation: StdIOUtils._getStdioOutputStream

- For stdout.readLineSync()
Uncaught Error: Unsupported operation: StdIOUtils._getStdioInputStream

**Comment by kwalrath** [comment]
DartPad runs on the web, so unfortunately it can't support dart:io. It should provide better messages, though. I'm going to close this in favor of https://github.com/dart-lang/dart-pad/issues/1615.
