### ISSUE TITLE
'Sound null safety' SDK constraints recommendation seems incorrect for TP2

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#2710]
Page URL: https://dart.dev/null-safety/
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
The SDK constraints section seems incorrect, for three reasons:

```yaml
environment: sdk: '>=2.11.0-213.0.dev <3.0.0'
```

1. I don't think this is indented correctly, is it? The `sdk` section should be on a separate line
2. The lower bound is driven by the [experimental release version](https://github.com/dart-lang/sdk/blob/c003c1a64dbcce0102182d271c3c92ea34a20779/tools/experimental_features.yaml#L101) and therefore probably should therefore be `>=2.10.0`
3. The upper bound should be set more tightly, based on the email exchange a few of us had. Likely `<2.12.0`, which will force this to be migrated again post-beta.

**Comment by kwalrath** [comment]
We updated the lower bound last week, based on conversations inside the team. @kevmoo can tell you more.

As to the format, I'm pretty sure you can compact it like this, but I didn't test it, and I don't know whether we'd usually recommend this format. We should, however, change the quotes to be double, since we usually use single quotes only for .dart files.

**Comment by mit-mit** [comment]
It's totally correct that a lower bound of 2.10 will suffice, but I personally find that confusing. It's not something we're likely to see a lot for future experiments, as it's only needed when they last several stable release. In those cases, the current dev release is the likely lower SDK constraint needed. @leafpetersen any reason why recommending a lower bound of 2.11.0-0.x would be bad?

**Comment by mit-mit** [comment]
Upper bound of `<2.12.0` sgtm

**Comment by timsneath** [comment]
My only thought is whether we overcomplicate the version by being so specific; ideally it's something that a developer can easily verify. (That is, `2.10` is _easy_, but `2.11.0-229.0.dev` is a mouthful and prone to error.)

**Comment by kevmoo** [comment]
> My only thought is whether we overcomplicate the version by being so specific; ideally it's something that a developer can easily verify. (That is, `2.10.0` is _easy_, but `2.11.0-229.0.dev` is a mouthful and prone to error.)

The nice(ish) thing about `2.11.0-229.0.dev` is it makes sure folks don't stumble into trying this with an old SDK.

They have to be on a recent build.

**Comment by kwalrath** [comment]
I'll update the doc now.
