### ISSUE TITLE
Non-existant functions in Built-In-Types for Language Tour

### ISSUE THREAD

**Issue by micpap25** [dart-lang/site-www#2717]
Page: https://dart.dev/guides/language/language-tour#lists
Page Source: https://github.com/dart-lang/site-www/blob/master/src/_guides/language/language-tour.md
Other Page Source: https://github.com/dart-lang/site-www/blob/master/examples/misc/lib/language_tour/built_in_types.dart

The source for the Language Tour refers to functions in the built_in_types file that don't exist, like `list-if` and `list-for`. I'm not sure exactly how the site infrastructure works, but I think either the references to those functions should be removed from the language tour source, or the functions should be added to the built_in_types source.

**Comment by kwalrath** [comment]
These are just names of doc regions (used in code excerpts). E.g. `<?code-excerpt "misc/test/language_tour/built_in_types_test.dart (list-if)"?>` refers to https://github.com/dart-lang/site-www/blob/953164d0da62023ac44888b6f07d180cd5616f69/examples/misc/test/language_tour/built_in_types_test.dart#L109.

**Comment by micpap25** [comment]
Ah, I see the issue. I didn't notice there was a difference between `built_in_types` and `built_in_types_test`. No problem then.
