### ISSUE TITLE
"//uncommenting this causes an error" in Language Tour

### ISSUE THREAD

**Issue by micpap25** [dart-lang/site-www#2718]
Page: https://dart.dev/guides/language/language-tour#lists
Page Source: https://github.com/dart-lang/site-www/blob/master/src/_guides/language/language-tour.md

Issue: There are a few instances where a code example has a section that says "uncommenting this causes an error". This is pretty obviously misleading and could cause confusion.

**Comment by kwalrath** [comment]
this -> this line?

**Comment by micpap25** [comment]
These three, specifically:
![image](https://user-images.githubusercontent.com/34077605/97769967-8d0a9700-1b05-11eb-8726-f3600a3ff949.png)
![image](https://user-images.githubusercontent.com/34077605/97769977-9e53a380-1b05-11eb-8137-e87c41e05bc2.png)
![image](https://user-images.githubusercontent.com/34077605/97769981-a6abde80-1b05-11eb-9bac-846b76dffff3.png)

**Comment by kwalrath** [comment]
Just to be clear... the issue is that "this" is unclear — seems like it could refer to the comment instead of the whole line, correct?

**Comment by micpap25** [comment]
ah, I'm sorry. I'm referring just to the part that says "Uncommenting this causes an error", not the entire line.

**Comment by kwalrath** [comment]
> ah, I'm sorry. I'm referring just to the part that says "Uncommenting this causes an error", not the entire line.

So changing "this" to "this line" is the fix, correct? Or we could say something like this:

```
// ... bad code here ... // This line of code has an error.
```

**Comment by micpap25** [comment]
OK, I think I misinterpreted some of your comments from earlier and confused myself a little. 

Basically, I previously thought that `//Uncommenting this causes an error` wasn't a clear enough indication to tell viewers that "this isn't allowed and will cause problems". I think it could be replaced with a more direct statement. 

I think I'll make a PR for this.
