### ISSUE TITLE
Skip the dev jobs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2720]
The dev channel jobs are taking 50 minutes and then timing out, starting with https://travis-ci.org/github/dart-lang/site-www/builds/739979991 (PR from 6 hours ago). https://travis-ci.org/github/dart-lang/site-www/builds/740059875 (master channel) looks broken in the same way. We haven't released a dev build recently, so I don't know why this is happening.

Soon we might have a non-nullable by default dev channel build, in which case everything will be broken anyway, so dev channel should be (1) allowed to fail until we update the build and (2) skipped for now to avoid tying up Travis for 50 minutes.

/cc @RedBrogdon

**Comment by pq** [comment]
See: https://github.com/dart-lang/sdk/issues/43979.

**Comment by pq** [comment]
This should be fixed in dev builds post https://github.com/dart-lang/sdk/commit/45931e9ea86099ff225b39e564ece2806ac32de8.
