### ISSUE TITLE
Update /tutorials/server/get-started to use `dart pub get`

### ISSUE THREAD

**Issue by shubhanshu02** [dart-lang/site-www#2728]
As discussed in #2725, we should add a step to show the usage of `dart pub get` later where the reader imports a library to the https://dart.dev/tutorials/server/get-started. 
Reason: Since the `dart create` automatically runs `dart pub get` on completion, the step for its usage is removed.

**Comment by kwalrath** [comment]
#3076 added a note about dart pub get, so I'm going to close this. We might still add a separate step, but only if people tell us that it's a good idea.
