### ISSUE TITLE
pub publish doc

### ISSUE THREAD

**Issue by bshlomo** [dart-lang/site-www#2729]
In the current version doc - 
Publish is one of the commands of the pub tool.
$ pub publish [--dry-run] [--force]

In dart SDK last version 
Usage: pub publish [options]
-h, --help       Print this usage information.
-n, --dry-run    Validate but do not publish the package.
-f, --force      Publish without confirmation if there are no errors.
    **--server**     The package server to which to upload this package.

missing the --server option in the current doc in this site

**Comment by kwalrath** [comment]
@mit-mit @kevmoo I have a vague memory that we didn't want to advertise `--server`. Right or wrong?

**Comment by kevmoo** [comment]
I think correct – we're deprecating it.

https://github.com/dart-lang/pub/pull/2697

**Comment by kwalrath** [comment]
Thanks for making sure we were documenting this correctly, @bshlomo!
