### ISSUE TITLE
support for microcontroller

### ISSUE THREAD

**Issue by aasirmutwalli22** [dart-lang/site-www#2733]

**Comment by kwalrath** [comment]
Could you clarify what the issue is?

**Comment by aasirmutwalli22** [comment]
> Could you clarify what the issue is?

It is not an essue. It is a feature request. If dart lang can be used to program microcontrollers like arduino, esp32, etc.

**Comment by kwalrath** [comment]
Ah, thanks for the clarification. Could you please open or comment on an issue in the dart-lang/sdk repo?
