### ISSUE TITLE
Define doc styles for non dartlang.org docs.

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#274]
Keep a list of affected pages here:

* [Analysis Server API Specification](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html)
* [Observatory docs](https://github.com/dart-lang/observatory)

@devoncarew

**Comment by kwalrath** [comment]
We have the developer doc style guide for editorial stuff: https://developers.google.com/style/.

What else do we need to define?
