### ISSUE TITLE
Dart book resource

### ISSUE THREAD

**Issue by AymenBrxII** [dart-lang/site-www#2740]
**Title:** [Dart Apprentice](https://www.raywenderlich.com/books/dart-apprentice/)
**Description:** Dart Apprentice will teach you all the basic concepts you need to master this language. Follow along the easily and thoroughly explained concepts and you will be building Dart applications in a breeze. 
**Authors:** Jonathan Sande & Matt Galloway

**Comment by kwalrath** [comment]
Thanks, I hadn't heard of that! It looks like it's in early access right now (and maybe not available in print?), but we'd welcome a pull request to add it to https://github.com/dart-lang/site-www/blob/master/src/_data/books-dart2.yml (which is included by https://github.com/dart-lang/site-www/blob/master/src/resources/books.md).
