### ISSUE TITLE
'Null safety: frequently asked questions' page issue

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#2746]
Page URL: https://dart.dev/null-safety/faq.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/faq.md

Move the section on `pkg:ffi` to the bottom – likely not super relevant to most external developers

**Comment by brittafi** [comment]
Hi, as a beginner to contributing I'd like to do this. Thanks!

**Comment by kwalrath** [comment]
It is your, @brittafi. Thank you for volunteering!

**Comment by kwalrath** [comment]
Fixed by #2756
