### ISSUE TITLE
"Mixed-mode" -> "Mixed-version"

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#2748]
The [in-progress null safety migration docs](https://kw-www-dartlang-1.firebaseapp.com/guides/language/evolution#mixed-mode-programs) use "mixed-mode" to refer to a Dart program that contains some opted in and some opted out libraries. That term is kind of confusing because "mode" sounds like a way to *run* a program (think "debug mode" or "release mode") but "mixed-mode" describes the program itself on disc.

We talked about this in the language meeting this morning, and instead we prefer "mixed version".

Likewise, instead of "partial null safety" (which sounds like a property of the program but is a mode you run it), we're thinking "unsound null safety".

@kwalrath, I'm not quite sure where the migration docs live right now or I'd fix these myself, so filing an issue instead. I'm happy to help out with the changes if you'd like.

@mit-mit @leafpetersen

**Comment by munificent** [comment]
Tying all the threads together: https://github.com/dart-lang/sdk/issues/44149

**Comment by kwalrath** [comment]
> We talked about this in the language meeting this morning, and instead we prefer "mixed version".
> 
> Likewise, instead of "partial null safety" (which sounds like a property of the program but is a mode you run it), we're thinking "unsound null safety".

Sounds good!
 
> @kwalrath, I'm not quite sure where the migration docs live right now or I'd fix these myself, so filing an issue instead. I'm happy to help out with the changes if you'd like.

I'll be happy to make all the changes for dart.dev.

**Comment by kwalrath** [comment]
@ryanmcginnis fyi. The FAQ uses _mixed-mode_  in one paragraph, and I'm fixing that now. (It doesn't use _partial null safety._) We might want to update the internal FAQ to match, so we don't accidentally regress in the future.

**Comment by mit-mit** [comment]
Adding a go link in https://github.com/dart-lang/site-www/pull/2752. For now pointing it at the wiki, but once we land this new page about mix version / unsound null safety, we should update that go link to point to it.

**Comment by ryanmcginnis** [comment]
@kwalrath thanks! i've updated the internal FAQ.

**Comment by munificent** [comment]
Thanks!

**Comment by kwalrath** [comment]
I believe I've fixed this everywhere.
