### ISSUE TITLE
Conditional Exports Dart 2

### ISSUE THREAD

**Issue by firefox360** [dart-lang/site-www#2751]
Hi there, 

I saw a lot of people asking questions about conditional exports in dart 2. I found out, Dart 2 does not support conditional exports the way it was supported in dart 1. The only condition now is based on dart.library,*!

But our project has a login screen and instead of using if-else conditions in one code base we wanted to use dependancy injection to load a specific export of the login implementation. The consumer class should not change if a new implementation is made. So if in the future a Facebook login should be supported, then we want to export a new login implementation based on the condition, without the consumer class to be changed.

We are not using XCode (because we saw something about flavors, but (tell us if we are wrong) we thought it was only possible in combination with XCode). 

Our initial plan was to combine three blogs about flutter technologies:
1. Using DI: https://medium.com/@greg.perry/flutters-dependency-injection-c4f053e4408
2. Using conditional exports (instead of commiting everything out that is not in use) (But this is not possible anymore in Dart 2): https://medium.com/@dvargahali/dart-2-conditional-imports-update-16147a776aa8
3. Using environmnent variables to read the condition for conditional exports:  https://efthymis.com/use-environment-variables-in-ci-cd-for-flutter-apps/

So the main question is: How can we deploy our app with different implementations of a class based on the Customer we are deploying for?

**Comment by kwalrath** [comment]
As a programming question, this is a good candidate for asking the [community](https://dart.dev/community#join-the-conversation) — maybe StackOverflow? When you get an answer, if it's appropriate for the Dart docs, could you please file an issue or PR with specific improvements we should make? (If it's a Flutter-specific answer, then https://github.com/flutter/website is the right place for the issue/PR.)

**Comment by firefox360** [comment]
The issue is you disabled the conditional exports, where it was available in Dart 1. Please make it available again :)

**Comment by kwalrath** [comment]
Ah, that would be an issue for https://github.com/dart-lang/language. :)
