### ISSUE TITLE
">>>" operator is not supported

### ISSUE THREAD

**Issue by arcticfox1919** [dart-lang/site-www#2755]
![](https://github.com/arcticfox1919/ImageHosting/blob/master/2020-11-13-002.png?raw=true)

I see the ">>>" operator in the document, but I get an error when I use it. Is this an oversight of the document?

![](https://github.com/arcticfox1919/ImageHosting/blob/master/2020-11-13-003.png?raw=true)

**Comment by kwalrath** [comment]
Oh interesting! I see the operator in the spec, but num, int, and double don't seem to implement it. I suspect it's available for specialized number classes.

/cc @lrhn for guidance on how to cover this in the language tour

**Comment by lrhn** [comment]
The `>>>` operator is not implemented yet. It's been specified since before 2.0, but implementing it hasn't been a priority yet.
So, nobody can use it. I hope it will be implemented *real soon now*.

When we introduce it into the implementations, then we will probably also add a `>>>` operator to the `int` class.

**Comment by kwalrath** [comment]
We might want to mention somewhere that `>>>` isn't implemented, probably in https://dart.dev/guides/language/language-tour#bitwise-and-shift-operators.

**Comment by RandalSchwartz** [comment]
One would wonder why there isn't a matching <<< then.

**Comment by lrhn** [comment]
There is an infinity of possible operators that we can add to the language. We can (and do) consider whether we should introduce larger regular families of operators, or just stick with the ones we have. Until such time, we'll probably only add specific operators that we actually need. The `>>>` is well-established and do we have an actual need for it. (Really, removing the `>>>` operator from the *language* when we removed it from `int` was completely uncalled for, we should just have left it in).
I'd probably accept `**` as well, but that's about it.

**Comment by parlough** [comment]
For reference, the 2.14 dev builds now include the necessary implementation, with a changelog entry here: https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#language

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/site-www/issues/3455 which will see the `>>>` operator as implemented in Dart 2.14 documented.

Thanks for opening the issue!
