### ISSUE TITLE
Add `required` to /null-safety

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2767]
Noticed while working on #2739

**Comment by parlough** [comment]
I'm going to close this as that page is a high level document which doesn't really go into the new language features introduced with null safety. The page links to [Understanding null safety](https://dart.dev/null-safety/understanding-null-safety) which covers [Required named parameters](https://dart.dev/null-safety/understanding-null-safety#required-named-parameters) alongside the other language features.
