### ISSUE TITLE
Migrate from .packages to package_config.json

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2777]
Per https://github.com/dart-lang/pub/issues/2756, the `.packages` file is being replaced by `.dart_tool/package_config.json`. The docs should be updated to reflect this.

Spec: https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md

Affected files:
src/_includes/packages-dir.html
src/tools/pub/versioning.md
src/tools/pub/cmd/pub-upgrade.md
src/tools/pub/cmd/pub-downgrade.md
src/tools/pub/cmd/pub-get.md
src/tools/pub/glossary.md
src/tools/pub/package-layout.md
src/_tutorials/libraries/shared-pkgs.md
src/_guides/libraries/private-files.md
src/_guides/packages.md

(We already link to the spec from the `dart pub get` step in https://dart.dev/null-safety/unsound-null-safety#migrating-incrementally.)

/cc @lrhn

**Comment by mit-mit** [comment]
@kwalrath we're moving ahead with this change now. Do we still need these website updates?

**Comment by kwalrath** [comment]
Looks like we fixed this in #3641. Thanks for the reminder!
