### ISSUE TITLE
Update dart:ffi note

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2784]
https://dart.dev/guides/libraries/c-interop says "As of Dart 2.7, dart:ffi is in beta". Update the version, at least. The status still seems accurate, based on the link.

UPDATE: I've updated the version to 2.10, but we'll need to update the version note in future releases.

**Comment by mit-mit** [comment]
Yes, still in beta (for a little bit longer; a few last changes coming through). But yes, should say "as of Dart 2.10".

**Comment by MrBirb** [comment]
I believe this can be closed too Kathy. You removed the [note](https://github.com/dart-lang/site-www/pull/3029)

**Comment by mit-mit** [comment]
Yup, good catch, thanks!
