### ISSUE TITLE
'Code of conduct' page issue

### ISSUE THREAD

**Issue by Amirnateghi1** [dart-lang/site-www#2796]
Page URL: https://dart.dev/code-of-conduct.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/code-of-conduct.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by NinaPacifier** [comment]
@Amirnateghi1 I am new to the open-source contribution. May I work on this issue???

**Comment by kwalrath** [comment]
I'm closing this, due to the lack of description. @Amirnateghi1 if you unintentionally left it blank, please update this issue and I'll reopen it.

**Comment by Amirnateghi1** [comment]
Spring Boots

**Comment by alecpedigree4** [comment]
$i
