### ISSUE TITLE
'Null safety: frequently asked questions' page issue

### ISSUE THREAD

**Issue by SebastianJL** [dart-lang/site-www#2799]
Page URL: https://dart.dev/null-safety/faq.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/faq.md

Description of issue:
I was just wondering about the following point:

> ## How do I signal that the return value from a Map is non-nullable?
> 
> The
> [lookup operator](https://api.dart.dev/stable/dart-core/Map/operator_get.html)
> on Map (`[]`) by default returns a nullable type. There's no way to signal to
> the language that the value is guaranteed to be there.
> 
> In this case, you should use the bang operator (`!`) to cast the value back to
> V:
> 
> ```dart
> if (blockTypes.containsKey(key)) {
>   return blockTypes[key]!; // blockTypes[key] is non-nullable
> } else {
>   throw ArgumentError('Could not read block type.');
> }
> ```

From my point of understanding this should be changed to something like this:

> ## How do I signal that the return value from a Map is non-nullable?
> Do not try to do that. Simply test whether the return value is null or not.
> 
> ```dart
> final blockType = blockTypes[key]
> if (blocktype != null) {
>   return blocktype;
> } else {
>   throw ArgumentError('Could not read block type.');
> }
> ```

The argument being, that in multithreaded code the code snippet as present in the FAQ now could actually fail with a null pointer exception, due to the value at key being possibly removed between the `containsKey()` check and the actual use of the lookup operator `[]`.

**Comment by NinaPacifier** [comment]
@SebastianJL I am new to open source. May I work on this issue??

**Comment by kwalrath** [comment]
This content is from an internal FAQ, so I need to get a call from them. @ryanmcginnis, would you be able to follow up?

**Comment by ryanmcginnis** [comment]
hey @davidmorgan WDYT?

**Comment by davidmorgan** [comment]
Thanks for the suggestion Sebastian!

But actually that's not needed in Dart, which uses `async`/`await` for code that would be multithreaded code in other languages. Because there is no `async` code in the snippet, it's not possible for the map to change.

**Comment by SebastianJL** [comment]
@davidmorgan

Yes, but I think the unsuspecting user might still use this in async code, as the faq is written for null safety issues and isn't focused on sync code. May I sugest adding a note about async code with my suggested code example?

**Comment by SebastianJL** [comment]
Isn't something like this conceiveable?

```dart
if (blockTypes.containsKey(key)) {
  await someOtherImportantThing():
  return blockTypes[key]!;
} else {
  throw ArgumentError('Could not read block type.');
}
```

Or is my example to contreived?

**Comment by davidmorgan** [comment]
Yes, your example has a race condition if the map is updated elsewhere.

That applies to any Dart code, though; I'm not sure we need to call it out here.

That said, the example is already a bit contrived and could maybe be improved. Most often what you actually want is just:

```
return blockTypes[key]!;
```

and you'll only occasionally want to add an explicit check for the null. How about we change the whole thing to:

---
In this case, you should use the bang operator (!) to cast the value back to V:

```
return blockTypes[key]!;
```

Which will throw if the map returns null. If you want explicit handling for that case:

```
var result = blockTypes[key];
if (result != null) return result;
// Handle the null case here, e.g. throw with explanation.
```

---
?

**Comment by SebastianJL** [comment]
Would be fine by me.

**Comment by SebastianJL** [comment]
@davidmorgan 
I added a pull request with your proposed changes. Please accept or close.
