### ISSUE TITLE
ECMA standard

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#280]
_From @wmleler on May 19, 2017 1:33_

I know this might sound silly, but we really should mention the fact that Dart is an ECMA standard on the Dart website. Of course, before we do this, we should probably update the standard, since the most recent version is from 2015.

_Copied from original issue: dart-lang/site-webdev#635_

**Comment by chalin** [comment]
_From @filiph on May 19, 2017 1:42_

Fair point

/cc @kasperl -- how's the ECMA standard process these days?

**Comment by chalin** [comment]
Good point, but I think that this should be open over https://github.com/dart-lang/site-www.

cc @kwalrath @Sfshaza

**Comment by kwalrath** [comment]
I'm not sure what the status is of the ECMA standard process. @leafpetersen?

**Comment by kwalrath** [comment]
No movement on this, as far as I know.

**Comment by mit-mit** [comment]
I believe this is accurately covered on https://dart.dev/guides/language/spec
