### ISSUE TITLE
'What’s new' page issue

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2814]
Page URL: https://dart.dev/guides/whats-new
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/whats-new.md

Don't forget to add https://dart.dev/dart-team-packages.

**Comment by Dxree** [comment]
Hey @kwalrath, I know you assigned yourself to the issue, but if you do want to turn it in, I could take care of it. 
I would just need a quick info where I should add the missing resource in the page.

**Comment by kwalrath** [comment]
Thanks @Dxree! I think it should go in a new section at the top called something like "Changes after 2.10". (We'd presumably change the title and its description after our next stable release.) We'd also need to delete `toc: false` from the top of the file.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/pull/3048
Closes https://github.com/dart-lang/site-www/pull/2842 as well
