### ISSUE TITLE
FAQ (null safety) should mention `growable` optional parameter for `List.generate()`

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/site-www#2837]
With my understanding, `List<int>(10)` generates a fixed length list, ~~while `List<int>.filled(10,0)` generates a growable list which is very slow with subscripting.~~
~~The page should also mention `List<int>.generate(10, generator, growable: false)` replacing `List<int>(10)` in some case.~~
We sometime have to migrate unnamed `List` constructor to `generate()` to avoid initialize members twice.
But, the default of `growable` flag in `generate()` is `true`, and it is source of trouble, because subscripting on growable `List` is very slow.
I propose that the FAQ will introduce an additional example for migrating to `generate()` noting the default value of `growable`.

**Comment by kwalrath** [comment]
Thanks for the suggestions, @Cat-sushi!

@davidmorgan, what do you say?

/cc @ryanmcginnis

**Comment by davidmorgan** [comment]
Hmm, it looks to me like `List.filled` defaults to `growable: false` which makes it equivalent

https://api.dart.dev/stable/2.10.4/dart-core/List/List.filled.html

**Comment by Cat-sushi** [comment]
Sorry, I misunderstood.
`filled()` creates fixed length lists.

 `generate()` create growable lists, anyway.
It is confusing, and I fell into the trap.
