### ISSUE TITLE
Fix links on linux package install page

### ISSUE THREAD

**Issue by whesse** [dart-lang/site-www#284]
The address of the debian packages has changed from
https://storage.googleapis.com/dart-archive/channels/dev/release/latest/linux_packages/debian_wheezy/dart_1.24.0-dev.5.0-1_amd64.deb
(for example) to 
https://storage.googleapis.com/dart-archive/channels/dev/release/latest/linux_packages/dart_1.24.0-dev.5.0-1_amd64.deb

The debian_wheezy component is removed.

The page https://www.dartlang.org/install/linux uses these links on the big blue buttons at the bottom of the page.

Please update the links.
I'll copy the stable release to the corresponding new location, so you can do both changes at once.

**Comment by Sfshaza** [comment]
Fixed.  PR https://github.com/dart-lang/site-www/pull/290
