### ISSUE TITLE
Switch from recommending Travis

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#2844]
In this document, we refer to Travis and Appveyor as our recommended solutions for GitHub CI. Now that Travis is closing down travis-ci.org, we might consider recommending GitHub Actions instead, since that's what we're using ourselves.

https://github.com/dart-lang/site-www/blob/d41a3870ed19c81c80c91a5c5a362adde304cd16/src/_guides/testing.md#L131-134

**Comment by kwalrath** [comment]
SGTM. @RedBrogdon wdyt?

**Comment by RedBrogdon** [comment]
Sounds like a good idea to me.

**Comment by AliAkberAakash** [comment]
I've added a pull request for this in #2903
