### ISSUE TITLE
Mention that `dart fix` debuts in 2.12

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/site-www#2858]
We should update the dart cli doc page to mention `dart fix`.

**Comment by kwalrath** [comment]
This debuts in 2.12, right @devoncarew?

**Comment by devoncarew** [comment]
> This debuts in 2.12, right @devoncarew?

Yup

**Comment by kwalrath** [comment]
> > This debuts in 2.12, right @devoncarew?
> 
> Yup

Ha, I forgot that when I created the link & page. I should update those pages to mention that.
