### ISSUE TITLE
Address TODO related to running browser tests

### ISSUE THREAD

**Issue by woinbo** [dart-lang/site-www#2860]
TODO's related to analyzing Dart code in the repo:

 - [x]  TODO After dart CLI ships in stable, use dart analyze for all channels. [link to file](https://github.com/dart-lang/site-www/blob/master/tool/dart_tools/bin/update_analyzer_txt.dart) (fixed by https://github.com/dart-lang/site-www/commit/1510195ad47ba2abb34f2e50d5d084eb19884ffe)
 
- [ ]  TODO(chalin): as of 2019/11/17, we don't need to select individual browser test files. Run browser tests over all files, since VM-only tests have been annotated as such.
   [link to file](https://github.com/dart-lang/site-www/blob/master/tool/analyze-and-test-examples.sh)

@kwalrath (#2119 )

**Comment by parlough** [comment]
I've updated this as the first TODO was fixed and removed by https://github.com/dart-lang/site-www/commit/1510195ad47ba2abb34f2e50d5d084eb19884ffe

The remaining issue/TODO still exists.

**Comment by parlough** [comment]
The site and how the tests are ran has gone through a complete rearchitecture since this issue was made, so I'm going to close this. If anyone would still like to see further improvements, please open a new individual issue. Thanks so much!
