### ISSUE TITLE
Address TODOs related to regexp

### ISSUE THREAD

**Issue by woinbo** [dart-lang/site-www#2861]
TODOs related to Regexp:

 - [ ]  TODO: maybe style special characters inside a regexp as punctuation. [link to file](https://github.com/dart-lang/site-www/blob/dd7abec8d8b31c4d8a78c7c469d3186c99d74512/src/_assets/js/vendor/code-prettify/prettify.js)

@kwalrath (#2119)

**Comment by kwalrath** [comment]
Looks like these TODOs are in something we depend on — not our own source code. (Sorry I didn't notice this before!)

**Comment by woinbo** [comment]
No problem @kwalrath, these all activities are giving me a great experience😊.
