### ISSUE TITLE
Address TODOs related to versions

### ISSUE THREAD

**Issue by woinbo** [dart-lang/site-www#2862]
### we need to refactor these TODO's if someone interested does comment on this issue. These issues are realated to `version`

Find pages with TODO's, and refactor them by changing code or add new code to that file.

Here's a list of the 11 pages we should look at and eventually update (there might be more that don't show up due to improper formatting): 
* Version related:
 - [ ] TODO: identify versions (on line number 767)
 - [ ] TODO: identify versions (on line number 781) [link to file](https://github.com/dart-lang/site-www/blob/dd7abec8d8b31c4d8a78c7c469d3186c99d74512/src/_assets/js/vendor/jquery-3.4.1.js)

**Comment by kwalrath** [comment]
Looks like these are TODOs in things we depend on... not in our source code.
