### ISSUE TITLE
AVOID using curly braces in interpolation when not needed. The example is wrong

### ISSUE THREAD

**Issue by ucallz** [dart-lang/site-www#2869]
Page URL: https://dart.dev/guides/language/effective-dart/usage
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/usage.md

Description of issue:

https://dart.dev/guides/language/effective-dart/usage#avoid-using-curly-braces-in-interpolation-when-not-needed 

The second row is wrong

```
'Hi, $name!'
    "Wear your wildest $decade's outfit."
    'Wear your wildest ${decade}s outfit.
```

**Comment by kwalrath** [comment]
I'm pretty sure the code is correct, but I'll let @munificent decide whether it could be better/clearer.
