### ISSUE TITLE
'webdev' page issue

### ISSUE THREAD

**Issue by brainee** [dart-lang/site-www#2871]
Page URL: https://dart.dev/tools/webdev.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/webdev.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
the following packages's versions are too old
build_runner: ^1.0.0
    build_web_compilers: ^0.4.0

it will rase up a bug
webdev could not run for this project.
The `build_runner` version – 1.1.3 – is not within the allowed constraint – >=1.6.2 <2.0.0.
The `build_web_compilers` version – 0.4.4+3 – is not within the allowed constraint – >=2.12.0 <3.0.0.

update to the following versions will help.
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.12.0 <3.0.0"

**Comment by RandalSchwartz** [comment]
```
build_runner: ">=1.6.2 <2.0.0"
build_web_compilers: ">=2.12.0 <3.0.0"
```
could be also written more simply as:
```
build_runner: ^1.6.2
build_web_compilers: ^2.12.0
```
