### ISSUE TITLE
New diagnostic message documentation

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/site-www#2875]
New diagnostic message documentation has been added in the sdk repo (https://dart-review.googlesource.com/c/sdk/+/179880) and is ready to be integrated into https://dart.dev/tools/diagnostic-messages.

**Comment by bwilkerson** [comment]
Should these be live on the site now, or does it take a while? I'm not seeing some of the messages that I expected to see (such as MAIN_FIRST_POSITIONAL_PARAMETER_TYPE).

**Comment by kwalrath** [comment]
> Should these be live on the site now, or does it take a while? I'm not seeing some of the messages that I expected to see (such as MAIN_FIRST_POSITIONAL_PARAMETER_TYPE).

They should be live now, but it looks like Travis is not cooperating. Let me follow up on this...

**Comment by kwalrath** [comment]
I tried kicking off a new build.

**Comment by bwilkerson** [comment]
Thanks!

**Comment by kwalrath** [comment]
It still hasn't started. 😭

**Comment by kwalrath** [comment]
Still not started... Our move to GitHub Actions can't come soon enough.

**Comment by kwalrath** [comment]
I did a manual push, and the new content is now visible on dart.dev (e.g. https://dart.dev/tools/diagnostic-messages#main_first_positional_parameter_type). 😓

**Comment by bwilkerson** [comment]
Thanks!
