### ISSUE TITLE
Language tour: Anonymous Functions mistaken "statement" when meaning "return expression"

### ISSUE THREAD

**Issue by RandalSchwartz** [dart-lang/site-www#2878]
> If the function contains only one statement, you can shorten it using arrow notation. 

No, if the function contains only *one expression* and that expression is *being returned* as the value of the function...

Sadly, the only example uses the print() function, which returns void, and some confuse it with a statement.  This can definitely use a clean-up.

**Comment by kwalrath** [comment]
Looks like I fixed this in #3039.
