### ISSUE TITLE
Mistake in explaining making a POST request from a standalone client in httpserver.md

### ISSUE THREAD

**Issue by zakariaz** [dart-lang/site-www#2886]
Hi,

i found a mistake in the the documentation when trying to learn dart, since i never contributed before to a project, i missed the point that i had to fill an issue first before making a pull request. So better later than never.

here is the link to the [pull request](https://github.com/zakariaz/site-www/pull/1)

Thank you for the amazing work that you are doing

**Comment by kwalrath** [comment]
Thank you for the PR! I'll approve it once you move it over to our repo.

**Comment by zakariaz** [comment]
You are welcome.
Merge done

**Comment by kwalrath** [comment]
Reopening (see https://github.com/zakariaz/site-www/pull/1#issuecomment-768450707).

**Comment by zakariaz** [comment]
Hello,

I am very confused, i merged it against my own repo! 

i did a proper pull request to the official repo so it can be merged. Thank you 

here is the link to the [pull request](https://github.com/dart-lang/site-www/pull/2939#ref-pullrequest-787064061l)
