### ISSUE TITLE
Remove mention of the resource package

### ISSUE THREAD

**Issue by legolas108** [dart-lang/site-www#2887]
Page URL: https://dart.dev/tools/pub/package-layout.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/package-layout.md

"You can reference another package’s assets using the [resource package](https://github.com/dart-lang/resource)." references a deprecated package. What's the alternative replacing this package, please?

**Comment by kwalrath** [comment]
@kevmoo what should we say?

**Comment by kevmoo** [comment]
CC @munificent @lrhn – I don't think we HAVE a replacement. 🤷

**Comment by lrhn** [comment]
We don't. It's not really possible.

The entire idea behind storing "resources" in the `lib/` directory and accessing them using `package:` URIs is fundamentally flawed when you do AOT compiling. It refers to *source* locations, and we don't have any well-defined way to ensure that the files are even available at run-time, and if they are, no promise about where they can be found.
I'm sure we could do something about that, but we'll quickly end up with resource manifests and deployment layout descriptors, and then going through a `package:` URI seems unnecessary.

The idea relied on the `Isolate` class knowing how to resolve `package` URIs at run-time, and the deployment somehow being able to place the files where they would be found. That worked very well for the JIT VM, and not really for anyone else. It was made to work for dart2js web deployment by having a fixed location for the files from the packages (and probably some kind of logic to copy the files from the source `lib/` to there), but I don't think that really scaled.

Dart does not have a "resource"/"asset" story. This was an attempt, it did not work.

**Comment by kwalrath** [comment]
@legolas108 thanks for the issue. Although the answer isn't the one we might have hoped for, at least we know that we should remove the reference to the `resource` package. Would you like to edit the page?
