### ISSUE TITLE
Wrong class named on "Intro to Dart for Java Developers -- Use optional parameters"

### ISSUE THREAD

**Issue by neilself** [dart-lang/site-www#289]
Under the section titled "Improve the output", it says, "Add the following toString() function to the Bicycle class:", but we're working with the Rectangle class, not the Bicycle class. The Bicycle class was used as an example on the previous page.

**Comment by Sfshaza** [comment]
Good catch, @neilself! I've fixed it in the source but there is a publication issue that will hopefully be resolved next week.

Thx!

**Comment by Sfshaza** [comment]
It's fixed!  Thx

**Comment by neilself** [comment]
Thanks for the quick response Shams!
