### ISSUE TITLE
Suggest using `dart pub upgrade --null-safety`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#2909]
Page URL: https://dart.dev/null-safety/migration-guide#update-dependencies
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/migration-guide.md

![AxZW6XRQLAt2pQL](https://user-images.githubusercontent.com/149732/106788648-81bd8f00-6651-11eb-9261-0bdcfce40c9d.png)

Maybe we should recommend `dart pub upgrade --null-safety`, now that it also works reasonably under flutter.

The command also comes with `dart pub upgrade --null-safety --dry-run` which doesn't modify your `pubspec.yaml`.
Finally, if some of your dependencies doesn't support null-safety yet, it'll tell you specifically which dependencies are problematic. And it'll give you a command to upgrade to null-safety partially. It's not a good idea to start writing null-safety code before all dependencies are upgraded to null-safety, but upgrading half of your dependencies while you wait for the other half is perfectly fine. Or you might know that the unmigrated dependencies isn't something you import, maybe it's just assets, and then it might not be as important that they be migrated.

In general, I don't think we need to say much about the partial null-safety migration, except that we discourage it. The implications can be hard to understand. Hence, I don't think we need to point out that the tool can do such partial migrations, just that it can help with upgrading the `pubspec.yaml`, and that partial migrations are discouraged.

<details>
<summary>
<b>Example where migration isn't possible..</b>
</summary>

```
[gallery]$ dart pub upgrade --null-safety --dry-run
null-safety compatible versions do not exist for:
 - google_fonts
 - package_info
 - web_benchmarks

You can choose to upgrade only some dependencies to null-safety using:
  dart pub upgrade --nullsafety flutter_localized_locales cupertino_icons animations scoped_model collection vector_math flutter_gallery_assets flutter_staggered_grid_view provider meta url_launcher rally_assets intl adaptive_breakpoints shrine_images path grinder test string_scanner pedantic args

Warning: Using null-safety features before upgrading all dependencies is
discouraged. For more details see: https://dart.dev/null-safety/migration-guide
```

</details>

<details>
<summary>
<b>Example where migration is possible...</b>
</summary>

```
Resolving dependencies...
> adaptive_breakpoints 0.0.4 (was 0.0.3)
> animations 2.0.0-nullsafety.0 (was 1.1.2)
  archive 3.0.0-nullsafety.0
...
> url_launcher_platform_interface 2.0.0-nullsafety.1 (was 1.0.9)
> url_launcher_windows 0.1.0-nullsafety.2 (was 0.0.1+3)
  vector_math 2.1.0-nullsafety.5
  vm_service 6.0.1-nullsafety.1 (6.0.1 available)
  webdriver 3.0.0-nullsafety.1
These packages are no longer being depended on:
- flutter_web_plugins 0.0.0 from sdk flutter
- js 0.6.3-nullsafety.3
- node_interop 1.2.0
- node_io 1.1.1
- url_launcher_web 0.1.5+1
Downloading grinder 0.9.0-nullsafety.0...
Downloading provider 5.0.0-nullsafety.3...
Downloading animations 2.0.0-nullsafety.0...
Downloading url_launcher 6.0.0-nullsafety.6...
Downloading glob 2.0.0-nullsafety.0...
Downloading cli_util 0.3.0-nullsafety.0...
Changed 25 dependencies!
23 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Changed 19 constraints in pubspec.yaml:
  intl: >=0.16.1 <=0.17.0 -> ^0.17.0-nullsafety.2
  flutter_localized_locales: >=1.1.1 <=2.0.0 -> ^2.0.0-nullsafety.1
  cupertino_icons: ^1.0.0 -> ^1.0.2
  rally_assets: ^2.0.0 -> ^3.0.1
  meta: ^1.1.8 -> ^1.3.0-nullsafety.6
  ...
  adaptive_breakpoints: ^0.0.2 -> ^0.0.4
  path: any -> ^1.8.0-nullsafety.3
  grinder: ^0.8.0 -> ^0.9.0-nullsafety.0
  pedantic: ^1.9.0 -> ^1.10.0-nullsafety.3
  string_scanner: ^1.0.5 -> ^1.1.0-nullsafety.3
```

</details>

**Comment by mit-mit** [comment]
sgtm

**Comment by kwalrath** [comment]
In https://dart.dev/null-safety/migration-guide#check-dependency-status, should we feature `dart pub upgrade --null-safety --dry-run` instead of `dart pub outdated --mode=null-safety`? And then take off the `--dry-run` for https://dart.dev/null-safety/migration-guide#update-dependencies?

Might we still want to talk about `dart pub outdated --mode=null-safety` anywhere (e.g. in https://dart.dev/null-safety/migration-guide#migration-tool, but maybe with more explanation)?

**Comment by Sameerkash** [comment]
This would be handy as I'm currently migrating some of the packages and I found it a tedious task to copy past each dependency to their key, also the tricky part was, the `tick` mark would also get copied along and with my editor having autosave, pub would run and throw error all the time I modify the file.

**Comment by mit-mit** [comment]
I would recommend first running `dart pub outdated --mode=null-safety` to undertand the status, and then change the guidance to run `dart pub upgrade --null-safety` where it currently says to manually edit the pubspec. Note that we also changed the output of `dart pub outdated ` do suggest that, so would be great to update the UI text shown in docs.

**Comment by mit-mit** [comment]
I think this happened in https://github.com/dart-lang/site-www/commit/bc51d0bb90ca195d28ebc86bff240ce6e293ae42#diff-55449b49f1a140f943f5da5518584bb3e32db53f3452e2a15975bc041109fbd6
