### ISSUE TITLE
Fix the beta & dev builds

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2911]
I worked around the dev build breakage in #2910, but I think one of our recent migrations broke the build somehow.

**Comment by parlough** [comment]
I believe these are working again with the switch to Github actions: https://github.com/dart-lang/site-www/pull/2921 :D

For example: https://github.com/dart-lang/site-www/runs/1881433095

**Comment by kwalrath** [comment]
GHA doesn't surface allowed failures well, but I believe (if you look at, say, https://github.com/dart-lang/site-www/actions/runs/558615064) that 5 tests are still failing:

* test (stable, ./tool/analyze-and-test-examples.sh --null-safety, true) (this can't pass until 2.12 stable)
* test (beta, ./tool/analyze-and-test-examples.sh --null-safety, true)
* test (beta, ./tool/analyze-and-test-examples.sh, true)
* test (dev, ./tool/analyze-and-test-examples.sh --null-safety, true)
* test (dev, ./tool/analyze-and-test-examples.sh, true)

**Comment by kwalrath** [comment]
Taking a quick look at [.github/workflows/build.yml](https://github.com/dart-lang/site-www/blob/master/.github/workflows/build.yml), it seems like when I fix any of those tests, I should change `experimental` to `false`. Is that correct, @athomas?

**Comment by athomas** [comment]
@kwalrath Correct. I haven't really looked into what `--null-safety` does in those scripts. Hopefully that flag can be retired post 2.12 and all the steps using the flag can be removed completely.
