### ISSUE TITLE
is! description should be flipped

### ISSUE THREAD

**Issue by nosmirck** [dart-lang/site-www#2913]
https://dart.dev/guides/language/language-tour#type-test-operators

The operator/description table looks like this:

Operator | Meaning
-- | --
as | Typecast (also used to specify library prefixes)
is | True if the object has the specified type
is! | False if the object has the specified type
-- | --

But the actual behaviour for `is!` should say: False if the object **doesn't** have the specified type

**Comment by kwalrath** [comment]
I believe this is correct as written, although it might be easier to understand if we turned it around:

True if the object **doesn't** have the specified type

**Comment by parlough** [comment]
@kwalrath I agree, flopping the conditional here introduces a more clear separation between the two. It also follows how I personally read its use in an expression:

```dart
if (myPet is! Piranha) { // If my pet is NOT a piranha, pet it
  myPet.pet();
}
```

**Comment by nosmirck** [comment]
> I believe this is correct as written, although it might be easier to understand if we turned it around:
> 
> True if the object **doesn't** have the specified type

OMG! That's totally right! It's actually correct but because of the way we read it as `is not` reading that False at the beginning and saying that matches the type confused the hell out of me!

I'm closing this but leaving the suggestion open to maybe change it to:

True if the object **doesn't** have the specified type

Thanks for the clarification!

**Comment by kwalrath** [comment]
I'm going to reopen because I do want to make this less confusing (plus I'm actively working on the language tour right now).
