### ISSUE TITLE
Use Docker for building

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#2918]
Adding a `Dockerfile` to the repo would simplify the environment setup and make it consistent across Linux, macOS, and Windows. This would keep the existing tools we have, but allow Docker users to skip installing RVM and NVM. @btobin has experience building a Jekyll site this way.

Previous discussion here: https://github.com/dart-lang/site-www/issues/2685

This also applies to flutter/website infrastructure, and could be shared in the https://github.com/dart-lang/site-shared repo.

**Comment by Sameerkash** [comment]
Since I had pain setting up the environment, I'd really love to work on this. 
I'll wait till the first triage ? 

Cc @kwalrath

**Comment by kwalrath** [comment]
Thank you for volunteering, @Sameerkash! @johnpryan and @athomas the ones who've most recently work on the site build, so I'll let them answer you.

**Comment by Sameerkash** [comment]
@kwalrath I recently got some more exposure to jekyll in one of the programs I'm a part of. 

So if there's an other issues that is up for grabs (if this particular one isn't) I'd really like to contribute more this repo. 

So please @ me and I'll take a look asap.

**Comment by kwalrath** [comment]
@Sameerkash that's great to hear! Right now we're kind of heads down, but after the Flutter event I'd love to talk with you about how you could contribute to site infrastructure. (We're trying out [Flutter's Discord server](https://github.com/flutter/flutter/wiki/Chat) for discussions like this that aren't tied to a particular issue.)

**Comment by Sameerkash** [comment]
Thanks @kwalrath I'm active on the flutter discord server. 

Would love to hear more from you there.

**Comment by athomas** [comment]
I'm supportive of this idea. I've spent a bit of time over the last couple of days to understand how the various site-* scripts hang together and what they do. Quite a bit of complexity comes from trying to work in a local environment where all sorts of things may be in the wrong state. If we'd switch to a dockerfile-based approach, the local environment is isolated from whatever weird configuration happens on the developers' machine. Thus, the dockerfile could be a lot simpler than the current collection of scripts (it always starts from a known good state).

**Comment by kwalrath** [comment]
I'm not sure how this will affect your work, @athomas, but we're planning to freeze the sites for a week, starting 2/24. We should talk...

**Comment by kwalrath** [comment]
For more context, check out [our conversation on the Discord channel](https://discord.com/channels/608014603317936148/613844675949887491/818894402603843584) (requires a login).

**Comment by parlough** [comment]
Implemented by https://github.com/dart-lang/site-www/commit/99fd6c7e61d2dc70809bed4b3dd6efe8fd5b2470
