### ISSUE TITLE
It's very troublesome to import extension function.

### ISSUE THREAD

**Issue by SuperBeagleDog** [dart-lang/site-www#2920]
**Code Snippet.**
`  extension Foo on String{
    void test(){}
 }`

**In this case,** 
we can't simply use test() function on an instance of String, 
Like this ` "test".test()` with **"alt+Enter" automatically importing**:

We can't use **"quickly import"** feature in Android Studio to give an instance of String the ability to call test() method in Dart.

**Kotlin can do this but Dart can't!** 

To import this extension function, I either copy the path of "Foo" , or type Foo name in another file to get "quickly import feature" and then delete this useless name.

Therefore, I hope you can improve this issue as quickly as you can, or give us an easier way to import extension functions.

**Thanks.**

**Comment by parlough** [comment]
I can see how this feature would be nice, especially since people are familiar with it in other languages.

This repository is for the Dart website and this is more of a request for an addition to the analysis server which is in the [sdk repository](https://github.com/dart-lang/sdk). You can [create an issue](https://github.com/dart-lang/sdk/issues/new) there, specifying it's for the analysis server.

**Comment by SuperBeagleDog** [comment]
> I can see how this feature would be nice, especially since people are familiar with it in other languages.
> 
> This repository is for the Dart website and this is more of a request for an addition to the analysis server which is in the [sdk repository](https://github.com/dart-lang/sdk). You can [create an issue](https://github.com/dart-lang/sdk/issues/new) there, specifying it's for the analysis server.

I'm not sure what did you want to say, I just issue a problem that Dart can't use extension function feature as easily as Kotlin does, and hope the Dart team can improve it. Thanks.

**Comment by parlough** [comment]
不好意思，我好久没用中文，但我的意思就是-

这个仓库是Dart网站的，你应该在Dart的[sdk仓库](https://github.com/dart-lang/sdk/issues/new)写这个问题。

**Comment by SuperBeagleDog** [comment]
> 不好意思，我好久没用中文，但我的意思就是-
> 
> 这个仓库是Dart网站的，你应该在Dart的[sdk仓库](https://github.com/dart-lang/sdk/issues/new)写这个问题。

Got it, Thank you.

**Comment by kwalrath** [comment]
Thanks for the help, @parlough! I hope you get what you need, @SuperBeagleDog.

**Comment by parlough** [comment]
As a reference(if anyone comes across this) the new issue was opened at https://github.com/dart-lang/sdk/issues/44875
