### ISSUE TITLE
Add documentation about publishing previews

### ISSUE THREAD

**Issue by guidezpl** [dart-lang/site-www#2923]
Alongside documentation about pre-releases https://dart.dev/tools/pub/publishing#publishing-prereleases, we should add documentation about preview packages (e.g. https://pub.dev/packages/intl/versions/0.17.0)

**Comment by kwalrath** [comment]
@mit-mit we should talk about this today

**Comment by kwalrath** [comment]
Got the details from mit:
* As a developer, you don't have to do anything to make your release a preview release _or_ to graduate it to a stable release.
* Pub.dev shows a package release as a Preview release when the published package's min SDK (in the pubspec) is an SDK that doesn’t yet have a stable release.

Example: The 0.17.0 version of the intl package has a [min SDK of 2.12.0-0](https://github.com/dart-lang/intl/blob/ed19735eba648cf10d5d6e6dc9b23b277017cb56/pubspec.yaml), so it's [currently displayed]( https://pub.dev/packages/intl/versions) as a Preview version. As soon as 2.12 has a stable release, intl's 0.17.0 version will be displayed as Latest (if no newer releases exist) and Stable.

**Comment by guidezpl** [comment]
Makes sense, matches my expectations
