### ISSUE TITLE
Consider flipping the order of language versions

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#2926]
Page URL: https://dart.dev/guides/language/evolution
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/evolution.md

Just opening an issue to gather feedback on the the order of language versions may benefit from being reversed. I imagine as a user visits this page, they'd expect to see the most recent versions first. It's likely those are likely the versions they'd care about most.

There may have been an appropriate reasoning for this order though, so if that was the case, let me know!

**Comment by kwalrath** [comment]
My inclination is also to see most recent things first (more helpful for finding which minimum language version you need), but I think @mit-mit was thinking of this more like "this is our history".

**Comment by parlough** [comment]
Thinking about it some more, I can definitely see this page's use as a chronological evolution since we have plenty of other places where changes are outlined in reverse chronological order.
