### ISSUE TITLE
Redirect top 404s

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#293]
Our top 404s for the last month (excluding some that I hope are fixed by the addition of https://www.dartlang.org/guides/testing):

1. /downloads/archive
1. /)
1. /docs/pub-package-manager
1. /download
1. /tools/debian
1. /tools/download-editor
1. /dartium
1. /docs
1. /codelabs/polymer

**Comment by kwalrath** [comment]
In the past 30 days, the top few 404s (none of them worryingly high) were:

* /language-tour
* /api
* /dartium/home
* /tools/download-editor
* /codelabs/polymer
* /events/2013/flight-school
* /tools/debian
* /2.0

**Comment by Sfshaza** [comment]
WOW, flight school?!?!

**Comment by chalin** [comment]
@kwalrath - given that #384 has landed, can this be closed?
