### ISSUE TITLE
Update Android Studio icon in tooling page

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#2942]
Page URL: https://dart.dev/tools/
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/index.md

Description of issue: The tooling page includes the old Android Studio icon.

I tried to find a decent image of the new icon without the title, but all I could find is the following SVG. It has a circular white app background behind it which looked weird once added to the actual page:
https://raw.githubusercontent.com/JetBrains/android/f66ebcf239a05a3f7530f8f57acccf0730c22e77/adt-branding/src/artwork/androidstudio.svg

Perhaps internally you could reach out to someone who has the svg without the background

**Comment by kwalrath** [comment]
Will do. Thanks for letting us know, @parlough!

**Comment by kwalrath** [comment]
Filed b/180058612

**Comment by kwalrath** [comment]
I never did get a response on that internal issue, yeesh.
