### ISSUE TITLE
Packages / Package reference / Versioning doesn't explain the meaning of 2.12.0-0

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/site-www#2943]
[site-www/versioning.md at master · dart-lang/site-www](https://github.com/dart-lang/site-www/blob/master/src/tools/pub/versioning.md "site-www/versioning.md at master · dart-lang/site-www")

**Comment by atsansone** [comment]
@munificent : Is there an explanation for the `-0` part of a language version?

**Comment by munificent** [comment]
It never shows up in a *language* version (those are aways just `major.minor`) but in can show up in SDK versions. Those use [semver](https://semver.org/) syntactically. (The way we release the Dart SDK doesn't exactly follow semver *semantics*, for better or worse.)

The `-` suffix followed by stuff makes the version number [a "pre-release" version](https://semver.org/#spec-item-9). So, for example, `1.2.3-beta` refers to package that is almost but not quite `1.2.3`. In terms of ordering, `1.2.3-beta` is considered lower than `1.2.3` but higher than `1.2.2`.
