### ISSUE TITLE
Choclatey compusory - please clarify

### ISSUE THREAD

**Issue by mikeparr** [dart-lang/site-www#2947]
It reads   '..CAN be istalled with choclatey'
Is this a MUST?  Is there another way.  Is the Choclatey way easiest?

**Comment by kwalrath** [comment]
It's not a must; you can always download the SDK as a zipfile, and I think other installers are available. I, unfortunately, haven't installed the SDK on Windows in a very long time, so I can't give advice on what's easiest.

**Comment by mikeparr** [comment]
Thanks for the reply, Kathy.  I might look for other ways, to avoid installing an extra program (chocolatey)
Mike

------ Original Message ------

**Comment by parlough** [comment]
I don't use Windows much but when I do I prefer manually downloading the SDK as a zip from the [archive](https://dart.dev/tools/sdk/archive) and adding it to my PATH manually or selecting it in IntelliJ. 

@kwalrath Perhaps not the most appropriate repo for this, but supporting [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/) and [adding manifests](https://github.com/microsoft/winget-pkgs) for Dart to Microsoft's new package manager may be worth exploring. It would need some support similar to how @athomas supports the homebrew tap, but to me it seems like the future of package management for Windows.

**Comment by parlough** [comment]
Hey @mikeparr, I hope you were able to get Dart downloaded. If you have any issues or came across a solution that worked well for you, let us know :)

I'm going to close this issue for now, but there are issues open on the SDK repository to track improved distribution mechanisms on Windows, such as one for distributing on [winget](https://github.com/dart-lang/sdk/issues/43977).
