### ISSUE TITLE
solution is actually a hint..!

### ISSUE THREAD

**Issue by hamyarflutter** [dart-lang/site-www#2954]
in this link https://dart.dev/codelabs/dart-cheatsheet#code-example-11 solution is like a  hint...there is no assertion i think so

**Comment by parlough** [comment]
Could you elaborate on what you expect the solution to be?

Do you mean that you expected the "extra credit" assertion to be in the solution as well?

**Comment by hamyarflutter** [comment]
hi..
yes of course...
i think so..
i am new to dart but i think there is no "extra credit"!

thanks for support
