### ISSUE TITLE
Follow-up to null safety migration guide update

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2955]
Follow-ups to #2929:

* Remove `-nullsafety` from images.
* Be consistent with https://dart.dev/tools/pub/publishing#publishing-previews.
  * Maybe link to/from it.
  * Maybe remove some content from /null-safety/migration-guide if it isn't essential.
* Be consistent about release vs. version, especially in the final paragraph. 
* "Switch to the latest beta release" instead of "Switch to the latest 2.12 beta release".

/cc @kevmoo @mit-mit

**Comment by micpap25** [comment]
Working on this right now, also made #2991 based on my observations.
