### ISSUE TITLE
graphic doesn't match text

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#296]
https://www.dartlang.org/guides/libraries/create-library-packages#importing-library-files says "The following graphic shows how to import lib/src/foo/a.dart from both lib and web."

But the web example imports lib/foo/a.dart, not lib/src/foo/a.dart. Also, we shouldn't encourage people to import anything from lib/src into web/main.dart.

I noticed this while I was working on the webdev dartdevc docs, where I'm spelling out the rules for imports.

/cc @jakemac53

**Comment by kwalrath** [comment]
Also, for accessibility's sake, we should probably put the code in text, not [just] the image.

**Comment by faruk13** [comment]
@kwalrath  this issue can be fixed by updating the text from lib/src/foo/a.dart to lib/foo/a.dart in appropriate place right? Correct me if I am wrong, beginner here.

**Comment by kwalrath** [comment]
Yes, @faruk13, I think only the text update is necessary.
