### ISSUE TITLE
'Effective Dart: Usage' page issue: Link to `unnecessary_getters` lint rule is broken.

### ISSUE THREAD

**Issue by hankyusa** [dart-lang/site-www#2971]
Page URL: https://dart.dev/guides/language/effective-dart/usage
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/usage.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

Link to `unnecessary_getters` lint rule (https://dart-lang.github.io/linter/lints/unnecessary_getters.html) is broken. It's under the "[PREFER using a final field to make a read-only property.](https://dart.dev/guides/language/effective-dart/usage#prefer-using-a-final-field-to-make-a-read-only-property)" section.

**Comment by kwalrath** [comment]
Thanks for the report! Looks like it should perhaps be https://dart-lang.github.io/linter/lints/unnecessary_getters_setters.html.
