### ISSUE TITLE
Make /tools/dart-fix unique

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2981]
Incorporate everything from https://github.com/dart-lang/sdk/blob/master/pkg/dartdev/doc/dart-fix.md into https://dart.dev/tools/dart-fix, and update https://dart.dev/go/dart-fix to link to /tools/dart-fix.

More info: #2978

**Comment by parlough** [comment]
This was fixed in https://github.com/dart-lang/site-www/commit/5da4181681b8129c542af876766f993b2fd278e4 and expanded in https://github.com/dart-lang/site-www/commit/577aef5f3999a81bb04d0f47f845836c971a67df
