### ISSUE TITLE
Dart VM snapshot documentation seems out of date

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/site-www#299]
Source: https://www.dartlang.org/articles/dart-vm/snapshots.

As mentioned on Gitter, it talks about at least 2 concepts (object and "full" snapshots) that aren't user accessible types, and also omits the newer `app-jit` and `app-aot` types (if we want to document them, even just to mention they exist but aren't supported).

**Comment by kwalrath** [comment]
Thanks for the report, Matan.

@a-siva might you be able to update this article? You could either edit it at https://github.com/dart-lang/site-www/blob/master/src/_articles/dart-vm/snapshots.md or just mark up a printout and I can make the changes for you.

**Comment by a-siva** [comment]
Ryan do you want to take a stab at this when you have time?

**Comment by rmacnak-google** [comment]
The page at https://github.com/dart-lang/sdk/wiki/Snapshots is more recent and describes how to use app-jit snapshots. I'll look at updating the full article.

**Comment by kwalrath** [comment]
We could just make the article point to the wiki. One less thing to keep up to date.

**Comment by kwalrath** [comment]
We implemented a redirect to make https://www.dartlang.org/articles/dart-vm/snapshots point to https://github.com/dart-lang/sdk/wiki/Snapshots.
