### ISSUE TITLE
Standardize location of links in source

### ISSUE THREAD

**Issue by micpap25** [dart-lang/site-www#2991]
While working on the null-safety code, I noticed that all the links were in-place (that is, the url was right next to the text that would be displayed). This is different from how, say, the language tour does it, where all the urls are at the bottom of the source.

Obviously this isn't very high priority, but perhaps one method should be chosen and kept to.

**Comment by maheshmnj** [comment]
@micpap25  thanks for filing the issue could you please point to the source code where exactly you meant?

**Comment by parlough** [comment]
I think @micpap25 is referring to the website in general not being consistent in its practices across many pages. The specific examples though were the [Null safety migration guide](https://github.com/dart-lang/site-www/blob/master/src/null-safety/migration-guide.md) which places the declarations for reference style Markdown links near where they are used compared to the [language tour](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/language-tour.md) which places a large majority at the bottom.

Giving it some thought, I agree that it would be nice to standardize where we place links, but I also think both locations have their merits so it requires more than a one or the other guideline.

My general practice is to place links which I'm only using in that section or in just one place(to allow for better text formatting) nearby, perhaps at the bottom of the section. Then links which are (or likely will be) referred to throughout the page at the bottom.

**Comment by parlough** [comment]
I think the suggestion is to include links in the same section as you are writing unless it will be referenced throughout the page. Closing this in favor of https://github.com/dart-lang/site-www/issues/2991 about documenting processes in general.
