### ISSUE TITLE
Migrate library tour to null safety

### ISSUE THREAD

**Issue by filiph** [dart-lang/site-www#2992]
https://dart.dev/guides/libraries/library-tour should have null safe code. I'm on it.

**Comment by filiph** [comment]
Ok, I have the code ready and also the markdown ready. @kwalrath, should I try to land both with one PR? I see that the model https://github.com/dart-lang/site-www/pull/2891 only migrated the code.

**Comment by kwalrath** [comment]
Oh nice! One PR for both is fine. I hope you did separate commits for the initial copies, so it's easy to see what changed (she said belatedly).
