### ISSUE TITLE
Bad sharing text

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3]
Even when a description exists in the YAML, www & webdev pages use the first few lines of content as the summary.

And no image?

For example, sharing www.dartlang.org on G+ results in this ugliness:

![image](https://cloud.githubusercontent.com/assets/2164483/16821234/ff0d043c-4909-11e6-922f-a71f7f578ec0.png)

**Comment by filiph** [comment]
Fixed with a51a6c31a287775134deb794ccf7d061f2fd2486
