### ISSUE TITLE
PREFER relative imports within `lib` (exception: AVOID `..`)

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#300]
This rule came up in the review of https://github.com/dart-lang/site-webdev/pull/714.

In general, we might want to give more guidance about imports, such as AVOID importing from src (unless it's a relative import).

/cc @kevmoo, @chalin

**Comment by kevmoo** [comment]
CC @matanlurey – we talked about this a bit w/ some refactoring in pkg/angular2

This is also something we should look into WRT the analysis server and/or IntelliJ – the way it handles file moves now is a bit weird...
