### ISSUE TITLE
Remove/replace site.www in _config.yml

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3003]
We no longer use site.www (it's a legacy of back when we split dartlang.org, I think). We should do one of the following:

1. Delete it from `_config.yml`.
2. Change it to `dart-site` (to match [flutter.dev's _config.yml](https://github.com/flutter/website/blob/master/_config.yml)) and make it empty.

If option 2 works, I prefer that, in case we copy any text from flutter.dev to dart.dev.

**Comment by MrBirb** [comment]
@kwalrath I believe there has been fixed :D ?

**Comment by parlough** [comment]
Thanks for pointing that out!

Fixed by https://github.com/dart-lang/site-www/commit/51e1d2a98bf66a4d9b354b9406544b0ac2524482
