### ISSUE TITLE
'dart pub upgrade' page issue

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/site-www#3043]
Page URL: https://dart.dev/tools/pub/cmd/pub-upgrade.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/cmd/pub-upgrade.md

Description of issue:

Missing description of new(?) flag "--major-versions"

**Comment by micpap25** [comment]
Hi, seems that your issue is already part of #2898. I'm going to start working on this soon.

**Comment by Tomucha** [comment]
Cool, feel free to close this one.

Thanks!

**Comment by domesticmouse** [comment]
Thanks @Tomucha, de-duping
