### ISSUE TITLE
Follow up on _migrated PR

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3046]
As follow ups to #3039:

* Remove more /examples/.../library_tour/* files (from the repo & from /tool/dartformat.sh)
* Use a macro to shorten references to examples (e.g. "../null_safety_examples/misc/lib -> "lib") 
* Convert src/_guides/libraries/_dart-io-tour.md & src/_guides/libraries/_dart-html-tour.md to use null-safe code

**Comment by parlough** [comment]
I'm slowly working towards finalizing all the individual migrations. There's a few pieces remaining and once it's finalized I'll work on consolidating everything back to `examples` and updating `dartformat.sh` for all relevant changes.
