### ISSUE TITLE
Finish migration to null safety

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3055]
* Add interim not-null-safe notes to more pages (follow-up to #3051)
* Follow up on migrated page work (#3046)
* Migrate remaining code snippets (related: #1803)

**Comment by parlough** [comment]
I believe the majority, if not all, snippets are now updated to null safety. Any exceptions that come up can be addressed on a case by case basis. We will continuing tracking the work to test code excerpts in https://github.com/dart-lang/site-www/issues/1803
