### ISSUE TITLE
Update documentation about null-safety and 'implicit-casts: false'

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/site-www#3059]
The document here: https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks has an example with an implicit downcast and mentions that `implicit-casts: false` fixes this. However, this document: https://dart.dev/null-safety/understanding-null-safety says `So with null safety we are removing implicit downcasts entirely.` I tested it in my app and in dartpad and it works as advertised (i.e. it reports implicit casts as errors) with null safety.

(Without null safety, the code on dartpad works but the error is still mentioned, which seems to be a bug?).

Would it make sense to mention that `implicit-casts: false` is unnecessary if the source code has null-safety?

**Comment by kwalrath** [comment]
Thanks for reporting this, @wujek-srujek. @bwilkerson, what's your take?

**Comment by bwilkerson** [comment]
> "So with null safety we are removing implicit downcasts entirely."

It's my understanding (@munificent, please correct me if I'm wrong) that the quote above is a slight exaggeration and that null safety actually disallows all implicit downcasts _except_ for those from `dynamic`.

And it's also my understanding (@srawlins, please correct me if I'm wrong) that the option still reports an error in the case where an implicit downcast from `dynamic` is found.

Assuming that's all true, we should still make a couple of changes.

- We should update the example in to show a cast from `dynamic`.
- In the same document, we should consider rewriting the text "A value of false ensures that the type inference engine never implicitly casts to a more specific type.". I don't believe it's accurate to say that this option impacts the type inference engine.
- We might want to update to mention the exception.

**Comment by wujek-srujek** [comment]
Hi @bwilkerson you are right, I've just tested it, and implicit downcasting to dynamic still works, and `implicit-casts: false` reports this as error.

**Comment by munificent** [comment]
> It's my understanding (@munificent, please correct me if I'm wrong) that the quote above is a slight exaggeration and that null safety actually disallows all implicit downcasts except for those from dynamic.

That's right. Personally, I don't tend to think of casts from `dynamic` as "downcasts". I know technically they are because `dynamic` is *a* top type, but my mental model is more that `dynamic` steps outside of the concept of a type hierarchy entirely.

**Comment by parlough** [comment]
With the change to the new strict mode analyzer options in [Enabling additional type checks](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks) which have deeper explanations and examples, I think we're in a fine position. 

As for highlighting the exception for dynamic, I think Bob's thoughts about `dynamic` make sense and I feel highlighting the exception in that point of the Null safety article might be more confusing than helpful.

I'll close this issue as fixed by the further analyzer strict modes documentation, but feel free to reply here if you think more clarifications are needed. Thanks!
