### ISSUE TITLE
"Sound Dart" should be "Dart strong mode" 

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-www#306]
I'd like to propose that we change the title of https://www.dartlang.org/guides/language/sound-dart from "Sound Dart" to "Dart strong mode".

**Comment by kwalrath** [comment]
@filiph @kevmoo @Sfshaza @vsmenon: discuss

(I remember that we had a good reason for not calling it a "mode", but Shams knows more than I do.)

**Comment by Sfshaza** [comment]
Back when I was writing these docs, I was told not to use "strong mode" because, in future, it won't be a mode. It will just be the way it is. So let's make sure we have consensus.

@munificent

**Comment by kevmoo** [comment]
Eventually, we'll stop talking about it. But to get there, we'll have to talk about it quite a bit – I'm a fan of at least being consistent in how we refer to it. (Sound -> strong)

**Comment by Sfshaza** [comment]
Talked to Dan and Kevin about this. They are OK with just renaming the pages and not modifying the text (it may still require some modification).

**Comment by kwalrath** [comment]
Unfortunately, we have a lot of places that refer to these pages by name.

**Comment by chalin** [comment]
Firebase rewrite rules to the rescue?

**Comment by leafpetersen** [comment]
Don't have strong feelings.  Seems a little bit of a shame to be switching to talking about modes at this point.

**Comment by Sfshaza** [comment]
I have renamed the docs on www.dartlang and webdev.dartlang.

PR on www: https://github.com/dart-lang/site-www/pull/309
PR on webdev: https://github.com/dart-lang/site-webdev/pull/769
