### ISSUE TITLE
Revise explanation of read-only properties in Java & Dart Codelab 

### ISSUE THREAD

**Issue by devahmedsaleh** [dart-lang/site-www#3071]
In the Codelab:  [Intro to Dart for Java Developers](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#1), illustration of read-only properties is confusing.

> The original Java example defines speed as a read-only variable—it declares it as private and provides only a getter.

In the related Java code, `speed` is not _read-only_ property, this is shown in: 

```        
    private int speed;

    public void applyBrake(int decrement) {
        speed -= decrement;
    }

    public void speedUp(int increment) {
        speed += increment;
    }
```

Also: 

> You can convert speed to read-only by changing its name and adding a getter.
> **Make speed a private, read-only instance variable**

In Dart code, `speed` was made _private_ by adding `_`, but it is not _read-only_ as shown in: 

```
  void applyBrake(int decrement) {
    _speed -= decrement;
  }

  void speedUp(int increment) {
    _speed += increment;
  }
```

the public _getter_ `get speed` can be considered read-only variable not the private instance variable` _speed`.

**Comment by parlough** [comment]
I feel most of these issues could maybe be fixed by adjusting "variable" to "property", as property more closely refers to the external portion, in the Java case, `.getSpeed`, and in the Dart case, `.speed`, which is implemented with the underlying `_speed` variable.

@domesticmouse I'm going through some old issues and came across this one. Do you think any changes are needed here? If so, could you take a look?

**Comment by parlough** [comment]
The same page also links to https://dartpad.dev/?id=f176b4c31b4be8a454107d0946fe2fa3 (https://gist.github.com/Sfshaza/f176b4c31b4be8a454107d0946fe2fa3) which triggers the `unnecessary_new` lint with `new Bicycle`. Could you also fix that, perhaps with a new gist under flutterdevrelgists? 

I would fix these, but I don't have access to the codelabs.

**Comment by domesticmouse** [comment]
@parlough I'm happy to share this document with you if you want to take an edit pass. I'll update DartPad snippets so they don't have linter warnings.

**Comment by parlough** [comment]
That would be great @domesticmouse, thanks!

**Comment by domesticmouse** [comment]
Shared

**Comment by parlough** [comment]
Thanks for the issue!

This codelab has been retired in favor of other learning material which we are working on improving and expanding, as the codelab was not up to date with modern Dart. We will be releasing more learning material over time, and for now, have a bunch of samples at https://dart.dev/language and a detailed walkthrough of different Dart features, that is written in a way that should be familiar to Java developers. 

Thanks again!
