### ISSUE TITLE
Archived numeric computation article links to removed benchmarking article

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/site-www#3072]
URL: https://dart.dev/articles/archive/benchmarking
Expected page: An archived article about benchmarking

Found multiple times at https://dart.dev/articles/archive/numeric-computation

**Comment by kwalrath** [comment]
Here's the most recent version I could find of the benchmarking article:
https://web.archive.org/web/20160702204441/https://www.dartlang.org/articles/benchmarking/

So it was apparently removed between July and October, 2016.

We've gotten only a handful of requests for the benchmarking article in the past 30 days, so I think the easiest fix is to just remove the links from the numeric computation article.

**Comment by kwalrath** [comment]
Fixed by #3079
