### ISSUE TITLE
'Migrating to null safety' page issue

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/site-www#3074]
The guidance on[ this page](https://dart.dev/null-safety/understanding-null-safety#null-assertion-operator) currently endorses using ! operator to "cast away" nullability, as a workaround for the static analyzer's inability to trust null-checks on non-local vars.

This is fundamentally a risky approach, because it leaves future NPEs in the code. Consider:
```
void _handlePressed(){
  if(_controller == null) return;
  // ... 5+ lines of code in the middle
  useController(_controller!);
}
```

It's quite easy for some developer in the future to remove, or break the null check at the top, while leaving in the `!` at the bottom. Null analysis has been completely disabled for the property, and compiler will provide no hint at all that anything is wrong. 

This seems to work counter to many of the goals of NNBD, and any claim to being "sound" is gone once one of these enters the codebase. 

The above could be re-written:
```
void _handlePressed(){
  final c = _controller;
  if(c == null) return;
  // ... 5+ lines of code in the middle
  useController(c);
}
```
This stays type safe, and better reflects the real-world code developers will want to write, to work around the current language limitations and stay sound. The example from this page could be rewritten, without bangs, as: 
```
// Using null safety:
String toString() {
  if (code == 200) return 'OK';
  return 'ERROR $code ${(error ?? "").toUpperCase()}';
}
```

This shows 2 approaches to solving this problem that are both preferable to !. Either cache it locally, or create a local fallback with ??. 

**Proposal: Add a section after the ! operator section, basically explaining why you should never do it, and go through 3 or 4 examples of refactoring code snippets, to "cast away" the nullability in a more future-proof way.**

Even the simple 
```
if(map[key] != null){
   use(map[key]!);
}
``` 
is probably better expressed as:
```
final value = map[key];
if(value != null){
  use(value);
}
```
It's less sneaky, and have no chance to ever be broken in the future. If null check is ever removed, compiler will immediately flag it.

**Comment by kwalrath** [comment]
The proposal sounds reasonable, but presumably we introduced `!` for a good reason, so I'd like input from one of our language gurus.

/cc @mit-mit @munificent

**Comment by munificent** [comment]
> The guidance on[ this page](https://dart.dev/null-safety/understanding-null-safety#null-assertion-operator) currently endorses using ! operator to "cast away" nullability, as a workaround for the static analyzer's inability to trust null-checks on non-local vars.

It's not just a workaround for that. It's an escape hatch for any case where the static type system is too conservative and pessimistic and doesn't correctly understand that some code is dynamically code. It's exactly like an `as` expression. You try to avoid using them, but sometimes they are the best solution.

> This is fundamentally a risky approach, because it leaves future NPEs in the code.

Yes, just like `as` expressions can also potentially throw exceptions (as downcasts can in other languages too). The key point is that you can *see in the text of the program* where that exception might arise. The `!` is a visible signal to pay closer attention to that code.

> This seems to work counter to many of the goals of NNBD, and any claim to being "sound" is gone once one of these enters the codebase.

It is still fully sound. Soundness say that expression of type T will only ever produce a value of type T. An `!` expression has a non-nullable type and it does indeed guarantee that it will never evaluate to null—instead it throws a runtime exception.

This is just as sound as the index `[]` operator on List. That statically claims to produce an element of the list's type. If you pass in an out of bounds index, it upholds that promise by throwing an out of bounds exception at runtime.

> The above could be re-written:
> 
> ```
> void _handlePressed(){
>   final c = _controller;
>   if(c == null) return;
>   // ... 5+ lines of code in the middle
>   useController(c);
> }
> ```

Yes, that's a good pattern. See here: https://dart.dev/guides/language/effective-dart/usage#consider-copying-a-nullable-field-to-a-local-variable-to-enable-type-promotion

At the same time, `!` is also a useful tool and we need to document it somehow. It can be hard to come up with concise examples that are still well-motivated enough to show a feature. I think the one we have is OK—the `toString()` method is short enough that it feels like overkill to me to copy the field to a local variable.

> It's less sneaky, and have no chance to ever be broken in the future. If null check is ever removed, compiler will immediately flag it.

I get where you're coming from, but in practice it seems like judicious use of `!` isn't particularly painful or error-prone. We've migrated a *lot* of code to null safety and it seems to work out OK. Consider that Dart before null safety (and Java and C# even today) essentially have a hidden `!` before *every single* `.` and seem to still be tractable.

Our goal is to have better static safety around null, but not necessarily have a perfect *static* proof that no null reference exception can occur. Getting to that point seems to require making the code much more verbose with relatively little marginal benefit over simply avoiding `!` when you can and keeping an eye on it when you can't.
