### ISSUE TITLE
implement not extend Exception class 

### ISSUE THREAD

**Issue by devahmedsaleh** [dart-lang/site-www#3077]
In [Intro to Dart for Java Developers](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#3) Codelab, it is mentioned that: 

> The Dart SDK defines classes for many common exceptions, or you can `extend `the Exception class to create more specific exceptions or (as in this example) you can throw a string that describes the problem encountered.

But In Dart, we cannot `extend `the Exception class, it should be replaced by `implement`

**Comment by kwalrath** [comment]
Thanks for spotting this! You're right, I think: it should be _implement_.

**Comment by kwalrath** [comment]
@domesticmouse what's the best way for me to make this change?

**Comment by kwalrath** [comment]
I'll update the source doc now.

**Comment by kwalrath** [comment]
Looks like I made this change back in March.
