### ISSUE TITLE
"with with" typo in "Effective Dart"

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#3081]
In [AVOID writing incomplete generic types](https://dart.dev/guides/language/effective-dart/design#avoid-writing-incomplete-generic-types), there is a duplicate "with".

**Comment by kwalrath** [comment]
Sounds like a great bug for a new contributor to fix!

**Comment by rad10wave** [comment]
Can I work on this issue?

**Comment by kwalrath** [comment]
It's yours, @rad10wave!

**Comment by munificent** [comment]
Fixed!
