### ISSUE TITLE
DevTools documentation is out of date

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/site-www#3099]
The chart [here](https://dart.dev/tools/dart-devtools) is stale.

* Missing information about Flutter Desktop in general (all our tools are enabled for flutter desktop)
* Missing information about the [network](https://flutter.dev/docs/development/tools/devtools/network) view. Available for Flutter native (non-web) and Dart CLI.
* Missing information about the [app size](https://flutter.dev/docs/development/tools/devtools/app-size) view. Available for flutter native (non-web) and Dart CLI
* Timeline has since been renamed to Performance (title needs to be updated as well as hyperlink)
* Performance has since been renamed to Cpu Profiler (title needs to be updated as well as hyperlink)

**Comment by kwalrath** [comment]
Also, we should update the homepage's screenshot of DevTools (3rd bullet under Productive development), as mentioned in #2889.

**Comment by kenzieschmoll** [comment]
There is a pretty good gif of devtools on the flutter docs: https://flutter.dev/docs/development/tools/devtools/overview. Can we use that?
