### ISSUE TITLE
[Next Release] Update references to and documentation around Stagehand

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3101]
Various references will be need to be removed, updated, or added to with the transition to what was stagehand just being part of `dart create` as the explicit references to stagehand won't be so relevant or necessary anymore.

https://github.com/dart-lang/sdk/commit/f6ce7a829f288267fb9720a30346ff4c086001ab

**Comment by kwalrath** [comment]
`fgrep -Rl stagehand src` shows 5 occurrences of "stagehand" in the site:

- [ ] src/tools/dart-tool.md
- [ ] src/_tutorials/web/get-started.md
- [ ] src/_tutorials/server/get-started.md
- [ ] src/_tutorials/server/cmdline.md
- [ ] src/_guides/libraries/useful-lib

raries.md
