### ISSUE TITLE
downcast is no longer but in doc, it say that works. fix plz

### ISSUE THREAD

**Issue by srawlins** [dart-lang/site-www#3103]
@rlaehddnrwiki commented on [Thu Mar 25 2021](https://github.com/dart-lang/dartdoc/issues/2592)

![화면 캡처 2021-03-26 093839](https://user-images.githubusercontent.com/59792586/112561130-f02ff980-8e17-11eb-9d71-e9ba39eeee13.png)
![화면 캡처 2021-03-26 094216](https://user-images.githubusercontent.com/59792586/112561135-f1612680-8e17-11eb-8200-a17db565c311.png)
![화면 캡처 2021-03-26 094231](https://user-images.githubusercontent.com/59792586/112561137-f1f9bd00-8e17-11eb-82cf-0ab3f4df96f1.png)

---

@srawlins commented on [Thu Mar 25 2021](https://github.com/dart-lang/dartdoc/issues/2592#issuecomment-807892387)

@rlaehddnrwiki do you wish to report an issue with the dartdoc documentation generation system? Or perhaps an article or a website somewhere? Where did you see this text which you have screenshotted?

---

@parlough commented on [Fri Mar 26 2021](https://github.com/dart-lang/dartdoc/issues/2592#issuecomment-808014721)

This is on [dart.dev](https://dart.dev/null-safety/understanding-null-safety) and can be sourced to https://github.com/dart-lang/site-www/blob/master/src/null-safety/understanding-null-safety/index.md 

I can see where the confusion comes from in this doc, but the final sentence in the paragraph explains what's happening here, in that this behavior was removed with null safety. It believe it is using the example to illustrate what worked before(and I believe still does with unsound null safety?). Since this page is about understanding the changes that come with null safety, this makes sense, but there's perhaps improvements that could be made to make this clearer.

@srawlins If you move this issue to [site-www](https://github.com/dart-lang/site-www) more discussion or followup can be had. Thanks :)

**Comment by munificent** [comment]
That point in the article is explaining how Dart *would* have behaved if we had added null safety but kept implicit downcasts. But then it clarifies that we didn't do that. So I think we're OK.
