### ISSUE TITLE
How do we want to refer to dart_style(dartfmt) and its functionality?

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3111]
The [dart_style](https://pub.dev/packages/dart_style) package is used to implement `dart format` and previously/still `dartfmt`. There are places we refer to this package/functionality as `dartfmt`, `dart format`, and perhaps some other repositories refer to it as `dart_style`(we do but only in reference to the pub listing I believe). 

IntelliJ also has a lot of strings referring to it as `dartfmt` and I am confident that's not the only place.

Do we want to standardize on calling this functionality `dart format` across the ecosystem(what I expect) or does `dartfmt` still have a place? Perhaps something else entirely, I'm not sure.

Once I get some feedback I can work on updating various references in this repository and elsewhere. I'll switch this issue over to tracking that work.

**Comment by domesticmouse** [comment]
My understanding is that `dart format` is the new name for `dartfmt`. I don't know what the story is with `dart_style`.

@mit-mit can you clarify?

**Comment by mit-mit** [comment]
I would use the prose "The Dart formatter" or the tech term `dart format` regarding on the context. I would not refer to the repo name, which is an implementation detail, and may change.
