### ISSUE TITLE
'dart pub outdated' page issue

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#3115]
Page URL: https://dart.dev/tools/pub/cmd/pub-outdated.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/cmd/pub-outdated.md

**Description of issue:**

The output shown In the very first run of `dart pub outdated` command:

![image](https://user-images.githubusercontent.com/40364434/113410820-98176b00-93b4-11eb-9c65-dbdabc4eefd2.png)

As you can see here, `path` is a direct dependency but later on in the article it says 

> The `path` and `meta` packages are still out-of-date, due to reasons that this package doesn’t control. 

If `path` is not a direct dependency but rather a transitive, it should be printed in `transitive dependencies` tab. 

**Solution:**

We need to update the screenshot of terminal.

**Comment by kwalrath** [comment]
This was an actual screenshot, and I don't believe path was a transitive dependency (although it might've been both direct and transitive).

**Comment by dark-chocolate** [comment]
@kwalrath Ok, it means `path` was a direct dependency. But then this line in the second part of the article needs to be changed.

> The path and meta packages are still out-of-date, due to reasons that this package doesn’t control.


Additionally , the latest screenshot shows the exact word for "direct dependencies" and "transitive  dependencies", screenshot attached:


![image](https://user-images.githubusercontent.com/40364434/113762349-c9779a00-9718-11eb-8722-b60554caa9e8.png)


![image](https://user-images.githubusercontent.com/40364434/113762377-cf6d7b00-9718-11eb-98f7-d6102df8a769.png)


This is not a major issue, I was just pointing out to update the documentation. :)
