### ISSUE TITLE
Custom type for map

### ISSUE THREAD

**Issue by lexent3010** [dart-lang/site-www#3117]
Hello. I do not understand if there is an opportunity to create your own type for map in dart. I want only certain strings from variables, or a list, to be the keys of an object.

**Comment by parlough** [comment]
I'm not exactly sure what you're requesting. To cover any potential meaning, I outlined a few possible scenarios:

If you want to specify what type of values a map can contain as its key and values, you can specify generic types. For example a `Map<String, int>` is a map with `String` keys and `int` values. You can learn more about this in the [Maps](https://dart.dev/guides/language/language-tour#maps) and [Generics](https://dart.dev/guides/language/language-tour#generics) section of the language tour.

If you want to limit exactly what values can be stored in the map, such as `'walking'`, `'running'`, and `'flying`. This is currently not possible, but an [`enum`](https://dart.dev/guides/language/language-tour#enumerated-types) may be a good solution. You can also just create a new `class` to properly represent and contain your desired behavior. If you for sure need specifying exact values(such as Strings) as types similar to what TypeScript supports, you'll likely need to open an issue on the Dart [language repository](https://github.com/dart-lang/language) as they handle defining the language and its features. I recommend you look for existing issues as similar requests likely already exist, such as https://github.com/dart-lang/language/issues/783

Currently, if you need to stick with `String`s though, your map is `const`, and you are just looking for better analysis support and autocompletion suggestions, the following implementation request in the SDK repo may be of interest to you. Feel free to add your desired behavior to the issue if it matches: https://github.com/dart-lang/sdk/issues/28289

Finally, if you mean a custom class implementation of a Map, you can definitely do so. There's even the [`MapBase`](https://api.dart.dev/stable/2.12.2/dart-collection/MapBase-class.html) class which may help you with your implementation.

---

Sorry that I wasn't so clear on what you are looking for, but hopefully one of those suggestions covers what you are looking for. If I missed something or you can provide more information, such as an example of what you're trying to achieve, feel free to reply and I'd be happy to help you implement it or at least direct you to the best place.

**Comment by lexent3010** [comment]
Let me give you an example. We have such a list or other string variable. 
`var list = ['foo', 'bar', 'hello', 'world']`
And I want only the values in the list to be used in the role of keys when initializing an object.
And I would like the compiler to track this. You understood correctly that I used this in TypeScript

**Comment by parlough** [comment]
Yeah I'm not sure there is a great way of achieving this in Dart currently.

As this is the GitHub repo for the [Dart website](https://dart.dev), I recommend you instead create an issue on the [Dart language GitHub repo](https://github.com/dart-lang/language/issues) with your request and an example. They handle what features get added to the language and you will be able to have more discussions there. They're very friendly and open to suggestions! :)

Let me know if you have any other questions though, thanks!

**Comment by kwalrath** [comment]
Thanks for the answer, @parlough! I'm going to close this, since there's no actionable item for the docs.
