### ISSUE TITLE
Clarify calling one library in two ways on 'Effective Dart: Usage' page

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#3124]
Page URL: https://dart.dev/guides/language/effective-dart/usage
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/effective-dart/usage.md

Description of issue:

Quoting [this article](https://dart.dev/guides/language/effective-dart/usage#dont-allow-an-import-path-to-reach-into-or-out-of-lib), 

![image](https://user-images.githubusercontent.com/40364434/113766415-ac919580-971d-11eb-861e-e98d37c1111e.png)

I think the first line is not `bad`, but actually is the right way to import. It is further confirmed in the [next section](https://dart.dev/guides/language/effective-dart/usage#prefer-relative-import-paths):

![image](https://user-images.githubusercontent.com/40364434/113766318-908df400-971d-11eb-8528-414d1487af4f.png)

**Comment by kwalrath** [comment]
It's true that the first line isn't bad; it's the combination of the two lines that's bad. I'm not sure how to make this clearer.

**Comment by dark-chocolate** [comment]
@kwalrath By "combination", do you mean there should be a space between the two lines (as mentioned in best practices)?

**Comment by kwalrath** [comment]
No, I mean that you're including the same library in two different ways, which is very bad.

Maybe we could change the example to something like this:

```dart
// This import by itself would be fine.
import 'package:my_package/api.dart';

// This import causes problems because it imports the same file (api.dart)
// but uses a different path. Avoiding ../lib imports prevents this problem. 
import '../lib/api.dart'; // Reaching into lib.
```

**Comment by dark-chocolate** [comment]
@kwalrath I didn't pay attention to the 2nd import line in 1st screenshot. I thought it would be `import 'test_utils.dart'`. I got your point now.

**Comment by kwalrath** [comment]
> @kwalrath I didn't pay attention to the 2nd import line in 1st screenshot. I thought it would be `import 'test_utils.dart'`. I got your point now.

You aren't the first person to be confused by the example, so I think it needs some improvement.

**Comment by kwalrath** [comment]
Turns out we had a PR from long ago that aims to fix this. I think it's ready to commit, and I hope it helps.

**Comment by parlough** [comment]
I think the addition of a "good" example with the current text after https://github.com/dart-lang/site-www/pull/3066 seems to sufficiently solve this issue. Let me know if you think further additions or changes are needed. 

Thanks again for creating an issue for this!

**Comment by dark-chocolate** [comment]
Hi, 

It's still confusing to have first import line (which is good) in the bad section. 

<img width="442" alt="image" src="https://user-images.githubusercontent.com/40364434/197261690-b506ea85-5c81-4659-afd5-7f649f0d3658.png">

I think it will make more sense if we can write it like this: 

`api.dart` can be imported in two ways: 
1. `import '../lib/api.dart';` (bad)
2. `import 'package:my_package/api.dart';` (good)

**Comment by parlough** [comment]
Hi @dark-chocolate, thanks for raising the concern. Taking a look, this snippet is not about the first one being good and the second one being bad, it's about how importing in both ways at the same time is very confusing and causes issues. So the suggestion to this issue, is to just stick to the `package` one.

If we only put the `import '../lib/api.dart';` in the bad section, it doesn't illustrate the potential ("bad") issues that may arise.

Keeping that in mind, do you see someway this would be more clear?

**Comment by dark-chocolate** [comment]
@parlough 

It's not clear what is bad. 

```dart
import '../lib/api.dart';
```

or the combination of

```dart
import 'package:my_package/api.dart';
import '../lib/api.dart';
```

Of course both are bad. I think the docs needs to convey the following message explicitly because the reader also knows that importing both will be bad, the doc was (I think) more about what should be the correct way of importing. 

> it's about how importing in both ways at the same time is very confusing and causes issues
