### ISSUE TITLE
'Extension methods' page issue, remove redundant generic type annotation. 

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#3130]
Page URL: https://dart.dev/guides/language/extension-methods
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/extension-methods.md

Description of issue:

In the code used in [Implementing generic extensions](https://dart.dev/guides/language/extension-methods#implementing-generic-extensions), this line

```dart
List<List<T>> split(int at) => <List<T>>[sublist(0, at), sublist(at)];
```

should be made

```dart
List<List<T>> split(int at) => [sublist(0, at), sublist(at)];
```

because of [effective dart's good practices.](https://dart.dev/guides/language/effective-dart/design#dont-write-type-arguments-on-generic-invocations-that-are-inferred)

**Comment by parlough** [comment]
Thanks for catching this! It's always a good idea to follow and encourage best practices.
