### ISSUE TITLE
'Understanding null safety' page issue, code is missing a return statement. 

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#3138]
Page URL: https://dart.dev/null-safety/understanding-null-safety/
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/understanding-null-safety/index.md

Description of issue:

In the code sample used [here](https://dart.dev/null-safety/understanding-null-safety#type-promotion-on-null-checks), the `return` statement is missing.

![image](https://user-images.githubusercontent.com/40364434/114212938-af30fc80-9962-11eb-806a-776cd101d406.png)

**Comment by munificent** [comment]
Fixed now.
