### ISSUE TITLE
accessing data in variable from another variable 

### ISSUE THREAD

**Issue by arielszy** [dart-lang/site-www#3142]
hi. this threat has the purpose of knowing if theres a way to do this or adding in a future dart version.
this is what am trying to do:

var a='data';
var name ='a';

print(a);// output 'data'
print(name);//output 'a'
print('$a');// output 'data'
print('$name');// output 'a'

print('$$name');// output should be  'data' like in php

i want to do this in dart.

**Comment by parlough** [comment]
Hey @arielszy thanks for opening the issue.

My understanding is you would essentially like dynamic variable evaluation. Personally, I'm not sure this fits well into Dart which now has a lot of static guarantees with a focus on familiarity and readability. 

I don't know much about language design though and this repository is for the [Dart website](https://dart.dev) and not the language itself. I recommend you [create an issue](https://github.com/dart-lang/language/issues/new/choose) on the [Dart language repository](https://github.com/dart-lang/language) with your feature request and perhaps to PHP documentation of the feature. They'd be able to take your suggestion in account there and have more discussion about it.

Let me know if you have any further questions. Thanks!

**Comment by arielszy** [comment]
Hi. I did. I realized that after publishing here. Thanks. by the way, they dont want to add this feature.

**Comment by kwalrath** [comment]
I'm going to close this issue, but thanks @parlough and @arielszy for the discussion.
