### ISSUE TITLE
Check initial whitespace in code blocks

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3145]
I noticed this while working on the [C interop page](https://dart.dev/guides/libraries/c-interop#using-dartffi). In the following screenshot from an in-progress version of the page, the line continuations (lines 2, 5, and 8) should be indented 4 or 6 spaces, but they're only indented 1 or 3 spaces:

![image](https://user-images.githubusercontent.com/2164483/114563171-074a5600-9c24-11eb-9352-b6be68f84fee.png)

This is in a triple-tick dart section. I haven't noticed it elsewhere (admittedly I haven't _looked_), so I wonder whether this is a recent development or there's something special about a dart code section within a list.

**Comment by parlough** [comment]
This is an issue with our current tooling. I'll close this in favor of https://github.com/dart-lang/site-www/issues/3846 which discusses a wider overhaul.
