### ISSUE TITLE
dart.dev homepage doesn't say "open source" anywhere

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3158]
I'd think that we'd want to say something on the homepage about Dart being open source. flutter.dev _does_ have the words "open source" on its homepage ("Install Flutter today. It’s free and open source.")

Some more notes:
* https://dart.dev/overview also doesn't have the words "open source".
* A search for "open source" on the site turns up mentions on https://dart.dev/brand, https://dart.dev/community, https://dart.dev/terms, and https://dart.dev/tools/dartpad/privacy (among other places). So it's mentioned, but not prominently.

There's a GitHub logo at the bottom of every dart.dev page, but it takes you to the site repo, not the language repo.

**Comment by mit-mit** [comment]
Yeah, good point!
