### ISSUE TITLE
Add a page listing go links

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3159]
Flutter already has an auto-generated page of go links: https://flutter.dev/docs/resources/design-docs.

Also we should be consistent with whatever flutter.dev does to address https://github.com/flutter/website/issues/5665.

**Comment by parlough** [comment]
On the Flutter website side, go links are used for design documents (which make sense to enumerate), but here (on dart.dev) they are more like temporary links or just used by tooling. So a list of them won't be that meaningful or reliable, so I'm going to close this for now, but if someone feels this is necessary, feel free to respond or reopen. Thanks!
