### ISSUE TITLE
'Understanding null safety' page issue

### ISSUE THREAD

**Issue by jjmean2** [dart-lang/site-www#3161]
Page URL: https://dart.dev/null-safety/understanding-null-safety/
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/understanding-null-safety/index.md

Description of issue:

In the first paragraph of [Required named parameters](https://dart.dev/null-safety/understanding-null-safety#required-named-parameters) section, I think this sentence 

>  What if you want to have a named parameter with a _**nullable**_ type and no default value? That would imply that you want to require the caller to always pass it. In other words, you want a parameter that is named but not optional.

should be this. (nullable -> non-nullable)

> What if you want to have a named parameter with a _**non-nullable**_ type and no default value? That would imply that you want to require the caller to always pass it. In other words, you want a parameter that is named but not optional.

**Comment by kwalrath** [comment]
@munificent I think @jjmean2 is right. OK for us to make this change?
