### ISSUE TITLE
'Understanding null safety' page issue

### ISSUE THREAD

**Issue by jjmean2** [dart-lang/site-www#3162]
Page URL: https://dart.dev/null-safety/understanding-null-safety/
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/understanding-null-safety/index.md

Description of issue:

In the [Nullability and generics](https://dart.dev/null-safety/understanding-null-safety#nullability-and-generics) section, there is following code example and description.

> ```dart
> // Using null safety:
> class Interval<T extends num?> {
>   T min, max;
> 
>   bool get isEmpty {
>     var localMin = min;
>     var localMax = max;
> 
>     // No min or max means an open-ended interval.
>     if (localMin == null || localMax == null) return false;
>     return localMax <= localMin;
>   }
> }
> ```
>
> This means that in the body of the class you get the flexibility of treating the type parameter as nullable. Note we have no constructor this time, and that’s OK. The fields will be implicitly initialized to `null`. You can declare uninitialized variables of the type parameter’s type.

But testing this code in dartpad with null safety, it is error to declare uninitialized instance variables of `T` type with no constructor.

<img width="1087" alt="스크린샷 2021-04-22 오전 6 48 26" src="https://user-images.githubusercontent.com/11574475/115626245-2e95d700-a338-11eb-8018-3842d3eec337.png">

I think it's because `T` can be non-nullable type at use site, as mentioned in next paragraph.
> Note that a nullable bound does not prevent users from instantiating the class with non-nullable types.

And, in that case, constructor is needed.

**Comment by squarelab-jwlee** [comment]
Oh, there is same issue already reported for this. I didn't see it. Sorry for duplicate issue.

https://github.com/dart-lang/site-www/issues/2763

I don't know how to delete or close this issue post.

**Comment by jjmean2** [comment]
Oh, there is same issue already reported for this. I didn't see it. Sorry for duplicate issue.

https://github.com/dart-lang/site-www/issues/2763

I don't know how to delete or close this issue post.

**Comment by jjmean2** [comment]
close because it's duplicate issue.

**Comment by kwalrath** [comment]
Thanks for being so thorough, @jjmean2!
