### ISSUE TITLE
Why do we use the touch-icon dev logos?

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3165]
In [head.html](https://github.com/dart-lang/site-www/blob/master/src/_includes/head.html) is there a reason we use the touch-icon- (found in [_assets/image](https://github.com/dart-lang/site-www/tree/master/src/_assets/image)) dev logos instead of the Dart logo?

This results in that icon showing up instead of the Dart logo in Google search on mobile.

![image](https://user-images.githubusercontent.com/18372958/116028959-e3bcdd80-a61d-11eb-9829-e9c987e46604.png)

Perhaps these just were never updated, not sure. I'd be happy to update/remove them, but wanted to make sure it wasn't intentional first.

**Comment by domesticmouse** [comment]
@kwalrath is the source of truth on this call, but I suspect a Dart logo would be betterer.

**Comment by kwalrath** [comment]
Oh that's weird. Yes, it should be the Dart logo. I can't think of when we'd intentionally use the dev logo for anything on our site.

@parlough if you could fix this, I'd appreciate it!
