### ISSUE TITLE
'Customizing static analysis' page issue analysis_option_deprecated link not found

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#3175]
Page URL: https://dart.dev/guides/language/analysis-options
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/analysis-options.md

In the [warning](https://dart.dev/guides/language/analysis-options#customizing-analysis-rules) part, the link for `analysis_option_deprecated` is broken. 

![image](https://user-images.githubusercontent.com/40364434/116466782-350fdb80-a86f-11eb-95c7-f83a78e60e8b.png)

The link is also broken for `invalid_assignment` in the [error](https://dart.dev/guides/language/analysis-options#customizing-analysis-rules) part:

![image](https://user-images.githubusercontent.com/40364434/116466979-756f5980-a86f-11eb-8d4f-ea97c8df0d72.png)

**Comment by kwalrath** [comment]
Thanks for letting us know about this, @dark-chocolate!
 
@bwilkerson, is there another place that https://dart.dev/guides/language/analysis-options#customizing-analysis-rules can link to? (The link to todo is also broken.)

**Comment by bwilkerson** [comment]
It looks like we're now publishing documentation for only the public API of the analyzer package, and the individual error codes are not part of that public API, so there's no dartdoc to which these could link.

For `invalid_assignment` we could potentially link to https://dart.dev/tools/diagnostic-messages#invalid_assignment (which is probably more informative than the doc comment for the error code constant was anyway).

For `analysis_option_deprecated` we could choose a different code with a severity of 'warning' or I could write the documentation for `analysis_option_deprecated`.

I'll note that the link for `todo` (under `info`) is also broken for the same reason. For that one we could choose any hint that's documented and link to it.

**Comment by kwalrath** [comment]
How about these:

* Hint: https://dart.dev/tools/diagnostic-messages#dead_code
* Warning: https://dart.dev/tools/diagnostic-messages#invalid_null_aware_operator
* Error: https://dart.dev/tools/diagnostic-messages#invalid_assignment (as you suggested)

**Comment by parlough** [comment]
I think these are a great set that will all be relatively commonly experienced!

**Comment by bwilkerson** [comment]
Those all look good to me too.
