### ISSUE TITLE
'build_runner' page issue: Remove redundant "pub". 

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#3176]
Page URL: https://dart.dev/tools/build_runner.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/build_runner.md

Description of issue:

Referring [this](https://dart.dev/tools/build_runner#using-built-in-commands), 

![image](https://user-images.githubusercontent.com/40364434/116611695-f80f1c00-a936-11eb-9c00-af272f6fe010.png)

We can remove `pub` from them as it is redundant, even the console shows the warning. 

> Deprecated. Use `dart run instead`

**Comment by parlough** [comment]
Thanks for the report! Definitely something we should update :)

If this is something you want to contribute yourself, feel free to open a pull request, and I can help you with any issues that come up. Otherwise, I can create a pull request with a fix in a few days.

**Comment by dark-chocolate** [comment]
@parlough  

> If this is something you want to contribute yourself, feel free to open a pull request, and I can help you with any issues that come up.

Thanks but I almost never did this so you might have tough time here, haha. 

> As a note, I'm not sure the flutter run command supports directly running pub packages therefore I believe it still needs the pub qualifier.

Actually, you're right, we can't use `flutter run` for running pub packages. So, we should only remove `pub` from the dart command but then these might not look align with each other:

```
dart run build_runner build
flutter pub run build_runner build
```
