### ISSUE TITLE
Add info on how to uninstall Dart

### ISSUE THREAD

**Issue by sfshaza2** [dart-lang/site-www#3187]
Inspired by this issue on flutter.dev:  https://github.com/flutter/website/issues/5695

**Comment by parlough** [comment]
Definitely a good idea. With our current setup, these are the following cases which seem the most important to cover:

- [ ] Uninstalling with Chocolatey in the Windows tab on [Get Dart](https://dart.dev/get-dart)
- [ ] Uninstalling with apt in the Linux tab on [Get Dart](https://dart.dev/get-dart)
- [ ] Uninstalling Debian packages with `dpkg` in the Linux tab on [Get Dart](https://dart.dev/get-dart)
- [ ] Uninstalling with Homebrew in the macOS tab [Get Dart](https://dart.dev/get-dart)
- [ ] Manually deleting SDK directory for those who manually downloaded the ZIP

It would also likely be good to mention removing Dart from path for situations where the package manager isn't responsible for doing so.

**Comment by sfshaza2** [comment]
I like the way you think, @parlough!

**Comment by Sameerkash** [comment]
Great points @parlough, 
I'll see if I can take this up once I finish up with the issue on flutter site, if there's on WIP on this one by then.

**Comment by kwalrath** [comment]
There's also the removing Dart by removing Flutter case, right?

**Comment by Sameerkash** [comment]
> There's also the removing Dart by removing Flutter case, right?

This could just link back to the flutter site. flutter/website#5695

**Comment by sfshaza2** [comment]
Absolutely.

**Comment by Sameerkash** [comment]
@parlough where would this page go?

**Comment by parlough** [comment]
@Sameerkash I think a few places could use additions, with perhaps the most straightforward being how to uninstall with the tools mentioned in each tab on the [Get the Dart SDK](https://dart.dev/get-dart) page. Those could be included near the end of each tab and perhaps completed as an initial PR separate from any new pages.

![image](https://user-images.githubusercontent.com/18372958/117542504-84c47480-afde-11eb-880b-94c8f8a21fe5.png)

As for the other pieces, such as removing extra items from the path, other forms of uninstall for manual installation, linking to the Flutter uninstall directions, etc I'm assuming we could create a new page as well. This could likely go in a similar place to the `get-dart.md` file and be linked to from the [Get Dart](https://dart.dev/get-dart) and [archive](https://dart.dev/tools/sdk/archive) pages. Perhaps @kwalrath will have more ideas here on the contents and location.

**Comment by kwalrath** [comment]
Like @parlough said, the uninstall page could be very similar to (and parallel to) the get-dart page. If the page starts looking too busy or you think that includes/tabs would be too hard to maintain, then we could use [`<summary>...<details>` tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) to hide unnecessary details.

I don't think we need the actual uninstall directions on the get-dart page — just information on where to find the uninstall page. (I'm always leery of including instructions/code that you don't want _everyone_ to copy-paste!)

**Comment by Sameerkash** [comment]
Okay, I'll try and make a PR soon.
