### ISSUE TITLE
Language tour: confusing xOrigin yOrigin in named constructor

### ISSUE THREAD

**Issue by RandalSchwartz** [dart-lang/site-www#3197]
The named constructor .origin uses xOrigin and yOrigin, but it's not clear that those are a reference to an earlier example defining them as const for the class.  Perhaps the const definitions can be repeated?

**Comment by parlough** [comment]
Thanks for pointing this out, fixing this would definitely improve clarity!

It seems the `const` values are actually declared lower in the [Instance methods](https://dart.dev/guides/language/language-tour#methods) section where they're not even used as far as I can tell.

We can likely just move the `const` declarations to the [Named constructors](https://dart.dev/guides/language/language-tour#methods) section instead where they are used.

**Comment by RandalSchwartz** [comment]
Credit actually goes to @nicos68 on Gitter, asking an innocent question.
