### ISSUE TITLE
Show indicator of additional length to on-page TOC on narrow pages

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3199]
Per feedback from @sfshaza2, it's not obvious that, in a medium-width page with a longish TOC, the TOC is abbreviated. E.g. check out https://dart.dev/guides/libraries/writing-package-pages:

![image](https://user-images.githubusercontent.com/2164483/117173661-d7edbb80-ad81-11eb-9b94-38994a164802.png)

If you aren't familiar with dart.dev TOC conventions, it looks like the TOC stops at 1. The arrow at the upper right is too far away to give this hint.

We should instead have some indication that the TOC has been shortened, and have the way to lengthen it be more obvious. Something like what d.g.c uses would be good.

![image](https://user-images.githubusercontent.com/2164483/117173982-2602bf00-ad82-11eb-880d-eb69d03e2bfb.png)
_Screenshot from https://developers.google.com/style/word-list_

**Comment by sfshaza2** [comment]
Thanks for filing this, @kwalrath! Perfection!  @jayoung-lee, what confused me wasn't your page, per se, it's how the Dart site implements it's table of contents. Kathy and I met yesterday to work it out.  :)

**Comment by jayoung-lee** [comment]
I see it now! The new design looks great :D Thanks for the update!
