### ISSUE TITLE
Identify some way to routinely check if the analyzer diagnostics file and the linter rules file are up to date

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3205]
The original plan to use a GitHub action to check unfortunately doesn't work well, as there is no way to indicate a job as "failing" without failing the entire build or blocking PRs from being merged. There currently only seems to be support for passing, failing, or not running as for indications. You can allow steps to fail, but then the UI will still surface the job as passing, limiting the usefulness.

There's various other options to consider such as a GitHub action cron job creating an issue or **pull request** (I'd love this) when they need to be updated.

**Comment by kwalrath** [comment]
A cron job that creates a PR/issue is an interesting option... I think just an issue might be sufficient, at least at first.

**Comment by parlough** [comment]
I'm going to close this in favor of consolidating in https://github.com/dart-lang/site-www/issues/1949, as we'll be overhauling our linter work anyway.
