### ISSUE TITLE
Dart books updated for null safety

### ISSUE THREAD

**Issue by suragch** [dart-lang/site-www#3209]
On the [Books about Dart](https://dart.dev/resources/books) page it lists [Dart Apprentice](https://www.raywenderlich.com/books/dart-apprentice) in the [Dart books preceding null safety](https://dart.dev/resources/books#dart-books-preceding-null-safety) section. However, Dart Apprentice has been fully updated for null safety as of version 1.1 of the book. (I'm the author.)

Could we make a new section or update the description on the Books about Dart page?

**Comment by parlough** [comment]
Thanks for letting us know @suragch, it's super exciting to see books updated to support null safety!

I'm thinking we can add books which support null safety to the top without any header like we did for [Dart 2 books previously ](https://github.com/dart-lang/site-www/blame/98126981ce20d6c1ad5df2595a000d25dbb38c87/src/resources/books.md#L12) and keep the "Dart books preceding null safety" section below those. We'd likely have to introduce a new yaml file for null safe books here: https://github.com/dart-lang/site-www/tree/master/src/_data

I can likely get to this tomorrow, but if you'd prefer you can also open a PR and I'd be happy to review it.

Thanks again!

**Comment by 4amVim** [comment]
Hey,

Extremely grateful for such clear instructions. I hope my PR is satisfactory 😄.

Thank You

**Comment by parlough** [comment]
Fixed by 938117368222079ac6485a5458c6701e0b4aa6f7

Thanks @4amVim for your work and @suragch for letting us know!
