### ISSUE TITLE
Standardize spacing around Liquid tags

### ISSUE THREAD

**Issue by micpap25** [dart-lang/site-www#3219]
See https://github.com/dart-lang/site-www/pull/3212#issuecomment-835581885

**Comment by parlough** [comment]
I think there is a benefit in standardization, so thanks for bringing this up! Moving the information/question over here:

Do we want to standardize around using spaces or not? We currently use a mix, with a lot of occurrences not using spaces, but Liquid's documentation and many other Jekyll websites use the spaces. Personally, I prefer using spaces for easier readability and ease of contribution, but I'm happy to go with with no spaces if that's desired as well.

Example without:

```liquid
{{site.page.name}}
```
With:

```liquid
{{ site.page.name }}
```

**Comment by kwalrath** [comment]
I tend to prefer spaces, as well. @sfshaza2 do you have a preference?

**Comment by sfshaza2** [comment]
I guess that, for me, it depends. I definitely don't want URLs likes like the following:

```
[comp]: {{ site.flutter-medium }}/providing-operating-system-compatibility-on-a-large-scale-374cc2fb0dad
[Adding AdMob banner and native inline ads to a Flutter app]: {{ site.codelabs }}/codelabs/admob-inline-ads-in-flutter
```

I'm also not a fan of:

```
{{ site.alert.note }}
  Only files located directly in the directory are included unless
  there are files with the same name inside a subdirectory
  (see [Asset Variants](#asset-variants)). To add files located in subdirectories, create
  an entry per directory.
{{ site.alert.end }}
```

In fact, I can't think of an example where I want the spaces. So, yeah, I guess I prefer without.

**Comment by kwalrath** [comment]
> If I could weigh in, my old commit standardized it so cases like the following would have no spaces:
> 
> `{{content}}`
> 
> While cases like the following would have spaces:
> 
> `{{ content | inject_anchors }}`
> 
> How much space should be included in this second example?

I like your spacing. It makes sense to include readability space when operators are involved.

**Comment by sfshaza2** [comment]
+1 I agree!
