### ISSUE TITLE
Link to all examples that are in dart-lang/samples

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3221]
Currently we have the following samples, and only the checked ones are linked to by dart.dev docs:

* [x] [command_line](https://github.com/dart-lang/samples/tree/master/command_line) (https://github.com/dart-lang/site-www/pull/3747)
* [x] [extension_methods](https://github.com/dart-lang/samples/tree/master/extension_methods) (https://github.com/dart-lang/site-www/pull/3748)
* [x] [ffi](https://github.com/dart-lang/samples/tree/master/ffi) (multiple samples; linked to by https://dart.dev/guides/libraries/c-interop)
* [x] [isolates](https://github.com/dart-lang/samples/tree/master/isolates) (https://github.com/dart-lang/site-www/pull/3696)
* [x] [native_app](https://github.com/dart-lang/samples/tree/master/native_app) (filed: #2063) (fixed: https://github.com/dart-lang/site-www/pull/3360)
* [x] [null_safety/calculate_lix](https://github.com/dart-lang/samples/tree/master/null_safety/calculate_lix) (linked to by https://dart.dev/null-safety; but do we still need this sample?)
* [x] [server/google_apis](https://github.com/dart-lang/samples/tree/master/server/google_apis) (linked to by https://dart.dev/tutorials/server/httpserver as of May 11)
* [x] [server/simple](https://github.com/dart-lang/samples/tree/master/server/simple) (linked to by https://dart.dev/tutorials/server/httpserver as of May 11)

We should identify which pages should link to each example [set] and add links. We could do more, such as describing the examples or featuring them in the docs. I hesitate to intertwine the samples and docs too much, since they're in different repos and so testing and tools like the excerpter wouldn't easily work.

/cc @johnpryan @RedBrogdon @mit-mit @domesticmouse @kevmoo

**Comment by kkreine** [comment]
Hey @kwalrath, it looks like the first two samples haven't been linked in the docs. I think it makes sense to link command_line in [/cmdline.md](https://github.com/dart-lang/site-www/blob/e02336c20370b91de190282cc5330af093c7d58b/src/_tutorials/server/cmdline.md) and extension_methods in [/extension-methods.md](https://github.com/dart-lang/site-www/blob/e02336c20370b91de190282cc5330af093c7d58b/src/_guides/language/extension-methods.md).

Let me know if this issue still needs work and if you'd like me to continue with or change the proposed link locations.

**Comment by kwalrath** [comment]
Thanks for looking into this, @kkreine! We have a site freeze right now, and then there are the holidays. But I'd love for you to fix this in January, if that isn't too late for you.

@parlough sgty?

**Comment by parlough** [comment]
That would be great if you could fix this in January, thanks! I would be happy to help with any questions or problems you come across :)

**Comment by kkreine** [comment]
@kwalrath  @parlough Sounds good to me! Thanks.

**Comment by parlough** [comment]
With the great contributions from @kkreine and the inclusion of the isolate examples on the [new concurrency page](https://github.com/dart-lang/site-www/pull/3696), this seems to be addressed. Thanks everyone.

If anyone would like any further improvements around specific links/mentions, feel free to open a new, focused issue. Thanks :D
