### ISSUE TITLE
"toString()" omitted in the last code snippet

### ISSUE THREAD

**Issue by nagychris** [dart-lang/site-www#3223]
![image](https://user-images.githubusercontent.com/65423853/117775508-e08b3980-b23a-11eb-8f2e-6c66d6c5cca1.png)

Shouldn't it be `bike.toString()`?

https://developers.google.com/codelabs/from-java-to-dart#1

**Comment by kwalrath** [comment]
@domesticmouse what would be a good way for me to make this change?

**Comment by kwalrath** [comment]
I'm fixing this in the same doc as I'm using to fix #3196.

**Comment by kwalrath** [comment]
Verified that this fix is published.
