### ISSUE TITLE
Disagreement on pub cache's default location on Windows

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#325]
https://www.dartlang.org/tools/pub/installing#optional-environment-variables says:

> By default, this directory is located ... in `AppData\Roaming\Pub\Cache` (on Windows).

But https://github.com/dart-lang/pub/issues/1107 says that it always defaults to $APPDATA/Pub/Cache on Windows.

Other issues:

* https://www.dartlang.org/tools/pub/installing#optional-environment-variables says "You can use the `PUB_CACHE` environmant variable to specify another location", but https://www.dartlang.org/tools/pub/cmd/pub-cache doesn't mention PUB_CACHE.
* Note the mispelled "environmAnt".
* If PUB_CACHE is legit, then maybe we should reopen https://github.com/dart-lang/pub/issues/1107.
* https://www.dartlang.org/tools/pub/installing#optional-environment-variables says "...see [The system package cache]", which links to /tools/pub/cmd/pub-get but is missing the implied anchor tag `#the-system-package-cache`.

I happened to notice all this when I was reviewing #320.

cc @nex3, @Sfshaza

**Comment by Sfshaza** [comment]
Oops, I missed that one in PR 320.

**Comment by nex3** [comment]
> https://www.dartlang.org/tools/pub/installing#optional-environment-variables says:
> 
> > By default, this directory is located ... in `AppData\Roaming\Pub\Cache` (on Windows).
> 
> But https://github.com/dart-lang/pub/issues/1107 says that it always defaults to $APPDATA/Pub/Cache on Windows.

In a sense, both of these are correct. The pub code accesses the `APPDATA` environment variable, but on recent versions of Windows this defaults to `AppData\Roaming`.

**Comment by Sfshaza** [comment]
Fixed in this PR:  https://github.com/dart-lang/site-www/issues/178
