### ISSUE TITLE
Update images on 'Fetch data dynamically' page

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3254]
Page URL: https://dart.dev/tutorials/web/fetch-data
Page source: https://github.com/dart-lang/site-www/tree/master/src/_tutorials/web/fetch-data.md

The images on the page use the old `dartlang.org` link, `http` instead of `https`, can be blurry on some screen sizes, and could use a style to match better with the rest of the website. We could create SVGs using a more user accessible tool such as https://www.diagrams.net/

**Comment by kwalrath** [comment]
@parlough what do you think of adding **help wanted** and **beginner** tags to this?
