### ISSUE TITLE
Global: Mac OS X -> macOS

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#326]
See https://en.wikipedia.org/wiki/MacOS, https://www.apple.com/macos/sierra/.

**Comment by kwalrath** [comment]
A bit of history from https://en.wikipedia.org/wiki/MacOS#macOS:

In 2016, with the release of macOS 10.12 Sierra, the name was changed from OS X to macOS to streamline it with the branding of Apple's other primary operating systems: iOS, watchOS, and tvOS.[51]

**Comment by Sfshaza** [comment]
Aaaaaaack! I did not realize this.

**Comment by kwalrath** [comment]
Yep, me neither. I must have seen it, but I didn't _notice_ it.

**Comment by Sfshaza** [comment]
Fixed in this PR:  Improving the docs for the pub commands
