### ISSUE TITLE
'Publishing packages' page issue

### ISSUE THREAD

**Issue by jonbhanson** [dart-lang/site-www#3271]
Page URL: https://dart.dev/tools/pub/publishing.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/pub/publishing.md

Description of issue:

My package, [flutter_native_splash](https://pub.dev/packages/flutter_native_splash) is a developer tool for generating a splash screen.  Thus, it should be added in `dev_dependencies`.  However, the instructions that are automatically created in the [installing](https://pub.dev/packages/flutter_native_splash/install) page instruct the user to add the package in `dependencies`.  I have looked in the docs, but I don't see any way to have pub.dev mark a package as added in `dev_dependencies`.  Is this possible?

**Comment by parlough** [comment]
Hey @jonbhanson, thanks for the issue/question! Unfortunately, as far as I know, currently package developers have no way to specify the package as being a `dev_dependency` in the `installing` tab. I believe this is on the pub team's radar though. You can find two issues around supporting this customization at [The pub installing tab doesn't show dev_dependencies](https://github.com/dart-lang/pub-dev/issues/2125) and [Customize the Installing tab](https://github.com/dart-lang/pub-dev/issues/2967). Perhaps you can add your use case to one of those issues.

As for this page or a similar one, perhaps we can add a note explaining this current lack of functionality and link to the relevant issue.

Let me know if you have any further questions!

**Comment by jonbhanson** [comment]
Thanks @parlough, I've added my comments to those tickets.  You can close this if you'd like since it is a duplicate.
