### ISSUE TITLE
Clarify that string interpolation guideline doesn't apply to single objects

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#3272]
The guideline [PREFER using interpolation to compose strings and values](https://dart.dev/guides/language/effective-dart/usage#prefer-using-interpolation-to-compose-strings-and-values) is intended to only apply when building up a larger string out of multiple pieces. But some misread it and interpret to mean that you also should not call `toString()` when all you need to do is convert a single object to a string.

We should add a sentence clarifying that the latter is allowed.

**Comment by kkreine** [comment]
Hey @parlough, it looks like this hasn't been completed yet. If this is still needed, would you like me to add a sentence such as "However, when converting only a single object to a string, calling toString() is acceptable." to the file, below the code example?

**Comment by parlough** [comment]
Hi @kkreine, this work has not been completed yet. Thanks for taking it on, I love that idea!

Perhaps we can refer to other exceptions on the page to be consistent with wording. For example: https://github.com/dart-lang/site-www/blob/main/src/_guides/language/effective-dart/usage.md?plain=1#L603-L604

I'm not the best with word crafting, but maybe something like the following? 

```
Note that this guideline applies to combining multiple literals and values.
It's fine to use `.toString()` when converting only a single object to a string. 
```

Feel free to make a pull request with whatever you think is best and I will assign an appropriate reviewer. Thanks again :)

**Comment by kkreine** [comment]
Hi @parlough, thank you for the guidance; it sounds much better to be consistent with wording, and I'll work to adhere to that.
