### ISSUE TITLE
'Null safety codelab' page issue. Exercise 3 showing code-excerpt tag.

### ISSUE THREAD

**Issue by JHBitencourt** [dart-lang/site-www#3283]
Page URL: https://dart.dev/codelabs/null-safety#exercise-nullable-type-parameters-for-generics
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/null-safety.md

Description of issue:

I guess this is not the intended behavior, and the tag shouldn't be showing at the page.

![image](https://user-images.githubusercontent.com/9002831/120117013-78f14b80-c161-11eb-9889-db7ea9d682a5.png)

I'm unaware of how this tag works through the build process, but maybe is there a sintaxe error?
By looking at the other examples a space could be missing after `String/g;` ?:

`replace="/String\?/String/g;/String>\?/String>/g"`

`replace="/first!/first/g; /!.abs/.abs/g"`

https://github.com/dart-lang/site-www/pull/3195/commits/e8ce4cfb93c91e8c81473ab821f30961c2bd4652#

**Comment by parlough** [comment]
Thanks for taking the time to investigate and report this! Seems to have been an issue with the `>` being improperly escaped.
