### ISSUE TITLE
TODO(miquelbeltran) Maybe ! would be better here

### ISSUE THREAD

**Issue by vendz** [dart-lang/site-www#3295]
TODO link: https://github.com/dart-lang/site-www/blob/master/null_safety_examples/misc/test/language_tour/browser_test.dart#L16

**Comment by vendz** [comment]
#3299

**Comment by parlough** [comment]
Thanks for making an issue to track this TODO! The question raised in this TODO is a good question and if anyone has any suggestions I'm open to them. I'm thinking since we know the div should be there, it's safe to use `!` in this case.
