### ISSUE TITLE
Remove TODO about explaining that non-required params can be null

### ISSUE THREAD

**Issue by vendz** [dart-lang/site-www#3297]
TODO link: https://github.com/dart-lang/site-www/blob/master/null_safety_examples/misc/lib/language_tour/functions.dart#L29

**Comment by parlough** [comment]
Thanks for opening this issue @vendz ! Taking a look at the language tour, I'm thinking the addition of this tip(https://github.com/dart-lang/site-www/blame/master/src/_guides/language/language-tour.md#L1334) may have addressed this issue. What do you think @kwalrath?

**Comment by kwalrath** [comment]
I think you're right, @parlough. I'm going to close this.

**Comment by kwalrath** [comment]
Reopening because we should remove the TODO. :)

**Comment by vendz** [comment]
@kwalrath should I remove the todo from file and create a PR
