### ISSUE TITLE
TODO(chalin): I believe that handleError's test argument should be declared

### ISSUE THREAD

**Issue by vendz** [dart-lang/site-www#3298]
TODO link: https://github.com/dart-lang/site-www/blob/master/null_safety_examples/misc/lib/tutorial/stream_interface.dart#L4

**Comment by parlough** [comment]
Thanks again for opening these @vendz 

As a note for anyone referring to this in the future, I believe these declarations are replicating what's found in the SDK and it's being noted that the declaration of `handleError`'s `test` parameter doesn't match the `Function` style. So this may need to be fixed first on the SDK side if it is truly a problem.
