### ISSUE TITLE
Create new codeblock theme to match Dart websites

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3301]
I was thinking we could create a new standardized code theme to match Dart websites in their current states, focusing on fitting in with dart.dev and pub.dev. Dartdoc could also use these new styles.

Currently some of dart.dev's colors don't seem to fit in with the rest of the website and pub/dartdoc use a modified derivative of GitHub's css. 

Perhaps DartPad's light theme could use something similar as well to further consistency.

**Comment by kwalrath** [comment]
Consistency would be very nice. Accessibility is also important, especially for people without perfect vision — light & dark options, and contrast beyond the minimum necessary.
