### ISSUE TITLE
'A tour of the Dart language' page issue

### ISSUE THREAD

**Issue by Labkamal** [dart-lang/site-www#3302]
Page URL: https://dart.dev/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by Labkamal** [comment]
Where to learn Dart complete for new developer. Plz tell. There is no complete pro level courses on udemy or any platform. Plz upload video fron scratch. It is no use of learn basic. Dart servers side programming course. Dart Flutter package Development course. Plz tell me

**Comment by parlough** [comment]
Thanks for letting us know about some of the content you would like to see!

For learning Dart, outside of the language tour, consider [Codelabs](https://dart.dev/codelabs) as well as other resources like [books](https://dart.dev/resources/books) such as [Dart Apprentice](https://www.raywenderlich.com/books/dart-apprentice) which seems to be updated and cover a lot. I recommend once you've gone over the initial material, try creating something of your own. When you get stuck, refer to [dart.dev](https://dart.dev) for reference or even other websites such as StackOverflow where there's lots of users helping with Dart and Flutter.

As for writing server side code with Dart, this is an area where improvements are being worked on(https://github.com/dart-lang/site-www/issues/3058), but there are some resources currently. Refer to https://dart.dev/tutorials/server/httpserver for some current resources. Beyond that, there's been a lot of development around developing on Google Cloud platforms such as Cloud Run and general ideas around "Full Stack Dart". I recommend you check out this Google Cloud podcast from last week: https://www.gcppodcast.com/post/episode-261-full-stack-dart-with-tony-pujals-and-kevin-moore/

For learning Flutter, I think the [Flutter Codelabs](https://flutter.dev/docs/codelabs) are great for initial learning. Then when you want to learn more about larger application development and more advanced coding concepts, consider watching [The Boring Flutter Development Show](https://www.youtube.com/playlist?list=PLjxrf2q8roU3ahJVrSgAnPjzkpGmL9Czl) or enrolling in a complete course such as [https://www.appbrewery.co/p/flutter-development-bootcamp-with-dart/](https://www.appbrewery.co/p/flutter-development-bootcamp-with-dart/).

There's plenty of other great community resources, such as courses, books, and videos. With all of this material though, some of it may be slightly outdated, so if there's any problems, refer to the Dart and Flutter websites to find out the newest APIs and standards. 

I hope some of that is helpful, but know there's lots of material that will still be added in the future. If there's a specific topic you'd ever like to see discussed or taught on dart.dev, let us know with an issue here and perhaps someone can begin working on it. Thanks again!
