### ISSUE TITLE
Update old examples involving implicit downcasts

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3304]
Update examples in analyzer documentation and type system documentation around implicit downcasts since they were removed with null safety. There may be other cases as well.

The example in [Enabling stricter type checks](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks) is no longer relevant as it won't work without the option anyway.

As we migrate [The Dart type system](https://dart.dev/guides/language/type-system) article we'll need to keep this in mind as well.

**Comment by parlough** [comment]
@bwilkerson Does `implicit-casts: false` have any remaining functionality in >= 2.12 that should be documented or should I just add a note explaining it is as no longer functional? 

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

**Comment by bwilkerson** [comment]
I think that's been replaced by other flags, but @srawlins would know more definitively. But yes, I agree that if it's deprecated / dead then we should remove it from the external docs and have a warning for it.

**Comment by srawlins** [comment]
`implicit-casts` still reports when a cast is made from `dynamic` to another type (if I'm not mistaken), but Dart 2.12 with null safety allows this, so it still has functionality.

**Comment by kwalrath** [comment]
If you're using 2.12/2.13 but your lower SDK bound is before that, does `implicit-casts` still catch non-`dynamic` casts?

**Comment by srawlins** [comment]
That's correct, it would.
