### ISSUE TITLE
install/archive page should be changed for Dartium versions

### ISSUE THREAD

**Issue by whesse** [dart-lang/site-www#331]
There will no longer be Dartium versions on the dev channel, and the stable 1.24 channels should fetch Dartium with version numbers 1.25.0-dev.6.x, as x increases.  Even though we are releasing 1.25.0-dev.7.0, and perhaps further, before 2.0, Dartium builds of those versions will not be released.

Perhaps the page should just be changed to have a separate stable Dartium section, and the existing stable and dev sections should work unchanged, just not including Dartium builds.

@terrylucas @whesse @Sfshaza @kwalrath

**Comment by kwalrath** [comment]
@whesse would it be OK to keep the tables as-is, and just remove the Dartium download links for versions > 1.24? Like this: https://kw-www-dartlang-1.firebaseapp.com/install/archive

Or do you think we really need a separate Dartium table? If so, what do you picture it looking like? Maybe (if the Dartium version #s track the SDK version #s):

| Dartium version | OS | Bits | Downloads |
|---------|----|-----|------------|
| 1.24.3 | Mac | 64-bit | Dartium (SHA-256) |
| 1.24.3 | Linux | 64-bit | Dartium (SHA-256) |
| ... | ... | ... | ... |
| 1.24.2 | Mac | 64-bit | Dartium (SHA-256) |
| ... | ... | ... | ... |
| 1.24.0-dev.6.9 | Mac | 64-bit | Dartium (SHA-256) |
| ... | ... | ... | ... |
| 1.24.0-dev.6.8 | Mac | 64-bit | Dartium (SHA-256) |
| ... | ... | ... | ... |

**Comment by whesse** [comment]
No, it is fine to keep the tables as-is. I was just overthinking it, trying to give you the solution, rather than telling you what the problem to solve was - that there would be no dev Dartium, and stable dartium will have version numbers different from the stable sdk numbers (1.25.0-dev.5.x, not 1.24.x)

**Comment by kwalrath** [comment]
Cool. We might still go with a separate download for Dartium, but since I have the all-in-one solution working already, I'll start with that.
