### ISSUE TITLE
Example code for "Don't use `this.` except to avoid shadowing" violates guidelines about untyped variables

### ISSUE THREAD

**Issue by tetkin-g** [dart-lang/site-www#3315]
https://dart.dev/guides/language/effective-dart/usage#dont-use-this-when-not-needed-to-avoid-shadowing
The guideline includes this example:

```dart
class Box {
  var value;

  void clear() {
    update(null);
  }

  void update(value) {
    this.value = value;
  }
}
```

The `var value;` part has no initializer and no explicit type, which means it's implicitly using `dynamic`, which goes against this guideline: http://go/edart/design#do-annotate-with-dynamic-instead-of-letting-inference-fail

**Comment by tetkin-g** [comment]
Same issue here:
https://dart.dev/guides/language/effective-dart/usage#dont-wrap-a-field-in-a-getter-and-setter-unnecessarily
```dart
class Box {
  var contents;
}
```

**Comment by munificent** [comment]
Yeah, this would be good to fix. (This guideline is ancient.) I'd probably use `Object?` for the type everywhere.
