### ISSUE TITLE
Tiny missing update pedantic --> lints/recommended

### ISSUE THREAD

**Issue by eernstg** [dart-lang/site-www#3323]
On https://dart.dev/guides/language/analysis-options#the-analysis-options-file, we have the following phrase:

> from a file in the pedantic package

I believe this should have been updated to '.. in the lints package'.

**Comment by kwalrath** [comment]
Oops. Thanks for letting us know!

**Comment by parlough** [comment]
If anyone wants to fix this, `pedantic` would need to be updated to `lints` at https://github.com/dart-lang/site-www/blame/master/src/_guides/language/analysis-options.md#L124

**Comment by CHuante** [comment]
Hi! id like to contribute to this and correct the phrase if nobody's called dibs

**Comment by parlough** [comment]
@CHuante Thanks for the offer, contribute away. Let me know if you have any questions or issues :)

**Comment by CHuante** [comment]
And i already have a question lol, I cant find the file thats holding that line of code.  are you able to find it through the link: https://github.com/dart-lang/site-www/blame/master/src/_guides/language/analysis-options.md#L124 
or is there a more efficient way to look?

**Comment by parlough** [comment]
@CHuante It should be in that file on line 124. This line:

```
from a file in the `pedantic` package.
```

should be updated to:

```
from a file in the `lints` package.
```

Another link without the blame information is: https://github.com/dart-lang/site-www/blob/master/src/_guides/language/analysis-options.md

Found at the path: `/src/_guides/language/analysis-options.md`

Let me know if you need any more information!

**Comment by CHuante** [comment]
Awesome thanks! I just sent a pull request, is everything in order?
