### ISSUE TITLE
Create a dedicated page for dart create

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3329]
I just came across some writing where a link to a dedicated dart create page may come in handy, particularly with the removal of `stagehand`.

We could at the very least document its core arguments and flags, as well as discuss at a high level what each template is useful for.

It should be located with the other `dart` tools at `/src/tools/dart-create.md`:

![image](https://user-images.githubusercontent.com/18372958/121828852-770da900-cc86-11eb-9c2c-5bfeb97c5c8d.png)

**Comment by kwalrath** [comment]
I intended to have a dedicated page for each command in the table toward the bottom of [the dart tool page](https://dart.dev/tools/dart-tool). Not sure whether there's a bug for that...
