### ISSUE TITLE
Update AUTHORS file

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3332]
Per the discussion at https://github.com/dart-lang/site-www/pull/3328#issuecomment-860531913.

Whatever we do, we should probably do the same on flutter/website.

/cc @sfshaza2

**Comment by sfshaza2** [comment]
I just looked at my corresponding file on flutter.dev. I definitely vote to delete.

**Comment by sfshaza2** [comment]
(Sorry, didn't mean to close.)

**Comment by kwalrath** [comment]
Some more info: https://opensource.google/docs/releasing/authors

**Comment by kwalrath** [comment]
Just talked to Hixie, who's inclined to leave these files where they are. I'll add some info to the top about where to find the full list of contributors.

**Comment by sfshaza2** [comment]
Oh well. The authors page on flutter.dev is very out of date.

**Comment by sfshaza2** [comment]
Kathy, can you do the same for flutter.dev?

**Comment by kwalrath** [comment]
> Kathy, can you do the same for flutter.dev?

You bet.
