### ISSUE TITLE
Followup improvements for /tools/non-promotion-reasons

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3339]
* [ ] Per @timsneath on twitter: https://twitter.com/timsneath/status/1404885186374868993, **add links** to /tools/non-promotion-reasons.
* [ ] Per https://github.com/dart-lang/site-www/pull/3253#issuecomment-858851452, **clarify the scope of this page**, and when type promotion can and cannot occur. This is related to a discussion I had with @RedBrogdon, regarding a question that @leafpetersen answered about type promotion via definite assignment.

**Comment by atsansone** [comment]
@timsneath : [This page](https://dart.dev/tools/non-promotion-reasons) no longer appears in the TOC.

1. Should it?
2. Should we go through adding these followups?

**Comment by timsneath** [comment]
I think so, although @mit-mit is the right person to answer. 

I'd probably change the title ('failure' implies that something has gone wrong, whereas this is "reasons why type promotion doesn't happen").

**Comment by mit-mit** [comment]
Yes, I think this should be more discoverable (either add in leftnav, or make it part of new null safety docs under `Language >`

Yes, I agree the verbiage should be tweaked a bit and rather than talking about "inference failure" -- which sounds a bit like a judgement -- to talk about "Fixing unpromoted types" and "... help you understand cases where a type isn't promoted to non-nullable"

**Comment by parlough** [comment]
This page is now in the sidenav and has been completely overhauled by Marya in https://github.com/dart-lang/site-www/commit/c7e458c8aab44e7f8a17270e117514af3806ee75. Also for Tim's original question about how to find this page, besides the sidenav, the analyzer surfaces links to the relevant sections when hitting a type promotion case while coding.

If anyone would like to see further changes, please open a new issue with more details. Thanks all for the discussion here and thanks Marya for the great improvements!
