### ISSUE TITLE
'Asynchronous programming: futures, async, await' page issue

### ISSUE THREAD

**Issue by izky212** [dart-lang/site-www#3373]
Page URL: https://dart.dev/codelabs/async-await.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/async-await.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by parlough** [comment]
Hi @izky212, thanks for opening an issue!

Do you have any more information on what issue you had though? Let us know and we'll be happy to help and/or work to get it fixed :)

**Comment by parlough** [comment]
Hey again @izky212! I'm going to close this issue for now as there isn't anything we can follow up on.

If you have more information or experience another issue, feel free to comment back on this issue or open a new one.

Thanks again :)
