### ISSUE TITLE
Add Link to An Up-to-Date Community-Maintained AngularDart Documentation Site

### ISSUE THREAD

**Issue by GZGavinZhao** [dart-lang/site-www#3378]
On the [Dart web](https://dart.dev/web) page, the AngularDart link points only to its GitHub repository and has no reference or link to a documentation site that can help new-comers who want to learn this fabulous framework. Is it possible to add a link on this page that links to a [community-maintained fork](https://github.com/angulardart-community/site-angulardart) of the AngularDart documentation site? The reason to not add the [official site](https://github.com/dart-lang/site-angulardart) is because it's archived and many information is outdated. 

If accepted, I would like to take care of this task.

**Comment by kwalrath** [comment]
@GZGavinZhao I was excited to see your work on angulardart.xyz! I'll be happy to link to it... I'll do it myself, because I need to think about how to phrase it.

**Comment by GZGavinZhao** [comment]
No problem! Thank you for your time and support :)
