### ISSUE TITLE
Describe .pubignore

### ISSUE THREAD

**Issue by jjangga0214** [dart-lang/site-www#3399]
Hi :)

Through https://github.com/dart-lang/pub/pull/2787, `.pubignore` is introduced.

I think it should be explained from https://dart.dev/tools/pub/publishing.

Thanks!

**Comment by parlough** [comment]
Thanks for the suggestion @jjangga0214, definitely would be nice to see this documented :)

**Comment by QiXi** [comment]
does .pubignore currently support pub.dev?

**Comment by jjangga0214** [comment]
@QiXi Accurately speaking, as far as I know, `.pubignore` does not have a direct relationship with pub.dev.
`pub` ( = `dart pub`) filters by `.pubignore` and `.gitignore` from publishing content _before publishing_. Then pub.dev receives 'unfiltered' files, so pub.dev does not know .pubignore.

**Comment by QiXi** [comment]
I was faced with the task of publishing some files to git, but not allowing them to be published on pub.dev, after which a search brought me to topics with `.pubignore`. Perhaps I did not formulate the question well, but I would like to know if I can use it today or is it still under development?

**Comment by parlough** [comment]
I don't think `.pubignore` functionality is available in the current stable builds of the SDK, but it should be available in the latest dev and beta builds of the SDK. Keep in mind though that this may result in changes in future behavior until the 2.14 release is made stable. You can find the changelog entry at the top of the 2.14 pub subsection: 3c14d86a67db7207bbc9f654ac49ee60e08e5240

**Comment by QiXi** [comment]
@parlough thanks for the answer

**Comment by kwalrath** [comment]
Closed in #3418
