### ISSUE TITLE
Add this repo to up-for-grabs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#341]
Although site-webdev is in up-for-grabs.net, site-www isn't. We'd love to add this repo.

See the instructions at https://github.com/up-for-grabs/up-for-grabs.net. Our entry should be consistent with what we already have in https://github.com/MunGell/awesome-for-beginners and http://up-for-grabs.net/#/tags/dart. (Or, if you have ideas for improving our existing entries, that'd be great too.)

Related (already fixed): dart-lang/site-webdev#832, up-for-grabs/up-for-grabs.net#677.

**Comment by rohithreddyvootla** [comment]
Hi, I would like to take this on.

**Comment by kwalrath** [comment]
Thank you!

**Comment by kwalrath** [comment]
Confirmed that this site is visible at http://up-for-grabs.net. Thanks, @rohithreddyvootla!
