### ISSUE TITLE
Code example styled with "passes" instead of "fails"

### ISSUE THREAD

**Issue by cankaraman** [dart-lang/site-www#3410]
Hi :),

I think the code example in the below page should be wrapped with "✗ static analysis: error/warning" red box. It's currently wrapped with a green success box.

"![problem](https://user-images.githubusercontent.com/16491175/126481448-44dc9068-5d02-4335-a944-05549b111823.jpg)"

url: https://dart.dev/guides/language/type-system
src: https://github.com/dart-lang/site-www/blob/master/src/_guides/language/type-system.md

**Comment by parlough** [comment]
Nice catch @cankaraman, thanks! This article was recently updated and I must have missed this one. There was also a broken link nearby, so I'll submit a PR for both of those issues soon.

**Comment by cankaraman** [comment]
No problem, glad to help.
