### ISSUE TITLE
\n not working on dartpad

### ISSUE THREAD

**Issue by CesaTor** [dart-lang/site-www#3421]
I tried to print a string with \n and it didn't print it creating a new line after.

This behaviour is present both on dart.dev and dartpad.dev

**Comment by parlough** [comment]
Thanks for pointing this out @CesaTor, I created a PR [in the DartPad repository](https://github.com/dart-lang/dart-pad/pull/1969) which I believe should address the issue. If it doesn't pan out, I'll work with others to get a proper fix.
