### ISSUE TITLE
Expand or remove Resources 'Overview' page

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3430]
Page URL: https://dart.dev/resources/
Page source: https://github.com/dart-lang/site-www/tree/master/src/resources/index.md

This page in its current state does not have much value. We should consider removing it or expand it with further information.

**Comment by kwalrath** [comment]
Somehow I was sure we already had a bug for this, but I can't find it.

**Comment by atsansone** [comment]
@parlough : This page does not appear in the TOC. Is that enough to close this? Do we need to redirect it? Or is another solution recommended?
