### ISSUE TITLE
Create a native print without newline

### ISSUE THREAD

**Issue by Mr-Sena** [dart-lang/site-www#3446]
### What information is missing?

I don't know an intuitive and functional solution to my problem

### How would you like us to fix this problem?

An implementation that allows using the command with the sleep function

**Comment by parlough** [comment]
Hey @Mr-Sena, thanks for opening the issue! As a note, this is the repository for the dart.dev website, and issues for additions to the SDK are best created on the SDK repo: https://github.com/dart-lang/sdk

This is a common request though, and if you are running on a platform which supports `dart:io`, I can suggest using `stdout.write`:

```dart
import 'dart:io';

void main() {
  stdout.write('Hello');
  stdout.writeln(' Mr-Sena');
}
```

This would print out `Hello Mr-Sena`. 

As for a generic, platform-agnostic print which doesn't automatically include a new-line, you can read through this [SDK issue](https://github.com/dart-lang/sdk/issues/46383) which requests a similar feature and has responses which present possible alternatives. If you have more feedback or use cases, I recommend you reach out there or in a new SDK repo issue.

Thanks again! Let me know if you have any questions.
