### ISSUE TITLE
publisher domain verification issue

### ISSUE THREAD

**Issue by AndroidJedi** [dart-lang/site-www#3448]
### Page URL

https://pub.dev/create-publisher

### Describe the problem

I have verified domain ownership in Google Search Console, but when I try to create publisher I still have verification error :

```You must verify the domain property with a DNS record — verifying a URL prefix property or being a collaborator on a property that someone else has verified is not sufficient.```

How to fix this?

**Comment by domesticmouse** [comment]
Please see https://support.google.com/webmasters/answer/34592?hl=en for more details on how to fix this issue.
