### ISSUE TITLE
Review tone of strings in Dart Cheatsheet

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#3485]
### Page URL

https://dart.dev/codelabs/dart-cheatsheet#optional-named-parameters

### Page source

https://github.com/dart-lang/site-www/blob/master/src/codelabs/dart-cheatsheet.md

### Describe the problem

Some strings used in the snippets on this page might not be following our [style guide](https://developers.google.com/style/tone).

### Expected fix

We should consider avoiding wacky sounding phrases in snippets

### Additional context

[context](https://github.com/dart-lang/site-www/pull/3481#discussion_r687202994)

**Comment by atsansone** [comment]
@johnpryan : The offending code doesn't appear in the documentation any more. It was changed in https://github.com/dart-lang/site-www/pull/3938. Closing.
