### ISSUE TITLE
Update the "pub run" documentation to reflect current behavior

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#35]
_From @nex3 on July 6, 2016 19:34_

The [documentation for `pub run`](https://www.dartlang.org/tools/pub/cmd/pub-run.html) is outdated—it's no longer valid to use `pub run foo/bar` to run the file `foo/bar.dart`. There are now three valid ways of specifying the executable:
- `dart_style:format` means "run the `format` executable from the `dart_style` package".
- `test` means "run the `test` executable from the `test` package". It's equivalent to `test:test`. This only applies if a Dart identifier is passed.
- `bin/test.dart` means "run the `bin/test.dart` file in the current package". This only applies if the path is _not_ a Dart identifier.

_Copied from original issue: dart-lang/www.dartlang.org#1588_

**Comment by Sfshaza** [comment]
_From @nex3 on July 6, 2016 21:16_

I misremembered and misread the code; the current documentation is actually fine.

**Comment by Sfshaza** [comment]
_From @skybrian on July 7, 2016 23:32_

The documentation still looks wrong to me. Specifically:

```
$ pub run foo arg1 arg2
This command looks in your package’s bin directory for the specified script and invokes it, passing in any arguments.
```
The example is using a Dart identifier, but the explanation is for when the user typed "foo.dart".

It seems like the docs should say what you just said in https://github.com/dart-lang/pub/issues/1428#issuecomment-230909731, explaining the difference between running "foo.dart" versus "foo".

**Comment by Sfshaza** [comment]
@skybrian, I just replicated your test with a bin/hello.dart directory and a basic pubspec. When I try:

% pub run hello.dart

It works. And when I try:

% pub run hello

That also works.

**Comment by skybrian** [comment]
That's strange, I just tried it (using Dart 1.18.1.) For me it looks like this:

```
$ pub run hello
Could not find package "hello". Did you forget to add a dependency?
skybrian-macbookpro2:tmp skybrian$ pub run bin/hello
hello!
skybrian-macbookpro2:tmp skybrian$ pub run bin/hello.dart
hello!
skybrian-macbookpro2:tmp skybrian$ ls -lR
total 16
drwxr-xr-x  4 skybrian  eng  136 Sep  2 18:33 bin
drwxr-xr-x  2 skybrian  eng   68 Sep  2 18:33 packages
-rw-r--r--  1 skybrian  eng   98 Sep  2 18:33 pubspec.lock
-rw-r--r--  1 skybrian  eng   10 Sep  2 18:25 pubspec.yaml

./bin:
total 16
-rw-r--r--  1 skybrian  eng  30 Sep  2 18:25 hello.dart
lrwxr-xr-x  1 skybrian  eng  11 Sep  2 18:33 packages -> ../packages

./packages:
```

**Comment by Sfshaza** [comment]
This works fine for me. I created a very simple "hello" app, presumably similar to Brian's. Files are attached.

Here's the output from my testing:

```
tmp $ pub get
Resolving dependencies... 
Got dependencies!
tmp $ pub run hello
hello!
tmp $ pub run hello.dart
hello!
tmp $ pub run bin/hello
hello!
tmp $ ls
bin		pubspec.lock	pubspec.yaml
tmp $ ls bin
hello.dart
tmp $ dart --version
Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
[tmp.zip](https://github.com/dart-lang/site-www/files/1154214/tmp.zip)
```

I'm closing. Re-open (or file a new bug) if you have more info.

**Comment by peabnuts123** [comment]
This is an old thread but I am still seeing the same issue.

```sh
$ ls bin
adslkajsdkljasd.dart    console_app.dart        web_server.dart

$ pub run web_server
Could not find package "web_server". Did you forget to add a dependency?

$ pub run web_server.dart
Target file: web/index.html.
Server running on http://localhost:9080/
^C

$ pub run adslkajsdkljasd
Could not find package "adslkajsdkljasd". Did you forget to add a dependency?

$ pub run adslkajsdkljasd.dart
Target file: web/index.html.
Server running on http://localhost:9080/
^C
```

`adslkajsdkljasd.dart` is a copy-paste of `web_server.dart` to validate that pub wasn't first searching its cache for a package named `web_server` first (presumably there are no packages on pub.dev called `adslkajsdkljasd`). 

It seems like the discussion in this thread has been suggesting that writing `pub run xxxx` is equivalent to referencing package `xxxx:xxxx` and is why it says "Could not find package". Surely the documentation needs to be updated to reflect this?

**Comment by peabnuts123** [comment]
cc @kwalrath apologies for the tag but I don't believe anybody in this thread works on the project any more.

**Comment by kwalrath** [comment]
@jonasfj who would know what the `pub run` behavior is supposed to be?

**Comment by jonasfj** [comment]
`pub run <package>:<command> [args...]` will check if dependencies are installed, specifically that:
 *  `.dart_tool/package_config.json` and `.packages` is a placement of `pubspec.lock`, and,
 *  `pubspec.lock` is a resolution that satisfies `pubspec.yaml`.
This is checked with timestamps and checks. I don't think we're going to document this, instead would merely specify that `pub run` checks if dependencies are installed (specifically how we check this may change over time).
Note. if dependencies are not installed `pub run` will bail and tell the user to invoke `pub get`.

Next `pub run <package>:<command> [args...]` will run `bin/<coomand>.dart` from `<package>` as depended on in `pubspec.yaml` (passing through `[args...]`). That is `bin/<coomand>.dart` from the version of `<package>` installed in this project, when `pub get` was called.

Doing `pub run XXX` is a short hand for `pub run XXX:XXX`, this works nicely in the case where `package:test` has a file `bin/test.dart`, then `pub run test` (which we use for running tests) is actually a short hand for calling `pub run test:test`.

--------
I've noticed that adding `.dart` to command is allowed, and will run `bin/<command>` and not `bin/<command>.dart` (avoiding double `.dart.dart`). Also if no `<package>:` is given and `<command>` is not a valid identifier (`[a-zA-Z_][A-Za-z0-9_]*`) then `pub run <command>` will run `bin/<command>.dart` from the current package. For example, `pub run test-thing` will always run `bin/test-thing.dart` from current package.

I'm not sure what story we can tell with these quicks, I somewhat suspect they are deprecated features. So I suggest we don't document them.

Instead I suggest we tell the story that:
 * `pub run <package>:<command>` calleds `bin/<command>.dart` from `<package>`
 * `pub run <command>` is a short hand for `pub run <command>:<command>`.
Hemce, we should encourage authors to give commonly used commands the same name as their package, as we see it done in `package:test` which has `bin/test.dart` -- making `pub run test` magically work :)

**Comment by peabnuts123** [comment]
> Also if no `<package>:` is given and `<command>` is not a valid identifier (`[a-zA-Z_][A-Za-z0-9_]*`) then `pub run <command>` will run `bin/<command>.dart` from the current package. For example, `pub run test-thing` will always run `bin/test-thing.dart` from current package.

(Apologies for sleeping on this reply)

@jonasfj  Are you saying that this is ONLY the case when `<command>` is not a valid package name? That doesn't seem to be documented, and the documentation on the dart.dev site ([here](https://dart.dev/tools/pub/cmd/pub-run#running-a-script-in-your-packages-bin-directory)) gives the example `pub run foo` which _is_ a valid package name, and as a result does not seem to work. Please see my comment above where I gave a few examples of `pub run ____` not working as documented. 

I'd also note that it seems that snake_case is the accepted standard for file names in Dart projects - which will almost always be valid package identifiers i.e. it will never realistically be true that your file will be executable by `pub run ____` unless you specify it explicitly by appending `.dart` to the name.

My suggestion as somebody new to the Dart scene would be to update the documentation for `pub run` to better match users' expectations of how this command works. As you say, it doesn't need to document the nuances of how it works under the hood, a "black box" approach is suitable.

E.g.
  - `pub run foo:bar` will run the command `bar` from the package `foo`
  - `pub run foo` is shorthand for `foo:foo`
  - `pub run foo.dart` will run `bin/foo.dart` in the current package
  - `pub run something/blah.dart` will run a file not in the `bin/` directory
  - If `foo` is not a valid package name e.g. `my-thing`, then `pub run foo` will run `bin/my-thing.dart` in the current package 

It actually seems to me like that last rule is a rather obscure / niche use-case and most users will likely never encounter it. 

Anyways those are my thoughts from the perspective of somebody new to the project. I don't have a lot of time right now but if you needed I could potentially offer some help writing a PR to change the `pub run` page on the documentation site. The Dart project is great, keep up the great work!

**Comment by jonasfj** [comment]
> * `pub run foo:bar` will run the command `bar` from the package `foo`
> * `pub run foo` is shorthand for `foo:foo`
> * `pub run foo.dart` will run `bin/foo.dart` in the current package
> * `pub run something/blah.dart` will run a file not in the `bin/` directory
> * If `foo` is not a valid package name e.g. `my-thing`, then `pub run foo` will run `bin/my-thing.dart` in the current package

I think you're right.. I'm somewhat confused by `.dart` being automatically added when missing.
But that's no reason not to document how this works. That said, I'm not entirely show how we should phrase this..

Also users can just do `dart path/to/file.dart`, so I'm not sure there is a huge win in explaining that `pub run foo` can be used as a shorthand for `dart bin/foo.dart`.

**Comment by kwalrath** [comment]
`run` is no longer listed in the output of `dart pub run`, as of 2.12, so I'm going to close this issue.
