### ISSUE TITLE
Remove Flutter Day puzzle piece

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3503]
### Page URL

https://dart.dev/codelabs/async-await#exercise-practice-handling-errors

### Page source

https://github.com/dart-lang/site-www/tree/master/src/codelabs/async-await.md

### Describe the problem

We should remove the following image and text, which were part of a long-ago [FlutterDay quest](https://twitter.com/FlutterDev/status/1276198179843629058):

![image](https://user-images.githubusercontent.com/2164483/129982105-b1209395-43e1-4812-aed3-02230b9f11c0.png)

**Comment by parlough** [comment]
Makes sense, but I'll miss it 💙

**Comment by kwalrath** [comment]
@sfshaza2 I can't find any pieces on flutter.dev.

@domesticmouse we might still have pieces in the external codelabs... unless you remember removing them?

**Comment by domesticmouse** [comment]
I think it is in at least one codelab. I'll find it when I do a sweep through the codelabs to proof everything for the next Flutter stable release.

**Comment by kwalrath** [comment]
> I think it is in at least one codelab. I'll find it when I do a sweep through the codelabs to proof everything for the next Flutter stable release.

We had a list of the pieces somewhere... I can try to find it if you can't find all 4 (or was it 5?).

**Comment by kwalrath** [comment]
> I think it is in at least one codelab. I'll find it when I do a sweep through the codelabs to proof everything for the next Flutter stable release.

I'll file an issue on flutter/website, if you haven't already.
