### ISSUE TITLE
[PAGE ISSUE]: 'Understanding null safety' shouldn't it be called type demotion instead of type promotion?

### ISSUE THREAD

**Issue by AlexanderJohr** [dart-lang/site-www#3511]
### Page URL

https://dart.dev/null-safety/understanding-null-safety/#type-promotion-on-null-checks

### Page source

https://github.com/dart-lang/site-www/tree/master/src/null-safety/understanding-null-safety/index.md

### Describe the problem

Dear Bob Nystrom,

in Section Type **promotion on null checks**,

shouldn't it be called _type **demotion** on null checks_ instead of _type **promotion** on null checks_?

Before the null check the variable `arguments` of the type `List<String>?` previously supported both the range of values of the type `List<String>` and also `null`.

After the null check the type gets converted to `List<String>`, hence it only supports the range of values of the type `List<String>`.

Fewer values mean type demotion, right?

Best Regards
Alexander Johr

**Comment by AlexanderJohr** [comment]
If you agree, I would take spend my time changing the texts

**Comment by parlough** [comment]
Hey @AlexanderJohr, thanks for opening an issue.

It definitely can be a bit confusing and I'm not fully sure how to best explain, but type promotion is about moving down the class hierarchy, not up. This provides access to more properties/methods, hence type _promotion_. All `List<String>` objects are `List<String>?` and can be assigned to variables of that type, but not the other way around. Type demotion would be going from `List<String>` to `List<String>?` as we could no longer access all of the list methods/properties.

```dart
List<String> nonNull = ['value'];
List<String>? nullable = null

nonNull = nullable; // Error because you cannot do this type promotion implicitly as it may not be a List<String>

nullable = nonNull; // Can do this type demotion implicitly, since List<String>? is a parent
```

As another example, `num` as the parent of `int` and `double` can store integer and float values, but you cannot just safely cast it to an `int`, you need to use a check to promote its type to one or the other, where you will then have access to the subtype's members as well.

**Comment by parlough** [comment]
There are some more formal mentions of type promotion in the [language spec](https://spec.dart.dev/DartLangSpecDraft.pdf), which better define type promotion and contains pieces such as the following which loosely describe promotion being from a "weaker" type to a subtype (which has access to more):

> It is pointless to deduce a weaker type than what is already known. Furthermore, this would lead to a situation where multiple types are associated with a
variable at a given point, which complicates the specification. Hence the requirement that the promoted type is a subtype of the current type.
Dart Programming Language Specification 17.38:

**Comment by atsansone** [comment]
@parlough states this correctly. Closing.
