### ISSUE TITLE
list of analysis rules is missing

### ISSUE THREAD

**Issue by furrary** [dart-lang/site-www#353]
I read [Customize Static Analysis](https://www.dartlang.org/guides/language/analysis-options) and there is a link to [Dart Lint](http://dart-lang.github.io/linter/lints/), but the page doesn't seem to have list of analysis rules like invalid_assignment, unused_import, etc.

**Comment by Sfshaza** [comment]
Not aware of a list of analyzer errors/warnings. Checking.

**Comment by zoechi** [comment]
https://stackoverflow.com/a/35969635/217408 contains links to the source where they are defined
What would be the benefit of listing them on the web?

**Comment by Sfshaza** [comment]
This list may change for Dart 2.0, but you can see the current list [here](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/error/error.dart).  Closing as will not fix. (We can revisit after Dart 2.0.)

**Comment by furrary** [comment]
Thank you so much. IMO, the link should be on [Customize Static Analysis](https://www.dartlang.org/guides/language/analysis-options) to make it easy to find for new Dart users like me. Right now, it's quite frustrating to know that there is a way to ignore errors/warnings, but can't do it because I don't know the exact error code.

**Comment by Sfshaza** [comment]
I can do that, furrary, but be aware that these are likely to change for 2.0

**Comment by Sfshaza** [comment]
A [note](https://www.dartlang.org/guides/language/analysis-options) has been added in [PR 354.](https://github.com/dart-lang/site-www/pull/354)
