### ISSUE TITLE
[PAGE ISSUE]: 'Dart SDK archive' page shows up unexpectedly in the navbars

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3532]
### Page URL

https://dart.dev/tools/sdk/archive/

### Page source

https://github.com/dart-lang/site-www/tree/master/src/tools/sdk/archive/index.md

### Describe the problem

The archive page shows up as the Dart SDK cli `Overview` page under tools in the left sidebar and under "Docs" in the top bar, despite being navigated to from the top level `get-dart` page.

![image](https://user-images.githubusercontent.com/18372958/131431621-e7bad28e-1ed4-4f5e-9d60-76151586db7e.png)

### Expected fix

What do you think about moving this to a child of `get-dart` page to something like `https://dart.dev/get-dart/archive` or even just `https://dart.dev/archive` and redirecting from the old link.

This will also have the benefit of not showing up as the Dart SDK CLI `Overview` page and instead being under the top level `Get Dart` category.

Let me know if you think any of these are worth exploring :)

**Comment by kwalrath** [comment]
I'm open to anything that makes more sense than the current situation!
