### ISSUE TITLE
[PAGE ISSUE]: 'Native extensions for the standalone Dart VM'

### ISSUE THREAD

**Issue by ufrshubham** [dart-lang/site-www#3542]
### Page URL

https://dart.dev/server/c-interop-native-extensions.html

### Page source

https://github.com/dart-lang/site-www/tree/master/src/server/c-interop-native-extensions.md

### Describe the problem

Section [Appendix: Compiling and linking extensions](https://dart.dev/server/c-interop-native-extensions#appendix-compiling-and-linking-extensions) talks about a platform-independent build system, called gyp, and a build file sample_extension.gypi. It is stated that this tool/file is available in dart's source repo, but I couldn't find them anywhere.

### Expected fix

If I am not wrong, gpy was replaced with gn sometime back. If so, probably better to update this section with same information.

**Comment by parlough** [comment]
Hey @ufrshubham, thanks for opening an issue!

Unfortunately, support for native extensions is [being removed](https://github.com/dart-lang/sdk/issues/45451) and this article is quite out of date, including this section. This is even more the case as the more recent sample and other related code was all removed today in https://github.com/dart-lang/sdk/commit/bda70c84892923769c40a131886d6e70fadc99cb

With the removal, I'm not sure there's a great way to update the section without large changes or a new example. We will likely instead completely archive this article soon with better indication of its out of date state.

For a more ergonomic and performant solution, look into [C interop using dart:ffi](https://dart.dev/guides/libraries/c-interop). Let me know if you have any further questions, thanks again :)

**Comment by ufrshubham** [comment]
Oh I see. If native extensions support is being dropped, then I don't see any point in updating this article. I am anyways using dart ffi so it is definitely not an major issue for me. Thanks for the information though.
