### ISSUE TITLE
[PAGE ISSUE]: 'Books about Dart'

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#3543]
### Page URL

https://dart.dev/resources/books.html

### Page source

https://github.com/dart-lang/site-www/tree/master/src/resources/books.md

### Describe the problem

I think we should consider removing the Dart 1 books from this page. 

There are two Dart 2 books listed; the Wenderlich one is pretty good (I haven't reviewed the other). 

I can't think of a scenario when I'd recommend the other books: moreover, I can only imagine that most of them are sufficiently outdated that they will have a negative impact on folks' ability to learn modern idiomatic Dart. 

Curious on others' thoughts, @mit-mit and @kwalrath in particular?

**Comment by mit-mit** [comment]
Removing the Dart 1.x books sounds like a good idea to me!
