### ISSUE TITLE
[PAGE ISSUE] Command mentioned in page no longer available

### ISSUE THREAD

**Issue by LeQuadratico** [dart-lang/site-www#3544]
### Page URL

https://dart.dev/tools/pub/cmd/pub-cache.html

### Page source

https://github.com/dart-lang/site-www/tree/master/src/tools/pub/cmd/pub-cache.md

### Describe the problem

The section "Clearing the global system cache" mentions the command `dart pub cache clear` to empty the entire system cache. 

However, when the command is used, I get the following error:
```
$ dart pub cache clear
Could not find a subcommand named "clear" for "dart pub cache".

Usage: dart pub cache [arguments...]
-h, --help    Print this usage information.

Available subcommands:
  add      Install a package.
  repair   Reinstall cached packages.

Run "dart help" to see global options.
See https://dart.dev/tools/pub/cmd/pub-cache for detailed documentation.
```

Flutter doctor:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale de_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

• No issues found!
```

### Expected fix

Remove the section "Clearing the global system cache" with the command `dart pub cache clear` from the website.

**Comment by parlough** [comment]
Hey @LeQuadratico, thanks so much for catching this and opening the issue!

I made a mistake when I added this subcommand, as it is actually `clean` instead of `clear`. Beyond that, I forgot this subcommand was not introduced until the 2.14 release of the SDK. I will go ahead and fix the name and add a note about version support. 

Thanks again :)
