### ISSUE TITLE
Verify Firebase declared redirects still lead to useful locations

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3546]
The site has a lot of redirects, a few of which are quite old and potentially lead to dead or at least outdated sites.

We should verify each of them leads to a useful location, and if not try to point it to an actually useful/updated location. If there is no alternate, we should either remove the redirect so they get a 404 or add a new page for removed content.

**Comment by parlough** [comment]
If a link is pointing to a location with no good alternative, should we just remove the redirect so it results in a 404?

**Comment by kwalrath** [comment]
> If a link is pointing to a location with no good alternative, should we just remove the redirect so it results in a 404?

Yes, I think so. That way we both offer the possibility of searching for something else, and see that people wanted the info at that URL.
