### ISSUE TITLE
Cover assert() in the Dart 2.0 page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#355]
In Dart 1.x, assert() works only in checked mode. But checked mode is obsolete in Dart 2.0. The [Dart 2.0 Updates page](https://www.dartlang.org/dart-2.0) should say how assert() will work in 2.0.

**Comment by chalin** [comment]
To give a bit more context, in the [Assert](https://www.dartlang.org/guides/language/language-tour#assert) section of the Language Tour it is written:

> > Note: Assert statements work only in checked mode. They have no effect in production mode.
>
> > Dart 2.0 note: Checked mode won’t be in Dart 2.0. For more information, see Dart 2.0 Updates.

@munificent, @floitschG - has it been decided how `assert()` will be handled in Dart 2? I'll be [reworking](https://github.com/dart-lang/site-www/issues/416) some of the example code and I was wondering if I should drop the use of asserts in favor of something else.

cc @kevmoo @filiph

**Comment by floitschG** [comment]
We will still have a second mode to enable `assert`s.

I think the easiest is to call it "debug" mode.

**Comment by kwalrath** [comment]
Tracking bug: dart-lang/sdk#32255

**Comment by kwalrath** [comment]
`--enable-asserts` will work for dart & dart2js. dartdevc always has asserts enabled. We won't call it a separate mode, iirc, just talk about how you use asserts.

**Comment by kwalrath** [comment]
@filiph how does assert() work in Flutter?

**Comment by filiph** [comment]
Currently, `assert` works in debug mode, and is an important part of the developer experience (asserts are everywhere in the framework, so that you get early feedback).

I haven't checked, but I assume in release mode asserts are off. Paging @Hixie to confirm that this is the case and that it won't change in the foreseeable future.

**Comment by Hixie** [comment]
yeah i don't expect that to change.
