### ISSUE TITLE
Mention constructor tear-offs in Effective Dart "DON’T create a lambda when a tear-off will do."

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#3560]
### Page URL

https://dart.dev/guides/language/effective-dart/usage#dont-create-a-lambda-when-a-tear-off-will-do

### Describe the problem

We have an existing rule that tells users to use a tear-off when possible. Right now, it is worded to specifically refer to methods. The language is getting support for [constructor tear-offs](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md) soon, so we should reword this guideline to include those too.

**Comment by devoncarew** [comment]
@munificent @kwalrath - can one of you add this to the ctor tearoff project? https://github.com/orgs/dart-lang/projects/27; I don't seem to be able to edit issues in this repo
