### ISSUE TITLE
Static analysis page should be updated for new `ignore: type=lint` feature

### ISSUE THREAD

**Issue by srawlins** [dart-lang/site-www#3576]
### Page URL

https://dart.dev/guides/language/analysis-options#suppressing-rules-for-a-file

### Describe the problem

Recently (as of last week, post-2.14), you can ignore static analysis reports inline in a new way:

`// ignore_for_file: type=lint` (or `// ignore: type=lint`)

This (first one) will suppress _all lint_ in a file (library?). So exciting! I don't know of why anyone would do the latter example, suppressing a single line; the feature was designed for the former example.

In any case, I think this should be documented.

### Expected fix

Documentation! A single sentence, like what exists for the other examples of inline ignores, is all I would expect.

**Comment by parlough** [comment]
Would it be useful to also highlight a specific use case? Is this primarily intended for generated code?

**Comment by srawlins** [comment]
Good point. The motivation was 100% for generated code, and that's all that comes to mind now 😛

**Comment by parlough** [comment]
@srawlins Just clarifying, what are the types supported here?

**Comment by srawlins** [comment]
For now, only the singular value, `lint` :D. No immediate plans to support other "types."
