### ISSUE TITLE
Document constructor tear-offs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3577]
### What information is missing?

Constructor tear-offs are a new feature in 2.15:

* [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md)
* [faq](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/faq.md)

### How would you like us to fix this problem?

We should probably update the language tour, and also Effective Dart (#3560).

**Comment by devoncarew** [comment]
@kwalrath - can you add this to https://github.com/orgs/dart-lang/projects/27? Thanks!

**Comment by kwalrath** [comment]
> Hmm, I think this and [dart-lang/sdk#46243](https://github.com/dart-lang/sdk/issues/46243) are dups of each other.

I think that's OK. This is the place where I'll see it, and that's the place where SDK engineers will see it.

**Comment by parlough** [comment]
It seems progress has been made towards this with the Effective Dart work in https://github.com/dart-lang/site-www/pull/3649

As for the language tour, I'm not sure we ever explicitly refer to tear-offs, but do have this related [Functions as first-class objects](https://dart.dev/guides/language/language-tour#functions-as-first-class-objects) section where we could expand on the idea and add a new example.

**Comment by kwalrath** [comment]
The language tour doesn't currently use the word _tear-off_. I want to update it to use it, and to at least mention the `ClassName.new` form of constructor tear-off.
