### ISSUE TITLE
Head text overlapping

### ISSUE THREAD

**Issue by albinpk** [dart-lang/site-www#3582]
### Describe the problem

Head text and chapter links overlaps in mobile view

![Screenshot_20210918-235402~3](https://user-images.githubusercontent.com/56157868/133905222-a21165d1-853b-4248-a079-1f93575ddd75.png)

**Comment by parlough** [comment]
Thanks for catching this @albinpk! I confirmed this is happening on my phone, to not as large of an extent, but it's very noticeable when I set Chrome to the layout of the Pixel 2 XL.
