### ISSUE TITLE
Switch to using `main` as primary branch

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3584]
We should migrate the repository to use `main` as the primary branch. This involves at least a few steps:

- [ ] Create the new `main` branch and switch to [using it as the default branch](https://github.com/github/renaming)
- [ ] Update the Jekyll configuration to reference the `main` branch instead
- [ ] Update GitHub actions to run on the `main` branch instead
- [ ] Update all self referencing GitHub links to use `/main` in the URL
- [ ] Verify there are no remaining uses
- [ ] Add a notice and instructions for contributors to switch to the new branch
- [ ] Complete the same work for `site-shared`

**Comment by kwalrath** [comment]
I believe we plan to do this when we update dart.dev to use the same infra as flutter.dev. Is there any urgency to get this done before, say, November?

**Comment by parlough** [comment]
@kwalrath I think it's fine to put that work together, I'll switch this to `blocked` for now.

**Comment by parlough** [comment]
With the infrastructure updates being included in https://github.com/dart-lang/site-www/commits/main, the default branch has now been updated to `main`! https://github.com/dart-lang/site-www
