### ISSUE TITLE
Add additional information to dart format page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3611]
### Page URL

https://dart.dev/tools/dart-format.html

### Page source

https://github.com/dart-lang/site-www/tree/master/src/tools/dart-format.md

### Describe the problem

We should consider adding the info in https://github.com/dart-lang/dart_style/wiki/CLI-Changes.

(I just found out about that page from https://groups.google.com/a/dartlang.org/g/misc/c/Rcpd_Sr0aKg/m/8sD323psBQAJ.)

**Comment by Veercodeprog** [comment]
anyone on this?
what information needs to be added?

**Comment by atsansone** [comment]
Thank you for raising this issue. This appears to be missing specific guidance on your request. As no information has been added for almost 3 years, we are closing this issue. Please feel free to reopen with additional guidance.
