### ISSUE TITLE
Use simpler/faster `$(document.body)` instead of `$('body')` in main.js

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3615]
### Describe the problem

We currently use an inconsistent mix of `$('body')` and `$("body")` within [main.js](https://github.com/dart-lang/site-www/blob/master/src/_assets/js/main.js). 

### Expected fix

We should switch these to the more consistent and slightly more performant `$(document.body)`. This will also very slightly simplify a transition away from jquery in the future.

**Comment by bstuff** [comment]
can I take?
