### ISSUE TITLE
Usage of `LineSplitter()` in examples should use the `const` constructor

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3623]
### Describe the problem

There are currently a few uses of `LineSplitter` where they could use the `const` constructor but they don't.

### Expected fix

These instances in the Dart code and documentation excerpts should use the `const` constructor instead.

`LineSplitter()` -> `const LineSplitter()`

| Example Code                                                                                                                                        | Documentation Location                                                                                                            |
|-----------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| [cat_no_hash.dart](https://github.com/dart-lang/site-www/blob/master/examples/misc/bin/cat_no_hash.dart#L8)                                         | [streams.md](https://github.com/dart-lang/site-www/blob/master/src/_tutorials/language/streams.md?plain=1#L353)                   |
| [stream.dart (1)](https://github.com/dart-lang/site-www/blob/master/examples/misc/lib/library_tour/async/stream.dart#L58)                             | [library-tour.md (1)](https://github.com/dart-lang/site-www/blob/master/src/_guides/libraries/library-tour.md?plain=1#L1352)        |
| [stream.dart (1)](https://github.com/dart-lang/site-www/blob/master/examples/misc/lib/library_tour/async/stream.dart#L58)                             | [library-tour.md (2)](https://github.com/dart-lang/site-www/blob/master/src/_guides/libraries/library-tour.md?plain=1#L1384)        |
| [stream.dart (2)](https://github.com/dart-lang/site-www/blob/master/examples/misc/lib/library_tour/async/stream.dart#L79)                             | [library-tour.md (3)](https://github.com/dart-lang/site-www/blob/master/src/_guides/libraries/library-tour.md?plain=1#L1408)        |
| [io_test.dart (1)](https://github.com/dart-lang/site-www/blob/master/examples/misc/test/library_tour/io_test.dart#L155)                               | [library-tour.md (4)](https://github.com/dart-lang/site-www/blob/master/src/_guides/libraries/library-tour.md?plain=1#L1619)        |
| [io_test.dart (1)](https://github.com/dart-lang/site-www/blob/master/examples/misc/test/library_tour/io_test.dart#L155)                               | [_dart-io-tour.md](https://github.com/dart-lang/site-www/blob/master/src/_guides/libraries/_dart-io-tour.md?plain=1#L115)         |
| [stream_controller.dart](https://github.com/dart-lang/site-www/blob/master/examples/misc/lib/articles/creating-streams/stream_controller.dart#L140) | [creating-streams.md](https://github.com/dart-lang/site-www/blob/master/src/_articles/libraries/creating-streams.md?plain=1#L131) |

Keep in mind that some changes may require some extra formatting by `dart format`.

### Additional context

Let me know if you need any help or clarifications, thanks!

**Comment by lkmandy** [comment]
Hi, I will like to work on this issue.

**Comment by parlough** [comment]
Hi @lkmandy, that would be great. Let me know if you have any issues. Thanks so much!
