### ISSUE TITLE
[PAGE ISSUE]: 'Write command-line apps'

### ISSUE THREAD

**Issue by yanadior9029** [dart-lang/site-www#3628]
### Page URL

https://dart.dev/tutorials/server/cmdline

### Page source

https://github.com/dart-lang/site-www/tree/master/src/_tutorials/server/cmdline.md

### Describe the problem

Please provide more guidance on which path file - quotes.txt will be picked up from. Through hit and trial, i figured out that 'quotes.txt' should be under root of the dart-project.
Is there any concept of classpath in Dart ?

**Comment by domesticmouse** [comment]
No, Dart doesn't have a concept of a classpath, nor does it have WAR files. Dart's command line experience is closer to that of Python or Node.js than to that of Java. The current working directory for an application is the directory in which the executable is launched. 

With that said, I think we could be clearer [here](https://dart.dev/tutorials/server/cmdline#running-dcat) and spell out downloading `quotes.txt` using curl, say, before running the command.
