### ISSUE TITLE
diagnostics page should support an "old diagnostic name" concept

### ISSUE THREAD

**Issue by srawlins** [dart-lang/site-www#3652]
### Describe the problem

I'd like to rename the `invalid_super_invocation` diagnostic to `super_invocation_not_last`. @bwilkerson points out that this currently requires creating a section with the old name, which links to the new section (by the new name). We'd like a better way that doesn't require that click.

The current fragment links work by translating the diagnostic names, found in headers, into hashes:

```markdown
### invalid_super_invocation
```

becomes the following HTML:

```html
<h3 id="invalid_super_invocation">
<a class="anchor" href="#invalid_super_invocation" aria-hidden="true">
<span class="octicon octicon-link"></span>
</a>invalid_super_invocation</h3>
```

Can we add infrastructure to add:
* another anchor below the h3 (`<a id="old_name" aria-hidden="true"></a>`)
* some text (maybe italic) indicating the old name (`<em>previously called <code>old_name</code></em>`)

(I think 302 redirects are out because each diagnostic is just a fragment link.)

**Comment by srawlins** [comment]
I'd be happy to take on this task if someone can point me to the script that turns the diagnostics in the SDK into the diagnostics.md file in this repo.

**Comment by bwilkerson** [comment]
The generator actually produces a `diagnostics.md` in the `analyzer` package's `tools` directory, and that file is currently hand-copied to this repository. The generator is here: https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/tool/diagnostics/generate.dart.

**Comment by parlough** [comment]
@srawlins Sounds like you'll handle this on the SDK side but if you need anything on this end, feel free to ping me again here :)

**Comment by srawlins** [comment]
Woohoo! Thanks!
