### ISSUE TITLE
Update FAQ and make it more visible

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#366]
https://www.dartlang.org/faq needs to be updated and then linked to more prominently.

**Comment by kwalrath** [comment]
@kevmoo I think we need to do this soon. Maybe you could print it out and mark it up on one of your many flights?

**Comment by kevmoo** [comment]
@anders-sandholm – wanna take a look?

**Comment by anders-sandholm** [comment]
Yes -- I'd prefer to make this part of our general upgrade for Dart 2.
Do we have a label for these issues yet?

**Comment by kwalrath** [comment]
We have two ways of tracking Dart 2 upgrades:

* [2-dev milestone](https://github.com/dart-lang/site-www/milestone/5) (which this bug is assigned to)
* [Dart 2.0 project](https://github.com/dart-lang/site-www/projects/2)

**Comment by anders-sandholm** [comment]
Fixed with https://github.com/dart-lang/site-www/pull/842

**Comment by chalin** [comment]
> https://www.dartlang.org/faq needs to be updated 

Nice to see this updated!

@kwalrath - date at the top should be updated too; it currently reads: _Updated August 2017_

> and then linked to more prominently.

Did we want to link to the FAQ from somewhere: side-nav, footer, or Language Overview?

I'll reopen this issue so that we can track the items mentioned above.

**Comment by anders-sandholm** [comment]
Just updated the date to May 2018 and fearlessly committed straight to master.

**Comment by anders-sandholm** [comment]
I think it's fine not to link to the FAQ more prominently. 
Let's close this issue.
