### ISSUE TITLE
[PAGE ISSUE]: 'Codelabs' Broken link

### ISSUE THREAD

**Issue by mmahamed** [dart-lang/site-www#3660]
### Page URL

https://dart.dev/codelabs/

### Page source

https://github.com/dart-lang/site-www/tree/master/src/codelabs/index.md

### Describe the problem

The link for 'Intro to Dart for Java Developers' is broken.

**Comment by danagbemava-nc** [comment]
Hi @mmahamed, thanks for catching that. 

<details>
<summary>screenshot</summary>


<img width="1440" alt="Screenshot 2021-11-05 at 09 24 54" src="https://user-images.githubusercontent.com/88313112/140488910-271f79b6-6dc0-4912-a5de-a135f37ffd45.png">

</details>

**Comment by domesticmouse** [comment]
Hi @mmahamed, thanks for your report. The codelab is back online.
