### ISSUE TITLE
[PAGE ISSUE]: 'Asynchronous programming: futures, async, await'

### ISSUE THREAD

**Issue by PeperMarkreel** [dart-lang/site-www#3670]
### Page URL

https://dart.dev/codelabs/async-await.html

### Page source

https://github.com/dart-lang/site-www/tree/master/src/codelabs/async-await.md

### Describe the problem

This is a really not helpful, confusing and itself contradicting example page. Please redo this completely and make it simple. 

### Expected fix

A good, not confusing or contradictory explanation of asynchronous programming in dart.

**Comment by parlough** [comment]
Hey @PeperMarkreel, thanks for opening an issue. I can understand you may be frustrated or confused by some of examples. Are there any specific areas which you think need improvement or are contradictory? Thanks again!

**Comment by parlough** [comment]
Thanks again for opening an issue. I'm going to close this for now as we need more actionable pain areas and potential improvements. We're always open to suggestions and improvements though!
