### ISSUE TITLE
CSS is not loading on Effective Dart

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#3692]
### Page URL

https://dart.dev/guides/language/effective-dart

### Describe the problem

The CSS file 404s so there is no styling on the page.

**Comment by kevmoo** [comment]
CC @kwalrath @parlough

**Comment by parlough** [comment]
I’m not currently experiencing this. Are there any other errors in the console?

Also can you try disabling the cache in the network tab of developer tools and reloading the page?

**Comment by natebosch** [comment]
![image](https://user-images.githubusercontent.com/7528195/143920883-25663c63-f297-4237-9da2-82e2b6f03fc4.png)

Console error:

```
effective-dart:1 Refused to apply style from 'https://dart.dev/assets/main-5e520dd94f9ec5a550bab0f5016724c330a7cd2bfd66265ed95105d374177a66.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

The request for CSS gets a 404:

```
Request URL: https://dart.dev/assets/main-5e520dd94f9ec5a550bab0f5016724c330a7cd2bfd66265ed95105d374177a66.css
Request Method: GET
Status Code: 404 
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by natebosch** [comment]
> Also can you try disabling the cache in the network tab of developer tools and reloading the page?

I have been reloading without the cache.

**Comment by kwalrath** [comment]
Thanks for letting us know, @natebosch. It's working for me, but I'll consult the website team.

What happens if you go to another page, such as https://dart.dev/guides/language/language-tour?

**Comment by natebosch** [comment]
> What happens if you go to another page, such as https://dart.dev/guides/language/language-tour?

Other pages work.

The page that is broken is using the hash `5e520dd94f9ec5a550bab0f5016724c330a7cd2bfd66265ed95105d374177a66`, so far the ones that work look like they are using the hash `a25e572053d2725cea15007818f58ca5c0018ebe1fcd3da915a2a07e14d2a3d0`.

Should these be identical across all pages?

**Comment by kwalrath** [comment]
I've filed an internal bug (b/208275562) against Firebase Hosting.

**Comment by kwalrath** [comment]
And it's fixed! It took some detective work, apparently. But I suspect we helped other sites with our report, so worth it.

**Comment by parlough** [comment]
Great to hear!

Thanks again for the report @natebosch :)
