### ISSUE TITLE
[PAGE ISSUE] 'Add Elements to the DOM' Page Issue

### ISSUE THREAD

**Issue by Avingo255** [dart-lang/site-www#3697]
### Page URL

https://dart.dev/tutorials/web/low-level-html/add-elements#:~:text=%20Add%20elements%20to%20the%20DOM%20%201,app.%20The%20main%20%28%29%20function%20uses...%20More%20

### Describe the problem

On the example with the todo list, it is currently not possible to run the app because there are many errors within the code. This could be because the code there is actually an older form of Dart. If you try to run the app, it will tell you that there was an error compiling to JavaScript because there are many errors in the code.

**### Errors in the code provided:**

- line 9 • The non-nullable variable 'toDoInput' must be initialized. (view docs)
  Try adding an initializer expression.

- line 10 • The non-nullable variable 'toDoList' must be initialized. (view docs)
  Try adding an initializer expression.
 
- line 11 • The non-nullable variable 'deleteAll' must be initialized. (view docs)
  Try adding an initializer expression.
 
- line 14 • A value of type 'Element?' can't be assigned to a variable of type 'InputElement'. (view docs)
  Try changing the type of the variable, or casting the right-hand type to 'InputElement'.
 
- line 15 • A value of type 'Element?' can't be assigned to a variable of type 'UListElement'. (view docs)
  Try changing the type of the variable, or casting the right-hand type to 'UListElement'.
 
- line 20 • Unnecessary new keyword. (view docs)

### Expected fix

Please could you fix/rewrite the code so that the app runs as expected?

### Additional context

There are no problems anywhere else on the page.

**Comment by parlough** [comment]
Thanks for opening the issue @Avingo255. There's a work in progress change which will fix this soon!
