### ISSUE TITLE
documentation for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/site-www#3699]
This is the tracking issue to update the website to include information about enhanced enums.

See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

**Comment by mit-mit** [comment]
Hi @parlough how is this coming along? Anything I can do to help?

**Comment by parlough** [comment]
@mit-mit I've opened https://github.com/dart-lang/site-www/pull/4026 with documentation for enhanced enums. Any feedback there would be great :)
