### ISSUE TITLE
Document "environment declarations"

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#37]
_From @nicolasgarnier on August 26, 2014 15:19_

_From [rnystrom@google.com](https://code.google.com/u/rnystrom@google.com/) on January 06, 2014 23:47:15_

The VM and core libraries have some sort of "fromEnvironment()" thing. I can't find any documentation on how to use it, what it's intended purpose is, how it works in a browser, rationale behind it, why it has such a confusing name, etc.

_Original issue: http://code.google.com/p/dart/issues/detail?id=15926_

_Copied from original issue: dart-lang/www.dartlang.org#809_

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 15:19_

_From [sethladd@google.com](https://code.google.com/u/sethladd@google.com/) on January 07, 2014 13:43:17_

In the meantime: http://blog.sethladd.com/2013/12/compile-time-dead-code-elimination-with.html

**Status:** Triaged  
  **Labels:** -Type-Defect Type-Task Area-Documentation

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 15:19_

_From [lrn@google.com](https://code.google.com/u/lrn@google.com/) on January 09, 2014 03:26:11_

The problem with this feature is that there is no class or library to document. All of the functionality lives in three constructors on different classes.

The String.fromEnvironment is the most generic one, and we should probably put any documentation there, and let the other two refer to the String constructor.

Also, the syntax to define the values isn't part of the language or library, We have agreed on using -Dfoo=bar on the VM and dart2js command lines, but another embedder or compiler could use something else. We can at most use the syntax as an example.

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 15:19_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on June 04, 2014 14:53:22_

**Labels:** -Area-Documentation Area-Site

**Comment by atsansone** [comment]
@munificent : Is this still an issue? We cover a good bit on [envvar](https://dart.dev/search?cx=011220921317074318178%3A_yy-tmb5t_i&ie=UTF-8&hl=en&q=environment+variables), but maybe we're not as complete as needed.

**Comment by parlough** [comment]
Superseded by https://github.com/dart-lang/site-www/issues/4349
