### ISSUE TITLE
Firebase preview deploys are failing

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3701]
### Describe the problem

Firebase preview deploys in PRs are failing due to the JWT token being invalid.

See https://github.com/dart-lang/site-www/runs/4446366078?check_suite_focus=true for more context on a failed run.

This is causing PR builds from branches on the repo to fail.

### Expected fix

Not sure yet, but looks like it may be an issue with the [service account](https://github.com/dart-lang/site-www/blob/master/.github/workflows/build.yml#L158) as the error mentions a failure to authenticate.

**Comment by parlough** [comment]
\cc @mit-mit

**Comment by mit-mit** [comment]
This seems to be happening across several of our repos. I'm not sure why yet.

**Comment by mit-mit** [comment]
I believe I've fixed the credentials for this; see this sample PR which is now deploying previews:
https://github.com/dart-lang/site-www/pull/3727

Unfortunately a side-effect of this fix is that the existing token used for production deploys likely doesn't work anymore. I believe the right fix for that is to use the github action for deploys to live also:
https://github.com/dart-lang/site-www/pull/3726

cc @kwalrath @parlough

**Comment by parlough** [comment]
I'm closing this as fixed due to PR and live deploys both working for a while. Thanks @mit-mit!
