### ISSUE TITLE
Update SDK release wiki page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3714]
### Describe the problem

https://github.com/dart-lang/site-www/wiki/Updating-to-new-SDK-releases refers to Travis, for one thing. It could use a refresh.

**Comment by EKivutha** [comment]
@parlough  please assign

**Comment by parlough** [comment]
Hi @EKivutha, thanks for the ping! Unfortunately for this specific issue, the GitHub wiki pages must be updated by someone with commit access to the repository as they don't support pull requests. 

Kathy updated the majority of the page a few days ago besides the Travis section. I will update this to refer to how to update the SDK versions used by the new Docker based infrastructure. 

If there is something else you'd like to see updated on the page, please let us know!

**Comment by EKivutha** [comment]
@parlough how do I get commit access

**Comment by kwalrath** [comment]
> @parlough how do I get commit access

Commit access is pretty rare, but we welcome PRs and specific up

**Comment by kwalrath** [comment]
Oops, didn't mean to close this! Commit access is fairly locked down, but as @parlough said, we'd welcome specific suggestions for change. And of course we welcome pull requests for non-wiki changes!

**Comment by parlough** [comment]
I've updated this to remove travis and with new instructions of how to test new releases. Thanks!
