### ISSUE TITLE
[PAGE ISSUE]: 'What’s new'

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3715]
### Page URL

https://dart.dev/guides/whats-new

### Page source

https://github.com/dart-lang/site-www/tree/master/src/_guides/whats-new.md

### Describe the problem

Needs an update for 2.15.

### Expected fix

Also update https://dart.dev/guides/language/evolution.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/a2aefa76ab63c86fe6bc7c900132972506395687
