### ISSUE TITLE
[2.16] Document analyzer's new strict-casts mode

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3721]
### What information is missing?

The analyzer's [new `strict-casts` mode](https://github.com/dart-lang/language/pull/2019) needs to be documented with the release of 2.16 and any old mentions of the "no implicit casts" need to be updated or indicated that they are deprecated.

### How would you like us to fix this problem?

- [ ] Document new `strict-casts` mode
- [ ] Update old mention of deprecated "no implicit casts" mode
- [ ] Update our examples to use this new mode

**Comment by mit-mit** [comment]
@parlough are you working on this, or do we need to find someone else?

**Comment by parlough** [comment]
@mit-mit I'll get back to this today and get something up for review for this and the other options mentioned in https://github.com/dart-lang/site-www/issues/2338 by today or tomorrow.

**Comment by parlough** [comment]
Closing as a duplicate of https://github.com/dart-lang/site-www/issues/2338
