### ISSUE TITLE
[PAGE ISSUE]: 'How to use packages'

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#3723]
### Page URL

https://dart.dev/guides/packages

### Page source

https://github.com/dart-lang/site-www/tree/master/src/_guides/packages.md

### Describe the problem

> Use pub to get your package’s dependencies.

should read:

> Use `dart pub` to get your package’s dependencies.

**Comment by kwalrath** [comment]
I think we call it _pub_ intentionally, since it's sometimes `dart pub` and sometimes `flutter pub` — or am I wrong about that?
