### ISSUE TITLE
Confusing code example in futures-error-handling guide

### ISSUE THREAD

**Issue by BorisNaguet** [dart-lang/site-www#373]
Hello,

on this page:
https://www.dartlang.org/guides/libraries/futures-error-handling#completing-the-future-returned-by-whencomplete

this example:
```dart
void main() {
  funcThatThrows()
    .then((_) => print("Won't reach here..."))   // Future completes with an error.
    .whenComplete(() => print("... or here...")) // Future completes with the same error.
    .then((_) => print("... nor here."))         // Future completes with the same error.
    .catchError(handleError)                     // Error is handled here.
}
```

It's confusing, because "Won't reach here, or here, nor here" seems to mean that it won't be printed.
But "... or here..." is actually printed (but the error is transmitted on the next Future as the comments explain correctly).

I think it would be clearer with an executable code in dartpad like on other parts of the site.

**Comment by lrhn** [comment]
I agree that it is so misleading that it's probably just wrong. The `whenComplete` part should, and will, be printed.

**Comment by kwalrath** [comment]
@BorisNaguet you've convinced me that the page should feature DartPad. (I think its original version was from before DartPad's existence.)

**Comment by Sfshaza** [comment]
Yes, this piece was written years ago by our DPE, and long before DartPad existed. I think it's a great idea!

**Comment by kwalrath** [comment]
Related to #407.
