### ISSUE TITLE
[PAGE ISSUE]: 'Custom package repositories'

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3730]
### Page URL

https://dart.dev/tools/pub/custom-package-repositories.html

### Page source

https://github.com/dart-lang/site-www/tree/master/src/tools/pub/custom-package-repositories.md

### Describe the problem

This page needs a copy edit.

**Comment by parlough** [comment]
I'm going to close this as a duplicate and consolidate this in https://github.com/dart-lang/site-www/issues/3921
