### ISSUE TITLE
Add links to explain behavior on 'Fixing type promotion failures' page

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/site-www#3744]
### Page URL

https://dart.dev/tools/non-promotion-reasons.html

### Page source

https://github.com/dart-lang/site-www/tree/master/src/tools/non-promotion-reasons.md

### Describe the problem

A lot of people are confused that non-local variables aren't automatically promoted by `is` or null checks.  Although https://dart.dev/tools/non-promotion-reasons.html helps explain that the behavior is expected, it doesn't help readers understand the rationale for the behavior, so the inability to promote non-local variables seems arbitrary.

### Expected fix

It would be useful to add a note that explains *why* only local variables can be promoted.  Perhaps add links to https://github.com/dart-lang/sdk/issues/21530, https://github.com/dart-lang/sdk/issues/44327, or to https://stackoverflow.com/q/65035574/.

**Comment by atsansone** [comment]
@MaryaBelanger : FYI. Not sure if this folds into your existing Type Promotion planning.

**Comment by parlough** [comment]
That makes sense, thanks for clarifying! I took a closer look at some of the links you shared and it seems the new additions to the page do a decent job of covering the "why" covered in those inline.

For example, when explaining why getters can't be promoted:

> The compiler has no way to guarantee that a getter returns the same result every time. Because their stability can’t be confirmed, getters are not safe to promote.

And another when discussing external fields:

> External fields don’t promote because they are essentially external getters; their implementation is code from outside of Dart, so there’s no guarantee for the compiler that an external field will return the same value each time it’s called.

If you get a chance, could you take a look and see if any particular explanation is missing or not sufficient? If so, we definitely should consider expanding the explanation.
