### ISSUE TITLE
Dart live editor not working due to localStorage access error

### ISSUE THREAD

**Issue by AmirhosseinAzimyzadeh** [dart-lang/site-www#3746]
### Page URL

https://dart.dev/

### Describe the problem

From the main page (in the console) I have access to localStorage and it's working just fine but somehow live editor is unable to access to the localStorage

Message on live editor:
DartPad requires localStorage to be enabled. For more information, visit dart.dev/tools/dartpad/troubleshoot.

console errors:
```
uncaught Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at jv.iZ (embed_dart.dart.js:13163)
    at ka.io (embed_dart.dart.js:11596)
    at Object.eval (eval at wv (embed_dart.dart.js:819), <anonymous>:3:35)
```

### Additional context

Browser:  chrome version 96.0.4664.110 (Official Build) (64-bit) (cohort: Stable)

**Comment by parlough** [comment]
Hey @AmirhosseinAzimyzadeh, thanks for opening an issue!

I'm curious where is the (live editor) DartPad you are trying? Is it at the bottom of the homepage on https://dart.dev, https://dartpad.dev, or somewhere else? Thanks again!

**Comment by AmirhosseinAzimyzadeh** [comment]
@parlough 
Bottom of the home page (https://dart.dev/)

**Comment by parlough** [comment]
Hey again @AmirhosseinAzimyzadeh, thanks for the update. 

If you get a chance, I recommend trying the instructions under [Embedded DartPads don't appear](https://dart.dev/tools/dartpad/troubleshoot#embedded-dartpads-dont-appear). Particularly, cookies must be allowed for dart.dev and dartpad.dev in most browsers for DartPad to be able to properly access local storage. 

Also give https://dartpad.dev/ a try which is a full webpage version of DartPad(the live editor). If neither of those work after checking/updating your settings, let me know. Thanks again!

**Comment by AmirhosseinAzimyzadeh** [comment]
After allowing third party cookies it's working 
Thanks.
