### ISSUE TITLE
Link to programmatically retrieve all versions

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/site-www#3749]
### Page URL

https://dart.dev/get-dart/archive

### Describe the problem

The get-dart/archive page lists a link to download any version, but it doesn't list a link to retrieve all available versions.

### Expected fix

An answer to the following question: Is there a link to get a list of all versions i.e. where do the dropdowns get their data from?

**Comment by parlough** [comment]
Hi @modulovalue, you can reference our code to retrieve the versions [here](https://github.com/dart-lang/site-www/blob/master/src/get-dart/sdk_builds.dart/lib/src/dart_downloads.dart). We use the [google_apis package](https://pub.dev/packages/googleapis) and its storage API to query for the listing. Using other language's google storage APIs should look similar.

As an example, this generates a link like https://storage.googleapis.com/storage/v1/b/dart-archive/o?delimiter=%2F&prefix=channels%2Fstable%2Frelease%2F&alt=json to retrieve the JSON listings for the `stable` channel. You can change `stable` to `beta` or `dev` as well.

Here's another possible example which retrieves an XML listing: https://storage.googleapis.com/dart-archive?delimiter=%2F&prefix=channels%2Fstable%2Frelease%2F.

Let me know if that helps, thanks for opening an issue! If it's commonly desired enough, we could perhaps look at including a more easily human readable JSON link example and some extra information on getting a list of releases.

**Comment by modulovalue** [comment]
Thank you :)
