### ISSUE TITLE
sdk constraint section should suggest an upper bound

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/site-www#375]
https://www.dartlang.org/tools/pub/pubspec#sdk-constraints

Pub is (probably) soon going to stop letting you publish versions of packages that don't have an upper bound constraint on the sdk (because its not safe at all generally). The docs should probably also suggest one so everybody doesn't run into this on new packages :).

For now the suggestion should probably be `>=1.x.x <2.0.0` (note that ^ syntax isn't supported for sdk constraints)

**Comment by kwalrath** [comment]
That's funny, just today I used `^1.24.0` and it worked. But I know it's dicey, since SDKs earlier than a certain version don't support `^` syntax.

I'll make this fix.
