### ISSUE TITLE
[PAGE ISSUE]: 'DartPad in tutorials: Best practices'

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3757]
### Page URL

https://dart.dev/resources/dartpad-best-practices.html

### Page source

https://github.com/dart-lang/site-www/tree/master/src/resources/dartpad-best-practices.md

### Describe the problem

Do we really need the survey at the end of the page any more? (Is anyone looking at the responses?)

### Expected fix

Remove the survey, perhaps documenting the survey-publishing process in the wiki or internal docs.

**Comment by kwalrath** [comment]
@inmatrix maybe you know?

**Comment by InMatrix** [comment]
Good catch. This survey is no longer needed.
