### ISSUE TITLE
robots.txt should reference sitemap.xml

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#3762]
### Describe the problem

Our `robots.txt` file does not reference `sitemap.xml` – it should!

### Expected fix

Add the reference!

**Comment by kevmoo** [comment]
CC @kwalrath @parlough 

See https://developers.google.com/search/docs/advanced/robots/create-robots-txt

**Comment by kevmoo** [comment]
FYI: `sitemap.xml` is correctly configured in our Google Search console settings, so this isn't super urgent. But it would be nice to do for other search engines

**Comment by kevmoo** [comment]
@parlough – assuming https://github.com/dart-lang/site-www/pull/3774 works, would you follow-up with this one?

**Comment by parlough** [comment]
Yep!
