### ISSUE TITLE
language tour: external and interface keywords

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/site-www#3767]
### Page URL

https://dart.dev/guides/language/language-tour#keywords

### Page source

https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

### Describe the problem

In the table of keywords in the language tour, the `external` and `interface` keywords currently link to stackoverflow discussions about these keywords rather than official explanations of these keywords.

### Expected fix

For the `external` keyword, you could possibly link [here](https://spec.dart.dev/DartLangSpecDraft.pdf#External%20Functions) instead. 

For the `interface` keyword, consider removing it from the table since it is no longer considered a keyword in the language.

### Additional context

The [stackoverflow discussion](https://stackoverflow.com/questions/28595501/was-the-interface-keyword-removed-from-dart) about the `interface` keyword suggests that the keyword was removed from the language in the year 2012. 

Is it still relevant to the language tour?

There does seem to be a small bit of relevant information in that the keyword has a superscript of 2 which means:

> Words with the superscript 2 are built-in identifiers. To simplify the task of porting JavaScript code to Dart, these keywords are valid identifiers in most places, but they can’t be used as class or type names, or as import prefixes.

And this does seem to be true in that the following code produces a compile error.

```dart
class interface {}
```
```
Error: Can't use 'interface' as a name here.
```

Although, surprisingly, the following code does not produce an error:
```dart
class function {}
```
despite `function` being a [javascript keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords).

**Comment by parlough** [comment]
Thanks for opening such a thorough issue @mmcdon20.

I love your idea to link to the spec for `external`. 

As for `interface`, that's slightly more complicated. I think it still deserves a place in the table as it provides an explanation of why it can't be used as an identifier in some situations. Beyond that, it also provides a useful reference for Java and C# developers to find the Dart equivalent. We could potentially point to a better location if you have one in mind though.

About your final mention of `function` as an identifier. Do you expect that to throw an error? `function` is not a reserved keyword in Dart.

Thanks again!

**Comment by mmcdon20** [comment]
> As for `interface`, that's slightly more complicated. 

Yeah, I thought this might be the case...

> I think it still deserves a place in the table as it provides an explanation of why it can't be used as an identifier in some situations. Beyond that, it also provides a useful reference for Java and C# developers to find the Dart equivalent. 

I could potentially agree if it linked to a good explanation somewhere, although it still might seem slightly weird to have it in the table of keywords if it isn't actually a keyword.

> We could potentially point to a better location if you have one in mind though.

Not really, these are about all I could find:
https://news.dartlang.org/2012/11/breaking-change-deprecated-language-features-and-dart2js.html
https://news.dartlang.org/2012/06/proposal-to-eliminate-interface.html

Maybe it is worth creating an explanation somewhere if something better doesn't already exist.

> About your final mention of function as an identifier. Do you expect that to throw an error? function is not a keyword in Dart, therefore you're free to use it as an identifier. The superscript description is about some Dart keywords being allowed in some locations to ease identifiers that were allowed in JavaScript, such as dynamic or export. Was it the JavaScript mention that caused this confusion? Perhaps we shouldn't mention JavaScript anymore here anyway as not many people are directly migrating code from JavaScript to Dart these days.

It is possible I completely misunderstood the meaning of that passage. 

If you compile the `class function {}` code to js, the compiler will actually change the name of `function` to `$function` in the compiled output (presumably so that it does not clash with the `function` keyword in javascript). If you name the class something like "hello" instead it doesn't add a $ to the name. 

I had thought that the reason `interface` is disallowed here is because it also clashes with the `interface` keyword in javascript, but instead of simply adding a $ to the name to get around that, it is disallowed altogether. Just seems inconsistent to me.

**Comment by parlough** [comment]
> I could potentially agree if it linked to a good explanation somewhere, although it still might seem slightly weird to have it in the table of keywords if it isn't actually a keyword.

I mean it is treated specially by the Dart language and tooling as a "built-in identifier", so it is still a sort of keyword. 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/18372958/149715524-153054f9-65e2-4c22-a055-0d38d0e1007b.png">

I agree the current location we're pointing isn't ideal. Perhaps the blog post you linked or some more up-to-date alternative or article. I'll give it some thought.

---

> It is possible I completely misunderstood the meaning of that passage.
> 
> If you compile the `class function {}` code to js, the compiler will actually change the name of `function` to `$function` in the compiled output (presumably so that it does not clash with the `function` keyword in javascript). If you name the class something like "hello" instead it doesn't add a $ to the name.
> 
> I had thought that the reason `interface` is disallowed here is because it also clashes with the `interface` keyword in javascript, but instead of simply adding a $ to the name to get around that, it is disallowed altogether. Just seems inconsistent to me.

So this mention is actually talking about the other way around. Looking back to Dart's origins, where it was primarily used as a JavaScript alternative, there were situations where people were almost directly translating JS code to Dart code. This note is about how allowing some of Dart's keywords to not be reserved in all situations may make it easier to convert JS code which used those keywords to to Dart.

For example, the following JS code contains two Dart keywords:

```js
var factory = 'Hi';
var get = 'World';
console.log(factory + ' ' + get);
```

I know this code is useless, but it can be converted to Dart easily despite using Dart keywords since they were specifically allowed in some places. This applies to larger situations and larger code bases where the naming actually make sense.

```dart
void main() {
  var factory = 'Hi';
  var get = 'World';
  print(factory + ' ' + get);
}
```

How you name identifiers in Dart has no consequence to the compiled JS as the compiler can choose whatever name it needs to and Dart2JS(the production compiler) usually is configured to use completely minified names like `ht` anyway. 

I can definitely understand where the confusion came from though so I think we should just not mention JavaScript. It is irrelevant for the most part and doesn't help the user.

Thanks again, I appreciate all of your input 💙

**Comment by parlough** [comment]
To sum up, I think there are three action items here:

- [ ] Update the `external` entry to link to the spec: https://spec.dart.dev/DartLangSpecDraft.pdf#External%20Functions
- [ ] Remove the mention to JavaScript in the built-in identifier explanation
- [ ] Try to find (or create) a suitable alternative to link to for the `interface` built-in identifier

**Comment by mmcdon20** [comment]
@parlough Thanks for the clarification.

Although I wonder, if `interface` no longer really does anything in dart, does it still need to be a "built-in identifier", or is it just a holdover from when it used to do something? That might be a question for the language engineers.

**Comment by mmcdon20** [comment]
Just a thought, but another possibility would be to have the `interface` keyword link to the section on [implicit interfaces](https://dart.dev/guides/language/language-tour#implicit-interfaces). 

Seems like that is the information you would want if you were a Java/C# developer looking for the dart equivalent (even if it isn't technically about `interface` as a keyword, and `implements` already links there, but it still might be the most relevant place in the docs to link to).
