### ISSUE TITLE
Standardize usage of em dash

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3768]
### Describe the problem

Currently we are inconsistent in our usage of em-dash(and perhaps other dashes) and not all usages follow the [Google developer documentation style guide](https://developers.google.com/style/dashes).

### Expected fix

We should consistently follow the style guide.

**Comment by kwalrath** [comment]
Specifically, the style guide calls for no spaces around em dashes.

Is it still OK to use a true em dash (e.g. Option+Shift+hyphen on Mac) as a character? It's easier to read than `&mdash;`.

**Comment by parlough** [comment]
It seems the true em dash(—) is still fine to include and works just fine.

**Comment by kwalrath** [comment]
We should also check for remaining short dashes. E.g. in https://dash-site-dev--dart-r4q6o37f.web.app/guides/libraries/create-library-packages#organizing-a-library-package there's one good dash (after _intended_ on the second line below) and one bad (highlighted before `shelf.dart` on the same line):

<img width="901" alt="image" src="https://user-images.githubusercontent.com/2164483/150210865-d141959b-8e45-42b4-9ea5-d1a287c76c4f.png">
