### ISSUE TITLE
Add a key binding to focus search bar

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3785]
### Describe the problem

A lot of websites have a key binding to focus (and open if needed) the search bar. It's convenient, particularly for keyboard users.

### Expected fix

Add a key binding to focus the search bar.

Google Search and GitHub both use `/` so I think it would be a good choice.

Consider bringing over the implementation to docs.flutter.dev as well.

**Comment by parlough** [comment]
Any thoughts?

**Comment by kwalrath** [comment]
@khanhnwin or @johnpryan what do you think?

**Comment by johnpryan** [comment]
Sounds great, it looks like [api.flutter.dev](https://api.flutter.dev/) uses `/` too.

**Comment by khanhnwin** [comment]
Sgtm! That'd be great!
