### ISSUE TITLE
Consider adding a OSSF Scorecard analysis action

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3787]
### Describe the problem

[OSSF Scorecards](https://github.com/ossf/scorecard#security-scorecards) is a tool to assess various checks related to software security. They now have an official [GitHub action](https://github.com/ossf/scorecard-action) so we could consider including at least some of its rules in our build.

**Comment by kwalrath** [comment]
@khanhnwin fyi

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/3199718ef9fb68f02845a7937cf0509a3bc39a2a
