### ISSUE TITLE
Replace or simplify font awesome usage

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3790]
### Describe the problem

After the infrastructure update we use JS for integrating Font Awesome. Even using brotli it is still 436 kB and by far the largest thing on the website for just a few icons.

### Expected fix

Manually include the icons we need perhaps as a font or switch to material icons and/or SVGs.

**Comment by kwalrath** [comment]
@khanhnwin @btobin fyi

**Comment by hrk2023** [comment]
Hey @parlough can I work on this issue?

**Comment by hrk2023** [comment]
Ok then I will start with replacing the font awesome links with appropriate material icons.

**Comment by hrk2023** [comment]
@parlough I made a PR [#151](https://github.com/dart-lang/site-shared/pull/151) in the dart-lang/site-shared repo regarding this issue. Please check it out and that's done I can create a PR for some CSS change required for the material icons.

**Comment by hrk2023** [comment]
@parlough I made a PR [#3830](https://github.com/dart-lang/site-www/pull/3830) in dart-lang/site-www repo to add some css styles for material icons added in dart-lang/site-shared.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/site-www/issues/4278 to consolidate the work.
