### ISSUE TITLE
Style guidelines for allowing implementing interfaces

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/site-www#382]
The [Design / types](https://www.dartlang.org/guides/language/effective-dart/design#types) section of the style guide gives recommendations when and how to `extend` or `mixin` classes from other packages. However, using `implements` on a class from another package can also lead to errors, if that package uses `is` expressions to guard accesses to protected class members.

I just encountered this problem while working with [package:built_collection](https://pub.dartlang.org/packages/built_collection). I want to write a class that implements `BuiltSet`, but doing that would break [this](https://github.com/google/built_collection.dart/blob/2e1d90255b4c071abd5287918d9f4a12d69da975/lib/src/set/built_set.dart#L30) line.

I guess the only way to resolve this is
> AVOID implementing a class that isn’t intended to be implemented.

The other option,
> DO guard accesses to protected members with a `obj.runtimeType == MyClass` check

would solve the `implements` problem, but is unnecessarily restrictive in the `extends` case.

Best regards,
Philipp

**Comment by munificent** [comment]
Fixed in https://github.com/dart-lang/site-www/commit/6836e7d0c4bb1008de2dbc517baa4661a0a48ecd.
