### ISSUE TITLE
[mirror] Deploy issues with mirror sites

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/site-www#3832]
### Describe the problem

In #3726 the deploy workflow was migrated to the Firebase deploy, which causes our mirror site unable to follow up on changes. Reasons:

- We use a legacy deploy workflow as defined at https://github.com/cfug/dart.cn/blob/aade33ab22e4cd61aff49b1c91224d6cbded896c/.github/workflows/build.yml.
- We don't have valid Firebase projects (at present), and I don't think we have any plan to migrate to Firebase since our host is standalone without any architectural services.

We do have a sync schedule for every few weeks, merging all new commits from the repo to a localized one. Now we've blocked by the workflow update.

### Expected fix

A valid solution to indicate how can we bypass the Firebase deploy, or continue to use the legacy workflow.

### Additional context

Mirror site repo: https://github.com/cfug/dart.cn

**Comment by chenglu** [comment]
Offline chatted and checked with Alex, these changes may not affect the deployment of the .cn site since the .cn site is not using Firebase Hosting. 

When synchronizing the docs repo, we might consider ignoring the Firebase configuration files and build script, such as the `firebase.json`, thanks!

**Comment by parlough** [comment]
Thanks for your hard working maintaining and localizing the Chinese language sites! Let us know if any changes here will help your processes :D

**Comment by AlexV525** [comment]
A further step might be migrated to a Firebase host, then we can throw our concern away. :)
