### ISSUE TITLE
Standardize code highlighting system

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3846]
### Describe the problem

Currently we use a prettify system with tools to convert blocks that start with `{% prettify dart tag=pre+code %}` as well as a rouge based system relying on the markdown code blocks (```).

Prettify is no longer supported, does highlighting in the browser, requires a more complicated system, and complicates our site infrastructure. We should standardize on rouge and the normal markdown code blocks.

### Expected fix

- [ ] Support code background highlighting in markdown code blocks (https://github.com/dart-lang/site-www/issues/1744)
- [ ] Verify rouge highlights as expected and uses the proper styles
- [ ] Switch all usages of prettify to markdown code blocks
- [ ] Remove prettify front-end infrastructure (CSS, SCSS, and JS)
- [ ] Remove prettify specific generation handling
- [ ] Support copying similar to Flutter's infrastructure (https://github.com/dart-lang/site-www/issues/1105)

**Comment by Rushour0** [comment]
Hey, can I work on this?
I would need to understand the issue a bit more neatly, if you can give an example run case for the same

**Comment by parlough** [comment]
The main part that needs to be done is tracked in https://github.com/dart-lang/site-www/issues/1744

Essentially, right now the `{% prettify dart tag=pre+code %}` syntax allows for highlighting certain text with `[!TEXT!]`, but the normal markdown syntax with ``` does not yet. I believe this is handled through some Jekyll plugins written in Ruby in [site-www/_plugins](https://github.com/dart-lang/site-www/tree/main/src/_plugins) and/or [site-shared/_plugins](https://github.com/dart-lang/site-shared/tree/main/src/_plugins).

This functionality is used a lot in pages like [Customizing static analysis options](https://dart.dev/guides/language/analysis-options). Here is an [example](https://github.com/dart-lang/site-www/blob/main/src/_guides/language/analysis-options.md?plain=1#L55).

I haven't had much of a chance to look into it, but probably some sort of replacements need to happen in the Markdown code handling. It sounds like the functionality may already be there, just not fully hooked up.
