### ISSUE TITLE
[PAGE ISSUE]: 'Fetch data dynamically'

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#3852]
### Page URL

https://dart.dev/tutorials/web/fetch-data

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_tutorials/web/fetch-data.md

### Describe the problem

This page urgently needs rewriting to not require `dart:html`. Most all users who come to it will either be writing server-side code without UI, or Flutter code. 

### Expected fix

Use package:http.

This page is better, although it assumes Flutter: https://docs.flutter.dev/cookbook/networking/fetch-data

### Additional context

/cc @kevmoo, for whom this is probably an important page with his cloud work.

**Comment by parlough** [comment]
Sounds like a great idea. Now that `package:http` is supported by DartPad, we can likely create some great cross-platform examples that can help a wider audience. 

I can look into this and other related improvements to the article, thanks!

**Comment by mit-mit** [comment]
Hey @parlough, still working on this?

**Comment by domesticmouse** [comment]
> Yep. Have been mostly out the past few months. Will finalize work on this this week after I fix a necessary DartPad issue first.

Which DartPad issue is blocking you?
