### ISSUE TITLE
New diagnostic message documentation available

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/site-www#3857]
### Page URL

https://dart.dev/tools/diagnostic-messages

### Describe the problem

There is new content for this page in `https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/tool/diagnostics/diagnostics.md` that's ready to be incorporated.

**Comment by parlough** [comment]
These are now published as of https://github.com/dart-lang/site-www/commit/fea6f582025358988e29bf9d09e176cbbfce47c5. Thanks for the update, the new diagnostic documentation looks great!
