### ISSUE TITLE
Link to language newsletters

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#387]
Somewhere on www.dartlang.org we should link (directly or indirectly) to the [language newsletters](https://github.com/dart-lang/sdk/tree/master/docs/newsletter). Better might be to provide a friendlier way to get to the language newsletters than linking to a GitHub directory. (Maybe someone's already doing the latter?) If a handwritten index is impractical, one possibility would be to provide a search of the dart-lang/sdk repo with "newsletter" already filled in, as in [this newsletter search for "arrow"](https://github.com/dart-lang/sdk/search?q=arrow+path%3A%2Fdocs%2Fnewsletter).

/cc @floitschG, @filiph, @kevmoo, @munificent

**Comment by floitschG** [comment]
I can definitely update some index somewhere when I publish the newsletters.

**Comment by kwalrath** [comment]
The (recently added) index is in https://github.com/dart-lang/sdk/blob/master/docs/newsletter/README.md, so I'll link to that.
