### ISSUE TITLE
[PAGE ISSUE]: 'Dart SDK archive'

### ISSUE THREAD

**Issue by StuckInsideJake** [dart-lang/site-www#3879]
### Page URL

https://dart.dev/get-dart/archive/

### Page source

The current Dart SDK version is 2.13.4.

Because map_one_interface depends on json_serializable >=6.0.0 which requires SDK version >=2.14.0 <3.0.0, version solving failed.
pub get failed (1; Because map_one_interface depends on json_serializable >=6.0.0 which requires SDK version >=2.14.0 <3.0.0, version solving failed.)
Process finished with exit code 1

**Comment by StuckInsideJake** [comment]
Android studio does not recognize 2.16 versions

**Comment by parlough** [comment]
Hello @StuckInsideJake, were you able to figure out your issue? 

If it is possible, I recommend updating your Dart SDK (>= 2.14) or Flutter SDK (>= 2.5) to the newest release you can. 

I haven't heard of any particular issues around using these recent releases on Android Studio, but if you have the latest plugin releases and it's not working, consider opening an issue on the [flutter-intellij](https://github.com/flutter/flutter-intellij) repository or for the [Dart plugin for IntelliJ](https://youtrack.jetbrains.com/issues/WEB?q=Subsystem:%20Dart) 

I'm not sure what `map_one_interface` is, but if it's your project and you cannot upgrade your SDK release, you could depend on an older release of `json_serializable` which supports earlier SDK releases. It seems the `5.0.2` release is the last release before they started requiring Dart >= 2.14.

Let me know if you have any further issues. Thanks!
