### ISSUE TITLE
Get Dart Ubuntu No such file or directory

### ISSUE THREAD

**Issue by jeffdahl** [dart-lang/site-www#3883]
### Page URL

https://dart.dev/get-dart

### Describe the problem

When running the following:
`echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list`

I receive:
`bash: deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main: No such file or directory`

### Expected fix

Sounds like the file is missing on the server.

**Comment by parlough** [comment]
I'm going to close this for now as no one else has reported this issue and the supported distros include these tools. Let me know if  you are still experiencing this issue, thanks!
