### ISSUE TITLE
[router] base href regexp doesn't work in IntelliJ multi-module mode

### ISSUE THREAD

**Issue by BorisNaguet** [dart-lang/site-www#389]
Hello,

On that page:
https://webdev.dartlang.org/angular/guide/router/1

There's a script:
```javascript
  // WARNING: DO NOT set the <base href> like this in production!
  // Details: https://webdev.dartlang.org/angular/guide/router
  (function () {
    // App being served out of web folder (like WebStorm does)?
    var match = document.location.pathname.match(/^\/[-\w]+\/web\//);
    var href = match ? match[0] : '/';
    document.write('<base href="' + href + '" />');
  }());
```

It should set base href to `/my_project/web/` when served by IntelliJ/webstorm.

The problem is that, when you have a project with different submodules, the url should be: `/my_project/my_module/web/`.
It's not matched by the regexp because the 'slash' is not matched.
Here is the right regexp:
`var match = document.location.pathname.match(/^\/[\/-\w]+\/web\//);`
with an extra `\/` in the char class

Regards

**Comment by kwalrath** [comment]
This issue was moved to dart-lang/site-webdev#1090
