### ISSUE TITLE
New Dart book

### ISSUE THREAD

**Issue by suragch** [dart-lang/site-www#3890]
### Page URL

https://dart.dev/resources/books

### Describe the problem

There is another Dart book that can be added to this page:

Data Structures & Algorithms in Dart
https://www.raywenderlich.com/books/data-structures-algorithms-in-dart

Full disclosure: I'm one of the authors.

**Comment by parlough** [comment]
@suragch This is really cool. It's nice to see a book not about Dart but about something else (besides Flutter) using Dart. Thanks for working on this and sharing. Definitely a great addition!

I can work on adding this and I hope to have a chance to read it soon :)

**Comment by parlough** [comment]
One question. The raywenderlich site specifies "By Vincent Ngo, Jonathan Sande and Kelvin Lau" but it seems in the book itself, you are specified as the only author. Should the author just be "Jonathan Sande" in the dart.dev listing?

Thanks again!

**Comment by suragch** [comment]
Thanks, @parlough. The book is based on [Data Structures and Algorithms in Swift](https://www.raywenderlich.com/books/data-structures-algorithms-in-swift), which was by Vincent Ngo and Kelvin Lau. I did the Dart version but am heavily indebted to the work of the two Swift authors. Since the main raywenderlich.com page that you'll link to uses all three of our names, you can follow that pattern. But whatever you think is best.
