### ISSUE TITLE
Cannot find source file: hello.def

### ISSUE THREAD

**Issue by igouy** [dart-lang/site-www#3893]
### Page URL

https://dart.dev/guides/libraries/c-interop#building-and-running

### Describe the problem

```
/hello_library$ cmake .
-- The C compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:3 (add_library):
  Cannot find source file:

    hello.def

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:3 (add_library):
  No SOURCES given to target: hello_library

```

### Expected fix

I expect the example to just work when followed:

https://dart.dev/guides/libraries/c-interop#building-and-running

**Comment by parlough** [comment]
Thanks for opening an issue @igouy!

It seems the CMake logic requires the [`hello.def`](https://github.com/dart-lang/samples/blob/master/ffi/hello_world/hello_library/hello.def) file to exist, but we didn't include it this list yet. You can [download it](https://github.com/dart-lang/samples/blob/master/ffi/hello_world/hello_library/hello.def) and include it next to other files in the `hello_library` directory. Let me know if that doesn't fix the issue though.

I'll make sure to add a mention to this file to the list. Thanks again!
