### ISSUE TITLE
Fix FFI example fails to find dependent package `test_utils` 

### ISSUE THREAD

**Issue by igouy** [dart-lang/site-www#3894]
### Page URL

https://dart.dev/guides/libraries/c-interop#building-and-running

### Describe the problem

```
$ dart pub get
Resolving dependencies... 
Because hello_world_ffi depends on test_utils from path which doesn't exist (could
  not find package test_utils at "../test_utils"), version solving failed.
```

### Expected fix

I expect "an example of building the dynamic library and executing the Dart app" to work when followed.

The "hello_world example has the following files" does not mention "../test_utils"

**Comment by parlough** [comment]
Hi @igouy, thanks again for opening an issue.

I'm curious, did you just install the linked files in the instructions? Currently they are meant as more of an example to loosely follow and understand, not necessarily as a template. Therefore for testing purposes, it require files elsewhere in the [samples](https://github.com/dart-lang/samples) repository. 

I'm thinking we can make it clear it, that to test this example, you should start by cloning the [samples](https://github.com/dart-lang/samples) repository and working on it from there. That way no files are missed and its easier than downloading files one by one. Then adding a comment in the `pubspec.yaml` that the extra dependency can be removed if it's their own project.

For your purposes, if you don't want to clone the entire `samples` repository to test it, you can simply remove the extra dependency on `test_utils` at the bottom of the `pubspec.yaml`: https://github.com/dart-lang/samples/blob/master/ffi/hello_world/pubspec.yaml#L18-L19

I'll work on those improvements, thanks again!

**Comment by igouy** [comment]
> I'm curious, did you just install the linked files in the instructions? 

Yes I (not ironically) "literally" followed the instructions.

>  an example to loosely follow

It's hello world! Make it so I can copy and paste stuff into a terminal window and it just works.

**Comment by parlough** [comment]
Thanks for clarifying!

I'll see if we can move everything within the directory to avoid the external directory dependency, making it easier to just copy and paste from the sample you want to use.

**Comment by atsansone** [comment]
@johnpryan : This looks like an error with the sample in the [pubspec.yaml at line 22](https://github.com/dart-lang/samples/blob/main/ffi/hello_world/pubspec.yaml#L22). It points to `../test_utils` which does not exist in the sample. `../test/` does. If that's the case, could you update it? Thanks!

**Comment by johnpryan** [comment]
The [test_utils](https://github.com/dart-lang/samples/tree/main/ffi/test_utils) package is used for testing the sample. There might be a better way to test the sample without causing confusion.
