### ISSUE TITLE
Invalid documention: user-info is not supported in url

### ISSUE THREAD

**Issue by delanym** [dart-lang/site-www#3897]
### Page URL

https://dart.dev/tools/pub/environment-variables#optional-environment-variables

### Describe the problem

See https://github.com/groupe-edf/nexus-repository-dart/issues/6

**Comment by parlough** [comment]
Hey @delanym, thanks for opening an issue. It seems that specifying user info is [not supported](https://github.com/dart-lang/pub/blob/master/lib/src/source/hosted.dart#L64-L66) in the URL. If you need authentication against a third party pub server, it seems [`dart pub token`](https://dart.dev/tools/pub/cmd/pub-token) is the preferred solution.

@jonasfj Could you provide some extra context here? I don't know much about third party pub servers and it seems you disallowed user-info in https://github.com/dart-lang/pub/pull/3030. Right now it seems our example on the page uses user-info, (`http://user:password@177.0.0.1:9999`), should we use something else?

**Comment by delanym** [comment]
It looks possible to use a [token](https://help.sonatype.com/repomanager3/nexus-repository-administration/user-authentication/security-setup-with-user-tokens) with Nexus Pro, but not Nexus OSS.

**Comment by jonasfj** [comment]
See my reply in https://github.com/dart-lang/site-www/pull/3901.

In short: Surprised anyone did this. Using `dart pub token` is much better.
