### ISSUE TITLE
Write Command-Line Apps tutorial does not work on Windows, can't find packages

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#39]
_From @gazialankus on June 1, 2016 12:44_

This tutorial: https://www.dartlang.org/docs/tutorials/cmdline/

Won't work on Windows: 

```
C:\Development\Dartish\tmp>dir
 Volume in drive C is HDD
 Volume Serial Number is DC07-D177

 Directory of C:\Development\Dartish\tmp

06/01/2016  03:28 PM    <DIR>          .
06/01/2016  03:28 PM    <DIR>          ..
06/01/2016  03:33 PM             2,063 dcat.dart
               1 File(s)          2,063 bytes
               2 Dir(s)  74,771,554,304 bytes free

C:\Development\Dartish\tmp>dart dcat.dart -n quotes.txt
Unhandled exception:
Could not import "package:args/args.dart" from "file:///C:/Development/Dartish/tmp/dcat.dart": Could not resolve a package location for base at file:///C:/Development/Dartish/tmp/dcat.dart
#0      _asyncLoadErrorCallback (dart:_builtin:162)
#1      _asyncLoadError (dart:_builtin:584)
#2      _loadPackage (dart:_builtin:625)
#3      _loadPackage.<anonymous closure> (dart:_builtin:641)
#4      _handlePackagesReply (dart:_builtin:482)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

C:\Development\Dartish\tmp>
```

I also started a stackoverflow question about it: http://stackoverflow.com/questions/37568953/dart-command-line-app-on-windows-cant-import-packages

_Copied from original issue: dart-lang/www.dartlang.org#1579_

**Comment by Sfshaza** [comment]
_From @zoechi on June 1, 2016 12:54_

A simple self-contained command line script might work without `pubspec.yaml` and without conforming to the pub package layout conventions but when packages (like `args` in the tutorial) AFAIK this can't work anymore. The tutorial should explain that or at least point to pages that do.

**Comment by Omiod** [comment]
Issue closed?
It is still not working in Windows and there are no notes regarding this issue.
Too bad today I decided to learn Dart :(

**Comment by gazialankus** [comment]
@Omiod the other issue is closed since it was moved here. This one remains open.

**Comment by Sfshaza** [comment]
@Omimod, as Gazihan noted, we now have a new repo for our new website. That
issue is still valid and was moved to the new repo.

**Comment by Sfshaza** [comment]
For folks who develop on Windows, is this still an issue?

**Comment by kwalrath** [comment]
Closing, since there's been no indication that this is still an issue.
