### ISSUE TITLE
[2.19] `Isolate.run()` docs

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#3904]
https://dart-review.googlesource.com/c/sdk/+/217008

### Summary

"Runs [computation] in a new isolate and returns the result." - [API docs](https://github.com/dart-lang/sdk/commit/a5f25ee3ba5a7f2e22b7698590727b32c37204f9#diff-c9ae8fb1ff4a1b2edd5b4883ebb21d80f818511d5f90ff7e79993f2cb9f909fcR153)

Currently, you have to use sendport and receiveport to get a return from an isolate. Isolate.run() doesn't eliminate the need for send-and-receive ports (there are still cases where one might want to fine tune the configuration of using send-and-receive ports for some reason, and they still can), it just wraps their usage so users don't have to handroll that implementation themselves. Now you can just call isolate.run() and get a return without having to write anything else

### Evaluation

- Potential updates needed on [Concurrency in Dart](https://dart.dev/guides/language/concurrency)
  - The use of sendport/receiveport shouldn't be mentioned in the default examples. 
  - Use isolate.run by default, mention that you could use send/receive if for some reason you want to configure that more closely
    - This page might not be the place to go into that much detail
- Potential new content needed; needs more info to determine
  - I don't think there is a need for new content, just updating the existing mentions of isolate that go in detail enough to talk about sharing data between isolates.
- Not sure about the significance of the [flutter samples repo](https://github.com/flutter/samples/tree/main/isolate_example), but it might need updating or adding to  
  - Use of send and receive ports is the default
  - My suggestion: any use of send and receive ports needs to be changed to isolate.run
  - Then, maybe, create a new example that shows how to use send and receive if you really want to
  - Samples being updated [here](https://github.com/flutter/samples/issues/1487)

**Comment by parlough** [comment]
This has been reverted in https://github.com/dart-lang/sdk/commit/d063ac32335881e34f324746b8e155cc93bc57d8, so changing the milestone.

**Comment by MaryaBelanger** [comment]
This is is in the [change log](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#dartisolate) for 2.19 now, and seems to be [implemented](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#dartisolate) at this point (I could be misreading that though), so I'm going to treat it as such and convert this into an evaluation issue.

**Comment by MaryaBelanger** [comment]
Tracking Flutter impact (will determine if it's included in 2.19(?))

https://github.com/dart-lang/sdk/issues/48566

**Comment by MaryaBelanger** [comment]
Note: [this example](https://github.com/dart-lang/samples/blob/master/isolates/bin/long_running_isolate.dart) shouldn't change because there is no method to accomplish this with `run()` yet

**Comment by MaryaBelanger** [comment]
Fixing PRs merged into [v2.19](https://github.com/dart-lang/site-www/tree/v2.19)
