### ISSUE TITLE
Document beta support for RISC-V

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#3906]
https://github.com/dart-lang/sdk/issues/38587

**Comment by parlough** [comment]
Is this ready to be documented as a properly supported architecture? It seems some features are not fully supported (FFI) and it doesn't seem the release team is releasing Linux builds for RISC-V yet.

**Comment by kevmoo** [comment]
@mit-mit @rmacnak-google – we're not ready to document RISC-V yet – correct?

**Comment by rmacnak-google** [comment]
The bots only started uploading RV64 SDKs yesterday. I'd put it off until the next release so things have time to settle.

**Comment by parlough** [comment]
I will keep this issue as tracking any necessary documentation changes, and have separated out [archive page](https://dart.dev/get-dart/archive) support for handling `riscv64` builds: https://github.com/dart-lang/site-www/issues/3958

**Comment by mit-mit** [comment]
I would like to update dart.dev with information about this for the 2.17 release, but tagging it as "experimental support" until we have a bit more customer validation.

Relevant pages are:
https://dart.dev/get-dart#system-requirements
https://dart.dev/get-dart/archive

**Comment by parlough** [comment]
I've landed documentation and archive support for RISC-V in https://github.com/dart-lang/site-www/commit/81ffe294b86e3f1003d8cf69674eaa2e0ecb59cc

I'll keep this issue open to track bringing that support to the beta and stable branches when those land.

**Comment by parlough** [comment]
@mit-mit Do you want the beta riscv builds to show up yet or should we only surface the dev builds for now?

**Comment by mit-mit** [comment]
Showing beta RISC-V would be fine! Probably don't want stable yet.
