### ISSUE TITLE
documentation for FFI plugins

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#3907]
https://github.com/flutter/flutter/pull/96225

**Comment by parlough** [comment]
Do you mean for this to be tracked in [flutter/website](https://github.com/flutter/website)? I'm not sure of any actionable work here on the Dart side.

**Comment by parlough** [comment]
@johnpryan Do you have more context here?

**Comment by iapicca** [comment]
https://github.com/flutter/website/issues/7073
