### ISSUE TITLE
documentation for deprecated .packages file

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#3909]
https://github.com/dart-lang/sdk/issues/48272

**Comment by mit-mit** [comment]
The work here is to search for any documentation that might mention `.packages, check that those same places already mention `package_config.json`, and if then to simply remove the mentioning of `.packages`

**Comment by kevmoo** [comment]
@mit-mit – do we want to (at a minimum) keep *some* references around – maybe at least one saying "hey this is old. If you're on 2.17+ delete it"

**Comment by parlough** [comment]
If that is desired, perhaps a note to remove it on the [Package layout](https://dart.dev/tools/pub/package-layout) page where we currently have the note about how it was replaced.

**Comment by kevmoo** [comment]
Or the 'what to ignore' page? Basically say if the package in question depends on Dart 2.17 (or greater) then you no longer need to ignore it.

**Comment by mit-mit** [comment]
@parlough I think this can safely be merged now?
