### ISSUE TITLE
https://news.dartlang.org/ is broken

### ISSUE THREAD

**Issue by telenieko** [dart-lang/site-www#3917]
### Page URL

https://news.dartlang.org/

### Describe the problem

There are several search results that point to <https://news.dartlang.org/> but that page is out of date and very much broken. There are broken images that screw up the whole layout and take most of the top part which means that when you go in you see nothing:

![image](https://user-images.githubusercontent.com/10505/158484955-285428f5-c577-4dc4-ae12-c352df12dfa4.png)

### Expected fix

- When someone reaches the root page (`/`) redirect to the current blog, <https://medium.com/dartlang>
- Remove all broken images, leave the site very lean so that if someone reaches an article directly (from a search engine for example) it can be read

**Comment by parlough** [comment]
Thanks for opening an issue @telenieko. 

I agree the broken images (especially the one on the top of each article) make the site and articles a bit hard to navigate, so it would be nice to see those fixed (or removed) for reference and posterity purposes. The root page redirect could be nice to see as well.

I'm not sure who has access though and the work likely wouldn't have any priority due to the blog being unsupported, outdated, and the content technically still being visible on the website (after navigating around the broken images). 

If you need to reference something, it's likely more reliable to rely on the [Wayback machine](https://web.archive.org/) long term as the content is preserved in its original form and generally should remain that way.

\cc @kevmoo Since I don't know much about the old blog.

**Comment by kevmoo** [comment]
Ugh. Hrm. Not sure what to do about this.

@sfshaza2 – any context here? @mit-mit ?

**Comment by domesticmouse** [comment]
Worst case we can redirect the DNS entry to a web host that 301 redirects the user appropriately.

**Comment by mit-mit** [comment]
I added this to the agenda for next weeks Dart DevRel meeting

**Comment by sfshaza2** [comment]
@kevmoo, I just scrolled through several pages of this blog and I don't agree that most of it has any value. Most of it seems pretty value-less to me. (Do we need info on IntelliJ 2017? or news that Dart is now strongly typed? or info on Dart Conf from years ago?) I remember that the content lives on blogger and @mit-mit has access to that. (I might still have access, too.) 

I would suggest that we back up an archive of the blog content and take the blog down. If we ever want to access the archive, at least the content is available internally. I also like @domesticmouse's suggestion of redirecting the DNS entry to the Medium Dart publication.

We can store the archive on our team's shared Google Drive.

I am wondering what happened to the images, though. Shouldn't those be stored with the content?

**Comment by parlough** [comment]
Sounds like a good plan to me, especially with the redirect. If anyone wants to refer to the contents externally, [the Wayback Machine](https://web.archive.org/web/*/http://news.dartlang.org) for the site should be sufficient.

**Comment by sfshaza2** [comment]
Exactly, @parlough. Kathy felt that the wayback machine should be sufficient and I tend to agree. If we save an archive of the blog, we can always dive in to retrieve any tidbits that still might be useful.

**Comment by telenieko** [comment]
It may be worth noting that search engines do not appear to index the [Wayback Machine](https://web.archive.org/), at least not fully as you can see by [asking google for site:web.archive.org + dart](https://www.google.com/search?q=site%3Aweb.archive.org+dart).

This would mean that if <https://news.dartlang.org/> is simply taken down and redirected to <https://medium.com/dartlang> Dart's "history" from 2011 to Sept. 2019 would basically be gone (unless you know about the old site and go fishing on the Wayback Machine). Search would be completely gone as server based search does not work on the Wayback machine.

I don't know how important that history is, surely someone writing a book would want to refer to it, nonetheless 8 years of posts may be worth preserving in a discoverable way.

A quick low effort fix would be to do minimal layout changes to the current site:

1. Remove the broken banner
2. Add a nice big notice at the top like "This site holds Dart's blog until 2019; for all the latest please go to <https://medium.com/dartlang> (because the current notice on the sidebar is hard to notice, specially below the broken banner).

A more permanent, but harder, solution would be to migrate the Blogger contents to medium.com and have it all there. And may need some review regarding broken images on some posts

**Comment by telenieko** [comment]
> @parlough:
> If you need to reference something, it's likely more reliable to rely on the [Wayback machine](https://web.archive.org/) long term as the content is preserved in its original form and generally should remain that way.
> \cc @kevmoo Since I don't know much about the old blog.

It may be worth noting that search engines do not appear to index the [Wayback Machine](https://web.archive.org/), at least not fully as you can see by [asking google for site:web.archive.org + dart](https://www.google.com/search?q=site%3Aweb.archive.org+dart).

This would mean that if <https://news.dartlang.org/> is simply taken down and redirected to <https://medium.com/dartlang> Dart's "history" from 2011 to Sept. 2019 would basically be gone (unless you know about the old site and go fishing on the Wayback Machine). Search would be completely gone as server based search does not work on the Wayback machine.

I don't know how important that history is, surely someone writing a book would want to refer to it, nonetheless 8 years of posts may be worth preserving in a discoverable way. @parlough  above said «There are a lot of great articles on the site.».

A quick low effort fix would be to do minimal layout changes to the current site:

1. Remove the broken banner
2. Add a nice big notice at the top like "This site holds Dart's blog until 2019; for all the latest please go to <https://medium.com/dartlang> (because the current notice on the sidebar is hard to notice, specially below the broken banner).
3. Redirect the root path to <https://medium.com/dartlang>, so you only stay on the old site if you landed on a specific article

A more permanent, but harder, solution would be to migrate the Blogger contents to medium.com and have it all there. And may need some review regarding broken images on some posts

**Comment by sfshaza2** [comment]
Migrating the old content to Medium is a non-starter for me. It's absolutely not worth the effort unless we have specific articles of interest we want to preserve publicly. @mit-mit, would you be willing to make the more minor changes on the old blog as recommended by @telenieko? I could definitely live with that solution. (I still think we should back up an archive of the blog and save it internally.)

**Comment by cnmade** [comment]
I can confirm the same issue here .

**Comment by parlough** [comment]
Thanks @mit-mit, that's a much better experience for referring to this older content.
