### ISSUE TITLE
Deploy is failing due to authentication issue

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3929]
### Describe the problem

It seems the Firebase JWT (token) has expired or no longer has the appropriate permissions to deploy, causing the deploy to fail:

You can see an example of the failed deploy in GitHub Actions here: https://github.com/dart-lang/site-www/runs/5619923913?check_suite_focus=true

```console
[2022-03-20T22:19:08.593Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2022-03-20T22:19:08.[67](https://github.com/dart-lang/site-www/runs/5619923913?check_suite_focus=true#step:9:67)9Z] Error: invalid_grant: Invalid JWT Signature.
 ```

### Expected fix

Generate a new token and replace the old one in GitHub secrets.

If the problem is it did expire, could we expand the validity of the token to avoid deployment issues in the future?

### Additional context

Our deployment logic can be found https://github.com/dart-lang/site-www/blob/main/.github/workflows/build.yml#L66-L71

\cc @mit-mit @sfshaza2 @RedBrogdon

**Comment by parlough** [comment]
Anyone able to help with this? I don’t have the ability to deploy locally so we’re missing some updates like the recent diagnostic messages.

Thanks!

**Comment by sfshaza2** [comment]
I just pinged Khanh and others about this.

**Comment by sfshaza2** [comment]
I don't have permission to deploy it manually, either. @khanhnwin is close to getting the issue fixed. (It has to do with a firebase token.)

**Comment by bwilkerson** [comment]
I don't know whether this means that this issue has now been fixed, but in case it's useful information the new diagnostics appear to be live.

**Comment by sfshaza2** [comment]
Yes, @mit-mit was able to fix the issue. Thanks, @khanh and all!

**Comment by parlough** [comment]
Looks like the deploy and the deploy previews are working. Thanks everyone for your help :)
