### ISSUE TITLE
Cleanup ideas for _guides/libraries/private-files.md

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#393]
Remove references to

- .project - Dart editor days
- .buildlog - Dart editor days

Mention .gitignore

 - I'm pretty sure pub uses what git ignores
 - https://help.github.com/articles/ignoring-files/
 - https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#_ignoring

Mention `~/.gitignore_global`

```
.DS_Store
.idea
/*.iml
```

**Comment by kwalrath** [comment]
Can you explain what you meant by the following?

> ```
> .DS_Store
> .idea
> /*.iml
> ```

We have a similar list in the doc:

```
*.iml         // IntelliJ
*.ipr         // IntelliJ
*.iws         // IntelliJ
.idea/        // IntelliJ
.DS_Store     // Mac
```

Did you want to us to modify it (removing ipr & iws, e.g., and maybe altering the others)?

**Comment by kevmoo** [comment]
Right. Sorry. I mean in the doc highlight that these should be in a global ignore...
