### ISSUE TITLE
Introduction - would like to contribute

### ISSUE THREAD

**Issue by Nirsu** [dart-lang/site-www#3933]
I'm currently a student, working for a company using a lot Flutter and JS (ReactJS, Nodejs).
I'm new to open source contribution, so I'd like to participate in my first pr. I saw that there was only one issue with the beginner label, but it's already assigned, I'd like to know if there was another issue I could contribute to :)

Thanks

**Comment by parlough** [comment]
Hi @Nirsu, it's great to hear from you and to see your excitement about participating, thanks for reaching out :)

For now, my recommendation is to look at issues with the [Help wanted label](https://github.com/dart-lang/site-www/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) which is sort of similar to `beginner` and find one you're interesting in working on. It's okay to only work on a small piece at a time. You could also look through any other issue to see if there are any you'd like to work on. I can go through soon and look for some more potential beginner issues. 

If you find one you want to work on, let me know if you have any questions about contributing, the issue, our setup, Dart, etc.

You can learn more about contributing in our [Contributing.md](https://github.com/dart-lang/site-www/blob/main/CONTRIBUTING.md). If your change is large and you need to setup a dev environment, you can follow the in the instructions in the [README](https://github.com/dart-lang/site-www#getting-started).

Thanks again!

**Comment by parlough** [comment]
I'm going to close this for now, but always feel free to let us know if you need help contributing. Thanks again!
