### ISSUE TITLE
New documentation for diagnostics

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/site-www#3945]
### Page URL

https://dart.dev/tools/diagnostic-messages

### Describe the problem

The documentation for diagnostics has been updated to include several new diagnostics.

### Expected fix

These need to be pulled from the `analyzer` package.

**Comment by bwilkerson** [comment]
I'm not seeing these when I open the page. Is there an expected delay from the time the PR lands until the time they show up on the web site?

**Comment by parlough** [comment]
@bwilkerson Sorry, the deploy is currently broken and I don’t have permission to deploy manually. 

https://github.com/dart-lang/site-www/issues/3929

@sfshaza2 has raised the issue with the devrel team, hoping we can get it fixed soon.

**Comment by bwilkerson** [comment]
No problem. Thanks for the issue reference.

**Comment by sfshaza2** [comment]
Yes, @khanhnwin is working on it. We are close to having it fixed, I think.

**Comment by khanhnwin** [comment]
For record keeping, this was fixed. Thanks for your patience, everyone!
