### ISSUE TITLE
Consider splitting 'dart compile' subcommands into their own pages

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#3977]
### Page URL

https://dart.dev/tools/dart-compile.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/dart-compile.md

### Describe the problem

As it stands now, we don't document the complete functionality of each command and the page is getting rather long. As we add more documentation about the various commands, especially with `dart compile js` replacing `dart2js`, the page will become a bit large to handle and have lots of documentation for different commands when the user may only care about one of them. If we want to add further subheadings, linking may become a larger issue as well.

### Expected fix

We should consider splitting the subcommands into their own pages, similar to the pub subcommands. This will make future documentation easier and more organized, especially with the desire to better document `dart compile js`.

**Comment by parlough** [comment]
@sfshaza2 @mit-mit Does splitting these up seem fine to you? Another option would be to only have a separate page for the `js` subcommand for now, but the consistency would be nice.

**Comment by domesticmouse** [comment]
I'm supportive of splitting and documenting sub commands on different pages

**Comment by mit-mit** [comment]
I'm fairly indifferent (we have much longer pages on the site even of we, say, expand this one to 2x it's current length)

**Comment by parlough** [comment]
After experimenting with this, I found for now it's probably not necessary, as a lot of the current information contained in the `dart2js` page would be better located somewhere else as a lot of it is shared behavior.
