### ISSUE TITLE
Reword homepage description of libraries and tools

### ISSUE THREAD

**Issue by hchiam** [dart-lang/site-www#398]
I believe 

> Dart’s **have** been powering very large apps for years now. 
(emphasis mine)

should be

> Dart’s been powering very large apps for years now.

in the core goals description: https://www.dartlang.org/

**Comment by kwalrath** [comment]
Oh, that's embarrassing. Thanks very much for the report!

**Comment by kwalrath** [comment]
Actually, if you insert the elliptical "core libraries and tools" it does make grammatical sense, but it's too easy to misread. I'll leave this open as a reminder to reword it.

**Comment by kwalrath** [comment]
@wmleler, @filiph: If you have good ideas for the second sentence of the description under "Provide a solid foundation of libraries and tools" on https://www.dartlang.org, please let me know (or open a PR).

**Comment by filiph** [comment]
How about this:

> A programming language is nothing without its core libraries and tools. We call it "batteries included". Dart's batteries has been powering very large apps for years now.

My problem with the current fix ("Dart has been powering very large apps for years now.") is that  it has nothing to do with the topic of that section (tooling).

**Comment by kwalrath** [comment]
> My problem with the current fix ("Dart has been powering very large apps for years now.") is that it has nothing to do with the topic of that section (tooling).

Yep, I realized that (after the initial shock of thinking we'd had a typo for a year :) ).

**Comment by wmleler** [comment]
+1 for Filip's solution.

**Comment by kwalrath** [comment]
I'm mostly offline for the next 2 days, but if anyone wants to do the commit, here's my tweaked version:

A programming language is nothing without its core libraries and tools. We call it _batteries included._ Dart's batteries have been powering very large apps for years now.

If we use quotation marks, it should be with the period inside ([unfortunately](https://developers.google.com/style/quotation-marks)): "batteries included."

**Comment by wmleler** [comment]
I am on something of a personal crusade to get the punctuation inside the
quotes rule changed. It all started years ago, when the editor on my first
book insisted that the punctuation had to be inside, even when it put a
period inside what we were telling the user to type on their keyboard.
Stupid. My new rule is that if the thing in quotes is not a complete
sentence, then there is no need to move any punctuation inside the trailing
quote. It also better handles cases like when the thing inside quotes is a
question, but what's outside is not (and vice-versa).

I've been using the new rule on my blog. It has been going for 9 years and
nobody has complained yet.

**Comment by kwalrath** [comment]
I completely agree, Wm, and in my personal writing I follow that rule. But I also believe that we should follow the style guide whenever possible. If you'd like to change the style guide, I can connect you with the powers that be.

(That said, I usually end up writing around the problem.)

**Comment by filiph** [comment]
Alright, nerds, please review https://github.com/dart-lang/site-www/pull/400 :)

**Comment by hchiam** [comment]
@filiph https://github.com/dart-lang/site-www/issues/398#issuecomment-337286993 

Sorry, I must have misread "```Dart's```" as short for "```Dart is```" or "```Dart has```". 
I see now that the original "```Dart's```" was really just short for "```Dart's core libraries and tools```", which I think was the meaning, grammar/brevity/readability aside. 

I.E.:

> A programming language is nothing without its core libraries and tools. Dart’s **core libraries and tools** have been powering very large apps for years now. 

(wordy, plus @kwalrath's https://github.com/dart-lang/site-www/issues/398#issuecomment-337262703)

**But instead of that, how about this:**

> A programming language is nothing without its core libraries and tools. **The ones used in** Dart have been powering very large apps for years now.

(shorter while maintaining plural "have")

**Comment by filiph** [comment]
Hi @hchiam, thanks! The wording was definitely clunky. What do you think about #400 (that should fix the issue). I'll add you as a reviewer for that.

**Comment by hchiam** [comment]
@filiph No worries, and thanks for following up! I re-read this sentence in the context of the tooling goal, and I think your wording is great.
