### ISSUE TITLE
Spell Checking method is deprescated

### ISSUE THREAD

**Issue by VanshajPoonia** [dart-lang/site-www#3981]
### Describe the problem

When I ran make setup, I received the warning: Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated.

### Expected fix

Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

**Comment by parlough** [comment]
Thanks for opening an issue. This was a temporary bug in a previous bundler release. Next time we update our Ruby dependencies, I believe this should be fixed.

Until then, the the build should still work. Let me know if you have any other issues. Thanks again!
