### ISSUE TITLE
Getting Started guide flowchat text is missing letters?

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/site-www#4]
On this page:
https://www.dartlang.org/guides/get-started

<img width="399" alt="dlorg-bug" src="https://cloud.githubusercontent.com/assets/1148886/16842226/0c4ca7d4-49b3-11e6-87b2-07ec5edbb93e.png">

The "So you want to" the you seems to be missing characters

Mac OS X 10.11.5
Browser: Brave 0.11.0

(Possibly a browser bug?)

**Comment by Sfshaza** [comment]
Can't duplicate this on Chrome, Safari, or Firefox (all on Mac).

This does sound like a browser bug with svg files on Brave. I'm closing. Re-open if you have further info that points to a bug on our page. Thanks!
