### ISSUE TITLE
Warn against creating circular package dependencies?

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#40]
_From @kwalrath on April 19, 2016 16:15_

See https://github.com/angular/angular.io/issues/1122. @jakemac53 says that circular library dependencies (within a package) can be hard to avoid, but that it's easier (and probably a good thing, in general) to avoid circular package dependencies.

cc @munificent 

_Copied from original issue: dart-lang/www.dartlang.org#1567_

**Comment by Sfshaza** [comment]
_From @munificent on April 21, 2016 22:51_

cc @nex3

**Comment by munificent** [comment]
Since barback is going away, it doesn't look like this is something we need to worry about.
