### ISSUE TITLE
Is it "initializing parameters" or "initializing formals"?

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/site-www#4011]
### Page URL

https://dart.dev/guides/language/language-tour#initializing-parameters

### Describe the problem

The [dart language tour](https://dart.dev/guides/language/language-tour#initializing-parameters) describes a feature it calls "initializing parameters", however both [effective dart](https://dart.dev/guides/language/effective-dart/usage#do-use-initializing-formals-when-possible) and the [dart lint tool documentation](https://dart-lang.github.io/linter/lints/prefer_initializing_formals.html) refer to the same feature as "initializing formals".

### Expected fix

Use a consistent name for this language feature.

**Comment by parlough** [comment]
I struggled deciding between these terms but chose simply parameters since I thought it would be the more familiar term for those reading the language tour.

I suppose it is better to be consistent with formals though and better explain the terminology (either here or in another section). Thanks for your thoughts!

**Comment by mmcdon20** [comment]
@parlough I do agree that the term "parameters" is far more familiar to people than "formals" is, but "initializing formals" seems to be used everywhere except for the language tour. I did notice that the dart language spec actually uses "initializing formal parameter" a few times, but mostly uses the shortened "initializing formal". I think if you used "initializing formal parameter" in the language tour it might be more approachable to dart newcomers but also not as confusing when you see the feature referred to as "initializing formals" in other dart documentation.

**Comment by parlough** [comment]
Yep, I think "Initializing formal parameters" is a good choice since it will be more discoverable when users search or use the TOC.
