### ISSUE TITLE
Tools entry in sidenav should be bold when Tools subpages are being visited

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#403]
See https://github.com/dart-lang/site-www/pull/402#discussion_r145819409

**Comment by kwalrath** [comment]
And (for the record) for the Install subpages. Possibly true even for sections that don't have breadcrumbs, though I'm less certain of that.

**Comment by kwalrath** [comment]
Seems to already be implemented. All the Install subpages are under Tools, so that's what's bold when you're on them.
