### ISSUE TITLE
Suggestion: 'Learning Dart as a JavaScript developer' should mention `for` loops

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/site-www#4038]
### Page URL

https://dart.dev/guides/language/coming-from/js-to-dart

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/coming-from/js-to-dart.md

### Describe the problem

I suspect that one of the reasons why I see `Iterable.forEach` used so much in Dart questions on StackOverflow is because many people have been institutionalized by JavaScript where `for ... in` unintuitively iterates over an object's properties.  JavaScript developers who want to avoid potential indexing/bounds errors therefore are recommended to use `Array.forEach` instead.

Dart doesn't have that problem, so `for ... in` should be the preferred way to loop.  Maybe this would be worth mentioning?

**Comment by parlough** [comment]
I feel this is a large emission even not considering the extra considerations of coming from JavaScript. Thanks for pointing that out!
