### ISSUE TITLE
cascade notation works on "instance methods" rather than "function calls"

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/site-www#4064]
### Page URL

https://dart.dev/guides/language/language-tour#cascade-notation

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/language-tour.md

### Describe the problem

This is just a small nitpick from the dart language tour, but the current explanation for cascade notation says:

> Cascades (.., ?..) allow you to make a sequence of operations on the same object. In addition to function calls, you can also access fields on that same object.

The explanation says that cascade works on "function calls", but it does not work on static functions, top-level functions, or anonymous functions. I think it would be clearer if it said "instance methods" instead of "function calls".

### Expected fix

Replace "function calls" with "instance methods".

**Comment by parlough** [comment]
That makes sense, thanks for catching this @mmcdon20!

I think we still need to include "calls" somehow though to indicate that invoking those methods work, not just accessing the tear-off of the method.

**Comment by mmcdon20** [comment]
@parlough technically there is nothing stopping you from using a cascade with a tear-off, but it effectively does nothing. So, I would be happy with "instance method calls" or similar.

**Comment by parlough** [comment]
Yeah they work, but I want to make sure the reader realizes it works for calling them too, so "instance methods calls" seems great to me :)

Taking a look, I realized none of the functional examples in the section actually call a traditional method directly on the object, only access or modify its properties. Perhaps we should add that.
