### ISSUE TITLE
Web apps: Fetch data dynamically

### ISSUE THREAD

**Issue by klr981** [dart-lang/site-www#4077]
### Page URL

https://dart.dev/tutorials/web/fetch-data

### Describe the problem

Tutorials do not work outside of DartPad even when following Get started: Web apps

**Comment by parlough** [comment]
Hey @klr981, thanks for opening an issue. Could you provide some more context on what isn't working? Is there an error or other problem running?

**Comment by parlough** [comment]
I'm going to close this as this page will soon be reworked and any current problems will be covered by the work suggested in https://github.com/dart-lang/site-www/issues/3852. If you have any more desires for the new page, let us know there. Thanks!
