### ISSUE TITLE
[PAGE ISSUE]: 'Asynchronous programming: futures, async, await'

### ISSUE THREAD

**Issue by magickibbles** [dart-lang/site-www#4113]
### Page URL

https://dart.dev/codelabs/async-await.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/codelabs/async-await.md

### Describe the problem

The test solution for [practice using async and await](https://dart.dev/codelabs/async-await#exercise-practice-using-async-and-await) doesn't work because of null-safety

### Expected fix

please update this so it functions

**Comment by parlough** [comment]
Hi @magickibbles, thanks for opening an issue.

Could you provide some more information on the issue you're facing? Are there any specific errors? The tests and solution provided for this exercise seemed to work for me.

Thanks again :)

**Comment by Tohusk** [comment]
I'm also getting this issue on firefox,
![Screenshot 2022-07-11 at 10-51-37 Asynchronous programming futures async await](https://user-images.githubusercontent.com/33451949/178169654-c2992586-57c8-4597-9b36-1b4eb7c04b68.png)
same issue with the two exercises below:
![Screenshot 2022-07-11 at 10-52-11 Asynchronous programming futures async await](https://user-images.githubusercontent.com/33451949/178169687-b1bb624b-26e9-4c4b-bdde-ed71c0f0dbe9.png)
![Screenshot 2022-07-11 at 10-52-24 Asynchronous programming futures async await](https://user-images.githubusercontent.com/33451949/178169697-62435e74-e6cd-4c25-91f9-83350d084a64.png)

**Comment by parlough** [comment]
Thanks for catching this @Tohusk, fixing it now :)

**Comment by magickibbles** [comment]
> Hi @magickibbles, thanks for opening an issue.
> 
> Could you provide some more information on the issue you're facing? Are there any specific errors? The tests and solution provided for this exercise seemed to work for me.
> 
> Thanks again :)

honestly forgot why I submitted this. sorry. ty tho :^)
