### ISSUE TITLE
There're no guidelines on the ordering of class members

### ISSUE THREAD

**Issue by jolleekin** [dart-lang/site-www#412]
To my knowledge, there're currently no guidelines on how class members should be ordered. Below are five factors that can affect the ordering of class members
1. Privacy (private/public)
2. static/instance
3. Type (field/getter/setter/method/operator/constructor)
4. Name
    `a` should be before `b`
5. Relationship among members
    Should `int _x` be placed next to `int get x => _x`?

**Comment by kwalrath** [comment]
@munificent do we have any recommendations/conventions for this? Should we?

**Comment by munificent** [comment]
No, we don't. Personally, I don't think we should.

When I was at EA, I wrote the C# style guide we used and it did specify a member order. It was fiendishly complex once you took into account all of the various flavors of members: public/private, getter/setter/field/method/constructor, static/nonstatic, factory/generative/const, override/overridable, etc.

In return for all of that complexity, it didn't seem to make the code much easier to read.

**Comment by filiph** [comment]
FWIW, I think the IntelliJ "Sort" functionality sorts Dart classes in a sane, though simple way (I think it's statics first, then member fields, then constructors / factories, then methods -- everything else is just alphabetical).

I thought it's part of `dartfmt` (like a separate mode) but I was mistaken.

**Comment by kwalrath** [comment]
OK, thanks for the comments (@munificent & @filiph) and for filing the issue (@jolleekin). I'm going to close this, since we have no plans to provide guidelines for the order.
