### ISSUE TITLE
[PAGE ISSUE]: 'A tour of the core libraries'

### ISSUE THREAD

**Issue by TheJim92** [dart-lang/site-www#4129]
### Page URL

https://dart.dev/guides/libraries/library-tour

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/libraries/library-tour.md

### Describe the problem

The following link in the section about Async and Future objects brings to a 404 not found: https://github.com/dart-lang/sdk/blob/main/docs/newsletter/20170915.md#synchronous-async-start

**Comment by parlough** [comment]
Thanks for catching this. The old newsletter entries were recently moved to the [language repository](https://github.com/dart-lang/language/tree/master/archive/newsletter) and I forgot to update our references to them. 

I've updated them in https://github.com/dart-lang/site-www/pull/4130

Thanks again!
