### ISSUE TITLE
[PAGE ISSUE]: 'Migrating to null safety'

### ISSUE THREAD

**Issue by bagintz** [dart-lang/site-www#4139]
### Page URL

https://dart.dev/null-safety/migration-guide.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/null-safety/migration-guide.md

### Describe the problem

`dart pub outdated --mode=null-safety`

shouldn't  this be

`flutter pub outdated --mode=null-safety`

???  At least the dart one didn't work for me

### Expected fix

change to flutter

**Comment by parlough** [comment]
Hi @bagintz, thanks for opening an issue.

This is the website for the Dart programming language, so not every user has the `flutter` command installed, therefore we showcase the `dart` version of the commands, which the `flutter` tool just redirects to for pub related commands.

As of Flutter 1.19, Flutter's `bin` folder also has the `dart` command line tool though, so if you add that folder to your path, both the `dart` and `flutter` command line tools should work. You can learn about setting your path to Flutter's bin on the Flutter website: [Windows instructions](https://docs.flutter.dev/get-started/install/windows#update-your-path), [macOS instructions](https://docs.flutter.dev/get-started/install/macos#update-your-path), [linux instructions](https://docs.flutter.dev/get-started/install/linux#update-your-path). If you need the `dart` tool, following those instructions should work, or you can have a separate Dart install as well. 

Let us know if you have any issues though, thanks again!
