### ISSUE TITLE
Update 'Who uses Dart' page

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#4144]
### Page URL

https://dart.dev/community/who-uses-dart.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/community/who-uses-dart.md

### Describe the problem

This page is in urgent need of an update, as highlighted here:
https://news.ycombinator.com/item?id=32078346

### Expected fix

Use content as in https://news.ycombinator.com/item?id=32104816 to update it! 

### Additional context

@mit-mit for visibility

**Comment by MikiPAUL** [comment]
@MaryaBelanger @timsneath @parlough , I would love to take on this task! I am confident that I can make a contribution here. Would you mind assigning this issue to me? Thank you!

**Comment by MaryaBelanger** [comment]
That sounds great @MikiPAUL, thanks! Looking forward to the PR
