### ISSUE TITLE
Move dart-lang/dart-up-and-running-book to dart-archive

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#415]
Move [dart-lang/dart-up-and-running-book](https://github.com/dart-lang/dart-up-and-running-book) to [dart-archive](https://github.com/dart-archive) now that the source code lives in this repo under `examples`.

(I'm opening an issue here since I can't open one over the up-and-running repo. :)

cc @kevmoo

**Comment by kevmoo** [comment]
Done! https://github.com/dart-archive/dart-up-and-running-book
