### ISSUE TITLE
[PAGE ISSUE]: 'A tour of the Dart language'

### ISSUE THREAD

**Issue by linlan-doc** [dart-lang/site-www#4151]
### Page URL

https://dart.dev/guides/language/language-tour

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/language-tour.md

### Describe the problem

In the section Numbers

```
var exponents = 1.42e5; 
print(exponents.runtimeType)
```

The result is int.

**Comment by domesticmouse** [comment]
It is?

```dart
void main() {
  var exponents = 1.42e5;
  print(exponents.runtimeType);
}
```

Running the above code:

```console
$ dart run bin/exponents_runtime_type.dart 
double
```

**Comment by danagbemava-nc** [comment]
@domesticmouse, it produces an `int` if you run it in `dartpad/web`. 

<img src="https://user-images.githubusercontent.com/88313112/180786659-ceb8fc92-cb14-42e5-ad6d-9d1e40ec100e.png" width="400" />

Hi @linlan-doc, this is covered in the [numbers documentation](https://dart.dev/guides/language/numbers). 

> An int on the web is represented as a double-precision floating-point value with no fractional part. In practice, this works pretty well: double-precision floating point provides 53 bits of integer precision. However, int values are always also double values, which can lead to some surprises.

The above is an excerpt from the numbers page. See the last paragraph in https://dart.dev/guides/language/numbers#dart-number-representation 

Does the documentation sufficiently explain the unexpected behaviour for you?

**Comment by linlan-doc** [comment]
I tested on Android emulator and the output is double, Thank you for your time.

**Comment by parlough** [comment]
Thanks for clearing it up @danagbemava-nc. 

We do link to the article, but I wonder if we can make it more explicit it describes the differences between platforms.
