### ISSUE TITLE
Improve visibility of dart-lang/linter docs

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#4158]
### Page URL

https://dart.dev/tools/linter-rules

### Page source

https://github.com/dart-lang/site-www/blob/main/src/tools/linter-rules.md

### Describe the problem

If I'm looking for more information about a rule, I need to go to the [linter package documentation](https://dart-lang.github.io/linter/lints/) and search for it there. 

### Expected fix

Link to the linter package docs from the [Linter rules page](https://dart.dev/tools/linter-rules)

**Comment by parlough** [comment]
I'm curious what information do you need from the linter standalone website that isn't present on the dart.dev Linter rules page? Or are you looking for information in a specific format?

For the most part, the information is the same, and I would rather reduce the need to go to the external site.

**Comment by johnpryan** [comment]
That makes sense. Maybe there's some things we could do to make this page easier to use like  badges or separate pages for each rule.
