### ISSUE TITLE
Trim down and reorganize examples code

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#416]
@kwalrath - A few questions about the code that came from the up-and-running repo:

- Some of the examples contain much more code than what is used in the tour code excerpts. Could we trim this down (before we start writing tests for all the code excerpts - #407)?
- Is it necessary to keep the current example subfolder structure? Some very small code excerpts could be combined (of course, provided that there is a meaningful grouping).
- Each example (except for those under `reference`) has its own `main()` etc. Our main goals is to test the code excerpts, not necessarily run them. So in some cases, the extra code used to run the excerpt could be dropped in favor of having tests instead.

Thoughts?

**Comment by kwalrath** [comment]
Feel free to do anything that'll make the code easier to deal with and test. You have carte blanche.

**Comment by kwalrath** [comment]
Actually, one caveat... We might want to convert some/most of the examples to be DartPads. Those might need to be complete examples (or easily convertible to complete examples).

**Comment by chalin** [comment]
Completed via #445, #443, #440, ... .
