### ISSUE TITLE
Clarify caret syntax

### ISSUE THREAD

**Issue by Roms1383** [dart-lang/site-www#4160]
### What information is missing?

As per the [docs of caret syntax for dependencies](https://dart.dev/tools/pub/dependencies#caret-syntax), it states that:
* `^1.2.3` is equivalent to `'>=1.2.3 <2.0.0'` (up to the next **major** release, exclusive)
* `^0.1.2` is equivalent to `'>=0.1.2 <0.2.0'` (up to the next **minor** release, exclusive)

What is the correct interpretation here ?
Does it mean that `^0.1.2` extends to the next **minor** because:
* if and only if it is `0.x.x` (based on current **major** being `< 1`)
* if and only if it is `x.1.x` (based on current **minor** being `< 2`)

Also, as the question might arise later on:
* what would `^0.0.0` translates into ?
* what would `^2.0.0` translates into ?

This issue relates and complements #168 / #193 / #825 / #1075

### How would you like us to fix this problem?

I think you should just mention which criteria will make the caret syntax extends to the next **major** release (exclusive) or the next **minor** release (exclusive).

**Comment by Roms1383** [comment]
There's an explanation already [on StackOverflow](https://stackoverflow.com/questions/53563079/what-is-the-caret-sign-before-the-dependency-version-number-in-flutters-pub), could you please confirm that it's correct ?

**Comment by parlough** [comment]
Yeah that is a good explanation on StackOverflow. As the section you pointed out notes, the caret syntax expands up to before the next breaking version:

> ^version means the range of all versions guaranteed to be backwards compatible with the specified version.

Based on the semver scheme pub uses, this is the next major version (X.0.0) for any major > 1, and the next minor version (0.X.0) for and major < 1:

We have further documentation on pub's versioning here: https://dart.dev/tools/pub/versioning#semantic-versions

I would rather not duplicate most of them, but I think we still could be more explicit about it being based on semantic version, link to that section on it, and explicitly state why the `^0.1.2` example expands to the next minor, not major version.

Thanks for opening the issue. It will be good to make clarifications here!

**Comment by Roms1383** [comment]
Awesome, thanks!
