### ISSUE TITLE
Consider adding complete Dart Course in progress PT-BR

### ISSUE THREAD

**Issue by washingtondeveloper** [dart-lang/site-www#4165]
Page URL

https://www.youtube.com/watch?v=Vz11rFFewkM&list=PLK5FPzMuRKlyiWZUUqea2Hmszhy9vUixJ

### Describe the problem

I would like to share the track of videos I'm producing for learning the Dart language.

Videos are in progress. Until the opening date of this issue, the last video is in series 66.

### Expected fix

Being able to share with videos from the videos page
https://dart.dev/resources/videos

**Comment by atsansone** [comment]
@johnpryan : Do you have any guidance on adding this type of content to the docs?

**Comment by johnpryan** [comment]
@washingtondeveloper thanks for sharing your series! This is the first Dart course in Portuguese that I've seen, and looks like it's already helping a lot of Portuguese speakers learn Dart.

@atsansone We should try to avoid adding _too_ many YouTube playlists to this page and have clear guidance for contributors. I tend to agree with this [comment from filiph](https://github.com/dart-lang/site-www/pull/1357#pullrequestreview-205905467). We might want to define some criteria to make sure that each course is up-to-date (for example, a course that uses Dart 1 doesn't use null safety) and unique from the others we list. The [Flutter videos page](https://docs.flutter.dev/resources/videos) page also links to some unofficial courses so ideally this criteria would be the same.

There are probably some more english-language Dart courses on YouTube than the Smartherd playlist we currently link to.

**Comment by washingtondeveloper** [comment]
In this series I am closely following the  [documentation](https://dart.dev/guides) and [specification](https://dart.dev/guides/language/spec) of the language.
