### ISSUE TITLE
[PAGE ISSUE]: 'Objective-C interop using package:ffigen' needs to be updated for `exclude-all-by-default`

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/site-www#4169]
### Page URL

https://dart.dev/guides/libraries/objective-c-interop

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/libraries/objective-c-interop.md

### Describe the problem

The text of this page contains a sample of the `ffigen` config that was changed in https://github.com/dart-lang/ffigen/pull/431/files#diff-e352cb7b95dae5bdc12e90c5d6f71e27a9dd5677ab003fd13bb1c162a1f5e0c7

This page needs to be updated for `exclude-all-by-default`

/cc @liamappelbe and @dcharkes

**Comment by parlough** [comment]
I believe this will be fixed by https://github.com/dart-lang/site-www/pull/4167 which I hope to review soon.
