### ISSUE TITLE
Example DartPad Gists are becoming out-of-date: update or drop them

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#417]
Example Gists are falling behind relative to the examples sources that they were created from. The Gists need to be updated. Actually, a much better alternative would be to avoid having to create Gists altogether :). See https://github.com/dart-lang/dart-pad/issues/788.

This is partly in support for #407.

**Comment by kwalrath** [comment]
I think we fixed the individual gists in our updates for Dart 2. Let's open specific issues for any exceptions we find in the future. (That said... I'd love a better way of keeping the DartPad code up to date.)

/cc @RedBrogdon
