### ISSUE TITLE
Document "funding" key for "pubspec.yaml"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#4183]
On the https://dart.dev/tools/pub/pubspec page.

```yaml
funding:
 - https://fundme.example.com/myname
```

**Comment by parlough** [comment]
I saw support was added to pub.dev in https://github.com/dart-lang/pub-dev/pull/5961. Does the current deployment have this change?

Also, just to confirm, the field only supports a list of HTTPS URLs? How about just one?

For other's reference: https://github.com/dart-lang/pub-dev/issues/4353

**Comment by isoos** [comment]
> Does the current deployment have this change?

Yes, it does.

> Also, just to confirm, does the field only support a list of HTTPS URLs? How about just one? 

Yes. That would be a list of one https URL.
