### ISSUE TITLE
Small markdown formatting glitch on ObjC guide

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/site-www#4204]
### Page URL

https://dart.dev/guides/libraries/objective-c-interop

### Describe the problem

In the swift example, there's a string literal that's incorrectly formatted: `"\_TtC12***swift\_module***10***SwiftClass***"`

The code tags are preventing the bold tags from working, and the underscores also don't need to be escaped.

### Expected fix

Either remove the code tags, or remove this string entirely (the section is clear enough without it).

**Comment by parlough** [comment]
Sorry, when reviewing I mistook the purpose of the formatting and added the code tags. Thanks for catching this. You can remove the code tag.

**Comment by liamappelbe** [comment]
Actually, mixing both looks pretty good on the site (though it looks a bit odd on github): `"_TtC12`***`swift_module`***`10`***`SwiftClass`***`"`
