### ISSUE TITLE
Document Flutter specific sections on page containing the pubspec format.

### ISSUE THREAD

**Issue by chinmaygarde** [dart-lang/site-www#421]
The pubspec format is [documented here]( https://www.dartlang.org/tools/pub/pubspec). However, it does not contain any Flutter specific sections. This includes useful things like adding assets, fonts, etc.. It would be great if all the default comments that are added as part of a new project template were documented on that page.

**Comment by sethladd** [comment]
Do we have this material documented on flutter.io ? I found https://flutter.io/using-packages/

I'd prefer not having to duplicate this content. Could we link over to flutter.io, from https://www.dartlang.org/tools/pub/pubspec, so there is a canonical doc about flutter + packages on flutter.io ?

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by sethladd** [comment]
@chinmaygarde is the bug "a user couldn't find the canonical docs for flutter-specific pubspec.yaml sections" ?

**Comment by chinmaygarde** [comment]
Yes. I was trying to add assets to a pubspec from which I had deleted the default comments. I Googled "pubspec format" and got to that page which didn't help. Then I ended up on https://flutter.io/using-packages/ which didn't help either. Then I just created a new project to see what the comments were.

The stuff I needed does seem to be documented here https://flutter.io/assets-and-images/.

**Comment by sethladd** [comment]
Ah, thanks for the clear explanation of your journey!

I'll turn it over to @mit-mit to help out here.

Agreed, we should probably document on /assets-and-images/ and Flutter's packages docs and link from dartlang.org's site.

**Comment by mit-mit** [comment]
Added links to assets page from 'using packages' in https://github.com/flutter/website/pull/729

Let me do some digging and see if we can get links added to https://www.dartlang.org/tools/pub/pubspec
