### ISSUE TITLE
[2.19] runZoned docs

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4224]
### Parent: 
https://github.com/dart-lang/sdk/issues/49679

### Evaluation: 
- Update needed:
    - https://dart.dev/articles/archive/zones : `runZoned` with `onError` used
    - ~Page is archived, what's the policy there? Update and take out of archive?~
      - Will take care of in a separate issue: https://github.com/dart-lang/site-www/issues/4348
- ~No entry in change log yet, add~
  - The only changes here are to the API docs, `onError` was already deprecated in a past release. I don't think cathcing up on API docs changes warrant an item in the change log 
  - But still warrants mention in 'What's new' page

### Reference:
- API docs already updated, use new syntax: https://github.com/dart-lang/sdk/commit/59cd692fb996f7b4f534a11ec9e270fcea07629e
- [This issue](https://github.com/dart-lang/sdk/issues/40681) better describes the change from `runZoned` with `onError` to `runZoned` and `runZonedGuarded`
- Some examples of `runZonedGuarded` in use:
  - [errorZone API](https://api.dart.dev/dev/2.19.0-437.0.dev/dart-async/Zone/errorZone.html)
  - [`(error, stackTrace)` example](https://github.com/privacybydesign/irmamobile/commit/577c26320a3ebdc7faa74cfe990efbdf70923d4a)
  - [`(dynamic error, StackTrace stackTrace)` example](https://github.com/aam/engine/commit/9a49932bf69b72c80eebb04fca22629ce7e7f2a8)
  - [other error handler output](https://github.com/abegehr/monsterjump/commit/12be8147386c6c9538fdd868eca8a13e880acef5)

**Comment by parlough** [comment]
The zones article is heavily outdated, in both the code examples and some of the explanations with much of it predating Dart 2. The writing and formatting of the website has heavily changed since then too.

Users want to learn more about zones though, so I would like to see the article updated. Starting with getting the code examples function and then adjusting for the 2.19 changes next would be a good start.

**Comment by MaryaBelanger** [comment]
@parlough So, this doesn't need to be rolled out with the 2.19 release, necessarily? It sounds like an improvement issue vs. a fix. Just want to clarify

**Comment by parlough** [comment]
The removal of `onError` from `runZoned` does require changes/fixes to the article with the 2.19 release.

I'm just highlighting other changes are needed to get the article compatible with even Dart 2.18 (hence the current archived state), so perhaps that's a higher priority, first step.

**Comment by MaryaBelanger** [comment]
@parlough could you help me figure out where to view the changes made in [this commit](https://github.com/dart-lang/sdk/commit/59cd692fb996f7b4f534a11ec9e270fcea07629e) in api.dart.dev? I've found that [lines 1696-1726](https://dart-review.googlesource.com/c/sdk/+/255252/5/sdk/lib/async/zone.dart#1696) seem to correspond to [here](https://api.dart.dev/dev/2.19.0-437.0.dev/dart-async/runZoned.html)... but I can't find some of the other new stuff/changes. Eg, where do the examples between [lines 624 and 668](https://dart-review.googlesource.com/c/sdk/+/255252/5/sdk/lib/async/zone.dart#624) show up in the API docs? 

How can I learn to interpret API doc changes better going forward?

I'd like to see the new examples of `runZonedGuarded` rendered in the API docs (it's hard to assess what the samples look like in the diff :/)

Appreciate your time! 🙏

**Comment by parlough** [comment]
It seems some of those changes might be on the properties of the [`Zone`](https://api.dart.dev/dev/dart-async/Zone-class.html) class itself. For example, lines 624 through 688 are on the [`errorZone`](https://api.dart.dev/dev/dart-async/Zone/errorZone.html) property of the class.

It's sometimes bit hard to see, especially on Gerrit, but to find where doc changes are, I scroll down to find the class, property, or method they are attached to, then I search for that. For example when searching for `errorZone`, the first result is that `Zone` property. If there are multiple results, I scroll up to find the class the method or property is part of.

**Comment by MaryaBelanger** [comment]
Small related fix in API docs: https://dart-review.googlesource.com/c/sdk/+/272488

**Comment by MaryaBelanger** [comment]
Fixing PRs merged into [v2.19](https://github.com/dart-lang/site-www/tree/v2.19)
