### ISSUE TITLE
[PAGE ISSUE]: 'Get the Dart SDK'

### ISSUE THREAD

**Issue by dikeshchouhan1** [dart-lang/site-www#4226]
### Page URL

https://dart.dev/get-dart/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/get-dart/index.md

### Describe the problem

debugging

**Comment by danagbemava-nc** [comment]
Hi @dikeshchouhan1, what is the issue you're referring to? Some more information would be appreciated

**Comment by parlough** [comment]
I'm going to close this issue, but if you have any more information or need more help, feel free to respond here or open a new issue. Thanks!
