### ISSUE TITLE
[PAGE ISSUE]: 'Get the Dart SDK'

### ISSUE THREAD

**Issue by ispbridge** [dart-lang/site-www#4248]
### Page URL

https://dart.dev/get-dart/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/get-dart/index.md

### Describe the problem

Code for M1 Mac didn't work

$ brew upgrade dart
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.

### Expected fix

for M1 Mac this one worked

"$arch -arm64 brew install dart"

**Comment by parlough** [comment]
Thanks for opening an issue @ispbridge!

It looks like you have the ARM version of Homebrew installed, so I'm confused why you need to specify to run the command in `amd64` mode. Is the terminal you're running this in running in Rosetta mode? [This article](https://www.macworld.com/article/338843/how-to-force-a-native-m1-mac-app-to-run-as-an-intel-app-instead.html) shows how to check if an app is set to run with Rosetta.

**Comment by parlough** [comment]
I'm going to close this for now as I haven't seen anyone else have the issue and we would need some extra information. Let us know if you're still facing this issue though. Thanks again!
