### ISSUE TITLE
[2.19] Deprecated APIs

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4249]
## This is an _evaluation_ ticket

Evaluating the _possible_ need for doc updates due to dart-lang/sdk#34233

### Summary

APIs deprecated in previous releases are fully removed now.

### Evaluation

Search dart.dev for all the APIs mentioned in the change log, (unlikely any are mentioned in the docs)
Correct to new recommended option if available :

- [x] `MirrorsUsed` and `Comment`
- [x] `kInvalidParams`
- [x] `kExtensionError`
- [x] `kExtensionErrorMax`
- [x] `kExtensionErrorMin` in `ServiceExtensionResponse`
- [x] `DEFAULT_BUFFER_SIZE` in `JsonUtf8Encoder`
- [x] Deprecated in 2.19: `UserTag.MAX_USER_TAGS`
- [x] `FallThroughError`
- [x] `registerElement` and `registerElement2` in `Document` and `HtmlDocument`
- [x] `NullThrownError` and `CyclicInitializationError`
  - gotta update [the spec](https://spec.dart.dev/DartLangSpecDraft.pdf) 🙃 
- [x] `IndexError` constructor in favor of `IndexError.withLength`
- [x] `RangeError.checkValidIndex` in favor of `IndexError.check`

### References

see [changelog](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#2190) for details, replacements, etc.

**Comment by parlough** [comment]
We don't currently track SDK release notes or breaking changes outside of language evolution and a link to the blog on the site's "What's new page". Might be useful to introduce a similar page to Flutter's.

As for the deprecations and removals here, you're right that we'll unlikely use any of these, but thanks for checking!

**Comment by MaryaBelanger** [comment]
Thanks for the insight @sfshaza2! Yeah, like @parlough said this is just to check the regular docs to make sure none of these are mentioned in any of the long-form content (guides, tutorials, troubleshooting, etc.); these changes are all documented in the change log already. 

[Flutter breaking changes](https://docs.flutter.dev/release/breaking-changes) (for my reference)
> Might be useful to introduce a similar page to Flutter's

Possibly, not sure how to gauge the usefulness of that but I could make another issue and see what the team thinks

**Comment by MaryaBelanger** [comment]
As expected, nothing in the docs (except the spec I think, but I know that lags behind). Closing!
