### ISSUE TITLE
Language tour: "Overridable operators" should be rephrased

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#425]
The section title and section on [Overridable operators](https://www.dartlang.org/guides/language/language-tour#overridable-operators) needs a little rework IMHO. The qualification of operators as (only) _overridable_ (as opposed to simply "definable") is misleading.

From the [DLS](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf), Section 10.1.1:
> _Operators_ are instance methods with special names.
> ...
> The following names are allowed for **user-defined operators**: <, >, <=, >=,
==, -, +, /, ˜/, *, %, |, ˆ, &, <<, >>, []=, [], ˜.

Maybe use of the title "User-definable operators" would be better than the current "Overridable operators"? And it should rapidly be made clear that "_Operators_ are instance methods with special names." I.e., one cannot define an operator in any other context.

**Comment by chalin** [comment]
If this is fixed, then #311 could easily be addressed too.

**Comment by kwalrath** [comment]
Sure, have at it!

**Comment by micpap25** [comment]
It's a bit hard to tell what exactly the status of this is since it still says "Overridable Operators", but since #311 was closed I think this can be closed as well.

**Comment by kwalrath** [comment]
Thanks for taking a look, @micpap25. @chalin what do you think?

**Comment by chalin** [comment]
> It's a bit hard to tell what exactly the status of this is since it still says "Overridable Operators", 

In my opinion, the problem originally reported here still holds.

> ... but since #311 was closed I think this can be closed as well.

I'm not sure I follow your reasoning: #311 was closed because #976 resolved the issue.

---

Actually, taking another quick look, IMHO a few more changes would help:

- Under [Classes > Methods](https://dart.dev/guides/language/language-tour#methods): add a subsection named "Operators" (because as the DLS says, operators are just methods with special names).
- The top-level [Operators section](https://dart.dev/guides/language/language-tour#operators) should be changed to refer to the new **Classes > Methods > Operators** section. I don't think that there is a need to refer to "Overridable operators".

I'm seeing other changes that would need to be done. If you'd like I can give it a shot some time this month.

**Comment by micpap25** [comment]
@chalin Ah, sorry, I thought your first comment...

> If this is fixed, then #311 could easily be addressed too.

...was saying that "this is fixed, thus we can easily address #311", not "when this is fixed, we can also address #311". If that makes sense, lol. 

I was originally asking about this issue because I wanted to resolve it, but it seems you have a clear plan of what will change so I'll move on to a different issue.

**Comment by chalin** [comment]
Oh, I see! No worries. Yes, I'll submit a fix soon. Cheers.
