### ISSUE TITLE
[3.2] Private field promotion docs

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4254]
## This is an _evaluation_ ticket

Evaluating the possible need for doc updates due to dart-lang/language#2020

### Summary

Type promotion is currently only available for _local_ variables. [#2020](https://github.com/dart-lang/language/issues/2020) will make it possible for _class_ fields to be safely promoted if they meet certain criteria: when the field is `private` and `final` (and there are no concrete getters of the same name, in the same library). 

Limiting promotable fields to `final` tells the compiler the instance value can't change (and therefore, type promotion remains sound). But, `final` doesn't protect soundness if another class implements the original class and overrides its field declarations. So, the compiler scans the library for implementing classes and can prevent type promotion of the original because of it.

But what if a class outside of the library implements the defining class and overrides its fields? The compiler can't check for implementing classes outside of the original's library, which is why the field must also be `private`. A `private` field tells the compiler that an implementing class from another library isn't able to change the value. 

So `private` and `final` allow the compiler to soundly promote a type because they inherently mean the value cannot be overridden outside of the compiler's purview.

One loophole (`nosuchmethod` overriding interfaces in an implementing class that doesn't fulfill the interface contract, i.e. doesn't explicitly declare the fields of the original class) is covered in [#49687](https://github.com/dart-lang/sdk/issues/49687) and another evaluation ticket (https://github.com/dart-lang/site-www/issues/4263).

### Evaluation

- [Fixing type promotion failures](https://dart.dev/tools/non-promotion-reasons)
  - #5246 
  - The sections on this page are actually linked to in type promotion error messages. 
  - [Only local variables can be promoted](https://dart.dev/tools/non-promotion-reasons#property-or-this) is no longer an error
  - "Write captured by a local function", "Written outside of the current closure or function expression", "Write captured outside of the current closure or function expression" sections all have "create a local variable" as a solution / workaround, so I'm wondering if they'll still be errors once non-local variables can be promoted, or maybe the workaround will change to utilize private final field promotion
    -  "Other causes and workarounds" section also mentions creating a local variable to fix most type promotion issues

  - New sections will need to be added to support new error messages from 2020 (@stereotype441 evaluating actual error code):
    - When non-local field promotion is not allowed because they're using an older version of Dart
    - When promotion doesn't work because the field is not final and private
    - When there's a getter with the same name in the same library that isn't final
      - [This comment in 2020](https://github.com/dart-lang/language/issues/2020#issuecomment-1190546861) says: "If the user tries to promote a field, and it's not promotable because there's some other concrete instance getter with the same name that's not a final field, **we can easily explain to them why the promotion failed**. And if they want promotion anyway (and know that it's safe), **the workaround should be fairly intuitive: just rename the field**."
      -  The workaround here is unclear, "just rename the field" is referring to the original field or the getter?
        - wouldn't the getter need to have the same name as the field it's getting? 
        - wouldn't the fix be that they need to declare the getter final too?

- [Effective Dart](https://dart.dev/guides/language/effective-dart/usage#consider-assigning-a-nullable-field-to-a-local-variable-to-enable-type-promotion)
   Implementation draft here: ~https://github.com/dart-lang/site-www/pull/4272~ 
   New: https://github.com/dart-lang/site-www/pull/5324
  - "Unfortunately, promotion is only sound for local variables and parameters, so fields and top-level variables aren’t promoted." - no longer true
  - ~The entire workaround is technically no longer necessary, maybe the section can be removed?~
    - It's still necessary, there are still many cases where type promotion isn't allowed and this is still a workaround for them.
  - ~Should we add a "CONSIDER" section recommending declaring private final fields if you want type promotion to happen?~
    - No, stating it in the existing section instead
- [x] [The Dart type system](https://dart.dev/language/type-system)
  - Maybe part of https://github.com/dart-lang/site-www/issues/4745 
  - No updates
- [x] [Fixing common type problems](https://dart.dev/guides/language/sound-problems) is another too-similar page that might need to be addressed to not detract from the source of truth that [Fixing type promotion failures](https://dart.dev/tools/non-promotion-reasons) should be.
  - No updates
  - [x] Put Fixing type promotion failures in the side nav somewhere...
  - [x] MAYBE consolidate? https://github.com/dart-lang/site-www/issues/4393
- [X] [Overview](https://dart.dev/null-safety) (nothing related)
- [X] [FAQ](https://dart.dev/null-safety/faq) (nothing related)
- [X] [Codelab](https://dart.dev/codelabs/null-safety)
  - Fairly certain there's nothing related, but the examples should probably be tested as-is with private final field promotion active...?
  - https://github.com/dart-lang/site-www/pull/5329
- [x] [Understanding null safety](https://dart.dev/null-safety/understanding-null-safety):
- https://github.com/dart-lang/site-www/pull/5325
  - [Type promotion on null checks](https://dart.dev/null-safety/understanding-null-safety#type-promotion-on-null-checks)
    - "Note that type promotion only works on local variables, not on fields or top-level variables..."
  - [Working with nullable fields](https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields)
    - E.g. "Flow-based type promotion does not apply to fields because..."
    - The entire section might be a misnomer because it's purpose is to provide a workaround for promoting nullable fields (there's also a ["Working with nullable _types_"](https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-types) section)
  - Lots of minor wording about local-only 

### References

- Original issue: https://github.com/dart-lang/language/issues/2020
- Comment that mostly sums up the final conclusion: https://github.com/dart-lang/language/issues/2020#issuecomment-1190546861

**Comment by stereotype441** [comment]
Minor nit: when you say "and getters of the same name, in the same library, are also final" I think you mean something like "and there are no concrete getters of the same name, in the same library".  (There's no such thing as a final or non-final getter).

**Comment by MaryaBelanger** [comment]
Note: need to take into consideration record fields as well

**Comment by parlough** [comment]
I don't you intended to close this as done yet. I'm going to reopen it, but feel free to close if that's what you meant :)

**Comment by MaryaBelanger** [comment]
@parlough Thanks, that wasn't supposed to happen! 😱  I think it happened because I linked the recent go-link pr to this, and just closed that. But you're right, definitely not anywhere near being done :)
