### ISSUE TITLE
Effective Dart: Don't type annotate initializing super formals

### ISSUE THREAD

**Issue by srawlins** [dart-lang/site-www#4262]
### Page URL

https://dart.dev/guides/language/effective-dart/design#dont-type-annotate-initializing-formals

### Describe the problem

Effective Dart has a rule, "DON’T type annotate initializing formals." which should be extended to cover super parameters.

### Expected fix

I don't know if a super parameter is an "initializing formal" or a new construct. So either we need a new rule, change the name of this rule, or just add some text in this rule.

**Comment by srawlins** [comment]
CC @munificent @natebosch

**Comment by natebosch** [comment]
Mentioning super parameters in that rule SGTM.

**Comment by munificent** [comment]
Me too.

**Comment by natebosch** [comment]
@srawlins - will we update the `type_init_formals` lint to catch this case as well?

**Comment by srawlins** [comment]
Yeah the proposal is in https://github.com/dart-lang/linter/issues/3210
