### ISSUE TITLE
Deploy is failing due to permission issue 

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4269]
### Describe the problem

Automatic deploy is failing on the main branch, due to a `cloudfunctions.functions.list` permission being denied.

```
  Error: HTTP Error: 403, Permission 'cloudfunctions.functions.list' denied on 'projects/dart-dev/locations/-/functions'
  [2022-10-06T17:50:49.242Z] Error Context: ***
    "body": ***
      "error": ***
        "code": 403,
        "message": "Permission 'cloudfunctions.functions.list' denied on 'projects/dart-dev/locations/-/functions'",
        "status": "PERMISSION_DENIED"
      ***
    ***,
    "response": ***
      "statusCode": 403
    ***
  ***
 ```
 
 Failed build log: https://github.com/dart-lang/site-www/actions/runs/3196595084/jobs/5224887570

### Additional context

The part of the workflow which handles deployment can be found at: https://github.com/dart-lang/site-www/blob/main/.github/workflows/build.yml#L72-L77

**Comment by khanhnwin** [comment]
This looks like a new permission that's required by the Firebase action since nothing was changed on the service account IAM. I've updated the IAM settings on our service account as a fix and re-ran the deploy action to verify. 

Context: https://github.com/FirebaseExtended/action-hosting-deploy/issues/203

**Comment by khanhnwin** [comment]
We're green again! https://github.com/dart-lang/site-www/actions/runs/3196595084/jobs/5225548010

**Comment by parlough** [comment]
Thanks so much @khanhnwin!
