### ISSUE TITLE
Don't break build when a new Node or Dart release is made

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4297]
### Describe the problem

It can impact work, breaking deploys and staging on PRs until someone updates the checksums, which not everyone may have the local setup to do so easily. Even once it's updated, PRs need to be updated by rebasing or merging to pass the build.

### Expected fix

I understand the checksum checks are important, but could we just pin and check a specific version and then update those pinned versions as desired?

**Comment by MaryaBelanger** [comment]
> could we just pin and check a specific version and then update those pinned versions as desired?

I don't have anything useful to add to whether it'd be ok to do this. Just emphatically voting to not have have the build break so often! Thanks Parker.
