### ISSUE TITLE
Not clear how to add dependencies to a command-line dart app from the command-line tutorial

### ISSUE THREAD

**Issue by DaveShuckerow** [dart-lang/site-www#432]
https://dart.dev/tutorials/server/cmdline

It's not clear from this tutorial that you need a pubspec or some other definition to resolve the dependency on package:args.

**Comment by kwalrath** [comment]
I suspect this page predates pub. Thanks very much for reporting this issue!

**Comment by kwalrath** [comment]
We've updated the page, but it still doesn't discuss pubspec.
