### ISSUE TITLE
Add an example for quoted exception in Effective Dart's Design section. 

### ISSUE THREAD

**Issue by iLoveDocs** [dart-lang/site-www#4324]
### What information is missing?

In the [PREFER the “positive” name for a boolean property or variable.](https://dart.dev/guides/language/effective-dart/design#prefer-the-positive-name-for-a-boolean-property-or-variable) section, there's an exception quoted like this: 

> Exception: With some properties, the negative form is what users overwhelmingly need to use. Choosing the positive case would force them to negate the property with ! everywhere. Instead, it may be better to use the negative case for that property.

It would be nice to provide example for this. 

### How would you like us to fix this problem?

An example could be: 

```dart
// Good 
if (list.isNotEmpty) {
  print(list.first);
}

// Bad
if (!list.isEmpty) {
  print(list.first);
}
```

**Comment by parlough** [comment]
Thanks for opening an issue. We don't currently have a lot of examples for exceptions, perhaps to avoid confusion, but this makes sense in general.

I'd like to hear @munificent's thoughts.
