### ISSUE TITLE
Two new books that replace Dart Apprentice

### ISSUE THREAD

**Issue by suragch** [dart-lang/site-www#4359]
### Page URL

https://dart.dev/resources/books

### Describe the problem

Kodeco (formerly raywenderlich.com) has updated their Dart Apprentice book. Rather than simply publishing a new edition of Dart Apprentice, we broke the book into two, reworking the content and adding new chapters. The two new books are Dart Apprentice: Fundamentals and Dart Apprentice: Beyond the Basics.

In the future we will not continue updating Dart Apprentice. My recommendation is to remove Dart Apprentice from the page and replace it with the two new books. This will keep readers from getting confused.

On the other hand, Dart Apprentice still mostly works since it is up to date for Dart 2.12 and it covers many of the topics in one volume that the two newer books cover. Cost conscious readers may prefer that. The differences are listed [here](https://forums.kodeco.com/t/dart-apprentice-old-vs-new/180601/2).

### Expected fix

Here are the links for the new two-book series (up-to-date for Dart 2.18):

- https://www.kodeco.com/books/dart-apprentice-fundamentals
- https://www.kodeco.com/books/dart-apprentice-beyond-the-basics

### Additional context

I'm the author.

**Comment by parlough** [comment]
I think we’d prefer to link to resources that will stay up to date. Thanks for the heads up!

**Comment by suragch** [comment]
@parlough Thank you. Looks good.
