### ISSUE TITLE
Followup to "Language tour example tests (#427)"

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#437]
Followup to #427. Comments by @filiph and @kwalrath are inlined below:

- [ ] If it does require the closing `!]`, I think we're good. I can't imagine `!]` in regular Dart code outside some weird string literal (which, I can live with).
  
  Still suggest documenting this here. ([original comment](https://github.com/dart-lang/site-www/pull/427/files#r151214996))
- [x] switch to `#confirm` instead of `button` as selector. in `querySelector('button')` - #438
- [x] ~This might need a bit more motivation here. Maybe show a code excerpt where you're testing the input, or just link to a dart file that uses `$print` and is most likely to survive forever.~
  
  ~Also, should we _always_ use `$print`, even in excerpts that are not tested (yet)? If so, clarify the language — "you should always use $print because ..."~ - #438. We're dropped `$print` in favor of using the test package `prints` matcher.
- [x] ~I'd suggest renaming it to `xvfb.sh` or something similar, then. Unless you have a concrete plan of uncommenting that `content_shell` line.~ #450 solves this by dropping the script altogether.

---

Related: #436

**Comment by kwalrath** [comment]
It looks like everything people really wanted has been done. Closing.
