### ISSUE TITLE
[2.19] Docs for new type inference circular dependency error

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4391]
## This is an _evaluation_ ticket

Evaluating the _possible_ need for doc updates due to https://github.com/dart-lang/sdk/issues/50383

### Summary
A compile-time error now occurs for inference dependency cycles. 

### Evaluation
Since this involves new messages in the analyzer and compiler, and since it's related to type inference, could there potentially be a new section on this page? https://dart.dev/tools/non-promotion-reasons

### References
- https://dart-review.googlesource.com/c/sdk/+/206421
- https://github.com/dart-lang/language/issues/1650

**Comment by MaryaBelanger** [comment]
@eernstg @scheglov for the new analyzer and compiler messages, would those messages potentially fit into the [Fixing type promotion failures](https://dart.dev/tools/non-promotion-reasons) page? 

Those sections [are linked to](https://github.com/dart-lang/sdk/blob/main/pkg/_fe_analyzer_shared/lib/src/flow_analysis/flow_analysis.dart#L2221) from different analyzer messages relating to type promotion failure, I believe. It seems like the compile-time error implemented by https://github.com/dart-lang/sdk/issues/50383 could be considered a type promotion failure, but I could be mistaken. 
Please let me know what your thoughts are about this! Thanks

**Comment by MaryaBelanger** [comment]
@stereotype441 can you let me know if I'm conflating type _inference_ failure with type _promotion_ failure? 

The more I look at this, I think https://github.com/dart-lang/sdk/issues/50383 absolutely qualifies as a type promotion failure; it literally blocks inference that wasn't previously blocked, and blocking inference blocks promotion, doesn't it?

Impact is extremely minimal, but documentation should be complete. If we document type promotion failures [here](https://dart.dev/tools/non-promotion-reasons) and link to those sections from the analyzer, then it should be done for every failure.

Unless I'm wrong and conflating, I will be: 
- adding a section to [Fixing type promotion failures](https://dart.dev/tools/non-promotion-reasons), and 
- creating a new class extending `NonPromotionReason` in [flow_analysis.dart](https://github.com/dart-lang/sdk/blob/main/pkg/_fe_analyzer_shared/lib/src/flow_analysis/flow_analysis.dart) to point to that section

**Comment by MaryaBelanger** [comment]
Ok just got my answers elsewhere, type promotion is _not_ the same thing as type inference. So, 
- nothing to add to [Fixing type promotion failures](https://dart.dev/tools/non-promotion-reasons) 
- [Fixing common type problems](https://dart.dev/guides/language/sound-problems) is for more general type problems (not just promotion failures), but the key word there is "common" problems, which this is not, so nothing to do there either
- Diagnostic docs are updated with the code as usual

So, nothing to do here, closing this issue!

**Comment by eernstg** [comment]
Sorry about the missing answer, just came back from a flu. Sounds like everything is in good shape now. Please give me a heads up if I can help with anything!

**Comment by MaryaBelanger** [comment]
Reopening because of [this comment](https://github.com/dart-lang/sdk/issues/50383#issuecomment-1396202035)

**Comment by MaryaBelanger** [comment]
aaaaand closing again because I forgot type inference is not the same as type promotion 🙃 so in lieu of a type _inference_ reference page, there's really no where to put this info.

I think I'll be revisiting this once we start to fill out the documentation but right now the foundation isn't there to support niche cases like this
