### ISSUE TITLE
[2.19] New diagnostic documentation available

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/site-www#4399]
There is new diagnostic documentation available in `pkg/analyzer/tool/diagnostics/diagnostics.md` that I would like to have published as soon as possible. The text has been reviewed, so there should be minimal edits required to land the changes.

@parlough

**Comment by parlough** [comment]
The additions and changes look good to me. So should be ready to land.

**Comment by parlough** [comment]
@bwilkerson Should be published in ~10 minutes :)
