### ISSUE TITLE
[2.19] Update whats-new and language evolution pages

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4404]
Once all 2.19 issues are closed, update [whats-new.md](https://github.com/dart-lang/site-www/blob/main/src/_guides/whats-new.md) and [evolution.md](https://github.com/dart-lang/site-www/blob/main/src/_guides/language/evolution.md) to reflect 2.19 changes (complete list [here](https://github.com/orgs/dart-lang/projects/55/views/2?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status))

**Comment by MaryaBelanger** [comment]
Need to specifically address where and how to add version notes about some of these changes
- [ ] [New "Don't explicitly name libraries" section](https://github.com/dart-lang/site-www/pull/4390#discussion_r1050533403)

**Comment by MaryaBelanger** [comment]
I'm not sure how this usually goes, maybe @parlough you can lmk, or maybe @sfshaza2 you might know what the practice was: 

We added a kind-of-big update/[new Effective Dart entry](https://github.com/dart-lang/site-www/pull/4423) _during the 2.19 window of time_. 

Even though it had nothing to do with 2.19 _development,_ does it still go in "What's new", since it's new in dart.dev?

**Comment by parlough** [comment]
> I'm not sure how this usually goes, maybe @parlough you can lmk, or maybe sfshaza2 you might know what the practice was: 
> 
> 
> 
> We added a kind-of-big update/[new Effective Dart entry](https://github.com/dart-lang/site-www/pull/4423) _during the 2.19 window of time_. 
> 
> 
> 
> Even though it had nothing to do with 2.19 _development,_ does it still go in "What's new", since it's new in dart.dev? 

Currently we use the page for what is new on the site, it doesn't necessarily have to be tied to the release. We could perhaps make that more clear with a slightly more specific page title.

**Comment by sfshaza2** [comment]
Yes, Parker is right. It is ENTIRELY to update folks on changes to the
site. I started this practice on flutter.dev and Kathy eventually (much
later) adopted it on dart.dev. I even say that "this section shows what's
new on the site since the last release."

**Comment by MaryaBelanger** [comment]
Two PRs:
- #4542 
- #4544
