### ISSUE TITLE
Add .dart_tool to 'What Not to Commit' page

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#444]
From URL: https://www.dartlang.org/guides/libraries/private-files

cc @kevmoo @jakemac53 

We're likely going to be seeing more tools writing to `.dart_tool/` and we should start recommending that this directory is ignored.

**Comment by natebosch** [comment]
@kevmoo  - we could perhaps also add it to the default Dart .gitignore at https://github.com/github/gitignore/blob/master/Dart.gitignore

**Comment by chalin** [comment]
And update stagehand templates while we're at it?

**Comment by natebosch** [comment]
Good call, stagehand should include it too

**Comment by kevmoo** [comment]
We should be clear about the convention for `.dart_tool`, too. i.e. `.dart_tool/<pkg>/...`

Having an explicit call-out on www will give us a place to reference from `pkg/build` docs...

**Comment by devoncarew** [comment]
What is `.dart_tool/`? The scratch directory for `package:build`?

We already have a fair number of git ignored and or temporary file entities created by dart tooling (`.pub/`, `build/`, `.packages`). We may want to unify or simplify them a bit at this point.

**Comment by kevmoo** [comment]
`.dart_tool` was supposed to be "the place" for any package to put things in

`.dart_tool/<pkg_name>`

**Comment by devoncarew** [comment]
And the package would decide on the lifecycle for the contents for `.dart_tool/foo`? So a build tool might blow it away frequently, and a package management tool might keep the contents for a while?

What about just `.dart/<pkg_name>` then? `.tools/<pkg_name>`? `.pkg/<pkg_name>`?

Having a centralized convention + location sounds great.

**Comment by kevmoo** [comment]
Ha! We should have talked when we created `.dart_tool`.

I'd rather not switch it around now...

**Comment by devoncarew** [comment]
I've not seen the directory or heard of the convention to date, so I don't think there's a large numbers of existing uses to switch around -

**Comment by natebosch** [comment]
FWIW I prefer `.dart_tool/` over the proposed alternatives.

`.tool/` could be other development related stuff. `.pkg/` is too much like the old `packages/` but serves an entirely different purpose. `.dart/` is OK but I like the extra clarity of including the word  "tool".

I would be in favor of moving `.pub` to `.dart_tool/pub`
