### ISSUE TITLE
I am working on translating the dart.dev website into Korean.

### ISSUE THREAD

**Issue by Coaspe** [dart-lang/site-www#4476]
### Page URL

https://dart-ko.dev/

### Describe the problem

I am working on translating the dart.dev website into Korean. (https://dart-ko.dev/)
Can you Dart team add this URL to https://dart.dev/community#additional-community-resources?
Alternatively, can I make a pull request for this?

**Comment by parlough** [comment]
Your work on this is super appreciated! Feel free to make a pull request and I can review it :)
