### ISSUE TITLE
Style doc on super-goes-last is missing?

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#45]
_From @vsmenon on March 29, 2016 16:59_

We used to recommend placing `super` last in the initializer list.  I don't see that in the style guide any more.

The linter references the original text:

https://github.com/dart-lang/linter/blob/master/lib/src/rules/super_goes_last.dart

@munificent @pq 

_Copied from original issue: dart-lang/www.dartlang.org#1563_

**Comment by Sfshaza** [comment]
_From @pq on April 6, 2016 18:17_

Interesting.  Maybe this is stale advice?  Paging @munificent!

**Comment by Sfshaza** [comment]
_From @munificent on April 6, 2016 19:41_

No, the advice is still good. Even more important now since DDC requires it.

It just got lost when I reorganized the style guide into Effective Dart.

**Comment by Sfshaza** [comment]
This text is here:
https://www.dartlang.org/guides/language/effective-dart/usage#do-place-the-super-call-last-in-a-constructor-initialization-list

Closing.

**Comment by munificent** [comment]
Thanks!

**Comment by pq** [comment]
\o/
