### ISSUE TITLE
Is this unpaired bracket a typo?

### ISSUE THREAD

**Issue by Coaspe** [dart-lang/site-www#4508]
### Page URL

https://dart.dev/guides/language/concurrency

### Page source

https://github.com/dart-lang/site-www/blob/main/src/_guides/language/concurrency/index.md

### Describe the problem

<img width="171" alt="image" src="https://user-images.githubusercontent.com/76432686/212189178-e8bfcb36-8118-4d39-bc2f-8a1c0fb8a1d3.png">

I found unpaired bracket in [concurrency/index.md](https://github.com/dart-lang/site-www/blob/main/src/_guides/language/concurrency/index.md).

**Comment by parlough** [comment]
That is a typo, thanks. While checking it out, I also realized the style was incorrectly applied to all images on the site when it should only be applied to the article content. 

I've opened a PR with a fix for both issues in https://github.com/dart-lang/site-www/pull/4509. Thanks again for pointing that out!
