### ISSUE TITLE
[PAGE ISSUE]: 'Automated publishing of packages to pub.dev'

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/site-www#4530]
### Page URL

https://dart.dev/tools/pub/automated-publishing.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/pub/automated-publishing.md

### Describe the problem

Some of the formatting and images aren't rendering correctly.

If you search for `!Configuration of publishing from GitHub Actions on pub.dev` on the page, you'll see that text, but I believe that's intended to be an in-line image.

And in that same area, I see `{% raw %}{{version}}{% raw %}`, but I believe that's intended to in-line some value? render something as code?

**Comment by parlough** [comment]
Thanks, I'm working on other cleanup and fixes for this page now, and I'll make sure these get fixed too.
