### ISSUE TITLE
[2.19] More `pub` (maybe)

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4533]
## This is an _evaluation_ issue

Evaluating the _potential_ need for documentation updates based on pub related items added to the change log late in the release cycle (bullets below)

### Summary
The major points are being covered by 4514. This issue is just to make sure I double check dart.dev for everything else, though it's unlikely there's any significant change.

### Evaluation

- `dart pub add foo:<constraint>` with an existing dependency will now update the constraint rather than fail.
  - in work: #4514 
- `dart pub add` will now allow adding multiple packages from any source using the same YAML syntax as in `pubspec.yaml`.
  - in work: #4514

- Update `dart pub publish` to allow `dependency_overrides` in `pubspec.yaml`. They will still cause a publication warning. Note that only `dependency_overrides` from the root package effect resolution.

- Update `dart pub publish` to require a working resolution. If publishing a breaking release of mutually dependent packages use `dependency_overrides` to obtain a resolution.

- `dart pub publish` will now give a warning if `dart analyze` reports any diagnostics.

- `dart pub publish` now shows the file sizes of large files in your package to prevent accidental publication of large unrelated files.

- Fix a bug in `dart pub upgrade --major-versions` where packages not requiring major updates would be held back unless needed.

- `dart pub get` now fails gracefully when run from inside the pub-cache

**Comment by MaryaBelanger** [comment]
I didn't find anywhere in the docs that these points would be valuable to elaborate on. 

The changes related to warnings and failures sufficiently sum up what's going on in their messages, so there doesn't need to be extra documentation to explain those. 

E.g. for "`dart pub get` now fails gracefully when run from inside the pub-cache", the message the user will see is "[Cannot operate on packages inside the cache.](https://dart.googlesource.com/pub.git/+/e2720c27/lib/src/entrypoint.dart#229)", kind of obvious to just get out of the cache to fix it. 

_**Side note for future me:**_
This was the first time digging into pub developments that don't have corresponding issues in GH. I only found out about these changes from the change log, and none of them are linked to anything for more explanation. 

It took me a while to figure out how to backtrack from the change log to find a source for more info. It seems simple now, but just in case, I'm writing it down for next time. Here's what to do:
- Go to the [change log blame](https://github.com/dart-lang/sdk/blame/master/CHANGELOG.md)
- Click on the commit adjacent to the change log update
  - e.g. [this one](https://github.com/dart-lang/sdk/blame/master/CHANGELOG.md#L458) for the `publish` / `analyze` thing
  - takes you [here](https://github.com/dart-lang/sdk/commit/250db68e251f44cfb057ce9754c5340681b00043)
- Read the commit messages in the log on that page to find what you're looking for (e.g. [this line highlighted](https://github.com/dart-lang/sdk/commit/250db68e251f44cfb057ce9754c5340681b00043#:~:text=Warn%20on%20%60pub%20publish%60%20if%20%60dart%20analyze%60%20has%20messages)) ** _(or skip to last bullet)_
  - click on the `dart.googlesource...` link to the right of the log entry
  - _not_ the issue number link on the left, those seem to be unrelated? I'm not sure (e.g. [this one](https://github.com/dart-lang/sdk/issues/3568) isn't about `publish`?)
  - that will bring you to a page that [lists all the files that were changed](https://dart.googlesource.com/pub.git/+/c287c110#:~:text=lib/src/log.dart%5B,dependency_test.dart%5Bdiff%5D) at the top
  - you can click through the files and ctrl+f search for the info you're looking for
- ** _If none of those messages seem related to what you're looking for,_ just click on the long [`Diff:` link](https://github.com/dart-lang/sdk/commit/250db68e251f44cfb057ce9754c5340681b00043#:~:text=Diff%3A%20https%3A//dart.googlesource.com/pub.git/%2B/28a2503d7f4806e6854e3ed0d783f065abfd1b5f~..817e61d9eb174f77dfd2cb1d1de45826f66ac6bf/) below them and that'll show you all the changes
  - [in the diff](https://dart.googlesource.com/pub.git/+/28a2503d7f4806e6854e3ed0d783f065abfd1b5f~..817e61d9eb174f77dfd2cb1d1de45826f66ac6bf/) just ctrl+f phrases for what you're looking for
  - I searched "analyze" and found `validator/analyze.dart` file had the work I was looking for

**Comment by parlough** [comment]
@MaryaBelanger Thanks for completing this evaluation, and everything makes sense.

As for your process, sounds like you found one that works well for you :D

My personal process for pub is similar to the following if it helps:

_Pretend I want to compare what is on the current stable (2.19.0) to current dev/alpha (3.0.0-<v>-dev):_

1. Open the base (stable) branch DEPS file: https://github.com/dart-lang/sdk/blob/stable/DEPS
2. Find the `pub_rev` in there: https://github.com/dart-lang/sdk/blob/stable/DEPS#L155
3. Open the target branch (`dev`) DEPS file: https://github.com/dart-lang/sdk/blob/dev/DEPS
4. Find the `pub_rev` in there: https://github.com/dart-lang/sdk/blob/dev/DEPS#L159
5. Create a GitHub compare link between the two commits:
6. https://github.com/dart-lang/pub/compare/<base>...<target>
7. For example, current stable to dev: https://github.com/dart-lang/pub/compare/9f41ae10d22071f825eee0f0e128e6854ba2adb5...0cbaf7a2fb8c8ca543c6f222bf25d5f5c63abbf3

**Comment by MaryaBelanger** [comment]
@parlough 😱 I'm speechless! I think you've mentioned this method to me before, but seeing how simple it is (and assuming it's applicable to all the development that goes into Dart), is really a game changer. We'll have to talk more about this offline!

**Comment by parlough** [comment]
There are a few situations where that won't always work, but we can talk more about those offline :)
