### ISSUE TITLE
[PAGE ISSUE]: 'Write command-line apps'

### ISSUE THREAD

**Issue by Rod4ech** [dart-lang/site-www#4555]
### Page URL

https://dart.dev/tutorials/server/cmdline

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_tutorials/server/cmdline.md

### Describe the problem

On the "Overview of the dcat app code" section
In line:
dcat(paths, showLineNumbers: argResults[lineNumber] as bool);

The following error appears:
The name 'dcat' refers to an import prefix, so it must be followed by '.'.
Try correcting the name to refer to something other than a prefix, or renaming the prefix.dart[prefix_identifier_not_followed_by_dot](https://dart.dev/diagnostics/prefix_identifier_not_followed_by_dot)

I have not been able to correct the issue and I am unsure if I am doing something wrong. 
Please advice.
Thanks

### Expected fix

Just to fix the code or provide guidance on how to successfully carry on.

### Additional context

Also the following line is impacted (I am guessing part of the same problem).
Future<void> dcat(List<String> paths, {bool showLineNumbers = false}) async {

Error shown:
The name 'dcat' is already used as an import prefix and can't be used to name a top-level element.
Try renaming either the top-level element or the prefix.dart[prefix_collides_with_top_level_member](https://dart.dev/diagnostics/prefix_collides_with_top_level_member)

**Comment by danagbemava-nc** [comment]
Hi @Rod4ech, in what file do you see the error? 

Kindly share what your project structure looks like and the code you have so far.

**Comment by parlough** [comment]
Hi @Rod4ech, thanks for opening an issue!

This diagnostic usually means you have an import such as `import 'something.dart' as dcat` near the top of your file but the example in this tutorial doesn't have that. If you are able to include the code you have locally, we'd be able to help you fix it. Thanks so much!

**Comment by Rod4ech** [comment]
Thanks @parlough and @danagbemava-nc for your quick responses.
Please see the full code that I am running on my Visual Studio Code editor. 
I have followed the instructions on [https://dart.dev/tutorials/server/cmdline].

The project structure is:
![image](https://user-images.githubusercontent.com/54581015/215624528-a353bcc2-e959-4267-b743-dfc40f2e9724.png)

The error shown:
![image](https://user-images.githubusercontent.com/54581015/215624702-183824d3-ea6b-476c-9f8e-9f38d2e579c0.png)

And the full dart code of the file:
import 'package:dcat/dcat.dart' as dcat;
import 'dart:convert';
import 'dart:io';

import 'package:args/args.dart';

const lineNumber = 'line-number';

void main(List<String> arguments) {
  exitCode = 0; // presume success
  final parser = ArgParser()..addFlag(lineNumber, negatable: false, abbr: 'n');

  ArgResults argResults = parser.parse(arguments);
  final paths = argResults.rest;

  dcat(paths, showLineNumbers: argResults[lineNumber] as bool);
}

Future<void> dcat(List<String> paths, {bool showLineNumbers = false}) async {
  if (paths.isEmpty) {
    // No files provided as arguments. Read from stdin and print each line.
    await stdin.pipe(stdout);
  } else {
    for (final path in paths) {
      var lineNumber = 1;
      final lines = utf8.decoder
          .bind(File(path).openRead())
          .transform(const LineSplitter());
      try {
        await for (final line in lines) {
          if (showLineNumbers) {
            stdout.write('${lineNumber++} ');
          }
          stdout.writeln(line);
        }
      } catch (_) {
        await _handleError(path);
      }
    }
  }
}

Future<void> _handleError(String path) async {
  if (await FileSystemEntity.isDirectory(path)) {
    stderr.writeln('error: $path is a directory');
  } else {
    exitCode = 2;
  }
}

Thanks!

**Comment by parlough** [comment]
@Rod4ech Thanks for the context! Try removing the first line. I think it is left over from the file `dart create` made for you, but will cause the import prefix (`as dcat`) to conflict with the function `dcat`.

**Comment by Rod4ech** [comment]
Thanks @parlough
Yes, you are right. Once that line is removed, the program runs smoothly. 
Cheers!
