### ISSUE TITLE
Critical: Broken CSS

### ISSUE THREAD

**Issue by passsy** [dart-lang/site-www#456]
The website is currently unusable

<img width="400" alt="screen shot 2017-12-04 at 22 39 46" src="https://user-images.githubusercontent.com/1096485/33577709-31abe702-d944-11e7-8891-f43bfe9e6700.png">

**Comment by chalin** [comment]
The site looks fine when I load it.
Can you empty your browser cache and reload to see if the problem persists?

**Comment by chalin** [comment]
Which browser and OS are you using?

**Comment by chalin** [comment]
I'm not seeing the problems that you report. I've tried Safari and Chrome (on both desktop and mobile iOS and Android).

**Comment by passsy** [comment]
Tried it in Chrome and Safari on macOS. Same on Android
￼

**Comment by chalin** [comment]
Thanks for checking.

At the bottom of site pages, you'll see a tool icon:
> <img width="164" alt="screen shot 2017-12-04 at 18 31 11" src="https://user-images.githubusercontent.com/4140793/33582068-6713b3fc-d921-11e7-839e-f9c75ff1d9e6.png">

If you hover over the tool icon, what build info do you see? I see
**`Site built on 2017/12/04 19:18 UTC`**.

**Comment by passsy** [comment]
It says `Site built on 2017/12/04 19:18 UTC`
<img width="268" alt="xfd0favdeg" src="https://user-images.githubusercontent.com/1096485/33582187-52c1320c-d954-11e7-91bd-eef5b79995d2.png">

**Comment by chalin** [comment]
Wow, same build! How strange. I'll rebuild and redeploy to see if that helps.

cc @kwalrath @kevmoo

**Comment by chalin** [comment]
@passsy, I've forced a rebuild and redeploy of the site. Could you please try reloading it again, and then let me know what the build information is? Thanks.

**Comment by passsy** [comment]
Chrome and Safari are working now with `Site built on 2017/12/04 23:40 UTC`.
I still get the error on Android in Chrome.

**Comment by passsy** [comment]
Error is gone on Chrome in Android as well.

**Comment by chalin** [comment]
Thanks again for having reported this. We'll try to get to the root cause.

**Comment by kwalrath** [comment]
This seems to be a CDN issue. A workaround is to purge the URL in your region:

```
curl -X PURGE <URL you want>
```
