### ISSUE TITLE
Remove mention of missing function in 'Iterable collections'

### ISSUE THREAD

**Issue by DemX86** [dart-lang/site-www#4570]
### Page URL

https://dart.dev/codelabs/iterables#example-using-firstwhere

### Page source

https://github.com/dart-lang/site-www/tree/main/src/codelabs/iterables.md

### Describe the problem

> In the example, `firstWhereWithOrElse()` calls…

There is no `firstWhereWithOrElse()` function in the example from above.

### Expected fix

Remove the function name mention

**Comment by danagbemava-nc** [comment]
I believe that message is referring to 

```dart
  var foundItem4 = items.firstWhere(
    (item) => item.length > 10,
    orElse: () => 'None!',
  );
```

but I can see why the phrasing can be confusing

**Comment by atsansone** [comment]
This issue no longer exists in the specified page. Closing.

![image](https://user-images.githubusercontent.com/706219/230208401-b315f384-cda4-4c43-8510-c741089ab604.png)

**Comment by parlough** [comment]
Yep, fixed by https://github.com/dart-lang/site-www/commit/e749e83d5e11274e949a896cfe5af5912aa2f27d!
