### ISSUE TITLE
Upcoming deprecations

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4585]
[Changelog 3.0](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#300---2023-05-10)

**Comment by atsansone** [comment]
@MaryaBelanger : Can you add any detail to this issue?

**Comment by MaryaBelanger** [comment]
I opened this as a place holder, but did not get around to checking on them. I believe others have been updating minor deprecation mentions gradually, so there might be nothing left to fix. 

What I would still like to do is just what I did for the last release: comb through the changelog for any mention of any deprecations, then search the site for any mention of the deprecated item. 

Since these are usually API deprecations, and dart.dev doesn't get into specific APIs too much, there's probably not much to fix, but I like the peach of mind from checking anyway!
