### ISSUE TITLE
Linter should not be referred to as a 'plugin'

### ISSUE THREAD

**Issue by srawlins** [dart-lang/site-www#4595]
### Page URL

https://dart.dev/guides/language/analysis-options

### Describe the problem

The text currently reads:

> You can also configure the linter, one of the analyzer’s plugins, to ensure that your code [...]

Since 'plugin' has a specific meaning in terms of the analyzer, and the linter is _not_ an analyzer plugin, we should use a different term. We will start using the term 'plugin' as part of https://github.com/dart-lang/site-www/issues/2013.

### Expected fix

So what word should we use? CC @bwilkerson @pq for thoughts. In many aspects we don't want to burden the users with any unnecessary distinction between the linter and the analyzer, but (for now) they are configured in different top-level sections (`analyzer:` vs `linter:`), so maybe it's best to keep the mention and just rewrite to avoid the word 'plugin'. Maybe "You can also configure linter rules, to ensure your code [...]" or similar...

**Comment by srawlins** [comment]
I'm happy to mail a PR if we land on some good text. :)

**Comment by bwilkerson** [comment]
I'm happy with your suggestion of "configure linter rules".

**Comment by parlough** [comment]
I like that too :)

**Comment by srawlins** [comment]
Other outdated text in this paragraph:

> Dart tools such as the
[Dart compiler (`dart compile`)](/tools/dart-compile),
[`dart analyze`](/tools/dart-analyze),
[`flutter analyze`]({{site.flutter-docs}}/testing/debugging#the-dart-analyzer),
and [JetBrains IDEs](/tools/jetbrains-plugin)
use the analyzer package to evaluate your code.

* I don't think `dart compile` in any way uses `analysis_options.yaml`.
* JetBrains IDEs? Er... let's update that.
