### ISSUE TITLE
Talk about package:resource

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#46]
_From @kwalrath on February 11, 2016 18:24_

It seems like [package:resource](https://pub.dartlang.org/packages/resource) might be the general purpose way to go for reading data from your own package (and/or other packages?). If so, we should cover it on www.dartlang.org. More info: https://github.com/dart-lang/resource

_Copied from original issue: dart-lang/www.dartlang.org#1550_

**Comment by kwalrath** [comment]
Should we cover this in https://www.dartlang.org/guides/libraries/useful-libraries? A quick look at https://pub.dartlang.org/packages/resource shows that 11 public packages depend on package:resource, and that it has a [score of 85](https://pub.dartlang.org/packages/resource#-analysis-tab-), with dings for popularity, a too-short description, and no example.

With a little work on the description & example, plus a link from dartlang.org, might this package be more popular?

/cc @kevmoo @lrhn

**Comment by lrhn** [comment]
I'd like to make a version 2 (3?) of it first that uses configured imports to avoid the `dart:io` dependency on non-IO-supporting platforms.
I used to have a CL for that, but it's been old for a while. I can look into it if I find the time.

**Comment by kevmoo** [comment]
pkg:resource is not super interesting for most users, I guess. I wouldn't
make it a top priority.

**Comment by parlough** [comment]
This package has now been deprecated due to the following reasoning:

> This package combines two functionalities:
> 
> Converting a package: URI to a platform specific URI (usually http: or file:, depending on the platform)
> Load the contents of such platform specific URIs.
> The former no longer makes sense when a large number of Dart programs are ahead-of-time compiled. Those programs do not have access to source files at runtime, and a package: URI references a source file. There is no standard way to find a runtime location of a source file, or even ensure that it is available.
> 
> The platform specific loading functionality can still be useful. However, without a way to produce such platform specific URIs from platform independent ones, the only URIs which can still be loaded on all platforms are http:/https: ones. Loading those is better supported by the http package.
> 
> As such, this package can no longer supports its original goal, being a cross platform resource loading solution. It will be discontinued rather than provide an inadequate solution.

As such our documentation around `dart:io` and `package:http` should be sufficient.
