### ISSUE TITLE
Remove the "Modify PATH for access to all Dart binaries" section to simplify the installation in 'Get the Dart SDK' Linux page

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#4609]
### Page URL

https://dart.dev/get-dart/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/get-dart/index.md

### Describe the problem

I think the Dart Linux installation instructions may be more complex than necessary. On my machine, installing Dart through `apt` automatically added a symbolic link to the `/usr/bin` directory:
 
```
tims@penguin:~$ ls -al /usr/bin/dart
lrwxrwxrwx 1 root root 20 Feb  7 10:57 /usr/bin/dart -> ../lib/dart/bin/dart
```

As a result, the exhortation to add `/usr/lib/dart` to the search path (the "Modify PATH for access to all Dart binaries" section) seems redundant.

It was probably useful in the past when Dart had a number of different CLI utilities, but now they have been unified into a single `dart` tool, the symlink should be sufficient.

### Expected fix

Remove the "Modify PATH for access to all Dart binaries" section to simplify the installation instructions.

### Additional context

/cc @mit-mit for validation that I'm right here :)

**Comment by parlough** [comment]
The [`dartaotruntime`](https://dart.dev/tools/dartaotruntime) tool is still bundled separately from the main `dart` executable, so I'm not sure we can remove the extra mention yet.

**Comment by timsneath** [comment]
Yeah, that's the only command left (and it's a fairly esoteric one). I'm not sure what the plan is there. (We could add a symlink for that if it's going to stay around.)

(BTW, https://github.com/dart-lang/sdk/issues/49293 is a related issue that demonstrates that the current status quo is confusing even with the documentation.)

**Comment by parlough** [comment]
If the command will stick around, adding the symlink would be great.

In the mean time, since there is only extra command that needs this, we can likely be more specific in the instructions on when/why this step is needed.

**Comment by mit-mit** [comment]
`dartaotruntime` is a very specialized command for those that want to create systems with the smallest possible footprint (it allows for sharing the runtime among several AOT snapshots). It really doesn't need to ever be in path. Those few that need it, know what to do with it.

Updating the steps to omit the path part SGTM
