### ISSUE TITLE
☂ [Tracking] Refactor "Core libraries" umbrella topic

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4610]
I think the Library tour should be unpacked under the "Core libraries" umbrella in the side nav, similar to how the [language tour is being unpacked](https://github.com/dart-lang/site-www/issues/4588).

> Libraries
> - Overview
> - Libraries and visibility _(from the language tour)_
> - dart:core
> - dart:async
> - dart:math
> - dart:convert
> - dart:html
> - dart:io

**Comment by parlough** [comment]
I think **Libraries and visibility** needs to remain in the language tour as it is more about the language functionality of libraries which is important to consider when writing any code with Dart. If anything we need to expand on the concept a little.

**Comment by parlough** [comment]
> @MaryaBelanger I think **Libraries and visibility** needs to remain in the language tour as it is more about the language functionality of libraries which is important to consider when writing any code with Dart. If anything we need to expand on the concept a little and do it much earlier. A lot of code in the tour imports other libraries but we never talk about what it means until way later.

**Comment by MaryaBelanger** [comment]
@parlough I wasn't too sure about that move, so thanks for your input. I'll move it back in #4612

**Comment by mit-mit** [comment]
SGTM!

**Comment by parlough** [comment]
After recent offline discussion, I'm moving this to p2 as finishing this move would simplify future library-related work :)

**Comment by MaryaBelanger** [comment]
Linking #5175 -- once the tour is deconstructed, we can fit the updated page under it's corresponding library's section

**Comment by parlough** [comment]
Thanks for adding that! If you plan to just hammer this out, I'll be happy to review it. It shouldn't interfere too much with my migration work, and might actually help it :)
