### ISSUE TITLE
Standard for spaces in adjacent strings split across multiple lines?

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4615]
I'm curious where people place the space when breaking up long strings across lines with adjacent strings. Do you place the space at the end of the first line/string or at the beginning of the next one?

I've seen this situation become more common with [`package:dart_flutter_team_lints`](https://pub.dev/packages/dart_flutter_team_lints) having the [`lines_longer_than_80_chars`](https://dart.dev/tools/linter-rules#lines_longer_than_80_chars) linter rule enabled.

**Previous line:**
```dart
final instructions = 'This file is generated from other files. '
    'To re-generate it, please run `dart run build_runner build` command '
    'from root of the project.';
```

**Next line:**
```dart
final instructions = 'This file is generated from other files.'
    ' To re-generate it, please run `dart run build_runner build` command'
    ' from root of the project.';
```
      
I'm just looking for a standard we can follow in documentation and maybe even projects (through a lint?) if a standard makes sense and is agreed upon.

**Comment by parlough** [comment]
\cc @devoncarew @kevmoo Do you have a personal standard? You've been adding this lint to a lot of projects recently, so I wonder what you've come across or defaulted to.

**Comment by devoncarew** [comment]
I always put the continuation bit on the end, so:

```
  'This file is generated from other files. '
  'To re-generate it, please run `dart run build_runner build` command '
  'from root of the project.'
```

but that's a habit of mine - I don't know that there are any real conventions or style guidance here -

**Comment by parlough** [comment]
Yeah I've had this habit too, but I've noticed a mix and heard about both. Thanks for sharing.

**Comment by kevmoo** [comment]
I do prety much what @devoncarew does

**Comment by atsansone** [comment]
That's what I've seen most IDEs that introduce hard breaks for multiline text blocks do. Consider end of line space to be correct.

**Comment by atsansone** [comment]
Add space at the end of line. Closing this issue as fixed.
