### ISSUE TITLE
Create site-wide "Glossary"

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4622]
### Summary

dart.dev needs a resource for definitions of frequently used terminology. In many cases, it doesn't make sense to define a term in the context it's being mentioned in, because it's derailing or doesn't fit the purpose of that doc. Content like what we have in the language tour faces this issue a lot, since it usually conveys simplified and straightforward "quickstart" types of information per topic; definitions of peripheral terms don't have a place. 

This is why the diagnostics page has it's own glossary section, because many of it's messages need to refer to terms that they don't have the space to define in a diagnostic message (nor should they have to do so, the purpose of a diagnostic message doesn't lend to defining every term inline). 

This is coming up now because there are new Dart 3 terms the diagnostic messages need defined and linked to in the main docs. 

### Evaluation

1. The new page will go under Resources >.Glossary

2. The contents of the Glossary section of the diagnostic messages page will be removed from that page and be the basis of the new Glossary page.

3. Over time, more terminology will be added to the new Glossary page, so other pages can link to its definitions. New Dart 3 definitions will be placed there.

4. The goal is that anywhere in the docs where a user can benefit from having the definition of a term handy, we will add links on the terms to the glossary.

5. A concern is that the glossary might become a dumping ground for information that should really be covered elsewhere in the documentation. Every new entry in the glossary needs to be heavily scrutinized to ensure
    - It's truly just a _definition_, not a full blown reference or example
    - There isn't a better existing location for that information. 

6. Need to go through the diagnostic messages (`analyzer/tool/diagnostics/generate.dart`) and add links to the new page anywhere one of the terms currently in the diagnostics glossary is used, so that the diagnostic messages page doesn't suffer from not having the definitions on the same page anymore

#### TBD

7. The Packages section has its own fully-formed, very involved, glossary. Currently I don't have any plans to remove that content from the packages section and incorporate it into the new glossary, but that might make sense in the future.

8. (stretch) @parlough has an idea to develop some tooling where you can hover over a word in the docs that's linked to a definition in the glossary, and a small window/blurb will open over the word showing it's definition, plus a link to it in the glossary in case the full definition is too long for the tiny pop up.  

### References

- [the diagnostic messages glossary](https://dart.dev/tools/diagnostic-messages#glossary)
- [the package content's glossary](https://dart.dev/tools/pub/glossary)

### Related/ToDo

- [x] https://github.com/dart-lang/site-www/pull/4954#discussion_r1218596841 - update the link to the `part` glossary entry once it's on the new page.

**Comment by MaryaBelanger** [comment]
Found this old glossary entry issue:
https://github.com/dart-lang/site-www/issues/3602

**Comment by MaryaBelanger** [comment]
@bwilkerson I am going to start "moving" the glossary off of the `diagnostics.md` page and to the new `glossary.md` page. 

The note at the top of `diagnostics.md` says "WARNING: Do NOT EDIT this file directly." because it's autogenerated, but it says that both in the copy on [site-www](https://github.com/dart-lang/site-www/blob/a3dca27daec08dc05a50c25f8315c5cda328375e/src/tools/diagnostic-messages.md#L6) and the copy in the [sdk](https://github.com/dart-lang/sdk/blob/24f262de2ae1f587ec3705da5540e592a9b699f8/pkg/analyzer/tool/diagnostics/diagnostics.md#L6). 

**Question:** I know the glossary section of the page isn't autogenerated from `messages.yaml,` so to edit that part, do I do so in `sdk/.../diagnostics.md` or `site-www/.../diagnostics.md`? The edit will be to remove the section, so I'm hoping I can do that in the sdk while simultaneously updating `messages.yaml` to the new links in site-www in the same CL.

**Comment by bwilkerson** [comment]
The glossary entries are actually in the generator itself, not in the `messages.yaml` files. See [https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/tool/diagnostics/generate.dart#L226](https://www.google.com/url?q=https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/tool/diagnostics/generate.dart%23L226&sa=D&source=docs&ust=1686845057325068&usg=AOvVaw1lAKXU8-0EWs6EDBOld-a7).

**Comment by atsansone** [comment]
@MaryaBelanger : There is a [glossary page](https://dart.dev/resources/glossary). Does this issue need to be reframed?

**Comment by MaryaBelanger** [comment]
@atsansone Yes and no... I kind of consider this a tracking issue, but that's debatable. Here's what's going on and I'll let you decide if we should close this or not (Evaluation section points):

1. Done, the page in your comment
2. In progress now as part of the diagnostic restructure: https://github.com/dart-lang/site-www/issues/5054#event-9777670067
3. Not really completable, shouldn't affect keeping this open
4. Same as 3
5. Same as 3
6. Also part of #5054, same as 2
7. The TBDs: not planned, wouldn't happen for a while anyway.

There's a couple ToDos for adding specific entries in this thread as well. I guess I'd like to leave this open until I do those, plus complete point 2/6 from the original plan.
