### ISSUE TITLE
[Infra] Symlinks are not resolved on Windows which breaks the building

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/site-www#4631]
### Describe the problem

There are many symbolic links in the repo. This makes it hard to build the site on Windows.
* When cloning the repo, Windows cannot recognize how to resolve them even with `core.symlinks` enabled.
* When building the site in Docker for Windows, `jekyll` cannot recognize a symbolic link created by Windows, which causes build failures.

### Expected fix

Remove symlinks as much as possible.

**Comment by parlough** [comment]
Is this within a WSL environment?

**Comment by AlexV525** [comment]
> Is this within a WSL environment?

I don't think so, the repo was cloned under Windows, and the Docker has enabled the WSL integration, but the preparation seems still outside of WSL.

**Comment by parlough** [comment]
I see. I'm not sure Windows outside of WSL is something we will aim to support with our current setup, so I recommend running everything from within WSL too, not just the docker integration. Always happy to take PRs which make things easier though.
