### ISSUE TITLE
Move language evolution page back into Language menu

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/site-www#4634]
### Page URL

https://dart.dev/guides/language/evolution

### Describe the problem

This page was moved out from under Language in https://github.com/dart-lang/site-www/pull/4604#event-8605531693

We're already seeing a drop in page views. This is a problem, as this page is critical in explaning the vibrancy of the Dart language.

### Expected fix

Please move it back.

The original argument was _"...but doesn't accomplish anything for readers as a stand alone document."_ I disagree with that. It does serve a very clear purpose, which is to explain the evolution of the language. I also don't see how the placement as the last node under Language could possible hurt?

**Comment by MaryaBelanger** [comment]
Will do, page views come first!
