### ISSUE TITLE
Change link for interface on 'Keywords' page

### ISSUE THREAD

**Issue by eernstg** [dart-lang/site-www#4662]
### Page URL

https://dart.dev/language/keywords.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/keywords.md

### Describe the problem

The new [_class modifiers_](https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md) feature which is about to be added to Dart will introduce the built-in identifier `interface` as a part of Dart source code (until now it has been unused, but it was still classified as a built-in identifier).

The 'Keywords' page shows `interface` as a built-in identifier (as it should), but it is linked to a section about 'implicit interfaces', which is misleading now.

### Expected fix

`interface` is going to be a class modifier such that `interface class C ...` declares a class where subtypes can be declared using `class D implements C {}` and `mixin M on C {}`, but not `class D extends C {}` (at least not in a different library). The link might actually just refer to the feature specification, https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md, or it could refer to a new section about class modifiers.

### Additional context

Thanks to @e1b916a3 for reporting this in https://github.com/dart-lang/sdk/issues/51728.

**Comment by MaryaBelanger** [comment]
Thanks @eernstg, i'll fold this into the class modifiers PR I'm working on. Added to the Dart 3 project under Class modifiers to ensure it's handled
