### ISSUE TITLE
Add tests for `hello_world_server_secure.dart`

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#468]
Followup to #463.

Add/complete tests for [hello_world_server_secure.dart](https://www.dartlang.org/tutorials/dart-vm/httpserver#using-https-with-bindsecure).

The current test (which is being skipped) results in:

>  HandshakeException: Handshake error in client (OS Error:  CERTIFICATE_VERIFY_FAILED: ok(ssl_cert.c:345))

Waiting on https://github.com/dart-lang/sdk/issues/24184.

**Comment by parlough** [comment]
Closing this as this particular example has been removed in preparation for an eventual rewrite of the page: https://github.com/dart-lang/site-www/pull/3230
