### ISSUE TITLE
[PAGE ISSUE]: 'Linter rules'

### ISSUE THREAD

**Issue by fedexperez** [dart-lang/site-www#4682]
### Page URL

https://dart.dev/tools/linter-rules.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/linter-rules.md

### Describe the problem

In the Style rules, the prefer_collection_literals says that is preferred to use collection literals when possible, but the example show the opposite 
![Screenshot 2023-03-16 at 10 48 34 AM](https://user-images.githubusercontent.com/70544976/225677178-6a14f006-6c19-445f-9a04-3967c298d6d9.png)

### Expected fix

Change the information from Good section and put it into the Bad section and viceversa 

### Additional context

The rule is here for more easy access https://dart.dev/tools/linter-rules#prefer_collection_literals

**Comment by parlough** [comment]
Thanks for opening an issue! 

@fedexperez Could you clarify? From your picture and the site, the use of collection literals (as shown with the `<Type>{}`) is already in the **Good** section, while using the original constructors is shown in the **Bad** section.

**Comment by fedexperez** [comment]
@parlough i`m sorry for misunderstanding the documentation. Everything is alright with the linter rule.

**Comment by parlough** [comment]
All good, glad we could clarify and make sure the documentation is correct. Thanks so much!
