### ISSUE TITLE
"dart" brew-formula is not up-to-date, up-to-date - "dart-sdk"

### ISSUE THREAD

**Issue by AlexKenbo** [dart-lang/site-www#4683]
### Page URL

https://dart.dev/get-dart

### Describe the problem

"dart" brew-formula is not up-to-date, up-to-date - "dart-sdk"

### Expected fix

https://formulae.brew.sh/formula/dart-sdk

**Comment by parlough** [comment]
Hi, thanks for opening an issue! My understanding is that these built-in formulas are community-supported/third-party formulas. If you want to see updates to them, your best hope is on the [homebrew repositories](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

The Dart team hosts their own [tap](https://docs.brew.sh/Taps) at `dart-lang/dart`: https://github.com/dart-lang/homebrew-dart

You can learn more about using Dart's homebrew tap in the **macOS** tab on [Get Dart](https://dart.dev/get-dart) or on the tap's [GitHub page](https://github.com/dart-lang/homebrew-dart#initial-setup).

Let me know if you think anything specific still needs to be done :)

**Comment by atsansone** [comment]
The Dart team does not support the linked tap. It does support the one listed on the page that @parlough . As this falls outside our scope, closing this issue.
