### ISSUE TITLE
Update executables example

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#469]
https://www.dartlang.org/tools/pub/pubspec#executables uses a couple of polymer scripts as examples. We should update to something newer.

**Comment by kwalrath** [comment]
Yes, it is. Would you like to fix it, @MarcusXavierr?

**Comment by MarcusXavierr** [comment]
Hi @kwalrath, what exactly needs to be done?

**Comment by kwalrath** [comment]
The following code and the text that describes it need should be updated to use a more current (or maybe imaginary) example of an executable:

```
executables:
  polymer-new-element: new_element
  useful-script:
```

It'd be nice to find (or make up) a similar example that has 2+ executables, one with nothing after the `:`, and one with something. Doing a [quick search on pub.dev](https://pub.dev/dart/packages?q=tool&sort=popularity) I found dart_style, which (going to its repo and looking at its [pubspec.yaml](https://github.com/dart-lang/dart_style/blob/master/pubspec.yaml)) is close, but no cigar.

I think inventing a good example might be easier than finding one.

**Comment by MarcusXavierr** [comment]
Something like this?
```
executables:
    slidy: main
    fvm:
```
@kwalrath

**Comment by kwalrath** [comment]
@MarcusXavierr that LGTM

**Comment by woinbo** [comment]
Is this issue still open? Can I work on this issue, this will be my 1st open source contribution.

**Comment by kwalrath** [comment]
It looks like this was fixed in #2688. Thanks for asking!

**Comment by woinbo** [comment]
Hello @kwalrath, I want to contribute to the flutter and dart I'm not getting from where should I start can you guide me as this is going to be my 1st contribution. I'm working on flutter and dart for about 1 year.

Thank you

**Comment by kwalrath** [comment]
That's great! I'll look out for a bug for you — maybe part of #2617 — but in the meantime, if you notice any issues with a dart.dev page (small things like typos are easiest to start with), you can click the page (📄)  link at the upper right of the page, then edit the page using the GitHub UI.

**Comment by kwalrath** [comment]
@woinbo, I've assigned src/tools/dart-devtools.md (from #2617) to you. Does that work for you?

**Comment by woinbo** [comment]
Yup that's perfect for me , let me work on this issue. Thank you
