### ISSUE TITLE
[Release] Record-related extensions on future

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4692]
### Summary

Records allow multiple returns, so `Future` functionality extends to return multiple futures and maintain types of values (wip, still learning about it).

### Evaluation
WIP:
- Language content on `Future`: https://dart.dev/language/async#handling-futures
- Library content on `Future`: https://dart.dev/guides/libraries/library-tour#future
- Codelab, probably don't need to update: https://dart.dev/codelabs/async-await
- Maybe tie in to new [records](https://github.com/dart-lang/site-www/issues/4176) content as well

Technically dart 3 but probably doesn't need to be documented on the site immediately (unless you think otherwise @lrhn)

### Resources

- sdk tracking issue, there's multiple related core API additions : https://github.com/dart-lang/sdk/issues/49928
- https://dart-review.googlesource.com/c/sdk/+/288903

**Comment by parlough** [comment]
I was just making an issue as well :P. Thanks for tackling this!
