### ISSUE TITLE
Updates for using caret syntax in pubspec SDK constraint

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4693]
As of Dart 2.19, pub now doesn't block specifying the SDK constraint with the caret syntax. We should document it, modify our mention of recommending against it, and consider recommending/preferring it in certain locations.

Commit reference: https://github.com/dart-lang/pub/commit/06ab0148b6b320b4bfc69b0adba028dd745268ef.

**Comment by parlough** [comment]
`dart create` may use it as the default in the future too: https://dart-review.googlesource.com/c/sdk/+/289900

**Comment by parlough** [comment]
Currently planning to change this alongside Dart 3 or closer to Dart 3, but let me know if you think we should adjust the warning now.

**Comment by domesticmouse** [comment]
So totally lean into specifying SDK constraint with caret syntax!

**Comment by sigurdm** [comment]
> but let me know if you think we should adjust the warning now or not change to this syntax at all :)

I think this can be adjusted already now. (No specific urgency though).

**Comment by parlough** [comment]
Sounds good, I’ll make the adjustments then. Thanks!

**Comment by atsansone** [comment]
@parlough : Is this complete?

**Comment by parlough** [comment]
It's partially complete. I have some in-progress local work I can wrap up when I have a chance.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/605b86c52111dd530a7a0f64014e5d0a44fb8172

Will land into `main` with other Dart 3 changes soon.
