### ISSUE TITLE
[Dart 3] Document 'dart pub add' support for adding dependency overrides

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4695]
### Page URL

https://dart.dev/tools/pub/cmd/pub-add.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/pub/cmd/pub-add.md

### Describe the problem

In Dart 3,`dart pub add` is adding support for adding dependency overrides in a similar fashion to dev dependencies:

```
dart pub add pub add override:foo:1.0.0
```

### Expected fix

Document this new functionality.

**Comment by parlough** [comment]
Cool, thanks!

It should probably be relatively similar to the `dev:` section: https://dart.dev/tools/pub/cmd/pub-add#dev-dependency

However, this change won't be able to land on the `main` branch for a few months since we generally don't document unreleased features on the website and this feature won't land until at least the release of Dart 3. You should instead target the in-progress `v3.0` branch where we are including and tracking in-progress Dart 3 documentation.

Let me know if you have any questions. Thanks!

**Comment by shaikahmadnawaz** [comment]
Thanks for your guidance! I'll take a look at the dev: section and make sure to target the in-progress v3.0 branch for my contributions. If I have any questions, I'll let you know. Thanks again for your help!

**Comment by shaikahmadnawaz** [comment]
One small doubt, I forked this repo in my account, how can I clone v3.0 branch so that I will create new branch to that clone and complete the documentation, Will you please help me.

**Comment by parlough** [comment]
There are a few options:

1. This one is probably the easiest: Delete your fork and recreate it. When creating a fork there is a checkbox that says "Copy the `main` branch only". If you unselect it, your fork will have all of the upstream branches.

<img width="529" alt="Screenshot of copy main only checkbox" src="https://user-images.githubusercontent.com/18372958/228775456-22fdb321-4018-41c6-a4d1-33030f31288c.png">

2. Clone this repository (`dart-lang/site-www`) and the branch should be there. When you're done with your work, you can add your [fork as a remote repository](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#adding-a-remote-repository) and push to it.

3. If you're familiar with git, from your cloned fork you can [add a remote repository](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#adding-a-remote-repository) that points to `dart-lang/site-www` and fetch from there. I imagine it would look something like this:

```
git remote add upstream https://github.com/dart-lang/site-www
git fetch upstream
git checkout v3.0
```

**Comment by shaikahmadnawaz** [comment]
I've just submitted a pull request with my changes for the v3.0 branch. Could you please take a look at it and let me know your thoughts? I'd really appreciate your feedback.

Here's the link to the pull request: https://github.com/dart-lang/site-www/pull/4726

Thank you!

**Comment by parlough** [comment]
Fixed in https://github.com/dart-lang/site-www/pull/4726
