### ISSUE TITLE
Document pub's versioning rules more precisely

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#47]
_From @nicolasgarnier on August 26, 2014 17:18_

_From [rnystrom@google.com](https://code.google.com/u/rnystrom@google.com/) on August 08, 2014 17:48:14_

We have pretty good docs on how versions work in pub here: https://www.dartlang.org/tools/pub/dependencies.html#version-constraints But, since that doc was written, a few corner cases and changes have been made. They don't affect most users, but it would be good to write them down somewhere. In particular:
1. We use semver 2.0.0-rc.1, not 2.0.0 final. (Yes, the versioning system we use is itself versioned.) This means that build suffixes are ordered in pub. Personally, I think that's the only sane choice.
2. Our handling of < and <= constraints follows npm with respect to pre-release versions:

<1.2.3 Less than a specific version. If there is no prerelease tag on the version range, then no prerelease version will be allowed either, even though these are technically "less than".

> =1.2.3 Greater than or equal to. Note that prerelease versions are NOT equal to their "normal" equivalents, so 1.2.3-beta will not satisfy this range, but 2.3.0-beta will.

I can give you more details if you want. Thanks!

_Original issue: http://code.google.com/p/dart/issues/detail?id=20422_

_Copied from original issue: dart-lang/www.dartlang.org#940_

**Comment by kwalrath** [comment]
_From @nicolasgarnier on August 26, 2014 17:18_

_From [kathyw@google.com](https://code.google.com/u/kathyw@google.com/) on August 08, 2014 09:39:11_

**Labels:** Docs-Tools

**Comment by kwalrath** [comment]
Related: #1182, #464.

**Comment by kwalrath** [comment]
@munificent I'm not sure whether this issue should be closed. Would you mind taking a look at our latest (on dart.dev, or better yet in the staged version of #2332 at https://kw-staging-dartlang-2.firebaseapp.com/tools/pub/dependencies#version-constraints)?

**Comment by munificent** [comment]
I think we're good.
