### ISSUE TITLE
[PAGE ISSUE]: 'C interop using dart:ffi'

### ISSUE THREAD

**Issue by garrdbyrd** [dart-lang/site-www#4717]
### Page URL

https://dart.dev/guides/libraries/c-interop

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/libraries/c-interop.md

### Describe the problem

In the **Examples** table at the top of the page, the description for the `primitives` example includes " Also demonstrates **varargs**."

The varargs example was removed in Merged Pull Request #153 "Remove FFI varargs example" in the `primitives` repository. [(link)](https://github.com/dart-lang/samples/commit/5c8bd7cdd7373431561ee09282babf58e1659b1a)

### Expected fix

Just change the description to "How to call C functions that have arguments and return values that are **ints** or **pointers**.".

**Comment by parlough** [comment]
Thanks for catching and reporting this! A fix has landed :)
