### ISSUE TITLE
Review and adjust newest diagnostic messages

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4740]
We landed some diagnostics so they could be marked as published. You can see the changes in https://github.com/dart-lang/site-www/pull/4738.

Could you review them and make any necessary adjustments in [`messages.yaml`](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/messages.yaml) or communicate them to Brian or I? Thanks!

**Comment by parlough** [comment]
@MaryaBelanger For extra context, the `messages.yaml` file generates the [`diagnostics.md`](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/tool/diagnostics/diagnostics.md) file in the SDK.

I think running `dart run /tool/diagnostics/generate.dart` from the `/pkg/analyzer` SDK directory should update it.

**Comment by MaryaBelanger** [comment]
I opened a CL for this, not sure if that'll close this automatically once complete? https://dart-review.googlesource.com/c/sdk/+/309780

And after it's approved and merged over there, I assume I need to follow [these steps](https://github.com/dart-lang/site-www/issues/1949#issuecomment-535257768) to update them here.

**Comment by parlough** [comment]
I believe it should close this issue automatically once that lands since you have permission here.

**Comment by MaryaBelanger** [comment]
Ok so it landed, https://dart-review.googlesource.com/c/sdk/+/309780

But didn't seem to close this. I'll do the copy-over of the generated file now and then manually close this myself
