### ISSUE TITLE
Fix charset error in local Italian version of Java to Dart Codelab

### ISSUE THREAD

**Issue by dsotgiu** [dart-lang/site-www#4778]
https://developers.google.com/codelabs/from-java-to-dart?hl=it#4

Displays &#39; instead of apostrophe.

**Comment by domesticmouse** [comment]
@sfshaza2 I'm guessing I should delete the localisations of the dart for Java developers codelab?

**Comment by dsotgiu** [comment]
is just a typo...

**Comment by sfshaza2** [comment]
Yeah, probably a good idea...

**Comment by domesticmouse** [comment]
And I have no idea where the localisations are stored. 

Related: cl/533661737

**Comment by parlough** [comment]
Thanks for opening an issue!

This codelab has been retired in favor of other learning material which we are working on improving and expanding, as the codelab was not up to date with modern Dart. We will be releasing more learning material over time, and for now, have a bunch of samples at https://dart.dev/language and a detailed walkthrough of different Dart features, that is written in a way that should be familiar to Java developers. 

Thanks again!
