### ISSUE TITLE
[PAGE ISSUE]: 'Search dart.dev'

### ISSUE THREAD

**Issue by MTEV** [dart-lang/site-www#4802]
### Page URL

https://dart.dev/search.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/search.html

### Describe the problem

i think i can duplicate key name in map 
why  when use addAll 
replace with key  name 
thanks for help

**Comment by parlough** [comment]
Hi @MTEV! Could you provide some more information or a sample of your code? I'm not super clear on what you are asking. Thanks!

**Comment by MTEV** [comment]
> Hi @MTEV! Could you provide some more information or a sample of your code? I'm not super clear on what you are asking. Thanks!

Mainclass.items.addAll({
    "keyname" : {
        "firestvalue": 100, // cghange every press
        "secondvalue": 100 // cghange every press
    }
}); 

Mainclass.items.addAll({
    "keyname" : {
        "firestvalue": 200, // cghange every press
        "secondvalue": 200 // cghange every press
    }
}); 
Mainclass.items.length will be 1  
not 2
i think  deferent between map  and  set  
i can't duplicate  key name   in set  but map i can

**Comment by atsansone** [comment]
Please direct any further questions to the resources @parlough mentioned. Thanks!
