### ISSUE TITLE
[Dart 3] Add class modifiers reference page

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4809]
Many asks for this, here's one: https://github.com/dart-lang/site-www/pull/4754#issuecomment-1522287240

Possibly might get in before release, otherwise right after

**Comment by atsansone** [comment]
@MaryaBelanger : With #4754 merged, is this done?

**Comment by MaryaBelanger** [comment]
No, this is still open. It's something that came up a few times in the reviews that wasn't planned for beforehand. I kind of also want to wait and see how what I've written so far goes over with users. I'm wondering if that, plus Bob's guidance article, will be sufficient and maybe a reference isn't necessary

**Comment by navaronbracke** [comment]
I'd love to see some kind of table that lists the options. I always go back to the table at https://github.com/dart-lang/language/blob/main/accepted/future-releases/class-modifiers/feature-specification.md#syntax to figure things out,
since the current website docs don't give such an overview.

**Comment by MaryaBelanger** [comment]
@navaronbracke That's what I was thinking, getting at least that table in as a minimum. Thanks for the vote of confidence!
