### ISSUE TITLE
[Dart 3] Colon syntax for named optional parameters

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4818]
I think this needs to be updated in the "named parameters" section of the [Functions](https://dart.dev/language/functions#named-parameters) page. 

Can't use `:` for named optional parameter default values anymore, only `=`. I think some of the examples on that page use `:` and will need to all change to `=`.

_Originally posted by @MaryaBelanger in https://github.com/dart-lang/site-www/pull/4808#discussion_r1186735920_

**Comment by parlough** [comment]
Taking a look at the linked section, it looks like we don't have any mentions or usages of the old syntax remaining. I removed the last mention of it being deprecated in https://github.com/dart-lang/site-www/commit/adc5ce1c215d3fe094332e2e45ba804914800596.

For other examples, it's an analyzer warning to use the old syntax starting in 2.19 and before that it was caught by a lint, so any other usages likely would have been caught.

**Comment by MaryaBelanger** [comment]
Oh great, thanks for checking!
