### ISSUE TITLE
Feedback on Dart 3 mixins and class modifier documentation

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/site-www#4826]
### Page URL

https://dart.dev/language/mixins.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/mixins.md

### Describe the problem

The documentation should explain how the `mixin` modifier interacts with the `class` modifier. For example (not tested!):

```dart
abstract mixin class Musician {
  // Note that we don't an `on` clause here because the class defines the
  // abstract method that must be defined i.e. `playInstrument` 
  void playInstrument(String instrumentName);

  void playPiano() {
    playInstrument('Piano');
  }
  void playFlute() {
    playInstrument('Flute');
  }
}

class Virtuoso with Musician { // Use `Musician` as a mixin
  void playInstrument(String instrumentName) {
    print('Plays with $instrumentName beautifully');
  }  
} 

class Novice extends Musician { // Use `Musician` as a base class
  void playInstrument(String instrumentName) {
    print('Plays with $instrumentName poorly');
  }  
} 
```

**Comment by parlough** [comment]
I believe the upcoming Dart 3 documentation that @MaryaBelanger is working on goes into more detail on this.

Staged mixin page: https://dart-dev--pr4566-v3-0-vnwr7lr4.web.app/language/mixins

Staged class modifier page: https://dart-dev--pr4566-v3-0-vnwr7lr4.web.app/language/class-modifiers

Can you take a look and see what you think?

**Comment by brianquinlan** [comment]
I think that the single sentence dealing with `mixin`s that are also `class`es might not be enough i.e.

> A mixin declaration defines a mixin. A class declaration defines a [class](https://dart-dev--pr4566-v3-0-vnwr7lr4.web.app/language/classes). A mixin class declaration defines a class that is usable as both a regular class and a mixin, with the same name and the same type.

AFAIK, you cannot use the `on` directive with a `mixin class`. So you need to use the approach that I described above i.e. make the class abstract and define the abstract methods that you need.

That is not obvious - or at least it wasn't to me ;-)

**Comment by brianquinlan** [comment]
The class modifiers page isn't really related to what this issue but I think that `sealed` could use a bit more explanation. 

> The sealed modifier prevents a class from being extended or implemented outside of its own library. Sealed classes also prevent construction, and are therefore implicitly [abstract](https://dart-dev--pr4566-v3-0-vnwr7lr4.web.app/language/class-modifiers#abstract).

I'd another sentence like:

Subclasses of sealed classes may be constructed and sealed classes may have [factory constructors](https://dart.dev/language/constructors#factory-constructors).

And then:

var vehicle = Vehicle();                 // ERROR: Cannot be instantiated
var vehicle = Truck();                   // GOOD: Subclasses can be instantiated

// ERROR: The switch is missing a subtype of Vehicle

maybe:

// ERROR: The switch is missing Bicycle or a default case.

**Comment by parlough** [comment]
Thanks for the feedback! Your point about `mixin class`es makes sense and I really like the idea of mentioning that sealed classes can have factory constructors.

I'll defer to @MaryaBelanger as she is working on documenting these.

**Comment by MaryaBelanger** [comment]
> I think that the single sentence dealing with mixins that are also classes might not be enough

I thought so too, but wasn't sure how else to elaborate. So this is great info, thank you!
I will try to open a PR for this today (before the new docs release tomorrow morning).

**Comment by brianquinlan** [comment]
I believe that you can't use `on` with `class` based on this grammar description i.e. `mixin class Foo on Bar` is not allowed.

```
classDeclaration  ::= (classModifiers | mixinClassModifiers) 'class' typeIdentifier
                      typeParameters? superclass? interfaces?
                      '{' (metadata classMemberDeclaration)* '}'
                      | classModifiers 'mixin'? 'class' mixinApplicationClass

classModifiers    ::= 'sealed'
                    | 'abstract'? ('base' | 'interface' | 'final')?

mixinClassModifiers ::= 'abstract'? 'base'? 'mixin'

mixinDeclaration  ::= 'base'? 'mixin' typeIdentifier typeParameters?
                      ('on' typeNotVoidList)? interfaces?
                      '{' (metadata classMemberDeclaration)* '}'
```

@munificent to confirm

**Comment by munificent** [comment]
Yes, `mixin class`es can't have `on` clauses. The way to think about `mixin class` is that it:

1. Lets users use it as both a mixin and a class.
2. But in return for that flexibility, the declaration itself can only do things that make sense for both classes and mixins.

Since classes can't have `on` clauses, `mixin class`es can't either. Since mixins can't have `extends` and `with` clauses, `mixin class`es can't either.
