### ISSUE TITLE
Create code excerpts (and maybe tests) for Dart 3 documentation

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4828]
We should add code excerpts and maybe tests for the new code snippets coming in Dart 3 documentation. This will help us ensure that the snippets compile, are formatted properly, and have no analysis errors or other issues.

~~I'm going to create a new folder for the documentation rather than putting them in the super crowded misc.~~

**Edit:** I created a new folder under `/examples/language` which can replicate the language sidenav structure: https://github.com/dart-lang/site-www/tree/main/examples/language

**Comment by parlough** [comment]
@MaryaBelanger Just wanted to note that I moved this to a higher priority, since I already caught a few switches that were broken in https://github.com/dart-lang/site-www/pull/4847. I'm worried there is other code that is slightly broken.

After I finish my finals, I think this is the first thing I will work on unless you want to work on it.

**Comment by MaryaBelanger** [comment]
@parlough Ok, I'm going to write the language evolution entry and then I'll work on it right away. Thanks for pointing it out

**Comment by MaryaBelanger** [comment]
- patterns.md done in #4857 
- records.md in #4856 
- class-modifiers.md in progress #4858 
- branches.md in progress #4859 
- ToDo: pattern-types.md

**Comment by parlough** [comment]
There are still improvements to be made, but it seems all of the snippets are using excerpts now. Closing this in favor of more specific tracking as necessary. Thanks everyone!
