### ISSUE TITLE
[v3.0] pattern precedence is unstated

### ISSUE THREAD

**Issue by RandalSchwartz** [dart-lang/site-www#4837]
### Page URL

https://dart.dev/language/pattern-types (v3.0)

### Page source

https://github.com/dart-lang/site-www/blob/main/src/language/pattern-types.md

### Describe the problem

You've alphabetized the patterns, but this destroys any sense of hierarchy, and the precedence matters, which is why we have parens!  If you're going to describe them in alpha order, rather than the precedence order, you'll need a precedence chart at the end or beginning.

### Expected fix

Return to precedence order, or add a precedence chart.

**Comment by atsansone** [comment]
The precedence appears to be covered in [this section of the proposed spec](https://github.com/dart-lang/language/blob/main/accepted/future-releases/0546-patterns/feature-specification.md#patterns).

**Comment by RandalSchwartz** [comment]
> The precedence appears to be covered in [this section of the proposed spec](https://github.com/dart-lang/language/blob/main/accepted/future-releases/0546-patterns/feature-specification.md#patterns).

Yes, that's what I was referencing.  That information is needed by users in the published docs as well.

**Comment by MaryaBelanger** [comment]
@RandalSchwartz Thank you for bringing this to my attention. I've opened #4895 to fix it; please review if you can!
