### ISSUE TITLE
Retire "Intro to Dart for Java Developers" codelab

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4844]
https://developers.google.com/codelabs/from-java-to-dart

Java and Dart have both changed a lot since the codelab was written and it includes code and comments that most certainly should change with those new features, especially with Dart 3 and JDK 21.

I'm not sure there is the bandwidth(?) to keep this codelab up to date and the target users are probably better served elsewhere, as we introduce new "Learn Dart" docs on the site. Or the codelab could be updated and transferred to the site where it's easier to keep up to date.

There are also multiple issues, some of which have been around for a while:

- https://github.com/dart-lang/site-www/issues/2698
- https://github.com/dart-lang/site-www/issues/3071
- https://github.com/dart-lang/site-www/issues/4778

**Comment by parlough** [comment]
@domesticmouse I think this codelab should just be retired. I don't see a lot of value in keeping it around.

**Comment by domesticmouse** [comment]
Thoughts @MaryaBelanger @johnpryan?

**Comment by johnpryan** [comment]
Retiring seems like a good option to me.

**Comment by parlough** [comment]
Okay, I've removed links to the codelab from both sites. Leaving this issue open to track finalizing its retirement.

**Comment by domesticmouse** [comment]
cl/533661737

**Comment by domesticmouse** [comment]
Related: https://github.com/dart-lang/site-www/issues/4778

**Comment by parlough** [comment]
Looks like the codelab is now redirecting to the beginner Flutter codelab. Thanks! Can this be closed @domesticmouse or is there anything else to adjust?

**Comment by domesticmouse** [comment]
I think this is done. Thanks @parlough =)
