### ISSUE TITLE
Cannot get to macOS tab on 'Get the Dart SDK'

### ISSUE THREAD

**Issue by DivineGull** [dart-lang/site-www#4863]
### Page URL

https://dart.dev/get-dart/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/get-dart/index.md

### Describe the problem

I can't click the 'mac os' button on the page. As I've completed downloading homebrew, I need to copy two lines of code from the dart.dev page. Unfortunately, the button is not working. I think the website itself is half-dead or smth idk.

**Comment by parlough** [comment]
Hi @DivineGull, thanks for opening an issue. Could you provide a recording as mentioned or check your [JavaScript console](https://developer.chrome.com/docs/devtools/console/javascript/) for errors.

Just in case it's not working, I'll reproduce the instructions here for you to reference:

---

[Install Homebrew,](https://brew.sh)
and then run the following commands:

```terminal
$ brew tap dart-lang/dart
$ brew install dart
```

> **Note**
>  Make sure the **Homebrew `bin` directory is in your `PATH`**. 
>  Setting up the path correctly makes it easier to use Dart SDK commands
>  such as `dart run` and `dart format`. 
>  For help configuring your path, 
>  consult the [Homebrew FAQ.](https://docs.brew.sh/FAQ)

To upgrade when a new release of Dart is available:

```terminal
$ brew upgrade dart
```

To switch between locally installed Dart releases, 
first install the version you want to switch to if you haven't.
For example, to install Dart 2.12:

```terminal
$ brew install dart@2.12
```

Then to switch between versions, 
unlink the current version and link the desired version.

```terminal
$ brew unlink dart@<old> && brew unlink dart@<new> && brew link dart@<new>
```

To see which versions of Dart you've installed:

```terminal
$ brew info dart
```

**Comment by atsansone** [comment]
I cannot replicate this behavior on macOS running Chrome 113.

![install-page-tabs](https://github.com/dart-lang/site-www/assets/706219/691a1acb-0b91-4022-843f-7fabfa6a24ec)

Can you tell us which OS and browser you're using?
