### ISSUE TITLE
Revise explanation of sealed class in 'Class modifiers'

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/site-www#4869]
### Page URL

https://dart.dev/language/class-modifiers.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/class-modifiers.md

### Describe the problem

Some members of the Dart team have interpreted the docs to mean that `sealed` classes cannot have constructors. They can for the purposes of initializing their subclasses.

### Expected fix

Maybe:

Sealed classes also prevent construction **(but they can define constructors for their subclasses to use)**, and are therefore implicitly [abstract](https://dart.dev/language/class-modifiers#abstract). However, subclasses of sealed classes can be constructed, and sealed classes can have [factory constructors](https://dart.dev/language/constructors#factory-constructors).

**Comment by MaryaBelanger** [comment]
Apologies for the delay @brianquinlan , I've just merged in the changes from #4834 which addresses this and the mixin class issue from #4826. Thanks for the extremely valuable feedback.
