### ISSUE TITLE
Rewrite mixins page

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4871]
Rewrite/rearrange contents on [mixins page](https://dart.dev/language/mixins) in a more sensible way, details in these comments: https://github.com/dart-lang/site-www/pull/4834#discussion_r1189194062

**Comment by parlough** [comment]
Some more [feedback on the page](https://github.com/dart-lang/site-www/issues/5144#issue-1864197013) from @feinstein:

> I think we should expand the mixin docs, there are more details to them that are not in the tutorial.
> 
> For example, a `mixin` can have abstract functions, that should be declared into a class that uses the `mixin`, so on this sense a `mixin` can have `abstract` methods, or getters, etc, even though its not an `abstract class mixin`. I discovered this by exploring `mixin`, so I wonder what else I can do with them that I just didn't find out for myself.
> 
> Also we should be more emphatic about the `mixin` limitations, we only show them in the `class, mixin, or mixin class?` section for a little bit.
