### ISSUE TITLE
Label patterns in 'Pattern types' as experimental

### ISSUE THREAD

**Issue by MisaGu** [dart-lang/site-www#4873]
### Page URL

https://dart.dev/language/pattern-types.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/pattern-types.md

### Describe the problem

Almost all displayed features are experimental. Please add an "Experimental" tag next to each pattern type to make it obvious.

### Expected fix

Havethe  "Experimental" tag next to every pattern title.

**Comment by parlough** [comment]
Hi @MisaGu, thanks for opening an issue.

I'm curious what you mean by experimental? Patterns and these different pattern types were released to stable with Dart 3.0 which was [released](https://medium.com/dartlang/announcing-dart-3-53f065a10635) on May 10.

**Comment by parlough** [comment]
Hi again!

I'm going to close this as patterns and these patterns types have been in the stable channel for a week now (3.0.0+ for Dart and 3.10.0+ for Flutter).

Let us know if you still think something needs to change in the docs. Thanks!
