### ISSUE TITLE
Update 'Record Equality' section in 'Records'

### ISSUE THREAD

**Issue by eernstg** [dart-lang/site-www#4874]
### Page URL

https://dart.dev/language/records.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/records.md

### Describe the problem

The example in section 'Record Equality', https://dart.dev/language/records#record-equality illustrates the typing properties which were already discussed at the end of the 'Record Syntax' section (in particular, it illustrates that types like `(int a, int b)` and `(int x, int y)` are the same type, but `({int a, int b})` and `({int x, int y})` are different types).

However, the example should be changed to illustrate equality (and possibly hashCode, but certainly equality), because that's the topic of the section.

### Expected fix

For example:

```dart
(int x, int y, int z) point = (1, 2, 3);
(int r, int g, int b) color = (1, 2, 3);

print(point == color); // Prints 'true'.
```

```dart
({int x, int y, int z}) point = (x: 1, y: 2, z: 3);
({int r, int g, int b}) color = (r: 1, g: 2, b: 3);

print(point == color); // Prints 'false'. Lint: Equals on unrelated types.
```

**Comment by MaryaBelanger** [comment]
Thank you Erik! Taking care of it right away (I think that repetition of examples was a last minute change that didn't quite make it in time for the thorough technical reviews that happened earlier, so catching this is very appreciated)
