### ISSUE TITLE
Consider renaming 'Callable classes' as 'Callable instances'

### ISSUE THREAD

**Issue by gamebox** [dart-lang/site-www#4876]
### Page URL

https://dart.dev/language/callable-classes.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/callable-classes.md

### Describe the problem

This topic might more accurately be called "Callable Instances". The class itself isn't callable (call isn't static), but the instance is.

### Expected fix

Update language in this document (and site navigation) to refer to "Callable Instances" instead of "Callable Classes"

**Comment by atsansone** [comment]
@munificent : Thoughts on this?

**Comment by gamebox** [comment]
To be clear, I'm happy to put in the admittedly tiny PR for this if desired

**Comment by eernstg** [comment]
Makes sense. Also, various specification documents use 'callable object' and 'callable objects' in about 25 locations (in commentary), so that's what a reader would find if they use site-www as a starting point for looking into any of those specification documents.

**Comment by parlough** [comment]
Thanks all! Sounds like we should rename to "Callable objects" then to be consistent with the specification and make the relationships between the two easier to identify.

@gamebox What do you think?

**Comment by gamebox** [comment]
That sounds good to me.  Want me to update my PR?
