### ISSUE TITLE
[PAGE ISSUE]: 'Migrating to null safety'

### ISSUE THREAD

**Issue by jpiabrantes** [dart-lang/site-www#4880]
### Page URL

https://dart.dev/null-safety/migration-guide.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/null-safety/migration-guide.md

### Describe the problem

The code on this page no longer works

```sh
dart pub outdated --mode=null-safety
```

Please tell us which flutter version we should have to run this and how to install that version.

**Comment by danagbemava-nc** [comment]
I see an error when I try to run it with flutter 3.10.0 (dart 3.0.0). 

```
The `--mode=null-safety` option is no longer supported.
Consider using the Dart 2.19 sdk to migrate to null safety.
```

@jpiabrantes, I think you should be able to run the command successfully with flutter 3.7.12 & below. They are running dart 2.19


We should update the documentation as it seems like this is no longer supported on dart 3

**Comment by parlough** [comment]
Thanks for the heads up. We're still in the process of updating and cleaning up our null safety documentation after the release of Dart 3. I just pushed a fix in https://github.com/dart-lang/site-www/commit/cab19b63d0ea553a46e41c174422e889029ca65e to make this more clear. Thanks again!
