### ISSUE TITLE
There is an example of trying to reassign the Record type even though it is immutable

### ISSUE THREAD

**Issue by hibix43** [dart-lang/site-www#4907]
### Page URL

https://dart.dev/language/records

### Page source

https://github.com/dart-lang/site-www/blob/main/src/language/records.md

### Describe the problem

There is an example of trying to reassign the Record type even though it is immutable.

Is the "Record syntax" sample code incorrect?

```dart
(int a, int b) recordAB = (1, 2);
(int x, int y) recordXY = (3, 4);

recordAB = recordXY; // OK.
```

I get the following error. Am I wrong?

>Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.dart(missing_const_final_var_or_type)
>
>The name 'recordAB' is already defined.
Try renaming one of the declarations.dartduplicate_definition

**Comment by eernstg** [comment]
The code is fine when located in a function body, but it is an error at the top level because statements cannot occur there:

```dart
(int a, int b) recordAB = (1, 2);
(int x, int y) recordXY = (3, 4);

recordAB = recordXY; // Error, expected a declaration and not a statement.
```

This would work:

```dart
void main() {
  (int a, int b) recordAB = (1, 2);
  (int x, int y) recordXY = (3, 4);

  recordAB = recordXY; // OK.
}
```

It might be a good idea to wrap all examples containing statements in a `void main() {...}` such that they are immediately runnable.

**Comment by hibix43** [comment]
I see. I understand the problem. Thank you very much. Please close this issue.

**Comment by parlough** [comment]
Thanks for the issue and the explanation!

We want to eventually introduce a system of expandable code snippets so we can hide the surrounding code to make it runnable, while also allowing us to focus on what's important.

I'll defer to that issue - https://github.com/dart-lang/site-www/issues/4908

**Comment by eernstg** [comment]
Sounds good, thanks!
