### ISSUE TITLE
Flutter note formatting issue

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4914]
### Describe the problem

Flutter notes are often oddly formatted due to the sizing of the Flutter logo.

### Expected fix

We should adjust the style somehow or remove the logo to stop messing up the formatting.

**Comment by parlough** [comment]
I'm going to close this as a duplicate of https://github.com/dart-lang/site-www/issues/4919 since @MaryaBelanger put more effort into her issue with fancy screenshots and diagrams :)

**Comment by MaryaBelanger** [comment]
Oh I'm sorry! I need to start checking if an issue already exists... Feel free to close mine next time (whatever it may be), we can always copy the fancy diagrams over 😅
