### ISSUE TITLE
Use WebP for images instead of PNG

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4918]
Now that Safari has supported WebP for a while, global market support [is over 97%](https://caniuse.com/webp), likely even higher among developers.

WebP supports better compression. Around 25% on average [according to MDN](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#webp_image). We should consider switching for all of our images for reduced page load time.

**Comment by parlough** [comment]
@atsansone Can you verify internally if this is okay at this point? Perhaps is mentioned on the guidelines you mentioned or elsewhere.

**Comment by atsansone** [comment]
Maybe use https://webponize.org/?

**Comment by parlough** [comment]
Closing this in favor of an automatic solution in https://github.com/dart-lang/site-www/issues/4473.
