### ISSUE TITLE
Gap due to icon in `flutter-note` site alerts

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4919]
### Describe the problem

The Flutter icon causes an inconsistent amount of space between the first and second line of any `{{site.alert.flutter-note}}`:

<img width="951" alt="image" src="https://github.com/dart-lang/site-www/assets/111139605/473e64ca-02b6-4872-87e5-836aa82dbfbe">

### Expected fix

The icon is good and should stay, but it'd be nice to not have that awkward gap. I'm not sure how to achieve that though. Maybe make it smaller so it doesn't push the line margin down? 

```
| img | Flutter note: line 1
line 2
line 3 etc
```

Or put it in it's own "section" on the left side of the block, and have all text just start to the right of that section:

```
|       | Flutter note: line 1
|  img  | line 2
|       | line 3 etc
```

**Comment by parlough** [comment]
I will try both and we can see what we think :)
