### ISSUE TITLE
Fix Matching example on 'Patterns' page

### ISSUE THREAD

**Issue by praxder** [dart-lang/site-www#4921]
### Page URL

https://dart.dev/language/patterns.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/patterns.md

### Describe the problem

On the "Matching" section, this example is given:
```dart
switch (obj) {
  // List pattern [a, b] matches obj first if obj is a list with two fields,
  // then if its fields match the constant subpatterns 'a' and 'b'.
  case [a, b]:
    print('$a, $b');
}
```
But that doesn't compile. I'm not sure why it doesn't compile, since [the docs](https://dart.dev/language/pattern-types#identifier) for the `identifier` type of pattern matching does show this as valid syntax. The example simply doesn't work on dartpad.dev.

### Expected fix

Not sure.

### Additional context

Tested on dartpad.dev with Dart 3.0.1.

**Comment by MaryaBelanger** [comment]
Thanks for checking on this @praxder 

Can you show us what you're getting from dartpad? I've tried and it's compiling. 

![image](https://github.com/dart-lang/site-www/assets/111139605/3fc28f89-f7fd-4cdf-8a94-e27f3b005a9b)

For reference, that code snippet is built in a dart file and added to the doc page. You can find the source [here](https://github.com/dart-lang/site-www/blob/main/examples/language/lib/patterns/switch.dart#L29) (lines 29-38).

On the doc page, it leaves out the declaration of `a` and `b` as constants, but the comment is meant to make up for showing that declaration:

>   // List pattern [a, b] matches obj first if obj is a list with two fields,
>   // then if its fields match **_the constant subpatterns 'a' and 'b'_.**

**Comment by praxder** [comment]
Ah, that makes sense, I was mis-interpreting that another way. In that case, this is working fine. Thanks for clarifying!

Closing this issue.

**Comment by MaryaBelanger** [comment]
No worries at all! It seems that having the actual constant declarations visible in the example code might've helped you avoid this confusion (correct me if I'm wrong). That's valuable feedback; we can add those to help other users who might run into the same question. If it was something else, or just something about the wording leading up to the example, let me know that too. Every detail matters!

**Comment by praxder** [comment]
Sounds good. I went ahead and opened another PR with those changed. 
https://github.com/dart-lang/site-www/pull/4924

**Comment by parlough** [comment]
Looks like https://github.com/dart-lang/site-www/pull/4924 handled the concerns here. Thank you!
