### ISSUE TITLE
[PAGE ISSUE]: 'Pattern types null-assert' section as a `</span>` instead of `!]`

### ISSUE THREAD

**Issue by exaby73** [dart-lang/site-www#4936]
### Page URL

https://dart.dev/language/pattern-types.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/pattern-types.md

### Describe the problem

The code sample of the current page is as follows:

```dart
List<String?> row = ['user', null];
switch (row) {
  case ['user', var name</span>: // ...
  // 'name' is a non-nullable string here.
}
```

After `var name`, there shouldn't be `</span>`.

### Expected fix

The code sample should be as follows:

```dart
List<String?> row = ['user', null];
switch (row) {
  case ['user', var name!]: // ...
  // 'name' is a non-nullable string here.
}
```

### Additional context

<img width="600" alt="image" src="https://github.com/dart-lang/site-www/assets/50555895/82e3c04e-b506-4c8d-a346-2763ad19add1">

Edit: looking at the source, there doesn't seem to be an issue in the content, which means maybe this is an issue with converting the markdown into HTML. I've included a screenshot above for how it currently looks

**Comment by MaryaBelanger** [comment]
I'm not immediately sure how to fix this, but just adding that there's also no issue in the source for the excerpt either: https://github.com/dart-lang/site-www/blob/main/examples/language/lib/patterns/pattern_types.dart#L141
