### ISSUE TITLE
Update `switch` example on 'Pattern types' page

### ISSUE THREAD

**Issue by veryriskyrisk** [dart-lang/site-www#4938]
### Page URL

https://dart.dev/language/pattern-types.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/pattern-types.md

### Describe the problem

List section has code snippet that doesn't compile:
```dart
switch (obj) {
  // Matches if obj is a list with two elements.
  case [a, b]: // ...
}
```

### Expected fix

This should probably be replaced with 
```dart
switch (obj) {
  // Matches if obj is a list with two elements.
  case [final a, final b]: // ...
}
```

**Comment by MaryaBelanger** [comment]
Code snippets are generated from a `dart` file in the `/examples` folder (If you look at the `code-excerpt` line right above the snippet in the source markdown, [line 298](https://github.com/dart-lang/site-www/blob/main/src/language/pattern-types.md?plain=1#L298), you can see the `dart` file that it points to). 

In that file we declared `a` and `b` as `const` ([lines 38-39](https://github.com/dart-lang/site-www/blob/main/examples/language/lib/patterns/pattern_types.dart#L38)), so it compiles there. That's not clear in the docs though, so we should update it. 

Thanks for pointing this out @veryriskyrisk!

**Comment by veryriskyrisk** [comment]
Thank you @MaryaBelanger! I didn't notice there are actual examples backing documentation - are those linked somewhere? If not please consider linking them next to the snippets, it'd make it easier to consume the documentation.

**Comment by MaryaBelanger** [comment]
> If not please consider linking them next to the snippets, it'd make it easier to consume the documentation.

That's a really great idea. We've had a few similar questions to yours recently, plus a few attempts at contribution that missed the source code files too, so simple linking would definitely solve that. I'm going to make another tracking issue for this!
