### ISSUE TITLE
Example code is not displayed right.

### ISSUE THREAD

**Issue by MiladAtef** [dart-lang/site-www#4943]
### Page URL

https://dart.dev/language/pattern-types#null-assert

### Page source

https://github.com/dart-lang/site-www/blob/main/src/language/pattern-types.md#null-assert

### Describe the problem

The example code in this section is displayed like this with "span":

```Dart
List<String?> row = ['user', null];
switch (row) {
  case ['user', var name</span>: // ...
  // 'name' is a non-nullable string here.
}
```

Where it is supposed to be displayed as the page source like the following:
```Dart
List<String?> row = ['user', null];
switch (row) {
  case ['user', var name!]: // ...
  // 'name' is a non-nullable string here.
}
```

**Comment by parlough** [comment]
Thanks for the issue. I landed a fix in https://github.com/dart-lang/site-shared/commit/d12bf9ba015be7f8be9e92da62000a0a48f3e4ff that will be included in https://github.com/dart-lang/site-www/pull/4942
