### ISSUE TITLE
[PAGE ISSUE]: 'Glossary of package terms' - "library package" term is misleading

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/site-www#4944]
### Page URL

https://dart.dev/tools/pub/glossary.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/pub/glossary.md

### Describe the problem

The term "Library package" is misleading imo, see https://github.com/dart-lang/language/issues/3123. I think we should come up with a different term (I would just call it a package).

In Dart a Library and a Package are two different things, and we are conflating the meanings with terms like this. A library is a single _compilation unit_, which is made up of a single primary file and then some number of parts, and has its own private scope.

A package is a collection of libraries under a directory, with a pubspec.yaml in the root of that directory (technically a pubspec.yaml is not actually required but for essentially all external users this would be how they make a package, so it is probably fine to omit this detail).

Packages also have a directory under which they can put their "public libraries", which is the `lib` directory (again technically doesn't have to be `lib/`, but does be for any normal developer, so probably not worth mentioning).

### Expected fix

My suggestion would be to change the term "Library package" to "Pub package", or possibly just "package", or some other term. I chose "Pub package" because typically a shared package would be published to pub. But you could also have your own non-published packages that are not apps, so it isn't a perfect term.

If we just called these a "package", then we would have the special "app package" term still, which would just be a special type of package that isn't intended to be depended on by other packages.

I think it would also be good to have a dedicated doc explaining more concretely exactly the "library" term and the "package" term.

**Comment by MaryaBelanger** [comment]
Pages/sections where this will need to be refactored:
- https://dart.dev/tools/pub/glossary#library-package (the issue page)
- https://dart.dev/guides/libraries/create-library-packages
  - The entire page uses "library package" to describe a typical package, i.e. a collection of libraries. 
- https://dart.dev/tools/pub/package-layout#public-libraries 
- https://dart.dev/language/libraries#implementing-libraries 
  - Says "See [Create Library Packages](https://dart.dev/guides/libraries/create-library-packages) for advice on how to implement a library package", further conflation
- Possibly more, will update

Working on this now and I agree that the conflation is an issue. But just want to make it clear it's going to be a big shift in terminology across the site. So everywhere it says "library package" now is going to change to _just_ package, and link to the definition that _a package is a collection of libraries_, and that _a library is a file plus it's parts_. 

@jonasfj I'll add your review to the PR; please jump in here if you disagree with the premise.

**Comment by jakemac53** [comment]
Yeah we should definitely be deliberate here - I don't know who would typically be involved in such changes/decisions :). But it _may_ be worth involving a few other folks on the product side of things to get some buy-in?
