### ISSUE TITLE
Out dated Markdown files with broken links

### ISSUE THREAD

**Issue by X-itachi-X** [dart-lang/site-www#4948]
### Describe the problem

Lots of Markdown files under [src](https://github.com/dart-lang/site-www/tree/main/src) are outdated and links are broken and images are also used there are outdated. lots of files need small reviews and checking if they are working correctly.

ps: I am a beginner issuer so if there is something I don't know please tell me

### Expected fix

according to me as far as i know we should check all the markdown files one by one and check all the links on other pages and images. as well as we should check if the images used there are updated or not.

### Additional context

[index.md](https://github.com/dart-lang/site-www/blob/main/src/web/index.md)
this an example of one of the broken markdown files

**Comment by parlough** [comment]
Thanks for opening an issue @X-itachi-X!

Could you provide a specific example of a link that's not working? 

The links in the markdown files in `/src` are relative from the base url, so as an example, the `/guides/libraries#web-platform-libraries` link in the file you mentioned will link to https://dart.dev/guides/libraries#web-platform-libraries on the site. You can see that working at https://dart.dev/web.

**Comment by X-itachi-X** [comment]
Thanks for responding so quickly, I was looking at only codes and thought that it wasn't working properly there as you now told me I checked, and works fine, and you don't expect people to use them from there it's fine then. but it would be great if the links in the markdown would work correctly too.
but if you don't want to worry about it then I will close this issue if you confirm.

**Comment by parlough** [comment]
I think we'd like to keep the links as is, since there are also community-supported translated versions of the site, and these base-url relative URLs allow the links to work easily in those situations as well. 

I appreciate you looking into this though :)

**Comment by X-itachi-X** [comment]
thanks for helping me to understand the way of open source. I will try to contribute more.
