### ISSUE TITLE
[PAGE ISSUE]: 'Code of conduct'

### ISSUE THREAD

**Issue by Outlaw999** [dart-lang/site-www#4977]
### Page URL

https://dart.dev/community/code-of-conduct.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/community/code-of-conduct.md

### Describe the problem

****### source 

### Expected fix

**project hook 7**

**Comment by parlough** [comment]
Hi @Outlaw999, thanks for opening a issue!

However, from the description, I'm not sure what the problem is. Could you perhaps expand on your issue or provide some more information or screenshots. Thanks so much!

**Comment by parlough** [comment]
I'm going to close this without extra information, but if you have any more information or need help, please let us know. Thanks so much!
