### ISSUE TITLE
Rewrite 'Write command-line apps' tutorial

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4987]
### Page URL

https://dart.dev/tutorials/server/cmdline

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_tutorials/server/cmdline.md

### Describe the problem

This is an old tutorial that could benefit from rewriting and a letter extra focus.

It is also the last use of tooltips, which we'd like to remove (https://github.com/dart-lang/site-www/issues/2316) to simplify the site infrastructure.

### Expected fix

Rewrite the tutorial, considering some stylistic choices from the more recent [Fetch data tutorial](https://dart.dev/tutorials/server/fetch-data). Keep it valuable and teach some basic concepts without using tooltips if possible.

**Comment by atsansone** [comment]
@parlough : #2316 asks to delete _or_ use more consistently. I'd prefer the latter. They have some great applications that I don't think we've taken full advantage.

**Comment by parlough** [comment]
I think we can and should revisit tooltips in code blocks in the future, especially since browsers are implementing native popover mechanisms, but currently this functionality is hard to maintain, write, properly test, and ensure accessibility.

I think for practical purposes in the meantime, it makes sense to drop its current use.

**Comment by atsansone** [comment]
Agreed if we revisit later.
