### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by pmishra** [dart-lang/site-www#5]
URL: https://www.dartlang.org/windows
Expected page: https://www.dartlang.org/windows

**Comment by pmishra** [comment]
Every link on https://www.dartlang.org/install page is throwing error.

**Comment by Sfshaza** [comment]
Fixed. I changed all permalinks removing the trailing slash on all directories. This also involved changing all references to those links. I fixed this on both www and webdev. Many many files were touched, but the linkchecker reports that both sites are clean.

FYI, the links were ONLY broken if you clicked them from https://www.dartlang.org/install. If you clicked them from https://www.dartlang.org/install/, they were fine. (Note the trailing slash in the latter case.)
