### ISSUE TITLE
View page source button for individual lint pages doesn't work

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5016]
### Describe the problem

For example, clicking the "View page source" button on this page https://dart.dev/tools/linter-rules/prefer_mixin leads to this 404 in the site repo https://github.com/dart-lang/site-www/tree/main/src/tools/linter-rules/prefer_mixin.md

### Expected fix

I'm sure this has something to do with how they live in the linter repo.

### Additional context

Not a big deal, but something to look into eventually.

**Comment by parlough** [comment]
I did not think of this, thank you so  much for catching it. What do you think about hiding it for now on those pages until we figure out where the content will live in the future?

**Comment by MaryaBelanger** [comment]
> What do you think about hiding it for now on those pages until we figure out where the content will live in the future?

That sounds good!
