### ISSUE TITLE
Update cover image for new edition on 'Books about Dart' page

### ISSUE THREAD

**Issue by suragch** [dart-lang/site-www#5051]
### Page URL

https://dart.dev/resources/books.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/resources/books.md

### Describe the problem

_Data Structures & Algorithms in Dart_ has a new edition out. The title, description and link are still fine, but the book cover image is out of date now.

### Expected fix

Could you replace the cover image with the new one? 

Cover image available here: https://www.kodeco.com/books/data-structures-algorithms-in-dart

**Comment by parlough** [comment]
Happy to update the cover (https://github.com/dart-lang/site-www/pull/5052). Thanks for the heads up.

Congratulations on the new edition and I love that you're keeping it up to date! I keep meaning to read the book, but haven't had the chance yet.

**Comment by suragch** [comment]
Thank you, @parlough !
