### ISSUE TITLE
Move diagnostic glossary entries to site-wide glossary

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#5054]
Really rough steps. Feel free to rewrite :) 

- [x] 1. Add entries to dart.dev/resources/glossary with any desired copy/technical updates (https://github.com/dart-lang/site-www/pull/5066)
- [x] 2. Update links in the SDK generator to link to `/glossary/<word>` (https://dart-review.googlesource.com/c/sdk/+/313960)
- [x] 3. Remove old glossary entries from `generate.dart` (https://dart-review.googlesource.com/c/sdk/+/313960)
- [ ] 4. Update version of diagnostic messages file on site-www #5070

**Comment by MaryaBelanger** [comment]
> 2. Update links in the SDK generator to link to /glossary/<word>

Does this mean I need to update links in [`generate.dart`](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/tool/diagnostics/generate.dart)? Or just as normal in `messages.yaml`, then run the generation tool?

And I'm guessing after generating `diagnostics.md` in the sdk, I'll have to copy it over here as with any diagnostic message updates? Thanks @parlough!

**Comment by parlough** [comment]
I apologize for not being super clear, I just made this issue pretty quickly. 

> 2. Update links in the SDK generator to link to /glossary/<word>
>
> Edit: Flip flopping again, did you mean I need to update the links on lines [241](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/tool/diagnostics/generate.dart#L241)-247 in generate.dart?

There are two potential solutions, I was originally thinking the first one but both are fine. Let me know what you think :) 

1. You can keep the link definitions in https://github.com/dart-lang/sdk/blob/acd2ad41b66187564b65d93cd70538c01727c720/pkg/analyzer/tool/diagnostics/generate.dart#L241-L247 but just update them to point the glossary entries. This way you don't need to update a bunch of links in `messages.yml` which use the link definitions.
2. You can specifying the links in each diagnostic message they are used in and remove those link definitions.

> And I'm guessing after generating `diagnostics.md` in the sdk, I'll have to copy it over here as with any diagnostic message updates?

Yep, exactly! You probably want to make sure to land the new glossary entries first in a separate to avoid any potential issues.

**Comment by MaryaBelanger** [comment]
Great! 1) Seems interesting, I might try that first

**Comment by MaryaBelanger** [comment]
Opened https://dart-review.googlesource.com/c/sdk/+/313960 for steps 2 and 3
