### ISSUE TITLE
iOS safari page horizontal size issue

### ISSUE THREAD

**Issue by sarasotafingerprints** [dart-lang/site-www#5062]
### Page URL

https://dart.dev/language/operators

### Describe the problem

The page is too wide on mobile on iPhone 12 pro

### Expected fix

Fix css width. See screenshot:

![IMG_0128](https://github.com/dart-lang/site-www/assets/121450556/0e709ab3-9691-490f-aa8d-cf7d4e9caef4)

**Comment by danagbemava-nc** [comment]
This is caused by the table on the page

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of #5041
