### ISSUE TITLE
Update pub package links

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#508]
The link structure has changed slightly in the new pub.dartlang.org.

E.g., the changelog link to https://pub.dartlang.org/packages/angular/versions/4.0.0+1#pub-pkg-tab-changelog should instead go to something like https://pub.dartlang.org/packages/angular/#-changelog-tab-.

**Comment by kwalrath** [comment]
Check this once #1324 is in.

**Comment by parlough** [comment]
Going through all the pub links I found on site-www, there doesn't seem to be any still affected by this issue anymore. Feel free to re-open if you come across anymore.
