### ISSUE TITLE
[PAGE ISSUE]: 'Operators' 

### ISSUE THREAD

**Issue by GouravNainwaya** [dart-lang/site-www#5087]
### Page URL

https://dart.dev/language/operators.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/operators.md

### Describe the problem

add dark mode support white mode so painfull for eyes

**Comment by parlough** [comment]
Thanks for opening an issue!

It's definitely something we have planned and would look to get done.

We're tracking this work in https://github.com/dart-lang/site-www/issues/2625, so I'll close this issue in favor of that one. Thanks again!
