### ISSUE TITLE
Consolidate formatting pages

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5091]
These pages should be consolidated:

- https://dart.dev/tools/dart-format 
- https://dart.dev/guides/language/formatting

**Comment by parlough** [comment]
Makes sense! Probably prefer the `dart format` page for consistency with other CLI tools.

We have a few other related issues such as https://github.com/dart-lang/site-www/issues/3611 and https://github.com/dart-lang/site-www/issues/4440, which discuss expanding the `dart format` page.
