### ISSUE TITLE
AVOID generic public top-level member names

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#51]
_From @munificent on January 11, 2016 21:3_

From @yjbanov:

> Unless a library is designed to be imported with a prefix (e.g. dart:math, package:path) we should discourage the use of generic top-level member names.
> 
> For example, a top-level function register would not be descriptive enough, risks to shadow another symbol with the same name, or cause a conflict. However, it might be ok if your library is meant to be used with a prefix, e.g. plugins.register(myPlugin) is fine.
> 
> Can this guideline be added to Effective Dart?

_Copied from original issue: dart-lang/www.dartlang.org#1543_

**Comment by Sfshaza** [comment]
_From @sethladd on January 11, 2016 21:33_

How do I know how to design a library to be imported as a prefix? Shouldn't I assume that I don't control that, and my user may or may not use a prefix?

**Comment by Sfshaza** [comment]
_From @munificent on January 11, 2016 21:43_

> How do I know how to design a library to be imported as a prefix?

By "how" do you mean "whether or not"? I think that's basically up to you. If the library mostly exposes bare functions, and their reasonable names have a lot in common, I think it often makes sense to assume an import prefix and then use shorter function names.

>  Shouldn't I assume that I don't control that, and my user may or may not use a prefix?

You don't *control* it, but I think you have the freedom to design an API that assumes your user is reasonable and will use a prefix if you suggest it. If they don't, it's up to them to know what they're doing.

**Comment by Sfshaza** [comment]
_From @sethladd on January 11, 2016 21:50_

Should the title be "AVOID generic public top-level member names if your library is not designed to be used with a prefix" or is the advice to "AVOID generic public top-level member names" ?

Maybe there's another bit of guidance: "Be explicit if your library is designed to be used with a prefix" ?

**Comment by Sfshaza** [comment]
_From @yjbanov on January 11, 2016 22:19_

I think choosing to design a prefixed library and choosing top-level names are separate concerns. _If_ you are working on a prefixed library, then avoid using generic top-level names would be the guideline. The decision to design a prefixed library would have already taken place by then, driven by other factors.

We could have a separate guideline about when to recommend a prefix.

**Comment by kwalrath** [comment]
Closing because it doesn't seem like we're going to add this. Feel free to reopen if you feel strongly that we _should_.
