### ISSUE TITLE
Clarify library documentation around support for deferred loading in AOT mode

### ISSUE THREAD

**Issue by a-siva** [dart-lang/site-www#5100]
https://dart.dev/language/libraries states that deferred loading is not supported in the Flutter and Dart VM.
This is not entirely true, we do support deferred loading in AOT mode, this text needs to be updated to reflect
the current state.

Please see https://github.com/dart-lang/sdk/issues/33118 which was closed as implemented for AOT

**Comment by a-siva** [comment]
> Thanks for the issue. Could you move this to [`dart-lang/site-www`](https://github.com/dart-lang/site-www/issues)? Otherwise it will get lost.
> 

Done

> Are there any special concerns for deferred loading in AOT that we should make sure to mention?

Please see [doc](https://docs.google.com/document/d/11OehIt4kZ8k-B8TFspCiKfO1PDlUeFBB4rwVyGczvg4/edit)

**Comment by atsansone** [comment]
Per [this comment](https://github.com/flutter/website/issues/7117#issuecomment-1790564360), the [Lazily loading a library](https://dart.dev/language/libraries#lazily-loading-a-library) needs an update.
