### ISSUE TITLE
Update platforms image on 'Dart overview' page

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#5101]
### Page URL

https://dart.dev/overview.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/overview.md

### Describe the problem

The platforms image needs to be updated to put a computer above ARM64 (replace one of the phones) since macOS ARM64 support is already stable and Windows 11 ARM support will reach stable eventually.

As a side note, the icons currently use Material Icons, but we should consider updating them to Material Symbols as the rest of the website will be doing so.

Not yet, but in the future, it will likely need to add RISC-V (RV64GC) and WASM as those targets become stable as well.

_Current image for reference:_
![Dart supported platforms image](https://dart.dev/assets/img/Dart-platforms.svg)

### Expected fix

- Figure out who created the image, ask them to update:
- Replace one of the phones above ARM64 with the computer icon
- (Optional) Replace Material Icons usages with Material Symbols

### Additional context

This image is also replicated in the SDK readme: https://github.com/dart-lang/sdk#dart

**Comment by parlough** [comment]
\cc @mit-mit You originally added this file, so perhaps you have the original source or can direct this to who does. Either way, it's not a pressing issue. Thanks!

**Comment by mit-mit** [comment]
Does this work @parlough? Wasn't sure if we need the background transparent or not?
 
![platforms](https://github.com/dart-lang/site-www/assets/13644170/418d416a-2ed0-4990-80ed-93f5652225f0)

**Comment by parlough** [comment]
Yes, thank you! I've updated it in https://github.com/dart-lang/site-www/pull/5135
