### ISSUE TITLE
Describe conditional imports on the 'Libraries' page

### ISSUE THREAD

**Issue by Nashev** [dart-lang/site-www#5109]
### Page URL

https://dart.dev/language/libraries.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/libraries.md

### Describe the problem

There is not described syntax like 
`import 'html_stub.dart' if (dart.library.html) 'dart:html' as html;`
but i see the source code used it. It must be described there.

P.S. What `dart.library.html` is here?

### Expected fix

Move or copy [this section](https://dart.dev/guides/libraries/create-packages#conditionally-importing-and-exporting-library-files) into the https://github.com/dart-lang/site-www/tree/main/src/language/libraries.md page and a little rewrite to more consistency. With a link to specification of the `dart.library`.

**Comment by Nashev** [comment]
Also there must be link to the https://dart.dev/guides/libraries page for clarification what names can be used in the `if` part

**Comment by atsansone** [comment]
@munificent : Would you have something I could reference to write out this documentation?

**Comment by parlough** [comment]
Thanks for raising this! It's definitely an area we need to work on documenting better soon. We're also open to contributions!

Closing in favor of https://github.com/dart-lang/site-www/issues/4225 which also tracks this work.

Thanks again :)
