### ISSUE TITLE
Error occurs on 'Get the Dart SDK' page

### ISSUE THREAD

**Issue by S-dhakad** [dart-lang/site-www#5110]
### Page URL

https://dart.dev/get-dart/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/get-dart/index.md

### Describe the problem

error aari

**Comment by S-dhakad** [comment]
error aarahi hai

**Comment by parlough** [comment]
Hi @S-dhakad, thanks for opening an issue!

Could you provide some more information on the issue you're facing? We'd be happy to help you figure it out.

**Comment by parlough** [comment]
Hi!

I'm going to close this issue as there isn't enough information to help with the error you're seeing. If you have more information, please feel free to common here or open a new issue and we'd be happy to try to help. 

Thanks again!
