### ISSUE TITLE
[PAGE ISSUE]: 'All linter rules' are not sorted alphabetically

### ISSUE THREAD

**Issue by alexeyinkin** [dart-lang/site-www#5124]
### Page URL

https://dart.dev/tools/linter-rules/all.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/linter-rules/all.md

### Describe the problem

Lints should be sorted alphabetically to simplify diffing when upgrading to a newer SDK.
Lints were sorted on the older page that was here: https://dart-lang.github.io/linter/lints/options/options.html

**Comment by parlough** [comment]
Thanks for reporting this! It makes sense for them to be alphabetical, but I never considered this way of determining what lints are new.

My hope is they are consistently documented in the SDK changelog. We've also been discussing introducing a new index/discovery page for lints and that could perhaps have a way to sort by release (among other options).

**Comment by alexeyinkin** [comment]
I believe the older page did suggest to copy the entire list to analysis_options.yaml and then remove unwanted ones. That's the reason it was and still is a piece of valid YAML, and not just a list.

I have the same workflow of copying it. So this impacts someone like me.

**Comment by parlough** [comment]
I really appreciate that feedback and insight! If you have any other feedback on linter rules, discovering them, or their documentation please let us know. We're beginning to plan work around improving the linter docs currently :) 

Until the fix (https://github.com/dart-lang/site-www/pull/5126) is approved and merged, the [staged version of the change](https://dart-dev--pr5126-fix-5124-btxdo25y.web.app/tools/linter-rules/all) should have what you're looking for.

For additional reference, I believe the two new lints in Dart 3.1 are [`no_self_assignments`](https://dart.dev/lints/no_wildcard_variable_uses) and [`no_self_assignments`](https://dart.dev/lints/no_wildcard_variable_uses). Thanks again!
