### ISSUE TITLE
How to find out  each dart version analytics `lint_rules.json`?

### ISSUE THREAD

**Issue by LongXiangGuo** [dart-lang/site-www#5136]
How can we see each dart version analytics lint_rules.json? Are there exist some tag for each dart version?
https://github.com/dart-lang/site-www/blob/7417fbc77cbecbc47a333607a44de1b20ff0ce75/src/_data/linter_rules.json#L4

**Comment by parlough** [comment]
Sorry, I'm not sure I fully understand. 

In the file you linked, each linter rule has a `sinceDartSdk` field which indicates which Dart version it was added in.

Is that what you are looking for or do you want a version of the file for specific Dart releases?

**Comment by LongXiangGuo** [comment]
There are some warnings in my project, e.g `dead_null_aware_expression`, `unnecessary_set_literal `, but not found in the `[linter_rules.json](https://github.com/dart-lang/site-www/blob/7417fbc77cbecbc47a333607a44de1b20ff0ce75/src/_data/linter_rules.json#L4)`.  I want to which version of the `linter_rules.json` contains it. So I can update all packages's analysis_options.yaml in my package.

Local env
dart 3.10.6
analytics package: flutter_lints: 2.0.2

**Comment by LongXiangGuo** [comment]
local analyze issue that not in the `lint_rules.json` should add to error list and ignore it or fix them.

**Comment by parlough** [comment]
> There are some warnings in my project, e.g `dead_null_aware_expression`, `unnecessary_set_literal`, but not found in the `linter_rules.json`.

These are diagnostics(errors/warnings/hints) built in to the [Dart analyzer](https://dart.dev/tools/analysis) not linter rules. Linter rules must be explicitly enabled but analyzer diagnostics are enabled by default.

You can find a list of the analyzer diagnostics at https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/messages.yaml, including [`dead_null_aware_expression `](https://github.com/dart-lang/sdk/blob/7acb65004175deb237dae6eacc1d282a8d06605a/pkg/analyzer/messages.yaml#L21208) and [`unnecessary_set_literal `](https://github.com/dart-lang/sdk/blob/7acb65004175deb237dae6eacc1d282a8d06605a/pkg/analyzer/messages.yaml#L25395). Diagnostics with extra documentation are also documented at https://dart.dev/tools/diagnostic-messages.

Is that what you're looking for?

**Comment by LongXiangGuo** [comment]
Yes, thanks very much. I'am just want to know all the analytics database, and automatically do some check or ignores base one the `line_rule.json` and local dart analyze issue  in my project `analysis_options_for_pipeline.yaml`. Because there is huge of analyze issue.
