### ISSUE TITLE
[PAGE ISSUE]: 'Mixins'

### ISSUE THREAD

**Issue by feinstein** [dart-lang/site-www#5144]
### Page URL

https://dart.dev/language/mixins.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/mixins.md

### Describe the problem

I think we should expand the mixin docs, there are more details to them that are not in the tutorial.

For example, a `mixin` can have abstract functions, that should be declared into a class that uses the `mixin`, so on this sense a `mixin` can have `abstract` methods, or getters, etc, even though its not an `abstract class mixin`. I discovered this by exploring `mixin`, so I wonder what else I can do with them that I just didn't find out for myself.

Also we should be more emphatic about the `mixin` limitations, we only show them in the `class, mixin, or mixin class?` section for a little bit.

**Comment by parlough** [comment]
Thanks for opening the issue.

We definitely agree! We're tracking a rewrite in https://github.com/dart-lang/site-www/issues/4871, so I'll close this in favor of that issue and move your details there.

**Comment by feinstein** [comment]
Thanks!
