### ISSUE TITLE
Do both @Deprecated and @deprecated metadata annotations exist ?

### ISSUE THREAD

**Issue by marcmcd** [dart-lang/site-www#5164]
### Page URL

https://dart.dev/language/metadata.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/metadata.md

### Describe the problem

The text "Three annotations are available to all Dart code: `@Deprecated`, `@deprecated`, and `@override`."
refers to the `@Deprecated` and `@deprecated` annotations. Do both of these exist?
Other web Dart metadata references do not
mention the `@Deprecated` annotation but do mention the `@required` or the `@proxy` annotations as
being available to all Dart code.

### Expected fix

Replace "Three annotations are available to all Dart code: `@Deprecated`, `@deprecated`, and `@override`."
with"Three annotations are available to all Dart code: `@deprecated`, `@override`, and `@required`." 
or
Replace "Three annotations are available to all Dart code: `@Deprecated`, `@deprecated`, and `@override`."
with "Three annotations are available to all Dart code: `@deprecated`, `@override`, and `@proxy`." 

Then replace all occurrences of `@Deprecated` with `@deprecated` in the remaining text.

**Comment by parlough** [comment]
Hey @marcmcd, thanks for opening an issue!

`@Deprecated` is an available annotation in `dart:core` and is actually suggested over `@deprecated` as it allows you to specify a deprecation message. You can learn more on the [`Deprecated` API docs](https://api.dart.dev/stable/dart-core/Deprecated-class.html).

As for `@required`, it is an annotation present in `package:meta` ([API docs](https://pub.dev/documentation/meta/latest/meta/required-constant.html)), before [sound null safety](https://dart.dev/null-safety). It is however no longer used as [`required`](https://dart.dev/language/functions#named-parameters) is a built-in keyword in Dart 2.12 and later.

As for `@proxy`, that was an old annotation from Dart 1 that is no longer part of Dart. I'm curious where you saw this, as any mention to it should likely be updated.

---

Does that provide the information you are looking for? So `Deprecated`, `@deprecated`, and `@override` should still be the three annotations available in `dart:core`. There is also [`@pragma`](https://api.dart.dev/stable/3.1.1/dart-core/pragma-class.html), but it generally shouldn't be needed by users.

With this information, do you think we could improve the page or make it clearer? Should we link to the API docs for each annotation on the page? 

Let us know. Thanks for question and the details!

**Comment by marcmcd** [comment]
Hi Parker,

Thanks for the quick response.
That clears things up for me.

> "As for @proxy, that was an old annotation from Dart 1 that is no longer part of Dart.
I'm curious where you saw this, as any mention to it should likely be updated."

I found that reference to @proxy here:
	https://stackoverflow.com/questions/23476800/what-does-do-in-dart-programs
that post is over 9 years old, so as far as I know,  nothing currently needs to be updated to remove @proxy

> With this information, do you think we could improve the page or make it clearer?
> Should we link to the API docs for each annotation on the page?

How about adding the text in _**bold italics**_ below ? You can leave out the @deprecated example for brevity.
 
--------------------------------------------------------- 8< ---------------------------------------------------------
Metadata

Use metadata to give additional information about your code. A metadata annotation begins with 
the character @, followed by either a reference to a compile-time constant (such as deprecated) 
or a call to a constant constructor.

Three annotations are available to all Dart code: @Deprecated, @deprecated, and @override. 
For examples of using @override, see Extending a class. Here’s an example of using the 
@Deprecated annotation:

<code>
class Television {
  /// Use [turnOn] to turn the power on instead.
  @Deprecated('Use turnOn instead')
  void activate() {
    turnOn();
  }

  /// Turns the TV's power on.
  void turnOn() {...}
  // ···
}
</code>

_**The @deprecated annotation is used to indicate code that will be removed
in the next release with no alternative code provided, it is equivalent to**_

_**`@Deprecated('next release')`**_

_**For example:**_

_**`@deprecated`**_
_**`void shimCall() {`**_
_**`  // ···`**_
_**`}`**_

You can define your own metadata annotations. Here’s an example of defining a @Todo 
annotation that takes two arguments:

<code>
class Todo {
  final String who;
  final String what;

  const Todo(this.who, this.what);
}
</code>

And here’s an example of using that @Todo annotation:

<code>
@Todo('Dash', 'Implement this function')
void doSomething() {
  print('Do something');
}
</code>

Metadata can appear before a library, class, typedef, type parameter, constructor, 
factory, function, field, parameter, or variable declaration and before an import 
or export directive. You can retrieve metadata at runtime using reflection.


    ⟨  Comments                                                                          Libraries  ⟩
--------------------------------------------------------- 8< ---------------------------------------------------------


Regards,
Marc McDougall

**Comment by parlough** [comment]
Thanks for providing some specific suggestions :D 

We actually always [recommend](https://dart.dev/tools/linter-rules/provide_deprecation_message) to specify a message with `@Deprecated`, so any mention of just `@deprecated` should be light.

I opened https://github.com/dart-lang/site-www/pull/5169 with a potential solution. Consider taking a look :)

**Comment by marcmcd** [comment]
Hi Parker,
I like your changes, thanks for helping me participate in the Dart documentation. Over and out.

**Comment by parlough** [comment]
Thank _you_! 🫡
