### ISSUE TITLE
Implement tag feature to differentiate types on breaking changes page

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5168]
From [this comment](https://github.com/dart-lang/site-www/pull/5061#issuecomment-1717980568)

The different types of changes on the breaking changes page currently just use bold text to signify which type (if any). Parker had the idea to make them tags, which would make the page a lot less cluttered / a lot more refined:

<img width="494" alt="Example tags" src="https://github.com/dart-lang/site-www/assets/18372958/2ab50a8a-58a6-4f6a-8455-1ef709c76a22">

**Comment by atsansone** [comment]
This is a solid idea if we can determine how to accomplish this. If we remain with Bootstrap, this may not be an issue. Otherwise, we may need to do some digging.

**Comment by parlough** [comment]
I'm going to implement this with an include and custom html/css, no bootstrap. It won't be an issue.
