### ISSUE TITLE
404: doc comment guidelines

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#517]
A link on http://dart-lang.github.io/linter/lints/package_api_docs.html points to https://www.dartlang.org/articles/doc-comment-guidelines. We should

- [ ] fix the source _and_
- [x] add a redirect to https://www.dartlang.org/guides/language/effective-dart/documentation.

(edit by @chalin - reformatted into a task list)

**Comment by chalin** [comment]
Linter fix: https://github.com/dart-lang/linter/pull/870

**Comment by chalin** [comment]
We've done all we can for site-www. We'll track the lint rule update via https://github.com/dart-lang/linter/pull/870. Closing.
