### ISSUE TITLE
Document code coverage utility

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#52]
_From @sethladd on September 12, 2014 6:25_

cc @cbracken 

How do I get it? Run it? See the reports?

_Copied from original issue: dart-lang/www.dartlang.org#1026_

**Comment by kwalrath** [comment]
_From @sethladd on September 12, 2014 6:27_

I found this: https://github.com/dart-lang/coverage

Pretty decent README, but maybe we can help?

Also, we probably want to add it to our gallery of tools.

**Comment by kwalrath** [comment]
_From @srawlins on September 12, 2014 7:34_

Agreed! For now, there aren't really reports :/ it outputs lcov format, so then any tool that formats lcov into a report could be used.

But really there should be an end-to-end coverage reporting solution. Unfortunately that is a lot of work, in order to generate pretty HTML hierarchies like [Javascript's Istanbul](http://gotwarlost.github.io/istanbul/public/coverage/lcov-report/index.html), [Ruby's SimpleCov](https://github.com/colszowka/simplecov#example-output), [Coveralls (service)](https://coveralls.io/info/features), including incremental coverage, [Java's JaCoCo](http://www.eclemma.org/jacoco/trunk/coverage/), the psychadelically-colored [Go Cover](http://blog.golang.org/cover), ...

**Comment by kwalrath** [comment]
_From @cbracken on September 12, 2014 16:12_

LCOV can be converted to an HTML bundle using the [lcov](http://ltp.sourceforge.net/coverage/lcov.php) tool. We do have a rudimentary pretty-printer, but the end result is basically a giant text dump.

There are a couple fixes/cleanups I should apply to the [coverage](https://github.com/dart-lang/coverage) README; one example is using `--observe:NNNN` instead of `--enable-vm-service:NNNN --pause_isolates_on_exit`.

**Comment by kwalrath** [comment]
_From @srawlins on September 12, 2014 16:31_

Also of note: I think of that most languages do _not_ provide their own coverage (lcov-outputing) tools. Go and Ruby are 2 exceptions. So right now the dart-lang/coverage tool puts the language ahead of most others in terms of coverage-tooling.

That being said, dart is _behind_ other languages in that the community has not provided a report-generating solution yet; "I just want to put _something_ in my pubspec, run my tests, and `open coverage/index.html`" does not have an answer. We can only point to external tools, right now.

**Comment by kwalrath** [comment]
_From @sethladd on September 12, 2014 16:33_

Dart needs an extensible task runner where people can add tasks, like, oh, maybe code coverage? :)

**Comment by kwalrath** [comment]
_From @srawlins on September 12, 2014 22:19_

When you say "Document" code coverage utility, are you picturing a Tutorial?

**Comment by kwalrath** [comment]
_From @sethladd on September 12, 2014 23:33_

Eventually, we want a few tutorials on unit testing. First up, make it known that we have a way to generate code coverage. :)

**Comment by kwalrath** [comment]
_From @Sfshaza on August 12, 2015 16:48_

I sent Chris a CL 6 months ago to add this to the tools page but it wasn't stable yet. I just checked with him again and it's still not stable. Stay tuned...

**Comment by kwalrath** [comment]
_From @cbracken on August 12, 2015 17:24_

Yep - until the observatory coverage API is marked stable, I'm not convinced we can do the same with the coverage package.

**Comment by Sfshaza** [comment]
Just talked to @cbracken. The underlying VM service APIs are stable, so he plans on finalizing an API in the next month or two.

**Comment by kwalrath** [comment]
@cbracken is the API stable? I see from https://pub.dartlang.org/packages/coverage#-versions-tab- that the version isn't 1.0 yet.

**Comment by atsansone** [comment]
This issue covers concerns not within the current site and an external tool that the Dart team did not develop. Any issues with LCOV should be covered in their documentation. Closing this issue.

**Comment by parlough** [comment]
We actually have a package which interacts with Dart's VM service to collect coverage information(https://pub.dev/packages/coverage). We should likely still document this. I've opened a new issue at https://github.com/dart-lang/site-www/issues/4355 to cover that work.

**Comment by cbracken** [comment]
Thanks! I suspect that's what this issue was referring to -- I wrote that package a long time ago, but it's been maintained by others on the team for the last few years.
