### ISSUE TITLE
Update integration guidelines on 'Package layout conventions' page

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/site-www#5215]
### Page URL

https://dart.dev/tools/pub/package-layout.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/pub/package-layout.md

### Describe the problem

There is a mismatch between this page, and the flutter integration test guidelines https://docs.flutter.dev/testing/integration-tests#directory-structure. The flutter guidelines suggest a separate directory for integration tests, `integration_test`.

It is probably easiest to just add `integration_test` here as a general purpose convention?

This comes up for package:build_runner and builder authers - today we only include the `test` directory by default, and builders which typically only run on tests (like mockito) will also only run on the `test` directory. We use this page as a way to establish the conventions, so it would be best if it listed the flutter convention as well.

### Expected fix

Add `integration_test` as a new top level directory in the full package example.

Mention the `integration_test` directory in the [tests and benchmarks](https://dart.dev/tools/pub/package-layout#tests-and-benchmarks) section (possibly linking to the [flutter docs](https://docs.flutter.dev/testing/integration-tests#directory-structure)).

#### Possible Alternative

Change the flutter guideline to `test/integration/`. I have no idea how feasible this would be, or any of the context surrounding the current recommendation.

### Additional context

Gitter conversation with a (rightfully) confused user [here](https://matrix.to/#/!KKuvkJKBWeOujZonjg:gitter.im/$rdkWcixv24JadzNFqmKBWTo1G0YN7oFvs4d6ZPsFOBI?via=gitter.im&via=matrix.org).

If we had a more consistent convention, this would "just work" out of the box without any configuration.

**Comment by jakemac53** [comment]
cc @natebosch @jonasfj for thoughts also

**Comment by jakemac53** [comment]
cc @zanderso for the flutter side (feel free to involve somebody else). I don't know how attached you all are to the `integration_test` directory compared to a `test/integration` directory. I would have a slight preference for the latter, just because it makes "convention over configuration" stuff easier (most tools expect just `test/` today, and have to be updated). But I ultimately don't care, just wanted to throw it out there :).

**Comment by zanderso** [comment]
@dnfield or maybe @goderbauer can correct me, but I believe that directory layout is recommended by `package:integration_test`. However I don't know whether `package:integration_test` *requires* that layout, or if it could change.

**Comment by jakemac53** [comment]
Correct, it is a part of the [integration_test](https://docs.flutter.dev/testing/integration-tests#directory-structure) docs. But that effectively is introducing a new standard top level directory for flutter (and by extension dart).

I just want to either:

- Establish that as an official pattern, so other tools know to support it.
- Or, change the convention to `test/integration/`.

**Comment by goderbauer** [comment]
I believe package:integration_test doesn't care where the test is. But I am not sure if the flutter_tool does some magic to determine how to bootstrap a particular test based on the folder it is in since for integration tests it needs to generate a special bootstrapping script. Maybe @christopherfujino knows.

If we were to change the convention to `test/integration` we'd need to check how that interacts with running unit tests. Right now, I can just do a `flutter test` in my project folder to run all the unit tests in my test directory quickly. If there is an `integration` subfolder in my `test` folder, would `flutter test` now try to run these as well? That's likely not what most people want since those usually take longer to run.

**Comment by dnfield** [comment]
@jiahaog knows about the tooling magic I believe

**Comment by natebosch** [comment]
I think I lean towards adding a new convention for this top level directory. It matches what folks are already doing, and won't require any config by default.

**Comment by jiahaog** [comment]
The Flutter Tool is able to run tests in two modes:

- `flutter test`: default mode where it runs tests in `$package/test` on the flutter tester
- `flutter test integration_test`: "Integration test" mode where it runs [the tests in](https://github.com/flutter/flutter/blob/b097d2402222a7687eb4a3b9a6db6dc0fafcc288/packages/flutter_tools/lib/src/commands/test.dart#L622) `$package/integration_test` on a connected device

**Comment by jakemac53** [comment]
Ah ok it looks like they are incompatible entirely with regular unit tests in the same run, so then a separate top level directory is a good idea.

So I think we should update this page then, to mention that `integration_test` dir. There is a question of if we should call this out as specifically a "flutter integration tests" directory or a general integration tests directory.

@natebosch do you think we should mention this pattern at all in the `package:test` docs? It does seem like `flutter test` and `dart test` would behave quite differently though, since in the `dart test` world you could freely run these tests together with other tests. So I am a little hesitant to suggest this pattern if it doesn't translate well across flutter/dart.

**Comment by natebosch** [comment]
> do you think we should mention this pattern at all in the `package:test` docs?

I think it could be worth mentioning something about the directory and say that `dart test` ignores it by default.
