### ISSUE TITLE
The mode implementation is wrong

### ISSUE THREAD

**Issue by ZMensRain** [dart-lang/site-www#5222]
### Page URL

https://pub.dev/documentation/scidart/latest/numdart/mode.html

### Describe the problem

The implementation for finding mode does not return mode correctly mainly because mode is not always a single number like in [5,0,6,8,10,8,10] the mode is _10 _and_ 8_ so the mode function should return a list of double.

### Expected fix

I think this implementation is better than the one provided only problem with it is it will return the `uniqueDataPoints` if all of the doubles provided occur the same amount of times like in [1,1,2,2,3,3,4,4,5,5,6,6,7,7] 
```
List<double> mode(List<double> dataPoints) {
    final List<double> modes = [];
    final uniqueDataPoints = dataPoints.toSet();

    int maxFrequency = 0;

    for (var dataPoint in uniqueDataPoints) {
      var frequency =
          dataPoints.where((element) => element == dataPoint).length;
      if (frequency > maxFrequency) {
        maxFrequency = frequency;
        modes.clear();
        modes.add(dataPoint);
      } else if (frequency == maxFrequency) {
        modes.add(dataPoint);
      }
    }

    return modes;
  }
```

**Comment by danagbemava-nc** [comment]
Hi @ZMensRain, the documentation you have linked to is that of a third-party package: `scidart`. 

Kindly report this on their issue tracker so that it can be properly addressed. https://github.com/scidart/scidart/issues?q=is:issue+is:open+sort:updated-desc

Closing from here. 

Thank you
