### ISSUE TITLE
Fix description for constructor's super parameters

### ISSUE THREAD

**Issue by pnguyen9** [dart-lang/site-www#5227]
I was reading through the documentation for constructors, when I arrived here: https://dart.dev/language/constructors#super-parameters

The description says:

> Super-initializer parameters cannot be positional if the super-constructor invocation already has positional arguments, but they can always be named:

And then the code is as follow:

```
class Vector2d {
  // ...

  Vector2d.named({required this.x, required this.y});
}

class Vector3d extends Vector2d {
  // ...

  // Forward the y parameter to the named super constructor like:
  // Vector3d.yzPlane({required double y, required this.z})
  //       : super.named(x: 0, y: y);
  Vector3d.yzPlane({required super.y, required this.z}) : super.named(x: 0);
}

```

The description talks about positional arguments, and the shown example below has named arguments instead. Which one is it?

**Comment by parlough** [comment]
Thanks for the issue @pnguyen9!

The description is explaining a limitation of positional parameters, and leads into the named example by ending with "always be **named**:". Perhaps we can be more specific with "always be named as follows" or similar?

**Comment by pnguyen9** [comment]
Hmm, I think I understand the intent now. Perhaps it would help to split the quoted line into 2 distinct lines, with one wrong example?

I feel like something like this would be more clear, although the page might look bloated:

![image](https://github.com/dart-lang/site-www/assets/22443655/d41445a8-ebc7-4616-a11e-6fe2f54c0440)

**Comment by natebosch** [comment]
I think the most confusing part is this sentence:

> Super-initializer parameters cannot be positional if the super-constructor invocation already has positional arguments, but they can always be named:

I think this is easier to express with a bad example (do we use those in this type of doc?)

```dart
  // If the super constructor invocation (`super(0)` below) has any
  // positional arguments it is an error to use a super parameter.
  Vector3d.xAxisError(super.x): z = 0, super(0); // BAD
```

Then I might adjust the prose above the following example:

> When the super constructor has named arguments they may be split between named super parameters (`super.y` below) and named arguments to the super constructor invocation (`super.named(x: 0)` below).

And the following example can be kept as is.

**Comment by eernstg** [comment]
Drive-by comment: Wouldn't it be simpler to read if the part about invoking a super constructor named `Point2D.named` and the part about positional super parameters were presented in terms of two completely separate examples?

I think it's just too easy to assume that those topics have something to do with each other, whereas they are actually completely unrelated.

(And the pet peeve: "named constructors" is bad terminology. It seems to imply that we can invoke `Point2D.named` in the body of `Point2D` using just `named(...)`, and it seems to imply that there should be a name clash with an instance member named `named`, as there would be with a static declaration named `named`. That's the reason why I prefer to talk about a constructor named `Point2D.named` and another one named `Point2D`, and not about "named" and "unnamed" constructors ;-).
