### ISSUE TITLE
[3.2] Document new `dart create` CLI template

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#5249]
Commit reference: https://github.com/dart-lang/sdk/commit/dc6731ba201fd8e9b5d5c5a1c14359eae04efdb3

**Comment by Priyanshuthapliyal2005** [comment]
Can I work on this issue ,and can you explain what I have to done in this issue

**Comment by parlough** [comment]
Hi @Priyanshuthapliyal2005, thanks for offering to work on this!

This template needs to be added to the table of templates on the [`dart create` page](https://dart.dev/tools/dart-create) _([source](https://github.com/dart-lang/site-www/blob/main/src/tools/dart-create.md?plain=1#L31-L38))_.

The description `dart create --help` provides for this template is:

```
A command-line application with basic argument parsing.
```

We could also consider adding more details, such as specifying that it uses `package:args`. Maybe something like:

```
A command-line application with basic argument parsing using [`package:args`](https://pub.dev/packages/args).
```

Let me know if you have any other questions. Note that the PR won't be able to land until the Dart 3.2 stable release that contains the new template, but you can always create it early if you'd like. Thanks again :)
