### ISSUE TITLE
Document pattern guards

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#5255]
### What information is missing?

The docs for patterns are excellent and very comprehensive, but I was talking to a couple of folks on the team and realized that they don't cover guard clauses. Not too much of a surprise given how much other stuff there was to cover, but we should probably explain them too. :)

[Here is the relevant part of the spec](https://github.com/dart-lang/language/blob/main/accepted/3.0/patterns/feature-specification.md#guard-clause). Guards are allowed in switch statement cases, switch expression cases, and if-case statements:

```dart
// Switch statement:
switch (something) {
  case somePattern when some || boolean || expression:
    //             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Guard clause.
    body;
}

// Switch expression:
var value = switch (something) {
  somePattern when some || boolean || expression => body,
  //               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Guard clause.
}

// If-case statement:
if (something case somePattern when some || boolean || expression) {
  //                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Guard clause.
  body;
}
```

**Comment by MaryaBelanger** [comment]
Guard clauses [are in the language tour](https://dart.dev/language/branches#guard-clause), but kinda tucked away. They're at the end of the [Branches](https://dart.dev/language/branches) page now, where if, if-case, and switches are covered. Since they apply to any `case` I figured that was appropriate.

1. Your example is better, so I will definitely update that! 

2. But obviously people are expecting that content to be somewhere else where they're not finding it, which is no good. 
    
    So the main question here is, should Guard content move to the Patterns pages? Where would you or other teammates expect to find that info? Maybe keep the section in Branches, but also add a new section to [Pattern types](https://dart.dev/language/pattern-types) (it's kind of a type, I guess?)?

**Comment by munificent** [comment]
> Guard clauses [are in the language tour](https://dart.dev/language/branches#guard-clause), but kinda tucked away. They're at the end of the [Branches](https://dart.dev/language/branches) page now, where if, if-case, and switches are covered.

Oops! I totally missed them there. You know, I think of them as associated with patterns because they were added to the language at the same time that patterns were. But that may be a connection that exists largely in my mind. It probably makes sense to keep them where you have them.

> but also add a new section to [Pattern types](https://dart.dev/language/pattern-types) (it's kind of a type, I guess?)?

It's not quite a pattern type (it's a thing that goes *after* a pattern in a switch case or if case), but maybe it's worth linking to them from the patterns page somewhere?

**Comment by parlough** [comment]
I agree continuing to collocate with the branching/switch documentation makes the most sense.

It's clear that a few new cross references and cross links from the pattern page would be helpful though.

My initial thinking is in the [Switch statements and expressions](https://dart.dev/language/patterns#switch-statements-and-expressions) portion of the patterns page which already has an example using guards. We could just expand a tiny bit on them existing and when/why, with a cross link to learn more. 

There are likely a few other places we could squeeze a mention in too :)

**Comment by MaryaBelanger** [comment]
> My initial thinking is in the [Switch statements and expressions](https://dart.dev/language/patterns#switch-statements-and-expressions) portion of the patterns page which already has an example using guards.

And it doesn't even link to the guard section, there's the problem! 😅 I'll link that and add a small guard description inline there too. 

> collocate

Ohoho, new word for me! Thanks :)
