### ISSUE TITLE
Add example on how to destructure named records

### ISSUE THREAD

**Issue by flurrux** [dart-lang/site-www#5262]
### What information is missing?

i was reading the page about records, hoping to find out how to destructure records with named fields, but found nothing.  
[this section](https://dart.dev/language/records#multiple-returns) only showcases how to destructure a record with positional fields.  
i tried the following:
```dart
({ String name, int age }) userInfo() { ... }

void test(){
  // this is the pattern for positional fields. maybe it will work here.
  final ( name, age ) = userInfo();
  // i get the error:
  // The matched value of type '({int age, String name})' isn't assignable to the required type '(Object?, Object?)'
	
  // maybe use curly braces?
  final ({ name, age }) = userInfo();
  // nope:
  // The matched value of type '({int age, String name})' isn't assignable to the required type 'Map<Object?, Object?>'
}
```

### How would you like us to fix this problem?

would be nice to have an example for how to destructure named fields as well.

**Comment by flurrux** [comment]
thank you @parlough, i appreciate your help :)

**Comment by jonmountjoy** [comment]
I came here to request a feature that would allow me to do this - because the documentation is missing.   It really should be documented - it's a good and important feature.  I went for months without using field names because I couldn't destructure them nicely.
