### ISSUE TITLE
Upgrade to bootstrap 4

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#527]
[Bootstrap 4 (stable)](https://getbootstrap.com) is out! See the [official migration guide](https://getbootstrap.com/docs/4.0/migration).

---

### Config

- [ ] Tooltips and popovers: now provided by third-party `popper.js` which must be separately loaded.

### [Grid system](https://getbootstrap.com/docs/4.0/migration/#grid-system)

- [ ] Drop `$screen-*` variable overrides (they don't exist anymore)
- [ ] Replace:
  - `/@media\s\(min-width: \$screen-(\w*)-min\)/` with `@include media-breakpoint-up($1)`
  - `/@media\s*\(max-width: \$screen-(\w*)-min\)/` with `@include media-breakpoint-down($1)`
- [ ] A new tier below `sm` was added. Every tier has been bumped up one level:
  `xs` -> can go to nothing or `sm`, `sm` -> `md` -> `lg` -> `xl`.
  E.g., `.col-xs-6` -> `.col-6`, `col-md-6` -> `.col-lg-6`. This affects size-related class names in markdown, and media queries in CSS.

  The new `$grid-breakpoints` are:
   - `xs: 0`
   - `sm: 576px`
   - `md: 768px` (formerly `sm`)
   - `lg: 992px` (formerly `md`)
   - `xl: 1200px` (formerly `lg`)

### [Buttons](https://getbootstrap.com/docs/4.0/migration/#buttons)

- [ ] Renamed `.btn-default` to `.btn-secondary`.

### [Dropdowns](https://getbootstrap.com/docs/4.0/migration/#dropdowns)

- [ ] Use appropriate classes, such as the required `.dropdown-item`.
- [ ] Drop unnecessary custom caret.

### [Navs](https://getbootstrap.com/docs/4.0/migration/#navs)

- [ ] Use appropriate classes, such as the required `.nav`, `.nav-item`, etc.

### [Navbars](https://getbootstrap.com/docs/4.0/migration/#navbar)

- [ ] ...

### Dynamic elements

- [ ] Tooltips and popovers: slightly different config.

### Utils

- [ ] `.pull-right` -> `.float-right`

**Comment by bcko** [comment]
I am interested. May I get your guidance?

**Comment by chalin** [comment]
This is a major undertaking that needs to be coordinated across site-www and site-webdev. It also requires a good understanding of how styles are currently used across both sites.

Have you considered starting with beginner and [help wanted](https://github.com/dart-lang/site-www/labels/help%20wanted) issues?

**Comment by bcko** [comment]
Oh I see, I will start with beginner and help wanted issues.

**Comment by kwalrath** [comment]
Looks like we updated to bootstrap 4 in #1106 and followup PRs.
