### ISSUE TITLE
[SITE ISSUE]: Pages are shown with a background blue color

### ISSUE THREAD

**Issue by warcayac** [dart-lang/site-www#5307]
### Page URL

https://dart.dev/codelabs/dart-cheatsheet.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/codelabs/dart-cheatsheet.md

### Describe the problem

While I was [this page](https://dart.dev/tools/linter-rules/avoid_classes_with_only_static_members#usage) I clicked on a button on that page to change theme, to Dark in my case, several minutes after when returning to Dart site, all pages show a background blue color and there's no button to change theme anymore.

![image](https://github.com/dart-lang/site-www/assets/7342885/105c2614-d155-4278-a98d-044d1b5bff05)

This happened in Vivaldi browser, with other browsers is working fine with its default theme, light theme.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by atsansone** [comment]
Dart.dev doesn't include the ability to change theme in the site nor does it yet support dark mode. The Vivaldi has not been tested with this site, either. Recommend checking the [Vivaldi documentation for this](https://vivaldi.com/blog/android/android-4-4-2481-4/#:~:text=If%20you%20have%20dark%20theme,dark%20theme%20for%20any%20webpage.).

**Comment by warcayac** [comment]
The problem was caused by an extension updated recently, I've restricted its access to certain web page only. Regarding the button changing the theme, surely I must have been confused.
