### ISSUE TITLE
Retraction documentation

### ISSUE THREAD

**Issue by szakarias** [dart-lang/site-www#5315]
### What information needs to be added?

Add extra documentation on how to migrate away from retracted package versions.

### Where should this new content appear?

https://dart.dev/tools/pub/publishing#retract

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/d4f82b4f928e9994a5f05e2c6552544536cdd4f9

Thanks for writing this extra documentation!!
