### ISSUE TITLE
Correct example code on classes in "The Dart type system" page

### ISSUE THREAD

**Issue by duongdominhchau** [dart-lang/site-www#5320]
### Page URL

https://dart.dev/language/type-system

### Describe the problem

I don't see how renaming the class can change its meaning.

![image](https://github.com/dart-lang/site-www/assets/56427890/428132c6-03bf-44ee-81cd-ae650fc4100e)

### Expected fix

```dart
class Root {}
class HoneyBadger extends Animal {
  @override
  void chase(Animal a) { ... }

  @override
  Root get parent => ...
}
```

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by atsansone** [comment]
@lrhn : Would you have any insight here? Thanks!

**Comment by lrhn** [comment]
That does look wrong.
I'd probably change it to
```dart
class HoneyBadger ... {
  ...
  Object get parent ...
}
```
Or another animal like
```
  ...
  Cat get parent ...
```

**Comment by parlough** [comment]
Thanks for reporting this!

The core issue here was fixed by https://github.com/dart-lang/site-www/commit/2c438c83419d26b92376ab804aacc9396444819b

We have some other issues opening tracking other improvements to the page as well.
