### ISSUE TITLE
Provide RSS feed for new website content

### ISSUE THREAD

**Issue by RichardJECooke** [dart-lang/site-www#5321]
### Page URL

https://dart.dev/guides/whats-new.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/guides/whats-new.md

### Describe the problem

Putting https://dart.dev/guides/whats-new into Inoreader.com can't find any RSS or Atom feeds. Where on the page do you keep them please?

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
Hey @RichardJECooke, thanks for reaching out.

We don't currently provide a RSS feed or similar for new content on the website, but you can definitely add the RSS feed for the Dart blog (https://medium.com/feed/dartlang). Most new releases and other interesting articles will be announced there.

**Comment by RichardJECooke** [comment]
Thanks, but isn't Medium a paywalled thing?
