### ISSUE TITLE
[3.2] Quick review of 'Objective-C and Swift interop using package:ffigen'

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#5333]
### Page URL

https://dart.dev/guides/libraries/objective-c-interop.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/guides/libraries/objective-c-interop.md

### Describe the problem

We should do a quick review of this page to verify its up to date for Dart 3.2 and the current version of various Dart FFI packages.

### Expected fix

Either fix any outdated mentions or create issues to come back to it.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
@liamappelbe Would you be able to spend some time checking the page to see if it's up to date as of Dart 3.2 and the most recent releases of the FFI packages? Particularly in relation to limitations.

**Comment by liamappelbe** [comment]
I'll need to update the [multithreading caveats](https://dart.dev/guides/libraries/objective-c-interop#callbacks-and-multithreading-limitations) part to mention `NativeCallable`s, but the rest is fine.
