### ISSUE TITLE
[PAGE ISSUE]: 'avoid_empty_else'

### ISSUE THREAD

**Issue by FeBotero** [dart-lang/site-www#5341]
### Page URL

https://dart.dev/tools/linter-rules/avoid_empty_else.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/linter-rules/avoid_empty_else.md

### Describe the problem

I realized that the example of good practice was missing.

### Expected fix

BAD
`if (x > y)
  print("1");
else ;
  print("2");`

Good
`if (x > y)
  print("1");
else 
  print("2");`

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
Thanks for opening an issue!

Note that if you want to work on this yourself, the source is actually in the SDK repository: https://github.com/dart-lang/sdk/blob/main/pkg/linter/lib/src/rules/avoid_empty_else.dart

**Comment by parlough** [comment]
Fixed and expanded by https://github.com/dart-lang/sdk/commit/aabc9badd04ea07a769248f39ce01272604b7ee4

Thanks again for reporting this!! I really appreciate it :)

**Comment by FeBotero** [comment]
Parker, do you allow me to post a screenshot on my LinkedIn? I've been working with flutter for just over 5 months and when I read your answer I was very happy. I know this was a small thing, but for me it is incredible.

**Comment by parlough** [comment]
Hey @FeBotero, sure! I'm happy I was able to help and I hope your journey with Dart and Flutter is going well and continues for a long time 🥳 

I still really appreciate you catching and reporting this. It's extremely helpful to both me and every other developer who views the page. You suggesting this also helped us notice and fix other nearby issues. Perhaps these docs would have never been improved if you didn't spend time reporting this, so thanks again!

Let us know if you find any other issues or areas of improvement, or have any questions about Dart :D
