### ISSUE TITLE
[3.2] Add code excerpts to non-promotion-reasons

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5350]
Lots of new code examples in #5246, should convert them all to code excerpts. 

- `{:.bad}` snippets don't get an excerpt (just going to cause errors)
- Right now, all the examples share generic class names and field names... there might be a way to section off the code for the snippets but we're either going to have to change a lot of the identifiers to fit them in the same file, or make a few new files. TBD

**Comment by parlough** [comment]
> {:.bad} snippets don't get an excerpt (just going to cause errors)

Sometimes this is what we want as we can confirm code we expect to get an error actually has an error. Just like we confirm that code we want to be valid, is valid.

> Right now, all the examples share generic class names and field names.

There's lots of ways to solve this from nesting where possible, different files, or replace instructions on the code excerpts.
