### ISSUE TITLE
Take "Interop" contents out from under "Development"

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5364]
Right now "Interoperability" is nested under "Development" in the side nav. 
![image](https://github.com/dart-lang/site-www/assets/111139605/79c1e6fd-4e97-4f64-8c73-14c49eb4107f)

I know interop _is_ inherently about development, and it makes a lot of sense for it to be nested there. Moving it out to it's own section would objectively be _less_ organized than it's current position. 

But, with a lot of work to [JS interop](#4578) upcoming, and [C interop](#5269) always expanding, it'd be really nice to have a sidenav section where you can _see_ the expanded contents under each interop type. But the side nav only expands to the 3rd level. That means it won't be obvious that JS interop has a bunch of tutorials and reference pages underneath it, it's just going to look like there's nothing new there, and that's pretty underwhelming for such a big feature release.

So, like the language tour expansion to make way for all the new Dart 3 features we did earlier this year, can we move "Interoperability" to it's own top level section to be able to highlight new interop docs?

Any opinions @mit-mit @parlough @atsansone @sfshaza2, or anyone?

**Comment by parlough** [comment]
Ship it.

**Comment by parlough** [comment]
To expand on my comment. We have a lot of interop doc restructuring and work planned, and I expect there will soon be multiple subcategories, especially if we ever delve into tasks. Nesting too deep isn't good for discoverability, so we definitely should raise interopability up to a top-level category.

Even though we'll remove it in favor of newer material, content like the current "low-level HTML" docs would also fit well under interop. In the past, it was a core/primary part of Dart development, but now it is another form of platform interop.

I wonder if a more descriptive name like "Platform interop" would fit?

With that new name, docs about the new `package:platform` would fit right in!!
