### ISSUE TITLE
Update or replace sound types example on 'The Dart type system' page

### ISSUE THREAD

**Issue by Lebron1992** [dart-lang/site-www#5372]
### Page URL

https://dart.dev/language/type-system.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/type-system.md

### Describe the problem

In the `Use sound return types when overriding methods ` section, there is a code block:

```dart
// static analysis: error/warning
class Root extends Animal {
  @override
  void chase(Animal a) { ... }

  @override
  Root get parent => ...
}
```

I think the code block should be `static analysis: success`.

### Expected fix

The expected code block should be:

```dart
// static analysis: error/warning
class HoneyBadger extends Animal {
  @override
  void chase(Animal a) { ... }

  @override
  Root get parent => ...
}
```

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by danagbemava-nc** [comment]
Hi @Lebron1992, why do you propose this should be the case?

**Comment by eernstg** [comment]
The 'bad' example is indeed bogus. See https://github.com/dart-lang/sdk/issues/53621 for an explanation.

**Comment by wngtk** [comment]
The overridden `parent` getter method can return an Animal or any other subtypes of Animal.  Unrelated types include supertype.

How about use this case:
```dart
class Root extends Animal {
  @override
  void chase(Animal a) { ... }

  @override
  Object get parent => ...
}
```

At beginning of this section:
> The return type of a method in a subclass must be the same type or a subtype of the return type of the method in the superclass. Consider the getter method in the Animal class:

Counterexample:
Using the superclass of the return type of the method in the subclass.

If class `Root` extends class `HoneyBadger`, the `parent` getter method cannot return an Animal.

```dart
class HoneyBadger extends Animal {
  @override
  void chase(Animal a) {  }

  @override
  HoneyBadger get parent => HoneyBadger();
}

// static analysis: error/warning
class Root extends HoneyBadger {
  @override
  void chase(Animal a) {  }

  @override
  Animal get parent => Animal();
}
```
