### ISSUE TITLE
Language versioned changes on breaking changes page

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5422]
[This CL](https://dart-review.googlesource.com/c/sdk/+/342700) updating the breaking change definition in the sdk specifically says that language versioned changes are _not_ breaking changes, so we have to update [this](https://dart.dev/resources/breaking-changes#:~:text=in%20this%20list.-,Language%20versioned%3A,-The%20Dart%20SDK):

    This page includes the following types of breaking changes:
    ...
    - Language versioned:

I know we do want to keep labeling language versioned changes on that page, though, so maybe it's a matter of moving that label definition out of that list and saying something like "Language versioned changes are not breaking changes, but are also labeled on this page"

cc @leafpetersen

**Comment by leafpetersen** [comment]
The core issue is this: there are many, many things which are breaking changes in the sense that they may break somebody, somewhere.  In the web page you link to, we undertake to **document** a subset of those breaking changes, including language versioned breaking changes.  The markdown document which I am updating in the CL you point to on the other hand, intends to document a "contract" from the Dart team as to what subset of breaking changes we promise not to make without going through a formal process.  Does that make sense?  In a venn diagram sense, there's an outer ring of "all things which might break somebody", an inner ring of "things which we promise to at least document that we're doing (including language versioned changes", and a very inner ring of "things which we will strive not to do, and if we do do without warning everybody and going through a process (or a really, really, really urgent reason like security) we will undertake to roll back".  Not sure how best to capture that.

**Comment by MaryaBelanger** [comment]
Thanks for explaining, Leaf. I definitely misunderstood the context, and given the different purposes of each document, I don't think it's necessary to change any wording on the site. Closing this
