### ISSUE TITLE
'dart doc' has wrong link to Effective Dart

### ISSUE THREAD

**Issue by jeetparte** [dart-lang/site-www#5426]
### Page URL

https://dart.dev/tools/dart-doc.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/dart-doc.md

### Describe the problem

This link in the first paragraph is incorrect —

> For guidance on writing doc comments, see the [documentation part of Effective Dart](https://dart.dev/effective-dart/usage#do-use-strings-in-part-of-directives).

It goes to https://dart.dev/effective-dart/usage#do-use-strings-in-part-of-directives.

### Expected fix

The correct link should be https://dart.dev/effective-dart/documentation#doc-comments

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
Thanks for noticing and reporting this! Not sure how we didn't notice this earlier.

You mentioned you'd like to fix this. If you open a pull request to fix the link, I'd be happy to review :)

Let me know if you have any issues. Thanks again!
