### ISSUE TITLE
'Dart 2 Updates' page issue - how to install `dev`?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#549]
From URL: https://www.dartlang.org/dart-2

See https://github.com/dart-lang/sample-pop_pop_win/issues/54#issuecomment-362310415

**Comment by kwalrath** [comment]
Also has requests for doc on site-webdev.

**Comment by chalin** [comment]
I'd say that this has been resolved for each of the three OSs that we document installation instructions for: https://www.dartlang.org/tools/sdk#install. If you agree, please close this issue.
