### ISSUE TITLE
Wrong page look on Edge browser with `FastSave for Instagram` extension

### ISSUE THREAD

**Issue by asavchuk** [dart-lang/site-www#5490]
### Page URL

https://dart.dev/tutorials/language/streams.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tutorials/language/streams.md

### Describe the problem

In Edge browser this page looks definitely strange https://prnt.sc/peSCf2PysWw6
For example, in Crome, everything is fine.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by huycozy** [comment]
Hi @asavchuk 
Which Edge browser version are you using? It's `Version 121.0.2277.83 (Official build) (64-bit)` on my Windows machine but I don't see the issue.

![image](https://github.com/dart-lang/site-www/assets/104349824/f08fa6b3-9d1b-4cc3-b59d-00d3613195c7)

**Comment by parlough** [comment]
Could you also let us know what extensions you have enabled? Thanks!

**Comment by asavchuk** [comment]
Hi @huycozy 
Version 121.0.2277.83 (Official build) (64-bit)
checked it now again - the same look

**Comment by asavchuk** [comment]
These are enabled extensions for Edge
https://prnt.sc/PG38zrDrlCF2

**Comment by huycozy** [comment]
I see the issue now after installing [`FastSave for Instagram™ (reel, photo, story)`](https://microsoftedge.microsoft.com/addons/detail/fastsave-for-instagram%E2%84%A2-/mondbgjbcikfecobjjjhekcgkdfipada?hl=en-US) extension. It affects all pages in dart.dev. 

<details>
<summary>Demo</summary>

![image](https://github.com/dart-lang/site-www/assets/104349824/e291fba1-61a9-4128-ada6-caf3934b2a0f)

</details>

**Comment by parlough** [comment]
That is quite odd... Thanks for determining that @huycozy! This should probably be reported to the extension itself as it shouldn't touch/affect any site besides Instagram, as otherwise that's quite invasive.

I am curious if you inspect the blue background, where does the CSS inspector say the blue is coming from. I might be able to make some adjustments so there are no issues.

**Comment by huycozy** [comment]
@parlough I tried inspecting CSS but still haven't figured it out yet. Below are some information I found:

- When right-click on the extension > Click on `This can read and change site data` > Click on `When you click extension` > Click on `Refresh` button from its alert dialog: The dart page UI is back to normal, but only at that time. Once we refresh the page, issue appears again.
- When left-click on the extension > Click on `Desktop` icon button. It will open instagram.com site, but the splash seems to come from the extension (blue splash screen). This is indeed coming from extension but it's hidden in its source code. 

I recorded a video for these findings. If you have some ideas to investigate this further, please let me know.

https://github.com/dart-lang/site-www/assets/104349824/b35e4934-2ef1-4844-b793-b1396a4f106f

**Comment by atsansone** [comment]
@huycozy : Thank you for your investigation. 

@asavchuk : Thank you for raising this to our attention. It doesn't appear that this is an issue with the Dart.dev site that we can remedy. 

Closing this issue.
