### ISSUE TITLE
Event loop article references old bugs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#55]
_From @xxgreg on November 27, 2014 8:14_

https://www.dartlang.org/articles/event-loop/

Fixed: http://dartbug.com/9002
Assumed stale: http://dartbug.com/9001

Quote:

Due to bugs 9001 and 9002, the first call to scheduleMicrotask() schedules a task on the event queue; this task creates the microtask queue and enqueues the function specified to scheduleMicrotask(). As long as the microtask queue has at least one entry, subsequent calls to scheduleMicrotask() correctly add to the microtask queue. Once the microtask queue is empty, it must be created again the next time scheduleMicrotask() is called.

The upshot of these bugs: The first task that you schedule with scheduleMicrotask() seems like it’s on the event queue.

A workaround is to put your first call to scheduleMicrotask() before your first call to new Future(). This creates the microtask queue before executing other tasks on the event queue. However, it doesn’t stop external events from being added to the event queue. It also doesn’t help when you have a delayed task.

Another way to add a task to the microtask queue is to invoke then() on a Future that’s already complete. See the previous section for more information.

_Copied from original issue: dart-lang/www.dartlang.org#1165_

**Comment by kwalrath** [comment]
_From @zoechi on November 28, 2014 20:20_

Also 
- the referenced bug 13433 is closed since 10/2013
- the link `See the then() reference` is broken.

**Comment by kwalrath** [comment]
_From @sethladd on December 1, 2014 10:5_

Thanks!

**Comment by kwalrath** [comment]
_From @zoechi on December 2, 2014 14:3_

The comments about not having isolates in the browser might need some update too.

**Comment by kwalrath** [comment]
_From @skybrian on July 28, 2015 19:57_

Here's another bit needing updating: "Currently, the microtask queue contains only entries originating from within Dart code, but we expect the web implementation to plug into the browser microtask queue."

The related issue was closed:
https://github.com/dart-lang/sdk/issues/13433

But it's not clear to me what the resolution was. Are Dart and JavaScript microtasks put on the same queue now? Does it work the same for dart2js and Dartium?

**Comment by kwalrath** [comment]
This article has been on site-webdev (https://webdev.dartlang.org/articles/performance/event-loop) since the website split, but should perhaps be moved back to site-www.

**Comment by sethladd** [comment]
If that article is talking about the VM, then yes, please move it back to site-www :)

**Comment by kwalrath** [comment]
I don't think it's talking about the VM specifically, but since it focused on events, it seemed more webdev-y. However, I think it's more general.
