### ISSUE TITLE
Update outdated mention that factory constructors can return `null`

### ISSUE THREAD

**Issue by robsenshemsedin** [dart-lang/site-www#5506]
### Page URL

https://dart.dev/codelabs/dart-cheatsheet.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/codelabs/dart-cheatsheet.md

### Describe the problem

The Factory constructors section of this page, describes factory constructors as follows:

>  Dart supports factory constructors, which can return subtypes or even null.

  But factory constructors no longer return `null ` with null-safe Dart. 

### Expected fix

We need to update the existing description to something like, 

> Dart supports factory constructors, which can return instances of a class or even subtypes.

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
Great catch @robsenshemsedin! I'm surprised no one noticed this early. Thank you :D

You mentioned "I will try and fix this problem on dart.dev". Feel free to open a PR with the change and I'd be happy to review it. If you have any issues, let me know :)

**Comment by robsenshemsedin** [comment]
@parlough I have opened PR with a change to the definition of Factory constructors.
