### ISSUE TITLE
Add logos to Platform Overview page

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-www#551]
I'm not a designer... but I'd love to see large Flutter, AngularDart, and Dart logos in each of the three boxes to lighten up the page (https://www.dartlang.org/guides/platforms)

**Comment by kwalrath** [comment]
Agreed. Related to #537.

**Comment by kwalrath** [comment]
Here are the logos I found, after a quick look:

https://flutter.io/images/flutter-mark-square-100.png
https://github.com/dart-lang/logos/blob/master/logos_and_wordmarks/angulardart-logo.svg
https://github.com/dart-lang/logos/blob/master/logos_and_wordmarks/dart-logo.png
