### ISSUE TITLE
Simplify the Get Started page

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-www#552]
I love the simplification of the front page and hope that we could do something similar for this page...

I'd like to propose that we
1) turn the bullet list into a sentence: "This website (www.dartlang.org) contains information about the Dart _language_ and _core libraries_".
2) Move the "use case table" down below these two sentences and potentially replace it with the contents of the simpler "Platforms" page which has the same amount of information.
3) Remove the helpful flowchart. I don't think it's that helpful / adding much beyond the "plaforms" info.
4) I'd even consider removing the remaining three sections as well (books, samples, get help). The two latter are easily reachable from the menus.

**Comment by chalin** [comment]
Those sound like good simplifications.

With all the extra page real estate, why not add an _Install Dart_ section, similar to this one from the  [webdev Get Started page](https://webdev.dartlang.org/guides/get-started):

> <img width="574" alt="screen shot 2018-02-02 at 09 32 13" src="https://user-images.githubusercontent.com/4140793/35738172-0d5d03e0-07fc-11e8-8e0a-5f365333cf42.png">

**Comment by chalin** [comment]
Might we want to mention Dart 2, and have a link to the /dart-2 page, either on the front page or the get started page? Currently it is hard to find a link to the Dart 2 page.

**Comment by kwalrath** [comment]
About the install Dart thing... Potential Flutter devs might be the majority of users, and we don't want them to install the SDK separately. I should clarify that. Let me think about the rest...
