### ISSUE TITLE
[PAGE ISSUE]: 'Dart overview'

### ISSUE THREAD

**Issue by cheeta1002** [dart-lang/site-www#5520]
### Page URL

https://dart.dev/overview/

### Page source

https://github.com/dart-lang/site-www/tree/main/./src/content/overview.md

### Describe the problem

The current Dart SDK version is 3.0.5.

Because task depends on dependencies any which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.0.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by darshankawar** [comment]
@cheeta1002 
Can you elaborate what exactly is the issue you are facing in the overview page ?
