### ISSUE TITLE
Install page should list Flutter SDK as an option

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#5536]
### Page URL

https://dart.dev/get-dart#choose-an-install-option

### Page source

https://github.com/dart-lang/site-www/blob/main/src/content/get-dart/index.md

### Describe the problem

We list the following options to install the Dart SDK:

1. Use a package manager (Recommended).
2. Use a Dart Docker image
3. Download from the SDK Archive
4. Build the SDK from source

### Expected fix

Include an option to install the Flutter SDK. Installing the Flutter SDK installs the Dart SDK too.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
\cc @atsansone Since you recently overhauled this page.

**Comment by atsansone** [comment]
Quick check with product management before I start, but otherwise sounds good.
