### ISSUE TITLE
Dart SDK 3.3.0 not published on Chocolatey because Dart SDK icon was moved

### ISSUE THREAD

**Issue by athomas** [dart-lang/site-www#5570]
### Page URL

https://community.chocolatey.org/packages/dart-sdk

### Describe the problem

The site no longer serves https://dart.dev/assets/shared/dart/icon/64.png which is referenced in chocolatey packages.

https://github.com/dart-lang/chocolatey-packages/blob/7f5b6d7ceaaae52784dd10ccfbcb71d0d37b4d08/dart-sdk/dart-sdk.nuspec#L18

This blocks 3.3.0 from being published which was noticed by users:
http://disq.us/p/2xquz36

### Expected fix

We need to fix the URL in chocolatey-packages or restore the URL on the site to unblock the chocolatey publishing.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by whesse** [comment]
The image file was moved to https://dart.dev/assets/img/logo/dart-64.png by change https://github.com/dart-lang/site-www/pull/5483

**Comment by athomas** [comment]
Thanks @parlough! The redirect has fixed chocolatey's validation.
