### ISSUE TITLE
internationalization of the website in at least the 5 most spoken languages in the world

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [dart-lang/site-www#5571]
### Describe the problem

The problem is being able to learn the Dart language. I am a business consultant in Latin America where Spanish is spoken and junior people always tell me that they have to make a double effort because they have to learn English or translate the documentation to learn, this is a barrier. entry for new users Dart is having a hard time gaining ground as the main language for many programmers according to the Tiobe index, if we want to enter at least in the top 10 we must create solutions so that more programmers learn Dart. According to Gemini, the 5 most spoken languages are: [link](https://g.co/gemini/share/6dc86cad7bff)

### Expected fix

From my point of view, being able to read the documentation of the dart.dev website in Spanish now Google has Gemini which is a tool that can help with the translation of the documentation, in real time. From the year 2022 we enter the era of artificial intelligence and Dart is no exception, we must use the tools to advance and solve the problem of the shortage of programmers in Dart

### On which browser(s) did you experience this issue?

Other

### Additional context

In the programming language market there is tough competition with Python and Javascript, I think Dart is superior but we must prove it, Dart should be an alternative language to Python for artificial intelligence issues, I think Dart and AI should be one. Thanks to Google Gemini we can evolve Dart

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by huycozy** [comment]
Thanks for the report! 

This is a similar issue being tracked at https://github.com/dart-lang/site-www/issues/2274. Please add there a comment with your information here. 

Closing this issue as a duplicate, please follow up on it for further updates.
