### ISSUE TITLE
Possible error in README about Node version constraint

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5576]
[Line 72](https://github.com/dart-lang/site-www/blob/main/README.md?plain=1#L72) says Node has to be version 20 _or later_. I had `20.0.0` installed. But, `corepack enable` didn't work for me until I upgraded node. 

Unfortunately I closed the terminal without saving the complaint from corepack about updating (and it's possible that closing and reopening the terminal is what solved the issue), but maybe it's worth someone else testing to see if we need to change the guidance to a newer version (I think it told me `>=20.5.0` or `>=20.20.0`)

**Comment by huycozy** [comment]
I'm using Node `v20.11.1` but don't see any issue with `corepack` commands (enable or install) on my machine. It would be helpful for investigation if you could find the history of command's output.

**Comment by huycozy** [comment]
I checked [nodejs v20.0.0 changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2023-04-18-version-2000-current-rafaelgss) but I still see `corepack` is mentioned:

```
deps: update corepack to 0.17.2 (Node.js GitHub Bot)
```

I'm not sure if we should update the version constraint in the docs or not as there is not much information (history command output or error stack trace). Will label this for other's input.

**Comment by huycozy** [comment]
You're welcome. Yes, I think we can close the issue. Once someone else also experiences this, we can re-open and investigate this further.
