### ISSUE TITLE
[PAGE ISSUE]: 'Dart overview' Clicking On DartPad Links Leads To "Page Not Found" Error Page

### ISSUE THREAD

**Issue by victoreronmosele** [dart-lang/site-www#5586]
### Page URL

https://dart.dev/overview/

### Page source

https://github.com/dart-lang/site-www/tree/main/./src/content/overview.md

### Describe the problem

Clicking on "open this example in its own window" leads to "Page Not Found" error page.

https://github.com/dart-lang/site-www/assets/19398044/98a54c62-07d6-40f0-ba14-6209371d043c

### Expected fix

Clicking on "open this example in its own window"  opens the correct DartPad page.

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by victoreronmosele** [comment]
The [GitHub gist ](https://gist.github.com/parlough/bc63d212c3252e44058ff76f34ef5730)linked to the broken DartPad link doesn't follow the DartPad [Sharing Guide](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide).

It doesn't have a `main.dart` as required by the guide. It has a `montecarlo.dart` instead.

**Comment by parlough** [comment]
> It doesn't have a main.dart as required by the guide. It has a montecarlo.dart instead.

Thanks for noticing this! DartPad never officially supported other Dart file names, but it used to work by chance. I've gone ahead and updated the filename in the gist :)

**Comment by victoreronmosele** [comment]
Thanks for the quick response! I'll send a PR shortly!

**Comment by victoreronmosele** [comment]
Here's the PR: https://github.com/dart-lang/site-www/pull/5589. :)
