### ISSUE TITLE
Diagnostics page missing from sidenav 

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5598]
@parlough wanted to check if this is intentional since you've done major work on the diagnostics and lints most recently. I vaguely remember [_Diagnostics_](https://dart.dev/tools/diagnostic-messages) used to be listed under the _Tools..._ umbrella in the sidenav, but it's not there anymore. Lmk if this is intentional or if you have any insights, otherwise I'd like to add it alongside _Linter rules_. Thanks!

**Comment by parlough** [comment]
I think I removed it intentionally as it's not super useful to visit on its own until we have some docs to explain diagnostics themselves. So eventually I planned to add it back :P

I'm more than fine with adding it back if it's helpful to you!

**Comment by atsansone** [comment]
@MaryaBelanger : Your call. If you're okay with it being gone for the time being, close this issue.
