### ISSUE TITLE
Better doc organization for Browser/Server

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#56]
_From @aikar on December 23, 2015 7:7_

Looking at the docs, it's not immediately clear (without digging and intuition) which dart API's are browser oriented, server oriented or both.

There's a warning on top of dart:io, but that could easily be missed.

Then you have things like dart:web_gl, which by intuition you can figure out, but outside of that, it's not immediately clear that its browser only.

I suggest categorizing the docs as 
- Browser Only
- Server Only
- Both

Then by section it's immediately clear the intent for each library

_Copied from original issue: dart-lang/www.dartlang.org#1539_

**Comment by Sfshaza** [comment]
_From @kwalrath on January 4, 2016 22:8_

Yes, this could and should be clearer.

@aikar: Could you please list a few URLs for the docs you found particularly confusing?

**Comment by kwalrath** [comment]
I think the new api.dartlang.org takes care of this problem.

![image](https://user-images.githubusercontent.com/2164483/50718150-801fd800-1041-11e9-88de-0aa09f33cb3b.png)
