### ISSUE TITLE
Correct the explanation on `Extension types` page

### ISSUE THREAD

**Issue by eernstg** [dart-lang/site-www#5610]
### Page URL

https://dart.dev/language/extension-types/

### Page source

https://github.com/dart-lang/site-www/tree/main/./src/content/language/extension-types.md

### Describe the problem

The sentence 

> An expression with the extension type `E` and the representation type `R` as its static type will be an object with type `R` at run time.

is slightly misleading. The problem is that we can read 'the representation type `R` as its static type' (and forget about 'the extension type `E`'), and conclude that the static type of the expression is `R`.

The static type of the expression is actually `E`, and the type `E` has a representation type which is denoted by `R` here, but `R` itself doesn't have any guaranteed relationship with the static type of that expression.

### Expected fix

We could say the following:

> If `e` is an expression whose static type is an extension type `E`, and the representation type of `E` is `R`, then the run-time type of the value of `e` is a subtype of `R`.

It is not guaranteed that the run-time type of this object is precisely `R`, and `e` might have many different values because we could reach that location in code and evaluate it many times, but it might still be OK to say that 'the run-time type of `e` is `R`', which would make it a bit less heavy.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
@MaryaBelanger Would you have time to consider and account for these adjustments?

**Comment by MaryaBelanger** [comment]
Thanks @eernstg, my mistake. I'll take your suggestion here, but I can also see now that in trying to abbreviate [your suggestion](https://github.com/dart-lang/site-www/pull/5557#discussion_r1492244349) from the last PR: 

> If an expression has an extension type `E` with representation type `R`
as its static type then _the value at run time will be an object_ with type `R`,

I totally removed the part where it's _the value_ of the expression at run time, not the type of the expression or extension type itself like I made it seem. Can't take any shortcuts when it comes to type system docs! 😅

**Comment by eernstg** [comment]
It's always tricky to decide on how explicit we have to be: An expression has a static type, but not a run-time type &mdash; only the _result_ of a specific expression evaluation has a run-time type (we could run the program many times, and each run could evaluate that expression many times). Next, that run-time type is always a subtype of the static type, and that 'subtype' concept always allows that run-time type to be the exact same type as the static type, plus all the proper subtypes, and so on. So can we ever say that "the expression `e` has the run-time type `T`", or do we have to include at least some of those intermediate steps, and if so which ones? :grin:

I think we'll have to try to listen carefully to users of the site, when we get the opportunity, in order to hear when a shortcut is too short (such that it creates misunderstandings), and then fill in a few more details.
