### ISSUE TITLE
Fix Exception exercise in 'Dart cheatsheet codelab' page

### ISSUE THREAD

**Issue by dtonhofer** [dart-lang/site-www#5615]
### Page URL

https://dart.dev/codelabs/dart-cheatsheet/

### Page source

https://github.com/dart-lang/site-www/tree/main/./src/content/codelabs/dart-cheatsheet.md

### Describe the problem

This is a bit of a nitpick: The solutions provided for the exercise in the section [Exceptions](https://dart.dev/codelabs/dart-cheatsheet#exceptions) unaccountably gives the Exception's actual runtime type to the logger in one case, but not in the other:

```
void tryFunction(VoidFunction untrustworthy, Logger logger) {
  try {
    untrustworthy();
  } on ExceptionWithMessage catch (e) {
    logger.logException(e.runtimeType, e.message);  // passes runtimeType here
  } on Exception {
    logger.logException(Exception);  // but only passes type "Exception" here
  } finally {
    logger.doneLogging();
  }
}
```

This is also in contradiction with the exercise statement, which is:

- If `untrustworthy()` throws an `ExceptionWithMessage`, call `logger.logException` with the exception type and message (try using `on` and `catch`).
- If `untrustworthy()` throws an `Exception`, call `logger.logException` with the exception type (try using `on` for this one).

### Expected fix

Just stay on target:

```
void tryFunction(VoidFunction untrustworthy, Logger logger) {
  try {
    untrustworthy();
  } on ExceptionWithMessage catch (e) {
    logger.logException(e.runtimeType, e.message); 
  } on Exception {
    logger.logException(e.runtimeType);
  } finally {
    logger.doneLogging();
  }
}
```

The above also passes the check.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by atsansone** [comment]
@dtonhofer : Small error that needed fixing:

```dart
void tryFunction(VoidFunction untrustworthy, Logger logger) {
  try {
    untrustworthy();
  } on ExceptionWithMessage catch (e) {
    logger.logException(e.runtimeType, e.message); 
  } on Exception catch(e) {
    logger.logException(e.runtimeType);
  } finally {
    logger.doneLogging();
  }
}
```

`e` is scoped to the Exception, so both Exceptions need it.
