### ISSUE TITLE
Parenthesized patterns text is misleading

### ISSUE THREAD

**Issue by whesse** [dart-lang/site-www#5653]
### Page URL

https://dart.dev/language/pattern-types#parenthesized

### Page source

https://github.com/dart-lang/site-www/blob/main/src/content/language/pattern-types.md?plain=1#L291

### Describe the problem

The text says that the pattern `x || y && z` evaluates `y && z` first because logical-and patterns have higher precedence than logical-or.

But in this case, the pattern `x` is evaluated first, and evaluates to true, and the patterns `y` and `z` and the pattern `y && z` are not evaluated at all (and would be evaluated second if x were false).

The example can't really be changed, because && and || are the only binary operators where parentheses can meaningfully be introduced.

Perhaps just say "the subpattern y && z is evaluated" versus "the subpattern x || y is evaluated". Or just say that `x || y && z` is equivalent to `x || ( y && z )`, which is different from `( x || y ) && z` . And don't talk about "evaluated first".

I also think that any example where the different parentheses give different results will also shortcut in at least one case, and not evaluate all the subpatterns, which makes it hard to make an example.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by eernstg** [comment]
Good catch! It is an astonishingly common mistake to characterize the effect of syntactic precedence in terms of "evaluate the part with higher precedence before the part with lower precedence", in spite of the fact that it is wrong.

Here's an example showing that it does matter:

```dart
class C {
  final StringBuffer buf;
  C(String s) : buf = StringBuffer('Top operator is `$s`: ');

  bool _f(String s) {
    buf.write(s);
    return true;
  }
  
  bool get a => _f('a');
  bool get b => _f('b');
  bool get c => _f('c');
}

void main() {
  var c = C('&&');
  switch (c) { case (C(a: true) || C(b: true)) && C(c: true): break; }
  print(c.buf);
  c = C('||');
  switch (c) { case C(a: true) || (C(b: true) && C(c: true)): break; }
  print(c.buf);
}
```
