### ISSUE TITLE
[PAGE ISSUE]: 'Asynchronous programming: Streams'

### ISSUE THREAD

**Issue by riccardohacker** [dart-lang/site-www#5660]
### Page URL

https://dart.dev/tutorials/language/streams/

### Page source

https://github.com/dart-lang/site-www/tree/main/./src/content/tutorials/language/streams.md

### Describe the problem

DartPads have always the same code (a simple for loop printing numbers from 1 to 10), so it's difficult to understand because examples mentioned are not visible.
Thank you, have a good day :)

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by atsansone** [comment]
@riccardohacker : Thank you for bringing this to our attention!

To clarify, are you referring to the second DartPad on that page? If so, it does display the 1..10 _if_ you first click **Run**.

![Image](https://github.com/dart-lang/site-www/assets/706219/32c6ddf0-31ac-4d4e-9105-e3506eed6290)

Please let us know if this resolves your concern.

**Comment by riccardohacker** [comment]
Sorry if i didn't posted any screenshot. I see that exact code and output in both the embedded dartpads of that page

**Comment by parlough** [comment]
Thanks for reporting this issue! I'm going to close this in favor of https://github.com/dart-lang/dart-pad/issues/2893 which tracks the core issue, which I'll work on soon.
