### ISSUE TITLE
[PAGE ISSUE]: 'Asynchronous programming: futures, async, await'

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/site-www#5669]
### Page URL

https://dart.dev/codelabs/async-await#example-async-and-await-with-try-catch

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/codelabs/async-await.md

### Describe the problem

The example code supplied for demonstrating how to handle errors in asynchronous code is not right. The lead in states:

> Run the following example to see how to handle an error from an asynchronous function. What do you think the output will be?

But the sample code is:

```dart
void main() {
  for (int i = 0; i < 10; i++) {
    print('hello ${i + 1}');
  }
}
```

Which has zero errors and zero asynchronous functions.

### Expected fix

Sample code that demonstrates the issue being discussed in the code. In fact, this sample seems to be boilerplate as it is repeated multiple times on the page.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
Yeah. The injection script has an issue with sending events at the wrong time. I'm investigating now - https://github.com/dart-lang/dart-pad/issues/2893
