### ISSUE TITLE
[3.4] Macros experiment page

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5692]
Plan for macros documentation work in the Dart 3.4 release.

## Summary
A single json serialization macro will be in `main` (probably behind a flag) by the 3.4 release. The feature will be advertised alongside this release, so we'll create an "experiment" page for users to learn more from when they hear about the feature. 

Users will not be able to write their own macros in the 3.4 stable release.

## Goals

- Introduce users to macros before the full implementation is complete.
- Teach users how to use the new json serialization macro.
- Showcase the cool features of macros and get users excited for the upcoming feature.
- Be VERY clear this is not available yet
  - Main feature completely unavailable, loose/hopeful timeline
  - Example macro behind flag, how to try it out

## Doc plan/eval

- Create a page at `dart.dev/language/macros`
- Hide from the side nav for now
- Redirect temporary link: https://github.com/dart-lang/site-www/issues/5685
- Clear note at the top about availability / timeline (or lack thereof)
  - (from [comment](https://github.com/dart-lang/site-www/issues/5692#issuecomment-2083735409)): direction on where to leave feedback (different repos, language, analyzer, specific issues? etc), what levels of feedback are welcome, etc
- Introduce macros at a high-level, how they work (feature as planned), why they're cool
  - General flow: custom macro, configurations, diagnostics, using a macro, generated augmentation, etc.
  - User experience improvements over other codegen:
    - integrated into Dart, don't have to run anything separate
    - no referencing weird generated symbols, things get added directly
    - significantly faster than other codegen
    - massively improved test experience
- Introduce serialization macro, how to use it / development experience of using it:
  - _This section will eventually move to the JSON serialization page_
  - Benefits over other serialization options
  - Actual steps with examples: 
    - Append annotation, creates ToJson method and FromJson constructor
    - Use any configurations
    - Show the augmentation file/updating (e.g. change field name, comment out annotation) in real time in the IDE
    - Emitting custom diagnostics
  - (maybe) Basic "migration" from json serializable package?
    - remove `part`, change annotation name, `dart run yourProgram` instead of running buildrunner, etc...

### Future

https://github.com/dart-lang/site-www/issues/5722

## Resources

- Serialization macro code: https://github.com/dart-lang/sdk/tree/main/tests/language/macros/json:
  - The macro itself [json_serializable.dart](https://github.com/dart-lang/sdk/blob/main/tests/language/macros/json/json_serializable.dart)
  - Tests (closest to usage example) [json_serializable_test.dart](https://github.com/dart-lang/sdk/blob/main/tests/language/macros/json/json_serializable_test.dart)
  - Annotation used alongside macro [json_key.dart](https://github.com/dart-lang/sdk/blob/main/tests/language/macros/json/json_key.dart)
- Static metaprogramming language [issue](https://github.com/dart-lang/language/issues/1482) 
- Feature [spec](https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md)
- Previous serialization solutions:
  - ([json_serializable package](https://pub.dev/packages/json_serializable))
    - [Example](https://github.com/google/json_serializable.dart/blob/master/example/lib/example.dart) of using previous solution
    - Example of generated code from existing serialization code generator [example.g.dart](https://github.com/google/json_serializable.dart/blob/master/example/lib/example.g.dart)

**Comment by pattobrien** [comment]
I've been experimenting with macros for about 4 months now, from a package-author perspective, and have experienced everything from minor feature questions to unrecoverable analyzer crashes that require IDE restarts (to be expected at this stage, of course).

One topic not explicitly stated in the above checklist is what levels of feedback would be welcome and where that feedback should be made, which I think would be helpful for both the Dart team as well as package authors.

**Comment by MaryaBelanger** [comment]
That's a great point @pattobrien, added to the plan (and other plans too, this is a great point for any documentation plan!)

In the mean time, so you don't have to wait for the docs to come out to start filing those issues, feel free to bring up any concern large or small on the [language repo](https://github.com/dart-lang/language/issues) (or find an existing issue there to discuss your experience). User feedback from 4 months of experience is incredibly valuable for this feature!

If you specifically want to call out something you want to make sure gets documented, you can leave comments on this issue or open an issue in [this repo](https://github.com/dart-lang/site-www/issues) and link to this issue (#5692) so it gets tracked. 

In the actual macros docs I'll probably only point users to the language repo for feedback, but in your case I think you should document your analyzer crash in the [sdk repo](https://github.com/dart-lang/sdk/issues) since that's where the analyzer lives (and it sounds pretty major, I'm sure they'd love to know about it)
