### ISSUE TITLE
library tour: document AsyncError replacement

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#57]
_From @nicolasgarnier on December 4, 2014 13:35_

_From @kwalrath on April 16, 2013 20:57_

ch03's example of reading files (ch03/ch03_2_html/web/app.dart) used to use AsyncError. AsyncError is gone now, so I removed that type. Perhaps we should use getAttachedStackTrace()?

In any case, we need to improve our coverage of async errors, both now and when they've come up with a better solution.

_Copied from original issue: dart-lang/dart-up-and-running-book#37_

_Copied from original issue: dart-lang/www.dartlang.org#1182_

**Comment by kwalrath** [comment]
_From @nicolasgarnier on December 4, 2014 13:35_

_From @kwalrath on April 16, 2013 20:58_

To be clear, here's the affected code in app.dart:

// PENDING: We should do more explicit error handling, once it's available. 
handleError(error) {
  print('Uh oh, there was an error.');
  print(error.toString());
}

**Comment by Sfshaza** [comment]
I'm not sure when it came back, but AsyncError is back. And, of course, if you're using the async/await language features, you can catch any errors. Closing.
