### ISSUE TITLE
Please remove "Dartosphere Blog Aggregator"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/site-www#570]
Unmaintained link @ https://www.dartlang.org/community.

**Comment by natebosch** [comment]
https://www.dartosphere.org/ is working for me

**Comment by chalin** [comment]
The link works for me. It leads to this:
<img width="1188" alt="screen shot 2018-02-12 at 14 08 10" src="https://user-images.githubusercontent.com/4140793/36114504-3191b396-0ffe-11e8-9634-0216bc0598c2.png">

**Comment by matanlurey** [comment]
Right, but as-per https://groups.google.com/a/dartlang.org/forum/#!topic/misc/qd5o2UZIio4, it's dead - as-in, not maintained.

**Comment by Kirrrr** [comment]
**www**.dartosphere.org is ok.
dartosphere.org is just incorrect because domain doesn't have no-www DNS record.

**Comment by matanlurey** [comment]
Ah, my confusion. OK, I'll leave this up to @kwalrath and @chalin. Close if you like.

**Comment by Kirrrr** [comment]
I think it would be better to inform Dartosphere maintainers about this issue. Www-only domain is a quite risky thing I guess.

**Comment by chalin** [comment]
@anders-sandholm recently updated the URL via #565 (adding the "www."), so I'll leave this as is for now.
