### ISSUE TITLE
.pub -> .dart_tool/pub

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#571]
Soon the place where pub hides its files will change (see dart-lang/sdk#32030). We need to update pages and scripts that refer to the old place. I found the following mentions of `.pub`:

* site-www/src/_guides/libraries/private-files.md:.pub/
* site-www/src/_tutorials/dart-vm/get-started.md:.pub
* site-www/src/tools/pub/cmd/pub-get.md:`packages` directories, or `.pub` directory (when present)

I should also fix, site-www/src/tools/pub/installing.md, which refers to `.pub_cache` (but should presumably be `.pub-cache`; I believe `~/.pub-cache` is unaffected).

**Comment by bcko** [comment]
@kwalrath @chalin 
The first two pages are already updated as shown below.

https://github.com/dart-lang/site-www/blob/master/src/_guides/libraries/private-files.md
> Don’t commit the following files and directories created by pub:
> ```
> .dart_tool/
> .packages
> build/
> pubspec.lock  // Except for application packages
> ```

https://github.com/dart-lang/site-www/blob/master/src/_tutorials/dart-vm/get-started.md
> Some of the files and directories in the hello_world app include the following:
> .dart_tool
> Support files used by pub and other Dart tools. You can ignore this.

I wasn't sure about the third page. 
The third page mentions doesn't mention `.pub` but `.pub-cache` and `packages`.

**Comment by kwalrath** [comment]
Thanks for checking, @bcko! I'll take a look at the third page.

**Comment by kwalrath** [comment]
I just took another look at these files, and the references to .pub* filenames all seem to be correct now.
