### ISSUE TITLE
Update 'Dart's core libraries' page

### ISSUE THREAD

**Issue by jarrodcolburn** [dart-lang/site-www#5716]
### Page URL

https://dart.dev/libraries#web-platform-libraries

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/libraries/index.md

### Describe the problem

Chart at bottom https://dart.dev/libraries#web-platform-libraries may need updating 
![image](https://github.com/dart-lang/site-www/assets/16673615/0dab92bf-c295-4a15-a0a3-7c4f2c4c5e65)

### Expected fix

Should either be revised or note the Note the next generation Js Interop in line with the table at https://dart.dev/interop/js-interop#next-generation-js-interop

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by atsansone** [comment]
@kevmoo : Are you okay with updating this page as the contributor outlines?

**Comment by kevmoo** [comment]
Yep! CC @srujzs who drove the work on our side

**Comment by srujzs** [comment]
I agree with this change. Just two comments though:

- We should probably still list `dart:html` (and other Web SDK libraries) and previous JS interop libraries, but mark them as legacy somehow. They still work and we haven't deprecated them, but we should let users know they are legacy. Maybe by adding `(legacy)` after them and moving them down the list?
- `package:web` may or may not make sense to include here as it's not part of the SDK and is built on a web-specific library.

**Comment by jarrodcolburn** [comment]
> - `package:web` may or may not make sense to include here as it's not part of the SDK and is built on a web-specific library.

I agree it's maybe not ideal to add package:web, but maybe even less ideal to exclude. Speaking from dev experience and given the context of the doc. For precedence, package:js is already listed, so they maybe have already run into same dilemma with js previously.

**Comment by srujzs** [comment]
> For precedence, package:js is already listed, so they maybe have already run into same dilemma with js previously.

Good point - I'm okay including `package:web` based on this then.

**Comment by MaryaBelanger** [comment]
This was fixed by #5860 last week
