### ISSUE TITLE
Checking documentation changes on dart.dev

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/site-www#5726]
I read the documentation on the dart.dev site for version 2.18. Then version 2.19 was released, the documentation was partially changed.

I'd like to know what exactly has changed. How can i do this?

Is it possible to add at least for the latest version a tab to show links to changes in the documentation on dart.dev? And when you click on a link, highlight changes?

**Comment by atsansone** [comment]
@gmb119943 : Thank you for bringing this to our attention. At this time, the Dart docs website doesn't call out which pages changed with each version. We do note what changes happened with the language in the [Language Evolution page](https://dart.dev/guides/language/evolution), which should include links to changed documentation. Hope that helps!
