### ISSUE TITLE
Clarify 'Constructors' warning & example

### ISSUE THREAD

**Issue by dtonhofer** [dart-lang/site-www#5728]
### Page URL

https://dart.dev/language/constructors/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/language/constructors.md

### Describe the problem

# Confusing warning

At 

https://dart.dev/language/constructors

we find the following highlighted remark:

> Use `this` only when there is a name conflict. Otherwise, Dart style omits the this.

For clarity, one should add that:

> For the generative constructor however, you *must* prefix the _initializing formal parameter_ name with `this.`.

# Confusing initialization in example code

Example code is given as:

~~~
class Point {
  double x = 0;
  double y = 0;

  // Generative constructor with initializing formal parameters:
  Point(this.x, this.y);
}
~~~

However, the explicit initialization of `x` and `y` to 0 is confusing, as "it does nothing". The values are immediately overwritten by the generative constructor.

Maybe one should show the two (or three) possibilities:

Example with initialization determined directly at the line of field definition:

~~~
class PointA {
  double x = 1.0;
  double y = 2.0;

  // The parameterless constructor is not even be needed to set to (1.0,2.0)
  PointA();

  @override
  String toString() {
    return "PointA($x,$y)";
  }
}
~~~

Example with mandatory initialization via constructor:

~~~
class PointB {
  double x; // must be set in constructor
  double y; // must be set in constructor

  // Generative constructor with initializing formal parameters
  PointB(this.x, this.y);

  @override
  String toString() {
    return "PointB($x,$y)";
  }
}
~~~

Constructor which may or may not set to non-null value:

~~~
class PointC {
  double? x; // null if not set in constructor
  double? y; // null if not set in constructor

  // Generative constructor with initializing formal parameters
  PointC(this.x, this.y);

  @override
  String toString() {
    return "PointC($x,$y)";
  }
}
~~~

And thus:

~~~
void main() {
  print(PointA());
  print(PointB(2.4,4.7));
  print(PointC(null,6.67));
}
~~~

Result:

~~~
PointA(1.0,2.0)
PointB(2.4,4.7)
PointC(null,6.67)
~~~

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by munificent** [comment]
Yeah, this page is pretty confusing.

> we find the following highlighted remark:
> 
> > Use `this` only when there is a name conflict. Otherwise, Dart style omits the this.
> 
> For clarity, one should add that:
> 
> > For the generative constructor however, you _must_ prefix the _initializing formal parameter_ name with `this.`.

Another option is to change the sentence to something like "Use `this.` before a field inside the constructor body only when there is a name conflict."

As you note, using `this.` *in a parameter list* has a separate meaning and isn't optional there to get what you want.

> Example code is given as:
> 
> ```
> class Point {
>   double x = 0;
>   double y = 0;
> 
>   // Generative constructor with initializing formal parameters:
>   Point(this.x, this.y);
> }
> ```
> 
> However, the explicit initialization of `x` and `y` to 0 is confusing, as "it does nothing". The values are immediately overwritten by the generative constructor.

I agree this example doesn't work well. It's trying to show two features at the same time—initializing fields at their declaration and initializing formals—but those features are in conflict. It's probably better split up as two separate examples.
