### ISSUE TITLE
Import imports for web apps

### ISSUE THREAD

**Issue by zoechi** [dart-lang/site-www#573]
[#916](https://github.com/dart-archive/www.dartlang.org/issues/916) was closed but the document that was supposed to fix it doesn't seem to be available anymore

I found it in https://github.com/dart-archive/www.dartlang.org/blob/master/src/site/polymer-old/app-directories.markdown but it's not available on the website. 

Also https://www.dartlang.org/tools/pub/package-layout#public-assets doesn't seem to explain it well enough.

> Also, avoid imports of package:package_name/src/....

I think this is misleading. This is only true if `package_name` is not the current package.

> Warning: Old code might refer to assets using /packages/<package>/<path>

I think the leading `/` is an error and as far as I know `packages/<package>/<path>` is still a valid import even though the `packages` directory doesn't exist anymore (please correct me if I'm wrong)
Please explain how to do such imports that work with `dart2js` and DDC 

See also https://stackoverflow.com/questions/48761411

**Comment by lrhn** [comment]
>> Also, avoid imports of package:package_name/src/....
> I think this is misleading. This is only true if package_name is not the current package.

Inside the package you can use a relative path. That makes it a good rule-of-thumb that if you have `package:.../src/` then you are probably messing with the private parts of another package. There still might be good reasons (like two co-developed packages that are "friendly" with each other).

The `packages/.../` import depends on the *deployment* layout. It's very likely that we'll keep this layout for web/JS compiled applications, but it's not something that's formally specified anywhere, and it's also quite possible to have make some kind of optimizing deployment tool that rearranges the files and tree-shakes unneeded resources.

**Comment by zoechi** [comment]
> Inside the package you can use a relative path. That makes it a good rule-of-thumb 

Right. I just think pointing out the exceptions like package imports within the current package and your example about co-developed packages could prevent confusion. 

There is also a linter rule that checks such imports to other packages.
