### ISSUE TITLE
[PAGE ISSUE]: 'Class modifiers': A summary table would make this so much easier to understand

### ISSUE THREAD

**Issue by Hixie** [dart-lang/site-www#5733]
### Page URL

https://dart.dev/language/class-modifiers/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/language/class-modifiers.md

### Describe the problem

I often find myself trying to figure out what combination of class modifiers to use to get the effect I want. Right now, I often end up giving up and not bothering. It would be so useful if there was a table that summarised this page, with the all the possible combinations of class modifiers in the first column, and then columns saying for each one whether it allows mixing in, extending, implementing, etc.

**Comment by MaryaBelanger** [comment]
@Hixie I'm not sure it solves the "all the possible combinations" question, but what about [this page](https://dart.dev/language/modifier-reference)? Maybe adding more combinations?

**Comment by Hixie** [comment]
Oh yeah that's exactly what I had in mind. Thanks!

**Comment by MaryaBelanger** [comment]
You brought up a good point though; I opened an issue to clarify that we do have that resource from the landing page. Thank you!
