### ISSUE TITLE
Install link should be more prominent on the home page

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#576]
If I'm in a hurry I'd like to be able to visit dartlang.org and ctrl-f "install" and find what I'm looking for.

**Comment by chalin** [comment]
FYI, related discussion: https://github.com/dart-lang/site-www/pull/533#discussion_r164211184.

**Comment by chalin** [comment]
cc @kwalrath @anders-sandholm - should we reopen the discussion?

Maybe we can reinstate the frontpage install button, but have a more prominent warning for Flutter users on the [install](https://www.dartlang.org/install) page? There is a warning now on that page, it just doesn't stick out.

**Comment by natebosch** [comment]
Ah, so this was intentional.

Since the link doesn't expand linewise comments:

@kwalrath - 
> The problem with having the install button there is that you don't want to install Dart that way if you use Flutter.

This makes sense, but I wonder if there is another compromise.

This came up in the gitter channel as a point of confusion.

**Comment by kwalrath** [comment]
If you really just want to be able to Ctrl-F "Install", then we could add an "Install the Dart SDK" link to the footer. Then it'd be on every page.

An alternative (or addition?) is to add back the Install button that takes you to https://www.dartlang.org/install, and make the Flutter stuff much more inviting/obvious (use a logo, e.g.).

@anders-sandholm, what do you think?

**Comment by anders-sandholm** [comment]
I'm happy with either. Why not both? :-)
