### ISSUE TITLE
Effective Dart Design page is not loading CSS

### ISSUE THREAD

**Issue by ninachen** [dart-lang/site-www#577]
**To reproduce**
Open https://www.dartlang.org/guides/language/effective-dart/design

**Expected**
Loads normally.

**Actual**
no has CSS

*Top of page*
![image](https://user-images.githubusercontent.com/6378241/36236983-1139e0f8-11ae-11e8-8372-73574ba3dc1f.png)

*Scrolled down*
![image](https://user-images.githubusercontent.com/6378241/36237019-4239a378-11ae-11e8-87ac-32ae63a2017d.png)

I can see the network request to load the CSS has 404ed in the console.
Request URL: https://www.dartlang.org/assets/style-49b15a079291b882826a4cf279523e83fa67e31017c18d97bca2d7254a977ea7.css
Request Method: GET
Status Code: 404 

Was able to reproduce in incognito and other computers. Was not able to reproduce on any other Effective Dart pages besides "Design."

**Comment by chalin** [comment]
Thanks for reporting this issue. Now and again (e.g., see #456) we see similar problems, and we are still trying to track down the cause.

The page loads fine for me. I'm just curious, which region (continent or country) are you attempting to access the page from?

At the bottom of site pages, you'll see a tool icon:
> <img width="164" alt="screen shot 2017-12-04 at 18 31 11" src="https://user-images.githubusercontent.com/4140793/33582068-6713b3fc-d921-11e7-839e-f9c75ff1d9e6.png">

If you hover over the tool icon, what build info do you see?

cc @kwalrath @kevmoo

**Comment by ninachen** [comment]
Tool icon: "Site built on 2018/02/09 20:40 UTC"

Per #456, yes, it seems like CDN issue. I and someone else -- both located in Southern California -- can reproduce this issue in Chrome on three different computers, in incognito and with cleared caches.

I asked two other people in Northern California and Washington state, respectively, if they could reproduce, which they could not, even with cleared caches.

**Comment by chalin** [comment]
Are you still seeing the problem? (I've had to deploy an update, and a redeploy usually makes these sorts of problems go away.)

**Comment by ninachen** [comment]
Looks to be working now. "Site built on 2018/02/15 06:32 PST"

![image](https://user-images.githubusercontent.com/6378241/36266281-f5c1267e-1225-11e8-81f4-0054a1e47889.png)

**Comment by chalin** [comment]
Thanks!
