### ISSUE TITLE
Add recommendations for designing/implementing libraries

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#58]
_From @kwalrath on December 14, 2015 22:25_

This could be a job for https://effective-dart-dot-dart-lang.appspot.com/effective-dart/design/. If not, we could put it in some other doc as an example of one way to go. It's already used in many examples, but it seems appropriate to provide docs so people don't have to infer from the source code.

Some examples of what we might recommend (off the top of my head; this is not a complete or final list):
- AVOID using `part`.
- DO place implementation libraries under lib/src.
- PREFER providing one or more top-level libraries that export implementation libraries.

You get the idea.

_Copied from original issue: dart-lang/www.dartlang.org#1537_

**Comment by Sfshaza** [comment]
_From @kwalrath on December 14, 2015 22:25_

cc @Sfshaza

**Comment by Sfshaza** [comment]
still valid

**Comment by munificent** [comment]
I added a couple of guidelines relevant to this:

> DON’T import libraries inside the src directory of another package.

The guideline for `part` mentions not everyone likes them.

If it's OK, I'm going to close this bug since it's a little too broad to be actionable beyond that.
