### ISSUE TITLE
'Language Tour' seems to be broken

### ISSUE THREAD

**Issue by szepeshazi** [dart-lang/site-www#580]
https://www.dartlang.org/guides/language/language-tour

Referenced stylesheet can't be loaded, HTTP 404.

**Comment by chalin** [comment]
Thanks for the issue.
Related: #456, #577

**Comment by szepeshazi** [comment]
Location: Budapest, Hungary, Europe.

**Comment by chalin** [comment]
Are you still seeing the problem? (I've had to deploy an update, and a redeploy usually makes these sorts of problems go away.)

**Comment by szepeshazi** [comment]
No, it's working perfectly now, thanks!

**Comment by kwalrath** [comment]
I'll add this to the internal Firebase issue.

**Comment by kwalrath** [comment]
This seems to be related to a known incident: https://status.firebase.google.com/incident/Hosting/18003.
