### ISSUE TITLE
Fix typo in Instance variable section of Classes page

### ISSUE THREAD

**Issue by mattrberry** [dart-lang/site-www#5824]
### Page URL

https://dart.dev/language/classes#instance-variables

### Describe the problem

Introduced in https://github.com/dart-lang/site-www/pull/5310, the section on "instance variables" (and the other file modified in that PR) references missing `this.fieldName` in the comment. I'd have fixed this myself, but honestly I'm not sure what the comment is trying to indicate is "OK" even after looking through the commit history on that PR. I figured I'd leave removing or updating the comment to somebody else

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by MaryaBelanger** [comment]
I think I intended that `this.fieldName` be a place holder for `this.x` and `this.y`, but I can see now that that's pretty confusing so thanks for pointing it out @mattrberry!
