### ISSUE TITLE
Site sometimes appears to deploy incompletely (Firebase CDN issue)

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#584]
Internally reported at b/70287168. Workarounds:

* Add a query parameter such as `?` or `?0` (helps you but not anyone else who tries the original URL). For example:
https://www.dartlang.org/guides/language/effective-dart/design?0

* Purge the CDN copy of the page in the affected region. For example:
  `curl -X PURGE https://www.dartlang.org/guides/language/effective-dart/design`

* Redeploy the site.  
  Only committers can do this. It purges all regions' caches, but something else might break.

Related issues:

* #456 
* #577 
* #580 
* #606
* #618 (probably was https://status.firebase.google.com/incident/Hosting/18003)

**Comment by kwalrath** [comment]
We haven't seen this since March 5, when the fix went out to production.

**Comment by chalin** [comment]
Great!
