### ISSUE TITLE
Document new workspaces feature

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/site-www#5891]
* We need a page somewhere like https://dart.dev/guides/packages explaining the motivation, and mechanics of workspaces.

* Each of the `pub` subcommand pages need to be updated to explain how they interact with workspaces.
* The 'glossary' should have an entry for workspaces

Resources: 

- Design doc: https://flutter.dev/go/pub-workspace

**Comment by sigurdm** [comment]
Sg!

Let me know if you need anything explained. And also please add me as a reviewer!

**Comment by MaryaBelanger** [comment]
Update: stable feature targeted for Q4, docs will accompany silent launch of what works in Q3 (but do not advertise, disclaimer at the top).

**FAQ/notes to include on the page:**
Q: What version of Dart supports workspaces?
A: Most of the feature work is complete with (the upcoming) Flutter 3.5. The feature should mostly work with a recent dev release of 3.5, but the feature will not be considered feature complete and ready for broad adoption until after Dart 3.5.

Q: When do you expect workspaces to be feature complete?
A: The current plan is with Dart 3.6 – and the associated Flutter version.
