### ISSUE TITLE
Add section on Function type declarations to 'Functions' page

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/site-www#5901]
### Page URL

https://dart.dev/language/functions/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/language/functions.md

### Describe the problem

The [functions page](https://dart.dev/language/functions) doesn't explain `Function` type declarations.

In contrast, the [records page](https://dart.dev/language/records) does explain [record types](https://dart.dev/language/records#record-types) for example.

### Expected fix

Add some explanation about how to use `Function` type declarations. (Including defining return types, parameter types, etc).

It might also be worth mentioning Function types on the [built-in types page](https://dart.dev/language/built-in-types).

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by RikinR** [comment]
hey ! by types of functions we are talking about static , getter & setter , constructors , anonymous and lamda functions right ?

**Comment by mmcdon20** [comment]
I was referring to the type declaration for a `Function`. 

```dart
int add(int a, int b) => a + b;

int Function(int, int) f = add;
```

In the above code, `f` is the type `int Function(int, int)`.

**Comment by RikinR** [comment]
Hey ! I have submitted the PR .
