### ISSUE TITLE
[PAGE ISSUE]: 'Variables'

### ISSUE THREAD

**Issue by Kutter07** [dart-lang/site-www#5953]
### Page URL

https://dart.dev/language/variables/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/language/variables.md

### Describe the problem

https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by atsansone** [comment]
This issue doesn't appear to include any concerns with the Dart docs. Closing for now. If you have an issue with the Variables page, please file a new issue with the necessary information to affect a change.
