### ISSUE TITLE
Get transparent Flutter logo

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#596]
For places like https://www.dartlang.org/install that have a Flutter logo in a colored box (e.g. the aside added in #592).

<img width="756" alt="screen shot 2018-02-21 at 11 37 08" src="https://user-images.githubusercontent.com/4140793/36492939-5fc118e2-16fc-11e8-8d4e-2bedce5f98ee.png">

/cc @wmleler

**Comment by bcko** [comment]
Would this logo work? https://github.com/dart-lang/logos/blob/master/flutter/logo/default.svg

**Comment by chalin** [comment]
Thanks for the ping @bcko. This issue was addressed when the install pages were reworked.
