### ISSUE TITLE
Update the "Page issue" template to remove reference to icons that have been removed

### ISSUE THREAD

**Issue by aakoch** [dart-lang/site-www#6035]
### Page URL

https://github.com/dart-lang/site-www/issues/new?assignees=&labels=from.page-issue&projects=&template=1_page_issue.yml

### Describe the problem

The instructions on fixing a typo confused me. The Github template says, "Found a typo? You can fix it yourself! 1. Click on the **page icon** to the left of the **bug icon** you clicked to come to this form." (emphasis mine) Well, I didn't click on a bug icon! So, now I'm going back and looking for a page icon and can't find it. Since this is my first time visiting, I'm assuming your site used to have icons but they have since been replaced with the text "View source" and "report an issue". 

### Expected fix

It would be splendid if you could change this wording to mention the new link text instead of icons I no longer find. Thanks!

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by RedBrogdon** [comment]
Thanks for catching this, @aakoch.

@parlough, am I misremembering, or are the icons temporarily gone as part of an infrastrucutre change you're working on? I feel like I read that in a PR somewhere, but I'm not sure.
