### ISSUE TITLE
'Frequently Asked Questions (FAQ)' page issue

### ISSUE THREAD

**Issue by mir** [dart-lang/site-www#604]
From URL: https://www.dartlang.org/faq

> Google already works on a multi-language bytecode: LLVM bitcode in PNaCl
This is not true. 
https://blog.chromium.org/2017/05/goodbye-pnacl-hello-webassembly.html

**Comment by kwalrath** [comment]
Thanks for the report. Clearly, we need to update our FAQ.

/cc @kevmoo, @mit-mit @anders-sandholm

**Comment by chalin** [comment]
Closed by #842
