### ISSUE TITLE
Search on 404 page doesn't work

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#6055]
Go to https://dart.dev/not_here
Search something: `try a search`
Sends user to `https://dart.dev/search.html?cx=011220921317074318178%3Ai4mscbaxtru&ie=UTF-8&hl=en&q=try+a+search`

Should send user to `https://dart.dev/search?cx=011220921317074318178%3A_yy-tmb5t_i&ie=UTF-8&hl=en&q=try+a+search` ???

**Comment by RedBrogdon** [comment]
@parlough, do you have time to look at this in the next few days? If not, I can give it a go.
