### ISSUE TITLE
Format section does not appear in the Navigation bar, 'Effective Dart: Style' page issue

### ISSUE THREAD

**Issue by Stargator** [dart-lang/site-www#606]
From URL: https://www.dartlang.org/guides/language/effective-dart/style

**Comment by kwalrath** [comment]
Could you clarify what the issue is? I see the Formatting section in the right-hand nav bar (in Chrome):

![image](https://user-images.githubusercontent.com/2164483/36690056-0689a396-1ae6-11e8-9b96-070bdf769fe4.png)

**Comment by Stargator** [comment]
@kwalrath It wasn't there when I opened my issue :)

**Comment by kwalrath** [comment]
Very strange! It might have been an intermittent CDN issue we've been seeing. (#584) The CDN's cache would've been refreshed when we pushed the site, which often happens several times a day.

If you see something weird again, we'd appreciate you reporting it, along with your location and (if possible) a screenshot.
