### ISSUE TITLE
Open DartPad link does not work

### ISSUE THREAD

**Issue by VGerris** [dart-lang/site-www#6064]
the link pointing to https://dartpad.cn/0ca5b334ec413c084575f575e0240501 at : https://codelabs.flutter-io.cn/codelabs/from-java-to-dart/index.html#1 does not work, it says : GoException: no routes for location: /0ca5b334ec413c084575f575e0240501

**Comment by parlough** [comment]
Thanks for opening an issue to report this!

However, that mirrored codelab is no longer supported and it's instructions won't work for the latest versions of Dart. Consider checking out other available Dart learning material, especially the [Dart language documentation](https://dart.dev/language). It's written in a way to be a useful reference for those familiar with a language like Java already :)

If you're curious about the code that linked to previously, you can access the underlying gist at https://gist.github.com/0ca5b334ec413c084575f575e0240501.
