### ISSUE TITLE
Add class naming conventions to the API Naming Guide

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#61]
_From @kwalrath on January 27, 2015 20:7_

_Copied from original issue: dart-lang/www.dartlang.org#1230_

**Comment by srawlins** [comment]
What conventions are intended here? Effective Dart now has a [names section](https://www.dartlang.org/guides/language/effective-dart/design#names) which I think covers everything...

**Comment by kwalrath** [comment]
Yeah, I think this is covered.
