### ISSUE TITLE
'Functions Are Fun, Part 1 - Dart Tips, Episode 6' page issue

### ISSUE THREAD

**Issue by nhosoya** [dart-lang/site-www#612]
From URL: https://www.dartlang.org/resources/dart-tips/dart-tips-ep-6

`[]` rendered as `<input type="checkbox">`.

## screenshot
![image](https://user-images.githubusercontent.com/1357608/36721887-7f71c63a-1bef-11e8-84e8-6e14c16a9024.png)

**Comment by chalin** [comment]
Thanks for noticing and reporting that!
