### ISSUE TITLE
Yellow is not a primary colour

### ISSUE THREAD

**Issue by dmcg** [dart-lang/site-www#6170]
### Page URL

https://dart.dev/language/patterns/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/language/patterns.md

### Describe the problem

Change yellow to green.

And no I can't fix it myself, because I tried and there is some gubbins around Google CLA and not accepting pull requests and its all pretty shit

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by MaryaBelanger** [comment]
Closing along with #6169
