### ISSUE TITLE
"Error 503 Success" on website pages

### ISSUE THREAD

**Issue by DanTup** [dart-lang/site-www#618]
I can't load any of these pages:

https://www.dartlang.org/guides/language/language-tour
https://www.dartlang.org/guides/get-started
https://www.dartlang.org/install
https://www.dartlang.org/install/archive

They give:

```
Error 503 Success
Success

Guru Mediation:
Details: cache-lhr6348-LHR 1519812846 2337442931

Varnish cache server
```

The homepage loads ok though!

**Comment by DanTup** [comment]
Ugh, what... works fine in Edge, but bad in Chrome (including in Incognito with no extensions/cookies etc.)

**Comment by DanTup** [comment]
Left is normal Chrome, failing... right is Incognito working.

![error](https://user-images.githubusercontent.com/1078012/36783530-39e0f7a0-1c74-11e8-8898-76f695ce7736.png)

**Comment by DanTup** [comment]
In dev tools on the "Clear Storage" tab I have everything ticked and clicked "Clear site data", yet still it fails to load on a force-refresh. Still works in Incognito. I'm baffled. Here's a new screenshot showing normal/incognito with the (request) headers all looking the same to me?

![broken](https://user-images.githubusercontent.com/1078012/36783803-24076706-1c75-11e8-95ae-aa420c247c84.png)

**Comment by DanTup** [comment]
Actually, I had it broken in Incognito mode just now, so I think it's flaky (though hitting refresh a bunch doesn't make it look that way!)

**Comment by chalin** [comment]
Hi Danny, thanks for the detailed feedback. I've also noticed some flakiness with Incognito, but in this case maybe you are hitting #584. Would you mind trying one of the solutions proposed there and letting me know if that helps?

cc @kwalrath

**Comment by DanTup** [comment]
Adding a query string doesn't help :(

I have two windows open side-by-side - one in incognito and one normal, one is broken, one is fine - hitting refresh endlessly in each one produces the same content (always the error in one, never in the other). If I restart my browser, there's a chance it works and if it does, it's always good, but if it doesn't, it's always bad.

It feels a little like there's a broken server and sticky load balancing means once you hit it you're stuck with it until you get a new session. However, there are no cookies in my requests in Incognito so if that's what's happening, I'm not sure what the stickiness would be based on (I also don't know whether there is any such load balancing/stickiness, I'm just thinking out loud).

**Comment by chalin** [comment]
Does `curl -X PURGE ...` have any effect?

**Comment by DanTup** [comment]
I'm on Windows and apparently PowerShell's equiv of `curl` doesn't like custom methods:

```text
M:\Coding\Applications\Dart-Code [master ≡]> Invoke-WebRequest -Method 'PURGE' https://www.dartlang.org/install/archive
Invoke-WebRequest : Cannot bind parameter 'Method'. Cannot convert value "PURGE" to type "Microsoft.PowerShell.Commands.WebRequestMethod". Error: "Unable to
match the identifier name PURGE to a valid enumerator name. Specify one of the following enumerator names and try again:
Default, Get, Head, Post, Put, Delete, Trace, Options, Merge, Patch"
```

However... since the error seems to be sticky within a session, I'm not sure if it'd make a reliable test (since I don't know if it'd hit the same node that's serving up the errors?).

I re-read some of the related issues on that other one, and it seems they were serving 404s (not found), but these are 503s (service unavailable?) so could be unrelated.

Aaaand, ofcourse I am now unable to reproduce the issue entirely :(

**Comment by kwalrath** [comment]
Scary. I'll add this to the internal bug.

**Comment by kwalrath** [comment]
@DanTup are you in NW England right now? (It matters if it's a CDN issue.)

@chalin let's avoid updating the site, if possible, for a few hours.

**Comment by chalin** [comment]
Np, I'm working on webdev atm.

**Comment by DanTup** [comment]
@kwalrath I am indeed in NW England :)

**Comment by kwalrath** [comment]
I'm going to close this since it looks like it was due to a known outage: https://status.firebase.google.com/incident/Hosting/18003
