### ISSUE TITLE
"What's new" page has broken links to SDK changelog

### ISSUE THREAD

**Issue by srawlins** [dart-lang/site-www#6181]
The [3.3.0 link](https://dart.dev/guides/whats-new#february-15-2024-3-3-release) is correct: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#330

The [3.4.0 link](https://dart.dev/guides/whats-new#may-14-2024-3-4-release) is broken: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#340

The [3.5.0 link](https://dart.dev/guides/whats-new#august-6-2024-3-5-release) is broken: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#350

**Comment by parlough** [comment]
Thanks for calling this out @srawlins. I also opened https://github.com/dart-lang/sdk/issues/56999 to avoid this situation in the future.
