### ISSUE TITLE
Consider if any best practices for digit separators should be documented

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#6200]
Any guidance about digit separators we're confident about documenting now?

In the spec, there are a few examples of [possible lints](https://github.com/dart-lang/language/blob/main/accepted/future-releases/digit-separators/feature-specification.md#possible-new-lint-rules): like consistent separator placement and consistent use of higher grouping.

Are these things we want to mention in Effective Dart (Like "Do use digit separators consistently")? Or we could mention it in the [language tour entry](https://dart.dev/language/built-in-types#numbers:~:text=in%20Dart.-,You%20can,-use%20one%20or), at the risk of getting into too much detail there.

(The answer here is probably "not yet"/"not necessary", but just checking :))

**Comment by munificent** [comment]
It's probably not necessary. This seems like a harmless enough feature that you'd have to try pretty hard to hurt yourself misusing it but I'm glad you started the discussion. :)
