### ISSUE TITLE
Grammar mistake

### ISSUE THREAD

**Issue by kq1231** [dart-lang/site-www#6201]
### Page URL

https://dart.dev/tools/linter-rules/use_build_context_synchronously.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/tools/linter-rules/individual-rules.md

### Describe the problem

There's a grammar mistake. 

### Expected fix

Storing BuildContext for later usage can easily lead to difficult-to-diagnose crashes. Asynchronous gaps are implicitly storing BuildContext and are some of the easiest to overlook when writing code.

"difficult-to-diagnose" should be hyphenated as it is a compound adjective describing "crashes."

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by MaryaBelanger** [comment]
@bwilkerson `use_build_context_synchronously` seems to be one of those shared names you explained to me recently. So, where do we apply this fix? I'm guessing in the shared name [description in `diagnostics.md`](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/tool/diagnostics/diagnostics.md?plain=1#L29163). But I also see the [same line](https://github.com/dart-lang/sdk/blob/main/pkg/linter/messages.yaml#L13030) under `deprecatedDetails` for one of the unique names in `messages.yaml`, so I'm just making sure. Thanks!

**Comment by bwilkerson** [comment]
The source for the Diagnostic Messages page lives in [the `messages.yaml` file in the linter package](https://github.com/dart-lang/sdk/blob/main/pkg/linter/messages.yaml#L12971).

The [`diagnostic.md`](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/tool/diagnostics/diagnostics.md?plain=1#L29163) file is generated from the content in `messages.yaml`.

The `deprecatedDetails` section (also in `messages.yaml`) is what's published on https://dart.dev/tools/linter-rules/use_build_context_synchronously.

So it sounds like there are probably two places in the same file that need to be updated.

**Comment by parlough** [comment]
Resolved by https://github.com/dart-lang/sdk/pull/57093 and https://github.com/dart-lang/sdk/commit/107995fcdbe10af87ee02bfd39593e567fa59e77. Thanks all!
