### ISSUE TITLE
Problem with api docs links

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#6210]
### Describe the problem

The first two API docs links on the [async page](https://dart.dev/language/async) (`Future` and `Stream`) lead to something that looks like this:
<img width="562" alt="image" src="https://github.com/user-attachments/assets/cd3d072d-f34c-42d2-a39b-6fe36a569679">

The url shows `api.dart.dev/stable/dart-async/Stream-class.html`
Visiting those pages by following the links directly from api.dart.dev doesn't have any problems, and the link is different: `api.dart.dev/dart-async/Stream-class.html`, no `/stable`. 

I'm guessing this isn't the only page with issues, I'll check more.

### Expected fix

I think the links to api docs on the site need to be adjusted for recent updates to the api docs site.

**Comment by MaryaBelanger** [comment]
Looks like just removing `{{site.sdkInfo.channel}}` (e.g `{{site.dart-api}}/{{site.sdkInfo.channel}}/dart-async/Stream-class.html`) does the trick

**Comment by jbcormoreche** [comment]
There are also 3 links containing /stable that most likely need to be changed in the firebase.json file.
https://github.com/dart-lang/site-www/blob/main/firebase.json

You can find them at line 151, 355 and 358.
The first two lead to a 404 page, the last one already leads to the right page through a redirect but the /stable part of the link probably needs to be removed too.
