### ISSUE TITLE
'Dart Tutorials' page UI Issue

### ISSUE THREAD

**Issue by krishnatandon1208** [dart-lang/site-www#624]
From URL: https://www.dartlang.org/tutorials

![image](https://user-images.githubusercontent.com/6280870/36940483-8e484cec-1f69-11e8-9295-12806a0b3f6f.png)

The menu bar on the right side has UI issue.
#toc .nav li {
    border-left: 3px solid #111111; //must be removed.
}

**Comment by chalin** [comment]
Thanks for pointing that out. A fix is on the way.
