### ISSUE TITLE
Automatically stage the website

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#63]
_From @kwalrath on February 26, 2015 23:16_

Whenever someone creates/updates a branch of this repo, we should stage it. That would make contributing to the docs much easier for dart-lang team members. We could have a special branch (not master) that's the source for the real site (the "default" version, in App Engine speak).

I've heard that HTMLRocks does automatic staging, using WebHooks & Travis.

@sethladd might have more details.

_Copied from original issue: dart-lang/www.dartlang.org#1261_

**Comment by kwalrath** [comment]
_From @sethladd on February 26, 2015 23:19_

@paulkinlan has it all set up for H5R

**Comment by kwalrath** [comment]
_From @Sfshaza on July 21, 2016 22:21_

This is easier with the new sites but we need to document it. (It's not automatic.)

**Comment by parlough** [comment]
This would be huge for contributions and reviews, especially with the complicated setup the website currently has.

This should be able to be done with Firebase and preview channels. There's a [simple guide](https://firebase.google.com/docs/hosting/github-integration) on the Firebase website and a Firebase team member wrote a longer guide [on Medium](https://medium.com/firebase-developers/the-comprehensive-guide-to-github-actions-and-firebase-hosting-818502d86c31).

Even if this is limited to `dart-lang` members and repository collaborators for security reasons, this would still be quite useful :)

**Comment by kwalrath** [comment]
I believe that someone (@chalin maybe?) tried implementing this but ran into issues. It might have been before preview channels were available.

**Comment by chalin** [comment]
Hi y'all. I did look into this a bit quite a while back. Right: I don't think preview channels existed back then. Yes this would be great to have! 🎉

**Comment by parlough** [comment]
I'm going to close this as fixed by https://github.com/dart-lang/site-www/pull/3536 🥳 

At the moment, it will only trigger for branches directly on this repository, limiting it to those who have push access. Most large changes are from dart-lang members or repository collaborators, so this should be fine for now. We could revisit this in the future if needed.
