### ISSUE TITLE
'Asynchronous Programming: Futures' page issue

### ISSUE THREAD

**Issue by malonehedges** [dart-lang/site-www#630]
From URL: https://www.dartlang.org/tutorials/language/futures

There are `<pre>` tags right before the `Handling errors` heading.

**Comment by kwalrath** [comment]
I don't see this, so I wonder if this is a manifestation of our nemesis, #584.

What geographic region are you in, @malonehedges?

Could you please try the steps in #584 to see whether that fixes the issue? (Try the query parameter first, and let us know whether that works. Then try the `curl` command, if you can.)

Thanks very much for reporting this issue!

**Comment by malonehedges** [comment]
No dice, still showing the tags after adding trying the query parameter and the `curl` command. I'm in California currently. And of course!

![image](https://user-images.githubusercontent.com/12092296/37017829-e8a30250-20c6-11e8-839e-ee34ce45838a.png)

**Comment by chalin** [comment]
Oops, my bad. This happened because of a recent change to the prettifier
plugin (that apparently is stripping off too much whitespace, and that is
affecting the markdown interpreter. I'll fix that later today. Thanks for
filing an issue about this!
