### ISSUE TITLE
Dart linux installation instructions should have instructions for pub

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#64]
_From @kevmoo on November 16, 2015 18:9_

_From @kulakowski on November 13, 2015 19:13_

https://www.dartlang.org/downloads/linux.html does not mention that pub (and dartfmt etc.) are placed in the location described in https://www.dartlang.org/tools/sdk/. Linking to the latter's instructions would be clarifying.

I came across this following the directions on http://flutter.io/getting-started/ which point to the linux installation instructions.

_Copied from original issue: dart-lang/sdk#24915_

_Copied from original issue: dart-lang/www.dartlang.org#1525_

**Comment by kwalrath** [comment]
I believe this issue is obsolete. Looks like all the info is there now.
