### ISSUE TITLE
Contributing with translations

### ISSUE THREAD

**Issue by leocavalcante** [dart-lang/site-www#645]
Haven't found any good resources on Dart in pt-BR, I can get by, but I see some fellow countrymen (and anyone) with english difficulties get this barrier.

There is a official way to contribute with translations?
Can I just fork this repo and start translating?
Can I register the dartlang.org.br domain?

Thanks!

**Comment by kwalrath** [comment]
Hi, @leocavalcante. Thanks for asking! We're in the midst of doing a big update, so now's not a good time to fork. I believe that @filiph is looking into the site infrastructure, so maybe he has something more helpful to say.

**Comment by filiph** [comment]
Hi @leocavalcante, thanks for asking! I agree with Kathy that now's not a good time, we'll probably be changing infra or at least merging our website github repos into one monorepo (for easier sharing of resources).

Translating the whole site is quite an undertaking, as you must know. Were you thinking about only translating some major parts? Maybe it makes sense to do something like http://dartlang.cz/, which is just a small subset, and its own thing (it doesn't depend on anything on our site). 

Another (probably stupid) idea: look at Google Translate output ([homepage](https://translate.google.com/translate?sl=auto&tl=pt&js=y&prev=_t&hl=en&ie=UTF-8&u=dartlang.org&edit-text=&act=url), [tour](https://translate.google.com/translate?hl=en&sl=en&tl=pt&u=https%3A%2F%2Fwww.dartlang.org%2Fguides%2Flanguage%2Flanguage-tour), ...) and offer better translation. I _think_ the better translations should be automatically used by Google Translate (but we'd have to check). Also, I just looked at the output and it looks like Translate is trying to translate the code itself, which probably makes this a bad idea.

In any case, feel free to register a domain, and please keep us posted. If you choose to make the site, and once it crosses some (yet undefined) quality threshold, we'll be more than happy to link to you.

**Comment by leocavalcante** [comment]
Awesome, so I'll be porting part of Install, Overview and Tour guides to https://crowdin.com/ then making the translated content available through some .br domain. Thank you.
