### ISSUE TITLE
'Effective Dart: Style' page issue: No information on how to style methods.

### ISSUE THREAD

**Issue by jyaif** [dart-lang/site-www#647]
From URL: https://www.dartlang.org/guides/language/effective-dart/style

No information on how to style methods. UpperCamelCase or lowerCamelCase?

**Comment by lrhn** [comment]
I believe that is covered by the default case of [lowerCamelCase for everything else](https://www.dartlang.org/guides/language/effective-dart/style#do-name-other-identifiers-using-lowercamelcase).

**Comment by jyaif** [comment]
I see, thanks.
I did a "ctrl-f" with "method" and did not find this section. Would you be OK with me changing:

> Class members, top-level definitions, variables, parameters, and named parameters should capitalize the first letter of each word except the first word, and use no separators.

to

> Class members, **_methods_,** top-level definitions, variables, parameters, and named parameters should capitalize the first letter of each word except the first word, and use no separators.

?

**Comment by lrhn** [comment]
Personally (but I'm not the maintainer of this repository) I'd be slightly wary at that phrasing.
The current text is correct in that "Class members" covers both static and instance methods, variables, getters and setters. Singling out `method` here could be confusing ("why are methods mentioned again?", "What does 'members' cover then?").

Maybe:

> Class members (methods, variables, getters, setters and constructors),  ...

**Comment by munificent** [comment]
I'm with @lrhn. I think the original wording is clearer. Even the parenthetical in the merged version of this omits fields, which might lead a reader to think that fields don't have the same naming rules as other kinds of members.
