### ISSUE TITLE
Update pub pages that reference build/server and/or transformers

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#649]
- [x] https://www.dartlang.org/tools/pub
- [x] https://www.dartlang.org/tools/pub/transformers
- [x] https://www.dartlang.org/tools/pub/assets-and-transformers

**Comment by kwalrath** [comment]
Also:
https://www.dartlang.org/tools/pub/glossary
https://www.dartlang.org/tools/pub/transformers/aggregate
https://www.dartlang.org/tools/pub/transformers/examples
https://www.dartlang.org/tools/pub/transformers/lazy-transformer

**Comment by kevmoo** [comment]
..I guess I should have put `/transformers/*` 😄

**Comment by chalin** [comment]
- [ ] `pub run` page: drop `--checked` in favor of `--preview-dart-2`

**Comment by kwalrath** [comment]
> - [ ] `pub run` page: drop `--checked` in favor of `--preview-dart-2` (once https://github.com/dart-lang/pub/issues/1807 is fixed)

`--preview-dart-2` is obsolete, right? It looks like we need to change `--checked` to `--check-asserts`, but that's not related to the original purpose of this bug...

**Comment by chalin** [comment]
> `--preview-dart-2` is obsolete, right?

I believe so.

> looks like we need to change `--checked` to `--check-asserts`

But that doesn't seem to be implemented yet:

```console
> pub run -h
Run an executable from a package.

Usage: pub run <executable> [args...]
-h, --help            Print this usage information.
-c, --[no-]checked    Enable runtime type checks and assertions.
```

> but that's not related to the original purpose of this bug...

Right. We already have an issue for that: **Update pub docs: --checked -> --check-asserts** #1059

**Comment by kwalrath** [comment]
Cool, closing this.
