### ISSUE TITLE
"Installing for server-side development on Debian/Ubuntu" do not appear to be correct.

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#65]
_From @Dejas9000 on March 25, 2015 0:38_

I have a fresh Ubuntu install (14.10).  I took the directions given at:

https://www.dartlang.org/tools/download.html#debian

and created the following script:

sudo apt-get update
sudo apt-get install apt-transport-https
sudo sh -c 'curl -k https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
sudo sh -c 'curl -k https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
sudo apt-get update
sudo apt-get install dart

The only difference between the provided instructions and my script is the addition of the -k flag for curl (because out of the box curl doesn't trust your cert.)

When I run the script, I observe the following output:

Ign http://security.ubuntu.com utopic-security InRelease
Ign http://archive.ubuntu.com utopic InRelease
Hit http://security.ubuntu.com utopic-security Release.gpg
Ign http://archive.ubuntu.com utopic-updates InRelease
Hit http://security.ubuntu.com utopic-security Release
Hit http://archive.ubuntu.com utopic Release.gpg
Hit http://archive.ubuntu.com utopic-updates Release.gpg
Ign http://ppa.launchpad.net utopic InRelease
Hit http://security.ubuntu.com utopic-security/main i386 Packages
Hit http://archive.ubuntu.com utopic Release
Hit http://security.ubuntu.com utopic-security/universe i386 Packages
Hit http://archive.ubuntu.com utopic-updates Release
Get:1 https://storage.googleapis.com stable InRelease
Ign https://storage.googleapis.com stable InRelease
Hit http://security.ubuntu.com utopic-security/main Translation-en
Hit http://ppa.launchpad.net utopic Release.gpg
Hit http://archive.ubuntu.com utopic/main i386 Packages
Hit http://security.ubuntu.com utopic-security/universe Translation-en
Hit http://archive.ubuntu.com utopic/universe i386 Packages
Hit https://storage.googleapis.com stable Release.gpg
Hit http://archive.ubuntu.com utopic/main Translation-en
Hit http://ppa.launchpad.net utopic Release
Hit http://archive.ubuntu.com utopic/universe Translation-en
Hit http://archive.ubuntu.com utopic-updates/main i386 Packages
Hit http://archive.ubuntu.com utopic-updates/universe i386 Packages
Hit https://storage.googleapis.com stable Release
Hit http://ppa.launchpad.net utopic/main i386 Packages
Hit http://archive.ubuntu.com utopic-updates/main Translation-en
Hit http://archive.ubuntu.com utopic-updates/universe Translation-en
Hit https://storage.googleapis.com stable/main amd64 Packages
Hit http://ppa.launchpad.net utopic/main Translation-en
Get:2 https://storage.googleapis.com stable/main Translation-en_US
Ign https://storage.googleapis.com stable/main Translation-en_US
Ign https://storage.googleapis.com stable/main Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1745  100  1745    0     0  13952      0 --:--:-- --:--:-- --:--:-- 14072
OK
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    95  100    95    0     0    884      0 --:--:-- --:--:-- --:--:--   887
Ign http://security.ubuntu.com utopic-security InRelease
Hit http://security.ubuntu.com utopic-security Release.gpg
**Get:1 https://storage.googleapis.com stable InRelease**
Ign https://storage.googleapis.com stable InRelease
Hit http://security.ubuntu.com utopic-security Release
Hit https://storage.googleapis.com stable Release.gpg
Hit https://storage.googleapis.com stable Release
Hit http://security.ubuntu.com utopic-security/main i386 Packages
Ign http://archive.ubuntu.com utopic InRelease
Ign http://ppa.launchpad.net utopic InRelease
Hit https://storage.googleapis.com stable/main amd64 Packages
Hit http://security.ubuntu.com utopic-security/universe i386 Packages
**Get:2 https://storage.googleapis.com stable/main Translation-en_US**
Hit http://security.ubuntu.com utopic-security/main Translation-en
Ign http://archive.ubuntu.com utopic-updates InRelease
Hit http://security.ubuntu.com utopic-security/universe Translation-en
Hit http://ppa.launchpad.net utopic Release.gpg
Hit http://archive.ubuntu.com utopic Release.gpg
Hit http://ppa.launchpad.net utopic Release
Hit http://archive.ubuntu.com utopic-updates Release.gpg
Hit http://archive.ubuntu.com utopic Release
Hit http://ppa.launchpad.net utopic/main i386 Packages
Ign https://storage.googleapis.com stable/main Translation-en_US
Ign https://storage.googleapis.com stable/main Translation-en
Hit http://archive.ubuntu.com utopic-updates Release
Hit http://ppa.launchpad.net utopic/main Translation-en
Hit http://archive.ubuntu.com utopic/main i386 Packages
Hit http://archive.ubuntu.com utopic/universe i386 Packages
Hit http://archive.ubuntu.com utopic/main Translation-en
Hit http://archive.ubuntu.com utopic/universe Translation-en
Hit http://archive.ubuntu.com utopic-updates/main i386 Packages
Hit http://archive.ubuntu.com utopic-updates/universe i386 Packages
Hit http://archive.ubuntu.com utopic-updates/main Translation-en
Hit http://archive.ubuntu.com utopic-updates/universe Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
**E: Unable to locate package dart**

So it appears there is something wrong. I suspect with the installation instructions. Please advise.

_Copied from original issue: dart-lang/www.dartlang.org#1290_

**Comment by kwalrath** [comment]
@sethladd who'd be a good person to take a look at this?

**Comment by kwalrath** [comment]
_From @sethladd on March 27, 2015 23:42_

hm, probably @sgjesse or @whesse could help verify this suggestion?

**Comment by kwalrath** [comment]
_From @luan-cestari on November 6, 2015 12:59_

Got the same problem , I tried to access the "https://storage.googleapis.com/download.dartlang.org/linux/debian" URL and I get a "NoSuchKey" error in XML format, which might be an internal errror (maybe the URL is not valid anymore due some reason)

**Comment by kwalrath** [comment]
_From @whesse on November 6, 2015 14:9_

You cannot view a cloud storage directory with the https://storage.googleapis.com URL.  You can only get an individual cloud storage object, using its complete URL.  There is an unsupported application https://gsdview.appspot.com/ application which does allow viewing a cloud storage directory, but it doesn't seem to work for gs://download.dartlang.org.  It does work with dart-archive:  http://gsdview.appspot.com/dart-archive/channels/

In general, you can't view cloud storage buckets as directories.  I'll keep working on trying to make the gsdview.appspot.com tool work for this bucket, though.

The download URL for a particular cloud storage object, like  https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list
should always work.

**Comment by kwalrath** [comment]
_From @luan-cestari on November 6, 2015 16:26_

Hi @whesse , thank you for the help and information. I downloaded the DEP file and installed it, it seems to work fine. I would just mentioned that it is just one symbolic link created in the /usr/bin/ (for dart) and there are some other tools which I was expecting to be exposed in /usr/lib/dart/bin/ (for example, pub). Maybe all the files in the dart/bin could a symbolic link.

**Comment by kwalrath** [comment]
Do we need to change the docs?

**Comment by sgjesse** [comment]
This is tracked on https://github.com/dart-lang/sdk/issues/19926, and the
reason for the Debian scripts not doing this automatically.

Maybe just update the docs to suggest adding /usr/lib/dart/bin to the PATH.

/Søren

**Comment by kwalrath** [comment]
Closing, after confirming that https://www.dartlang.org/tools/sdk#install has instructions on adding /usr/lib/dart/bin to the PATH.
