### ISSUE TITLE
Create page for build_runner

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#650]
`build_runner` (https://pub.dartlang.org/packages/build_runner) will replace `pub build`. It's intended for anyone who *uses* a builder. Anyone who *creates* a builder (using https://pub.dartlang.org/packages/build) should document how to configure the builder (if needed).

To use a builder, you'd run a command like this:

```
pub run build_runner build
```

Possible URL: /tools/build/build_runner

Even if we have to cover API, there's precedent for having tool-related package docs under /tools: www.dartlang.org/tools/pub/transformers.

/cc @kevmoo 
Related issue: #649

**Comment by chalin** [comment]
Just a reminder that we have such a page on webdev now: https://webdev-dartlang-org-dev.firebaseapp.com/tools/build_runner

**Comment by kevmoo** [comment]
This is in the dart2 staging site, right?

**Comment by kwalrath** [comment]
Patrice's page is in the Angular 5 staging site. We still need a page (or something) for build_runner in the www site.

**Comment by kwalrath** [comment]
Per https://github.com/dart-lang/site-www/pull/944#discussion_r197290295, this page should define what a builder is in a way that we can easily link to.

**Comment by kwalrath** [comment]
Page was created in #1212.
