### ISSUE TITLE
Update Dart icon, website color scheme, and design 

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-www#651]
@filiph, once you've had a chance to land the changes needed on flutter.io, it would great if you would help us get dartlang up to snuff as well on the master branch.

---

Edited by @chalin:

- [x] Logos used in site pages.
- [x] Site favicon.ico
- [x] Site social media shared images: Use new logo as og_image #832 
- [x] Examples: any use of logos, including favicon.
- [x] Delete unused `src/twitter` folder and the images it contains? Cf. https://github.com/dart-lang/site-www/issues/651#issuecomment-386271055

**Comment by filiph** [comment]
Okay. We're not ready for the Flutter change yet, but it will land sometime between now and I/O. Hope that's okay.

**Comment by JekCharlsonYu** [comment]
Can we confirm that this includes the following sites


https://pub.dartlang.org/
https://www.dartlang.org/
https://webdev.dartlang.org/

**Comment by chalin** [comment]
@filiph - if some of the resources are ready, then I can put them in the site-shared repo as a first step.

**Comment by kwalrath** [comment]
Another possibility is to put stand-ins for the final resources in the site-shared repo, so we can migrate to shared assets before the final ones are ready.

**Comment by JekCharlsonYu** [comment]
Flutter Logo change github issue:  https://github.com/flutter/website/pull/953

**Comment by chalin** [comment]
You can see below an example of what I have so far. The following changes have been made

- Font-family base matches Flutter site.
- Slight change in colors to match Flutter palette
- This uses the new logos (including the Angular logo that I reworked/colorized).

### New

<img width="1155" alt="screen shot 2018-04-25 at 17 57 24" src="https://user-images.githubusercontent.com/4140793/39275143-2dce7bf8-48b2-11e8-9fd2-d99328ba5449.png">

### Old

<img width="1157" alt="screen shot 2018-04-25 at 17 58 19" src="https://user-images.githubusercontent.com/4140793/39275167-4ad560c2-48b2-11e8-997b-4a6cd9b3e9a3.png">

**Comment by chalin** [comment]
@kwalrath, @Sfshaza - AFAICT, the images under https://github.com/dart-lang/site-www/tree/master/twitter aren't used by site-www. The logo in that folder is obsolete, so I'd like to remove the entire folder, is that ok with you?

**Comment by Sfshaza** [comment]
Sounds good to me.

**Comment by kwalrath** [comment]
I don't remember why we ever had those images.

**Comment by chalin** [comment]
Btw, we have some of those listed at the end of #637.

**Comment by chalin** [comment]
The changes are live y'all!

**Comment by chalin** [comment]
Followups: #833, #834.
