### ISSUE TITLE
Switch to Dart 2 site; link to Dart 1.x site

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#654]
Once Flutter switches to Dart 2, so will www.dartlang.org. The Dart 1.x version of the site will be temporarily available at https://v1-dartlang-org.firebaseapp.com.

---

Edit: @chalin added itemized list. Contributes to #637.

- [x] Adjust URL config values for `url`, `dev-url`, `prev-url`
  - [x] On master - #772
  - [x] On 1.x - #770
- [x] Add site-switching dropdown menu to main nav
  - [x] On master - #724
  - [x] On 1.x - #753
- [x] Add a banner to every page, similar to what we have for webdev. See @anders-sandholm request in https://github.com/dart-lang/site-www/pull/753#issuecomment-379233184
  - [x] On master - #765
  - [x] On 1.x - #764

**Comment by kwalrath** [comment]
We'll probably want an easy way of switching between the two sites until Dart 2 is on the stable channel.

**Comment by chalin** [comment]
Would you like a dropdown line on webdev?

**Comment by kwalrath** [comment]
> Would you like a dropdown (under "Language") like on webdev?

That's probably the easiest way to go. Of course, libraries are also versioned, but most of the site changes are language related. @kevmoo & @filiph what do you say? See https://webdev.dartlang.org for an example of what Patrice is proposing.

**Comment by chalin** [comment]
Switch complete! \o/
