### ISSUE TITLE
Update Sample Code page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#655]
https://www.dartlang.org/samples needs updating to:

* [x] Drop the cookbook. (#687)
* [x] Drop new/const - #870
* [x] Maybe show off other new syntax. [Could be after 2-beta2] (`Future<void>`)

/cc @anders-sandholm @leafpetersen

**Comment by kwalrath** [comment]
Note that the sitemap has https://www.dartlang.org/samples/index. If you do a web search for "Dart samples", you'll see a link to https://www.dartlang.org/samples/. They should both be https://www.dartlang.org/samples (with nothing after "samples").

**Comment by kwalrath** [comment]
I'm creating a PR to drop the cookbook, but the repo still exists (and we'll refer to it). We should either update it or delete it or let someone else have it. See https://github.com/dart-lang/dart-samples/issues/107.

**Comment by kwalrath** [comment]
Do we want to show off any new syntax? If not, we should close this issue.

/cc @filiph

**Comment by filiph** [comment]
Sorry for the long delay.

I wonder if we want to go from `Future<Null>` to `Future<void>` (I'm not 100% sure that this is applicable to the sample, though, so we'd have to test.)

Otherwise, no new syntax that I know of.

**Comment by chalin** [comment]
Related: https://github.com/dart-lang/linter/issues/1126

**Comment by kwalrath** [comment]
I believe the Sample Code page is now up-to-date.
