### ISSUE TITLE
Delete Dart Tips?

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#658]
With Dart 2, it's probably time to say goodbye to the Dart Tips videos:

https://www.dartlang.org/resources/dart-tips
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-1
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-2
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-3
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-4
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-5
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-6
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-7
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-8
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-9
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-10
https://www.dartlang.org/resources/dart-tips/dart-tips-ep-11

/cc @anders-sandholm @filiph

**Comment by filiph** [comment]
Yes please! I'd go as far as removing the YouTube videos because I still see them showing up in search results. But yeah, first step: remove their embeds from the site.

Maybe redirect `resources/dart-tips/*` somewhere else? Tour?

**Comment by kwalrath** [comment]
Either the language tour or [Get Started](https://www.dartlang.org/guides/get-started) (which links to the language tour).

**Comment by anders-sandholm** [comment]
Yes! 
Also like the idea of redirecting to the lang-tour (or Get Started - my preference would be the tour).
