### ISSUE TITLE
Update DartPad screenshots

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#659]
Once DartPad has full Dart 2 support, take new screenshots. The current screenshots are out of date because strong mode is no longer optional.

Relevant images on site-www:

- [x] /src/_guides/language/images/dartpad-ex-type-inference.png
- [x] /src/tools/images/DartPadWindow.png (PR: #731)
- [x] /src/_guides/language/images/strong-mode-ex.jpg

Affected pages:

- [DartPad](https://www.dartlang.org/tools/dartpad)
- [Strong mode FAQ](https://www.dartlang.org/guides/language/sound-faq)

**Comment by kwalrath** [comment]
DartPad no longer allows opting out of strong mode, so we need to update screenshots, even if DartPad doesn't have complete Dart 2 support.

**Comment by kwalrath** [comment]
I think the screenshots might all be up-to-date, for now, but we'll need to update them again if DartPad's appearance changes again (e.g. for Dart 2 or to indicate that it doesn't yet support Dart 2).

**Comment by chalin** [comment]
> I think the screenshots might all be up-to-date

Yes, the images were updated last week (#869). Obsolete image files were **deleted**, including the following that are mentioned above:

- dartpad-ex-type-inference.png
- strong-mode-ex.jpg

I can't find DartPadWindow.png.

> but we'll need to update them again if DartPad's appearance changes again

Close this for now and re-open if/when DartPad's appearance changes? The logo has already been updated (and the screenshot refreshed via #869). I don't expect any other (surface) changes to DartPad in support of Dart 2.

**Comment by kwalrath** [comment]
Actually, soon there's going to be a Dart version at the lower right (dart-lang/dart-pad#818).

**Comment by kwalrath** [comment]
And... the Dart version is now visible!

![image](https://user-images.githubusercontent.com/2164483/40450659-2b95b596-5e91-11e8-93f3-54cacdf5782a.png)

**Comment by chalin** [comment]
Shall we wait for it to at least show 2.0.0-dev.xx before updating images?
