### ISSUE TITLE
Review Performance page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#661]
Do we need to update https://www.dartlang.org/performance for Dart 2?

**Comment by anders-sandholm** [comment]
I'd suggest we delete this page. It was mostly created for us to have real-estate where we could show the Dart vs. JS performance chart. After we deleted that chart, the page mostly contains static/stale info. In particular, with the shift towards more AOT even for native execution the existing contents are not fully up to date. 

Also looked at analytics and it seems we have very few visits to the page. 

I'd suggest we redirect to https://www.dartlang.org/articles/dart-vm/benchmarking for now. Eventually (if/when we delete that article too) we should probably redirect to https://www.dartlang.org/dart-vm

WDYT?

**Comment by kwalrath** [comment]
SGTM.
