### ISSUE TITLE
Change /dart-2 to be a migration guide

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#662]
Once the website is all about Dart 2, what purpose does this page (https://www.dartlang.org/dart-2) have? Should it list the differences between Dart 1.x and Dart 2? Should it be redirected to something else?

/cc @anders-sandholm @kevmoo

**Comment by kevmoo** [comment]
Leave it up for – a while – track traffic.

I like the idea of having an overview of Dart1 -> Dart2 – migration guide?

**Comment by anders-sandholm** [comment]
Yes -- If we can re-purpose the page to mainly address migration guidance, then that makes sense. Could be a list of differences and then link to the v1 site as long as that is still up.

**Comment by anders-sandholm** [comment]
Inspiration for what to include in the migration guide 
https://groups.google.com/forum/#!topic/flutter-dev/H8dDhWg_c8I

**Comment by kwalrath** [comment]
The page now includes a general-purpose migration guide (plus a package migration guide) and links to Flutter and webdev migration guides.
