### ISSUE TITLE
Re-enable frontpage main example tests and "Open in Dartpad" button 

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#668]
We've dropped the use of `new` from the main example. While we can still run the analyzer over this code (w/ `--preview-dart-2`), we can no longer run tests or launch Dartpad.

- [x] Run tests, since these require a web compiler that supports optional new/const - #903
- [x] Dartpad isn't Dart 2 compatible yet.

**Comment by kwalrath** [comment]
Why does this test require a web compiler? I'd have thought we'd use the Dart VM wherever possible on site-www. (Although since this is intended to work in DartPad, I guess it makes sense to test this particular example with a web compiler.)

**Comment by chalin** [comment]
> since this is intended to work in DartPad, I guess it makes sense to test this particular example with a web compiler

Right, it is tested in DartPad as a web app.

**Comment by kwalrath** [comment]
DartPad now supports Dart 2.

**Comment by chalin** [comment]
Closed by #750, #903
