### ISSUE TITLE
Style guide should specify what should be exported by a library

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#67]
_From @donny-dont on May 12, 2015 22:48_

Its not clear from the style guide what is acceptable to export by a library.

As a contrived example lets say I have a package foo that uses a package bar.

```
// lib/foo.dart
import 'package:bar/bar.dart';

class Foo {
  void doBar(Bar bar);
}
```

If a client of Foo is likely to use doBar its not clear if there should be an `export 'package:bar/bar.dart' in foo.dart, or if the library consumer should assume that if they want to use the method that they will then need to add bar to their pubspec and import it separately.

_Copied from original issue: dart-lang/www.dartlang.org#1349_

**Comment by kwalrath** [comment]
_From @munificent on May 13, 2015 17:43_

This is probably a bit out of scope for the style guide, but I agree it would be useful to document somewhere.

(And, in this case, the answer is no, you don't generally need to export a library just because a type from it is in your public API.)

**Comment by kwalrath** [comment]
_From @donny-dont on May 13, 2015 18:5_

Yea just wasn't sure what the logic is for exporting other libraries that are outside your package. It seemed like in general it was a don't export anything outside your jurisdiction but there's no docs with guidelines anywhere.

**Comment by kwalrath** [comment]
Lasse, Florian, Natalie, Bob... they have this kind of knowledge. It'd be good to have a library design guide of some sort.

**Comment by kwalrath** [comment]
_From @donny-dont on June 18, 2015 22:31_

Article would be great too.

**Comment by kwalrath** [comment]
_From @nex3 on June 24, 2015 21:16_

> (And, in this case, the answer is no, you don't generally need to export a library just because a type from it is in your public API.)

This is true *except* when the library is in your package. You should make sure that any types defined in package-private libraries but used in your public API are exported as part of that public API.

**Comment by munificent** [comment]
This issue is pretty old, hasn't come up much, and feels a little out of scope to me for "Effective Dart". I'm going to close this unless anyone feels strongly it should be covered.
