### ISSUE TITLE
Update who uses dart

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/site-www#671]
with at least Fluter and possibly Posse/Hamilton app.

https://www.dartlang.org/community/who-uses-dart

**Comment by kwalrath** [comment]
@wmleler could you give us the details (or better yet, a PR)?

**Comment by wmleler** [comment]
Does it make sense to categorize these? For example, into
Google
Web
Flutter
Other

**Comment by kwalrath** [comment]
About categorizing... maybe. I'll open a separate issue about that.
