### ISSUE TITLE
Screenshot of "imgs/run.png" button looks tomato red, not true red

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#68]
_From @Sfshaza on August 25, 2015 16:52_

This is the screen grab of Dartpad's run button. We need to play with the color profile or something.

_Copied from original issue: dart-lang/www.dartlang.org#1446_

**Comment by Sfshaza** [comment]
For reference:
http://www.gballard.net/psd/go_live_page_profile/embeddedJPEGprofiles.html

**Comment by kwalrath** [comment]
Related: #1118

**Comment by kwalrath** [comment]
This image is no longer in our docs, now that we use the new DartPad.
