### ISSUE TITLE
Add troubleshooting note to Dart for Java Developers tutorial

### ISSUE THREAD

**Issue by norrisduncan** [dart-lang/site-www#681]
I'm going through the Into to Dart for Java Developers and section 2 says that a constructor without a body is allowed in Dart, while Dartpad is saying that it can't compile without a body for the constructor:
<img width="1643" alt="dart for java developers issue" src="https://user-images.githubusercontent.com/30136453/37560614-4a0df730-2a12-11e8-86ed-e12c5979d951.png">

**Comment by matanlurey** [comment]
You are missing a semi-colon, i.e:

`Bicycle(this.field1, this.field2, this.field3);`
`                                              ^`

**Comment by norrisduncan** [comment]
Ahhh sorry to waste your time, I am so dumb

**Comment by kwalrath** [comment]
Not dumb! We can always make the docs clearer. We appreciate all feedback!

**Comment by kwalrath** [comment]
TODO: Add troubleshooting note about what happens if you're missing a semicolon.

**Comment by kwalrath** [comment]
Done.
