### ISSUE TITLE
Delete assets related to the old flowchart

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#683]
Search for get-started-flowchart, and remove images & styles.

* src/_assets/stylesheets/_overwrites.scss
* src/_guides/images/get-started-flowchart.svg
* src/_guides/images/get-started-flowchart.png

**Comment by leahzxxz** [comment]
I can take a look if no one is working on it?

**Comment by leahzxxz** [comment]
Also: Readme starting line 106 referred to the `get-started-flowchart.png`(line 109), do we need any changes there?

**Comment by kwalrath** [comment]
It'd be great if you took this, @leahzxxz. Thanks! (I don't know about the readme. Link?)

**Comment by chalin** [comment]
@leahzxxz is referring to this (emphasis mine):

> Rerun the command with the -d option to figure out what triggered the crash. **(Hint: If the last file read is get-started-flowchart.png, then you're probably running the jekyll server, not the firebase one.)**

I would suggest simply dropping the hint.

**Comment by leahzxxz** [comment]
Cool! Do I need to fork the repo? Got an erorr when I tried pushing my branch. I have signed CLA :)

**Comment by kwalrath** [comment]
Yes, I'm pretty sure you need your own fork.

**Comment by leahzxxz** [comment]
PR: https://github.com/dart-lang/site-www/pull/737
