### ISSUE TITLE
platform-specific download pages should feature "Updating" sections

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#69]
_From @kwalrath on September 24, 2015 18:29_

When IDEs tell their users to update their version of Dart, they should be able to send them to a page that prominently features update instructions.

I don't necessarily want to separate installing from updating, so let's try adding big headings with "Updating". E.g., in https://www.dartlang.org/downloads/windows.html, "Updating using Chocolatey" could follow "Installing using Chocolatey" in the list of links at the top, and link to a new, top-level section on updating.

_Copied from original issue: dart-lang/www.dartlang.org#1470_

**Comment by Sfshaza** [comment]
_From @sethladd on September 26, 2015 14:36_

I see now... good idea!

**Comment by kwalrath** [comment]
Still a good idea. :/

**Comment by kwalrath** [comment]
The Mac version of https://dart.dev/get-dart has an "Upgrade" section (close to "Updating", but the Windows & Linux versions don't.

**Comment by kwalrath** [comment]
We could really use some help with this. Here are the files to edit:

https://github.com/dart-lang/site-www/blob/master/src/tools/sdk/_windows.md
https://github.com/dart-lang/site-www/blob/master/src/tools/sdk/_linux.md

Those files (along with the Mac one) are included by the source file for https://dart.dev/get-dart.

**Comment by atsansone** [comment]
The update instructions can be found in the [Get Dart page](https://dart.dev/get-dart). Closing this issue.
