### ISSUE TITLE
Add new/const back to homepage example

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#693]
Rumor is that optional new/const has been deferred to b3.

/cc @anders-sandholm

**Comment by lrhn** [comment]
As I understand it, we are only deferring the "implicit const" case, where an omitted prefix can be either `new` or `const`. If it's definitely `new` or definitely `const`, we do allow you to omit it already.

**Comment by kwalrath** [comment]
I've been told we need to add back `new` and `const`.
