### ISSUE TITLE
Embed analyzer error in analysis-options

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#697]
See https://github.com/dart-lang/site-www/pull/694#discussion_r176261171.

**Comment by kwalrath** [comment]
Worth a try while I can get help from the master.

**Comment by chalin** [comment]
In case you don't know / recall: https://github.com/dart-lang/site-www/tree/master/examples#new-sources explains how to update the analyzer results file.

**Comment by kwalrath** [comment]
Seems to already be embedded.
