### ISSUE TITLE
Consider adding multiple code examples to the homepage, and starting with a simpler one

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/site-www#7]
I like the current example, as it highlights many features of the language, but I think it might also be a bit overwhelming to devs who are new to dart.

It might be worth exploring using tabs or an accordion style ui to highlight multiple different code samples?

**Comment by filiph** [comment]
Good point. We purposefully wanted a single, entertaining, and quite advanced example. Maybe we went too far. Currently, a good place to read simpler code is [dartlang.org/samples](http://dartlang.org/samples).

**Comment by parlough** [comment]
This was implemented a long time ago with the Dash redesign and https://dart.dev/#try-dart which introduced multiple introductory code samples. Thanks!
