### ISSUE TITLE
Visual bug on mobile (iPad) codelab

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#71]
_From @Georgehe4 on May 25, 2015 18:2_

Device/Browser: Using chrome on the iPad Air 2
https://www.dartlang.org/codelabs/darrrt/

When scrolling to the bottom of the page, the footer sticks in the view even after scrolling up.
In the picture attached, it is not possible to scroll up to remove the footer.

Becomes fixed after waiting for auto-scroll to complete.
![11354913_10202866066412564_723444120_n](https://cloud.githubusercontent.com/assets/3150228/7800629/19f12a6e-02cd-11e5-9bbc-962acac9faa5.jpg)

_Copied from original issue: dart-lang/www.dartlang.org#1368_

**Comment by raphalvessa** [comment]
This codelab doesn't seem to exist anymore.

**Comment by chalin** [comment]
Correct, that codelab has been deprecated. Closing this issue.

**Comment by kwalrath** [comment]
It might be an issue elsewhere, but since we have no easy way to test it... Closing seems reasonable.
