### ISSUE TITLE
Remove detailed guidelines on whitespace and indentation?

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#717]
Now that we have dartfmt, I don't think it's useful to write down a bunch of detailed explicit rules on whitespace. Especially given that in some cases, dartfmt's rules are too subtle to easily capture in prose.

The style guide already says, "DO use dartfmt to format your code." What do you think about removing all of the other formatting guidelines?

**Comment by chalin** [comment]
SGTM

**Comment by munificent** [comment]
> But perhaps instead of deleting move it into a .md file under dart-lang/dart_style to document why dartfmt formats the way it does?

Yeah, that would be good. There's a long-standing issue to do that (https://github.com/dart-lang/dart_style/issues/395) that I've never had time to get to. It's tricky because in many cases, there is no easy way to summarize its behavior because it is doing global optimization for line-breaking.

I don't want to be in the situation where the docs disagree with the observed behavior and users file bugs that the implementation is "wrong" because of that.
