### ISSUE TITLE
Debian apt-get instructions should use wget not curl

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#72]
_From @rmacnak-google on October 22, 2015 20:9_

curl is not included in the default Debian distribution

curl URL --> wget -qO- URL

https://www.dartlang.org/downloads/linux.html

_Copied from original issue: dart-lang/www.dartlang.org#1497_

**Comment by Sfshaza** [comment]
_From @sethladd on October 22, 2015 21:7_

Good catch. Thank you!

**Comment by kwalrath** [comment]
We should do this. Could we get a volunteer who has Linux and can thus test the instructions?

The file to edit is https://github.com/dart-lang/site-shared/blob/master/src/tools/sdk/_linux.md.

**Comment by pandaxtc** [comment]
I can confirm that using `wget -qO-` in place of `curl` works on Ubuntu 16.04. Should I open a pull request to edit https://github.com/dart-lang/site-www/blob/master/src/tools/sdk/_linux.md?

**Comment by kwalrath** [comment]
Yes please, @pandaxtc!

**Comment by pandaxtc** [comment]
Sorry about the duplicate pull requests, I needed to update my commit with an actual email for the CLA.

**Comment by kwalrath** [comment]
Thanks, @pandaxtc!
