### ISSUE TITLE
Mention installing Dart via scoop for Windows users

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#73]
_From @sethladd on May 26, 2015 15:50_

https://github.com/lukesampson/scoop/pull/372

unsupported by the Dart team, but looks really useful for our Windows users.

_Copied from original issue: dart-lang/www.dartlang.org#1369_

**Comment by kwalrath** [comment]
_From @sethladd on May 26, 2015 15:50_

cc @kwalrath @Sfshaza

**Comment by Sfshaza** [comment]
@kevmoo, is Scoop still valid?

**Comment by kevmoo** [comment]
@Sfshaza I have no idea. Maybe look at a trends plot of them vs chocolatey?

**Comment by Sfshaza** [comment]
I've asked on G+ and folks tell me they don't use Scoop. Folks seem to use Windows Installer, Chocolatey, or Dart-Up. Closing.

https://plus.sandbox.google.com/b/109866369054280216564/+dartlang/posts/3Dn8RHycpeY
