### ISSUE TITLE
Effective Dart: Function, typedef, guidance

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/site-www#735]
I'd like to see guidance around:

* Prefer the new typedef/function type syntax
* Consider using inline function types unless the typedef is strongly needed (with examples)
* Avoid type annotating anything plain `Function` (basically `dynamic` in Dart 2)
* Avoid implementing `Function` (?)

/cc @munificent

**Comment by munificent** [comment]
> * Avoid implementing Function (?)

[That one's covered already](https://www.dartlang.org/guides/language/effective-dart/design#avoid-annotating-with-function).

> * Avoid implementing Function (?)

I don't know if you even *can* do this anymore. If I recall, Dart 2 makes that an error.

I agree on the other two.

**Comment by matanlurey** [comment]
@lrhn:

> Still, it doesn't need to be a style guide recommendation, it will be written directly on the class itself.

Most users do not read documentation, and we need the style guide to refer to best practices.
