### ISSUE TITLE
Drop "API Reference" submenu items from sidenav

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#738]
Mobile and Dart VM have "API Reference" submenu items:

> <img width="164" alt="screen shot 2018-04-03 at 17 08 05" src="https://user-images.githubusercontent.com/4140793/38276349-b6e1b970-3762-11e8-909f-d7f7f2a6cc52.png">

For mobile, I'm not sure why anyone would come to look on the dartlang.org site for a link to the Flutter API docs. I'd **suggest removing it.** The top-level mobile menu entry is already a link to an external site. It seems strange for it to have submenu items.

We're left with the "Dart VM" API, which is actually a link to the API docs for the Dart SDK libraries. Maybe the link should be moved to the [More resources](https://www.dartlang.org/dart-vm#more-resources) section of the [Dart VM](https://www.dartlang.org/dart-vm) page?

@kwalrath WDYT?

**Comment by kwalrath** [comment]
I'm fine with dropping the API links from the sidenav if we move the API docs up to the top of the "Other resources" section of https://www.dartlang.org/guides/libraries.

Having API doc links in the Dart VM pages sounds fine, too. https://api.dartlang.org/dev is reasonably clear about which libraries the VM supports, thanks to the new categories in the side nav. I'm wondering if the API docs should label the top group... it's hard to describe which libraries you can use in web apps, except by saying "non-VM" (and vice versa). Maybe that's enough, though.

**Comment by chalin** [comment]
> if we move the API docs up to the top of the "Other resources" section of https://www.dartlang.org/guides/libraries.

Good idea.

>  I'm wondering if the API docs should label the top group... it's hard to describe which libraries you can use in web apps, except by saying "non-VM" (and vice versa)

I agree. I've shared this concern via https://github.com/dart-lang/dartdoc/issues/1118.
