### ISSUE TITLE
Lambdas can be better than tear-offs

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#74]
_From @nex3 on October 28, 2015 22:54_

[This usage note](https://www.dartlang.org/effective-dart/usage/#dont-create-a-lambda-when-a-tear-off-will-do) says "DON’T create a lambda when a tear-off will do", but tear-offs have one important flaw: they don't add a stack trace entry.

This means that if you write something like `stream.listen(sink.add)` and `sink.add` throws an error, the line of code that actually hooked the stream up to the sink—which is likely to be the actual source of the error—doesn't appear on the stack trace at all. On the other hand, if you wrote `stream.listen((value) => sink.add(value))`, it would show up.

Given this, I think we should at least soften this guideline to CONSIDER, and possibly omit it entirely.

_Copied from original issue: dart-lang/www.dartlang.org#1503_

**Comment by Sfshaza** [comment]
_From @munificent on October 29, 2015 23:17_

Whoa, I had no idea.

That sounds to me like something we should try to fix in our tooling and not something users should have to make their code more verbose to work around.

**Comment by Sfshaza** [comment]
_From @nex3 on October 29, 2015 23:57_

That would be awesome, but unless we expect that to happen very soon we should still probably ease up on the language in the guide.

**Comment by munificent** [comment]
On further thought, I don't think we should encourage users to add unneeded lambdas in order to synthesize stack trace entries.

**Comment by nex3** [comment]
Are we tracking the improvement of stack traces here? Because otherwise, this can seriously complicate debugging in ways users may not be aware of, especially in asynchronous situations where getting accurate stack traces is already difficult.

**Comment by munificent** [comment]
> Are we tracking the improvement of stack traces here?

Not here, no. Filing a bug on the SDK repo wouldn't hurt.
