### ISSUE TITLE
Use `sdk_builds` package for archive page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#75]
_From @jakemac53 on June 10, 2015 18:8_

https://pub.dartlang.org/packages/sdk_builds should be a lot more stable than our current solution

_Copied from original issue: dart-lang/www.dartlang.org#1387_

**Comment by kwalrath** [comment]
_From @kevmoo on June 10, 2015 18:14_

In my infinite free time...

**Comment by johnpryan** [comment]
It doesn't seem like anyone is interested in maintaining this package anymore, but since we already put in the work [here](https://github.com/dart-lang/site-shared/pull/100) I'm going to just copy the entire package into dart-lang/site-shared
