### ISSUE TITLE
Copy /tools/pub/obsolete & /dart-2 from master to 1.x

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#755]
@kevmoo needs copies of these at dartlang.org so that he can announce the impending removal of pub build/serve and transformers (without pointing to a non-dartlang.org URL).

Once the master branch is www.dartlang.org again, we can remove these copies or redirect them to www.dartlang.org's copies.

**Comment by kevmoo** [comment]
`dart-2` is already live here: https://www.dartlang.org/dart-2

Am I missing something?

**Comment by kevmoo** [comment]
@kwalrath – the more I think about it. Long-term, the obsolete page should *only* be on the v1 site.

Right? Once v2 goes live?

**Comment by kwalrath** [comment]
I think /dart-2 on 1.x is out of date. (It does exist, though.)

I'm not sure about the obsolete page... I'll think about it.

**Comment by chalin** [comment]
If/once #753 is merged, then we could add a redirect rule for 1.2/dart-2 so that it sends folks to the master /dart-2 (we're doing something similar on webdev).

**Comment by kwalrath** [comment]
As long as it's a 302 redirect, that seems fine.

**Comment by chalin** [comment]
The sites have switched, shouldn't https://v1-dartlang-org.firebaseapp.com/dart-2 tell folks to visit the Dart 2 version of that page (currently it has a banner towards the top that claims that Dart 2 is "still landing").

**Comment by kwalrath** [comment]
Yes, it should. I'll do that now.

**Comment by chalin** [comment]
> shouldn't https://v1-dartlang-org.firebaseapp.com/dart-2 tell folks to visit the Dart 2 version of that page

Done:
> <img width="739" alt="screen shot 2018-06-07 at 07 51 28" src="https://user-images.githubusercontent.com/4140793/41097902-9ee20706-6a27-11e8-9621-c08f5afb8d33.png">

I don't feel that we actually need to copy and/or link `/tools/pub/obsolete`. @kwalrath, WDYT? If not, then this issue can be closed.

**Comment by kwalrath** [comment]
Agreed.
