### ISSUE TITLE
Link to barback/transformer migration guidance in /pub/obsolete.md

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#757]
Link here: https://github.com/dart-lang/build/blob/master/docs/from_barback_transformer.md

Needs improvement, but it's a start...

**Comment by kevmoo** [comment]
This is a start: https://github.com/dart-lang/build/blob/master/docs/from_barback_transformer.md

**Comment by kwalrath** [comment]
Fixed by #1640.
