### ISSUE TITLE
Guidelines for Doc Comments request

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#78]
_From @dvorapa on July 26, 2015 12:33_

Guidelines for Doc Comments article should contain some information about linking to the library from the library itself. Example from the dart:html Document class documentation:

    /// Each web page loaded in the browser has its own [Document] object, which is
    /// typically an [HtmlDocument].

The `[Document]` links to the same documentation page, where it is (the link goes nowhere). 
See https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:html.Document for live example

_Copied from original issue: dart-lang/www.dartlang.org#1417_

**Comment by Sfshaza** [comment]
Periodically (in the past) our method of linking to the API docs has changed. I'm not sure if this is what caused the broken link on the Document page as reported by dvorapa. The link is fine now and linking to a doc page from itself is no different than anywhere else. Closing, but please re-open and provide more info if I'm missing something here.
