### ISSUE TITLE
Typos `chcolatey` => `chocolatey` and `run,` => `run` on windows install page

### ISSUE THREAD

**Issue by ijneb** [dart-lang/site-www#784]
https://github.com/dart-lang/site-www/blob/type-annotations/src/tools/sdk/_windows.md

**Comment by chalin** [comment]
Thanks for the issue! Would you be willing to make the edits yourself? Just click the pencil in the [_windows.md](https://github.com/dart-lang/site-www/blob/type-annotations/src/tools/sdk/_windows.md) page:
> <img width="160" alt="screen shot 2018-04-12 at 12 17 16" src="https://user-images.githubusercontent.com/4140793/38690187-8600c8d8-3e4b-11e8-985a-aafa95a69dce.png">

**Comment by ijneb** [comment]
Done, thanks: https://github.com/dart-lang/site-www/pull/786

**Comment by kwalrath** [comment]
Reopening until we accept the PR.

**Comment by chalin** [comment]
Closed by #792
