### ISSUE TITLE
Update "obsolete" pages

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#787]
For every page marked obsolete:

* Consider deleting it.
* If we leave it, add a note describing why it's still around and/or where they can find the most up-to-date information.

This came up because someone in Gitter noticed that https://www.dartlang.org/articles/language/await-async was obsolete, and was asking where to get the new information.

**Comment by kwalrath** [comment]
Obsolete articles are marked with `obsolete: true` in their YAML header. ([search](https://github.com/dart-lang/site-www/search?l=Markdown&q=%22obsolete%3A+true%22&type=))

**Comment by kwalrath** [comment]
See also #663.

**Comment by parlough** [comment]
I'm going to close this issue in favor of https://github.com/dart-lang/site-www/issues/663 which covers the same issue. Thanks!
