### ISSUE TITLE
Sitemap contains pages ending in .html and /

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#797]
If you go to https://www.dartlang.org/sitemap.xml and search for **.html**, you'll see a bunch of pages with that suffix. There are also pages with a **/** suffix.

Nothing on this site should have a .html or / suffix.

```
Downloads$ grep ".html" sitemap.xml 
<loc>https://www.dartlang.org/dart-2.html</loc>
<loc>https://www.dartlang.org/tools/pub/environment-variables.html</loc>
<loc>https://www.dartlang.org/tools/pub/glossary.html</loc>
<loc>https://www.dartlang.org/install.html</loc>
<loc>https://www.dartlang.org/tools/jetbrains-plugin.html</loc>
<loc>https://www.dartlang.org/tools/pub/cmd/pub-get.html</loc>
<loc>https://www.dartlang.org/search.html</loc>
$ grep "/</loc>" sitemap.xml
<loc>https://www.dartlang.org/</loc>
<loc>https://www.dartlang.org/dart-vm/tools/</loc>
<loc>https://www.dartlang.org/dart-vm/</loc>
<loc>https://www.dartlang.org/tools/pub/</loc>
<loc>https://www.dartlang.org/tools/sdk/archive/</loc>
<loc>https://www.dartlang.org/tools/sdk/</loc>
<loc>https://www.dartlang.org/tools/</loc>
```

Related: #796

**Comment by chalin** [comment]
Looking into this now.

site-www is using a plugin. Over on site-webdev, we dropped that plugin because we were having issues, and rolled our own sitemap.xml page. I'll do the same here.

I'll also ensure that the site version dropdown doesn't leave trailing slashes in cross-site URLs.

**Comment by chalin** [comment]
> I'll also ensure that the site version dropdown doesn't leave trailing slashes in cross-site URLs.

I've move that to #799
