### ISSUE TITLE
Clearer wording for Windows installer description

### ISSUE THREAD

**Issue by GeKorm** [dart-lang/site-www#8]
In https://www.dartlang.org/install/windows#using-a-third-party-installer
When I introduce Dart to new developers sometimes I get complaints that there's no installer. They think that the current installer is deprecated because of the "unsupported" disclaimer. Can we change that to "unofficial" or "community supported" to clear up any confusion?
The installer and bundled updater are working fine and are open source projects.

**Comment by Sfshaza** [comment]
Fixed.
