### ISSUE TITLE
Dartium path shown on "brew upgrade dart" is incorrect

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#80]
_From @sethladd on July 29, 2015 19:33_

_From @sanfordredlich on July 29, 2015 15:59_

Hi, it shows: "/usr/local/opt/dart/Chromium.app" when it should be "/usr/local/opt/dartium" because that's how the symlinks are actually set up. See output below:

| ~ @ Sanfords-MBP (sanford) 
| => brew upgrade dart
==> Upgrading 1 outdated package, with result:
dart-lang/dart/dart 1.11.1
==> Upgrading dart-lang/dart/dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.11.1/sdk/dartsdk-macos-x64-release.zip
###### ################################################################## 100.0%

==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec

--with-dartium:
  To use with IntelliJ, set the Dartium execute home to:
    /usr/local/opt/dart/Chromium.app
==> Summary
🍺  /usr/local/Cellar/dart/1.11.1: 224 files, 31M, built in 2.4 minutes

---

| /usr/local/opt/dart @ Sanfords-MBP (sanford) 
| => cd ..
total 44
lrwxr-xr-x  1 sanford  admin    23B Nov  8  2014 autoconf -> ../Cellar/autoconf/2.69
lrwxr-xr-x  1 sanford  admin    21B Jul 29 08:48 dart -> ../Cellar/dart/1.11.1
lrwxr-xr-x  1 sanford  admin    24B Jun  4 08:50 dartium -> ../Cellar/dartium/1.10.1
lrwxr-xr-x  1 sanford  admin    24B Jan 15  2015 exercism -> ../Cellar/exercism/1.9.0
lrwxr-xr-x  1 sanford  admin    19B May 30 07:10 hub -> ../Cellar/hub/2.2.1
lrwxr-xr-x  1 sanford  admin    22B Nov  4  2014 mysql -> ../Cellar/mysql/5.6.21
lrwxr-xr-x  1 sanford  admin    24B Nov  4  2014 openssl -> ../Cellar/openssl/1.0.1j
lrwxr-xr-x  1 sanford  admin    25B Nov  8  2014 pkg-config -> ../Cellar/pkg-config/0.28
lrwxr-xr-x  1 sanford  admin    21B Nov  8  2014 rbenv -> ../Cellar/rbenv/0.4.0
lrwxr-xr-x  1 sanford  admin    29B Nov  8  2014 ruby-build -> ../Cellar/ruby-build/20141028
lrwxr-xr-x  1 sanford  admin    19B Nov  7  2014 wget -> ../Cellar/wget/1.16

---

| /usr/local/opt @ Sanfords-MBP (sanford) 
| => pwd
/usr/local/opt

_Copied from original issue: dart-lang/sdk#23918_

_Copied from original issue: dart-lang/www.dartlang.org#1421_

**Comment by kwalrath** [comment]
_From @sethladd on July 29, 2015 19:33_

Thanks for the report!

**Comment by kwalrath** [comment]
This is a tool change, not a dartlang.org change, right @sethladd?

**Comment by kwalrath** [comment]
_From @sethladd on July 29, 2015 21:20_

We show this path on the "install dart sdk for mac" page, under the "Installation locations" section.

(note: I haven't verified that the suggested path in the issue is correct. It's been a while since I've used Dartium :)

**Comment by kwalrath** [comment]
I'd rather not show paths, since I tell people how to get it and the path might conceivably change...

**Comment by kwalrath** [comment]
_From @sethladd on July 29, 2015 21:22_

The paths were there before I made my tweaks. Feel free to remove the paths :)

**Comment by kwalrath** [comment]
To be clear, the page doesn't show paths. I think the user was complaining about paths displayed by the tool.

**Comment by kwalrath** [comment]
_From @sethladd on July 29, 2015 21:54_

Maybe we're talking about two different things?

![screen shot 2015-07-29 at 2 54 14 pm](https://cloud.githubusercontent.com/assets/5479/8970985/b6143e74-3601-11e5-80bf-f62f72b65aa8.png)

Are these paths accurate?

**Comment by kwalrath** [comment]
They're accurate for my installation, but mine is probably not the cleanest setup. Perhaps someone who's just installed for the first time could verify?

**Comment by branflake2267** [comment]
On my mac MacOS Sierra 10.12.3,  (`brew --prefix`) points to `/usr/local/` which makes `/usr/local/opt/dart/libexec` which will not work for the sdk directory. Chromium also does not exists there. IntelliJ figures out the version from this dart directory, but Chromium.app is missing at this location. 

`/usr/local/opt/dart/libexec points to /usr/local/Cellar/dart/1.22.1/libexec`

```
Brandons-MacBook-Pro:dart branflake2267$ brew install dart --with-content-shell --with-dartium
Warning: dart-lang/dart/dart-1.22.1 already installed
Brandons-MacBook-Pro:dart branflake2267$ 

```

**Comment by branflake2267** [comment]
It looks like several layers exist in my comment. After adding the flutter sdk to the IDE, the dart sdk path automatically changed. (I haven't found chromium in the brew instal path yet.)

![screen shot 2017-02-25 at 11 21 54 am](https://cloud.githubusercontent.com/assets/1326504/23334117/3210968c-fb4d-11e6-9525-15a489a6d56b.png)

**Comment by kwalrath** [comment]
Thanks for the details, @branflake2267.

**Comment by chalin** [comment]
Dart 2 doesn't support Dartium, and we won't be updating the 1.x branch for this.
