### ISSUE TITLE
Update & clarify docs for pubspec.yaml documentation field

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#801]
In the course of researching dart-lang/angular_components#252, I looked at the [docs for pubspec's documentation field](https://www.dartlang.org/tools/pub/pubspec#documentation). They need work.

They seem to imply that you won't get pub-generated API docs if you don't specify a blank `documentation` field. That can't be true. I looked at the file history, and this text has been there for at least 2 years, long before pub started hosting API docs.

@isoos, can you give info here about how the `documentation` field is treated?

**Comment by isoos** [comment]
Unfortunately we haven't handled this properly, e.g. if you set a proper url, pub site still ignores it, see this `TODO` block:
https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/frontend/models.dart#L202

On the plus side the missing `documentation:` entry is treated the same way as the empty, and we display the pub-generated docs. Tracking pub site implementation here: https://github.com/dart-lang/pub-dartlang-dart/issues/1214

**Comment by chalin** [comment]
Related: https://github.com/dart-lang/pub-dartlang-dart/issues/1216

**Comment by kwalrath** [comment]
Some work has been done, but the summary of this field still needs clarification.

**Comment by kwalrath** [comment]
Fixed by #1640.
