### ISSUE TITLE
 Bug when HttpClient verifying the server certificate ?

### ISSUE THREAD

**Issue by wendux** [dart-lang/site-www#804]
When I use ` HttpClient` to request  "https://www.google.com" in china ， I  was surprised to find that the response  is not the  google home page and without any error tip !  some of response content is : 
```
  <script src="https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/nocache/imgdata/seErrorRec.js"></script>
    <title>页面不存在_百度搜索</title>
    <style data-for="result">
....
```
It seems to be Http hijacking! 

Because the certificate of baidu.com is  trusted root certificate, so  the `badCertificateCallback` of `HttpClient` is not invoked。

I guess that the `HttpClient` may not verify the hostname listed in  server certificate (should assure  the request hostname is in the server certificate ) .  If this is really the fact , means all  trusted root certificate  can be used to hijacking the https request.  It will lead serious security  issue.

**Comment by kwalrath** [comment]
Not sure if this should be an [SDK issue](https://github.com/dart-lang/sdk/issues) or a doc issue (here and/or in the API docs).

@lrhn, care to comment?

**Comment by lrhn** [comment]
It should be an SDK issue, and I can see that it is now: https://github.com/dart-lang/sdk/issues/32940
I've tagged it as library-io, since any error would be in the `HttpClient` code, or in the system code backing it.
