### ISSUE TITLE
The tooltip following my mouse over the whole screen is super annoying

### ISSUE THREAD

**Issue by caguillen214** [dart-lang/site-www#815]
The tooltip that says "Intro to Dart for Java Developers" that consistently shows up over the entirety of the page is annoying. Even when you hover the Tutorial navigation links on the left it still says the same thing.

**Comment by chalin** [comment]
I'm sure it must be. I'm not seeing that behavior so: which OS and browser are you using? And just to be sure, which page(s) to you see this behavior for?

**Comment by caguillen214** [comment]
Linux & Chrome

https://codelabs.developers.google.com/codelabs/from-java-to-dart/#6 (but any of the prior pages)

**Comment by chalin** [comment]
Thanks for the link to the page. Yes, I see it (MacOS, chrome)!

**Comment by kwalrath** [comment]
The internal bug is b/69459641.

**Comment by x1ddos** [comment]
FYI in case you want to follow the progress:
https://github.com/googlecodelabs/codelab-elements/issues/28

**Comment by chalin** [comment]
@x1ddos - https://github.com/googlecodelabs/codelab-elements/issues/28 is marked as fixed, but I'm still seeing the tooltip. /cc @kwalrath

**Comment by x1ddos** [comment]
Yes, it was closed to indicate that the change has been submitted. I reopened it will close again when the change is rolled out to the public website.

**Comment by kwalrath** [comment]
We're still waiting for the fix to googlecodelabs/codelab-elements#28.

**Comment by kwalrath** [comment]
I'm not seeing this any more, so I'm going to close this. (Please comment if you still see this, and I'll re-open the bug.)
