### ISSUE TITLE
Update pubspec examples/doc

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#825]
All our templates (e.g. https://github.com/dart-lang/stagehand/blob/master/templates/console-full/pubspec.yaml) use single quotes or none in their pubspecs.

We should use the same conventions in our docs. E.g. https://www.dartlang.org/tools/pub/pubspec uses double quotes in many places (but not consistently).

~~We might also be able to remove the note in https://www.dartlang.org/tools/pub/pubspec#sdk-constraints about not using caret syntax for the SDK constraint.~~ Nope, we can't. 

/cc @Sfshaza

**Comment by Kelltimo** [comment]
Hello, I would like to help and make my first open source contribution on this! Would you recommend starting here - https://github.com/dart-lang/site-www#the-dart-language-site-wwwdartlangorg ? Thank you

Tim

**Comment by kwalrath** [comment]
Thanks for offering, @Kelltimo! You don't need to have a full build (or even your own repo) if you're just making small changes, such as changing " to ' in the pubspec page. I'd recommend starting out by editing https://github.com/dart-lang/site-www/blob/master/src/tools/pub/pubspec.md using the GitHub interface.

(Good question, btw! I should clarify that README.)

**Comment by bcko** [comment]
[args/pubspec.yaml](https://github.com/dart-lang/args/blob/master/pubspec.yaml) uses double quotes. Making a pull request to change.

**Comment by AllUsernamesHaveBeenTaken** [comment]
This issue is also done?

**Comment by kwalrath** [comment]
@AllUsernamesHaveBeenTaken it looks like the answer is yes. Thanks!
