### ISSUE TITLE
Give help on workflow when you develop both Flutter and web/command-line apps

### ISSUE THREAD

**Issue by 1fish2** [dart-lang/site-www#867]
The page https://www.dartlang.org/tools/jetbrains-plugin.html says to install a JetBrains IDE, the Dart SDK, and the Dart plugin, then create a new Dart project via the "Create New Project" dialog.

I installed the Flutter SDK -- which includes the Dart SDK -- on macOS 10.12.6, put the Flutter and Dart SDKs on the $PATH, installed the Flutter plugin for Android Studio -- which installs the Dart plugin -- and set up everything that `flutter doctor` recommended. It will successfully create and run a Flutter project, but the "Create New Project" dialog doesn't have an option to create a Dart project.

I would like to explore Dart and write programs that use the Dart VM in addition to Flutter.

Q. Do I need to install a separate copy of the Dart SDK?
Q. ... from dev channel to get 2.0?
Q. What will happen when these two SDKs don't update in sync?
Q. Is there some other setup needed to use the Dart plugin in Android Studio?
Q. Does the Dart plugin work in PyCharm Pro if not in Android Studio?

Android Studio 3.1.2, Build #AI-173.4720617.

The Flutter plugin has the correct Flutter SDK path (~/dev/flutter), and reports:

> Flutter 0.3.2 • channel beta • https://github.com/flutter/flutter.git Framework • revision 44b7e7d3f4 (3 weeks ago) • 2018-04-20 01:02:44 -0700 Engine • revision 09d05a3891 Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

The Dart plugin has the correct Dart SDK path (~/dev/flutter/bin/cache/dart-sdk) and reports

> Version 2.0.0-edge.c080951d...

**Comment by kwalrath** [comment]
Good questions. You might get a better answer on StackOverflow, but here's my understanding:

> Q. Do I need to install a separate copy of the Dart SDK?

Yes.

> Q. ... from dev channel to get 2.0?

Yes.

> Q. What will happen when these two SDKs don't update in sync?

What are you worried about happening? You can specify package version dependencies, if that helps.

> Q. Is there some other setup needed to use the Dart plugin in Android Studio?

I don't know.

> Q. Does the Dart plugin work in PyCharm Pro if not in Android Studio?

I don't know.

/cc @kevmoo

**Comment by kevmoo** [comment]
There should be no issue getting the Dart plugin working in AndroidStudio or any other JetBrains IDE. We see PhpStorm among others...

**Comment by kwalrath** [comment]
@kevmoo have you used AndroidStudio for both server-side and Flutter development? Or do you use a different IDE (or different configuration?) depending on whether you're doing server-side or Flutter dev?

**Comment by kevmoo** [comment]
I use AndroidStudio for Flutter and IntelliJ for web/server

**Comment by 1fish2** [comment]
Thanks. I filed this Issue to recommend that the webpage help people avoid these installation gotchas in addition to getting the answers.

The results:
 - brew installs dev channel Dart into `/usr/local/Cellar/dart/2.0.0-dev.55.0`.
 - The Dart plugin in PyCharm Pro can create Dart Projects. 👍
 - It automatically sets the Dart SDK path to `/usr/local/opt/dart/libexec`, which via symlink is `/usr/local/Cellar/dart/2.0.0-dev.55.0/libexec`.
 - It's not obvious that both `dart/` and `dart/libexec/` contain `bin/` directories and that `dart/libexec` is the directory to use as the SDK.
 - The Dart plugin in Android Studio does not recognize `/usr/local/opt/dart` as a Dart SDK. It will recognize `/usr/local/opt/dart/libexec` but still won't create Dart Projects. I restored this setting to `/Users/jerry/dev/flutter/bin/cache/dart-sdk`.
 - I don't know what problems could arise from having two different Dart SDKs. They aren't quite the same version. The brew installation is now on the $PATH and I removed the other.

**Comment by kwalrath** [comment]
We still aren't sure what guidance to give. Some people just use the SDK that's in Flutter, but that might not always work.

**Comment by parlough** [comment]
It seems this picture is much more clear today, with the Flutter SDK including a full Dart SDK by default, with stable releases tied together. We also now mention this on the Get Dart page and the IntelliJ instruction page.

As for the other IDE related questions, Android Studio prompts users to install the Dart plugin when installing the Flutter one, and also includes a Dart project generator which can be used. We mark other JetBrains IDEs as being supported, just with a focus on WebStorm. 

I agree we could offer more help related to paths, but I'll leave that work to more focused issues such as https://github.com/dart-lang/site-www/issues/2045.

If there's anything more specific we could still improve here, feel free to let us know or open a new issue. Thanks for all of the discussion and feedback here!
