### ISSUE TITLE
No use of line "var NEWLINE = '\n';" in Command Line example

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#87]
_From @jkleiser on November 13, 2015 11:30_

In the dcat example at www.dartlang.org/docs/tutorials/cmdline/, the line "var NEWLINE = '\n';" seems to be a leftover. If there had been any use for this NEWLINE, I think it would have been better had it been a 'const' than a 'var'.
I also find it strange that dartanalyzer fails to report unused top-level const's and var's.

_Copied from original issue: dart-lang/www.dartlang.org#1522_

**Comment by Sfshaza** [comment]
Thanks, @jkleiser, for filing this bug! It caused me to update the entire tutorial!

**Comment by jkleiser** [comment]
Great!
