### ISSUE TITLE
Codelab should tell people to remove the 'new' keyword

### ISSUE THREAD

**Issue by JeongSeongGuk** [dart-lang/site-www#876]
Hi! I'm new to Dart. So I'm doing the 'Intro to Dart for Java Developers' codelab.

I read the below sentence in first image.

 - In Dart 2, the new keyword is optional. Once DartPad is updated to Dart 2, you'll be able to say bike = Bicycle(2, 0, 1).

I followed this sentence to remove the keyword 'new', but like the second image, an error occurred.

I did not speak English well and I used Google Translator. Please understand.

![image](https://user-images.githubusercontent.com/37972432/40180329-881e7a38-5a21-11e8-84f9-6763e0d856d7.png)

![image](https://user-images.githubusercontent.com/37972432/40179393-2b7aaa2e-5a1f-11e8-8d0a-887285bd6efd.png)

**Comment by kwalrath** [comment]
Thanks very much for letting us know that you were surprised by what you read.

Unfortunately, DartPad isn't updated to Dart 2 yet. Once it is, you'll be able to remove the `new` keyword. But the example uses `new` because it's still required. I wanted to mention optional `new` because that's a feature that has started being used in Dart 2 (for example, in many Flutter examples).

Can you think of a way I could say this more clearly? Or maybe I should convince the DartPad people to show the Dart version more prominently?

**Comment by JeongSeongGuk** [comment]
I'm sorry. I had a wrong translation.

If you specify the current version of DartPad in observation(like below sentence), it will be easier for someone who can not speak English well like me to understand.

 - In Dart 2, the new keyword is optional. Once DartPad is updated to Dart 2 **(The current version of DartPad is ~)** , you'll be able to say bike = Bicycle(2, 0, 1).

Thank you!

**Comment by kwalrath** [comment]
@devoncarew I think we're going to get more problems like this as long as DartPad isn't based on Dart 2. What do you think about some sort of very visible caveat in the actual DartPad UI?

**Comment by devoncarew** [comment]
A disclaimer of some sort makes sense, in order to prevent dart 1 / dart 2 confusion. Likely in the bottom right? Any advice as to what to say?

/cc @jcollins-g, who's working on upgrading the backend to dart 2

**Comment by kwalrath** [comment]
Maybe we could just have similar to the version string from About DartPad:

**Based on Dart SDK 1.25.0-dev**

Clicking it could bring up the About dialog, just like clicking DartPad does. We might want more about the version in the About dialog. Maybe something like this (assuming there's a bug that tracks DartPad progress toward Dart 2... Is https://github.com/dart-lang/dart-services/issues/337 the best choice, or do we need a dart-pad tracking issue?):

---------------

... feedback.

DartPad is based on Dart SDK 1.25.0-dev.16.4. For the status of the Dart 2 version of DartPad, see the [tracking issue](https://github.com/dart-lang/dart-services/issues/337).

---------------

**Comment by chalin** [comment]
[DartPad now uses Dart 2 SDK, semantics](https://groups.google.com/a/dartlang.org/forum/#!topic/announce/loQ5gorIzG4)

**Comment by chalin** [comment]
@kwalrath - can we close this now?

**Comment by kwalrath** [comment]
Actually, I'm going to reopen this to remind me to update the codelab to tell people to remove the "new".

**Comment by kwalrath** [comment]
I've updated the codelab and the DartPads that it links to.
