### ISSUE TITLE
Dart 2 language changes

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#877]
Changes that we might want to integrate into the docs (Language Tour?):

- [ ] [mixin and interface are built-in identifiers](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/2qNR4-71vm0)
- [ ] [noSuchMethod mocking passes default arguments](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/qjDiBEPg8Kk)

**Comment by kwalrath** [comment]
I think #883 is all we need to close this bug. The new keywords aren't actually used yet, so we can't discuss them. And we don't cover `noSuchMethod` in enough detail to warrant talking about the change in behavior.

Some notes follow.

The following pages mention noSuchMethod:
* https://www.dartlang.org/guides/language/language-tour#nosuchmethod
* Articles marked as possibly obsolete:
  * https://www.dartlang.org/articles/language/emulating-functions
  * https://www.dartlang.org/articles/dart-vm/reflection-with-mirrors

The following pages mention mixins:
* https://www.dartlang.org/guides/language/language-tour* https://www.dartlang.org/articles/language/mixins (marked as possibly obsolete)
* https://www.dartlang.org/samples#mixins
* https://www.dartlang.org/guides/language/effective-dart/design#avoid-mixing-in-a-class-that-isnt-intended-to-be-a-mixin
* https://www.dartlang.org/guides/language/spec#changes-in-the-4th-edition

Lots of pages have the word _interface_; I won't enumerate them here.
