### ISSUE TITLE
Add download link to content_shell

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#88]
I could not find a link to the Content Shell binary. It's very useful for testing and will be a required download for the Test Runner I'm building. Maybe a link in https://www.dartlang.org/tools/download.html somewhere would be nice, or otherwise maybe in the page about testing.

Migrated from: [Issue 1164](https://github.com/dart-lang/www.dartlang.org/issues/1164). See that bug for additional comments.

**Comment by kwalrath** [comment]
Obsolete.
