### ISSUE TITLE
Document @required from the meta library

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#886]
I couldn't find this feature documented anywhere on www. Not in the library tour and not in the "commonly used library" page. It's used heavily in Flutter. It's even mentioned in [What's your Favorite Dart Feature?](https://news.dartlang.org/2016/10/whats-your-favorite-dart-feature.html)

**Comment by kwalrath** [comment]
True, I've been noticing `@required` in Flutter code. How is a Flutter developer or API developer most likely to encounter it?

**Comment by Sfshaza** [comment]
It's mostly used in class constructors. So, when they create a class
instance, it FORCES them to provide those parameters.

Also, if they write APIs, they should probably use it.

**Comment by kwalrath** [comment]
They only need to use it if names are required, correct? Which seems to be a Flutter standard, but isn't required (haha) by all APIs.

**Comment by Sfshaza** [comment]
Adding a note:
Most Flutter devs will encounter @required when creating an instance of a Flutter class. It forces certain parameters to be provided.

API devs will want to use @required when specifying classes and constructors. Where needed, they can force the user to supply certain parameter values.

**Comment by chalin** [comment]
Can you provide an Flutter example or a link to one?

**Comment by Sfshaza** [comment]
D'OH! I didn't see our other exchange when I added that last note.

You asked:
They only need to use it if names are required, correct? Which seems to be a Flutter standard, but isn't required (haha) by all APIs.

That sounds right, but you might want to confirm.

**Comment by filiph** [comment]
```
class Foo {
  Foo({Key key, @required String title});
}
```

Yes, this is only used for named parameters, and in Flutter (almost?) exclusively for constructors. The idea is that named parameters are more readable at the call site, but you want some of them to be required.

**Comment by Sfshaza** [comment]
@chalin, here's an example of where one is specified in the API:
https://docs.flutter.io/flutter/animation/AnimationController-class.html

If you are using this class in an IDE with the Flutter/Dart plugins, the analyzer gives an error until you provide it. Here an [animation example you can play with](https://github.com/flutter/website/tree/master/_includes/code/animation/animate5), if you'd like.

Just run Flutter create <myapp>, and replace lib/main.dart with that code. If your IDE has the right plugins, you can just create the project there.
