### ISSUE TITLE
Download archive should use analytics

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#89]
Moved from [Issue 1069](https://github.com/dart-lang/www.dartlang.org/issues/1069). See that issue for additional info.

**Comment by parlough** [comment]
I'm curious is this needed? I assumed analytics were tracked on the download side of things?

**Comment by kwalrath** [comment]
> I'm curious is this needed? I assumed analytics were tracked on the download side of things?

I believe they are, but I don't know if we care about the source of the download.

@mit-mit and @kevmoo, what do you say?

/cc @srawlins, who created the original issue 7 (!) years ago

**Comment by kevmoo** [comment]
I don't think we have anything to do here.

We can get raw download numbers out of google storage.

**Comment by kwalrath** [comment]
OK, I'm closing this issue.
