### ISSUE TITLE
Provide downloadable API docs in html/pdf format

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#90]
From sethladd@gmail.com on August 03, 2014 06:28:32

We generate a zip of the API docs. Users sometimes ask for an offline version of the docs. Can we make it easy to discover the docs' zip file? http://gsdview.appspot.com/dart-archive/channels/stable/release/latest/api-docs/

Migrated from [issue 933](https://github.com/dart-lang/www.dartlang.org/issues/933). See that issue for additional comments.

**Comment by Sfshaza** [comment]
The latest zip file for the docs is now available on the download archive page. Closing.

**Comment by kwalrath** [comment]
Confirmed that the download is HTML files, not whatever we used to generate.
