### ISSUE TITLE
'Dart 2' page issue - explain dart2_fix

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#900]
From URL: https://www.dartlang.org/dart-2.html

`Run the dart2_fix tool.` – include a short sub-bullet about what this does? 
Link to the pub page - https://pub.dartlang.org/packages/dart2_fix

**Comment by chalin** [comment]
@kevmoo - how about this:

> 3. Run the [dart2_fix tool](#) to automatically migrate some Dart 1.x API usages in your source code to Dart 2.

**Comment by kevmoo** [comment]
Or? "Use the dart2_fix tool to help migrate some usages of deprecated Dart 1.x API to Dart 2."

**Comment by chalin** [comment]
For sake of uniformity, all the steps should be imperative. How about:

> 3. Run the [dart2_fix tool](#). It helps migrate some usages of deprecated Dart 1.x API to Dart 2.

**Comment by kevmoo** [comment]
SGTM! – API -> APIs
