### ISSUE TITLE
Upload the new Dart logo to wikipedia

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/site-www#916]
Not sure where to file this, but [this Wikipedia entry needs updating](https://en.wikipedia.org/wiki/Dart_(programming_language)). It still mentions Dartium, checked mode, and gives short shrift to Dart 2 with its strong type checking.

**Comment by kwalrath** [comment]
I'm not sure what the etiquette is for updating info about your own project. We'll happily accept anyone's help for this. (If no one volunteers by the time Dart 2 is out, I'll do it myself.)

**Comment by Sfshaza** [comment]
Yeah, I'm not sure about that either. But it seems like a good plan.

**Comment by parlough** [comment]
The logo also needs updating.

**Comment by kwalrath** [comment]
All right, guess it's up to me.

/cc @kevmoo

**Comment by kwalrath** [comment]
I've made a few updates: https://en.wikipedia.org/w/index.php?title=Dart_(programming_language)&action=history. It looks like @parlough also contributed (thanks!).

I tried to update the logo to the one at https://github.com/dart-lang/logos/blob/master/dart/logo%2Btext/horizontal/default.svg (or another one in that directory), but I don't have the Wikipedia juice to do so. @parlough, do you?

**Comment by parlough** [comment]
@kwalrath I also got stuck trying to upload the new icon, but I was trying to upload a new version to the current one. Possibly we should just upload it in a new entry and link to that instead, or did you try that already?

**Comment by kwalrath** [comment]
@parlough I tried and failed to upload a new entry. (I haven't made enough edits to have a "confirmed account".) Like you, I first tried to replace the existing image, but realized that it'd probably be better to upload a new one.

**Comment by AllUsernamesHaveBeenTaken** [comment]
I think the logo is up to date, isn't it?

**Comment by kwalrath** [comment]
Yes, thanks for checking, @AllUsernamesHaveBeenTaken! It looks like GreenMeansGo [uploaded the new logo 19 September](https://commons.wikimedia.org/wiki/File:Dart_programming_language_logo.svg).
