### ISSUE TITLE
"Dart 1.x" -> "Dart 1" cleanup

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#927]
This cleanup was discussed a while ago, but it wasn't seen as a priority. Since then, a few instances of "Dart 1" (vs. "Dart 1.x") have slipped into the docs. It is probably time to cleanup the docs and only use "Dart 1".

**Comment by kwalrath** [comment]
I thought we wanted to continue using "Dart 1.x", not "Dart 1".
