### ISSUE TITLE
Error opening Dartpad

### ISSUE THREAD

**Issue by stuart-dragon** [dart-lang/site-www#949]
On the codelab, https://codelabs.developers.google.com/codelabs/from-java-to-dart/#1, when you open the https://dartpad.dartlang.org/0ca5b334ec413c084575f575e0240501, throws an error about the gist

**Comment by chalin** [comment]
Hi Stuart: I'm not seeing any errors.

Can you provide a screenshot? Also:

- Which browser (and its version) are you using?
- Which version of DartPad is shown in the lower right corner of the DartPad window?

**Comment by stuart-dragon** [comment]
Hi, I just retried and I didn’t get the error (both with chrome and Firefox) I’ll close the issue
