### ISSUE TITLE
Bad URL: Tools, analyzer, dartfmt , dartdoc, observatory

### ISSUE THREAD

**Issue by challe** [dart-lang/site-www#95]
URL: https://www.dartlang.org/tools/analyzer/
Expected page: https://github.com/dart-lang/sdk/tree/master/pkg/analyzer_cli#dartanalyzer

URL: https://www.dartlang.org/tools/dartfmt/
Expected page: https://github.com/dart-lang/dart_style#readme

URL: https://www.dartlang.org/tools/dartdoc/
Expected page: https://github.com/dart-lang/dartdoc

URL: https://www.dartlang.org/tools/observatory/
Expected page: https://dart-lang.github.io/observatory/

Links found via Google search

**Comment by filiph** [comment]
Thanks for the report! This is embarrassing. Fixed with https://github.com/dart-lang/site-www/commit/faf677fe387ea52d04197645781cd20dd5293cf2
