### ISSUE TITLE
Clarify codelab text

### ISSUE THREAD

**Issue by a871031791** [dart-lang/site-www#950]
all code run  in DartPad error,
And skip(1) 会忽略迭代中的第一个值
take(3)会获取接下来的 3 个值，也就是 2，3 和 4不是2,3,5

**Comment by kwalrath** [comment]
It looks like you're reporting an issue with the last step of the Java -> Dart codelab, https://codelabs.developers.google.com/codelabs/from-java-to-dart/#5. The DartPad works for me, though: https://dartpad.dartlang.org/bd0d627c9af8d264c2b3dde7c0939375

Can you clarify what you did/saw? Screenshots might help.

Thanks!

**Comment by chalin** [comment]
It seems to have been a temporary glitch: see the (now closed issue) https://github.com/dart-lang/site-www/issues/949

**Comment by kwalrath** [comment]
It also looks like the text was confusing to the reader. From Google Translate: "And skip(1) ignores the first value in the iteration. Take(3) gets the next 3 values, that is, 2,3 and 4 are not 2,3,5."

The text is correct, but I could maybe add indexes to make it clearer. (Then again, maybe it's plenty clear once the code is running. @a871031791, what do you think?)

**Comment by kwalrath** [comment]
Closing due to lack of information.
