### ISSUE TITLE
Dart tour: Factory constructors section says to use `new`, but omits it

### ISSUE THREAD

**Issue by cpelling** [dart-lang/site-www#958]
From URL: https://www.dartlang.org/guides/language/language-tour#using-constructors

The text says "To invoke a factory constructor, you use the new keyword", but the following code snippet (pasted below) does not use the `new` keyword.

var logger = Logger('UI');
logger.log('Button clicked');

**Comment by kwalrath** [comment]
Oops, good catch. We fixed all the code in the language tour to omit the optional `new`, but we missed some occurrences of `new` in the text. I'll search for them.

Thanks, @cpelling!
