### ISSUE TITLE
Point to new Chinese translation of dartlang.org

### ISSUE THREAD

**Issue by ChiQianBingYue** [dart-lang/site-www#960]
I am translating the lang tour and lib tour to Chinese.
So, I want to know if there is a way to support i18n in this website.

**Comment by kwalrath** [comment]
Thanks for asking, @ChiQianBingYue. We don't currently have i18n support, but we'll be happy to link to your translations.

There's currently a link in https://www.dartlang.org/community#additional-community-resources to [Resources for Chinese developers](http://www.dartlang.cc/support/for-chinese.html). Is anything on that page or site (http://www.dartlang.cc) still useful?

**Comment by ChiQianBingYue** [comment]
The site (http://www.dartlang.cc) looks awesome but seems out of maintenance for a long time.
I recently noticed some Chinese developer created [http://dart.goodev.org/](http://dart.goodev.org/), which is a good clone of the current https://www.dartlang.org/.  Maybe it's a good idea to link their website at dartlang.org.

**Comment by kwalrath** [comment]
Thanks very much, @ChiQianBingYue. I'll ask one of our Chinese-speaking people to look into dart.goodev.org.

**Comment by ChiQianBingYue** [comment]
You are welcome.

**Comment by kwalrath** [comment]
From one of our Chinese speaking Googlers:

> It seems that dart.goodev.org is based on a more recent version of the official dart site than www.dartlang.cc. But on the homepage of dart.goodev.org, it links to http://www.dartlang.cc and says it's old but has more Chinese resources. I think you can either link both or just dart.goodev.org since it also links to the older Chinese site. 

So I plan to link to dart.goodev.org.

**Comment by ChiQianBingYue** [comment]
Sounds good!

**Comment by kwalrath** [comment]
I'm going to keep this open to remind me to make that change.

**Comment by kwalrath** [comment]
@ChiQianBingYue it looks like the "newer" version is still way behind. Are you still willing to do a new translation?

**Comment by amisare** [comment]
I am currently translating based on the latest version. Website address https://www.dartcn.io. It may take about two or three weeks for the entire website to be translated. I hope to pay attention to it.Waiting for the website translation to complete, I hope we can exchange the links.

**Comment by kwalrath** [comment]
We'll be very happy to link to a newer translation.

**Comment by amisare** [comment]
Thank you, I will finish as soon as possible.

**Comment by amisare** [comment]
www.dartdoc.cn
Chinese website has been translated. It based on the latest version of the official website.
It will be continue to update and improve in the future.
Hope you can look into and link it.

**Comment by kwalrath** [comment]
The new link is now active at https://www.dartlang.org/community#additional-community-resources.
