### ISSUE TITLE
Dart VM -> Server

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#965]
From https://github.com/dart-lang/site-www/issues/245#issuecomment-399995210.

- [x] [Get Started page](https://www.dartlang.org/guides/get-started)
- [x] Install page - #964
- [x] [Platforms page](https://www.dartlang.org/guides/platforms)
- [x] Sidenav - all pages (when viewed from wide displays) other than the front page. #970
- [x] https://www.dartlang.org/guides/json
- [ ] Changing `/dart-vm` URLs to be `/server` (with appropriate redirects)

**Comment by kwalrath** [comment]
I'll take the sidenav right now.

**Comment by kwalrath** [comment]
I'm working on other pages right now...

**Comment by chalin** [comment]
Paths requiring renaming:
- ./src/_articles/dart-vm
- ./src/_tutorials/dart-vm
- ./src/dart-vm
