### ISSUE TITLE
Document "include" in analysis-options

### ISSUE THREAD

**Issue by avilladsen** [dart-lang/site-www#971]
The [Customize Static Analysis](https://www.dartlang.org/guides/language/analysis-options) page should document the `include:` top-level option, which lets you specify a URI (just relative path or `package:`, I think?) to import analysis options from. 

See dart-lang/sdk#32612 for context.

**Comment by chalin** [comment]
@kwalrath - I've started looking into this.

@bwilkerson wrote https://github.com/dart-lang/sdk/issues/32612#issuecomment-400832470:

> I didn't find any documentation for it...

Is there any internal doc? Regardless, what (YAML) types can the field have? E.g., must it be a string or can it be a list of strings? Any restrictions on the path (relative/absolute).

Btw, I'm seeing inconsistent behavior between the CLI analyzer and the analysis server (via WebStorm). E.g., if I `include` in invalid path, the CLI analyzer issues no warning. Is this expected?

**Comment by bwilkerson** [comment]
> Is there any internal doc?

Nothing I can think of that would be useful as a starting point. Just some documentation comments scattered throughout the code.

> Regardless, what (YAML) types can the field have?

It must be a valid URI. The URI will be resolved in the same way as URI's in import directives, relative to the containing file if it's a relative URI.

> ... the CLI analyzer issues no warning. Is this expected?

You should be able to see the warning if you explicitly include the analysis options file on the command line. I suspect that if you give the CLI analyzer a directory that it only analyzes `.dart` files.

**Comment by chalin** [comment]
@bwilkerson - thanks for the feedback.

> You should be able to see the warning if you explicitly include the analysis options file on the command line.

Interesting. I would not have thought that necessary (the CLI _has_ to read the analysis options file anyways, so why not print issues if they are encountered). Thanks for clarifying.

**Comment by kwalrath** [comment]
Fixed in #1328.
