### ISSUE TITLE
Library tour: const or no const for Durations?

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#972]
The following code appears in the [Dates and times](https://www.dartlang.org/guides/libraries/library-tour#dates-and-times) section of the Library Tour:

https://github.com/dart-lang/site-www/blob/36ea96c7d2a8857d7046df6c2b42062c52f9f716/examples/misc/test/library_tour/core_test.dart#L606-L612

Notice the two `const` `Duration`s. I'd be tempted to drop them, but chose not to do so during my last sweep.

@munificent @kwalrath @TedSander - any opinions about this?

More broadly: should we generally be promoting (via our example code) use of `const` for (immutable) types like Duration? Maybe we need a separate guideline on when to use `const` (esp. in light of issues like https://github.com/dart-lang/sdk/issues/33430, that highlight that const canonicalization is lazy, so IMHO it isn't that clear cut what the runtime cost/benefits are of using `const`).

**Comment by chalin** [comment]
Here is another example (which is meant to be focused on illustrating `Comparable`):
https://github.com/dart-lang/site-www/blob/36ea96c7d2a8857d7046df6c2b42062c52f9f716/examples/misc/lib/library_tour/core/comparable.dart#L1-L13

I'd like to drop the `const`. Any objections?

**Comment by chalin** [comment]
Another example:
https://github.com/dart-lang/site-www/blob/36ea96c7d2a8857d7046df6c2b42062c52f9f716/examples/misc/lib/library_tour/core/exception.dart#L1-L8

Drop `const` here too?

**Comment by chalin** [comment]
The following use of `const` seems like it is a good idea:
https://github.com/dart-lang/site-www/blob/36ea96c7d2a8857d7046df6c2b42062c52f9f716/examples/misc/lib/tutorial/cat_no_hash.dart#L7-L10

But again, for a simple demo program it probably won't make a difference, so shall we drop it here too?

Maybe we can we can describe selective use of creating compile-time constants as a program optimization step (that can be left until one has some performance metrics to guide the tuned use of `const` constructors against)?

**Comment by munificent** [comment]
Oof, it depends on who you ask. My understanding is that const is an important performance *improvement* on Flutter, but can be a perf *hit* on the web. I don't really know what guidance to give.

**Comment by chalin** [comment]
> const is an important performance *improvement* on Flutter, but can be a perf *hit* on the web

Intuitively, that makes sense.

As for the specific examples above, I'd like to make them more terse by dropping the `const`. Any objections to that?

**Comment by chalin** [comment]
> Dropping the `const` sgtm.

Ok I'll do that (unless @munificent speaks up against it).

Bob, event a comment along these lines is better than nothing IMHO:

> const is an important performance *improvement* on Flutter, but can be a perf *hit* on the web

**Comment by kwalrath** [comment]
Ah, I saw this after I made my comments. :) We should definitely talk about the performance implications of const somewhere.
