### ISSUE TITLE
Missing information regarding Anonymous functions in Language Tour.

### ISSUE THREAD

**Issue by jyaif** [dart-lang/site-www#977]
How does one write the type of a variable that stores an anonymous function?
How does one write the prototype of a function that takes an anonymous function in parameter?

**Comment by chalin** [comment]
The Language Tour is an introduction to Dart's core features. The [Effective Dart](https://www.dartlang.org/guides/language/effective-dart#summary-of-all-rules) pages contain a wealth of information. Particularly relevant to your questions is [Effective Dart: Design](/guides/language/effective-dart/design). 

> How does one write the type of a variable that stores an anonymous function?

See: [PREFER inline function types over typedefs.](https://www.dartlang.org/guides/language/effective-dart/design#prefer-inline-function-types-over-typedefs)

> How does one write the prototype of a function that takes an anonymous function in parameter?

See:
- [PREFER signatures in function type annotations.](https://www.dartlang.org/guides/language/effective-dart/design#prefer-signatures-in-function-type-annotations)
- [CONSIDER using function type syntax for parameters.](https://www.dartlang.org/guides/language/effective-dart/design#consider-using-function-type-syntax-for-parameters)

Also:

- [DON’T use the legacy typedef syntax.](https://www.dartlang.org/guides/language/effective-dart/design#dont-use-the-legacy-typedef-syntax)

**Comment by kwalrath** [comment]
TODO: Review whether the language tour should cover any of this, and make sure it links to Effective Dart appropriately.

**Comment by micpap25** [comment]
I'm about to make a push for this, I just have one question. Why might the CSE for search-all on this site be different from the one on the Flutter site? Aren't they supposed to show the same results? This is coming from someone who doesn't know much about the topic, I just wanted to check.

**Comment by kwalrath** [comment]
Good question! The Dart "search more" CSE has these sites:

* api.dart.dev
* dart.dev
* flutter.dev
* stackoverflow.com

The Flutter "search more" CSE is the same, but with api.flutter.dev instead of api.dart.dev. I think that makes sense because api.flutter.dev is a superset (more or less) of api.dart.dev, and it might be confusing for non-Flutter Dart devs to get results like dart:ui that aren't in the core Dart API.

**Comment by micpap25** [comment]
I'm just realizing... I accidentally commented on the wrong issue... this belongs on #2383, haha.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/1158 which also tracks this work. Thanks for opening an issue :)
