### ISSUE TITLE
Update Native Extensions article

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#980]
Followup to https://github.com/dart-lang/site-www/pull/973#discussion_r198966480 for the [Native Extensions](https://www.dartlang.org/articles/dart-vm/native-extensions) article.

- Use `<?code-excerpts?>`
- Update to Dart 2.

**Comment by chalin** [comment]
@a-siva: is there a way to invoke [`./tools/test.py`](https://github.com/dart-lang/sdk/wiki/Building#testing) to just run the `samples/sample_extension` tests? /cc @kwalrath

**Comment by chalin** [comment]
@a-siva: nm, I was able to build the extension and run the tests.

**Comment by a-siva** [comment]
sivalinuxmach[sdk]>tools/test.py -cdartk samples
Test configuration: dartk_vm_debug_x64
[00:04 | 100% | +    5 | -    0]
sivalinuxmach[sdk]>

Should do it.

**Comment by kwalrath** [comment]
#1294 fixed a link, but this article could still use a closer look and more integration/updating of its example code.

**Comment by parlough** [comment]
Now that support for this mechanism was removed and this documentation only points elsewhere, there is nothing to left to update, so closing. Thanks!
