### ISSUE TITLE
404s

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#982]
We've had a lot of 404s recently for /assets/dart-logo-wordmark-118e1af8162f4353fb6f2bb18c21b4ec3b448de7f2caf47d1c87561aaa519999.png. Any ideas, @chalin?

Over time, another top 404 (though rare in any given week) is /web-ui/observables, which appears to still be in the Google search index. I'll look into a fix for this one.

**Comment by chalin** [comment]
I suspect that the `/assets/dart-logo-wordmark-....png` comes from the time before we fixed the OG image (image used for shares via social media).

The simplest thing to do would be to add a redirect similar to the one that is already there for `/assets/dart-logo-for-shares*.png`: https://github.com/dart-lang/site-www/blob/66925530f1dcfedafce04445ee010681a6d7ae24/firebase.json#L278-L282

Do you want me to fix this one while you fix the other?

**Comment by kwalrath** [comment]
> Do you want me to fix this one while you fix the other?

Sure, SGTM.

**Comment by kwalrath** [comment]
I think /web-ui* should redirect to https://webdev.dartlang.org/guides/web-programming.
