### ISSUE TITLE
Remove link to indexed_db tutorial.

### ISSUE THREAD

**Issue by filiph** [dart-lang/site-www#99]
A link from api.dartlang.org [indexdb](https://api.dartlang.org/stable/1.17.1/dart-indexed_db/dart-indexed_db-library.html) leads to https://www.dartlang.org/docs/tutorials/indexeddb/ which has moved

**Comment by kwalrath** [comment]
I don't think that tutorial exists anywhere any more, so I'm going to transfer this bug to the sdk repo.

**Comment by kwalrath** [comment]
This issue was moved to dart-lang/sdk#35811
