### ISSUE TITLE
Remove note about whereType status

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#995]
See https://github.com/dart-lang/site-www/pull/991#pullrequestreview-136003640 and https://github.com/dart-lang/sdk/issues/32463 for details.

/cc @munificent @lrhn @Hixie

**Comment by kwalrath** [comment]
Blocked on the release of Flutter Beta 7.

**Comment by chalin** [comment]
@kevmoo et all: is this still blocked by Flutter? Can I drop the following note from the docs (now or along with Dart 2 stable) given that issue #32463 is now closed?

> **Before using `whereType()`, make sure it's implemented.** We expect `whereType()` to be added late in Dar 2 development. For details, see [SDK issue #32463.](https://github.com/dart-lang/sdk/issues/32463#issuecomment-402975456)

**Comment by kevmoo** [comment]
Yes, please!

**Comment by kwalrath** [comment]
I thought we were waiting for Flutter 0.7, which is not out yet.

**Comment by kwalrath** [comment]
I'm going to add this text back, until Beta 7 goes out.

**Comment by mit-mit** [comment]
FYI, beta 7 went out a few days ago:
https://flutter.io/sdk-archive/
