### ISSUE TITLE
Generalize type annotation guidelines

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#996]
Effective Dart used to have two general guidelines around annotating APIs:

* DO type annotate public APIs
* PREFER type annotating private declarations.

Now the corresponding rules are:

* PREFER type annotating public fields and top-level variables if the type isn’t obvious.
* CONSIDER type annotating private fields and top-level variables if the type isn’t obvious.
* PREFER annotating with dynamic instead of letting inference fail.

Since unannotated parameters and returns usually aren't inferred, I believe the effect of the new guidelines is technically the same, but it certainly ain't obvious. The best fix is probably to just generalize the first two to:

* PREFER type annotating public APIs if the type isn’t obvious.
* CONSIDER type annotating private APIs if the type isn’t obvious.

Then in the prose explain that it applies to top-level variables, fields, parameters, and return types. Explain that in the absence of an initializer, the type is basically never obvious.

**Comment by natebosch** [comment]
I think we'll need to make it clear that `something() => 1` might look obvious, but still needs the return type annotation.
